### ISSUE TITLE
Failed at the node-sass@3.1.2 postinstall script 'node scripts/build.js

### ISSUE THREAD

**Issue by EmmanuelMariki** [sass/node-sass#1001]
gyp ERR! node -v v0.12.1
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 12.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "gulp-sass" "--save-dev"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.1.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.1.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.

**Comment by saper** [comment]
@EmmanuelMariki Can you try to follow our https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md guide?

**Comment by saper** [comment]
Also, I think you need to have Darwin 12.7.0 (MacOS X 10.7) to use the pre-compiled binary. (see https://github.com/sass/node-sass/issues/693).

**Comment by EmmanuelMariki** [comment]
Thank: Am using MacOS X 10.8  how do i update Darwin fro 12.6 to 12.7  am new to MacOS X

**Comment by saper** [comment]
I am sorry, I cannot help you with that. Please contact Apple.

**Comment by mdxprograms** [comment]
I'm using 10.9 and 10.10 and get the same error.

**Comment by saper** [comment]
1.2.3 is pretty old and we did provide only Linux binaries for that.

**Comment by mdxprograms** [comment]
What is the fix for this?

**Comment by mdxprograms** [comment]
I don't think the developer should have to do the following after doing yo backbone <app_name>:
    npm install node-sass --save

**Comment by mdxprograms** [comment]
is this on generator-backbone?

**Comment by saper** [comment]
`npm install node-sass` should pick up the latest version. However, if you use some other packages to pull node-sass they might specify some older version of `node-sass` for you. Raise the issue request to those packages (check their respective `package.json` files).

**Comment by xzyfer** [comment]
`node-sass@1.2.3` was release before `node@0.12` as such it is not supported. Please update node-sass the more recent `v3`, or downgrade your node to `0.10.38`. 

There is nothing we can if you're running year old versions of node-sass or node.
