### ISSUE TITLE
Comment starting with /*! not removed

### ISSUE THREAD

**Issue by SamVerschueren** [sass/node-sass#1002]
When a comment was added that starts with `/*!` like

```css
/*!
 * This will not be removed in the output
 */
```

this comment will be kept in the output.

**Comment by saper** [comment]
That's the correct behaviour according to the Sass reference http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments What's wrong?

**Comment by SamVerschueren** [comment]
Oh sorry, my bad. I was compiling a library and didn't wanted the comments in it. Thought it was a bug but it isn't then :). My bad, will close the issue.

**Comment by saper** [comment]
Thanks, I am relieved now :)
