### ISSUE TITLE
Why do you no longer provide precompiled binaries?

### ISSUE THREAD

**Issue by mauritslamers** [sass/node-sass#1003]
When I first started using node-sass for my project (NodeJS build tools for a web framework), I was happy to see that the node-sass package was providing precompiled binaries. During the preparation of making my project compatible with node v0.12, I suddenly noticed that node-sass requires compilation.
While it is not a problem for me, it is a problem for my users.

I would like to be able to bundle node-sass with my project without having to require of my users to have either XCode or Visual Studio installed, not in the least because it is a hassle to download and install it, and it adds another 5 GB of dead disk space.

**Comment by saper** [comment]
We do ship binaries, maybe there is some problem somewhere on the way? Can you check our TROUBLESHOOTING.md file and provide more details about your platform?

**Comment by mauritslamers** [comment]
Ah, then I must have overlooked something. I saw the computer compiling node-sass and didn't see the precompiled directory in the repository, so I assumed there are no longer binaries available.
I am installing node-sass 1.1.4 under Lubuntu 15.04 64bit, with node 0.12. Is it compiling because it is an older version for which no node 0.12 binaries are available?

**Comment by saper** [comment]
On Sat, 13 Jun 2015, Maurits Lamers wrote:

> Ah, then I must have overlooked something. I saw the computer
> compiling node-sass and didn't see the precompiled directory in the
> repository, so I assumed there are no longer binaries available.

Precompiled binary will be fetched automatically when "node scripts/install.js"
is being run (normally a part of "npm install" process).

The binaries then get installed a platform-dependent subdirectory of "vendor".

It is possible to manually download binaries (for multiple platforms
if so desired).

> I am installing node-sass 1.1.4 under Lubuntu 15.04 64bit, with node
> 0.12. Is it compiling because it is an older version for which no node
> 0.12 binaries are available?

Yes, for the current node-sass (3.2.0) we support 0.12, 0.10 as well
as iojs 1.0.x, 1.2.x and 2.0 series.

**Comment by mauritslamers** [comment]
ok thanks a lot!
