### ISSUE TITLE
Bug, node-sass install always faild on win7x64

### ISSUE THREAD

**Issue by niluanxy** [sass/node-sass#1011]
my match was run windows7 64bit,and install node-sass with version of 2.1.1 always faild,it tell me: Unexpected token '\u0000' at 1:1. then i try install other version,but also faild,how to fix that?

**Comment by saper** [comment]
Can you publish the full log and follow our [TROUBLESHOOTING.md guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)?

**Comment by niluanxy** [comment]
i hava solation this probrom,that due to the cache,after clean node cache,i can installed;

**Comment by saper** [comment]
Thanks! good it worked. Can we now close this?

**Comment by niluanxy** [comment]
yes，and thank you


在2015年06月25日 17:58，Marcin Cieślak 写道:

Thanks! good it worked. Can we now close this?
