### ISSUE TITLE
Unable to install node-sass 3.x on Debian 8

### ISSUE THREAD

**Issue by soee** [sass/node-sass#1013]
When trying to install any 3.x node-sass on my Debian 8 server, it ends with following error:

```
#npm update
-
> node-sass@3.2.0 install web/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at web/node_modules/node-sass/vendor/linux-x64-14/binding.node

> node-sass@3.2.0 postinstall web/node_modules/node-sass
> node scripts/build.js

`web/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists. 
 testing binary.
node: symbol lookup error: web/node_modules/node-sass/vendor/linux-x64-14/binding.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.11.14
npm ERR! npm  v2.12.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT/var/www/clients/client1/web20/
npm ERR! syscall spawn

npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     web/npm-debug.log
```

**Comment by saper** [comment]
Looks like some incompatibility between how node got compiled on your system and the way we compile node-sass binary.

can you check the output of `ldd binding.node` where binding.node is the binary file downloaded into `vendor` subdirectory of node-sass

Also the output of 
 
    ldd `which node`

command would be great.

does `build.js` file exist in the `scripts` directory?

**Comment by saper** [comment]
Same problem: https://github.com/sass/node-sass/issues/751

**Comment by saper** [comment]
I am unable to reproduce the problem using a freshly installed [Debian 8.1](http://gemmei.acc.umu.se/debian-cd/8.1.0/amd64/iso-cd/debian-8.1.0-amd64-netinst.iso), installing `apt-transport-https`, adding nodesource.com GPG key to apt and configuring

````
deb https://deb.nodesource.com/node_0.12 jessie main
deb-src https://deb.nodesource.com/node_0.12 jessie main
````

as `/etc/apt/sources.list.d` and installing node after refreshing apt package database.

For me `node-sass` installed fine.

I would recommend taking `nvm` out of equation and see if that causes the problem.

**Comment by saper** [comment]
Well, I have tried using nvm as well (with node v0.12.5) and it installed node-sass fine as well.

**Comment by xzyfer** [comment]
The issue here is `node v0.11.14`. This version in unsupported and never will be. Please update a stable release 0.10.38, 0.12.2 or iojs.

**Comment by soee** [comment]
Thank you for details. I'll check it later and see if changing node version helps.

**Comment by soee** [comment]
Hi, as suggested i moved to node v0.12.5 and now the problem seems to be gone.

**Comment by korczis** [comment]
It seems it is still not working with latest `iojs` on mac for some reason ... :(

**Comment by saper** [comment]
@korczis: can you follow our [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) guide?

**Comment by francisbrito** [comment]
I had this issue while using `iojs 3.0.0` (from [this](https://hub.docker.com/_/iojs/) docker container), it flew away by downgrading to `iojs 2.5`. I'm guessing changes from 2.x to 3.x are messing up the build script.

**Comment by saper** [comment]
We do not support iojs 3.0 yet. See #1053.

**Comment by francisbrito** [comment]
Oh, I see. Should've checked for iojs 3.0 support before attempting using node-sass on it. Thanks for pointing it out (so fast!)
