### ISSUE TITLE
Standardize on cross-spawn

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1015]
There a known issues with `spawn` on Windows -  joyent/node#2318 as an example. 

As a work around we sometimes use [cross-spawn](https://www.npmjs.com/package/cross-spawn). We will move all usage of `spawn` to `cross-spawn`.

**Comment by saper** [comment]
https://github.com/joyent/node/issues/2318 seems to me like a correct behaviour by design.

Would t `child_process.exec` for our tests and running `git`? That should solve all problems related to directly launching an executable.

**Comment by xzyfer** [comment]
> Would child_process.exec work for our tests and running git

Good question. I have not tested. I see no issue sticking with cross-spawn it's well maintained, and very small.
