### ISSUE TITLE
Can't install node-sass - gyp ERR! stack Error: Command failed: python -c import platform

### ISSUE THREAD

**Issue by pixelstew** [sass/node-sass#1019]
Hi there,

I have succesfully installed an older version of node sass - v2.0.0 during tests but the latest version keeps throwing the same error.

Node version is 12.5

    gyp ERR! configure error 
    gyp ERR! stack Error: Command failed: python -c import platform; print(platform.python_version());
    gyp ERR! stack python: no user 187739958
    gyp ERR! stack 
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:196:12)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at maybeClose (internal/child_process.js:764:16)
    gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at Socket.emit (events.js:169:7)
    gyp ERR! stack     at Pipe._onclose (net.js:467:12)
    gyp ERR! System Darwin 11.4.2
    gyp ERR! command "/usr/local/bin/iojs" "/Users/rob_gilbert/style-guide/node_modules/node-   sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
    gyp ERR! cwd /Users/rob_gilbert/style-guide/node_modules/node-sass
    gyp ERR! node -v v2.3.1
    gyp ERR! pangyp -v v2.2.1
    gyp ERR! not ok 
    Build failed
    npm ERR! Darwin 11.4.2
    npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "node-sass"
    npm ERR! node v2.3.1
    npm ERR! npm  v2.11.3
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
    npm ERR! This is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/rob_gilbert/style-guide/npm-debug.log
    osimac15-2:style-guide rob_gilbert$

**Comment by saper** [comment]
There is something strange with your Python installation; working python is needed for most binary packages and is not a requirement specific only to node-sass.

which version of Python is this? Can you reinstall/upgrade?

**Comment by pixelstew** [comment]
Yeah that struck me as odd too. I'm on a different computer now but from memory i'm on Python 2.7.2. I'll try and reinstall in the morning - see if that solves it. 

As you mentioned though it's specific to node-sass, and I haven't experienced problems elsewhere. Also I found it odd that an earlier version (2.0.0) of node-sass installed without a hitch.

**Comment by saper** [comment]
One thing that is already strange - npm did not apparently download a binary module for your platform. That's why it tries to invoke python to build it for you. Can you post your full log somewhere? There should be some information that the download attempt failed.

**Comment by saper** [comment]
By the way for some reason you are not using node 0.12.5, but iojs 2.3.1. It should work with node-sass as well, but there might be something unexpected in your environment. For example, different binary modules are required for node and iojs.

**Comment by xzyfer** [comment]
I can confirm node-sass@3.2.0 installs and runs fine on iojs-v2.3.4
