### ISSUE TITLE
Can't install node-sass,always stay in >node scripts/install.js

### ISSUE THREAD

**Issue by niluanxy** [sass/node-sass#1021]
today when i install node-sass,it always faild,every times always stay in line: >node script/install.js,when i wait 30 minutes,have anything change.my os is mac 10.10.4.

**Comment by saper** [comment]
@niluanxy do you have a working connection to github to download the binary?

**Comment by niluanxy** [comment]
@saper find problem,that's because the net is two slow to github,when i go home and reinstall,it can success.sorry to disturb you.
