### ISSUE TITLE
Trouble Installing gulp-sass - Error: Cannot find module 'C:\scripts\install.js'

### ISSUE THREAD

**Issue by jaegz** [sass/node-sass#1027]
I've been stuck on this for several hours. I spent a lot of time googling and trying other's suggestions but no luck so far...

Here's a snapshot of my setup.

PATH 
%appdata%\npm; %ProgramFiles%\nodejs; C:\Users\cjaeger1\AppData\Roaming\npm

NODE_PATH
%AppData%\npm\node_modules

> node -p process.versios
{ http_parser: '2.3',
  node: '0.12.6',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1o' }

> node -p process.platform
win32

> node -p process.arch
x64

> npm install --save-dev gulp-sass
npm WARN package.json iq-responsive@1.0.0 No repository field.
npm WARN package.json iq-responsive@1.0.0 No README data
\
> node-sass@3.2.0 install c:\sites\iq-responsive\node_modules\gulp-sass\node_mod
ules\node-sass
> node scripts/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\scripts\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-sass"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.2.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 install script 'node scripts/install.js'.

npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\sites\iq-responsive\npm-debug.log

Let me know if I should include a gist of the npm-debug.log

Thanks for any guidance!

**Comment by xzyfer** [comment]
Hi @jaegz, please follow the steps in the [TROUBLESHOOTING guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and add the output to a gist.

**Comment by mingfang** [comment]
same problem on ubuntu 14.04.
what is the problem?

**Comment by xzyfer** [comment]
Hi @mingfang, please follow the steps in the [TROUBLESHOOTING guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and add the output to a gist.

**Comment by mingfang** [comment]
Thanks @xzyfer .
Indeed the troubleshooting guide said to use ```-unsafe-perm``` and it works now.
Thanks for the quick response.

**Comment by jaegz** [comment]
Followed the TROUBLESHOOTING guide and here's a gist of the output: https://gist.github.com/jaegz/251c27efc6f955aafce2

Thanks

**Comment by saper** [comment]
Are you running npm install from cmd.exe or some other way?

**Comment by jaegz** [comment]
Hi @saper,

I am running npm install from git bash

**Comment by saper** [comment]
Can you try from cmd.exe shell if it works better?

**Comment by jaegz** [comment]
Ok just tried it out... running into same error

**Comment by front-thinking** [comment]
I install gulp-sass，but every time it stoped there and never go on.    Windows 64 OS.
![](http://i3.tietuku.com/dda147fcd3299986.jpg)


but if I install node-sass first and than install gulp-sass,it wil be installed successly.

**Comment by jaegz** [comment]
Still stumped on this... My colleague with the same lenovo laptop was able to install this no problem. I switched my PATH variable to match his, and deleted the NODE_PATH... still getting kicked from install with same error mentioned above. Anything else I can provide that could help troubleshoot this issue?

**Comment by szymonc** [comment]
Same problem here on windows 7 64

**Comment by xzyfer** [comment]
Please follow the [TROUBLESHOOTING guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and paste the output produced into a github gist before posting "me too" style comments.

**Comment by jaegz** [comment]
Anything else I can provide that could help troubleshoot this issue?

**Comment by saper** [comment]
Can you try this under cmd.exe:

````cmd
npm cache clean
npm install -ddd node-sass 2> npm.log
````
and post `npm.log` to gist.github.com again?

**Comment by jaegz** [comment]
Sure thing, here it is:
https://gist.github.com/jaegz/a4195373e89e741afb6a

**Comment by saper** [comment]
Can you post your environment values (`SET`) - if it's not too private?

**Comment by saper** [comment]
Can you try to create `C:\Users\cjaeger1\something` and try to `npm install node-sass` there? Will it report `C:\scripts\install.js` failure or some other directory?

**Comment by saper** [comment]
Also, can you go to `C:\Users\cjaeger1\something` and start 

```cmd
C:\WINDOWS\System32\cmd.exe /c node
```

and then type `process.cwd()` ?

**Comment by saper** [comment]
It's me again - I have added some extra logging in [my private npm fork](https://github.com/saper/npm/tree/lifecyclelog). Can you just replace `lib/utils/lifecycle.js` in your `npm` install directorywith this file: https://github.com/saper/npm/blob/lifecyclelog/lib/utils/lifecycle.js and report the results of `npm install -ddd node-sass` agaaain

**Comment by jaegz** [comment]
@saper thanks for looking deeper into this... much appreciated! 
I'll be back at my desk in about 10hrs to step through everything and report back.

Btw, I just browsed that issue reference to npm/npm and I remember running into issues with phantomjs as well (while trying to install gulp-svg-sprite). I have put that issue on the back burner as node-sass/gulp-sass has been my main concern. Should I also post what smikes & othiym23 have suggested?

**Comment by saper** [comment]
`npm config ls` is always nice, but I think we need to get more logs :)

**Comment by jaegz** [comment]
> Can you post your environment values (SET) - if it's not too private?

User PATH
C:\Windows\System32;C:\Users\cjaeger1\AppData\Roaming\npm

System Path
C:\Windows\System32;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Ruby193\bin;C:\Program Files\nodejs\


>Can you try to create C:\Users\cjaeger1\something and try to npm install node-sass there? Will it report C:\scripts\install.js failure or some other directory? (just make sure you nuke all other copies of node_modules if possible).

Created `C:\Users\cjaeger1\temp1` and ran `npm install node-sass` and reports fail to `'C:\scripts\install.js'` (by nuke all other copies of node_modules you mean in that temp1 dir only, correct?)



>Also, can you go to C:\Users\cjaeger1\something and start
C:\WINDOWS\System32\cmd.exe /c node
and then type process.cwd() ?

Outputs `'C:\\'`


>It's me again - I have added some extra logging in my private npm fork. Can you just replace lib/utils/lifecycle.js in your npm install directorywith this file: https://github.com/saper/npm/blob/lifecyclelog/lib/utils/lifecycle.js and report the results of npm install -ddd node-sass agaaain

Here she is: https://gist.github.com/jaegz/b0fc3fad2baa2fe6a70d

**Comment by saper** [comment]
> >Also, can you go to C:\Users\cjaeger1\something and start
> C:\WINDOWS\System32\cmd.exe /c node
> and then type process.cwd() ?
> 
> Outputs `'C:\\'`

This is the reason! But why? Is there any node.bat or anything on your %PATH% ?

**Comment by saper** [comment]
> >Also, can you go to C:\Users\cjaeger1\something and start
> C:\WINDOWS\System32\cmd.exe /c node
> and then type process.cwd() ?
> 
> Outputs `'C:\\'`

And when you do

````cmd
C:\> cd C:\Users\cjaeger1
C:\Users\cjaeger1> C:\WINDOWS\System32\cmd.exe /C cmd
````

what is your working directory?

**Comment by saper** [comment]
> > Can you post your environment values (SET) - if it's not too private?
> 
> User PATH
> C:\Windows\System32;C:\Users\cjaeger1\AppData\Roaming\npm

Continuing ... what do the following commands say:

````cmd
reg query "HKLM\Software\Microsoft\Command Processor" /s
reg query "HKCU\Software\Microsoft\Command Processor" /s
````

**Comment by jaegz** [comment]
>This is the reason! But why? Is there any node.bat or anything on your %PATH% ?

Great news, we're getting closer!

>And when you do
C:\> cd C:\Users\cjaeger1
C:\Users\cjaeger1> C:\WINDOWS\System32\cmd.exe /C cmd
what is your working directory?

working directory is C:\>

>Continuing ... what do the following commands say:
reg query "HKLM\Software\Microsoft\Command Processor" /s
reg query "HKCU\Software\Microsoft\Command Processor" /s

C:\>reg query "HKLM\Software\Microsoft\Command Processor" /s

HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor
    CompletionChar    REG_DWORD    0x40
    DefaultColor    REG_DWORD    0x0
    EnableExtensions    REG_DWORD    0x1
    PathCompletionChar    REG_DWORD    0x40


C:\>reg query "HKCU\Software\Microsoft\Command Processor" /s

HKEY_CURRENT_USER\Software\Microsoft\Command Processor
    CompletionChar    REG_DWORD    0x9
    DefaultColor    REG_DWORD    0x0
    EnableExtensions    REG_DWORD    0x1
    PathCompletionChar    REG_DWORD    0x9
    Autorun    REG_SZ    CD /d C:\

**Comment by saper** [comment]
On Tue, 11 Aug 2015, chris jaeger wrote:

> Great news, we're getting closer!
> C:\>reg query "HKCU\Software\Microsoft\Command Processor" /s
> 
> HKEY_CURRENT_USER\Software\Microsoft\Command Processor
>     CompletionChar    REG_DWORD    0x9
>     DefaultColor    REG_DWORD    0x0
>     EnableExtensions    REG_DWORD    0x1
>     PathCompletionChar    REG_DWORD    0x9
>     Autorun    REG_SZ    CD /d C:\
                           ^^^^^^^^^

This is it. The same as https://github.com/sass/node-sass/issues/1012#issuecomment-115715502

Please remove this entry and everything will work(tm).

**Comment by jaegz** [comment]
YES! `npm install node-sass` successful!
I don't remember ever setting up an autorun, but that's definitely what was failing the installations.

**THANK YOU** @saper 
Let me know where to send beer money

**Comment by xzyfer** [comment]
Amazing work on this @saper.

**Comment by veremey** [comment]
Sorry, @saper I can install `gulp-sass` 
`npm install --save-dev gulp-sass` doesn't work git:bash  always write that I must to install  `gulp-sass` 
  I'm open PowerShell on windows 10 do:  

PS C:\> reg query "HKCU\Software\Microsoft\Command Processor" /s

HKEY_CURRENT_USER\Software\Microsoft\Command Processor
    CompletionChar    REG_DWORD    0x9
    DefaultColor    REG_DWORD    0x0
    EnableExtensions    REG_DWORD    0x1
    PathCompletionChar    REG_DWORD    0x9

can you help me?

**Comment by rollrodrig** [comment]
Running npm install --save gulp-sass --unsafe-perm worked for me.
node -v
v8.9.3

npm -v
5.5.1

**Comment by lloydtawanda** [comment]
Thank you @rollrodrig
