### ISSUE TITLE
Cannot read property 'binarySite' of undefined in getBinaryUrl() -> node-sass/lib/extensions.js:107:32

### ISSUE THREAD

**Issue by wwi-johnbuhay** [sass/node-sass#1030]
Here are the gists that includes the steps from the troubleshooting guide:

https://gist.github.com/wwi-johnbuhay/6fb5e7fe4518dca28548

**Comment by saper** [comment]
Thank you. Did you have any previous version of node-sass installed before? Can you check the contents of npm cache? I think it's a bug we have but I'd like to investigate further. How does your cached `package.json` look like in the NPM cache?

**Comment by wwi-johnbuhay** [comment]
Thanks for the help,

I did not have a previous version of node-sass before, to provide this debugging info I made sure to start from a clean environment.

I've added the contents of the npm cached package.json here:
https://gist.github.com/wwi-johnbuhay/6fb5e7fe4518dca28548#file-npm_node-sass_3-2-0_package_package-json

**Comment by wwi-johnbuhay** [comment]
I just compared the package.json between the problematic one above and the one that installs successfully in the node:latest docker container, which i did not configure to use our artifactory registry.

The missing lines in the problematic package.json are:

"gitHead": "6343cea64ed6d33e2f37ff388888f6a3a189c8a8",
    "gypfile": true,
...
"libsass": "3.2.5",
...
"nodeSassConfig": {
        "binarySite": "https://github.com/sass/node-sass/releases/download"
    },

**Comment by saper** [comment]
That's interesting. It's `nodeSassConfig` that is missing indeed. Is your custom registry not keeping custom properties stored?

**Comment by saper** [comment]
Can you try `npm install npm-registry` and try this script? https://gist.github.com/578d44b6e02753e0008e

**Comment by wwi-johnbuhay** [comment]
It appears that way, not keeping custom properties stored. I will reach out to them about it after this.

Here is the gist using the artifactory registry https://gist.github.com/wwi-johnbuhay/6fb5e7fe4518dca28548#file-npm-registry

**Comment by saper** [comment]
Maybe it's not "The Most Powerful Repository Around" :) Do hey have a public bug tracker?

The second case is strange - I just removed a whole `nodeSassConfig` stanza from `package.json` and that's what I got:

````
$ git diff -- package.json
diff --git a/package.json b/package.json
index f1dc6dc..9befb1b 100644
--- a/package.json
+++ b/package.json
@@ -18,9 +18,6 @@
     "node": ">=0.10.0"
   },
   "main": "lib/index.js",
-  "nodeSassConfig": {
-    "binarySite": "https://github.com/sass/node-sass/releases/download"
-  },
   "bin": {
     "node-sass": "bin/node-sass"
   },

$ env SASS_BINARY_SITE=https://github.com/sass/node-sass/releases/download npm install

> node-sass@3.2.0 install /home/saper/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/saper/node_modules/node-sass/vendor/freebsd-x64-14/binding.node

> node-sass@3.2.0 postinstall /home/saper/node_modules/node-sass
> node scripts/build.js

` /home/saper/node_modules/node-sass/vendor/freebsd-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
````

**Comment by saper** [comment]
The bug tracker:https://www.jfrog.com/jira/browse/RTFACT

**Comment by wwi-johnbuhay** [comment]
thanks for helping me pinpoint what artifactory is missing, i have other things to do right now, but i will open a ticket with jfrog and when I figure this out I'll update this thread for other private registry users

**Comment by xzyfer** [comment]
Do we know if this is an npm issue with private repositories, or the something specific to the setup of this particular repository?

We're actively considering pushing more config into package.json so it'd be good to get the to bottom of this.

**Comment by wwi-johnbuhay** [comment]
This a bug with the version of artifactory we are using(3.2.0).

I just tested the latest version (3.9.1) using jfrogs docker container and the npm request does retrieve the custom properties, I set up the npm registry in the same manner and was successful in installing node-sass with artifactory proxying the public registry. I was also able to successfully install packages that depend upon node-sass like grunt-sass as well.

**Comment by saper** [comment]
On Tue, 14 Jul 2015, John Buhay wrote:

> This a bug with the version of artifactory we are using(3.2.0).

Thanks for reporting this! Hopefully others having similar issue will bump info this thread.

**Comment by wwi-johnbuhay** [comment]
This was very helpful for testing:
http://www.jfrog.com/confluence/display/RTF/Running+with+Docker#RunningwithDocker-RunningArtifactoryPro

**Comment by xzyfer** [comment]
Thanks for the confirmation @wwi-johnbuhay. This was important to us we we're planning to rely more on package.json custom data.
