### ISSUE TITLE
is there a fontsDir equivalent?

### ISSUE THREAD

**Issue by casertap** [sass/node-sass#1035]
I am migrating from compass to sass because the ruby config is a pain in the ...
mainly because I want to run the grunt command during deploy from my local machine using capistrano.

Anyway I trouble migrating from compass to sass.
Is there an equivalent for fontsDir options to replace the font-url mixin automatically.

my compass task looks like this 
````
compass: {
      options: {
        sassDir: '<%= yeoman.app %>/styles',
        cssDir: '<%= yeoman.tmp %>/styles',
        generatedImagesDir: '<%= yeoman.tmp %>/assets/generated',
        imagesDir: '<%= yeoman.tmp %>/assets',
        javascriptsDir: '<%= yeoman.tmp %>/scripts',
        fontsDir: '<%= yeoman.tmp %>/fonts',
        importPath: './bower_components',
        //The full http path to images on the web server.
        //this allow Compass URL Helpers like image-url, font-url to generate the proper url
        httpImagesPath: '/assets',
        httpGeneratedImagesPath: '/assets/generated',
        httpFontsPath: '/assets',
        relativeAssets: false,
        assetCacheBuster: false,
        raw: 'Sass::Script::Number.precision = 10\n'
      },
      dist: {
        options: {
          debugInfo: false,
          generatedImagesDir: '<%= yeoman.dist %>/assets/'
        }
      },
      server: {
        options: {
          debugInfo: true
        }
      }
    },

````

**Comment by saper** [comment]
Hi, I think you might want to check out https://github.com/sass-eyeglass/eyeglass, brought to the node-sass world by the creators of Compass.`node-sass` does not deal with assets at all, it just translates Sass to CSS.

**Comment by xzyfer** [comment]
We will not be adding url helpers to node-sass. There is great tooling in the npm ecosystem for rewriting urls.
