### ISSUE TITLE
Problem in Windows downloading node-sass-binaries dependency

### ISSUE THREAD

**Issue by alvNa** [sass/node-sass#1037]
Currently we are working in a project with 2 kind of systems: Linux Fedora & Windows 7.
In our proyect we have a dependency with node-sass through gulp-sass.
In Linux is working fine, but in Windows we have the following problem:
- When the node-sass is downloaded, the directory node-sass\vendor\win32-x64-11 is empty
- If I try to execute a task related with this module I get this message
"Error: `libsass` bindings not found in {myproyect_path}\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-11\binding.node. Try reinstalling `node-sass`?"
- If I downloaded manually the binary (https://github.com/sass/node-sass-binaries) and put on the directory as binding.node it works fine.

Thank you

**Comment by xzyfer** [comment]
You need to run `npm install` on both systems to download both bindings.

**Comment by am11** [comment]
You can also download the binary after installing the package:

```powershell
# this is windows powershell
cd somewhere_temp # experimental

npm install node-sass

cd node_modules/node-sass

$bin = (node -p process.platform) + '-' + (node -p process.arch) + '-' + (node -p process.versions.modules)


node .\scripts\install.js --sass-binary-name $bin

# binary matching the value of current OS will be downloaded
```

To download the binding for other OS, hardcode the calculated value of `$bin` read from your Linux box, or perform the regular install first on Linux, move directory to Windows and run the install script or even vice versa (transform powershell syntax to bash)

---

Note that, it is also possible to download the binding for some other OS in first place:

```bash
# in Linux
SASS_BINARY_NAME=win32-ia32-42 node install node-sass

# in Windows PowerShell
$env:SASS_BINARY_NAME='freebsd-ia3-14'; node install node-sass

# in Windows Command Prompt
SASS_BINARY_NAME=darwin-x64-44 && node install node-sass
```
One drawback is, after the download, the installer validates the binding per the current OS, which fails in this case. But if you download the binary after downloading node-sass, it will skip the validation. 

I think we should also make the validation skip if requested binary is different than the current platform.

Well there *is* a quirky way to force skip the binary validation:

```bash
# in Linux
SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1 SASS_BINARY_NAME=win32-ia32-42 node install node-sass

# in Windows PowerShell
$env:SASS_BINARY_NAME='freebsd-ia3-14'; $env:SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1; node install node-sass

# in Windows Command Prompt
SASS_BINARY_NAME=darwin-x64-44 && SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1 && node install node-sass
```

If you have read this far, you will notice that it is quite possible to install binaries for multiple OSes without leaving CLI, downloading the binaries manually from https://github.com/sass/node-sass/releases/tag/v3.2.0 or installing node-sass twice. :)

**Comment by saper** [comment]
If you experience issues despite having node-sass binaries installed for all your platforms, please reopen.

**Comment by fredvb** [comment]
I just installed sass with : gem install sass, then I tried running "npm install -g node-sass" and got this odd situation: 
"Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/win32-x64-45_binding.node": HTTP error 404 Not Found"
Why 45 ?

**Comment by saper** [comment]
@fredvb please check the list of [our issues](https://github.com/sass/node-sass/issues).

**Comment by fredvb** [comment]
Thanks, for some reason I got lazy and only searched via google search and didn't find those. 
Thanks for the heads up.
Hope it'll get settled sooner or later.
