### ISSUE TITLE
Create an @inject directive, like @extend, that would strip off the extending selectors.

### ISSUE THREAD

**Issue by joseorihuela** [sass/node-sass#1038]
I currently use something similar to this feature in my projects, basically by replacing class definitions with ```@mixin classname {}``` **vs** ```.classname {}```. I find on large projects, when using Bootstrap or Foundation, that being able to inject the class contents into semantic classes reduces the overhead of excessive extending selectors.

***Example:***
```html
<nav class="main-nav"</nav>
```

Recommended Extending Method:
```css
.main-nav {
  @extend .navbar;
  @extend .navbar-default;
  @extend .navbar-fixed-top;
}
```

Generated Selectors:
```css
@media (xyz) .navbar, .main-nav {}
.navbar, .main-nav {}
.navbar-default, .main-nav {}
.navbar-fixed-top, .main-nav {}
@media (xzy) .navbar-fixed-top, .main-nav, .navbar-fixed-bottom {}
.navbar-fixed-top, .main-nav, .navbar-fixed-bottom {}
.navbar:after, .main-nav:after {}
.navbar:before, .main-nav:before, .navbar:after, .main-nav:after {}
```
***Injecting:***

Using existing classes as @mixin:
```css
.main-nav {
  @include navbar;
  @include navbar-default;
  @include navbar-fixed-top;
}
```

Generated Selectors:
```css
  @media (xyz) .main-nav {}
  .main-nav {}
  .main-nav:before, .main-nav:after {}
```

**Comment by xzyfer** [comment]
Language level features are decided by the Ruby Sass team. We're simply a node implementation of the Sass language spec. Please open this issue in https://github.com/sass/sass/issues

**Comment by joseorihuela** [comment]
Thanks, sorry about that!

- Jose Orihuela
