### ISSUE TITLE
Multiple include-paths from CLI

### ISSUE THREAD

**Issue by paulcpederson** [sass/node-sass#1043]
`includePaths` from the [Node API](https://github.com/sass/node-sass#includepaths) expects an array of paths, but I can't figure out how to pass multiple paths on the command line. Is that possible? It seems like the CLI is checking for `include-path` [to be an array](https://github.com/sass/node-sass/blob/master/bin/node-sass#L267), but it is initially [declared as a string](https://github.com/sass/node-sass/blob/master/bin/node-sass#L68).

I expected it to work like `node-sass sass/ --include-path path/1/ path/2/ -o css/`. Perhaps there is a different syntax and I'm just being a bit dull?

If this is currently impossible, I could certainly try my hand at implementing it!

**Comment by mgreter** [comment]
Just a shot in the wild, but have you tried `node-sass sass/ --include-path /1 --include-path /2`. This is just a guess, since it is how most CLI tools work ...

**Comment by paulcpederson** [comment]
@mgreter Nice! worked great!

**Comment by paulcpederson** [comment]
:+1:
