### ISSUE TITLE
Build fails with new iojs changes

### ISSUE THREAD

**Issue by meandavejustice** [sass/node-sass#1052]
https://github.com/nodejs/io.js/blob/master/CHANGELOG.md#2015-08-04-version-300-rvagg

**Comment by xzyfer** [comment]
Yep we're on it. The changes are significant.

**Comment by xzyfer** [comment]
Tracking in https://github.com/sass/node-sass/issues/1053

**Comment by saper** [comment]
@meandavejustice can you try #1054 if it works for you?
