### ISSUE TITLE
npm@3: Error: Cannot find module '/tmp/node_modules/node-sass/node_modules/pangyp/bin/node-gyp

### ISSUE THREAD

**Issue by saper** [sass/node-sass#1061]
npm 3 has a new toy called auto-flattening, i.e all dependencies will be installed in the same level `node_modules` if possible. This breaks our assumption about how to find `node-gyp`.

Workaround: make sure you are using npm 2.x series.

**Comment by yairEO** [comment]
I apparently got stuck with this error after upgrading my Node to the latest (on windows) `v0.12.7`
`NPM -v` is `2.11.3` ... 

I hope this will be solved quickly..

**Comment by saper** [comment]
This error is about npm 3.0 and we have a fix in #1063. Can you go through our [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) guide and post the output to the new issue?

**Comment by busches** [comment]
Using this with `npm@3.3` resolved the `Error: Cannot find module 'X:\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'.` I was getting.
