### ISSUE TITLE
sass2scss from node-sass

### ISSUE THREAD

**Issue by dkebler** [sass/node-sass#1068]
Does node_sass support calls to  sass2scss so I can deal with indented sass vendor libraries while compiling my scss?   I see nothing in your documentation.

According to this repo sass2scss is part of the libass. 
https://github.com/mgreter/sass2scss

**Comment by saper** [comment]
Yes.

**Comment by dkebler** [comment]
great

can you point to me to your documentation on usage.  I can't identify
anything in read.me file.

I am aware of  indentedSyntax switch but that is either or deal.

I am looking to convert some vender indent sass before compiling it with my
scss and other vendor scss.

in the cli it's a separate call https://github.com/mgreter/sass2scss so not
seeing how to do this from node-sass



On Wed, Aug 12, 2015 at 8:52 AM, Marcin Cieślak <notifications@github.com>
wrote:

> Yes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sass/node-sass/issues/1068#issuecomment-130352088>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by saper** [comment]
We have [a test for this feature in our test suite](https://github.com/sass/node-sass/blob/81c5446b5a1876ed30c14d5c9c351ca80537275a/test/api.js#L79-L91):

````js
    it('should compile sass to css using indented syntax', function(done) {
      var src = read(fixture('indent/index.sass'), 'utf8');
      var expected = read(fixture('indent/expected.css'), 'utf8').trim();

      sass.render({
        data: src,
        indentedSyntax: true
      }, function(error, result) {
        assert.equal(result.css.toString().trim(), expected.replace(/\r\n/g, '\n'));
        done();
      });
    });
````

And its [input file](https://github.com/sass/node-sass/blob/81c5446b5a1876ed30c14d5c9c351ca80537275a/test/fixtures/indent/index.sass):

````sass
foo
  + bar
    color: red
````

I think you need to use `.sass` filename extension to let libsass recognize the file.

**Comment by dkebler** [comment]
Ok, I did a little test of my own and yes it will compile automagically
mixed syntax as long as extension for indent files is .sass as you say.

So sorry, I was confused by the IndentedSyntax switch which really isn't
needed it seems.

A little change to your read.me (below) for that would have kept me from
wasting your time.

---
indentedSyntax

Type: Boolean Default: false

true values enable Sass Indented Syntax
<http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html> for parsing
the data string or file.

Note: node-sass will compile a mixed library of scss and indented syntax
(.sass) files with the Default setting (false) as long .sass and .scss
extensions are used in filenames.

------------


I know I could do a PR but it's a small change.

Thx again, close this.


On Wed, Aug 12, 2015 at 10:47 AM, Marcin Cieślak <notifications@github.com>
wrote:

> We have a test for this feature in our test suite
> <https://github.com/sass/node-sass/blob/81c5446b5a1876ed30c14d5c9c351ca80537275a/test/api.js#L79-L91>
> :
>
>     it('should compile sass to css using indented syntax', function(done) {
>       var src = read(fixture('indent/index.sass'), 'utf8');
>       var expected = read(fixture('indent/expected.css'), 'utf8').trim();
>
>       sass.render({
>         data: src,
>         indentedSyntax: true
>       }, function(error, result) {
>         assert.equal(result.css.toString().trim(), expected.replace(/\r\n/g, '\n'));
>         done();
>       });
>     });
>
> And its input file
> <https://github.com/sass/node-sass/blob/81c5446b5a1876ed30c14d5c9c351ca80537275a/test/fixtures/indent/index.sass>
> :
>
> foo
>   + bar
>     color: red
>
> I think you need to use .sass filename extension to let libsass recognize
> the file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sass/node-sass/issues/1068#issuecomment-130387971>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by saper** [comment]
We submit everything via PR's, so you won't somebody else will have to do it :(

**Comment by dkebler** [comment]
made a PR for that read.me note

**Comment by saper** [comment]
Thanks, merged!
