### ISSUE TITLE
@each - invalid selector after 

### ISSUE THREAD

**Issue by maxaille** [sass/node-sass#1069]
I just passed from an old version of grunt-sass to gulp-sass, and I immediatly get an error when trying to compile
```
$colors : (teal:#00A0B1, blue:#2E8DEF, sky-blue:#0A5BC4, dark-purple:#643EBF, purple:#A700AE, red:#bf1e34, orange:#DC572E, yellow:#E0BC2D, green:#00A600, grey:#A8A8A8)
@each $name, $color in $colors
    .#{$name}
        background-color: $color
```
Error:
```events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: public/styles/tools.sass
  11:202  invalid selector after 
    at options.error (.../node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)
```

I tried removing the ```.``` in ```.#{$name}```  and replaced it in the variable like ```#{'.' + $name}``` or other things but nothing worked.
Am I missing something or is it a bug ?

**Comment by saper** [comment]
Ruby Sass says:

````
Error: Invalid CSS after "..., grey:#A8A8A8)": expected selector or at-rule, was "@each $name, $c..."
        on line 2 of 1069.test.scss
  Use --trace for backtrace.
````

**Comment by saper** [comment]
It works if you give the file name `.sass` extension or tell node-sass to use indented syntax:

````
~/node_modules/node-sass/bin/node-sass 1069.test.sass
.teal {
  background-color: #00A0B1; }

.blue {
  background-color: #2E8DEF; }

.sky-blue {
  background-color: #0A5BC4; }

.dark-purple {
  background-color: #643EBF; }

.purple {
  background-color: #A700AE; }

.red {
  background-color: #bf1e34; }

.orange {
  background-color: #DC572E; }

.yellow {
  background-color: #E0BC2D; }

.green {
  background-color: #00A600; }

.grey {
  background-color: #A8A8A8; }

````

Ruby gives some warnings at the top:

````
WARNING on line 4, column 6 of 1069.test.sass:
You probably don't mean to use the color value `teal' in interpolation here.
It may end up represented as #008080, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "teal").
If you really want to use the color value here, use `"" + $name'.
````

**Comment by maxaille** [comment]
Well, I was using ```.pipe(sass({outputStyle: 'compressed'}))``` in gulp and it 's that that broke all the thing. After trying directly with node-sass, I got the same problem. With any other output-style I have no problem compiling this code.
So using --output-style compressed seems to broke with @each using the SASS syntax

**Comment by saper** [comment]
Here's what I got with the current libsass master (wrapped a bit)

````css
$  ~/node_modules/node-sass/bin/node-sass -i 1069.test.sass --output-style=compressed
.teal{background-color:#00A0B1}.blue{background-color:#2E8DEF}
.sky-blue{background-color:#0A5BC4}
.dark-purple{background-color:#643EBF}.purple{background-color:#A700AE}
.red{background-color:#bf1e34}.orange{background-color:#DC572E}
.green{background-color:#00A600}.grey{background-color:#A8A8A8}
````

**Comment by maxaille** [comment]
Within tools.sass I have:
```
$colors : (teal:#00A0B1, blue:#2E8DEF, sky-blue:#0A5BC4, dark-purple:#643EBF, purple:#A700AE, red:#bf1e34, orange:#DC572E, yellow:#E0BC2D, green:#00A600, grey:#A8A8A8)
@each $name, $color in $colors
    .#{$name}
        background-color: $color
```


node-sass -i tools.sass --output-style=compressed 
```
{
  "message": "invalid selector after ",
  "column": 33,
  "line": 2,
  "file": "/home/mborges/git/processus/src/public/styles/tools.sass",
  "status": 1
}
```


node-sass --version
```
node-sass	3.2.0	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
```

**Comment by saper** [comment]
> node-sass --version
> ```
> node-sass	3.2.0	(Wrapper)	[JavaScript]
> libsass  	3.2.5	(Sass Compiler)	[C/C++]
> ```

Mine:

    $ ~/node_modules/node-sass/bin/node-sass --version 
    node-sass   3.2.0   (Wrapper)   [JavaScript]
    libsass     3.2.5-172-g1ebed-dirty  (Sass Compiler) [C/C++]

So it seems it got fixed in the yet-unreleased libsass code.

**Comment by xzyfer** [comment]
I can confirm this issue is present in LibSass 3.2.5 is compressed output mode. It appears to be resolved on master. We'll get this fix when the next version of LibSass is released.

**Comment by xzyfer** [comment]
Fixed in https://github.com/sass/node-sass/pull/1214. Will be in v3.4.0.
