### ISSUE TITLE
npm i node-sass --save 404 error

### ISSUE THREAD

**Issue by liyaodong** [sass/node-sass#1071]
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-45_binding.node": HTTP error 404 Not Found
```

Where is `darwin-x64-45_binding.node` ? Why npm install will download the not exist release ?

`Mac OS X 10.10.4 ` `npm 2.13.3` `iojs 3.0.0`

Thank you all !

**Comment by xzyfer** [comment]
Please search before opening an issue in the future. We currently do not
support iojs 3.
