### ISSUE TITLE
Yeoman webapp generator error with sass

### ISSUE THREAD

**Issue by iamzifei** [sass/node-sass#1073]
Followed the "Get Started" instruction of Yeoman and get the latest stable npm and bower. However I'm getting the following error when running `npm install`

<pre>npm install

\> node-sass@3.2.0 install /Users/zifei/Dev/projects/Woyao-
web/node_modules/grunt-sass/node_modules/node-sass

\> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download
/v3.2.0/darwin-x64-45_binding.node": HTTP error 404 Not Found

\> node-sass@3.2.0 postinstall /Users/zifei/Dev/projects/Woyao-
web/node_modules/grunt-sass/node_modules/node-sass

\> node scripts/build.js

Building: /Users/zifei/.nvm/versions/io.js/v3.0.0/bin/iojs 
node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= 
--libsass_ldflags= --libsass_library=
gyp: /Users/zifei/.node-gyp/3.0.0/common.gypi not found (cwd: /Users/zifei
/Dev/projects/Woyao-web/node_modules/grunt-sass/node_modules/node-sass) 
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/zifei/Dev/projects
/Woyao-web/node_modules/grunt-sass/node_modules/node-sass/node_modules
/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit 
(internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/zifei/.nvm/versions/io.js/v3.0.0/bin/iojs" 
"/Users/zifei/Dev/projects/Woyao-web/node_modules/grunt-sass/node_modules
/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" 
"--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/zifei/Dev/projects/Woyao-web/node_modules/grunt-
sass/node_modules/node-sass
gyp ERR! node -v v3.0.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/zifei/.nvm/versions/io.js/v3.0.0/bin/iojs" "/Users
/zifei/.nvm/versions/io.js/v3.0.0/bin/npm" "install"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node 
scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zifei/Dev/projects/Woyao-web/npm-debug.log</pre>

**Comment by xzyfer** [comment]
Please search before opening a new issue. We currently do not support iojs
3.
