### ISSUE TITLE
sass-graph extensions

### ISSUE THREAD

**Issue by razvanc87** [sass/node-sass#1074]
Damn... this took me a while to figure out. So I'm using `.sass` (that is with the extension `sass`, not `scss) files here and, the `sass-graph` package isn't initialize with this extension so I was wondering why the heck wouldn't it watch the `@imports`... I had to change line 228 in `bin/node-sass` from
```
  var graphOptions = { loadPaths: options.includePath };
```
to
```
  var graphOptions = {
    loadPaths: options.includePath,
    extensions: ['sass', 'scss', 'css']
  };
```

Now all is good :)

**Comment by xzyfer** [comment]
Thanks @razvanc87 

Duplicate https://github.com/sass/node-sass/issues/1075
Fixed in https://github.com/sass/node-sass/pull/1078
