### ISSUE TITLE
Unable to watch directory

### ISSUE THREAD

**Issue by fsaftoiu** [sass/node-sass#1075]
Hi,

I'm having trouble watching a directory with multiple SASS files using the following command line :
`.\node_modules\.bin\node-sass --sourcemap -w .\sass -o .\css`

As far as I can tell, this is because at line 228 of the node-sass script :
`var graphOptions = { loadPaths: options.includePath };`
the extensions are not specified. I've changed the line to :
`var graphOptions = { loadPaths: options.includePath, extensions : ["scss", "sass", "css"] };`
and it works perfectly.

**Comment by xzyfer** [comment]
Thanks for report @fsaftoiu. You're absolutely correct and I have a patch in https://github.com/sass/node-sass/pull/1078
