### ISSUE TITLE
darwin-x64-45_binding.node 404

### ISSUE THREAD

**Issue by synthecypher** [sass/node-sass#1082]
I'm trying to install the latest version of `gulp-sass` which in turn installs the latest version of `node-sass` and `node-sass` is failing to install because it's trying to download my operating system's libsass bindings which don't exist.

```Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-45_binding.node": HTTP error 404 Not Found```

**Comment by machinealgo** [comment]
This is also happening to us, on a clean OS X machine with no node_modules installed.

**Comment by xzyfer** [comment]
Please search before opening new issues. We do not currently support iojs
v3.
