### ISSUE TITLE
Compiling can't find @import'd files using the SASS syntax

### ISSUE THREAD

**Issue by danielcgold** [sass/node-sass#1083]
I'm using this command to compile my CSS.
`node-sass -w sass/ -o css/ --include-path='bower_components/'`

When I broke out my sass file into partials I noticed that watch stopped compiling my CSS. I took out watch and just tried to compile, but the changes still weren't compiling into my CSS file. I changed my syntax from `.sass` to `.scss` and the above command worked. 

I'm using the latest version of node-sass.
```
node-sass       3.2.0	   (Wrapper)             [JavaScript]
libsass         3.2.5      (Sass Compiler)       [C/C++]
```

**Comment by xzyfer** [comment]
Thanks for the report @danielcgold. This has been fixed and will be in the next release.
