### ISSUE TITLE
node-sass fails to build on iojs 3.0.0

### ISSUE THREAD

**Issue by felixsanz** [sass/node-sass#1085]
Getting this error:

```
> node-sass@3.2.0 install /srv/http/whiledev.com/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-45_binding.node": HTTP error 404 Not Found
```

x64-45_binding.node doesn't exist. Only up to -44.

**Comment by xzyfer** [comment]
**Please** search before opening new issues. 

Duplicate https://github.com/sass/node-sass/issues/1082 https://github.com/sass/node-sass/issues/1073 https://github.com/sass/node-sass/issues/1071 https://github.com/sass/node-sass/issues/1067 https://github.com/sass/node-sass/issues/1064 https://github.com/sass/node-sass/issues/1059

**Comment by felixsanz** [comment]
@xzyfer  Search what? All of those are closed. Leave one open at least if you want people to know about it

**Comment by dark-elephant** [comment]
Now that node 4.0.0 is released, you might have to consider fixing this.

**Comment by xzyfer** [comment]
This has been fixed for a while. Update to v3.3.0 for iojs support, v3.3.2 for Node 4.

**Comment by dark-elephant** [comment]
cool.. Thanks!
