### ISSUE TITLE
npm install problem with gulp/node-sass@3.2.0

### ISSUE THREAD

**Issue by bmacnaughton** [sass/node-sass#1087]
This seems very similar to some other threads, but I'm documenting it here. Is my solution to build node-sass from source so the binary is compatible with my OS?

Here's the console log. I can send or post the relevant lines from the npm-debug.log if that would be helpful, but there's a lot of noise there so I won't unless you request it.

> node-sass@3.2.0 install /home/bruce/whale/root/whale/gulp/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/bruce/whale/root/whale/gulp/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node

> node-sass@3.2.0 postinstall /home/bruce/whale/root/whale/gulp/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /home/bruce/whale/root/whale/gulp/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists. 
 testing binary.
node: symbol lookup error: /home/bruce/whale/root/whale/gulp/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_
npm ERR! Linux 3.13.0-62-generic
npm ERR! argv "node" "/home/bruce/.nvm/v0.11.14/bin/npm" "install" "--save"
npm ERR! node v0.11.14
npm ERR! npm  v2.11.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bruce/whale/root/whale/gulp/npm-debug.log

**Comment by saper** [comment]
You are using node 0.11 which is not supported. Try 0.10, 0.12 or io.js up to 2.5. Support for io.js 3.0 coming soon (#1054) but node 0.11 and 0.13 will never be supported.

**Comment by bmacnaughton** [comment]
Thanks for the quick reply. OK, I'll give things a shot with 0.12.

I hear that node.js and io.js are rejoining - would that change anything?

Thanks again - the quick reply really makes progress much easier.

**Comment by saper** [comment]
The biggest API changes came with io.js 3.0, but we need to see once node 4.0 comes out.
