### ISSUE TITLE
Watching appears to not re-render when imports are modified

### ISSUE THREAD

**Issue by athenot** [sass/node-sass#1095]
Even after applying the temp fix in #1075 to get my `.sass` files to be rendered, when any `@import`s are modified, this doesn't trigger a re-render of parents.

This is the case whether the `@import`ed files are prefixed with `_` or not.

It turns out the call to `visitGraphAncestors` (sass-graph, L.247) does not return the list of parents as would be expected.

My temporary work around—in case anyone else finds it useful—is to use `fswatch`. No graph traversal but I only have a couple target files so I re-render it all:

```
fswatch style/ | xargs -n1 -I{} node-sass style/main.css generated/out.css
```

**Comment by xzyfer** [comment]
Can you please confirm this is still an issue with v3.3.0?

**Comment by athenot** [comment]
Updated to 3.3.1 (from 3.2.0), can still reproduce.

    $ ./node_modules/node-sass/bin/node-sass -version
    node-sass	3.3.1	(Wrapper)	[JavaScript]
    libsass  	3.2.5	(Sass Compiler)	[C/C++]
    $ ./node_modules/node-sass/node_modules/sass-graph/bin/sassgraph -version
    2.0.1

Source is in `style`, dest is in `public/generated`. File `main.sass` references `home.sass` and `_forms.sass` (among others):

    @import home
    @import forms

Running this command:

    ./node_modules/.bin/node-sass -w style -o public/generated

Never re-renders when `import`ed files are modified. Does re-render when `main.sass` is modified. When `home.sass` is modified, that one is rerendered but not `main.sass`.

I also tried the following, which produced the same behavior.

    ./node_modules/.bin/node-sass --watch=style style/main.sass public/generated/out.css 

Let me know if there's anything else I can do to help.

**Comment by xzyfer** [comment]
Thanks for the update. We'll keep looking into this.

**Comment by saper** [comment]
@athenot from the file extension ('sass') as well as the import format I am guessing that you are using traditional Sass indented syntax. Our dependency walker, https://github.com/xzyfer/sass-graph does not support indented syntax very well. See also #1179 for I think the same case.

I have prepared some test cases in https://github.com/xzyfer/sass-graph/issues/31 where we can track the issue.

**Comment by athenot** [comment]
That is correct. I forgot to specify that. And yes I can see how that syntax is harder to walk. Honestly, it's not urgent at all since I use `make` to build and manage the dependencies there. But I'll keep an eye on  `xzyfer/sass-graph`.

Thanks a lot, I wish I could be more useful!

**Comment by jjeising** [comment]
I'm also seeing this behavior with the SCSS syntax. Are you sure this depends on the syntax?

**Comment by saper** [comment]
We are now pretty certain that the reason the above case is not working is the use of sass syntax. Can you open a new bug for your case please? Please include working code which we can download and run.

**Comment by chisleu** [comment]
This may be related so I thought I would pass it along.

I have indented syntax turned on and it is forcing the css to rerender for every request, even without changes.

I do not have force turned on.
The behavior stops when I converted the indented syntax to bracketed syntax.

**Comment by d6u** [comment]
I use SCSS syntax on 3.4.2, and new files are not watched after `@import`, restart node-sass solve the issue, but really annoying.

**Comment by xzyfer** [comment]
@chisleu the library we use parsing the sass import graph does not currently support the indented syntax, which is why we need to compile everything. It's a know issue that's out of our control.

**Comment by xzyfer** [comment]
@d6u there are some bugs in the library we use parsing the sass import graph.

**Comment by ryankask** [comment]
I'm seeing the the same issue as @d6u. @xzyfer Since it works when node-sass is restarted, is it an issue with the import graph or rather with adding new files in the graph to watcher?

In the meantime, I've changed `watch()` in `bin/node-sass` to the following which works for this particular project.

```
  gaze.on('changed', function(file) {
    var files = [file];
    graph.visitAncestors(file, function(parent) {
      files.push(parent);
    });
    files.forEach(function(file) {
      if (path.basename(file)[0] !== '_') {
        renderFile(file, options, emitter);
      }
    });
    // Added this...
    graph = grapher.parseFile(options.src, graphOptions);
    var nextFilesToWatch = [];
    for (var fileName in graph.index) {
      nextFilesToWatch.push(fileName);
    }
    gaze.add(nextFilesToWatch);
  });
```

**Comment by Karklis** [comment]
+1 Same problem. i moved my scss dev to ruby and sass for now, slower but work.

My main.scss import bbb.scss that import ccc.scss. When change ccc.scss, the watcher works, but do not execute the reder, unless change something in bbb.scss, than this will trigger node-sass to render.

**Comment by xzyfer** [comment]
@ryankask  you're correct we currently don't rebuild the graph when files are added or deleted.

**Comment by saper** [comment]
https://github.com/sass/node-sass/issues/1179#issuecomment-543501928 it seems to be working now.
