### ISSUE TITLE
Allow binaries to be install from the local filesystem

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1106]
Originally mentioned in https://github.com/sass/node-sass/issues/1104#issuecomment-134525186

### Problem

Currently the binary site config, as the name suggests, needs to be a remote URL. Allowing file access might be useful for local development.

### Proposed solution

```
 set SASS_BINARY_LOCATION=C:/tmp/node-sass-bin-mirror
 npm install node-sass
````

### Usecase

To be honest I'm not entire sure this is useful. The major usecase I see for this is offline development.

Thoughts @am11 @saper?

**Comment by xzyfer** [comment]
@flogehring this may be of interest to you.

**Comment by flogehring** [comment]
Yes, that and

     "nodeSassConfig": {
       "binarySite": "C:/temp/node-sass-bin-mirror/"
    },

would both be helpful for offline development or development behind annoying corporate proxies

**Comment by am11** [comment]
At present it is quite possible. Also, the install script skips the binary download (not sure if we documented it properly, these details are buried in some PR description):

### Bash version:

```bash
mkdir /test-sass
cd /test-sass

# download / copy binding.node in /test-sass, then:
set SASS_BINARY_PATH=/test-sass/binding.node

npm install node-sass
```

### CMD version:

```cmd
mkdir \test-sass
cd \test-sass

:: download / copy binding.node in c:\test-sass, then:
SET SASS_BINARY_PATH=C:/test-sass/binding.node
:: your drive letter may vary

npm install node-sass
```

### PowerShell version:

```powershell
mkdir /test-sass
cd /test-sass

# download / copy binding.node in c:\test-sass, then:
$env:SASS_BINARY_PATH="C:/test-sass/binding.node"
# your drive-letter may vary

npm install node-sass
```

### `package.json` version:

```json
"nodeSassConfig": {
  "binaryPath": "/test-sass/binding.node"
}
```

**Comment by xzyfer** [comment]
Argh you're totally right. Completely forgot about `SASS_BINARY_PATH`. It comes up so rarely.

I'm glad I asked the question.

**Comment by saper** [comment]
I think we could consider adding support for this to `SASS_BINARY_SITE` (maybe renamed again:) - it can be useful for folks sharing node installations via UNC shares ('\\Server\disk'). Not sure what is the proper URL scheme for UNC since file://server/disk should go to FTP.

**Comment by xzyfer** [comment]
@saper according to @am11 this is already available but under the `SASS_BINARY_PATH` variable instead. May be there's a case for combining the two and determining whether it's an FS or network operation at runtime.

**Comment by saper** [comment]
Those two are not equivalent: SASS_BINARY_PATH points at the ultimate location of **the** binding file - it must match your node-sass version, architecture and node engine. A repository pointed to by SASS_BINARY_SITE can contain multiple node versions, architectures, and engines - much like our github binary repository. I would have expected to have those shared via some shared, but non-HTTP path in a closed environment.

**Comment by am11** [comment]
@xzyfer, we have:

[SASS_BINARY_NAME](https://github.com/sass/node-sass/blob/78ac14fb1f8ef7d6b231971634a9fc4a0e4f901c/lib/extensions.js#L50-L56)
[SASS_BINARY_SITE](https://github.com/sass/node-sass/blob/78ac14fb1f8ef7d6b231971634a9fc4a0e4f901c/lib/extensions.js#L78-L101)
[SASS_BINARY_PATH](https://github.com/sass/node-sass/blob/78ac14fb1f8ef7d6b231971634a9fc4a0e4f901c/lib/extensions.js#L123-L133)

At the time, I thought this will suffice most of the needs for the original/first requesters, which it did. I took some inspirations form PhantomJS project.
But as always, there is a room for enhancement and as I see it, path to enhancement is paved with zero obstacles here.

**Comment by xzyfer** [comment]
Tracking documentation of these, and other, ENV variables in https://github.com/sass/node-sass/issues/1143

**Comment by DominicTobias** [comment]
If I do:

"nodeSassConfig": {
  "binaryPath": "test-sass/binding.node" // or ./path
}

It seems it is ignored and `npm i node-sass` still tries to compile a binary. How can I get it to work? Thanks

**Comment by DominicTobias** [comment]
Thanks @am11, I'll try SASS_BINARY_PATH again. But yes I think it would be very to have so that behind corporate firewalls a project can be installed without any extra steps!
