### ISSUE TITLE
Release v3.3.1

### ISSUE THREAD

**Issue by rstacruz** [sass/node-sass#1111]
It seems the latest in npm is still 3.2.0. https://www.npmjs.com/package/node-sass

**Comment by moret** [comment]
:+1:

**Comment by nschonni** [comment]
They are on NPM with the `@Beta` tag because of the issues explained in #1107

**Comment by xzyfer** [comment]
@rstacruz @moret the 3.3.x release have been take down due to a issue in a 3rd partly extensions cause segfaults when used with certain other libraries. Subscribe to #1107 for more updates.
