### ISSUE TITLE
A bug in scss|sass parser? if using a @

### ISSUE THREAD

**Issue by prisis** [sass/node-sass#1119]
Hi :),
small question, this behavior is not right?
https://gist.github.com/prisis/f3d7eab8a9eff453fb1c

it should be something like this 
~~~css

  @-webkit-keyframes identifier {
    0% { top: 0; left: 0; }
    30% { top: 50px; }
    68%, 72% { left: 50px; }
    100% { top: 100px; left: 100%; }
  }
  @-moz-keyframes identifier {
    0% { top: 0; left: 0; }
    30% { top: 50px; }
    68%, 72% { left: 50px; }
    100% { top: 100px; left: 100%; }
  }
  @keyframes identifier {
    0% { top: 0; left: 0; }
    30% { top: 50px; }
    68%, 72% { left: 50px; }
    100% { top: 100px; left: 100%; }
  }
~~~

But i get a error, invalid selector after  on line 5 at column 26
If i change @ to a or b it works

**Comment by xzyfer** [comment]
The gist you have supplied does not compile with Ruby Sass and as such will not compile with Node Sass.

http://sassmeister.com/gist/6f0cda31bf2728a6d95a
