### ISSUE TITLE
`& {}` throws unknown error

### ISSUE THREAD

**Issue by Nirazul** [sass/node-sass#1120]
I've noticed that a sass file consisting of only `&{}` throws the following error in node-sass:
```{ [Error: unknown] message: 'unknown', status: 5 }```

...whereas `@{}` for example throws:
```{ [Error: invalid top-level expression] <...more>```

More information about my build:

**Executed command:**
```
var sass = require('node-sass');
sass.render({
  file: '/path/to/file/main.scss',
}, function(err, result) {
    console.log(err);
});
```

**Versions:**
- `node-sass`: 3.3.2
- `node`: 0.12.7
- `npm`: 2.11.3

Is there anything else I can provide to help?

**Comment by saper** [comment]
https://github.com/sass/libsass/wiki/API-Documentation says 5 means "unknown error" :)

**Comment by Nirazul** [comment]
Ok, then this is completely libsass related. 
What would you propose? File a ticket there as this looks like an error or at least the wrong error code?

**Comment by saper** [comment]
I guess it might be https://github.com/sass/libsass/issues/1519 but let me check.

**Comment by saper** [comment]
Here's what Ruby Sass says:

````
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 1 of /home/saper/sw/nodes-sass-problems/1120/test.scss
  Use --trace for backtrace.
````

**Comment by saper** [comment]
A kind of fix is in https://github.com/sass/libsass/pull/1524

**Comment by ChrisCinelli** [comment]
Related to https://github.com/jtangelder/sass-loader/issues/156

**Comment by xzyfer** [comment]
Fixed in https://github.com/sass/node-sass/pull/1214. Will be in v3.4.0.
