### ISSUE TITLE
Using a custom prefix for a style fails with indented syntax (.sass)

### ISSUE THREAD

**Issue by namxam** [sass/node-sass#1121]
I am trying to compile the following file

test.sass
```sass
:global .test
  background-color: #eee
```

via
```bash
./node_modules/node-sass/bin/node-sass -i test.sass test.css
```
but it fails with
```json
{
  "message": "invalid top-level expression",
  "column": 1,
  "line": 1,
  "file": "/path-to-project/test.sass",
  "status": 1
}
```
Doing the same with scss syntax works perfectly. I am not sure if this is intended behaviour or a bug. Interestingly, the same example works on sassmeister.com although they are using node-sass for compilation. But i have no idea why!

For reference, I am trying to use global prefix for react css modules [gajus/react-css-modules#15].

My Setup:
```
> ./node_modules/node-sass/bin/node-sass -v
node-sass	3.3.2	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
```

**Comment by xzyfer** [comment]
@namxam the example given is not valid `.sass` and such will not compile on Node Sass. The `.scss` on the other hand is a super set of CSS and will accept this syntax.

If you think the the `:global/:local: syntax of css modules should be part of the `.sass` syntax you'll need to create an issue with the official Sass repository https://github.com/sass/sass/issues
