### ISSUE TITLE
Build node 4.0 binaries - NODE_MODULE_VERSION 46

### ISSUE THREAD

**Issue by saper** [sass/node-sass#1122]
node 4.0 will probably import V8 4.5, with minor changes to the V8 API (most probably not relevant to our module). `nan` upgrade is not required.

[node 4.0 milestone](https://github.com/nodejs/node/milestones/4.0.0)

https://github.com/nodejs/node/pull/2632 - import of V8 `4.5.103.30`

https://github.com/nodejs/node/pull/2678 -  `NODE_MODULE_VERSION` bump to 46

#### Binaries
- [x] OSX
- [x] Linux 32bit
- [x] Linux 64bit
- [x] Windows 32bit
- [x] Windows 64bit
- [x] FreeBSD 32bit
- [x] FreeBSD 64bit

#### Release
- [x] Back port binaries to v3.3.2
- [ ] ~~Release v3.3.3~~

**Comment by saper** [comment]
I can confirm that node some v4.0.0-pre with the new V8 builds and runs `node-sass` just fine. We just get a new set of modules with a number `46`.

**Comment by xzyfer** [comment]
Cool, so we still need to generate binaries, but there's no real work required?

If we don't need to bump nan and do a new release we can just attach the new binaries to the current release.

**Comment by mzgol** [comment]
`node-sass` doesn't compile for me with Node.js 4.0.0-rc.2:
```
$ node --version
v4.0.0-rc.2
$ npm --version
2.14.2
$ npm i node-sass
npm WARN engine node-sass@3.3.2: wanted: {"node":">=0.10.0"} (current: {"node":"4.0.0-rc.2","npm":"2.14.2"})
(...)
> node-sass@3.3.2 install /Users/mgol/_/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-46_binding.node": HTTP error 404 Not Found

> node-sass@3.3.2 postinstall /Users/mgol/_/node_modules/node-sass
> node scripts/build.js

Building: /Users/mgol/.nvm/versions/node/v4.0.0-rc.2/bin/node /Users/mgol/_/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/mgol/_/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/mgol/_/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/mgol/.nvm/versions/node/v4.0.0-rc.2/bin/node" "/Users/mgol/_/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mgol/_/node_modules/node-sass
gyp ERR! node -v v4.0.0-rc.2
gyp ERR! pangyp -v v2.3.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/mgol/.nvm/versions/node/v4.0.0-rc.2/bin/node" "/Users/mgol/.nvm/versions/node/v4.0.0-rc.2/bin/npm" "i" "node-sass"
npm ERR! node v4.0.0-rc.2
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mgol/_/npm-debug.log
```

**Comment by mzgol** [comment]
Ah, this is most likely due to https://github.com/nodejs/node-gyp/pull/711#issuecomment-138290280; the fix has not been backported to pangyp yet (if ever).

**Comment by saper** [comment]
Just a stupid download problem - try using `--nodedir=your-node-sourcedir` and it will run fine. I am dying rc.1 right niw for testing and it works fine.

**Comment by mzgol** [comment]
You should drop pangyp in favor of node-gyp@3, it handles all these cases, including io.js & Node RCs.

https://twitter.com/rvagg/status/641045378037510144

**Comment by xzyfer** [comment]
It's on the road map @mzgol https://github.com/sass/node-sass/issues/1124

We adopted pangyp to get around node-gyp's lack of iojs support.

**Comment by mzgol** [comment]
Oh, I missed it, sorry.

-- 
Michał Gołębiowski

**Comment by xzyfer** [comment]
A 3rd RC looks scheduled for release in the next 24hrs

**Comment by fhemberger** [comment]
RC5 with working node-gyp is out: https://twitter.com/rvagg/status/641163073206681600
If we don't find any mayor blocker, the final v4.0.0 will be released in a few hours.

**Comment by mzgol** [comment]
The final 4.0.0 is out.

**Comment by yoshokatana** [comment]
Hmm, I'm getting this right now:

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-46_binding.node": HTTP error 404 Not Found
```

**Comment by saper** [comment]
> ```
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-46_binding.node": HTTP error 404 Not Found
> ```

We haven't released node 4.0 binaries yet?

**Comment by yoshokatana** [comment]
Oh! I thought that was what @mzgol was talking about. Alright, I'll be patient. :3

**Comment by saper** [comment]
But it's possible to compile it yourself, if you have a working C++11 compiler. Actually npm proceeds to the building stage after failed install.

**Comment by mzgol** [comment]
@saper It doesn't compile for me on OS X 10.11 public beta 6:
```
$ node --version
v4.0.0
$ npm --version
2.14.2
$ npm install node-sass
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things

> node-sass@3.3.2 install /Users/mgol/_/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-46_binding.node": HTTP error 404 Not Found

> node-sass@3.3.2 postinstall /Users/mgol/_/node_modules/node-sass
> node scripts/build.js

Building: /Users/mgol/.nvm/versions/node/v4.0.0/bin/node /Users/mgol/_/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: /Users/mgol/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/mgol/_/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/mgol/_/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/mgol/.nvm/versions/node/v4.0.0/bin/node" "/Users/mgol/_/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mgol/_/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/mgol/.nvm/versions/node/v4.0.0/bin/node" "/Users/mgol/.nvm/versions/node/v4.0.0/bin/npm" "install" "node-sass"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mgol/_/npm-debug.log

**Comment by mattmewton** [comment]
I am having the same issue as @mzgol above on 10.10. Is there a fix coming soon for this?

**Comment by mzgol** [comment]
Ahh, ignore me. I must have had a broken `~/.node-gyp`, most likely because of trying experimental Node 4.0.0 binaries before. Removign that directory & running `npm install node-sass` again worked. :)

(I knew I should have an enough modern compiler so the issue had to be sth else...)

**Comment by saper** [comment]
On Tue, 8 Sep 2015, Michał Gołębiowski wrote:

> Ahh, ignore me. I must have had a broken `~/.node-gyp`, most likely because of trying experimental Node 4.0.0 binaries before. Removign that directory & running `npm install node-sass` again worked. :)

Michał,

I see you are running on a Mac - can you run `npm test` and see if you run into
https://github.com/sass/node-sass/issues/1127 ? I'd appreciate having your `config.gypi`

**Comment by mzgol** [comment]
> I see you are running on a Mac - can you run `npm test` and see if you run into
> https://github.com/sass/node-sass/issues/1127 ? I'd appreciate having your `config.gypi`

Sure. Let's move the discussion to #1127. :)

**Comment by buunguyen** [comment]
Hi, I got error installing node-sass on Node 4.0 (RTM).

```bash
> node-sass@3.3.2 install /Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.2/darwin-x64-46_binding.node": HTTP error 404 Not Found

> node-sass@3.3.2 postinstall /Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass
> node scripts/build.js

Building: /Users/nn/.nvm/versions/node/v4.0.0/bin/node /Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: /Users/nn/.node-gyp/4.0.0/common.gypi not found (cwd: /Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/nn/.nvm/versions/node/v4.0.0/bin/node" "/Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass/node_modules/pangyp/bin/node-gyp.js" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/nn/Documents/Projects/telfi/telfi-app/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/nn/.nvm/versions/node/v4.0.0/bin/node" "/Users/nn/.nvm/versions/node/v4.0.0/bin/npm" "install" "node-sass"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1

npm ERR! Failed at the node-sass@3.3.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
```

**Comment by saper** [comment]
> Hi, I got error installing node-sass on Node 4.0 (RTM).

Please read this issue before posting. We are not supporting Node 4.0 yet.

**Comment by buunguyen** [comment]
I did read the issue and know you don't support Node 4 yet. Just report the error I have with the RTM release and hope it helps somehow. If it doesn't, please just ignore.

**Comment by xzyfer** [comment]
Sounds like some of there errors are just simply due to the us not having switched back to node-gyp. Even with a 404 when downloading binaries we should be falling back to a local compilations.

**Comment by hinell** [comment]
@saper Hi. How many days it will take for node 4 integration?

**Comment by saper** [comment]
@hinell depends on the hourly rate offered!

**Comment by hinell** [comment]
@saper Ha,ha. Yeah. Great joke. :no_mouth: i: It seems it's time to rollback my nodejs version.

**Comment by xzyfer** [comment]
If you use OSX you should now have Node 4 support.

**Comment by buunguyen** [comment]
@xzyfer it works, thanks a lot!

**Comment by xzyfer** [comment]
\o/ :tada:

**Comment by xzyfer** [comment]
If you use Linux you should now have Node 4 support.

**Comment by mrliptontea** [comment]
when should I expect `46` for Windows?

**Comment by xzyfer** [comment]
Hopefully in the next couple hours. You can always follow our Twitter for more frequent updates.

https://twitter.com/nodesass/status/641469706541604864

**Comment by darkyen** [comment]
\o/

**Comment by xzyfer** [comment]
If you use Window you should now have Node 4 support.

**Comment by mrliptontea** [comment]
yep, it's working :+1: :tada:

**Comment by ingro** [comment]
Yeah is running fine now, thanks @xzyfer !

**Comment by yoshokatana** [comment]
@xzyfer thanks!

**Comment by yosuke-furukawa** [comment]
We are listing Node v4.0 issues in this thread. If you find any other issues, please write the issue and add the following url.
https://github.com/nodejs/node/issues/2798

**Comment by xzyfer** [comment]
@yosuke-furukawa thanks, but we have no issues with Node v4

**Comment by yosuke-furukawa** [comment]
@xzyfer perfect :)

**Comment by Master244** [comment]
Error on ubuntu 14.04 couldn't figure out if this was supported yet or not. Trying to do this in a dockerfile with an Ember project.

Step 21 : RUN npm rebuild node-sass
 ---> Running in 05c1efe63790

> node-sass@3.2.0 install /src/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node": HTTP error 404 Not Found

> node-sass@3.2.0 postinstall /src/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/nodejs node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: /root/.node-gyp/4.1.1/common.gypi not found (cwd: /src/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/src/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "/usr/bin/nodejs" "/src/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /src/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
gyp ERR! node -v v4.1.1
gyp ERR! pangyp -v v2.3.0
gyp ERR! not ok 
Build failed

**Comment by saper** [comment]
@master244 Please use [node-sass@3.3.3](https://github.com/sass/node-sass/releases/tag/v3.3.3) since 3.2.0 does not support node 4.x. This should be the version you install by the plain `npm install node-sass`

**Comment by usta** [comment]
my system is trying to fetch https://github.com/sass/node-sass/releases/download/v3.4.1/linux-x64-47_binding.node
on the other hand it looks like there isn't any x86-47 How can i fix this problem

**Comment by saper** [comment]
> my system is trying to fetch https://github.com/sass/node-sass/releases/download/v3.4.1/linux-x64-47_binding.node
> on the other hand it looks like there isn't any x86-47 How can i fix this problem

We don't support node v5.0.0 yet.

**Comment by saper** [comment]
> my system is trying to fetch https://github.com/sass/node-sass/releases/download/v3.4.1/linux-x64-47_binding.node
> on the other hand it looks like there isn't any x86-47 How can i fix this problem

But you can try to compile node-sass (you need a recent C++ compiler installed to do that).
npm install will start compiling if it fails to download.

**Comment by usta** [comment]
it looks like i need compile it manually because :

gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.0.0-pre
gyp verb command install [ '6.0.0-pre' ]
gyp verb install input version string "6.0.0-pre"
gyp verb detected "pre" node version 6.0.0-pre
gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/lib/node_modules/node-sass/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/lib/node_modules/node-sass/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/lib/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/lib/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.3.0-0.rc6.git2.1.fc24.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/node-sass
gyp ERR! node -v v6.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm verb lifecycle node-sass@3.4.1~postinstall: unsafe-perm in lifecycle false
npm verb lifecycle node-sass@3.4.1~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/node-sass/node_modules/.bin:/usr/lib/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
npm verb lifecycle node-sass@3.4.1~postinstall: CWD: /usr/lib/node_modules/node-sass
npm info lifecycle node-sass@3.4.1~postinstall: Failed to exec postinstall script
npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm verb stack Error: node-sass@3.4.1 postinstall: `node scripts/build.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid node-sass@3.4.1
npm verb cwd /home/usta/Documents/node
npm ERR! Linux 4.3.0-0.rc6.git2.1.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "-g" "install" "node-sass" "--verbose"
npm ERR! node v6.0.0-pre
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

**Comment by saper** [comment]
> gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead

You have to do what it says: Download the source code of the node engine
you are using and use --nodedir /path/to/node/source/code flag to point it to the source.

If it doesn't work for you, just downgrade to node 4.x

You will have the same problems with all node native add-ons, not only with node-sass.

**Comment by mzgol** [comment]
@saper @usta Note, thought, that this should be a problem only for manually compiled pre-releases (I suppose that's the case here). Compiling alphas, rcs etc. should work with newest node-gyp but doesn't for some reason, I reported it in #1224.
