### ISSUE TITLE
Order of includes changed in libsass 3.3

### ISSUE THREAD

**Issue by saper** [sass/node-sass#1123]
I am getting this trying to test an update to #1040 (using https://github.com/sass/libsass/commit/5b4122d62f3f05750ec5745530758f266d66321e):
````
  1) api .render({stats: {}}) should contain an array of all included files:

      Uncaught [ '/home/saper/node_modules/node-sass/test/fixtures/include-files/index.scss',
  '/home/saper/node_modules/node-sass/test/fixtur deepEqual [ '/home/saper/node_modules/node-sass/test/fixtures/include-files/bar.scss',
  '/home/saper/node_modules/node-sass/test/fixtures
      + expected - actual

       [
      -  "/home/saper/node_modules/node-sass/test/fixtures/include-files/index.scss"
         "/home/saper/node_modules/node-sass/test/fixtures/include-files/bar.scss"
         "/home/saper/node_modules/node-sass/test/fixtures/include-files/foo.scss"
      +  "/home/saper/node_modules/node-sass/test/fixtures/include-files/index.scss"
       ]
      
  

  2) api .renderSync({stats: {}}) should contain an array of all included files:

      '/home/saper/node_modules/node-sass/test/fixtures/include-files/index.scss' == '/home/saper/node_modules/node-sass/test/fixtures/include-files/bar.scss'
      + expected - actual

      -/home/saper/node_modules/node-sass/test/fixtures/include-files/index.scss
      +/home/saper/node_modules/node-sass/test/fixtures/include-files/bar.scss
      
````

Is the order now correct?

**Comment by xzyfer** [comment]
@saper I expect the new order is correct. This sounds like it's related to https://github.com/sass/libsass/issues/1262

**Comment by saper** [comment]
so what are we testing here actually :)

**Comment by xzyfer** [comment]
My gut is the test was just based on the output Libsass produced assuming it was correct. Before my time :)

**Comment by saper** [comment]
Not my department, either :)

**Comment by xzyfer** [comment]
I'm not entirely sure either is correct to be honest.

**Comment by xzyfer** [comment]
>`includedFiles` (Array) - Absolute paths to all related scss files in no particular order.

**Comment by saper** [comment]
> >`includedFiles` (Array) - Absolute paths to all related scss files in no particular order.

I'm relieved, thanks!

**Comment by saper** [comment]
Well, still valid - we need to fix the test to ignore the order.

**Comment by xzyfer** [comment]
I figured it all belong in https://github.com/sass/node-sass/pull/1040

**Comment by saper** [comment]
poor me :) no problem

**Comment by saper** [comment]
Should be fixed in https://github.com/saper/node-sass/commit/160eb46a4d9be328fb6b04b484a3ff4ec8b93c97
