### ISSUE TITLE
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.0/binding.node

### ISSUE THREAD

**Issue by datpham23** [sass/node-sass#1136]
Any ideas how to resolve this?
npm: 2.14.2
node: v4.0.0

node-sass@2.1.1 install /Users/dpham/Developer/projects/productexplorer/node_modules/brucke-ui/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.0/binding.node

> node-sass@2.1.1 postinstall /Users/dpham/Developer/projects/productexplorer/node_modules/brucke-ui/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cpp:1:

**Comment by saper** [comment]
You are trying to use node-sass@2.1.1 which is old and we do not provide bindings for the new node editions. Please try node-sass@3.2.2.
