### ISSUE TITLE
Error running sas

### ISSUE THREAD

**Issue by KOSSOKO** [sass/node-sass#1141]
Hi everyone, I start with ionic and when I want to use sass, I don't have compilation.
I got this errors 
Updated F:\Documents\SED\Appli\Demo\www\index.html <link href> references to sass compiled css

Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:188:23)

at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\index.js:3:17)
at Module._compile (module.js:434:26)

Exception with  (CLI v1.6.4)

Your system information:

Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: null
Node Version: v4.0.0

I decided to reinstall gulp and I got this 2nd error

$ npm install gulp-sass
npm WARN package.json demo@1.0.0 No repository field.
npm WARN package.json demo@1.0.0 No README data
npm WARN package.json demo@1.0.0 No license field.
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things

> node-sass@2.1.1 install F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.0/binding.node

> node-sass@2.1.1 postinstall F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Documents\\SED\\Appli\\Demo\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd F:\Documents\SED\Appli\Demo\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed
gulp-sass@1.3.3 node_modules\gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0

I don't know how to resolves it. Thanks in advance.

**Comment by xzyfer** [comment]
You're using node 4 with node-sass@2.1.1. Only node 0.10, and 0.12 are supported with that version.

**Comment by KOSSOKO** [comment]
Yes it works. Thanks

**Comment by xzyfer** [comment]
I've PR'd ionic to fix their broken dependency https://github.com/driftyco/ionic/pull/4449

**Comment by saper** [comment]
@xzyfer I think we should go forward with #1167 , also maybe for 1.x

**Comment by xzyfer** [comment]
Agreed. I planed to do it on the plan but didn't have time.
