### ISSUE TITLE
Issue with nodejs 4

### ISSUE THREAD

**Issue by andrewdonskikh** [sass/node-sass#1164]
Guys I got a problem with latest nodejs - 
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.1/binding.node
And then a bunch of errors.
Could it be resolved somehow?
Thank you.

**Comment by saper** [comment]
You are using 2.1.1 which does not support node 4.0. Please upgrade to the node-sass 3.3.3.

**Comment by xzyfer** [comment]
You're using v2.1.1. That version is very old and only support node 0.10
and 0.12. Upgrade to latest v3.3.3 for iojs and node 4 support.

**Comment by andrewdonskikh** [comment]
Thank you much! Have a perfect day!
