### ISSUE TITLE
Libsass binding not found

### ISSUE THREAD

**Issue by jaesung2061** [sass/node-sass#1165]
I've already read through #918. I've fixed the issue on my local machine (windows 10) but it doesn't work on my server (ubuntu).

The versions are identical on both machines.

Node v4.1.0
Npm v2.14.3
Gulp v3.9.0
Gulp-sass v2.0.4
Node-sass v3.3.3

**Comment by KingScooty** [comment]
Having the same issues with `grunt-sass` on OSX.

**Comment by xzyfer** [comment]
If you've read #918 then you know to follow our [troubleshooting guide](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md) and put **all** of the output into a gist. 

Sadly saying "x doesn't work" doesn't get us any closer to figuring out the problems.

**Comment by saper** [comment]
If you share the same disk/folder between Windows and Ubuntu you need **two** binary files to be installed.

**Comment by jaesung2061** [comment]
I got it working.

The trouble shooting guide says

> Then, using the version number we gather at the beginning, go to https://github.com/sass/node-sass-> binaries/tree/v.
> 
> There you should see a folder with same name as the one in the vendor folder. Download the >binding.node file from that folder and replace your own with it.

I noticed that node-sass was looking for libsass bindings in `linux-x64-46`. However, the folder that was present was `linux-x64-14`. Hopefully that helps?

**Comment by xzyfer** [comment]
This issue is almost always fixed by running `npm rebuild node-sass`. Newer version of node-sass will instruct you to do so.

**Comment by jaesung2061** [comment]
I actually already did that, many times. No errors were thrown but it didn't fix the issue.

**Comment by xzyfer** [comment]
Out of curiosity were you running it in on the failing machine or your local machine?

**Comment by jaesung2061** [comment]
The failing machine. Ubuntu running on Digital ocean server. At least I think... I haven't slept all night I forget what I did exactly. I just know that adding the correct folder and file fixed the problem.

**Comment by jaesung2061** [comment]
Hey @xzyfer, me again. Starting up a new project and the problem sprang up again. Same problem as before. Node-sass is looking for `binding.node` in `vendor/linux-x64-46/`. The folder that's actually there is `vendor/linux-x64-11/`. Running `npm rebuild node-sass` throws an error. Error log outputs this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'rebuild', 'node-sass' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink /usr/bin/node
5 info readInstalled object
6 verbose rebuild path, id [ '/home/vagrant/Code/anvel/node_modules/gulp-sass/node_modules/node-sass',
6 verbose rebuild   'node-sass@3.3.3' ]
7 silly rebuild set [ '/home/vagrant/Code/anvel/node_modules/gulp-sass/node_modules/node-sass' ]
8 info build /home/vagrant/Code/anvel/node_modules/gulp-sass/node_modules/node-sass
9 info preinstall node-sass@3.3.3
10 verbose linkStuff [ false,
10 verbose linkStuff   false,
10 verbose linkStuff   false,
10 verbose linkStuff   '/home/vagrant/Code/anvel/node_modules/gulp-sass/node_modules' ]
11 info linkStuff node-sass@3.3.3
12 verbose linkBins node-sass@3.3.3
13 verbose link bins [ { 'node-sass': 'bin/node-sass' },
13 verbose link bins   '/home/vagrant/Code/anvel/node_modules/gulp-sass/node_modules/.bin',
13 verbose link bins   false ]
14 verbose linkMans node-sass@3.3.3
15 verbose rebuildBundles node-sass@3.3.3
16 verbose rebuildBundles [ 'async-foreach',
16 verbose rebuildBundles   'chalk',
16 verbose rebuildBundles   'cross-spawn',
16 verbose rebuildBundles   'gaze',
16 verbose rebuildBundles   'get-stdin',
16 verbose rebuildBundles   'glob',
16 verbose rebuildBundles   'meow',
16 verbose rebuildBundles   'mkdirp',
16 verbose rebuildBundles   'nan',
16 verbose rebuildBundles   'node-gyp',
16 verbose rebuildBundles   'npmconf',
16 verbose rebuildBundles   'request',
16 verbose rebuildBundles   'sass-graph' ]
17 error Error: UNKNOWN, symlink '../node-sass/bin/node-sass'
18 error If you need help, you may report this *entire* log,
18 error including the npm and node versions, at:
18 error     <http://github.com/npm/npm/issues>
19 error System Linux 3.13.0-30-generic
20 error command "/usr/bin/node" "/usr/bin/npm" "rebuild" "node-sass"
21 error cwd /home/vagrant/Code/anvel
22 error node -v v0.10.32
23 error npm -v 1.4.28
24 error path ../node-sass/bin/node-sass
25 error code UNKNOWN
26 error errno -1
27 verbose exit [ -1, true ]
```

It works on my local machine and deployment server. But for some reason I'm getting the wrong `binding.node` on my vagrant box (the project files are shared between local and vm). Anyways, just wanted to let you know but it's not a major issue for now.

**Comment by saper** [comment]
> 17 error Error: UNKNOWN, symlink '../node-sass/bin/node-sass'
> 18 error If you need help, you may report this *entire* log,
> 18 error including the npm and node versions, at:
> 18 error     <http://github.com/npm/npm/issues>
> 19 error System Linux 3.13.0-30-generic
> 20 error command "/usr/bin/node" "/usr/bin/npm" "rebuild" "node-sass"
> 21 error cwd /home/vagrant/Code/anvel
> 22 error node -v v0.10.32
> 23 error npm -v 1.4.28
> 24 error path ../node-sass/bin/node-sass
> 25 error code UNKNOWN
> 26 error errno -1
> 27 verbose exit [ -1, true ]
> ```
> 
> It works on my local machine and deployment server. But for some
> reason I'm getting the wrong `binding.node` on my vagrant box (the
> project files are shared between local and vm). Anyways, just wanted
> to let you know but it's not a major issue for now.

Apparently your npm has a problem with symbolic links. Can you
try upgrading your npm? Or maybe don't use symbolic links there.
