### ISSUE TITLE
Create 2.1.2 release for engine restrictions for Node > 0.12

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#1167]
Throwing out the idea of publishing a patch release on 2.1.1 that enforces the `engine` property for node =< 0.12 similar to #1014. I'll try and pop on the Slack channel later to discuss this.

**Comment by mattcodez** [comment]
Yes if this is possible that would be great. We were having issues deploying with Dokku and just started guessing that the Node version it was using was too new. Pulled back to 0.12.7 with package.json and all is good now.

**Comment by juliankrispel** [comment]
same, this is quite annoying :(

**Comment by xzyfer** [comment]
The noise appears to have quieted down. Closing this.
