### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by andrezzoid** [sass/node-sass#1169]
Hi, when I try to `npm install --save-dev node-sass`I get the following error:

```
npm ERR! UNKNOWN, symlink '../har-validator/bin/har-validator'
```

I'm using node v0.10.40, npm v3.3.3 in an Ubunbu 14.04 VM. Can you help me figure it out?

**Comment by saper** [comment]
This is probably related to npm@3 and the way it handles existing packages. Try using npm@2 and report the problem to the http://github.com/npm/npm/issues if it's not already there.

**Comment by andrezzoid** [comment]
Thanks for your help. I've tried using npm@2 but the error persisted. In the end, it was a vagrant issue, which I was using to setup my vm.
