### ISSUE TITLE
Node sass package fails to install

### ISSUE THREAD

**Issue by wesharehoodies** [sass/node-sass#1170]
I tried to generate the Yeoman backbone generator. Here's what it's trying to tell me.

$ yo backbone

Binary downloaded and installed at /Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/indreklasn/Work/backbone-app/npm-debug.log

Any clues?

**Comment by saper** [comment]
Can you upgrade to `node-sass@3.3.3`? Just `npm install node-sass`.

**Comment by wesharehoodies** [comment]
Indreks-MBP% sudo npm install node-sass
npm WARN package.json backboneapp@0.0.0 No description
npm WARN package.json backboneapp@0.0.0 No repository field.
npm WARN package.json backboneapp@0.0.0 No README data
npm WARN package.json backboneapp@0.0.0 No license field.

> spawn-sync@1.0.13 postinstall /Users/indreklasn/Work/backbone-app/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

-
> node-sass@3.3.3 install /Users/indreklasn/Work/backbone-app/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/indreklasn/Work/backbone-app/node_modules/node-sass/vendor/darwin-x64-14/binding.node

> node-sass@3.3.3 postinstall /Users/indreklasn/Work/backbone-app/node_modules/node-sass
> node scripts/build.js

` /Users/indreklasn/Work/backbone-app/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.3.3 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── npmconf@2.1.2 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, once@1.3.2, osenv@0.1.3, config-chain@1.1.9, nopt@3.0.4, semver@4.3.6)
├── nan@2.0.9
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)
├── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── gaze@0.5.1 (globule@0.1.0)
├── cross-spawn@2.0.0 (cross-spawn-async@2.0.0, spawn-sync@1.0.13)
├── request@2.63.0 (aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, caseless@0.11.0, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, combined-stream@1.0.5, qs@5.1.0, form-data@1.0.0-rc3, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, hawk@3.1.0, har-validator@1.8.0)
├── sass-graph@2.0.1 (yargs@3.25.0, lodash@3.10.1)
└── node-gyp@3.0.3 (graceful-fs@4.1.2, osenv@0.1.3, semver@5.0.3, nopt@3.0.4, which@1.1.2, minimatch@1.0.0, fstream@1.0.8, glob@4.5.3, path-array@1.0.0, rimraf@2.4.3, tar@1.0.3, npmlog@1.2.1)
_______________________
Indreks-MBP% npm node-sass -v
2.14.1

_______________________

Doesn't seem to upgrade it. I searched  a little on google but didn't find a fix yet.

**Comment by saper** [comment]
> Indreks-MBP% sudo npm install node-sass
> Binary is fine; exiting.
> node-sass@3.3.3 node_modules/node-sass

Everything is fine ^^

(...)
> Indreks-MBP% npm node-sass -v
> 2.14.1

This is your npm version, not node-sass's.

**Comment by wesharehoodies** [comment]
Ah, sorry about that. That was embarrassing. Anyways I updated my Node, NPM and sass-node to the latest versions out there. Deleted my dir, refreshed terminals. 

Then tried again:

$ yo backbone

I get the same error. 

______
Binary downloaded and installed at /Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/indreklasn/Work/backbone-app/npm-debug.log
______
Is the cause somehow by my end?

**Comment by saper** [comment]
On Wed, 23 Sep 2015, Indrek Lasn wrote:

> $ yo backbone
> 
> I get the same error. 
> 
> ______
> Binary downloaded and installed at /Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node
> 
> > node-sass@1.2.3 postinstall /Users/indreklasn/Work/backbone-app/node_modules/grunt-sass/node_modules/node-sass

^^^^^^^^^^^^^^^^^^^^

> Is the cause somehow by my end?

grunt-sass insists you should use node-sass@1.2.3 which is too old to work on your node.
The current version is node-sass@3.3.3

**Comment by jpeguerocastro** [comment]
try...
sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by donshius** [comment]
@jpeguerocastro this has solved the issue for me, thank you

**Comment by bretonio** [comment]
Someone from another forum suggested `npm install --no-optional` to cure this but it did not work for me.

No matter what I do I cannot get past `node-sass` during an `npm install`!

**Comment by wesharehoodies** [comment]
@bretonio try

``` 
$ npm install node-sass global

```

**Comment by sureshamk** [comment]
try with ```yarn ``` Its resolved this kind of issue for me

**Comment by wesharehoodies** [comment]
Hindsight: This happens when you install a new version of Node and before installing a new version you have run `npm install`

Here's how you fix it: `rm -rf node_modules && npm rebuild node-sass && npm i `
