### ISSUE TITLE
invalid selector after

### ISSUE THREAD

**Issue by rapitkan** [sass/node-sass#1174]
node-sass (node_modules/node-sass/lib/index.js:277:32) gives an error 'invalid selector after'.

This is the scss code it tries to translate:

````
@mixin createSelector($selectorName, $properties) {
    .#{$selectorName} {
        @each $property, $value in $properties {
            $property: $value;
        }
    }
}
````

And the problematic character is a dot (line 2 in the code)

I'm using gulp-sass@2.0.4 which uses node-sass@3.3.3

**Comment by saper** [comment]
I have some trouble reproducing this, how are you invoking that mixin?

**Comment by saper** [comment]
Probably related: https://github.com/sass/libsass/issues/1525, https://github.com/sass/libsass/issues/1522

**Comment by rapitkan** [comment]
For example: @include createSelector('Px-xs', ('padding-left': 1em, 'padding-right': 1em));

**Comment by saper** [comment]
Both Ruby Sass and libsass master generate empty output for me (with our without a dot)

**Comment by rapitkan** [comment]
I'm developing this library: https://github.com/niant/once and we can't update to the recent gulp-sass version (which uses node-sass 3.3.3) because of we'll get the 'invalid selector after' error that points to node-sass.

**Comment by saper** [comment]
I need a code that generates this error, please...

**Comment by rapitkan** [comment]
We are solving the problem and it seems that the error is thrown without gulp-sass. But unfortunately I don't have a proper code to give you just now. We'll debug more and get back to this. Big thanks for helping.

**Comment by saper** [comment]
> We are solving the problem and it seems that the error is thrown
> without gulp-sass. But unfortunately I don't have a proper code to
> give you just now. We'll debug more and get back to this. Big thanks
> for helping.

I have tried node-sass 3.3.3 (libsass 3.2.5) and 3.4.0.beta (libsass 3.3.0.beta2)
and both give me an empty output...

**Comment by rapitkan** [comment]
Hi! We got it fixed by interpolating parameters. You can find the changes here: https://github.com/niant/once/commit/1ecf964f340e9c6df98adcf2de819131f29f60a2 It's still unknown why it didn't work without interpolation.
