### ISSUE TITLE
type-of("color-keyword") incorrectly equals to "color"

### ISSUE THREAD

**Issue by nilskaspersson** [sass/node-sass#1175]
When checking the type of a [color keyword](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Color_keywords) enclosed in quotes it returns "color", with the expected result being "string". 

Can the behaviour be changed to `type-of("color-keyword") == string` and `type-of(color-keyword) == color`?

**Comment by saper** [comment]
With the latest and greatest:

````
sassc: 3.3.0-beta1
libsass: 3.3.0-beta2-4-g3686
sass2scss: 1.0.3
````

this one 

````
h1 { font-face: type-of("red") }
h2 { font-face: type-of(red) }
````

generates

````
h1 {
  font-face: string; }

h2 {
  font-face: color; }

````

is this what you need?

You can try this in the node-sass@beta already.

**Comment by saper** [comment]
Probably related: https://github.com/sass/libsass/issues/1525, https://github.com/sass/libsass/issues/1522

**Comment by nilskaspersson** [comment]
>is this what you need?

Yes. I tried out the 3.4 beta build and it behaves as expected. Thank you!
