### ISSUE TITLE
Sourcemaps issue with partial import

### ISSUE THREAD

**Issue by glen-84** [sass/node-sass#1181]
Please accept my apologies in advance if this is not the right place to report this.

With the following task:

```
let cssSrc = "src/**/*.scss";
let cssDest = "dist/styles";

gulp.task("build-css", () => {
    return gulp.src(cssSrc)
        .pipe(sourcemaps.init({debug:true})) //tmp debug
        .pipe(sass().on("error", sass.logError))
        .pipe(sourcemaps.write(".", {debug:true})) //tmp debug
        .pipe(gulp.dest(cssDest));
});
```

A file `/src/a.scss` that has `@import "b";` will have a map that includes `"sources":["a.scss","_b.scss"]`.
A file `/src/app/styles/a.scss` that has `@import "b";` will have a map that includes `"sources":["app/styles/a.scss","_b.scss"]`.

Which results in:

`gulp-sourcemap-write: source file not found: D:\Programming\Projects\x\src\_b.scss`

I assume it's supposed to include the full path to `_b.scss` in sources?

**Comment by saper** [comment]
can you reproduce the problem without gulp-sass? Also it would be good to have a small repository with minimal test files to reproduces this.

**Comment by glen-84** [comment]
I'm not able to repro using node-sass directly. Would this be a gulp-sass or gulp-sourcemaps issue?

Sorry. :fearful:

**Comment by glen-84** [comment]
I think it's [this](https://github.com/dlmanning/gulp-sass/issues/319).

Closing.
