### ISSUE TITLE
how come vendor directory is ignored in package.json?

### ISSUE THREAD

**Issue by gkatsev** [sass/node-sass#1183]
I'm using node-sass in a build project of sorts which gets packaged on a CI/CD server using `npm pack`. However, because the [`package.json` is ignoring it in the files array](https://github.com/sass/node-sass/blob/v3.3.3/package.json#L35-L41) `npm pack` isn't including it in the output tarball.
Our CI runs on the same architecture of the prod machine, so, it should just work if the binary were to be included.

Thanks!

**Comment by saper** [comment]
We have decided not to include [binaries](https://github.com/sass/node-sass-binaries) into the npm package because currently there are 49 of them, weighting total 409 MB.

**Comment by gkatsev** [comment]
I understand not including the binaries in the package. My issue is that when I package up my app which depends on `node-sass`, node-sass ends up not including the downloaded binaries and my app breaks.
I'm not asking for the binaries to be distributed with `node-sass` but rather when that when I run `npm pack` on my package, `node-sass` currently-downloaded-binary will get included in the generated tarball. This way, I won't be required to run `npm rebuild` when running my app in my production server.
Does this make sense? If not, I'll try and make an example to make it clearer.

**Comment by xzyfer** [comment]
@gkatsev we understand your issue. Do you have a suggested fix that would not result in us publishing the binaries to npm?

**Comment by gkatsev** [comment]
Including `vendor` in the `package.json` is necessary. Then, a `prepublish` script can make sure to delete the vendor directory before npm publish node-sass so it doesn't accidentally get added to a release of `node-sass`. And then when a dependent `npm pack`s their app, the `vendor` directory gets added in their package and not ignored. I've just tested this out locally and seems to be working as expected.
I can PR this if that sounds like a good plan. Otherwise, I'll try and think of what other options are available.

**Comment by xzyfer** [comment]
Sounds good. We'd be happy to see a PR.

**Comment by gkatsev** [comment]
I haven't forgotten about this. Been away last week, hope to get a PR out this week.

**Comment by gkatsev** [comment]
So, I've started finally looking at this in detail. Unfortunately, `prepublish` runs on both `npm install` and `npm publish`, which means that if you clone this repo and run `npm install` with the current change, it will download/build the binary but then it will run `prepublish` and the `vendor` directory will be removed.
Looking into making it run only on `publish`.

**Comment by gkatsev** [comment]
It's possible there isn't an answer here until https://github.com/npm/npm/issues/10074 is resolved.

**Comment by gkatsev** [comment]
I think a workaround is available by using this module: https://github.com/iarna/in-publish

**Comment by gkatsev** [comment]
Sorry it's taken so long but I finally have a PR ready for this in #1384.
