### ISSUE TITLE
Live test page request

### ISSUE THREAD

**Issue by yairEO** [sass/node-sass#1184]
Would be nice to have a live test page, like http://sassmeister.com/ which would have an option to choose from a list of node-sass version, to test for bugs and features, so it would be much easier to report them and reproduce. just a though. 

I was just encountering a bug, and it seems such a waste of time for me to set up some way to reproduce it so someone could see.

**Comment by saper** [comment]
sassmeister is offering to use libsass, which is what node-sass uses. node-sass@3.3.3 is using libsass 3.2.5, available on sassmeister.

**Comment by saper** [comment]
And actually https://github.com/SassMeister/libsass.sassmeister is using node-sass to do the job :)

**Comment by xzyfer** [comment]
@yairEO I would suggesting opening an issue with Sassmeister to support multiple node-sass/libsass versions. This is not something that is relevant to this project.
