### ISSUE TITLE
node-sass 3.3.3 does not seem to work on Node 4

### ISSUE THREAD

**Issue by mikemaccana** [sass/node-sass#1185]
Per https://github.com/sass/node-sass/issues/1122, I am using the latest node-sass on the current stable node release.

However building fails on pangyp:

    $ npm install --save node-sass@latest
    npm WARN prefer global node-gyp@3.0.3 should be installed with -g

    > node-sass@2.1.1 install /var/www/myapp/node_modules/mylib/node_modules/gulp-sass/node_modules/node-sass
    > node scripts/install.js

    Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-4.1/binding.node

    > node-sass@3.3.3 install /var/www/myapp/node_modules/mylib/node_modules/node-sass
    > node scripts/install.js

    Binary downloaded and installed at /var/www/myapp/node_modules/mylib/node_modules/node-sass/vendor/linux-x64-46/binding.node

    > node-sass@2.1.1 postinstall /var/www/myapp/node_modules/mylib/node_modules/gulp-sass/node_modules/node-sass
    > node scripts/build.js

    module.js:338
        throw err;
        ^

    Error: Cannot find module '/var/www/myapp/node_modules/mylib/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Function.Module.runMain (module.js:475:10)
        at startup (node.js:117:18)
        at node.js:951:3
    Build failed

    > spawn-sync@1.0.13 postinstall /var/www/myapp/node_modules/mylib/node_modules/spawn-sync
    > node postinstall

    > node-sass@3.3.3 postinstall /var/www/myapp/node_modules/mylib/node_modules/node-sass
    > node scripts/build.js

    ` /var/www/myapp/node_modules/mylib/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists.
     testing binary.
    Binary is fine; exiting.
    ansi-regex@0.2.1 node_modules/node-sass/node_modules/ansi-regex -> node_modules/gulp-sass/node_modules/ansi-regex
    ansi-styles@1.1.0 node_modules/node-sass/node_modules/ansi-styles -> node_modules/gulp-sass/node_modules/ansi-styles
    has-ansi@0.1.0 node_modules/node-sass/node_modules/has-ansi -> node_modules/gulp-sass/node_modules/has-ansi
    nan@1.9.0 node_modules/node-sass/node_modules/nan -> node_modules/gulp-sass/node_modules/nan
    object-assign@2.1.1 node_modules/node-sass/node_modules/object-assign -> node_modules/gulp-sass/node_modules/object-assign
    strip-ansi@0.3.0 node_modules/node-sass/node_modules/strip-ansi -> node_modules/gulp-sass/node_modules/strip-ansi
    supports-color@0.2.0 node_modules/node-sass/node_modules/supports-color -> node_modules/gulp-sass/node_modules/supports-color
    chalk@0.5.1 node_modules/node-sass/node_modules/chalk -> node_modules/gulp-sass/node_modules/chalk
    mylib@1.4.2 /var/www/myapp/node_modules/mylib
    ├─┬ gulp@3.9.0
    │ └─┬ liftoff@2.2.0
    │   └─┬ findup-sync@0.3.0
    │     └── glob@5.0.15
    ├─┬ gulp-if@1.2.5
    │ └─┬ gulp-match@0.2.1
    │   └── minimatch@1.0.0
    ├─┬ gulp-sass@1.3.3
    │ └─┬ node-sass@2.1.1
    │   └── get-stdin@4.0.1
    ├─┬ gulp-uglify@1.4.1
    │ └─┬ uglify-js@2.4.24
    │   └─┬ yargs@3.5.4
    │     └── wordwrap@0.0.2
    ├─┬ multiline@1.0.2
    │ └─┬ strip-indent@1.0.1
    │   └── get-stdin@4.0.1
    └─┬ node-sass@3.3.3
      ├── async-foreach@0.1.3
      ├─┬ cross-spawn@2.0.0
      │ ├─┬ cross-spawn-async@2.0.0
      │ │ └─┬ which@1.1.2
      │ │   └─┬ is-absolute@0.1.7
      │ │     └── is-relative@0.1.3
      │ └─┬ spawn-sync@1.0.13
      │   └── os-shim@0.1.3
      ├── get-stdin@4.0.1
      ├── glob@5.0.15
      ├─┬ meow@3.3.0
      │ └─┬ indent-string@1.2.2
      │   └── get-stdin@4.0.1
      ├─┬ node-gyp@3.0.3
      │ ├─┬ fstream@1.0.8
      │ │ └── graceful-fs@4.1.2
      │ ├── graceful-fs@4.1.2
      │ ├── minimatch@1.0.0
      │ └─┬ path-array@1.0.0
      │   └── array-index@0.1.1
      └─┬ sass-graph@2.0.1
        ├── lodash@3.10.1
        └─┬ yargs@3.26.0
          ├─┬ cliui@2.1.0
          │ ├─┬ center-align@0.1.1
          │ │ └─┬ align-text@0.1.3
          │ │   ├── kind-of@2.0.1
          │ │   ├── longest@1.0.1
          │ │   └── repeat-string@1.5.2
          │ ├── right-align@0.1.3
          │ └── wordwrap@0.0.2
          ├─┬ os-locale@1.4.0
          │ └─┬ lcid@1.0.0
          │   └── invert-kv@1.0.0
          ├── window-size@0.1.2
          └── y18n@3.2.0

node-sass then complains it is doesn't have a working binary:

    $ gulp
    /var/www/myapp/node_modules/mylib/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
        throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
        ^

    Error: `libsass` bindings not found. Try reinstalling `node-sass`?
        at getBinding (/var/www/myapp/node_modules/mylib/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
        at Object.<anonymous> (/var/www/myapp/node_modules/mylib/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/var/www/myapp/node_modules/mylib/node_modules/gulp-sass/index.js:3:17)
        at Module._compile (module.js:434:26)

**Comment by Lothiraldan** [comment]
Same error here

**Comment by saper** [comment]
As one can see from the npm output you are getting node-sass 2.1.1, not 3.3.3. You need to update your project dependencies, since the newest gulp-sass uses the newest node-sass as well.

**Comment by mikemaccana** [comment]
Yep @saper you're correct: I had both 3.3.3 installed top level and 2.1.1 installed deeper in the same dependency tree. I cleaned out my tree and used npm v3 (which installs to the top level by default) to reduce the redundancy.

**Comment by ericdiviney** [comment]
Could you elaborate more on how you "cleaned out your tree"? I seem to be having the same problem that you did, but I'm not sure what "cleaning out the tree" means.

Thanks!

**Comment by saper** [comment]
> Could you elaborate more on how you "cleaned out your tree"? I seem to be having the same problem that you did, but I'm not sure what "cleaning out the tree" means.

Most probably "rm -rf node_modules"

Did you try "npm rebuild node-sass" already?

**Comment by andfinally** [comment]
Thanks, cleaning out node_modules and reinstalling everything fixed it for me.

**Comment by saper** [comment]
@Lothiraldan clean your dependencies as indicated above.
