### ISSUE TITLE
Error reported on wrong line

### ISSUE THREAD

**Issue by martinleopold** [sass/node-sass#1186]
Using node-sass 3.3.3 (through gulp-sass 2.0.4), I discovered an issue through working on an ionic project (which includes a lot of scss partials). I narrowed the issue down to the following simple test case:

```
$percentage: 10%; // line 1
// line 2
$conflict: $percentage + 20px; // line 3
```

This results in node sass reporting an error on line 1:
```
Error: test.scss
  1:14  Incompatible units: 'px' and '%'.
    at options.error (/Users/ml/Documents/_Work/dc/_local/dc/node_modules/node-sass/lib/index.js:277:32)
```

while ruby sass reports the corret line:
```
Error: Incompatible units: 'px' and '%'.
        on line 3 of test.scss
  Use --trace for backtrace.
```

You can imagine this results in hard to find errors, since the error message points to some line while the error is actually on another line in a different file etc.
I was only able to track it down through using ruby sass.

**Comment by xzyfer** [comment]
Thanks @martinleopold! I've confirmed this is a LibSass bug. Tracking upstream in https://github.com/sass/libsass/issues/1577
