### ISSUE TITLE
Is there a way to not download the *_binding.node file from internet?

### ISSUE THREAD

**Issue by leochen1216** [sass/node-sass#1190]
Version: 3.4.0-beta1
Platform: linux

I'm getting the following error when I try to `npm rebuild` this node module on build machine. 
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.0-beta1/linux-x64-11_binding.node": 
```
The build server in my company can't connect to internet for security reason.
Is there a way to walkaround this issue?

**Comment by xzyfer** [comment]
Yes. The binary URL resolution and download behaviour can be controlled by
the following settings
https://github.com/sass/node-sass/blob/master/README.md#binary-configuration-parameters

**Comment by leochen1216** [comment]
It works, thank you!
