### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by at0g** [sass/node-sass#1193]
When attempting to compile the following scss:

```
.recursive-thing {
  &:not(& &) {
	color: red;
  }
}
```

**node-sass fails with _segmentation fault 11_.**

My environment:
```
OS X 10.10.5
node 0.12.5
npm 2.11.2
node-sass 3.3.3
libsass 3.2.5
```

**Comment by saper** [comment]
Works for me with 

````
node-sass	3.4.0-beta1	(Wrapper)	[JavaScript]
libsass  	3.3.0.b2+FreeBSD.	(Sass Compiler)	[C/C++]
````

so it is fixed in the beta version of libsass.

**Comment by xzyfer** [comment]
@at0g this has been fixed the current beta.

```
npm install node-sass@beta
```

**Comment by xzyfer** [comment]
Fixed in https://github.com/sass/node-sass/pull/1214. Will be in v3.4.0.
