### ISSUE TITLE
Behavior when you set both file and data

### ISSUE THREAD

**Issue by sebakerckhof** [sass/node-sass#1195]
Node sass requires you to either set the file or data option. However, when you set both the behavior seems to be: data is preferred over file, except if data is an empty string.
IMO, it would be better to always prefer data as long as it is a set and it is a string, even when empty.

The reason I set both is so I get a previous path in the custom importer I wrote. However the file path I set is a special one for the Meteor framework which looks like: ' {meteor packagename}/path/to/style.scss', which, of course, node-sass does not understand and will throw an error. Normally, node-sass does not try to process this file as long as I also specify data, but sometimes the scss file is empty, resulting in an empty data string.

If I do not set the file, but only the data, then in the custom importer I wrote, I get 'stdin' as previous path, but this could give errors in the (rare) case somebody would have a file named 'stdin.scss'.

I hope it's clear, otherwise I'll try to come up with an example repo to show the problem.

**Comment by xzyfer** [comment]
Thanks for the issue. This is on purpose. We're simply relying on
JavaScript falsey type coercion. We do this as a fail safe for poor
implementation of node sass. This is something we may be open to changing
but it would be a breaking change.

As mentioned in a previous issue, I question the need to rely so heavily on
prev in custom importers.

**Comment by xzyfer** [comment]
For the time being the behaviour when passing both data and file is considered undefined, and liable to change without notice. It's documented that only one can be used.
