### ISSUE TITLE
Is mandatory to install node-sass if already have gulp-sass?

### ISSUE THREAD

**Issue by MXTcomunica** [sass/node-sass#1199]
Sorry for this newbie question, but I'm a... Newbie

I'm using GULP, and in a project I have "gulp-sass" as dependency in my package.json.

I NEVER had installed node-sass using npm install node-sass (not locally in that project, not globally, not in other projects, NEVER).

SASS preprocessing works fine and my .scss files generates .css without problem.

The doubt is: is libsass used in this conversion? If yes: how is this possible if I've never installed node-sass ?

Thank you very much.

**Comment by xzyfer** [comment]
Hi. Yes gulp-sass installs node-sass for you because it can't work without
it. It's worth reading about npm to learn how dependency management works
in node.
