### ISSUE TITLE
Error: The `libsass` binding was not found

### ISSUE THREAD

**Issue by jkim-pmap** [sass/node-sass#1202]
I went through the entire Troubleshooting guide and got to the very last step `node -p "console.log(require('node-sass').info)"` and got this error from the command line: 

```
jkim:temp1 jkim$ Error: The `libsass` binding was not found in /Users/jkim/temp1/node_modules/node-sass/vendor/darwin-x64-46/binding.node
-bash: libsass: command not found
-bash: Error:: command not found
jkim:temp1 jkim$ node -p "console.log(require('node-sass').info)"
node-sass	3.3.3	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
undefined
```

**Comment by saper** [comment]
Where those `Error:` lines come from? Something got pasted wrongly.

````
node -p "console.log(require('node-sass').info)"
node-sass   3.3.3   (Wrapper)   [JavaScript]
libsass     3.2.5   (Sass Compiler) [C/C++]
````

the above is correct and indicates node-sass got installed properly.

**Comment by jkim-pmap** [comment]
I replaced the original binding.node file in vendor > darwin-x64-46 folder with the matching one from (here)[https://github.com/sass/node-sass-binaries/]. Then I put `node -p "console.log(require('node-sass').info)"` into the command line, and that's when it throws the error that `libsass` binding was not found.

**Comment by jkim-pmap** [comment]
Found the solution; my package.json file had `"gulp-sass": "^1.3.3"`. Did `npm uninstall gulp-sass` and `npm install gulp-sass --save-dev` and it changed from ^1.3.3 to `"gulp-sass": "^2.0.4"`. Thank you for your help!

**Comment by saper** [comment]
Older gulp-sass installed old node-sass, which does not support node 4.0. Good to hear it works now!
