### ISSUE TITLE
When will variable interpolation in @imports be supported?

### ISSUE THREAD

**Issue by peterjwest** [sass/node-sass#1203]
I'm not really sure how this tracks the main SASS library. This feature doesn't seem to be available yet, but maybe I'm just making a mistake.

**Comment by xzyfer** [comment]
Do you have an example of what you mean?

**Comment by peterjwest** [comment]
Something like this:
```
$bootstrapDir: "../../bower_components/bootstrap-sass";
@import "#{$bootstrapDir}/assets/stylesheets/bootstrap/variables";
```

**Comment by xzyfer** [comment]
As far as I'm aware this is not yet support in Ruby Sass. Node Sass is just an implementation of the Ruby Sass language. All language feature requests need to be opened with them http://github.com/sass/sass
