### ISSUE TITLE
node@3.3.3 broken with npm shrinkwrap

### ISSUE THREAD

**Issue by geminiyellow** [sass/node-sass#1207]
hello everyone, i try to use `npm shrinkwrap` to my project.
but in travis ci, the node-sass@3.3.3 will cause an error.

```
├── UNMET PEER DEPENDENCY node-sass@^3.3.3
```

i check my npm-shrinkwrap file, node-sass is not in this file.
who can tell me how to fix this?

**Comment by saper** [comment]
which project are you building a shrinkwrap for? is node-sass listed there as a dependency?

**Comment by xzyfer** [comment]
Looks an issue with another package with has a peer dependency on node-sass. Peer dependencies should be avoided.

**Comment by geminiyellow** [comment]
@saper @xzyfer no,just in `devDependences` , something like this.

```
  "devDependencies": {
    ...
    "bootstrap-sass": "^3.3.5",
    "bootstrap-sass-loader": "^1.0.9",
    "css-loader": "^0.20.2",
    "file-loader": "^0.8.4",
    "imports-loader": "^0.6.5",
    "loader-utils": "^0.2.11",
    "node-libs-browser": "^0.5.3",
    "node-sass": "^3.3.3",
    "phantomjs": "^1.9.18",
    "react": "^0.14.0",
    "react-addons-test-utils": "^0.14.0",
    "react-bootstrap": "^0.27.2",
    "react-dom": "^0.14.0",
    "react-hot-loader": "^1.3.0",
    "sass-loader": "^3.0.0",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.6",
    "webpack-dev-server": "^1.12.1"
    ...
  }
```

**Comment by geminiyellow** [comment]
@xzyfer 

yes, `sass-loader` use `node-sass` in `peerDependencies`
and, `bootstrap-sass` use `node-sass` in `devDependencies`

**Comment by saper** [comment]
> @xzyfer 
> 
> yes, `sass-loader` use `node-sass` in `peerDependencies`
> and, `bootstrap-sass` use `node-sass` in `devDependencies`

devDependencies are fine.

Make sure you are using the latest sass-loader and raise the issue with them.

**Comment by geminiyellow** [comment]
@saper thank you sir, i check my packages by `ncu --upgradeAll`, all my package is the latest version.

**Comment by xzyfer** [comment]
Closing since there is nothing we can do.
