### ISSUE TITLE
3.4.0-beta.2 incorrectly published on npm

### ISSUE THREAD

**Issue by billyjanitsch** [sass/node-sass#1208]
`3.4.0-beta2` has been incorrectly published as `3.4.0-beta.2` (extra period before the 2). This causes version-checking packages like `npm-check-updates` to misinterpret it as a stable release.

**Comment by xzyfer** [comment]
This wasn't a mistake, `3.4.0-beta1` was incorrectly released with the extra `.` as per the node-semver spec - https://github.com/npm/node-semver#prerelease-tags

**Comment by xzyfer** [comment]
We won't fixing this because the changing the tag will just shift the problem on to other users. We expect 3.4.0 stable to land this week.

**Comment by billyjanitsch** [comment]
Ah, sorry, my mistake! Thanks for clarifying.

**Comment by xzyfer** [comment]
This sounds like a bug worth opening with npm-check-updates
