### ISSUE TITLE
"npm install" then error "libsass` binding was not found", manual execute "npm install node-sass" then ok.

### ISSUE THREAD

**Issue by ustccjw** [sass/node-sass#1209]
mac osx

```
$ node -v     
v4.1.2
$ npm -v     
v3.3.7
```

**Comment by saper** [comment]
`npm install` what failed?

Check your project for outdated dependencies an make sure you are using only the newest version of node-sass,

**Comment by ustccjw** [comment]
`npm install` is ok, but execute(webpack bundle) will report error "libsass binding was not found".

After manual execute "npm install node-sass" , that is ok

**Comment by ustccjw** [comment]
I just don't understand  the difference between `npm install` and `npm install node-sass` for `node-sass`.

**Comment by saper** [comment]
> I just don't understand  the difference between `npm install` and `npm install node-sass` for `node-sass`.

What are you trying to install with `npm install` ? How does your `package.json` look like?

**Comment by ustccjw** [comment]
oh, it's npm 3.3.7 bug, 3.3.8 has fixed. https://github.com/npm/npm/issues/9922
