### ISSUE TITLE
Install fails with: 'node' is not recognized as an internal or external command... on Windows 10

### ISSUE THREAD

**Issue by saturdayplace** [sass/node-sass#1210]
I'm new to node.js so I'm happy to add any other details I've overlooked

    D:\Users\saturdayplace\Documents\www\accntr>mkdir \temp1

    D:\Users\saturdayplace\Documents\www\accntr>cd \temp1

    D:\temp1>npm -v
    3.3.7

    D:\temp1>node -v
    v4.1.2

    D:\temp1>which node
    C:\Program Files\nodejs\node.EXE

    D:\temp1>node -p process.versions
    { http_parser: '2.5.0',
      node: '4.1.2',
      v8: '4.5.103.35',
      uv: '1.7.5',
      zlib: '1.2.8',
      ares: '1.10.1-DEV',
      modules: '46',
      openssl: '1.0.2d' }

    D:\temp1>node -p process.platform
    win32

    D:\temp1>node -p process.arch
    x64

    D:\temp1>npm install node-sass

    > node-sass@3.3.3 install D:\temp1\node_modules\node-sass
    > node scripts/install.js

    'node' is not recognized as an internal or external command,
    operable program or batch file.
    npm WARN ENOENT ENOENT: no such file or directory, open 'D:\temp1\package.json'
    npm WARN EPACKAGEJSON temp1 No description
    npm WARN EPACKAGEJSON temp1 No repository field.
    npm WARN EPACKAGEJSON temp1 No README data
    npm WARN EPACKAGEJSON temp1 No license field.
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
    npm ERR! node v4.1.2
    npm ERR! npm  v3.3.7
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@3.3.3 install: `node scripts/install.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-sass@3.3.3 install script 'node scripts/install.js'.
    npm ERR! This is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/install.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\temp1\npm-debug.log

D:\temp1\node_modules does not contain a node-sass directory

npm-debug.log is at https://gist.github.com/saturdayplace/e6203909df0bee7f1bb6

**Comment by saper** [comment]
What happens if you type `cmd.exe /c node` ?

**Comment by saturdayplace** [comment]
I get dropped into some interactive prompt. (I'm totally new to node, so I'm not sure what it's called)

    D:\tmp1>cmd.exe /c node
    >

I have to ctrl-d to get out

**Comment by saper** [comment]
One quick hint: try to upgrade to npm 3.3.8.

**Comment by saturdayplace** [comment]
Looks like that solved whatever was the problem. Many thanks!

**Comment by saper** [comment]
Yep, the problem was https://github.com/npm/npm/issues/9922. Good to hear it works now!
