### ISSUE TITLE
CLI appends raw souce map content to css when --embed-source-map is provided and no outfile is provided

### ISSUE THREAD

**Issue by danielknell** [sass/node-sass#1211]
when the cli is used without specifying an output file and source maps are enabled it will pipe the source map to stdout after the css content, this makes it impossible to pipe the output into other tools when using `--source-map-embed` to inline the source map.

```
$ node_modules/.bin/node-sass --source-map true --source-map-embed --source-map-contents theme/styles/test.scss
body {
  background: #eee; }

/*# sourceMappingURL=data:application/json;base64,ewoJInZlcnNpb24iOiAzLAoJImZpbGUiOiAiLi4vdGhlbWUvc3R5bGVzL3Rlc3QuY3NzIiwKCSJzb3VyY2VzIjogWwoJCSIuLi90aGVtZS9zdHlsZXMvdGVzdC5zY3NzIgoJXSwKCSJzb3VyY2VzQ29udGVudCI6IFsKCQkiYm9keSB7XG4gICAgYmFja2dyb3VuZDogI2VlZTtcbn0iCgldLAoJIm1hcHBpbmdzIjogIkFBQUEsSUFBSSxDQUFDO0VBQ0QsVUFBVSxFQUFFLElBQUssR0FEZiIsCgkibmFtZXMiOiBbXQp9 */
{
    "version": 3,
    "file": "../theme/styles/test.css",
    "sources": [
        "../theme/styles/test.scss"
    ],
    "sourcesContent": [
        "body {\n    background: #eee;\n}"
    ],
    "mappings": "AAAA,IAAI,CAAC;EACD,UAAU,EAAE,IAAK,GADf",
    "names": []
}
```

i was hoping to be able to take the output and pipe it into other tools that can process the css and inline source map before writing to disk but the appended json breaks things.

```
$ node_modules/.bin/node-sass --version
node-sass   3.3.3   (Wrapper)   [JavaScript]
libsass     3.2.5   (Sass Compiler) [C/C++]
```

**Comment by danielknell** [comment]
the problem is caused here:

https://github.com/sass/node-sass/blob/master/lib/render.js#L60

if it were changed to the following then the embedded source map would function fine and could be piped into other tools.

```javascript
      if (sourceMap && !options.sourceMapEmbed) {
        emitter.emit('log', result.map.toString());
      }
```

I wanted to send this as a pull request but i am having trouble getting the tests to run so may not be able too.

**Comment by xzyfer** [comment]
Apologies for the failing tests. There is a race condition we're working on.
