### ISSUE TITLE
why don't use the lastest version of python(>v3.0.0,  v3.4.3 etc.)

### ISSUE THREAD

**Issue by fuchao2012** [sass/node-sass#1225]
python version have release for a while. why don't the project use the new version of python ?

i need to reinstall python old version to ONE project. 

what the F...

**Comment by xzyfer** [comment]
This is how node complies native extensions. This is a node issue, not a
node sass one. All native extensions require python 2.

**Comment by saper** [comment]
https://bugs.chromium.org/p/gyp/issues/detail?id=36 some people consider python 2.x "ancient", heh.
