### ISSUE TITLE
absolute paths in importer 

### ISSUE THREAD

**Issue by tcurdt** [sass/node-sass#1226]
I am trying to write an importer that properly resolves `import`s and reads the content from memory (instead of from disk).

The following code almost gets me there - but I have no clue how to get from the `url` to an actual absolute path on disk.

      Sass.render({
        data: '@import "some/path"',
        importer: function(url, prev, done) {

          console.log('FILE', url, prev);
          
          var pathAbs = ??(url);
          if (ok) {
            done({
              file: pathAbs,
              contents: ''
            });
          } else {
            done({});
          }

        }
      }), function(err, result) {
        if (err) {
          console.log("KO", err);
        } else {
          console.log("OK", result.css.toString());
        }
      });

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/1219

**Comment by tcurdt** [comment]
@xzyfer on the first call `prev` is `stdin` - which is clearly because the input is not coming from the file system.

At the moment I work around this by catching that case and provide the proper path - but is there a way to set the filename up front somehow?

**Comment by saper** [comment]
How are you invoking node-sass? If the scss templates comes from stdin there is no way for any program to know where it comes from. It could be generated automatically on the fly, for example.

**Comment by tcurdt** [comment]
@saper other libraries usually let you explicitly specify a path just for that case.

      Sass.render( {}, {
        data: 'input',
        importer: function(argument, parent, done) {

          if (parent == 'stdin') {
            // catch the corner case
            parent = pathParent;
          }

        }
      }), function(err, result) {
        ...
      });

Something like:

      Sass.render( {}, {
        data: 'input',
        filename: 'filename',
        ...

**Comment by xzyfer** [comment]
This is fixed in v3.4.2

**Comment by tcurdt** [comment]
@xzyfer ace! thanks

**Comment by tcurdt** [comment]
@xzyfer which commit is it?

**Comment by xzyfer** [comment]
https://github.com/sass/node-sass/pull/1220

**Comment by tcurdt** [comment]
@xzyfer thanks

What about the initial filename?
Keep my work around or should I open another issue as feature request?

**Comment by xzyfer** [comment]
Please open a new issue with a fully working example (preferably a GitHub repo).
