### ISSUE TITLE
Is it possible to pass data to the compiled css using the CLI?

### ISSUE THREAD

**Issue by Duder-onomy** [sass/node-sass#1228]
Hello, 

I am trying to use this [`data`](https://www.npmjs.com/package/node-sass#data) option with the cli?  If it is possible, can you give a quick example?

I cannot tell from the docs or the source if it is implemented. When trying things like `--data` or `-d` I get errors.

**Comment by xzyfer** [comment]
Yes. More info in https://github.com/sass/node-sass/issues/382
