### ISSUE TITLE
Cannot download win32-x64-47_binding.node

### ISSUE THREAD

**Issue by heikkilamarko** [sass/node-sass#1230]
I am running the following npm install:

`$ npm install node-sass`

I get the following error logged in the console:

`Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.1/win32-x64-47_binding.node"`

It seem that `win32-x64-47_binding.node` is missing from the list here:

`https://github.com/sass/node-sass/releases`

**Comment by xzyfer** [comment]
Node 5 only just came out. The system we use to build windows binaries
hasn't been updated yet.

**Comment by russellpabon** [comment]
I have the same issues. What is the other option for this? like how to install previous version instead of win32-x64-47_binding.node

**Comment by xzyfer** [comment]
The solution is not using node 5.

**Comment by worc** [comment]
i ran into the same issue, and yes, node-sass works just fine under v4.2.1.

**Comment by namerci** [comment]
I have installed Visual Studio Community 2015 and node-sass works perfectly with node 5. I don't know if this will help.

**Comment by NicolasParada** [comment]
I already have VS2015 and  no help.

**Comment by xzyfer** [comment]
Windows Node 5 binary is now available for v3.4.1 **only**. Just npm install.
