### ISSUE TITLE
Having issue with node-sass and Heroku

### ISSUE THREAD

**Issue by ericwebster** [sass/node-sass#1233]
Hey Guys,

Been trying to figure this one out for a few days. Running locally (windows 10, python installed) Node-sass compiles with my build just fine.

But when I push it to Heroku its failing. If I take node-sass out of my package.json it deploys.. so I'm pretty sure its related to node-sass.

I have tried NodeJS 4.x and 0.12.2, both fail.

Also update to NPM 3.3.10

Below is a log of my build, any ideas would be awesome. Thanks

===========================================================
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 371 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Using set buildpack heroku/nodejs
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  0.12.2
remote:        engines.npm (package.json):   3.3.10
remote:
remote:        Downloading and installing node 0.12.2...
remote:        Downloading and installing npm 3.3.10 (replacing version 2.7.4)...
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > kerberos@0.0.11 install /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/kerberos
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:
remote:        make: Entering directory `/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/kerberos/build'
remote:        CXX(target) Release/obj.target/kerberos/lib/kerberos.o
remote:        CXX(target) Release/obj.target/kerberos/lib/worker.o
remote:        CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
remote:        CC(target) Release/obj.target/kerberos/lib/base64.o
remote:        CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
remote:        SOLINK_MODULE(target) Release/obj.target/kerberos.node
remote:        COPY Release/kerberos.node
remote:        make: Leaving directory `/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/kerberos/build'
remote:
remote:        > bson@0.2.22 install /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/bson
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:
remote:        make: Entering directory `/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/bson/build'
remote:        CXX(target) Release/obj.target/bson/ext/bson.o
remote:        SOLINK_MODULE(target) Release/obj.target/bson.node
remote:        COPY Release/bson.node
remote:        make: Leaving directory `/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/bson/build'
remote:
remote:        > phantomjs@1.9.18 install /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/phantomjs
remote:        > node install.js
remote:
remote:        Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2

remote:        Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
remote:        Receiving...
remote:
remote:        Received 12854K total.
remote:        Extracting tar contents (via spawned process)
remote:        Removing /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/phantomjs/lib/phantom
remote:        Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1446384194790/phantomjs-1.9.8-linux-x86_64 -> /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/phantomjs/lib/phantom
remote:        Writing location.js file
remote:        Done. Phantomjs binary available at /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/phantomjs/lib/phantom/bin/phantomjs
remote:
remote:        > node-sass@1.2.3 install /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/node-sass-middleware/node_modules/node-sass
remote:        > node scripts/install.js
remote:
remote:        Binary downloaded and installed at /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/node-sass-middleware/node_modules/node-sass/vendor/linux-x64/binding.node
remote:
remote:        > node-sass@3.4.1 install /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/node-sass
remote:        > node scripts/install.js
remote:
remote:        Binary downloaded and installed at /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/node-sass/vendor/linux-x64-14/binding.node
remote:
remote:        > spawn-sync@1.0.14 postinstall /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/spawn-sync
remote:        > node postinstall
remote:
remote:
remote:        > node-sass@1.2.3 postinstall /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/node-sass-middleware/node_modules/node-sass
remote:        > node scripts/build.js
remote:
remote:        `linux-x64` exists; testing
remote:        module.js:355
remote:        Module._extensions[extension](this, filename);
remote:        ^
remote:        Error: Module did not self-register.
remote:        at Error (native)
remote:        at Module.load (module.js:355:32)
remote:        at Function.Module._load (module.js:310:12)
remote:        at Module.require (module.js:365:17)
remote:        at require (module.js:384:17)
remote:        at Object.<anonymous> (/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:181:15)
remote:        at Module._compile (module.js:460:26)
remote:        at Object.Module._extensions..js (module.js:478:10)
remote:        at Module.load (module.js:355:32)
remote:        at Function.Module._load (module.js:310:12)
remote:        recapper@0.0.0-6 /tmp/build_9cd22ea3a41a036994c9d95998b5d84d
remote:        ├── async@0.9.2
remote:        ├─┬ cloudinary@1.2.5
remote:        │ ├── chunking-streams@0.0.8
remote:        │ ├── lodash@3.10.1
remote:        │ └── q@1.4.1
remote:        ├── d3@3.5.6
remote:        ├── dotenv@0.4.0
remote:        ├─┬ express-handlebars@1.2.2
remote:        │ ├─┬ glob@5.0.15
remote:        │ │ ├── inflight@1.0.4
remote:        │ │ ├── inherits@2.0.1
remote:        │ │ ├─┬ minimatch@3.0.0
remote:        │ │ │ └─┬ brace-expansion@1.1.1
remote:        │ │ │   ├── balanced-match@0.2.1
remote:        │ │ │   └── concat-map@0.0.1
remote:        │ │ └── path-is-absolute@1.0.0
remote:        │ ├── graceful-fs@3.0.8
remote:        │ ├─┬ promise@6.1.0
remote:        │ │ └── asap@1.0.0
remote:        │ └── semver@3.0.1
remote:        ├─┬ gulp-sourcemaps@1.6.0
remote:        │ ├── convert-source-map@1.1.1
remote:        │ ├── graceful-fs@4.1.2
remote:        │ ├─┬ strip-bom@2.0.0
remote:        │ │ └── is-utf8@0.2.0
remote:        │ ├─┬ through2@2.0.0
remote:        │ │ ├─┬ readable-stream@2.0.4
remote:        │ │ │ ├── core-util-is@1.0.1
remote:        │ │ │ ├── isarray@0.0.1
remote:        │ │ │ ├── process-nextick-args@1.0.3
remote:        │ │ │ ├── string_decoder@0.10.31
remote:        │ │ │ └── util-deprecate@1.0.2
remote:        │ │ └── xtend@4.0.0
remote:        │ └─┬ vinyl@1.1.0
remote:        │   ├── clone@1.0.2
remote:        │   ├── clone-stats@0.0.1
remote:        │   └── replace-ext@0.0.1
remote:        ├─┬ handlebars@2.0.0
remote:        │ ├─┬ optimist@0.3.7
remote:        │ │ └── wordwrap@0.0.3
remote:        │ └─┬ uglify-js@2.3.6
remote:        │   ├── async@0.2.10
remote:        │   └─┬ source-map@0.1.43
remote:        │     └── amdefine@1.0.0
remote:        ├─┬ html-pdf@1.4.0
remote:        │ └─┬ phantomjs@1.9.18
remote:        │   ├── adm-zip@0.4.4
remote:        │   ├─┬ fs-extra@0.23.1
remote:        │   │ └── graceful-fs@4.1.2
remote:        │   ├── kew@0.4.0
remote:        │   ├── npmconf@2.1.1
remote:        │   ├── progress@1.1.8
remote:        │   ├─┬ request@2.42.0
remote:        │   │ ├── aws-sign2@0.5.0
remote:        │   │ ├─┬ bl@0.9.4
remote:        │   │ │ └── readable-stream@1.0.33
remote:        │   │ ├── caseless@0.6.0
remote:        │   │ ├── forever-agent@0.5.2
remote:        │   │ ├─┬ form-data@0.1.4
remote:        │   │ │ ├─┬ combined-stream@0.0.7
remote:        │   │ │ │ └── delayed-stream@0.0.5
remote:        │   │ │ └── mime@1.2.11
remote:        │   │ ├─┬ hawk@1.1.1
remote:        │   │ │ ├── boom@0.4.2
remote:        │   │ │ ├── cryptiles@0.2.2
remote:        │   │ │ ├── hoek@0.9.1
remote:        │   │ │ └── sntp@0.2.4
remote:        │   │ ├── http-signature@0.10.1
remote:        │   │ ├── mime-types@1.0.2
remote:        │   │ ├── oauth-sign@0.4.0
remote:        │   │ └── qs@1.2.2
remote:        │   ├─┬ request-progress@0.3.1
remote:        │   │ └── throttleit@0.0.2
remote:        │   └── which@1.0.9
remote:        ├── i@0.3.3
remote:        ├─┬ keystone@0.2.42
remote:        │ ├─┬ azure@0.10.6
remote:        │ │ ├─┬ azure-arm-authorization@0.10.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── azure-arm-compute@0.10.0
remote:        │ │ ├── azure-arm-dns@0.10.0
remote:        │ │ ├─┬ azure-arm-insights@0.10.0
remote:        │ │ │ └── moment@2.6.0
remote:        │ │ ├── azure-arm-keyvault@0.10.0
remote:        │ │ ├── azure-arm-network@0.10.0
remote:        │ │ ├─┬ azure-arm-resource@0.10.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── azure-arm-storage@0.10.0
remote:        │ │ ├─┬ azure-arm-website@0.10.0
remote:        │ │ │ ├── moment@2.6.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── azure-asm-compute@0.10.0
remote:        │ │ ├─┬ azure-asm-hdinsight@0.10.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├─┬ azure-asm-mgmt@0.10.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── azure-asm-network@0.10.0
remote:        │ │ ├─┬ azure-asm-sb@0.10.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── azure-asm-scheduler@0.10.0
remote:        │ │ ├─┬ azure-asm-sql@0.10.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── azure-asm-storage@0.10.0
remote:        │ │ ├── azure-asm-store@0.10.0
remote:        │ │ ├── azure-asm-subscription@0.10.0
remote:        │ │ ├── azure-asm-trafficmanager@0.10.0
remote:        │ │ ├─┬ azure-asm-website@0.10.0
remote:        │ │ │ ├── moment@2.6.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├─┬ azure-common@0.9.12
remote:        │ │ │ ├── dateformat@1.0.2-1.2.3
remote:        │ │ │ ├── duplexer@0.1.1
remote:        │ │ │ ├── envconf@0.0.4
remote:        │ │ │ ├── request@2.45.0
remote:        │ │ │ ├── through@2.3.8
remote:        │ │ │ ├── tunnel@0.0.3
remote:        │ │ │ ├── underscore@1.4.4
remote:        │ │ │ ├── validator@3.1.0
remote:        │ │ │ ├─┬ xml2js@0.2.7
remote:        │ │ │ │ └── sax@0.5.2
remote:        │ │ │ └── xmlbuilder@0.4.3
remote:        │ │ ├─┬ azure-gallery@2.0.0-pre.16
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├─┬ azure-keyvault@0.9.2
remote:        │ │ │ └─┬ azure-common@0.9.10
remote:        │ │ │   ├─┬ request@2.27.0
remote:        │ │ │   │ ├── hawk@1.0.0
remote:        │ │ │   │ ├── mime@1.2.11
remote:        │ │ │   │ ├── oauth-sign@0.3.0
remote:        │ │ │   │ ├── qs@0.6.6
remote:        │ │ │   │ └── tunnel-agent@0.3.0
remote:        │ │ │   └── underscore@1.4.4
remote:        │ │ ├─┬ azure-monitoring@0.10.0
remote:        │ │ │ ├── moment@2.6.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├─┬ azure-sb@0.10.0
remote:        │ │ │ ├── mpns@2.0.1
remote:        │ │ │ ├── underscore@1.4.4
remote:        │ │ │ └── wns@0.5.3
remote:        │ │ ├─┬ azure-scheduler@0.10.0
remote:        │ │ │ └── moment@2.6.0
remote:        │ │ ├─┬ azure-storage@0.3.3
remote:        │ │ │ ├── extend@1.2.1
remote:        │ │ │ ├── mime@1.2.11
remote:        │ │ │ ├─┬ request@2.27.0
remote:        │ │ │ │ ├── aws-sign@0.3.0
remote:        │ │ │ │ ├── cookie-jar@0.3.0
remote:        │ │ │ │ ├── hawk@1.0.0
remote:        │ │ │ │ ├── oauth-sign@0.3.0
remote:        │ │ │ │ ├── qs@0.6.6
remote:        │ │ │ │ └── tunnel-agent@0.3.0
remote:        │ │ │ └── underscore@1.4.4
remote:        │ │ ├── mime@1.2.11
remote:        │ │ ├── node-uuid@1.2.0
remote:        │ │ ├─┬ request@2.45.0
remote:        │ │ │ └── node-uuid@1.4.3
remote:        │ │ └── underscore@1.4.4
remote:        │ ├── bcrypt-nodejs@0.0.3
remote:        │ ├── bluebird@2.3.11
remote:        │ ├─┬ cloudinary@1.0.13
remote:        │ │ ├─┬ coffee-script@1.7.1
remote:        │ │ │ └── mkdirp@0.3.5
remote:        │ │ └── underscore@1.4.4
remote:        │ ├── connect-flash@0.1.1
remote:        │ ├── csv@0.3.7
remote:        │ ├─┬ embedly@1.0.4
remote:        │ │ ├── batbelt@0.0.2
remote:        │ │ ├─┬ hashish@0.0.4
remote:        │ │ │ └── traverse@0.6.6
remote:        │ │ ├── sprintf@0.1.1
remote:        │ │ └─┬ superagent@0.21.0
remote:        │ │   ├── component-emitter@1.1.2
remote:        │ │   ├── cookiejar@2.0.1
remote:        │ │   ├── form-data@0.1.3
remote:        │ │   ├── formidable@1.0.14
remote:        │ │   ├── methods@1.0.1
remote:        │ │   ├── mime@1.2.11
remote:        │ │   ├── qs@1.2.0
remote:        │ │   ├── readable-stream@1.0.27-1
remote:        │ │   └── reduce-component@1.0.1
remote:        │ ├─┬ express@3.3.8
remote:        │ │ ├── buffer-crc32@0.2.1
remote:        │ │ ├─┬ commander@1.2.0
remote:        │ │ │ └── keypress@0.1.0
remote:        │ │ ├─┬ connect@2.8.8
remote:        │ │ │ ├── bytes@0.2.0
remote:        │ │ │ ├── methods@0.0.1
remote:        │ │ │ ├── pause@0.0.1
remote:        │ │ │ ├── qs@0.6.5
remote:        │ │ │ └── uid2@0.0.2
remote:        │ │ ├── cookie@0.1.0
remote:        │ │ ├── cookie-signature@1.0.1
remote:        │ │ ├─┬ debug@2.2.0
remote:        │ │ │ └── ms@0.7.1
remote:        │ │ ├── fresh@0.2.0
remote:        │ │ ├── methods@0.0.1
remote:        │ │ ├── mkdirp@0.3.5
remote:        │ │ ├── range-parser@0.0.4
remote:        │ │ └─┬ send@0.1.4
remote:        │ │   └── mime@1.2.11
remote:        │ ├─┬ fs-extra@0.12.0
remote:        │ │ ├── jsonfile@2.2.3
remote:        │ │ ├── ncp@0.6.0
remote:        │ │ └── rimraf@2.4.3
remote:        │ ├─┬ jade@1.8.2
remote:        │ │ ├── character-parser@1.2.1
remote:        │ │ ├── commander@2.5.1
remote:        │ │ ├─┬ constantinople@3.0.2
remote:        │ │ │ └── acorn@2.5.2
remote:        │ │ ├─┬ transformers@2.1.0
remote:        │ │ │ ├─┬ css@1.0.8
remote:        │ │ │ │ ├── css-parse@1.0.4
remote:        │ │ │ │ └── css-stringify@1.0.5
remote:        │ │ │ ├─┬ promise@2.0.0
remote:        │ │ │ │ └── is-promise@1.0.1
remote:        │ │ │ └── uglify-js@2.2.5
remote:        │ │ ├── void-elements@1.0.0
remote:        │ │ └─┬ with@4.0.3
remote:        │ │   ├── acorn@1.2.2
remote:        │ │   └── acorn-globals@1.0.8
remote:        │ ├─┬ keystone-utils@0.1.13
remote:        │ │ └── html-stringify@0.0.3
remote:        │ ├─┬ less-middleware@1.0.4
remote:        │ │ ├─┬ less@1.7.5
remote:        │ │ │ ├─┬ clean-css@2.2.23
remote:        │ │ │ │ └── commander@2.2.0
remote:        │ │ │ ├── mime@1.2.11
remote:        │ │ │ └─┬ request@2.40.0
remote:        │ │ │   ├── oauth-sign@0.3.0
remote:        │ │ │   └── qs@1.0.2
remote:        │ │ ├── mkdirp@0.3.5
remote:        │ │ └─┬ node.extend@1.0.10
remote:        │ │   └── is@0.3.0
remote:        │ ├── mandrill-api@1.0.45
remote:        │ ├── marked@0.3.5
remote:        │ ├─┬ mongoose@3.8.36
remote:        │ │ ├── hooks@0.2.1
remote:        │ │ ├─┬ mongodb@1.4.38
remote:        │ │ │ ├─┬ bson@0.2.22
remote:        │ │ │ │ └── nan@1.8.4
remote:        │ │ │ ├── kerberos@0.0.11
remote:        │ │ │ └── readable-stream@2.0.4
remote:        │ │ ├── mpath@0.1.1
remote:        │ │ ├── mpromise@0.4.3
remote:        │ │ ├─┬ mquery@1.6.1
remote:        │ │ │ └── bluebird@2.9.26
remote:        │ │ ├── ms@0.1.0
remote:        │ │ ├── muri@1.1.0
remote:        │ │ ├── regexp-clone@0.0.1
remote:        │ │ └── sliced@0.0.5
remote:        │ ├── mpromise@0.5.5
remote:        │ ├── numeral@1.5.3
remote:        │ ├── queryfilter@0.0.4
remote:        │ ├─┬ range_check@0.0.5
remote:        │ │ └── ipaddr.js@0.1.1
remote:        │ ├── scmp@1.0.0
remote:        │ └── semver@4.1.1
remote:        ├─┬ knox@0.9.2
remote:        │ ├─┬ debug@1.0.4
remote:        │ │ └── ms@0.6.2
remote:        │ ├─┬ once@1.3.2
remote:        │ │ └── wrappy@1.0.1
remote:        │ ├── stream-counter@1.0.0
remote:        │ └─┬ xml2js@0.4.15
remote:        │   ├── sax@1.1.4
remote:        │   └── xmlbuilder@3.1.0
remote:        ├── mime@1.3.4
remote:        ├── moment@2.8.4
remote:        ├─┬ node-sass@3.4.1
remote:        │ ├── async-foreach@0.1.3
remote:        │ ├─┬ chalk@1.1.1
remote:        │ │ ├── ansi-styles@2.1.0
remote:        │ │ ├─┬ has-ansi@2.0.0
remote:        │ │ │ └── ansi-regex@2.0.0
remote:        │ │ ├── strip-ansi@3.0.0
remote:        │ │ └── supports-color@2.0.0
remote:        │ ├─┬ cross-spawn@2.0.0
remote:        │ │ ├─┬ cross-spawn-async@2.0.0
remote:        │ │ │ ├── lru-cache@2.7.0
remote:        │ │ │ └─┬ which@1.2.0
remote:        │ │ │   └─┬ is-absolute@0.1.7
remote:        │ │ │     └── is-relative@0.1.3
remote:        │ │ └─┬ spawn-sync@1.0.14
remote:        │ │   ├─┬ concat-stream@1.5.1
remote:        │ │   │ └── typedarray@0.0.6
remote:        │ │   └── os-shim@0.1.3
remote:        │ ├── get-stdin@4.0.1
remote:        │ ├─┬ meow@3.5.0
remote:        │ │ ├── loud-rejection@1.0.0
remote:        │ │ ├── minimist@1.2.0
remote:        │ │ ├─┬ normalize-package-data@2.3.4
remote:        │ │ │ ├── hosted-git-info@2.1.4
remote:        │ │ │ ├─┬ is-builtin-module@1.0.0
remote:        │ │ │ │ └── builtin-modules@1.1.0
remote:        │ │ │ └─┬ validate-npm-package-license@3.0.1
remote:        │ │ │   ├─┬ spdx-correct@1.0.2
remote:        │ │ │   │ └── spdx-license-ids@1.1.0
remote:        │ │ │   └─┬ spdx-expression-parse@1.0.0
remote:        │ │ │     └── spdx-exceptions@1.0.3
remote:        │ │ ├── object-assign@4.0.1
remote:        │ │ ├─┬ read-pkg-up@1.0.1
remote:        │ │ │ ├─┬ find-up@1.0.0
remote:        │ │ │ │ └── path-exists@2.0.0
remote:        │ │ │ └─┬ read-pkg@1.1.0
remote:        │ │ │   ├─┬ load-json-file@1.0.1
remote:        │ │ │   │ ├── graceful-fs@4.1.2
remote:        │ │ │   │ ├─┬ parse-json@2.2.0
remote:        │ │ │   │ │ └── error-ex@1.2.0
remote:        │ │ │   │ └── pify@2.3.0
remote:        │ │ │   └─┬ path-type@1.0.0
remote:        │ │ │     └── graceful-fs@4.1.2
remote:        │ │ ├─┬ redent@1.0.0
remote:        │ │ │ ├─┬ indent-string@2.1.0
remote:        │ │ │ │ └── repeating@2.0.0
remote:        │ │ │ └── strip-indent@1.0.1
remote:        │ │ └── trim-newlines@1.0.0
remote:        │ ├── mkdirp@0.5.1
remote:        │ ├── nan@2.1.0
remote:        │ ├─┬ node-gyp@3.0.3
remote:        │ │ ├─┬ fstream@1.0.8
remote:        │ │ │ └── graceful-fs@4.1.2
remote:        │ │ ├─┬ glob@4.5.3
remote:        │ │ │ └── minimatch@2.0.10
remote:        │ │ ├── graceful-fs@4.1.2
remote:        │ │ ├── minimatch@1.0.0
remote:        │ │ ├─┬ nopt@3.0.4
remote:        │ │ │ └── abbrev@1.0.7
remote:        │ │ ├─┬ npmlog@1.2.1
remote:        │ │ │ ├── ansi@0.3.0
remote:        │ │ │ ├─┬ are-we-there-yet@1.0.4
remote:        │ │ │ │ ├── delegates@0.1.0
remote:        │ │ │ │ └── readable-stream@1.1.13
remote:        │ │ │ └─┬ gauge@1.2.2
remote:        │ │ │   ├── has-unicode@1.0.1
remote:        │ │ │   ├─┬ lodash.pad@3.1.1
remote:        │ │ │   │ ├── lodash._basetostring@3.0.1
remote:        │ │ │   │ └─┬ lodash._createpadding@3.6.1
remote:        │ │ │   │   └── lodash.repeat@3.0.1
remote:        │ │ │   ├── lodash.padleft@3.1.1
remote:        │ │ │   └── lodash.padright@3.1.1
remote:        │ │ ├─┬ osenv@0.1.3
remote:        │ │ │ ├── os-homedir@1.0.1
remote:        │ │ │ └── os-tmpdir@1.0.1
remote:        │ │ ├─┬ path-array@1.0.0
remote:        │ │ │ └── array-index@0.1.1
remote:        │ │ └─┬ tar@1.0.3
remote:        │ │   └── block-stream@0.0.8
remote:        │ ├─┬ npmconf@2.1.2
remote:        │ │ ├─┬ config-chain@1.1.9
remote:        │ │ │ └── proto-list@1.2.4
remote:        │ │ ├── ini@1.3.4
remote:        │ │ └── uid-number@0.0.5
remote:        │ └─┬ sass-graph@2.0.1
remote:        │   └─┬ yargs@3.29.0
remote:        │     ├── camelcase@1.2.1
remote:        │     ├─┬ cliui@3.0.3
remote:        │     │ ├─┬ string-width@1.0.1
remote:        │     │ │ ├─┬ code-point-at@1.0.0
remote:        │     │ │ │ └── number-is-nan@1.0.0
remote:        │     │ │ └── is-fullwidth-code-point@1.0.0
remote:        │     │ └── wrap-ansi@1.0.0
remote:        │     ├── decamelize@1.1.1
remote:        │     ├─┬ os-locale@1.4.0
remote:        │     │ └─┬ lcid@1.0.0
remote:        │     │   └── invert-kv@1.0.0
remote:        │     ├── window-size@0.1.2
remote:        │     └── y18n@3.2.0
remote:        ├─┬ request@2.65.0
remote:        │ ├── aws-sign2@0.6.0
remote:        │ ├── bl@1.0.0
remote:        │ ├── caseless@0.11.0
remote:        │ ├─┬ combined-stream@1.0.5
remote:        │ │ └── delayed-stream@1.0.0
remote:        │ ├── extend@3.0.0
remote:        │ ├── forever-agent@0.6.1
remote:        │ ├─┬ form-data@1.0.0-rc3
remote:        │ │ └── async@1.5.0
remote:        │ ├─┬ har-validator@2.0.2
remote:        │ │ ├─┬ commander@2.9.0
remote:        │ │ │ └── graceful-readlink@1.0.1
remote:        │ │ ├─┬ is-my-json-valid@2.12.2
remote:        │ │ │ ├── generate-function@2.0.0
remote:        │ │ │ ├─┬ generate-object-property@1.2.0
remote:        │ │ │ │ └── is-property@1.0.2
remote:        │ │ │ └── jsonpointer@2.0.0
remote:        │ │ └─┬ pinkie-promise@1.0.0
remote:        │ │   └── pinkie@1.0.0
remote:        │ ├─┬ hawk@3.1.0
remote:        │ │ ├── boom@2.10.1
remote:        │ │ ├── cryptiles@2.0.5
remote:        │ │ ├── hoek@2.16.3
remote:        │ │ └── sntp@1.0.9
remote:        │ ├─┬ http-signature@0.11.0
remote:        │ │ ├── asn1@0.1.11
remote:        │ │ ├── assert-plus@0.1.5
remote:        │ │ └── ctype@0.5.3
remote:        │ ├── isstream@0.1.2
remote:        │ ├── json-stringify-safe@5.0.1
remote:        │ ├─┬ mime-types@2.1.7
remote:        │ │ └── mime-db@1.19.0
remote:        │ ├── node-uuid@1.4.3
remote:        │ ├── oauth-sign@0.8.0
remote:        │ ├── qs@5.2.0
remote:        │ ├── stringstream@0.0.5
remote:        │ ├── tough-cookie@2.2.0
remote:        │ └── tunnel-agent@0.4.1
remote:        ├─┬ twitter@1.2.5
remote:        │ └── deep-extend@0.3.3
remote:        └── underscore@1.7.0
remote:
remote:        npm ERR! Linux 3.13.0-57-generic
remote:        npm ERR! argv "node" "/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_9cd22ea3a41a036994c9d95998b5d84d/.npmrc"
remote:        npm ERR! node v0.12.2
remote:        npm ERR! npm  v3.3.10
remote:        npm ERR! code ELIFECYCLE
remote:
remote:        npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the node-sass package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node scripts/build.js
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls node-sass
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_9cd22ea3a41a036994c9d95998b5d84d/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy....
remote:
remote: !       Push rejected to rekaper-staging.
remote:
To XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by xzyfer** [comment]
You're trying to install two versions of node-sass, 3.4.1 and 1.2.3. It appears that node-sass@1.2.3 doesn't work on the versions of node you're using. This version ancient and we cannot offer support for it.

Please update to a newer version of node-sass-middleware to get a newer version of node-sass.

**Comment by sureshamk** [comment]
try with `yarn` Its resolved this kind of issue for me
