### ISSUE TITLE
includePath not reading includes

### ISSUE THREAD

**Issue by Saturn2888** [sass/node-sass#1234]
In the docs, it's called `includePaths`, but in the source, it says `includePath`. Either way, I tried both and still have the same issue. No include paths actually work. I've tried absolute includes, relative, relative with a `./` in front; no fix.

```shell
Error in plugin 'sass'
Message:
    resources\assets\scss\app.scss
Error: file to import not found or unreadable: foundation/functions
       Current dir:
        on line 16 of stdin
>> @import 'foundation/functions';
   --------^
```

I'm on Windows 10 with my project on the `D:` drive. I've used both Git Bash and standard CMD, and it does not find includePath values with either of these.

```shell
$ node -v
v4.2.1
```

```shell
$ npm -v
2.14.7
```

```shell
$ gulp -v
[22:02:52] CLI version 0.3.0
[22:02:52] Local version 3.9.0
```

Here's the function I wrote to do the includePath

```js
ops.css.build = function(taskName, src, dest) {
	return gulp.src(src)
		.pipe($.plumber({errorHandler: ops.showError}))
		.pipe($.filter(['**/*.+(sass|scss)']))
		.pipe($.newer({
			dest: dest,
			ext: '.css'
		}))
		.pipe($.debug({title: taskName}))

		// Sass -> CSS
		.pipe($.sourcemaps.init())
		.pipe($.sass({
			// directory: __base,
			errLogToConsole: true,
			includePath: [
				'bower_components/datetimepicker/',
				'bower_components/font-awesome/scss/',
				'bower_components/foundation/scss/',
				'bower_components/slick.js/slick/'
			],
			outputStyle: 'expanded'
		}).on('error', $.sass.logError))

		// Prefix
		.pipe($.autoprefixer({
			browsers: [
				'last 2 versions',
				'> 5%',
				'ie 10-11',
				'not ie <= 9' // Might be redundant
			]
		}))
```

**Comment by xzyfer** [comment]
Sorry I'm not following. What is `$.sass`, assume gulp-sass?

I can confirm `includePath` works as expected. This is a configuration issue in your application. Please create small github repository that shows the issue your experiencing.

**Comment by Saturn2888** [comment]
It's working now yes.

And $.sass = require('gulp-sass')
