### ISSUE TITLE
npm install node-sass FAILED node-sass@3.4.1 postinstall

### ISSUE THREAD

**Issue by ado-san** [sass/node-sass#1238]
Below the npm.err extract file (ask me for npm-debug.log and npm.log if needed):

npm verb pkgid node-sass@3.4.1
npm verb cwd /Users/buyer/ionictodo
npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-ddd" "node-sass"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.1 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/node-sass
npm info preuninstall node-sass@3.4.1
npm info uninstall node-sass@3.4.1
npm verb unbuild rmStuff node-sass@3.4.1 from /Users/buyer/ionictodo/node_modules
npm sill gentlyRm /Users/buyer/ionictodo/node_modules/.bin/node-sass is being gently removed 
npm sill gentlyRm verifying /Users/buyer/ionictodo is an npm working directory
npm sill gentlyRm containing path /Users/buyer/ionictodo is under npm's control, in /Users/buyer/ionictodo
npm sill gentlyRm deletion target /Users/buyer/ionictodo/node_modules/.bin/node-sass is under /Users/buyer/ionictodo
npm verb gentlyRm vacuuming from /Users/buyer/ionictodo/node_modules/.bin/node-sass up to /Users/buyer/ionictodo
npm sill vacuum-fs removing /Users/buyer/ionictodo/node_modules/.bin/node-sass
npm sill vacuum-fs removing /Users/buyer/ionictodo/node_modules/.bin
npm sill vacuum-fs quitting because other entries in /Users/buyer/ionictodo/node_modules
npm info postuninstall node-sass@3.4.1
npm sill gentlyRm /Users/buyer/ionictodo/node_modules/node-sass is being purged from base /Users/buyer/ionictodo
npm verb gentlyRm don't care about contents; nuking /Users/buyer/ionictodo/node_modules/node-sass
npm sill vacuum-fs purging /Users/buyer/ionictodo/node_modules/node-sass
npm sill vacuum-fs removing /Users/buyer/ionictodo/node_modules
npm sill vacuum-fs finished vacuuming up to /Users/buyer/ionictodo

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/buyer/ionictodo/npm-debug.log

**Comment by TylerJBrown192** [comment]
I'm having the same error message. I'm working on a Windows 7 Enterprise machine. Here is the output of my console:

npm verb stack Error: node-sass@3.4.1 postinstall: `node scripts/build.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:233:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid node-sass@3.4.1
npm verb cwd C:\Projects\Main-Dev\Src\OnlineBanking.API\uux\node-build
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "-verbose"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.1 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Main-Dev\Src\OnlineBanking.API\uux\node-build\npm-debug
.log

debug.log available on request

**Comment by xzyfer** [comment]
This has been answered multiple times. We currently do not support Windows with Node 5 because the service we use to build own binaries hasn't updated. Generally speaking if you're using something that's a week old it's probably the problem. Downgrade to Node 4.

**Comment by xzyfer** [comment]
Apologies @ado-san your issue is different. Please consult the [contributing docs](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md) before opening issues. Without following those steps we cannot assist you.

<img width="776" alt="screen shot 2015-11-03 at 12 44 19 pm" src="https://cloud.githubusercontent.com/assets/579928/10899439/a5ebb874-8228-11e5-97e5-75e75f62100b.png">

**Comment by ado-san** [comment]
@xzyfer thanks. I followed the best practices and opened #1240
