### ISSUE TITLE
When using importer with includePaths, prev is not resolved to a full path

### ISSUE THREAD

**Issue by quarterto** [sass/node-sass#1243]
(not sure if this should go here or in libsass)

When using a custom importer, together with files imported via `includePaths`, if an imported file in the include path imports another file, when the import is passed to the importer `prev` is not resolved to a full path. 

Hope that makes sense; if not, here's a concrete example:

https://github.com/quarterto/importer-test
https://github.com/quarterto/importer-test-no-include-path

Both repositories [run node-sass](https://github.com/quarterto/importer-test/blob/master/build.sh) with a [custom importer](https://github.com/quarterto/importer-test/blob/master/importer.js) that just outputs `prev` to stderr and calls `done` with no arguments. The first has this directory structure:

```
├── a.scss
└── folder
    ├── b.scss
    └── c.scss
```

with `a` including `b` including `c` and `--include-path=folder`. The second has

```
├── a.scss
├── b.scss
└── c.scss
```

with no `--include-path`. The importer outputs

```
/Users/matthew.brennan/Documents/importer-test/a.scss
b
```

for the first and

```
/Users/matthew.brennan/Documents/importer-test/a.scss
/Users/matthew.brennan/Documents/importer-test/b
```

for the second.

**Comment by mbarlock** [comment]
I believe this is a dupe of #1219

**Comment by saper** [comment]
Will check, thanks.

**Comment by quarterto** [comment]
Ah, it's an exact dupe of that, thanks. I clearly didn't search hard enough.
