### ISSUE TITLE
Add a banner option

### ISSUE THREAD

**Issue by danwellman** [sass/node-sass#1246]
Please add an option to allow a banner to be injected to the top of the compiled CSS file, e.g. a copyright/ownership statement

**Comment by elektronik2k5** [comment]
I think that wold be out of scope for this project. You can include it in your SASS, or if you're using webpack, there's a loader for that.

**Comment by xzyfer** [comment]
We will not add this. Do this in a post process like gulp, grunt, simple
string concatenation.

**Comment by danwellman** [comment]
Understood, thanks :)
