### ISSUE TITLE
404 on a patch

### ISSUE THREAD

**Issue by valtido** [sass/node-sass#1253]
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/win32-x64-47_binding.node": HTTP error 404 Not Found
```
I get the above when I try to download the harp server https://github.com/sintaxi/harp .

I am pulling my hair and going bold... any help on re-instating this?

**Comment by xzyfer** [comment]
The version you're using was released before node 5 so it's not compatible.
Downgrade node, or upgrade node-sass.

Odds are if you're using a version of nkde that's a couple weeks old and
you're suddenly having strange issues that's the reason.
