### ISSUE TITLE
Bump Libsass to 3.3.2

### ISSUE THREAD

**Issue by blimmer** [sass/node-sass#1256]
I'm still seeing issues with lib-sass 3.3.1 on node-sass 3.4.1.

Can we please bump the included version of lib-sass to 3.3.2?

**Comment by xzyfer** [comment]
We're working on it as you can see from this issue.

**Comment by JohnAlbin** [comment]
This issue: https://github.com/sass/node-sass/pull/1248

**Comment by blimmer** [comment]
Great, thanks! I'll close this issue since its being actively worked
