### ISSUE TITLE
Cannot download win32-x64-46_binding.node

### ISSUE THREAD

**Issue by Leonkao** [sass/node-sass#1263]
# My environment 
node version : v4.2.2
npm version : v2.14.7
node-sass version :3.4.1

# THE ERROR
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.1/win32-x64-46_binding.node":

socket hang up

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

```
## I troubleshoot the cause, it may be a network failure. I can not access 
```
https://github-cloud.s3.amazonaws.com/releases/4128353/10dc4cb6-88a5-11e5-8375-a865ca7ff7b8.node
```
# Advice:
Move the *.node files from github-cloud.s3.amazonaws.com to github.com

**Comment by saper** [comment]
This is a networking problem, you can try to download those file offline.

**Comment by Leonkao** [comment]
Sorry ,I just can download the Source code (zip), 
Can you tell me how to bulid the win32-x64-46_binding.node file? 
Thanks !

**Comment by xzyfer** [comment]
We will not move the binaries. As the error message suggests you should use
a proxy.

**Comment by Leonkao** [comment]
I got it.
Thank you very much!

**Comment by saper** [comment]
On Thu, 12 Nov 2015, Leon kao wrote:

> Sorry ,I just can download the Source code (zip), 
> Can you tell me how to bulid the win32-x64-46_binding.node file? 

You can try building from source using MinGW or Microsoft Visual Studio 2013 or 2015
and a Windows SDK.

You can also get a ready file by cloning https://github.com/sass/node-sass-binaries
repository.

**Comment by Leonkao** [comment]
@saper 
I'm sorry to reply to your message too late.
Thank you very much!
