### ISSUE TITLE
Import fails with similarly named partial in 3.4.2

### ISSUE THREAD

**Issue by mmwtsn** [sass/node-sass#1267]
A project I'm working on imports a pattern library in which the base file imports a partial with the same file name (e.g. `base.scss` imports `_base.scss`). This setup was working through `v3.4.1` but fails on `v3.4.2` with the following error:

```
Error: It's not clear which file to import for '@import "base"'.
```

Looking through the [`v3.4.2` release notes](https://github.com/sass/node-sass/releases/tag/v3.4.2) it looks like `@import` was refactored in [libsass#1626](https://github.com/sass/libsass/pull/1626).

Is this a regression? It broke our CI server builds this morning when the new patch was installed.

**Comment by mmwtsn** [comment]
To clarify, this *should* fail according to the [SASS specification](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials):

> "Note that you may not include a partial and a non-partial with the same name in the same directory. For example, _colors.scss may not exist alongside colors.scss."

My concern here is with this potentially being a breaking change that was introduced in a patch update between `v3.4.1` and `v3.4.2`.

**Comment by xzyfer** [comment]
This is tricky. Node Sass technically follows semver but LibSass does not. There isn't really much we can do here. The expectation is that we do what Ruby Sass does. If you're relying on an undocumented bug semver offers no guarantees that behaviour won't break.
