### ISSUE TITLE
Chaining custom importers

### ISSUE THREAD

**Issue by strarsis** [sass/node-sass#1271]
In npm there are basically now the [node-sass-custom-importer](https://github.com/danderu/node-sass-custom-importer) and [node-sass-import-once](https://github.com/at-import/node-sass-import-once).
For example node-sass-import-once comes with extra functionality, 
some functionality of both importers intersect or are slightly different.

Wouldn't it make sense to allow chaining custom importers, 
where each got its own dedicated purpose?
Like first node-sass-import-once for importing once (and doing that well) 
and then node-sass-custom-importer for the custom paths.

With best regards

**Comment by xzyfer** [comment]
This has come up before. Unfortunately chaining of importers doesn't make
sense. The fundamental rule of importers is that an import can only match a
single importer. Chaining breaks this model.

The right way to do what you suggest would be for importer authors to write
modules in such a way that the core logic can be required and used by other
importers.
