### ISSUE TITLE
fail to install node-sass on windows 8.1

### ISSUE THREAD

**Issue by superpig** [sass/node-sass#1275]
G:\temp1>npm -v
2.11.2

G:\temp1>node -v
v0.12.6

G:\temp1>node -p process.versions
{ http_parser: '2.3',
  node: '0.12.6',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1o' }

G:\temp1>node -p process.platform
win32

G:\temp1>node -p process.arch
ia32

gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (G:\temp1\node_modules\nod
e-sass\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_pro
cess.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "G:\\te
mp1\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.
js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--li
bsass_ldflags=" "--libsass_library="
gyp ERR! cwd G:\temp1\node_modules\node-sass
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Pro
gram Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll" "node-sass"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scri
pts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     G:\temp1\npm-debug.log

**Comment by saper** [comment]
Can you post your  full `npm-debug.log` to gist.github.com ?

**Comment by superpig** [comment]
this is my npm-debug.log file:  https://gist.github.com/superpig/801c8860c5c9893ccd0d

**Comment by saper** [comment]
`npm install` tries to fetch the binary file from github.com and S3. If you need to use a proxy to access the unlimited Internet, you might need to configure npm proxy settings.
