### ISSUE TITLE
node-sass@3.4.x can`t install on centos

### ISSUE THREAD

**Issue by magicismight** [sass/node-sass#1278]
```
> node-sass@3.4.0 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.1.0
gyp info using node@4.2.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.6.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.2.1
gyp verb command install [ '4.2.1' ]
gyp verb install input version string "4.2.1"
gyp verb install installing version: 4.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 4.2.1
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /usr/local/lib/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/local/lib/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/local/lib/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /usr/local/lib/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-sass/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.node-gyp/4.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/usr/local/lib/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.0"' -I/root/.node-gyp/4.2.1/include/node -I/root/.node-gyp/4.2.1/src -I/root/.node-gyp/4.2.1/deps/uv/include -I/root/.node-gyp/4.2.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:1:
../src/libsass/src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
../src/libsass/src/ast.hpp:245: 错误：‘class std::unordered_map<Sass::Expression*, Sass::Expression*, std::hash<Sass::Expression*>, std::equal_to<Sass::Expression*>, std::allocator<std::pair<Sass::Expression* const, Sass::Expression*> > >’没有名为‘reserve’的成员
../src/libsass/src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
../src/libsass/src/ast.hpp:274: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:278: 错误：不能将‘Sass::Hashed::reset_duplicate_key()’转换为‘bool’
../src/libsass/src/ast.hpp:279: 错误：expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:279: 错误：expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
../src/libsass/src/ast.hpp:861: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:865: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:865: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:865: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:865: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:865: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:865: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
../src/libsass/src/ast.hpp:1098: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1100: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1100: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1100: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1100: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1100: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1100: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
../src/libsass/src/ast.hpp:1365: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1367: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1367: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1367: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1367: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1367: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1367: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*, std::string)’:
../src/libsass/src/ast.cpp:520: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:523: 错误：expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:523: 错误：expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:523: 错误：expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:523: 错误：expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘void Sass::Selector_List::populate_extends(Sass::Selector_List*, Sass::Context&, Sass::ExtensionSubsetMap&)’:
../src/libsass/src/ast.cpp:1284: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:2038: 错误：expected primary-expression at end of input
../src/libsass/src/ast.cpp:2038: 错误：expected ‘;’ at end of input
../src/libsass/src/ast.cpp:2038: 错误：expected primary-expression at end of input
../src/libsass/src/ast.cpp:2038: 错误：expected ‘)’ at end of input
../src/libsass/src/ast.cpp:2038: 错误：expected statement at end of input
../src/libsass/src/ast.cpp:1283: 警告：未使用的变量‘extender’
../src/libsass/src/ast.cpp:2038: 错误：expected ‘}’ at end of input
../src/libsass/src/ast.cpp: At global scope:
../src/libsass/src/ast.cpp:2038: 错误：expected ‘}’ at end of input
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] 错误 1
make: Leaving directory `/usr/local/lib/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.23.4.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/node-sass
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32-504.23.4.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/root/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "--unsafe-perm" "-g" "node-sass@3.4.0"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /www/deyi/beeuilder/npm-debug.log
```

[root@localhost temp]# node -p process.versions
{ http_parser: '2.5.0',
  node: '4.2.1',
  v8: '4.5.103.35',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2d' }
[root@localhost temp]# node -p process.platform
linux
[root@localhost temp]# node -p process.arch
x64

**Comment by saper** [comment]
Do you need proxy to let 'npm install' download the binary?

**Comment by saper** [comment]
also, if you cannot download and have to compile, you need to upgrade your gcc

**Comment by javyliu** [comment]
Some error,why?

gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/data1/home/oswap/test_apps/inner_app/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.2"' -I/home/oswap/.node-gyp/0.12.9/include/node -I/home/oswap/.node-gyp/0.12.9/src -I/home/oswap/.node-gyp/0.12.9/deps/uv/include -I/home/oswap/.node-gyp/0.12.9/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:1:
../src/libsass/src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
../src/libsass/src/ast.hpp:246: 错误：‘class std::unordered_map<Sass::Expression*, Sass::Expression*, std::hash<Sass::Expression*>, std::equal_to<Sass::Expression*>, std::allocator<std::pair<Sass::Expression* const, Sass::Expression*> > >’没有名为‘reserve’的成员
../src/libsass/src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
../src/libsass/src/ast.hpp:275: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:279: 错误：不能将‘Sass::Hashed::reset_duplicate_key()’转换为‘bool’
../src/libsass/src/ast.hpp:280: 错误：expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:280: 错误：expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
../src/libsass/src/ast.hpp:872: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:876: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:876: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:876: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:876: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:876: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:876: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
../src/libsass/src/ast.hpp:1109: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1111: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1111: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1111: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1111: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1111: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1111: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Number::hash()’:
../src/libsass/src/ast.hpp:1236: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1238: 错误：expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1238: 错误：expected ‘;’ before ‘for’
../src/libsass/src/ast.hpp:1238: 错误：expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1238: 错误：expected ‘)’ before ‘for’
../src/libsass/src/ast.hpp:1238: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1240: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1240: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1240: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1240: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1240: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1240: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
../src/libsass/src/ast.hpp:1380: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1382: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1382: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1382: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1382: 错误：expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1382: 错误：expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1382: 错误：expected ‘;’ before ‘}’ token
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*, std::string)’:
../src/libsass/src/ast.cpp:520: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:523: 错误：expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:523: 错误：expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:523: 错误：expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:523: 错误：expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘void Sass::Selector_List::populate_extends(Sass::Selector_List*, Sass::Context&, Sass::ExtensionSubsetMap&)’:
../src/libsass/src/ast.cpp:1294: 错误：expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:2133: 错误：expected primary-expression at end of input
../src/libsass/src/ast.cpp:2133: 错误：expected ‘;’ at end of input
../src/libsass/src/ast.cpp:2133: 错误：expected primary-expression at end of input
../src/libsass/src/ast.cpp:2133: 错误：expected ‘)’ at end of input
../src/libsass/src/ast.cpp:2133: 错误：expected statement at end of input
../src/libsass/src/ast.cpp:1293: 警告：未使用的变量‘extender’
../src/libsass/src/ast.cpp:2133: 错误：expected ‘}’ at end of input
../src/libsass/src/ast.cpp: At global scope:
../src/libsass/src/ast.cpp:2133: 错误：expected ‘}’ at end of input
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] 错误 1
make: Leaving directory `/data1/home/oswap/test_apps/inner_app/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data1/home/oswap/test_apps/inner_app/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "/data1/home/oswap/.nvm/versions/node/v0.12.9/bin/node" "/data1/home/oswap/test_apps/inner_app/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /data1/home/oswap/test_apps/inner_app/node_modules/node-sass
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32-279.el6.x86_64
npm ERR! argv "/home/oswap/.nvm/versions/node/v0.12.9/bin/node" "/home/oswap/.nvm/versions/node/v0.12.9/bin/npm" "install" "node-sass" "--save-dev" "--registry=http://r.cnpmjs.org"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by xzyfer** [comment]
Unfortunately you've both cut off the important output. However it appears that your system was unable to installed the precompiled binary we supply. As a result it has fallen back to trying to compile locally which has failed due your OS having an outdated gcc version.

As @saper suggests this is likely because the download was blocked by a firewall. Please configure npm to use a proxy.
