### ISSUE TITLE
in centos7 failed to install node-sass

### ISSUE THREAD

**Issue by leeir** [sass/node-sass#1279]
cd ..; /root/nvm/versions/node/v5.0.0/lib/node_modules/node-sass/node_modules/node-gyp/gyp/gyp_main.py -fmake --ignore-environment "--toplevel-dir=." -I/root/nvm/versions/node/v5.0.0/lib/node_modules/node-sass/build/config.gypi -I/root/nvm/versions/node/v5.0.0/lib/node_modules/node-sass/node_modules/node-gyp/addon.gypi -I/root/.node-gyp/5.0.0/include/node/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/root/.node-gyp/5.0.0" "-Dnode_gyp_dir=/root/nvm/versions/node/v5.0.0/lib/node_modules/node-sass/node_modules/node-gyp" "-Dnode_lib_file=node.lib" "-Dmodule_root_dir=/root/nvm/versions/node/v5.0.0/lib/node_modules/node-sass" binding.gyp

env:
{ http_parser: '2.5.0',
  node: '5.0.0',
  v8: '4.6.85.28',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2d' }

**Comment by xzyfer** [comment]
This is not a useful bug report. In future follow the instructions in our [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md).
