### ISSUE TITLE
Unable to get a Node SASS 2.1.1 binary

### ISSUE THREAD

**Issue by blong145** [sass/node-sass#1280]
I'm not sure why, but 

https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-ia32-node-4.2/binding.node

returns a not found page instead of the actual content. Is this something you control or is it a github problem?

**Comment by saper** [comment]
You need to use a newer node-sass version. Node-sass 2.1.1 does not support recent node engines.
