### ISSUE TITLE
Malloc crash

### ISSUE THREAD

**Issue by nastiatikk** [sass/node-sass#1281]
The source of my issue is that if there is a scss error in the files (missing semicolon, missing closing bracket, typo in the variable name, commented out variable, etc.) it aborts gulp that is run with `npm start` 
```
gulp(5254,0x1038eb000) malloc: *** error for object 0x1020f4ecc: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

I see there are similar issues https://github.com/dlmanning/gulp-sass/issues/104 and https://github.com/sass/node-sass/issues/554 and https://github.com/dlmanning/gulp-sass/issues/155

I'm using
`"gulp-sass": "^2.1.0",`
`npm 3.3.6`
`node v5.0.0`

```
import gulp from 'gulp';
import sass from 'gulp-sass';
import sourceMaps from 'gulp-sourcemaps';
import postcss from 'gulp-postcss';
import autoprefixer from 'autoprefixer';
import gulpIf from 'gulp-if';
import csso from 'gulp-csso';
import handleErrors from '../lib/handle-errors';
import plumber from 'gulp-plumber';
import * as config from '../config';

export default function sassTask() {
    return gulp.src(config.sass.src)
        .pipe((plumber({ errorHandler: handleErrors })))
        .pipe(sourceMaps.init())
        .pipe(

            // Handle sass errors specifically
            sass(config.sass.sassConfig)
                .on('error', sass.logError)
        )
        .pipe(postcss([
            autoprefixer({
                browsers: ['last 3 versions']
            })
        ]))
        .pipe(gulpIf(!global.isWatching, csso()))
        .pipe(sourceMaps.write('./'))
        .pipe(gulp.dest(config.sass.dest));
}

gulp.task('sass', sassTask);
```

**Comment by nastiatikk** [comment]
@bassettsj

**Comment by saper** [comment]
which node-sass version are you getting?

**Comment by nastiatikk** [comment]
Hi @saper, thanks for checking out this issue!

```
└─┬ gulp-sass@2.1.0
  └── node-sass@3.4.2
```

**Comment by xzyfer** [comment]
Malloc errors are always a LibSass bug. Please provide the Sass code that causes this error so we can fix LibSass.

**Comment by afeldinger** [comment]
I'm encountering the same issue. As stated in original post, it occurs with even fairly basic scss errors, but I'm seeing it with a few other things as well:

* anything other than valid @include directives in the root scss stylesheet, including references to non-existing files. 
* commented @include directives will trigger the error as well
* the @include directive must be the first character in the line. Indenting with space or tab characters trigger the error

For my current project, I'm using
```
node: v5.1.0
npm: 3.3.12
└─┬ gulp-sass@2.1.0
  └── node-sass@3.4.2 
```

But I have another project, where the error doesn't occur, using
```
node: v0.12.2
npm: 2.7.4
└─┬ gulp-sass@2.0.4
  └── node-sass@3.4.1 
```

**Comment by nastiatikk** [comment]
It happens in all files. It happens if I make changes in a file that keeps all variables, it happens in the files where these variables are used.

For example, there is a `unit` variable in a `_variables.scss`:
```
// Basic unit for spacing and alignment; 6 to 12px recommended. Apply in whole
// or half multiples.
$unit: 10px;
```

If I comment it out I have a malloc error.

If there is a file with alert styles `_alert.scss`:
```
.alert {
    padding: $unit;
    background-color: $accent-color; 
    color: white;
}

And there is a typo in `$unit` variable name, or if there is a missing `;` at the end of the line – malloc error comes as a result.

**Comment by nastiatikk** [comment]
@afeldinger This error happens only on my side in our team, so developers added `gulp-ruby-sass` as an alternative. It works good with sass errors and provides the message with an error location. Maybe it will help you to handle this issue while it's being explored and fixed

**Comment by afeldinger** [comment]
@nastiatikk Thanks for the tip. So far, I'm the only one working on the files, so it's a fairly contained problem. But this seems like a fairly serious issue – I'm actually quite surprised there aren't more reports, at least if it affects everyone.

**Comment by afeldinger** [comment]
I just manually changed the node-sass included with gulp-sass to version 3.4.1, and everything is working as expected again.

**Comment by xzyfer** [comment]
@nastiatikk I an unable to reproduce the malloc with node-sass 3.4.2

**Comment by xzyfer** [comment]
I an unable to reproduce this error. Unless someone can produce some sample Sass code that produces this error there is nothing we can do.

**Comment by bvdputte** [comment]
I am experiencing the same issues...

I've created a gist (https://gist.github.com/bvdputte/1529fa195f2be2ebb04f) based upon files above which does trigger the malloc error; there is a missing semicolon on line 5 of _alert.scss -> this shouldn't be throwing a meaningless malloc error, but useful debug information.

As stated above, there are many other minor "issues" that trigger the malloc error as well (e.g. using a variable name with a typo in it, ...).

Screenshot of the error:
![screen shot 2016-01-19 at 09 57 51](https://cloud.githubusercontent.com/assets/490505/12414015/279a28be-be93-11e5-898c-348234e3b202.png)

*Versions*:
node: v5.2.0
npm: 3.3.12
"gulp": "~3.9.0",
"gulp-sass": "^2.1.1",
node-sass: 3.4.1

**Comment by bvdputte** [comment]
FYI; I've just retested this with another node and npm version

node v4.2.4
npm 2.14.12

Same results :-(

**Comment by xzyfer** [comment]
@bvdputte please don't comment on closed issues. These are unlikely to be related. Open a new issue with all the relevent information from our [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md).
