### ISSUE TITLE
node-sass fails to install with pre-existing binary on alpine linux

### ISSUE THREAD

**Issue by johanb** [sass/node-sass#1282]
I'm sorry if this issue has been reported before or if I'm doing it wrong. I've tried searching but couldn't find any similar issues on google nor github (forgive me if I searched wrong). 

I'm trying to install node-sass on an alpine-linux docker-container. This is all part of some larger application that uses guilp to build it's assets. However for this bug report I've made an attempt to make the problem as small as possible, so I've tried to isolate the issue as much as possible. Here is what I've come up with to illustrate what I'm experiencing:

Here is my configuration:

## Dockerfile
```Dockerfile
FROM mhart/alpine-node

COPY bin/ /usr/local/bin

RUN install-libsass

#RUN SASS_BINARY_PATH=/usr/bin/sass npm install node-sass --sass-binary-path='/usr/bin/sass'
```

## bin/install-libsass
```
#!/bin/sh

# build
apk --update add git build-base
git clone https://github.com/sass/sassc
cd sassc
git clone https://github.com/sass/libsass
SASS_LIBSASS_PATH=/sassc/libsass make

# install
mv bin/sassc /usr/bin/sass

# cleanup
cd /
rm -rf /sassc
apk del git build-base
apk add libstdc++ # sass binary still needs this because of dynamic linking.
rm -rf /var/cache/apk/*
```

If I uncomment the last line from the `Dockerfile`, I get the following output: https://gist.github.com/johanb/c2f47b52afb9e090c236

The problematic lines from the log I've tracked down seem to be this:

```
` /usr/bin/sass ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
```

Which in turn lead me here: https://github.com/sass/node-sass/blob/master/scripts/build.js#L209

But I can't figure out why the binary would not be correct according to `node-sass`

I've confirmed the `sass` binary is actually correct using the following script:

## bin/test-sass
```
#!/bin/sh
echo --- Tests ---

echo -n "it should install sassc 3.3.0... "
sass -v | grep sassc | grep "3.3.0" > /dev/null
[ "$?" -ne 0 ] && echo nope && exit 1
echo ok

echo -n "it should compile SCSS... "
echo '$blue: #00f; .thing { color: $blue; }' > /tmp/test.scss
sass /tmp/test.scss | grep "color: #00f" > /dev/null
[ "$?" -ne 0 ] && echo nope && exit 1
rm /tmp/test.scss
echo ok
```

which, when run inside the container, outputs:

```
--- Tests ---
it should install sassc 3.3.0... ok
it should compile SCSS... ok
```

Output from process.versions

```
{ http_parser: '2.6.0',
  node: '5.1.0',
  v8: '4.6.85.31',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '47',
  openssl: '1.0.2d' }
```

What am I doing wrong ? Thank you for your time.

**Comment by saper** [comment]
I find the report confusing a bit, but I think some things needs to be explained:

- libsass is a library in C++ that is used by node-sass and sassc
- sassc and node-sass are independent from each other, sassc is not needed by node-sass to run
- node-sass has it's own little piece of C++ code, "a binding" that mediates between v8, a Javascript engine written in C++ and the libsass binary. This binding comes in a form of a shared library and we publish those binaries for many platforms at https://github.com/sass/node-sass/releases
- node-sass when compiled normally uses a bundled set of C++ sources that contain both the binding and a complete libsass code
- node-sass binding code is tightly bound to the version of libsass it is using, to the node engine version and the platform
- therefore, in a general case, one does need neither libsass nor sassc pre-installed. Node-sass requires a modern C++11 library to run and of course the node engine it was compiled against. It is possible to have multiple binding binaries stored in the "vendor" directory if one plans to share the installation between different node engines and/or platforms
- one can compile a binding yourself, for that a modern C++11 compiler is needed and the C/C++ header and GYP (build tool  generating make files) configuration files matching the node engine used. The header and configuration files will be downloaded by the build process if needed.
- whenever we mean "the binary" in a node-sass context we always mean the binding code (*.node file) and not sassc.
- it *is* possible to compile node-sass binding using a pre-installed libsass library, but it is definitely not recommended at this stage.

**Comment by saper** [comment]
Can you give me the output of the `process.execPath` after you start `node` by hand?

**Comment by xzyfer** [comment]
@johanb I don't see you install node-sass anywhere in your setup.

**Comment by camsjams** [comment]
Try this:
https://github.com/jbergknoff/Dockerfile/blob/c8b94cf41348bd60f753364237811c8365ebd4d6/sass/build.sh

**Comment by xzyfer** [comment]
We're working on Alpine Linux support in https://github.com/sass/node-sass/issues/1589 and could use your help!
