### ISSUE TITLE
Compile error with vs2013 functions.cpp

### ISSUE THREAD

**Issue by WangZhechao** [sass/node-sass#1284]
I use vs2013 compile the project, I always make some mistakes when I build it。

example：

```
 libsass\src\functions.cpp(1176) : error C2065: 'distributed' : undeclared identifier
 libsass\src\functions.cpp(1176) : error C2061: syntax error : identifier 'uint_fast32_t'
```

I tried to fix the error:

functions.cpp file
```
#include <cstdint>   <= add it
#include <cstdlib>
#include <cmath>
#include <cctype>

```

it is ok!

**Comment by xzyfer** [comment]
Thanks for the report @WangZhechao. This is a known issue in the latest LibSass release - https://github.com/sass/libsass/pull/1719

Whether they/we continue to support VS 2013 is an open question. Please comment there if that is something you require.

We should update our readme to mention we require VS 2015 now.
