### ISSUE TITLE
Problems on color:white

### ISSUE THREAD

**Issue by Thorgrim901** [sass/node-sass#1295]
Hi everyone
when compiling a file with this style inside

```
.ciao
  color:white
```

the compiler doesn't output anything and it doesn't give me errors

![image](https://cloud.githubusercontent.com/assets/3064143/11597567/c9aaa3fe-9abc-11e5-934a-6238d9f0f458.png)

is this a bug?

massimiliano

**Comment by xzyfer** [comment]
Thanks for the report @Thorgrim901. When running this code with Ruby Sass I get the following warning and no output.

```
WARNING on line 2 of test.sass:
This selector doesn't have any properties and will not be rendered.
```

Node Sass must compile the same as Ruby Sass, so this is not a bug.

**Comment by wytesk133** [comment]
@Thorgrim901 You were missing a space between `:` and `w`
This is what it should be
```sass
.ciao
  color: white
```
