### ISSUE TITLE
'libsass bindings not found. Try reinstalling 'node-sass'?

### ISSUE THREAD

**Issue by jgacuca567** [sass/node-sass#1298]
Referencing Issue #918 

I did `npm install node-sass`

However when I do that, I keep getting the error that current version of  `lodash` is no longer maintained, is it a problem on my side or your side?

See Screenshot Below 
<img width="701" alt="screen shot 2015-12-06 at 1 11 07 pm" src="https://cloud.githubusercontent.com/assets/4000076/11614770/da3592ba-9c1a-11e5-94a8-4e0e94453f19.png">

**Comment by xzyfer** [comment]
You can safely ignore this warning.

**Comment by jgacuca567** [comment]
I updated my version of `lodash` and I had to install compass, once I did,
I was able to run grunt without any errors.

Thanks.

On Sun, Dec 6, 2015 at 5:11 PM Michael Mifsud <notifications@github.com>
wrote:

> You can safely ignore this warning.
> On 7 Dec 2015 5:11 am, "jgacuca567" <notifications@github.com> wrote:
>
> > Referencing Issue #918 <https://github.com/sass/node-sass/issues/918>
> >
> > I did npm install node-sass
> >
> > However when I do that, I keep getting the error that current version of
> > lodash is no longer maintained, is it a problem on my side or your side?
> >
> > See Screenshot Below
> > [image: screen shot 2015-12-06 at 1 11 07 pm]
> > <
> https://cloud.githubusercontent.com/assets/4000076/11614770/da3592ba-9c1a-11e5-94a8-4e0e94453f19.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sass/node-sass/issues/1298>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sass/node-sass/issues/1298#issuecomment-162353452>.
>
-- 
James Gacuca
jgacuca@gmail.com
(202)-569-1159
