### ISSUE TITLE
indented sass does not output proper result

### ISSUE THREAD

**Issue by omenking** [sass/node-sass#1300]
My sass (1.0):

```sass
.testing
  :margin
    :bottom 32px
```

My javascript
```js
var fs   = require('fs');
var sass = require('node-sass');
sass.render({
   file           : 'style.sass'
  ,outFile        : 'style.css'
  ,indentedSyntax : true
},function(err, result){
  fs.writeFile('style.css', result.css, function(err){
    if(!err){}
  });
});
```

The result
```css
.testing :margin {
  bottom: 32px; }
```

**Comment by omenking** [comment]
If I change the colon syntax to the colon to come afterword I get the correct result. I could not find a configure option for the preference of colon in front. Does this port not support the colon in-front syntax?

```sass
.testing
  :margin
    :bottom 32px
```

**Comment by xzyfer** [comment]
Thanks for the report @omenking.

This a bug in sass2scss which LibSass uses to parse the indented syntax. I've created a bug in LibSass to track this. Please subscribe to https://github.com/sass/libsass/issues/1781 for updates.

**Comment by mgreter** [comment]
Already looked into that syntax last year, but it was too hard and complicated, since it looks very similar to pseudo selector. Not even sure what the heuristics should be to differentiate those two cases.

**Comment by xzyfer** [comment]
@chriseppstein can you shed some light on to the @mgreter query?
