### ISSUE TITLE
can u change git@github.com:sass/libsass.git to https?

### ISSUE THREAD

**Issue by DavidKk** [sass/node-sass#1301]
it can be more friendly, `some people just know npm install....`
```
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
````
thx

**Comment by xzyfer** [comment]
Change this where exactly?

**Comment by DavidKk** [comment]
it in node-sass/scripts/build.js 

git@github.com:sass/libsass.git
https://github.com/sass/libsass.git

![image](https://cloud.githubusercontent.com/assets/4200041/11717807/aff30a52-9f8d-11e5-8f04-eb469b915a0c.png)

**Comment by saper** [comment]
Sure we can: filed #1306 for review

**Comment by DavidKk** [comment]
OK ^_^ thx
