### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`

### ISSUE THREAD

**Issue by samdeesh** [sass/node-sass#1305]
Creating a new issue as I was not able to comment https://github.com/sass/node-sass/issues/918
I am using a windows machine & faced the issue tried rebuild, uninstall & latest install nothing is working with logs below:

C:\imageSearch>npm rebuild node-sass

> node-sass@3.4.2 install C:\imageSearch\node_modules\node-sass
> node scripts/install.js

> node-sass@3.4.2 postinstall C:\imageSearch\node_modules\node-sass
> node scripts/build.js

` C:\imageSearch\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exist
s.
 testing binary.
Binary is fine; exiting.

> node-sass@2.1.1 install C:\imageSearch\node_modules\gulp-sass\node_modules\nod
e-sass
> node scripts/install.js

> node-sass@2.1.1 postinstall C:\imageSearch\node_modules\gulp-sass\node_modules
\node-sass
> node scripts/build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 522 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (C:\imageSearch\node_modules\gulp-sass
\node_modules\node-sass\node_modules\pangyp\lib\install.js:252:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\imageSearch\node_modules\gul
p-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.j
s:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\imageSearch\\node_mo
dules\\gulp-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp"
"rebuild"
gyp ERR! cwd C:\imageSearch\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v4.2.3
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok
Build failed
node-sass@3.4.2 C:\imageSearch\node_modules\node-sass
node-sass@2.1.1 C:\imageSearch\node_modules\gulp-sass\node_modules\node-sass

C:\imageSearch>npm uninstall node-sass
unbuild node-sass@3.4.2

C:\imageSearch>npm install node-sass
npm WARN package.json imageStock@0.0.0 No repository field.
npm WARN package.json imageStock@0.0.0 No license field.
\
> spawn-sync@1.0.13 postinstall C:\imageSearch\node_modules\node-sass\node_modul
es\cross-spawn\node_modules\spawn-sync
> node postinstall

/
> node-sass@3.4.2 install C:\imageSearch\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\imageSearch\node_modules\node-sass\vendor\
win32-x64-46\binding.node

> node-sass@3.4.2 postinstall C:\imageSearch\node_modules\node-sass
> node scripts/build.js

` C:\imageSearch\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exist
s.
 testing binary.
Binary is fine; exiting.
node-sass@3.4.2 node_modules\node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── sass-graph@2.0.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2
.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── nan@2.1.0
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.3, semv
er@4.3.6, osenv@0.1.3, config-chain@1.1.9, nopt@3.0.6)
├── meow@3.6.0 (trim-newlines@1.0.0, object-assign@4.0.1, minimist@1.2.0, camelc
ase-keys@2.0.0, loud-rejection@1.2.0, redent@1.0.0, normalize-package-data@2.3.5
, read-pkg-up@1.0.1)
├── cross-spawn@2.1.0 (cross-spawn-async@2.1.1, spawn-sync@1.0.13)
├── gaze@0.5.2 (globule@0.1.0)
├── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oa
uth-sign@0.8.0, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstre
am@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, qs@5.2.0,
 node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.8, form-data@1.0.0-rc3,
bl@1.0.0, hawk@3.1.2, http-signature@1.1.0, har-validator@2.0.3)
└── node-gyp@3.2.1 (graceful-fs@4.1.2, semver@5.1.0, osenv@0.1.3, fstream@1.0.8,
 nopt@3.0.6, minimatch@1.0.0, tar@2.2.1, which@1.2.0, glob@4.5.3, path-array@1.0
.0, rimraf@2.4.4, npmlog@1.2.1)

C:\imageSearch>gulp dev
[14:01:09] Using gulpfile C:\imageSearch\Gulpfile.js
[14:01:14] Starting 'clean'...
[14:01:15] Starting 'lint'...
[14:02:00] Starting 'staticAnalysis'...
[14:02:09] ESLint found no problems in 1 file
[14:02:10] ESLint found no problems in 1 file
[14:02:10] ESLint found no problems in 1 file
[14:02:10] Finished 'clean' after 57 s
[14:02:10] Starting 'markup'...
[14:02:10] Starting 'styles'...
[14:02:11] 'styles' errored after 147 ms
[14:02:11] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (C:\imageSearch\node_modules\gulp-sass\node_modules\node-sass\
lib\index.js:22:11)
    at Object.<anonymous> (C:\imageSearch\node_modules\gulp-sass\node_modules\no
de-sass\lib\index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\imageSearch\node_modules\gulp-sass\index.js:3:17)
    at Module._compile (module.js:435:26)
[14:02:11] ESLint found no problems in 1 file
[14:02:11] ESLint found no problems in 1 file
[14:02:11] ESLint found no problems in 1 file
[14:02:11] ESLint found no problems in 1 file
[14:02:11] ESLint found no problems in 1 file
[14:02:11] Finished 'lint' after 56 s
[14:02:11] Finished 'markup' after 478 ms
[14:02:12] Finished 'staticAnalysis' after 12 s

C:\imageSearch>npm intsall node@lates

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Samdeesh\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.14.7 C:\Program Files\nodejs\node_modules\npm

C:\imageSearch>npm intsall node@latest

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Samdeesh\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.14.7 C:\Program Files\nodejs\node_modules\npm

C:\imageSearch>npm install node@latest
npm WARN package.json imageStock@0.0.0 No repository field.
npm WARN package.json imageStock@0.0.0 No license field.
npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.o
rg/
^CTerminate batch job (Y/N)? y

C:\imageSearch>npm install -g node@latest
npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.o
rg/
node@0.0.0 C:\Users\Samdeesh\AppData\Roaming\npm\node_modules\node

C:\imageSearch>node -v
v4.2.3

C:\imageSearch>npm -v
2.14.7

**Comment by xzyfer** [comment]
Looks like you have both node-sass@2.1.1 and node-sass@3.4.2. You can
confirm this with `npm ls node-sass`.

Unfortunately node-sass@2 can only be installed with nkde 0.10 or 0.12.

**Comment by samdeesh** [comment]
yup I found 2 versions:
C:\imageSearch>npm ls node-sass
imageStock@0.0.0 C:\imageSearch
├─┬ gulp-sass@1.3.3
│ └── node-sass@2.1.1
└── node-sass@3.4.2  extraneous

npm ERR! extraneous: node-sass@3.4.2 C:\imageSearch\node_modules\node-sass

What Shall I DO?

**Comment by samdeesh** [comment]
Re-installed gulp-sass & remove node-sass. 
Fixed now.. Thanks for the pointer

**Comment by aditcmarix** [comment]
I also have the same problem.
I remove node-sass and re installed gulp-sass and its working

Thanks

**Comment by MikeBarnhardt** [comment]
Also, `npm rebuild node-sass` should work.

**Comment by lb091188** [comment]
gulp-sass is same as node-sass?I remember it build of Ruby~
