### ISSUE TITLE
An install error on windows10

### ISSUE THREAD

**Issue by lmnsg** [sass/node-sass#1312]
OS: win10
node: v5.3.0
npm:3.5.2

some log:
install:sass-graph        ▐ ╢█████████████████████████████████████████
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-47_binding.node":

connect ETIMEDOUT 54.231.49.32:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
install:sass-graph        ▐ ╢█████████████████████████████████████████
postinstall               ▌ ╢█████████████████████████████████████████
postinstall               ▌ ╢█████████████████████████████████████████
postinstall:assert-plus → ▀ ╢█████████████████████████████████████████
postinstall:boom → lifecy ▐ ╢█████████████████████████████████████████
postinstall:lodash.repeat ▐ ╢█████████████████████████████████████████
postinstall:semver        ▄ ╢█████████████████████████████████████████
postinstall:qs → lifecycl ▄ ╢█████████████████████████████████████████
postinstall:tough-cookie  ▀ ╢█████████████████████████████████████████

> spawn-sync@1.0.13 postinstall D:\testsass\node_modules\spawn-sync
> node postinstall

postinstall:concat-stream ▄ ╢█████████████████████████████████████████
postinstall:concat-stream ▄ ╢█████████████████████████████████████████
postinstall:request       ▐ ╢█████████████████████████████████████████

> node-sass@3.4.2 postinstall D:\testsass\node_modules\node-sass
> node scripts/build.js

postinstall:sass-graph    ▌ ╢█████████████████████████████████████████
Building: C:\Program Files\nodejs\node.exe D:\testsass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\testsass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.2.1
gyp info using node@5.3.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (D:\testsass\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (D:\testsass\node_modules\which\which.js:82:29)
gyp verb `which` failed     at D:\testsass\node_modules\which\which.js:93:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (D:\testsass\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (D:\testsass\node_modules\which\which.js:82:29)
gyp verb `which` failed     at D:\testsass\node_modules\which\which.js:93:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python [Error: not found: python]
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\testsass\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at D:\testsass\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\testsass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\testsass\node_modules\node-sass
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Build failed
postinstall:sass-graph    ▌ ╢█████████████████████████████████████████
postinstall → rollbackFai ▌ ╢█████████████████████████████████████████
postinstall → rollbackFai ▀ ╢█████████████████████████████████████████
runTopLevelLifecycles     ▌ ╢█████████████████████████████████████████
npm WARN ENOENT ENOENT: no such file or directory, open 'D:\testsass\package.json'
runTopLevelLifecycles     ▀ ╢█████████████████████████████████████████
npm WARN EPACKAGEJSON testsass No description
runTopLevelLifecycles     ▐ ╢█████████████████████████████████████████
npm WARN EPACKAGEJSON testsass No repository field.
runTopLevelLifecycles     ▄ ╢█████████████████████████████████████████
npm WARN EPACKAGEJSON testsass No README data
runTopLevelLifecycles     ▌ ╢█████████████████████████████████████████
npm WARN EPACKAGEJSON testsass No license field.
runTopLevelLifecycles     ▀ ╢█████████████████████████████████████████
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-sass" "-save"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\testsass\npm-debug.log

help......

**Comment by xzyfer** [comment]
Please read the error message.

>Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-47_binding.node":
>
>connect ETIMEDOUT 54.231.49.32:443
>
>Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.
>```
>  export HTTP_PROXY=http://example.com:1234
>```
>or configure npm proxy via
>```
>  npm config set proxy http://example.com:8080
>```

This is a networking issue either with your network or npm. Nothing to do with node-sass.

**Comment by hanxu317317** [comment]
i have the same issue.it's not the network problem.
i ping github.com.the network is right.

**Comment by saper** [comment]
@hanxu317317 I'd double check if you have a "man in the middle" transparent proxy for SSL. For example, check SSL certificates you are getting.
