### ISSUE TITLE
Should properly print the error info instead of segment fault from a specific case.

### ISSUE THREAD

**Issue by linmic** [sass/node-sass#1316]
I've encountered an issue that, I forgot to append semicolon at the end of line within a nested sass code. And it just stdout the segment fault message instead of proper error messages. The minimum sample code is as following:

```sass
.a {
  display: block /* here */

  a {

    &::after {
      color: red;
    }
  }
}
```

The only error message I got from node-sass:

```
zsh: segmentation fault  ./node_modules/.bin/node-sass b.scss
```

The ruby version have this right, it printed out:

```
Error: Illegal nesting: Only properties may be nested beneath properties.
        on line 6 of b.scss
  Use --trace for backtrace.
```

My env:

```
node        4.2.4
node-sass   3.4.2     (Wrapper)       [JavaScript]
libsass     3.3.2     (Sass Compiler) [C/C++]
```

Thanks.

**Comment by xzyfer** [comment]
Thanks for the report @linmic. This is an issue with LibSass. I've open https://github.com/sass/libsass/issues/1803 with them.

Unfortunately segfaults are fatals error that node-sass cannot do anything about.
