### ISSUE TITLE
Cannot install node-sass version 3.1.2

### ISSUE THREAD

**Issue by ahayakawalv** [sass/node-sass#1327]
I tried running $ npm install node-sass@3.1.2, but I received this error:

> node-sass@3.1.2 install /Library/WebServer/Documents/plan-html/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.1.2/darwin-x64-46_binding.node": HTTP error 404 Not Found

> node-sass@3.1.2 postinstall /Library/WebServer/Documents/plan-html/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
module.js:340
    throw err;
    ^

Error: Cannot find module '/Library/WebServer/Documents/plan-html/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
Build failed

OS: OS X 10.10.5
Node: 4.2.4
NPM: 3.5.2

It seems to be the github url to download is not working. Thanks for looking into it!

**Comment by saper** [comment]
node-sass 3.1.2 is too old for node 4.x 
Use the newest version of node-sass (3.4.2 currently).
