### ISSUE TITLE
Node-gyp fails to compile

### ISSUE THREAD

**Issue by s-a** [sass/node-sass#1328]
Ref:
- https://github.com/s-a/iron-node/issues/61
- https://github.com/electronjs/electron-rebuild/issues/42

**Comment by xzyfer** [comment]
A quick search of the closed issue would have revealed that we don't currently support atom shell. https://github.com/sass/node-sass/issues/1047

We're happy to readdress this situation if someone from the atom community is willing and able to contribute patches for that ecosystem.

Currently noone on the core team uses, or is experience with atom shell. There are also no CI services, that we're aware off, to tracking regressions.

**Comment by matthew-dean** [comment]
This also fails for NW.js.

**Comment by stefanKuijers** [comment]
@xzyfer If I see it right there is now [CI support for Electron](https://github.com/atom/electron/issues/190) using Travis. What would be needed to change the opinion on supporting electron? 

I've been trying to solve the support but at the moment I don't even really know where to start. It would be great to find out a way we could get this support in. I'd be glad to help where I can.

**Comment by xzyfer** [comment]
@stefanKuijers that's interesting to see. I'm not familiar with the Electron ecosystem but this a step in the right direction. The team is currently busy with other things for the time being but we'd be interested in hearing about your progress.

**Comment by stefanKuijers** [comment]
Well... as I stated before I don't even know where to start. I've been trying to understand this node-gyp thing and tried to solve this on my local machine as well but I did not get far. The only success I had was to fix support for linux with a local rebuild through node-gyp with electron headers. For that I did not have to do anything special but on Windows I got stuck. 

I am now looking for alternatives cause in this building and compiling world I feel out of my league. If you can give me some pointers and articles on how this stuff works I am still happy to look into this though. I'd love to learn something new anytime :D

**Comment by saper** [comment]
You can have a look at the node-git project, I think they use node-pre-gyp and boty electron and nw.js are supported there.

**Comment by stefanKuijers** [comment]
Thanks for the pointer. I will look into that project to see how they fixed it there. :)
