### ISSUE TITLE
Node-sass installation failure

### ISSUE THREAD

**Issue by Mohit127** [sass/node-sass#1332]
I have been trying to install node-sass but had no sucseess. Using latest version of node and npm. 

![nodesass](https://cloud.githubusercontent.com/assets/3339818/12146662/d66b95d6-b4ba-11e5-9ab2-f3f4585eca2c.JPG)

**Comment by gogomartin** [comment]
I have a similar issue on Linux Rasbian.

'''
/var/blog/twister-jekyll-theme-master $ npm install
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN prefer global jshint@2.5.11 should be installed with -g

> node-sass@0.9.3 install /var/blog/twister-jekyll-theme-master/node_modules/node-sass
> node build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Går till katalogen ”/var/blog/twister-jekyll-theme-master/node_modules/node-sass/build”
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../../nan/nan.h:337:64: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(nan_isolate, receiver, argc, argv);
                                                                ^
../../nan/nan.h:337:64: note: candidate is:
In file included from /home/pi/.node-gyp/5.2.0/include/node/node.h:42:0,
                 from ../../nan/nan.h:157,
                 from ../binding.cpp:1:
/home/pi/.node-gyp/5.2.0/include/node/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/pi/.node-gyp/5.2.0/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../binding.cpp:1:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:409:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../../nan/nan.h:409:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../../nan/nan.h:409:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../../nan/nan.h:403:36: note: previous declaration ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../../nan/nan.h:409:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../../nan/nan.h:409:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../../nan/nan.h:427:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
   NanNew<v8::StringObject, v8::Handle<v8::String> >(
   ^
../../nan/nan.h:420:3: note: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
   NanNew<v8::StringObject, v8::Local<v8::String> >(
   ^
../../nan/nan.h:444:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:438:36: note: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:456:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:450:36: note: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:767:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:767:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:770:57: error: ‘callback’ was not declared in this scope
     return node::Buffer::New(nan_isolate, data, length, callback, hint);
                                                         ^
../../nan/nan.h:770:67: error: ‘hint’ was not declared in this scope
     return node::Buffer::New(nan_isolate, data, length, callback, hint);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:777:53: error: call of overloaded ‘New(v8::Isolate*&, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(nan_isolate, data, size);
                                                     ^
../../nan/nan.h:777:53: note: candidates are:
In file included from ../../nan/nan.h:158:0,
                 from ../binding.cpp:1:
/home/pi/.node-gyp/5.2.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/5.2.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/pi/.node-gyp/5.2.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/5.2.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../binding.cpp:1:0:
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:781:47: error: could not convert ‘node::Buffer::New(nan_isolate, size)’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(nan_isolate, size);
                                               ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:788:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(nan_isolate, data, size);
            ^
../../nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../../nan/nan.h:1728:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../../nan/nan.h:1729:23: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../../nan/nan.h:1730:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../../nan/nan.h:1730:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
../binding.cpp: In function ‘void MakeCallback(uv_work_t*)’:
../binding.cpp:124:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/pi/.node-gyp/5.2.0/include/node/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
                                   ^
binding.target.mk:118: receptet för målet ”Release/obj.target/binding/binding.o” misslyckades
make: *** [Release/obj.target/binding/binding.o] Fel 1
make: Lämnar katalogen ”/var/blog/twister-jekyll-theme-master/node_modules/node-sass/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Linux 4.1.13+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/blog/twister-jekyll-theme-master/node_modules/node-sass
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
Build failed
'''

**Comment by saper** [comment]
@gogomartin This is not the same issue: you are using an ancient version of node-sass and the newest version of node, that won't work. Please upgrade.

@mohit127 it seems this yet another instance of #1283 - let's follow up there
