### ISSUE TITLE
npmconf is a deprecated and unmaintained dependency

### ISSUE THREAD

**Issue by yannickcr** [sass/node-sass#1333]
node-sass is using [npmconf](https://github.com/npm/npmconf) but this package is now deprecated and unmaintained.

Therefore some npmconf issue like npm/npmconf#61 makes node-sass impossible to install in some environments.

It would be great if the npmconf dependency could be removed/replaced.

**Comment by xzyfer** [comment]
Querying what the alternative is now. npmconf is rather important to our internals and cannot simply be removed without an alternative.

**Comment by xzyfer** [comment]
>run npm get proxy and npm get https-proxy as child processes. If that feels kind of clunky and heavyweight, I agree, but that's the most robust way to do it.
> https://github.com/npm/npmconf/pull/61#issuecomment-169523714

**Comment by xzyfer** [comment]
As per https://github.com/npm/npmconf/pull/61#issuecomment-170880758

We'll like pull just the proxy code from npmconf into node-sass core.

**Comment by adambuczynski** [comment]
Is this an issues that is going to be addressed still? I'm getting this warning for all my installs now:

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

**Comment by xzyfer** [comment]
We won't be changing this is the near future. Warnings can be ignored.

**Comment by adambuczynski** [comment]
I know they can be ignored, but they ain't pretty. Is there no other way to do the thing that npmconf does? Or perhaps just take the lib and embed it within node-sass?

**Comment by danez** [comment]
You could simply replace the npmconf call with Environment variables. All configurations from npm are added to `process.env` if run in the context of npm.

PhantomJS fixed it that way.
https://github.com/Medium/phantomjs/commit/2620fb283439181cab0a99b89fdf4532455bc35d#diff-f16acefe4b6553580c43edab685f50f3L168

**Comment by xzyfer** [comment]
This patch was reverted in v3.5.2 because it was not functionally equivalent and broke installations for some proxy users.

**Comment by jorrit** [comment]
In which cases did it not work?

**Comment by xzyfer** [comment]
Not 100% sure but we got many reports of installations failing behind proxies.

https://github.com/sass/node-sass/issues/1458

**Comment by xzyfer** [comment]
I noticed once case that wasn't counted for was the `.npmrc` config file. Could be related.
