### ISSUE TITLE
Merge media queries with same conditions

### ISSUE THREAD

**Issue by manuel-di-iorio** [sass/node-sass#1335]
Use case (scss):

	body {
		font-size: 15pt;
		
		@media (max-width: 40em) {
			font-size: 13pt;
		}
	}

	header {
		font-size: 17pt;
		
		@media (max-width: 40em) {
			font-size: 15pt;
		}
	}

This will be compiled in nested mode to:

	body {
	  font-size: 15pt; }
	  @media (max-width: 40em) {
		body {
		  font-size: 13pt; } }

	header {
	  font-size: 17pt; }
	  @media (max-width: 40em) {
		header {
		  font-size: 15pt; } }

Same with compressed output:

    body{font-size:15pt}@media (max-width: 40em){body{font-size:13pt}}header{font-size:17pt}@media (max-width: 40em){header{font-size:15pt}}

As you can see, as the file will become more complex, as more media queries with same conditions there will be, not good if you want to compress your css a lot, but still using the powerful syntax of sass :)

**Comment by saper** [comment]
Closing in favour of https://github.com/sass/libsass/issues/1840
