### ISSUE TITLE
Install failure on fresh install, works on second

### ISSUE THREAD

**Issue by wesleytodd** [sass/node-sass#1336]
When doing a fresh install I am getting this error:

```
Error: Cannot find module 'once'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (<...>/node_modules/npmconf/npmconf.js:6:12)
```
The second install succeeds.  I was not getting this when using `npm@2.x`, but am now using `npm@3.x`.  Pretty sure it has to do with the [install script that uses npmconf](https://github.com/sass/node-sass/blob/master/scripts/install.js#L8).  Seems like npm is not done installing when it runs the post install script for this package.  

I will also open an issue on npm for this because it is probably something they should also fix.

**Comment by saper** [comment]
I read your bug report on https://github.com/npm/npm/issues/11101 and I don't understand how this is a bug in node-sass.  I also do not know who can I try to reproduce it?

**Comment by wesleytodd** [comment]
So I am only able to reporo it on my linux boxes (digital ocean Ubuntu 14) when doing my actual production builds.  Not entirely sure why there would be a difference, but it happens there every time.

I found that npm issue after filing this, but since that is the current version of npm I feel like getting compatibility here would be worth while until they can fix that.  I can close this if you want :)

**Comment by saper** [comment]
I am interested in fixing this, but somehow your `require()` does not work as it should. Does it help if you downgrade npm a bit?

**Comment by xzyfer** [comment]
I'm not sure there is anything we can do here if the dependency simply isn't there.

**Comment by wesleytodd** [comment]
I totally understand.  I guess we can just close this and see if anyone can shed more light on it.  Personally I solved it by just npm installing twice in my ansible playbook.  easy peazy :)
