### ISSUE TITLE
No binary available for armhf architecture

### ISSUE THREAD

**Issue by henrywright** [sass/node-sass#1340]
Hey guys,

I tried to build WordPress today and realised node-sass doesn't have a pre-compiled binary for armhf. Any chance you can begin to support armhf? Lots of Chromebooks are now using the armhf architecture and also the Raspberry Pi.

For the record, I get this error:

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/linux-arm-11_binding.node": 

HTTP error 404 

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

**Comment by toddmedema** [comment]
Would also greatly appreciate this, using a Raspi to run our web-based home automation system

**Comment by xzyfer** [comment]
Supply prebuilt binaries is predicated on a representative of that community taking the responsibility of generating the binaries. Currently binary generate is either automated or handled by a contributor familiar with a specific platform.

However the node-sass install should fallback to generating the binary locally once the download attempt fails. If this is not happening that there is a bug.

There's one major caveat in that even if the local compilation takes places there's no guarantee that LibSass or node-sass will compile on your architecture. Without the ability to test against a specific architecture in our CI there's no way to know if any when we break things.

This is already an issue with SunOS, who thankfully has some vocal users who are willing able to PR fixes.

**Comment by xzyfer** [comment]
Closing due to lack of community interest.

**Comment by henrywright** [comment]
:cry:

**Comment by xzyfer** [comment]
Sorry @henrywright. Unless someone with an invested interested in armhf architecture is willing to champion this there isn't much we can do.

**Comment by henrywright** [comment]
No worries @xzyfer :)

**Comment by matthova** [comment]
Dang

**Comment by dantrevino** [comment]
In after closed.  Also looking for arm... android-arm for installing under termux on android.  I undertand the need for a maintainer.  My comment is just informational.

**Comment by danquack** [comment]
Can we make this a feature request?

**Comment by xzyfer** [comment]
This is not something we can do without someone from the community willing and able to maintain arm support for us. We simply do not have the capacity, hardward, or expertise to do this.

See https://github.com/sass/node-sass/issues/1340#issuecomment-171660434

**Comment by rugk** [comment]
Hardware? Would not you just need a RasPi?? I think that's really the lowest hardware requirement one can have.

**Comment by xzyfer** [comment]
Quite possibly? I don't know, which is part of the problem. We're open to accepting help.

**Comment by ossdev07** [comment]
Hi @xzyfer,
Still getting following issue while building "node-Sass":
```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/linux-arm64-64_binding.node":

HTTP error 404 Not Found

```
Although it falls back on building the binary, and build it successfully. it would be good if you can provide prebuilt binary for arm64 as Travis-CI have announced multi-platform support.

Let me know if i can help you in any way for the same.
Thanks.

**Comment by dalibouz** [comment]
i resolved this problem by creating a vm linux, i runned the npm install then i copied the directory node-sass from node_modules of vm linux to the node_module of the the raspberry pi.
