### ISSUE TITLE
Installation failure on Windows (10) with nodejs@4.2.3

### ISSUE THREAD

**Issue by 74sharlock** [sass/node-sass#1343]
2935 verbose lifecycle node-sass@3.4.2~postinstall: CWD: D:\editor_research\node_modules\node-sass
    2936 silly lifecycle node-sass@3.4.2~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
    2937 silly lifecycle node-sass@3.4.2~postinstall: Returned: code: 1  signal: null
    2938 info lifecycle node-sass@3.4.2~postinstall: Failed to exec postinstall script
    2939 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
    2939 verbose stack Exit status 1
    2939 verbose stack     at EventEmitter.<anonymous> (C:\Users\Huiyishi\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
    2939 verbose stack     at emitTwo (events.js:87:13)
    2939 verbose stack     at EventEmitter.emit (events.js:172:7)
    2939 verbose stack     at ChildProcess.<anonymous> (C:\Users\Huiyishi\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
    2939 verbose stack     at emitTwo (events.js:87:13)
    2939 verbose stack     at ChildProcess.emit (events.js:172:7)
    2939 verbose stack     at maybeClose (internal/child_process.js:818:16)
    2939 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    2940 verbose pkgid node-sass@3.4.2
    2941 verbose cwd D:\editor_research
    2942 error Windows_NT 10.0.10240
    2943 error argv "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Huiyishi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "node-sass"
    2944 error node v4.2.3
    2945 error npm  v3.5.3
    2946 error code ELIFECYCLE
    2947 error node-sass@3.4.2 postinstall: `node scripts/build.js`
    2947 error Exit status 1
    2948 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
    2948 error Make sure you have the latest version of node.js and npm installed.
    2948 error If you do, this is most likely a problem with the node-sass package,
    2948 error not with npm itself.
    2948 error Tell the author that this fails on your system:
    2948 error     node scripts/build.js
    2948 error You can get information on how to open an issue for this project with:
    2948 error     npm bugs node-sass
    2948 error Or if that isn't available, you can get their info via:
    2948 error     npm owner ls node-sass
    2948 error There is likely additional logging output above.
    2949 verbose exit [ 1, true ]

**Comment by saper** [comment]
Can you share a full log (see our TROUBLESHOOTING.md), since the failure was probably earlier, when we try to download the binary.

**Comment by saper** [comment]
Also, is your node on PATH?

**Comment by 74sharlock** [comment]
I followed <b>TROUBLESHOOTING.md</b>, then I solved this problem.
<b>Sorry</b> && <b>Thanks</b> .
