### ISSUE TITLE
Limited error trace

### ISSUE THREAD

**Issue by kaelig** [sass/node-sass#1345]
## Use case

We're using a custom mixin (`deprecate($version)`) in `vendor/deprecate.scss` to tell us where to look at when a piece of code is deprecated.

Unfortunately, node-sass doesn't give us a full trace of the error and we can't trace where the error originated from.

## Ruby Sass

Very useful output, which tells us where to look (ui/components/buttons/flavors/base/index.scss):

```
Error: Deprecated code was found: please remove it to continue.
        on line 129 of ui/vendor/deprecate.scss, in `deprecate'
        from line 74 of ui/components/buttons/flavors/base/index.scss
        from line 26 of ui/components/index.scss
        from line 28 of ui/index.scss
  Use --trace for backtrace.
```

## Node Sass

Not so useful, outputs a JSON object with only one level of depth.

No way to guess that we should look at ui/components/buttons/flavors/base/index.scss.

```json
{
  "formatted": "Error: Deprecated code was found: please remove it to continue.\n        on line 129 of ui/vendor/deprecate.scss\n>>     @error 'Deprecated code was found: please remove it to continue.';\n   ----^\n",
  "message": "Deprecated code was found: please remove it to continue.",
  "column": 5,
  "line": 129,
  "file": "/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/ui/vendor/deprecate.scss",
  "status": 1
}
```

## Temporary workaround

Until we get better information from `@error`, use `@warn` instead. It gives the necessary amount of info:

```
WARNING: Deprecated code was found: please remove it to continue.
	on line 129 of ui/vendor/deprecate.scss
	from line 30 of ui/utilities/visibility/flavors/collapsed-expanded/index.scss
```

**Comment by xzyfer** [comment]
This situation may improve with the next release

**Comment by xzyfer** [comment]
@kaelig this may be fixed in the upcoming beta. Subscribe to #1349 for updates on that release.

**Comment by kaelig** [comment]
Closing this as I think it was fixed in the last version.

**Comment by lunelson** [comment]
Sorry, it's not fixed. See the linked issue above.
