### ISSUE TITLE
Render issue with empty background url

### ISSUE THREAD

**Issue by su27** [sass/node-sass#1346]
When I try to render something with empty background url, the result seems to be broken with an extra `url(` prepended:

```
> sass.render({'data': 'body{background:url()}'}, function(e,r){console.info(r.css.toString())})
> body {
  background: url(url(); }
```

**Comment by xzyfer** [comment]
I've confirmed this is an issue in LibSass 3.3.2. It got worse in LibSass 3.3.3. There's a patch on master so this should be fixed in node-sass@3.5.0.
