### ISSUE TITLE
Sass file directory from custom function

### ISSUE THREAD

**Issue by glebmachine** [sass/node-sass#1355]
Hi!

How can i rich sass file directory from custom function.
I'm trying to rich my node-sass with following function:

```js
module.exports = {
  'image-height($image)': (image) => {
    var dimensions = imagesize(image.getValue());
    return types.String(dimensions.height + 'px');
  },
};
```

So, here i can't find the way to get *caller sass file* directory.
Please, give me a clue

**Comment by qiu8310** [comment]
Me too

**Comment by xzyfer** [comment]
#1390 makes the options object passed to `render` and `renderSync` available as `this.options` inside custom functions. 

Inside a custom function `this.options.file` will be the file that was compiled by Node Sass. However there is currently no way to know which file is calling a function because of custom importers.

**Comment by danilvalov** [comment]
@glebmachine 
I have some problem. And I don't have the `this.options.file` property (not exists).
But I noticed something. I use `sass-loader` like a wrapper in my webpack config. And there is a property `this.options.includePaths` with a path of the handling sass-file (in the end of the `this.options.includePaths`). I know this is a bad solution. But it works for me.

```
const path = require('path');
const sass = require('node-sass');
const imageSizeOf = require('image-size');

module.exports = {
  'image-height($imageUrl)': function (imageUrl) {
    // Get the last item from the `this.options.includePaths` string
    const absoluteImagePath = this.options.includePaths.split(':').pop();
    const absoluteImageUrl = path.resolve(absoluteImagePath, imageUrl.getValue());
    const dimensions = imageSizeOf(absoluteImageUrl);

    return sass.types.Number(dimensions.height, 'px');
  }
};
```
