### ISSUE TITLE
Old version of lodash?

### ISSUE THREAD

**Issue by troymclure1** [sass/node-sass#1359]
H There, 

Getting an error when I install gulp-sass. Anyway around or should I ignore it?

OSX: 10.10.5
npm 2.11.2
node: v0.12.5
gulp:  3.9.0 
gulp-sass 2.1.1

npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

/node_modules/gulp-sass/node_modules/node-sass/node_modules/gaze/node_modules/globule/node_modules

**Comment by xzyfer** [comment]
We're aware of this warning. You can ignore it.

**Comment by troymclure1** [comment]
thanks @xzyfer.
