### ISSUE TITLE
Arrow functions cause parse/syntax error

### ISSUE THREAD

**Issue by Krail** [sass/node-sass#1364]
When I try to minify a javascript file with an arrow function, I get this type of error in my logs:

    ERROR - Parse error. syntax error
      sortedProjects.sort((a, b) => {

I run the compressor like so,

    new compressor.minify({
      type: 'gcc',
      fileIn: path.join(__dirname, '..', 'public', 'js', element),
      fileOut: path.join(__dirname, '..', 'public', 'js', element.replace(/\.js$/, '.min.js')),
      callback: (err, min) => { if (err) throw err; }
    });

I've ran my code through other online validators, and it is syntactically correct.

**Comment by xzyfer** [comment]
I don't see how this is related to node sass.

**Comment by Krail** [comment]
I'm sorry, wrong repository! `/sigh`
