### ISSUE TITLE
If watching, initially compile

### ISSUE THREAD

**Issue by corysimmons** [sass/node-sass#1369]
I'm using the cli in [npm scripts](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/). I want to watch stuff, but when I do, it doesn't initially trigger. It would be nice if it did, or if you're concerned about XYZ, at least offer a flag like `--initial`.

This would make it so I didn't have to have 2 scripts:

```json
"scripts": {
    "start": "npm-run-all styles:compile-sass styles:watch-sass",
    "styles:compile-sass": "node-sass style.scss > style.css",
    "styles:watch-sass": "node-sass -w style.scss -o ./"
  }
```

:x:

**Comment by xzyfer** [comment]
We have no plans to do this. We believe it's an unnecessary compilation to our CLI for a niche usecase. Your current solution is fine.

**Comment by corysimmons** [comment]
Who is "we"? Sure you don't want to open this up to community discussion since it seems like a rather easy change that I'm sure a lot of people who use npm scripts would really appreciate?

**Comment by xzyfer** [comment]
>Who is "we"?

We are the maintainers of the this project. 

>it seems like a rather easy change

Every new feature adds complexity and a maintenance burden for us. We weigh up the usefulness, and demand for a feature against the complexity, and ongoing support cost.

>that I'm sure a lot of people who use npm scripts would really appreciate

To be frank, if you're going to give the convenience of asset pipelines for something more low level like npm scripts, it's unreasonable to expect package authors to take on the work of making things convenient again.

>We believe it's an unnecessary compilation to our CLI

What you're asking for is very trivially achieved using simple scripting.

```
    "styles:dev": "node-sass style.scss > style.css && node-sass -w style.scss -o ./",
```

**Comment by corysimmons** [comment]
> What you're asking for is very trivially achieved using simple scripting.

Not DRY.

Meh.

**Comment by jhildenbiddle** [comment]
Both sides seem reasonable to me.

@corysimmons: You can remain DRY by leveraging NPM's [custom script arguments](https://docs.npmjs.com/cli/run-script):

```
"scripts": {
  "build:sass": "node-sass -r --output-style compressed src/style.scss -o dist",
  "watch:sass": "npm run build:sass && npm run build:sass -- -w"
}
```

**Comment by dreadrocksean** [comment]
But if both sides seem reasonable, then the edge must go to the customer.  Personally, we devs strive for the most DRY code, regardless of triviality.  It is our culture and many team leads and PM's are chosen based on their strict desire for clean, readable and maintainable code.

To diss this in a public forum as xyzfer has is quite rude.

**Comment by ohxyz** [comment]
Still looking forward to this feature. Would be handy if watch multiple files across different paths. Could save lots of lines in package.json. Still appreciate the effort from maintainers and communities.

**Comment by jakobrosenberg** [comment]
I can't understand why this feature isn't enabled by default, let alone not available.

Is there a single scenario where an initial build is unwanted?

**Comment by rockneverdies55** [comment]
"watch" should be building first then waiting for the updates to rebuild.
