### ISSUE TITLE
Consider supporting x86 Node on OSX

### ISSUE THREAD

**Issue by JKAussieSkater** [sass/node-sass#1370]
Failing to install `node-sass` on Mac OS X (10.11 El Capitan) using node.js x86 architecture.

* I've tried to npm install `node-sass` [using x86 node](https://nodejs.org/download/release/v0.12.9/), it failed to install the node bindings (the `/node_modules/node-sass/vendor/` folder isn't created)
 * npm appears to be caught in a loop which never ends (so the installation is never truly completed, the process can only be aborted by the user)
* The [node-sass-binaries](https://github.com/sass/node-sass-binaries) are completely absent of a `darwin-ia32-11_binding.node`
* Running node-sass anyway produces the following errors in the console log:

```ShellSession
Error: The `libsass` binding was not found in ~/node_modules/node-sass/vendor/darwin-ia32-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```
* Running `npm rebuild node-sass` creates the following errors in the console log:

```ShellSession
> node-sass@3.4.2 install ~/node_modules/node-sass
> node scripts/install.js

module.js:338
    throw err;
    ^
Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/node_modules/node-sass/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "node-sass"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
```
----

## Problem
It seems that the node-sass developers expect all OS X node variants to be x64 . . .

However, some 3rd party web-development applications, like [Brackets.io](http://brackets.io/), operate on their own x86 version of node.js (including in Mac OS X). Without a **darwin-ia32** binding.node, `node-sass` fails to install or function on these 3rd party web-development applications (a major issue for OS X users).

## Solution
Please add the node-sass binaries for **darwin-ia32** architecture.

@jasonsanjose, How did you manage to aquire the [`/node-sass/vendor/darwin-ia32-11/binding.node`](https://github.com/jasonsanjose/brackets-sass/tree/master/node/2.0.3/node_modules/node-sass/vendor/darwin-ia32-11) for your Brackets Sass extension?

Note: Also reported [sass/node-sass-binaries Issue # 120](https://github.com/sass/node-sass-binaries/issues/120)

**Comment by xzyfer** [comment]
Apology, I build the osx binaries and wasn't even away there was 32bit Mac
node runtimes.

This is the first time it has come up.

**Comment by JKAussieSkater** [comment]
It's okay, thanks! 🤘🏿

I noticed a few rogue issues regarding this on various forums, but I guess nobody realised the problem was linked to a missing binary until I posted this issue just now.

Would you be able to include the 32bit binaries for OSX in your future builds?
I was going to build it myself, but I haven't experience at such things and couldn't find any documentation on how to do it 😆

**Comment by xzyfer** [comment]
You can build it locally with

npm build node-sass

I'll see what I can do about distributing the 32bit osx binaries.

**Comment by prejr-dev** [comment]
I've been trying to build it locally with ```node scripts/build.js --target_arch=ia32 -f```` and when I check the binding.node that's produced with file on mac os x, it tells me that
```
vendor/darwin-x64-46/binding.node: Mach-O bundle i386
```

which seems to be the appropriate version to run with the 32bit binary necessary for brackets? When I use the binding brackets, brackets informs me that it hit a sigtrap. Is this a problem with the binary?

**Comment by JKAussieSkater** [comment]
@prejr-dev, the output file `vendor/darwin-x64-xx/` should be `vendor/darwin-ia32-xx/`, which makes me think it wasn't compiled correctly.

I've noticed you've used `--target_arch=ia32`, but perhaps you also need to be using a 32bit version of node as well/instead, in order to compile correctly (I'm not sure myself, but it's worth a try if you've got the time).

@xzyfer, I tried building it locally, but it didn't create the binary. Perhaps there are some dependencies I don't have installed (I only have node & npm on my machine, no python or miscellaneous).

Would you be able to create the binaries and upload them to [the sister site](https://github.com/sass/node-sass-binaries)?

**Comment by xzyfer** [comment]
@JKAussieSkater I've looked into this and unfortunately nodejs doesn't do 32bit releases for OSX. This ties our hands somewhat with regards to our automated releases. 

Can I ask how you managed to install a 32bit node on osx?

**Comment by JKAussieSkater** [comment]
Well, I guess this is why I was wondering how @jasonsanjose created the SASS binary for 32bit node OSX.

You know that corporate giant Adobe?

They've released a surprisingly useful open source IDE for website design, it's called Brackets.io
They use a customised 32bit Node engine for each OS they've ported it to (Linux/Mac/Windows). Installing Brackets on your computer will include a 32bit Node.

But I guess to answer your question: Yes, Node is offered in 32bit for OSX, you can install it from here:
* [December 2015](https://nodejs.org/download/release/v0.12.9/)

**Comment by xzyfer** [comment]
I see, so it looks like 32bit osx releases are only made for 0.10 and 0.12.
If the Node released with brackets is customised as you say it's unlikely
we can compile a binary that'll work for that environment.

**Comment by xzyfer** [comment]
It took a bunch of fiddling around but I have managed to build 32bit darwin binaries. I've attached them to the current v3.7.0 for your experimentation. Please confirm whether these binaries work for you.

If no response is received before v3.8.0 these binaries will not be created moving forward.

**Comment by JKAussieSkater** [comment]
@xzyfer, thank you for doing this! Sorry I didn't get back to you sooner, I'm flooded with university assignments :(

I attempted to install it but it seems to fail when building the binary . . . Here's my console output:

```
$ node /Users/JKAussieSkater/node_modules/node-sass/scripts/build.js --target_arch=ia32 -f
Detected a git install
Cloning libSass into src/libsass
Checking out libsass to 3.3.6
Building: /usr/local/bin/node /Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library= --target_arch=ia32
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=',
gyp verb cli   '--target_arch=ia32' ]
gyp info using node-gyp@3.3.1
gyp info using node@0.12.9 | darwin | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:14:12)
gyp verb `which` failed     at F (/Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:69:19)
gyp verb `which` failed     at E (/Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:81:29)
gyp verb `which` failed     at /Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:90:16
gyp verb `which` failed     at /Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/node_modules/which/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/node_modules/which/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 0.12.9
gyp verb command install [ '0.12.9' ]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'assert-plus'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:336:15)
gyp ERR! stack     at Function.Module._load (module.js:278:25)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! stack     at require (module.js:384:17)
gyp ERR! stack     at Object.<anonymous> (/Users/JKAussieSkater/node_modules/node-sass/node_modules/request/node_modules/http-signature/lib/parser.js:3:14)
gyp ERR! stack     at Module._compile (module.js:460:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
gyp ERR! stack     at Module.load (module.js:355:32)
gyp ERR! stack     at Function.Module._load (module.js:310:12)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! stack     at require (module.js:384:17)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/JKAussieSkater/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" "--target_arch=ia32"
gyp ERR! cwd /Users/JKAussieSkater
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed
```

Would you have any ideas on how I should proceed?

**Comment by xzyfer** [comment]
It looks like you've installed node-sass in a weird way. Just try an `npm install node-sass` in `/tmp` directory.

**Comment by JKAussieSkater** [comment]
Yes, I did do it strangely, it was a fallback because the usual way didn't work. i.e. `npm install node-sass` didn't work.

Actually, I originally tried this:

```npm install git://github.com/sass/node-sass.git#ad4c44c```

Which installed the latest commit, however, it kept installing forever. As though it was stuck in a loop. I left it for 45 minutes, and no further progress.

It was as though it successfully installed node-sass despite not exiting from npm, however, as before, the `/vendor/` folder is still absent, and no binaries were compiled.

Any ideas?

**Comment by xzyfer** [comment]
You should never use `npm install git://. It's behaviour is undefined. 

This fix is in the latest release so all you need to do is `npm install node-sass`. Please define `didn't work`

**Comment by JKAussieSkater** [comment]
Actually, I just want to add, it seems as though some users (including myself) are unable to build binaries automatically via `npm install node-sass`

It just doesn't work. Probably because I'm not a pro-developer, and my computer is missing some software packages that pro-developers usually have. I've tried to install `npm install node-sass` in Darwin 64bit node, same result. And I've tried to install it on Windows 10 (64bit), no success.

Perhaps there's a strange incompatibility with Intel Core 2 Duo processors?

It's not the best "solution", but uploading a pre-compiled binary to [node-sass-binaries](https://github.com/sass/node-sass-binaries) would mean I (and others) simply wouldn't have to worry about building our own binary, and could manually download it after the partial installation of `npm install node-sass`.

**Comment by xzyfer** [comment]
You should never need to build the binary locally. `npm install node-sass` will fetch a precompiled binary for you. You need a very specific environment to compile native extensions which is why we supply a collection of binaries.

Please be more specific when you say the install doesn't work. We have detailed documentation in our troubleshooting guide on how to report installation issues.

We already upload the precompiled binaries to `node-sass-binaries` that's the reason for it's existence. However we actively discourage using this repository, it's mostly for record keeping. We attach all the precompiled binaries to the Github release page for each release.

This issue is specifically about supplying a precompiled 32bit osx binary which I have done for you. This binary should be automatically downloaded when running `npm install node-sass@latest` with a 32bit node version.

**Comment by JKAussieSkater** [comment]
Here is a screenshot of "not working" . . . 

![screenshot](https://cloud.githubusercontent.com/assets/12983913/15594961/1eccf40c-23fe-11e6-8441-f012c53f0486.png)

By the way, thank you for your detailed response! I really appreciate your effort!

Here is a screenshot of "meanwhile, as the terminal does this infinite loop of nothing, this folder was created . . . "

![screenshot 2](https://cloud.githubusercontent.com/assets/12983913/15595002/7e0f4e10-23fe-11e6-8537-33be0c2c32e8.png)

So certainly the package is successfully being installed, but it isn't succeeding at retrieving the precompiled binaries from wherever they come from.

**Comment by JKAussieSkater** [comment]
About 4 months ago, during the university break, I did spend hours on the troubleshooting pages, trying to resolve this issue, but wasn't successful. From memory, at the time, there were several open threads around the interwebs which were years old — people were experiencing the same problems as I've shown in my screenshots, but to no resolution in those threads.

I'll look at the troubleshooting again, and give it another go, in case I was doing something wrong last time. But I won't be able to do all of this troubleshooting for probably another month, I'm about to start exams, so I don't really have time for this atm . . .

**Comment by xzyfer** [comment]
Please follow the steps on our documentation on how to report issues with installations. Screenshot are unhelpful.

https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx

**Comment by xzyfer** [comment]
There a handful of copy paste commands which we need at a bare minimum before we can help in any way.

**Comment by JKAussieSkater** [comment]
Sorry, I should specify in the first screenshot, the cursor in the square box continuously does this animation:
[\\] [|] [/] [-] [\\] [|] [/] [-] etc.

But yes, the screenshots are unhelpful, you can understand why my vague "doesn't work" couldn't really be further detailed.

Thanks for the link! As I mentioned, I'm a bit occupied with my studies at the moment, but I'll follow the troubleshooting guide probably in a month after my exams. Thanks again for your help so far!
