### ISSUE TITLE
Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.

### ISSUE THREAD

**Issue by trmck** [sass/node-sass#1371]
npm install node-sass is failing for Windows 10 (Windows_NT 10.0.10586)
node version v5.5.0-0
npm version v3.3.12

**Real Installation Debugging Info**
[npm-debug.log.txt](https://github.com/sass/node-sass/files/120024/npm-debug.txt)

**Troubleshooting Debugging Info**
[npm.err.txt](https://github.com/sass/node-sass/files/120047/npm.err.txt)
[npm-debug.log.txt](https://github.com/sass/node-sass/files/120048/npm-debug.log.txt)

**Comment by Toilal** [comment]
Same kind of issue with `mhart/alpine-node` docker image, which also use npm 3.

```
FROM mhart/alpine-node

RUN node --version
RUN npm --version

RUN npm install node-sass
```

Trying to build this image gives the following output.

```
Step 1 : FROM mhart/alpine-node
 ---> 7f1f1a584fdb
Step 2 : RUN node --version
 ---> Running in 8ae0fdaef03a
v5.5.0
 ---> 443416be1a85
Removing intermediate container 8ae0fdaef03a
Step 3 : RUN npm --version
 ---> Running in 1147e0a69492
3.5.3
 ---> 9091ddb34bb9
Removing intermediate container 1147e0a69492
Step 4 : RUN npm install node-sass
 ---> Running in 84d556b2bfe1
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> node-sass@3.4.2 install /node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /node_modules/node-sass/vendor/linux-x64-47/binding.node

> spawn-sync@1.0.15 postinstall /node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall /node_modules/node-sass
> node scripts/build.js

` /node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/bin/node /node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
```

I cut the end of log, but issue seems to be with "Problem with the binary", and then it tries to compile the node-sass binary from sources ...

Same issue with `mhart/alpine-node` docker image, which also use npm 3.

```
FROM mhart/alpine-node

RUN node --version
RUN npm --version

RUN npm install node-sass
```

Trying to build this image gives the following output.

```
Step 1 : FROM mhart/alpine-node
 ---> 7f1f1a584fdb
Step 2 : RUN node --version
 ---> Running in 8ae0fdaef03a
v5.5.0
 ---> 443416be1a85
Removing intermediate container 8ae0fdaef03a
Step 3 : RUN npm --version
 ---> Running in 1147e0a69492
3.5.3
 ---> 9091ddb34bb9
Removing intermediate container 1147e0a69492
Step 4 : RUN npm install node-sass
 ---> Running in 84d556b2bfe1
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> node-sass@3.4.2 install /node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /node_modules/node-sass/vendor/linux-x64-47/binding.node

> spawn-sync@1.0.15 postinstall /node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall /node_modules/node-sass
> node scripts/build.js

` /node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/bin/node /node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
```

I cut the end of log, but issue seems to be with "Problem with the binary", and then it tries to compile the node-sass binary from sources ...

**Comment by Laruxo** [comment]
I had similar issues and downgrading to node.js v4.2.6 helped.
So I am not sure anymore if node-sass support node.js 5.5?

**Comment by xzyfer** [comment]
@Toilal alpine linux is not supported. A quick grep of closed issues would have made this clear.

@Laruxo node-sass supports all major versions of node.js. You must've have been running an old version of node-sass.

**Comment by xzyfer** [comment]
@trmck the error code in your npm log is `3228369023`, which is `0xC06D007F` in hex.

This error is usually due to antivirus or malware scanner interfering with the npm install. This can happen with node-sass because we download a precompiled binary from GitHub so you don't have to have Visual Studio installed and configured. Disable or correctly configure your virus scanners and malware scanners.
