### ISSUE TITLE
`libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by AnvarPK** [sass/node-sass#1380]
`libsass` bindings not found. Try reinstalling `node-sass`?

**Comment by shennan** [comment]
Having same issue, OSX. Strangely, it doesn't fail in one module, but does with the other. Node version is 0.12.7.

**Comment by shennan** [comment]
Ignore me, my issue was human error. I was referencing a local module that had not been updated since a change of node versions. Hence calling `npm rebuild node-sass` was not rebuilding the package that it was supposed to be.

**Comment by saper** [comment]
Closing this. Please check other open and closed issues for this error message (there are plenty of them) and if you are sure it's a new thing, please follow the steps outlined in the TROUBLESHOOTING.md file.
