### ISSUE TITLE
Cannot install SmartOs

### ISSUE THREAD

**Issue by rickshawhobo** [sass/node-sass#1382]
Hi All
Getting this error when trying npm install node-sass

> node-sass@3.4.2 install /data/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/sunos-x64-47_binding.node": 

HTTP error 404 Not Found

Any help here would be appreciated. Running node v5.5.0 npm v3.3.12

**Comment by xzyfer** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx

**Comment by xzyfer** [comment]
SmartOS is currently not supported.
