### ISSUE TITLE
Watch compiles unrequested files

### ISSUE THREAD

**Issue by OlsonDev** [sass/node-sass#1388]
This is the command I run:
```
node-sass -w --indent-type tab --indent-width 1 --linefeed crlf --output-style expanded --precision 10 Client/sass/styles.scss -out-file wwwroot/css/styles.css
```
`styles.scss` looks like:
```scss
@import 'reset';
@import 'variables';
@import 'layout';
@import 'keywords';
@import 'pages/all'; // more @imports
```

I would expect `node-sass` to compile `styles.scss`, learn about all its dependencies (everything `@import`'d), and watch everything it came across. If anything changes, just compile `styles.scss`.

Instead, what happens:
- Change `layout.scss`
- `node-sass` compiles `layout.scss`
- Throws error because `layout.scss` expected `variables.scss` variables
- `node-sass` compiles `styles.scss`, writes it successfully to disk

Another example, different behavior:
- Change `reset.scss`
- `node-sass` compiles `reset.scss`
- `node-sass` writes something to `wwwroot\css\styles.css` -- educated guess: this is actually `reset.scss`'s output
- `node-sass` compiles `styles.scss`, writes it successfully to disk

Either way, I never intend for anything besides `styles.scss` to be the compilation entry point. Is this a bug or am I passing the wrong options to `node-sass`?

**EDIT:** I was passing `-r` before but I removed the `-r` and the same behavior exists.

**Comment by xzyfer** [comment]
Can you please provide the output of `ls` in your sass directory.

**Comment by xzyfer** [comment]
Sounds like you're not correctly using [partials](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials). Any file you don't want to be directly compiled should start with an `_`.
