### ISSUE TITLE
potential leak with concurrent renders

### ISSUE THREAD

**Issue by eoneill** [sass/node-sass#1391]
We run node-sass builds in a CI environment where builds get kicked off with each commit.

We've been seeing intermittent `Fatal error: Argument should be a string.` errors causing builds to fail. This is inconsistent and hard to reproduce, but we believe this happens when multiple node-sass renders happen concurrently.

I'll continue digging in our environment and hope to provide more useful information here shortly.

It's worth noting that each of these builds is using it's own node-sass instance, so this is more likely a libsass issue, but the error itself appears to originate in the SassError constructor in `src/sass_types/error.cpp`.

Running `node-sass@3.4.2`.

**Comment by xzyfer** [comment]
Interesting. LibSass is compiled into the node-sass binary so they're entirely independent.

It's also worth noting that `Argument should be a string` is an error thrown by the node-sass layer that talks to LibSass.

**Comment by xzyfer** [comment]
The error is related to custom functions. Specifically when a custom function returns an error, or returning a Sass number or string type with an invalid value.

Hope this helps track down your issue.

**Comment by eoneill** [comment]
Closing this. I've been able to narrow down the issue to an eyeglass custom function.
