### ISSUE TITLE
Trouble installing gulp-sass

### ISSUE THREAD

**Issue by hellerim** [sass/node-sass#1392]
On trying to install gulp-sass on a WinXP virtual box, I get repeatedly this result:

> npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Programme\\nodejs\\\\node.exe" "C:\\Programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-sass"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

>npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
npm ERR!     C:\usr\dvl\sss\npm-debug.log

npm-debug.log does not reveal (to me) what the problem really is; the exit status says "STATUS_ACCESS_VIOLATION" which can be caused by anything. I tried to install several versions of gulp-sass; beginning with 2.0.0, the installation fails consistently. Version 1.3.3 installs smoothly.

I was not able to find a description of this problem elsewhere in the Web.

`npm` install [...] sass

worked fine without any problems.

A file with combined environment, screenshot and contents of npm_debug.log is attached.

Help is appreciated!

Kind regards,

Goetz

[error.zip](https://github.com/sass/node-sass/files/138826/error.zip)

**Comment by xzyfer** [comment]
There is a known issue with node-sass@3.4.2 and Windows XP. This is fixed in the current beta.

```
npm install node-sass@beta
```

The beta is also available with grunt and gulp sass

```
npm install grunt-sass@beta
npm install gulp-sass@beta
```
