### ISSUE TITLE
SASS complier errors not being displayed

### ISSUE THREAD

**Issue by Gespinha** [sass/node-sass#1393]
Hi there,

I'm using `grunt` with `grunt-sass`, which uses `node-sass` and I have the following configuration into grunt:

```
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    sass: {
      options: {
        outputStyle: 'compressed'
      },
      dev: {
        files: {
          'style.css': 'style.sass'
        }
      }
    }
  });
```

**But the SASS compiles even with errors and doesn't log my errors in the console.** Why is this? How can I make it log SASS errors and not compile until these errors are fixed?

I'd really appreciate some help on this.

Thanks in advance :)

**Comment by saper** [comment]
This is not enough information to check. If you have some sass file where you should get an error, but you don't - please post the file with the instructions to reproduce the problem without using grunt. You might want to check our TROUBLESHOOTING.md file for more help.

If there is something wrong with how gulp reacts to the errors from node-sass then a bug report should be filed against the grunt plugin.

**Comment by Gespinha** [comment]
@saper Well, basically what's happening is this: I have a `.sass` file with the following SASS:

```
.one
    color: #000
    padding: 10px

```
and it compiles nicely as this:

`.one{color:#000;padding:10px}`

But if I purposely change it to a wrong SASS syntax, which should result in error, like this:

```
.one
    color: #000
    padd
```

It still compiles, without giving me a single error log, but it compiles to this:

`.one{color:#000}`

I am using the latest version of `grunt` and `grunt-sass` and my configurations are the ones above (in the question of this post).

So, what do you think, is this a bug? What am I doing wrong?

**Comment by xzyfer** [comment]
@Gespinha please test your code with Ruby Sass before opening an issue here. If you had done so you would have seen that this does not produce an error. Node Sass simply aims simply to copy what Ruby Sass does.

**Comment by Gespinha** [comment]
@xzyfer I recreated the same example on `grunt-contrib-sass` and the same happens. I've also used Ruby Sass and it reproduces error logs, but I can't manage to get those errors on grunt.

Can you please let me know if the errors should show up? When do they show up?
