### ISSUE TITLE
Segmentation fault error when a semi colon is missing and is followed by two nested selectors

### ISSUE THREAD

**Issue by benhughes** [sass/node-sass#1394]
Found a pretty rare bug, that took me a few hours to track down to node-sass. Steps to repro:

Create a file called `test.scss` that looks like this:
```
.top-rule {
  display: block

  &--sub-rule {
    border: 0;
    &--another-sub-rule {
      display: none;
    }
  }
}
```
It's a declaration that's missing a semi colon followed by two nested rules. In my tests it doesn't seem to matter what the rules are.

Then run `node-sass test.scss test.css` and you should get an error such as: `28485 segmentation fault  node-sass test.scss test.css` 

if you run `sass test.scss test.css` you get the correct expected error.

```
Error: Illegal nesting: Only properties may be nested beneath properties.
        on line 5 of test.scss
  Use --trace for backtrace.
```

version info
```
node-sass --v
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
```

**Comment by xzyfer** [comment]
I believe this is fixed in the current beta. Can you confirm?

npm install node-sass@beta

Betas for gulp and grunt sass are also available.

**Comment by benhughes** [comment]
Yep can confirm that it is fixed in master. Getting the expected error now:

```
{
  "formatted": "Error: Illegal nesting: Only properties may be nested beneath properties.\n        on line 4 of test.scss\n>>   &--sub-rule {\n   -------------^\n",
  "message": "Illegal nesting: Only properties may be nested beneath properties.",
  "column": 14,
  "line": 4,
  "file": "/Users/benjaminhughes/code-repo/temp/sass-error/test.scss",
  "status": 1
}
```

Thanks :+1:
