### ISSUE TITLE
Mediaquery and maven variable

### ISSUE THREAD

**Issue by yvanavermaet** [sass/node-sass#1395]
Hi

We've encountered a small issue with our current set-up.

- We use Akamai to cache our images
- Some HTML-elements have a background-image
- If we update these images (in our /img-folder), we also need to update a fingerprint (parameter 'c' in the examples below), so that these new images are picked up by Akamai (otherwise it'll return the old cached version)
- The fingerprint is automatically replaced by Maven, our build tool

**In the code below this works great**
```
body {
	background: transparent url('../img/image-small.jpg?c=${buildNumber}') 50% top no-repeat;
	background-size: cover;
}
```
**Output**
```
body {
	background: transparent url("../img/image-small.jpg?c=${buildNumber}") 50% top no-repeat;
	background-size: cover;
}
```

**If we now add some media queries, this doesn't work**
```
body {
	background: transparent url('../img/image-small.jpg?c=${buildNumber}') 50% top no-repeat;
	background-size: cover;

	@media only screen and (min-width: 600px) {
		background-image: url('../img/image-medium.jpg?c=${buildNumber}');
		background-position: left top;
	}

	@media only screen and (min-width: 1200px) {
		background-image: url('../img/image-large.jpg?c=${buildNumber}');
	}
}
```

**Output**
```
body {
	background: transparent url("../img/image-small.jpg?c=${buildNumber}") 50% top no-repeat;
	background-size: cover;
}
	body {
		background-image: url("../img/image-medium.jpg?c=${buildNumber}");
		background-position: left top;
	}
	body {
		background-image: url("../img/image-large.jpg?c=${buildNumber}");
	}
}
```
**Expected output**
```
body {
	background: transparent url("../img/image-small.jpg?c=${buildNumber}") 50% top no-repeat;
	background-size: cover;
}

@media only screen and (min-width: 600px) {
	body {
		background-image: url("../img/image-medium.jpg?c=${buildNumber}");
		background-position: left top;
	}
}

@media only screen and (min-width: 1200px) {
	body {
		background-image: url("../img/image-large.jpg?c=${buildNumber}");
	}
}
```

Notice the missing 2 media queries
It's not possible to replace ${buildNumber} with another string/value.

Thanks in advance.

Kind regards,
Yannick

**Comment by mgreter** [comment]
Please try first with ruby sass and if you can provide a single working example, with sample inputand output that you can confirm work with ruby sass. I get `Invalid CSS after "...% top no-repeat": expected expression (e.g. 1px, bold), was ";"` with your "If we now add some media queries, this doesn't work" sample on [sassmeister] [1]. And also always include the libsass version you are using, thanks!

[1]: www.sassmeister.com

**Comment by yvanavermaet** [comment]
@mgreter Apologies, had a small error in the Input. I've updated my post and If you copy the HTML now to sassmeister, it'll work.

I'll try this use case with Ruby Sass asap and will provide feedback here.

I'm using gulp-sass (v2.1.1) which uses node-sass (v3.4.2) which uses LibSass version 3.3.2

**Comment by mgreter** [comment]
[libsass 3.3.3 compilation results] [1]

[1]: http://libsass.ocbnet.ch/srcmap/#Ym9keSB7CiAgICBiYWNrZ3JvdW5kOiB0cmFuc3BhcmVudCB1cmwoJy4uL2ltZy9pbWFnZS1zbWFsbC5qcGc/Yz0ke2J1aWxkTnVtYmVyfScpIDUwJSB0b3Agbm8tcmVwZWF0OwogICAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjsKCiAgICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtaW4td2lkdGg6IDYwMHB4KSB7CiAgICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKCcuLi9pbWcvaW1hZ2UtbWVkaXVtLmpwZz9jPSR7YnVpbGROdW1iZXJ9Jyk7CiAgICAgICAgYmFja2dyb3VuZC1wb3NpdGlvbjogbGVmdCB0b3A7CiAgICB9CgogICAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWluLXdpZHRoOiAxMjAwcHgpIHsKICAgICAgICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoJy4uL2ltZy9pbWFnZS1sYXJnZS5qcGc/Yz0ke2J1aWxkTnVtYmVyfScpOwogICAgfQp9

**Comment by yvanavermaet** [comment]
@mgreter After seeing your link, I decided to look into it a bit further and noticed that it's not related to node-sass, but to gulp-bless.. .My apologies, I'll close this issue and raise another one in their repo.

Thanks for your time and sorry for the inconvenience.

**Comment by mgreter** [comment]
@yvanavermaet thanks for looking into it yourself, glad you could find the culprit!
