### ISSUE TITLE
indentedSyntax allowing CSS rules with ";" and errors to be compiled

### ISSUE THREAD

**Issue by Gespinha** [sass/node-sass#1402]
Hi there,

I've been testing `node-sass` with `grunt` and set the `indentedSyntax` to `true`, which should make the compilation engine compile my CSS on .sass files respecting the SASS indented syntax.

Along with this syntax, in Ruby SASS, something like this:

```
.object
  max-width: 500px
  font-weight: bold;
  co
```

Should result in one error and one warning. The error would be displayed regarding the ";" character, which is not allowed in SASS indented syntax and the warning regarding the "co", which is missing a value.

Because of the error, the compilation should be aborted, but both error and warning should be displayed.

In `node-sass`, not only the ";" is not being displayed as an error, but warnings are not being shown as well. Is this a known bug? Because it makes developing with SASS on node just useless, as large SASS applications can become rather difficult to debug without these warnings and errors working correctly.

I know `grunt-contrib-sass` does this and works just like Ruby SASS, so I would expect `grunt-sass` to work the same way, but faster.

Thanks

**Comment by xzyfer** [comment]
Thanks for the report @Gespinha. These are bugs in a library used by LibSass. I've opened two issues with that library.

- https://github.com/mgreter/sass2scss/issues/27
- https://github.com/mgreter/sass2scss/issues/28
