### ISSUE TITLE
What about a .sassrc-like file?

### ISSUE THREAD

**Issue by floriangosse** [sass/node-sass#1409]
The idea is to add a file called `.sassrc` or similar to your project root where the configurations are defined.

YAML:
```yaml
---
includePaths:
  - node_modules/
  - bower_components/
```

or in JSON styntax:
```
{
  "includePaths": [
    "node_modules/",
    "bower_components/"
  ]
}
```

If the config file exists you can simply run `node-sass src/style.scss dest/style.css` and the options will be automatically applied.

This is also useful for editors which can automatically resolve imported files for jumping between them.

**Comment by xzyfer** [comment]
This is related to https://github.com/sass/node-sass/issues/1409

**Comment by saper** [comment]
This is even the same @xzyfer :):)

**Comment by xzyfer** [comment]
Closing this in order to consolidate discussion in #1409.

**Comment by floriangosse** [comment]
@xzyfer please reference the correct issue.

**Comment by xzyfer** [comment]
Apologies , I didn't grok @saper's humor. I meant #917. The specific focus is different but the solution will likely be the same.
