### ISSUE TITLE
error MSB4019: The imported project "C:\---\Microsoft.Cpp..." was not found

### ISSUE THREAD

**Issue by kyathil** [sass/node-sass#1410]
Greetings,
I've been trying to install node-sass in my project. However, I receive error MSB4019 whenever I try and have tried every trick i found on the Internet to solve the problem, to no avail. I've tried setting the VCTargetPath etc.

I got the following tools:
node 4.4
bower 1.7.7
npm 3.7.1
phantomjs 2.0
ember-cli 1.13.1

Is anyone here able to help me solve this? It seems like I cannot build my Ember project without node-sass

**Comment by saper** [comment]
Can you publish a full log of your compiler output? Are you using Visual Studio command prompt?

**Comment by kyathil** [comment]
I actually did a full system swipe and then suddenly everything just worked...

**Comment by saper** [comment]
Yes, that looked like a Microsoft Visual Studio installation issue to me. Good it got sorted out.
