### ISSUE TITLE
Failed at the node-sass@3.4.2 install script 'node scripts/install.js'

### ISSUE THREAD

**Issue by jbudge3** [sass/node-sass#1414]
I'm brand new to all of this, and was asked to install Harp for a front-end web dev class, and I keep running into this error. Running node v5.8.0, nam v3.7.3 on Mac OS X 10.11.3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "harp"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jacobbudge/npm-debug.log
npm ERR! code 1

**Comment by decebe** [comment]
Hi
I'm running into the same problem when I try to install ionic (Mac OS X 10.9.5, node 4.4.0, npm 2.14.20):

/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic

> node-sass@3.4.2 install /usr/local/lib/node_modules/ionic/node_modules/node-sass
> node scripts/install.js

sh: node: command not found
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm/bin/npm-debug.log


Here's the npm-debug.log:
[npm-debug.log.zip](https://github.com/sass/node-sass/files/178807/npm-debug.log.zip)

**Comment by xzyfer** [comment]
@jbudge3 @decebe please read the [CONTRIBUTING.md](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md) before opening a new issue. Closing this since these two reports are unrelated to each other. If you're still experiencing installation issues open a new issue.

**Comment by dattatrey93** [comment]
Hi,i'm running with same problem ,here is the whole issue


npm ERR! Linux 3.16.0-69-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "rebuild" "node-sass"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/narottam/Documents/docs/npm-debug.log

**Comment by xzyfer** [comment]
@dattatrey93 this is not the whole issue. As I've said above, please read the [CONTRIBUTING.md](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md) before opening an issue so you can provide the required information for us to help you.

**Comment by vicmonmena** [comment]
Hi!

Same problem here! Where this issue is continued?

Thx!

**Comment by diogomachado** [comment]
Try install without `-g`:

`npm install ionic`

**Comment by kaleksandrov** [comment]
I'm facing the same problem:

[ERROR] npm ERR! file sh
[ERROR] npm ERR! path sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn sh
[ERROR] 
[ERROR] npm ERR! node-sass@4.3.0 install: `node scripts/install.js`
[ERROR] npm ERR! spawn sh ENOENT

The interesting part is that my command passes on my windows dev machine but fails with the above error on our dedicated for builds linux machine.
