### ISSUE TITLE
Output to file not directory > file

### ISSUE THREAD

**Issue by NathanKleekamp** [sass/node-sass#1415]
When running this `node-sass --output-style compressed style.scss style.css` via npm scripts, I receive the following error: `Error: EISDIR: illegal operation on a directory`. 

If I run with the `-o` flag, like so: `node-sass --output-style compressed style.scss -o style.css`, it generates the following: 

```
style.scss
style.css
└── style.css
```

Is there anyway to just generate the `style.css` file within the same directory as the `style.scss` file? Or am I going to have to move things around in a post hook?

**Comment by xzyfer** [comment]
Node sass outputs the compiled CSS to stdout. If you want to write to a
file you'll need to pipe the out.

```
node-sass input.scss > input.css
```

**Comment by NathanKleekamp** [comment]
Yup, I saw that node-sass outputs to stdout in the documentation, but when I try:

```
"scripts": {
    "scss": "node-sass --output-style compressed style.scss > style.css"
}
```

or even a more simplified version:

```
"scripts": {
    "scss": "node-sass style.scss > style.css"
}
```
It errors out, and I get:

```
> node-sass style.scss > style.css
sh: style.css: Is a directory
```
I'm using node-sass 3.4.2 and node 4.2.1. Thanks for your help!

**Comment by NathanKleekamp** [comment]
Never mind. I had a style.css directory hanging around the directory from when I was experimenting with the`-o` flag. Sorry for the confusion. I just noticed it after un-hiding untracked files in Atom -Nathan

**Comment by xzyfer** [comment]
That's because you previously created a directory call `style.css` with the
previous command. Remove that directory and you're set.
