### ISSUE TITLE
Failed install node-sass

### ISSUE THREAD

**Issue by LeG3nDz** [sass/node-sass#1425]
Hi community,

I would like install node-sass (with sass-brunch) but i've error after my npm install :

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\str\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v4.4.1
    npm ERR! npm  v3.3.10
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

Do you have any idea how i can resolv my problem ?

node -v : 4.4.1
npm -v : 3.3.10

Thank you !

**Comment by xzyfer** [comment]
Please read the contributing.md before opening an issue

**Comment by coocier** [comment]
same problem...

**Comment by Robert-Janagap** [comment]
same here :(
