### ISSUE TITLE
Webpack fails due to node-sass

### ISSUE THREAD

**Issue by simPod** [sass/node-sass#1426]
My node version is v5.7.1
My npm version is 3.6.0
My node-sass version is 3.4.2

When I run `webpack -d`, it works, when I run `webpack -p` it fails:

```
> project-web@1.0.0 build-prod /var/www/project/releases/45
> webpack -p

Killed

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-prod"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! project-web@1.0.0 build-prod: `webpack -p`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the project-web@1.0.0 build-prod script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the project-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs project-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls project-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/project/releases/45/npm-debug.log
```

I have no idea why. 

When I try to remove `node_modules` dir, `npm cache clear` and `npm install`, everything is ok. But after `webpack -p` it says:
```
 ERROR in ./src/styles/front/style.scss
    Module build failed: Error: The `libsass` binding was not found in /var/www/project/releases/45/node_modules/node-sass/vendor/linux-x64-47/binding.node
    This usually happens because your node version has changed.
    Run `npm rebuild node-sass` to build the binding for your current node version.
```
So I run `npm rebuild node-sass` and after that the `npm ERR!` shows again as shown in the first snippet here.

Does anyone have any idea what might be wrong? I tried to do the same with different server, same ubuntu dist, same node and npm versions and it works like a charm there. Thanks

**Comment by saper** [comment]
Can you check the operating system logs to see why the process got killed? Maybe there is some infinite loop or endless recursion and it simply ran out of memory?

**Comment by simPod** [comment]
Wow, you're right. The server it's working on has 2GB memory, this one has only 1GB. Is there a way I can optimize node-sass building process so it doesn't need such high memory?

**Comment by saper** [comment]
Node-sass does not normally require test much memory, you might want to optimize your sass maybe.

**Comment by saper** [comment]
If it happens during building, we need more information about your system, please check CONTRIBUTING.md and attach full logs.

**Comment by xzyfer** [comment]
I'd say node Sass isn't the issue here. Something in your webpack server is
leaking memory. Try update all your dependencies and see if it's still
happening.
