### ISSUE TITLE
Failed to install node-sass module in windows-7

### ISSUE THREAD

**Issue by debroop7** [sass/node-sass#1429]
node v5.9.1
npm  v3.7.3

Please find attached the log files for the same.

Thanks,
Debroop
[npm_err.pdf](https://github.com/sass/node-sass/files/189660/npm_err.pdf)
[npm_log.pdf](https://github.com/sass/node-sass/files/189659/npm_log.pdf)
[npm-debug.pdf](https://github.com/sass/node-sass/files/189661/npm-debug.pdf)

Few more details:
npm -v 3.7.3
node -v v5.9.1
node -p proc
	ess.versions
	{ http_parser: '2.6.2',
	  node: '5.9.1',
	  v8: '4.6.85.31',
	  uv: '1.8.0',
	  zlib: '1.2.8',
	  ares: '1.10.1-DEV',
	  icu: '56.1',
	  modules: '47',
	  openssl: '1.0.2g' }

node -p process.platform win32

node -p process.arch x64

**Comment by debroop7** [comment]
Few more detals:
npm -v 3.7.3
node -v v5.9.1
node -p proc
	ess.versions
	{ http_parser: '2.6.2',
	  node: '5.9.1',
	  v8: '4.6.85.31',
	  uv: '1.8.0',
	  zlib: '1.2.8',
	  ares: '1.10.1-DEV',
	  icu: '56.1',
	  modules: '47',
	  openssl: '1.0.2g' }

node -p process.platform win32

node -p process.arch x64

Thanks,
Debroop

**Comment by xzyfer** [comment]
As the error message says this is a network issue with your computer.

```
Cannot download "
https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-47_binding.node":
tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL
routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
Hint: If github.com is not accessible in your location
 try setting a proxy via HTTP_PROXY, e.g.
 export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
 npm config set proxy http://example.com:8080
```

**Comment by hanxu317317** [comment]
how do u resolve this??
