### ISSUE TITLE
 [ERROR] load plugin [fis-parser-node-sass] config error

### ISSUE THREAD

**Issue by yuzhanchao2015** [sass/node-sass#1431]
D:\worknew>fis3 release

 [INFO] Currently running fis3 (C:\Users\yuzhanchao\AppData\Roaming\npm\node_mod
ules\fis3\)

 Ω .
 [ERROR] load plugin [fis-parser-node-sass] config error : The `libsass` binding
 was not found in D:\worknew\node_modules\node-sass\vendor\win32-x64-46\binding.
node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version..

**Comment by yuzhanchao2015** [comment]
why happen

**Comment by xzyfer** [comment]
The error message explains why and how to fix it.
>This usually happens because your node version has changed.
>Run npm rebuild node-sass to build the binding for your current node version
