### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`

### ISSUE THREAD

**Issue by maketroli** [sass/node-sass#1432]
I've been struggling with this for the last 2 hours and I don't know what is going on, I already went into every post about this on Google and I am getting the same problem every time I try something new

    node version: 4.2.6
    npm version: 2.5.1 

when I do `grunt serve`, this is what I get

    CRSJOPGP0223:promo-multiproduct-oaa2 berretan$ grunt serve
    Loading "sass.js" tasks...ERROR
    >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    
    Running "serve" task
    
    Running "clean:server" (clean) task
    >> 1 path cleaned.
    
    Running "concurrent:server" (concurrent) task
        
        Loading "sass.js" tasks...ERROR
        >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
        
        Running "copy:css" (copy) task
        
        
        Done, without errors.
        
        
        Execution Time (2016-03-30 19:05:07 UTC)
        loading tasks  2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
        Total 2.1s
            
        Loading "sass.js" tasks...ERROR
        >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
        
        Running "jshint:all" (jshint) task
        >> 9 files lint free.
        
        Done, without errors.
        
        
        Execution Time (2016-03-30 19:05:07 UTC)
        loading tasks     2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 87%
        jshint:all     288ms  ▇▇▇▇▇▇ 12%
        Total 2.3s
            Warning: OptionParser::InvalidOption: invalid option: --source-map
          Use --trace for backtrace. Use --force to continue.
            
            Aborted due to warnings.
        
    
    Execution Time (2016-03-30 19:05:05 UTC)
    loading tasks      1.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 34%
    concurrent:server  2.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 66%
    Total 4.4s

here my packege.json file

    {
      "name": "oaa-recipe-c",
      "app": "app",
      "dist": "dist",
      "version": "0.0.0",
      "dependencies": {
        "bower": "~1.3.9",
        "metrojs": "^0.9.77"
      },
      "devDependencies": {
        "assemble": "~0.4.42",
        "grunt": "~0.4.5",
        "grunt-autoprefixer": "~2.2.0",
        "grunt-bower-install": "~1.4.0",
        "grunt-concurrent": "~1.0.0",
        "grunt-contrib-clean": "~0.6.0",
        "grunt-contrib-compress": "~0.8.0",
        "grunt-contrib-concat": "~0.5.0",
        "grunt-contrib-connect": "~0.9.0",
        "grunt-contrib-copy": "~0.8.0",
        "grunt-contrib-cssmin": "~0.12.0",
        "grunt-contrib-htmlmin": "~0.4.0",
        "grunt-contrib-imagemin": "~0.7.1",
        "grunt-contrib-jshint": "~0.11.0",
        "grunt-contrib-sass": "^1.0.0",
        "grunt-contrib-uglify": "~0.8.0",
        "grunt-contrib-watch": "~0.6.1",
        "grunt-exec": "~0.4.5",
        "grunt-notify": "^0.4.0",
        "grunt-rev": "~0.1.0",
        "grunt-sass": "~0.18.1",
        "grunt-stripmq": "~0.0.6",
        "grunt-svgmin": "~2.0.1",
        "grunt-usemin": "~3.0.0",
        "grunt-wiredep": "^1.7.0",
        "load-grunt-tasks": "~3.1.0",
        "node-sass": "*",
        "time-grunt": "~1.1.0"
      },
      "engines": {
        "node": ">=0.10.0"
      }
    }

I am getting crazy, how is possible that there is no standard way to bypass this or a message providing the solution? even if I do `npm rebuild node-sass` or `npm install node-sass` as suggested in the terminal error, I get the same at the end.

what do you think it is?

**Comment by danimalweb** [comment]
Similar issue here.

```
├── UNMET PEER DEPENDENCY eslint@<2.3.0
└─┬ gulp-sass@2.2.0
  └── node-sass@3.4.2

npm ERR! peer dep missing: eslint@<2.3.0, required by babel-eslint@5.0.2
```

**Comment by brandonweiss** [comment]
I'm hitting this as well. It tells me to rebuild but that doesn't seem to do anything.

**Comment by brandonweiss** [comment]
This is crazy hacky and might not work for you, but I had a coworker send me their `node_modules/node-sass/vendor/`. I dropped it in and it worked.

[vendor.zip](https://github.com/sass/node-sass/files/198292/vendor.zip)

**Comment by anhkhoi** [comment]
The same error for me. 
```
npm version: 2.11.3
node version: 0.12.7
```
My workaround is only remove node-sass folder and re-install package. It's inconvenient. 
Which other ways to solve this issue?

**Comment by CanKattw** [comment]
Please check the output of 
`npm config ls.
`
Probably you have 
`ignore-scripts = true
`

remove this line in 
~/.npmrc

**Comment by anhkhoi** [comment]
@CanKattw 
I checked. But my config is only have `ignore-scripts = false`. Need to remove it also.

**Comment by danpantry** [comment]
+1, also having this issue. In my experience it was due to the install script downloading the 32 bit version of `binding.node`, but attempting to locate the 64 bit version. installing the 64 bit version manually fixed the issue.

**Comment by xzyfer** [comment]
To everyone here, this error will only ever happen if you changed your environment between installs. 99% of the time this message is reported one of the follow has happened:

- node sass has been installed, then you version of node changed, this happens if you
  - manually upgraded node, in which case you need to remove and reinstall your node_modules
  - copied you node_modules directory to a different machine i.e. committed node_modules in git
  - npm install was run locally but work in a docker containers or vice verse
  - have two versions on node installed
    - this happens a lot on osx if you installed node both from the website and later via brew or vice verse
    - this usually means npm run install scripts with a different version of node than you are using

The new beta will clearly tell you which binding you have installed so you can more easily determine where your installation went wrong.

We store the binding at install time in the`node-sass/vendor` in a directory named after the environment which `npm install` was run. To see your environment you can run 

```
node -p "[process.platform, '-', process.arch, '-', process.versions.modules].join('')"
```

This string will tell you which OS

'darwin' = 'OS X'
'freebsd' = 'FreeBSD'
'linux' = 'Linux'
'win32' = 'Windows'
```

Architecture (32/64bit)

```
'ia32' = '32-bit'
'x86' = '32-bit'
'x64' = '64-bit'
```

Node version

```
11 = 'Node 0.10.x'
14 = 'Node 0.12.x'
42 =  'io.js 1.x'
43 = 'io.js 1.1.x'
44 = 'io.js 2.x'
45 = 'io.js 3.x'
46 = 'Node.js 4.x'
47 = 'Node.js 5.x'
```

***

You compare this string against the directories in your `node-sass/vendor` to figure our what when wrong with your `npm install`

**Comment by brandonweiss** [comment]
Ah, whoops, for me the issue seems to be `ignore-scripts` being `true`. I set that for security reasons—didn't realize it would break installing certain packages.

**Comment by Drabc** [comment]
I had this same issue. deleting the ``` node_modules/node-sass ``` folder and running ``` npm install ```  fix this particular error. However, now I'm getting ``` ERROR in Module did not self-register ```.

**Comment by Drabc** [comment]
Also, I notice that when I run ```node -p "[process.platform, '-', process.arch, '-', process.versions.modules].join('')"``` I get ```linux-x64-47```, but the binary is been installed in ```node_modules/node-sass/vendor/linux-x64-11```

**Comment by xzyfer** [comment]
@drabc this means that npm install was run with node 0.10 instead of your current node 5. You likely have two node versions installed. The old one is still being used by npm when.

**Comment by xzyfer** [comment]
This is a local environment issue. I've provided all the information necessary to correct your environment. This issue has gotten off track and no longer serves a constructive purpose.

**Comment by maketroli** [comment]
Just got the solution for this, you should have the Node version according to the node-sass version, the way I did it:

```
sudo npm install -g n
sudo n 0.12.7
sudo npm install node-sass@2
sudo npm -g install node-gyp@3
sudo npm rebuild node-sass 
```

now, you should be specific on your error message, it doesn't say anything.

**Comment by Drabc** [comment]
As xzyfer suggested, I had two version of NPM and Node. One for root and one for a normal user, for some reason. Both users now how the same versions and that solved my issue.

**Comment by harit-dhiman** [comment]
Yes, Solution given above worked for me.

sudo npm install -g n
sudo n 0.12.7
sudo npm install node-sass@2
sudo npm -g install node-gyp@3
sudo npm rebuild node-sass

**Comment by BertCotton** [comment]
For what it's worth, I'm getting this error in Visual Studio because I did npm install from my bash shell.  Visual Studio is only 32 bit, but since it wasn't the tool that ran 'npm install' it must have grabbed the "wrong" version.
For me, deleting the node_modules and having Visual Studio reinstall it, fixes this problem.

It doesn't fix the problem of me using Visual Studio :/

**Comment by danpantry** [comment]
@BertCotton  Use VSCode. It's a far better experience if you *have* to use a Microsoft product than Visual Studio for JavaScript.

**Comment by Serjster** [comment]
> Just got the solution for this, you should have the Node version according to the node-sass version, the > way I did it:
> 
> `sudo npm install -g n`
> `sudo n 0.12.7`
> `sudo npm install node-sass@2`
> `sudo npm -g install node-gyp@3`
> `sudo npm rebuild node-sass `
> now, you should be specific on your error message, it doesn't say anything.

This seems to be windows specific? `n` doesn't want to install on Windows.

**Comment by maketroli** [comment]
Hey, @Serjster, sorry I just saw this. I applied that process on Mac, El Capitan to be specific. 

What errors are you getting on Windows?

**Comment by maketroli** [comment]
Just realised that:

>(Unfortunately n is not supported on Windows yet. If you're able to make it work, send in a pull request!)

**Comment by vicdidia** [comment]
@maketroli 's solution works for both Ubuntu and Mac. This problem was persisting across platforms for me but this worked great. 
The only thing I'd recommend is if maketroli's solution didn't work straight out then make sure to do a fresh install of the repository. Then also do a fresh install of the node modules. This helped me on Mac OSX.

**Comment by juliangav** [comment]
I upgraded my node-sass to the latest version and everything worked (package.json).

**Comment by michelle-marrion** [comment]
Thanks you so much
