### ISSUE TITLE
Binary test fails in master after the commit 22c560c70a

### ISSUE THREAD

**Issue by chivorotkiv** [sass/node-sass#1434]
Hi. 
Something [was changed](https://monosnap.com/file/CtV5ucpfvNicRdax84ZY4qs5hVKMMu.png) in `build.js` in the commit: [22c560c70a](https://github.com/sass/node-sass/commit/22c560c70a9c637d93a29e47a6d558b04e1ccefd).

Tested on MacOS:
* Before: [binary is fine](https://monosnap.com/file/9sSNfnsxyLJVkmJeFQGFnTk4U04BcY.png)
* After: [problem with the binary](https://monosnap.com/file/8Ob2CJrhpBDtVcPReEQ297m9zAyhhm.png), compile it with c++.

Also I have tested it on Windows 7:
* Before: binary exists, binary is fine, no c++ compilation
* After: binary exists, problem with the binary, c++ compilation passes successfully.

But if the binaries weren't changed and were valid before, they should also be valid after the change of `build.js`

/cc @xzyfer

**Comment by xzyfer** [comment]
I actually noticed this last night. Thanks for digging in and finding the
offending commit. I'll take a look shortly.
