### ISSUE TITLE
Bus Error 10

### ISSUE THREAD

**Issue by jgacuca567** [sass/node-sass#1436]
@xzyfer 
I had reviewed installing, and tried following the example from [David Walsh](https://davidwalsh.name/upgrade-nodejs) link but, I keep getting the `buserror10` when I run `grunt`. 

Current Version
`node v5.10.0`

I have reviewed, my sass for jshint errors but no errors are showing.

**Comment by xzyfer** [comment]
If you don't provide us the information to produce this error ourselves there is nothing we can do. In future please read the [CONTRIBUTING.md](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md) before opening an issue.

**Comment by xzyfer** [comment]
We'll reopen this is more information is supplied.

**Comment by jgacuca567** [comment]
@xzyfer I have added more information. Please review and let me know if you are able to encounter the error.

**Comment by xzyfer** [comment]
What version of node-sass are you using?

**Comment by jgacuca567** [comment]
@xzyfer `node-sass: 3.4.2`

**Comment by xzyfer** [comment]
Can you please try the beta?

npm install node-sass@beta

**Comment by jgacuca567** [comment]
@xzyfer, with `node-sass@beta`, I still get the `bus error:10`
