### ISSUE TITLE
ERROR INSTALLING with npm install -g node-sass

### ISSUE THREAD

**Issue by analtherapist** [sass/node-sass#1438]
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Documents and Settings\
\Bob\\Application Data\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
"ionic"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Documents and Settings\Bob\npm-debug.log
npm ERR! code 1

**Comment by saper** [comment]
This is #1283 please upgrade to node-sass v3.5.0-beta.1 to have this fixed.
