### ISSUE TITLE
Document how to mirror node-sass-binaries repo

### ISSUE THREAD

**Issue by mattdsteele** [sass/node-sass#1443]
I'm working in a proxied environment where access to `raw.githubusercontent.com` is restricted, similar to #775. I'd like to mirror the node-sass-binaries repo locally and use the `sass_binary_site` NPM configuration but I'm not sure how to create such a mirror.

The site specification looks to be documented here: https://github.com/sass/node-sass/blob/9c6933f4eb5c9572e1cdc577d500469c14411908/lib/extensions.js#L121-L147

But I can't seem to use my normal mirroring tool - wget returns HTTP 400s when hitting raw.githubusercontent.com:

```
wget -m -k -K -E https://raw.githubusercontent.com/sass/node-sass-binaries
```

What's the best way to mirror the repo such that I can have an on-premises copy? Should I clone the git repo and use another tool to host it over HTTP?

/cc @saper @chriseppstein - based on other tickets it looks like you might have been successful at this already?

**Comment by xzyfer** [comment]
Check out the sass/node-sass-binaries github repo.

**Comment by mattdsteele** [comment]
@xzyfer I'm not sure where I should be looking - [this issue](https://github.com/sass/node-sass-binaries/issues/113) appears to recommend not mirroring the repo directly. Is there another approach I should take? Or is hosting on-premises something I just need to do manually?

**Comment by xzyfer** [comment]
I'm not I understand your problem. If you need the binaries locally you can
download then from the github release page for every release. If you're
getting non 200 responses the issue is with your mirroring implementation.

**Comment by mattdsteele** [comment]
Correct, the issue is with my mirroring implementation. I was hoping someone had documented a recipe I could follow.

I'll close this out; if I get something up & running I'll post it back here. Thanks!

**Comment by saper** [comment]
I think there is one thing which is not nice that we have a long-big-filename modules in the node-sass-binaries repository, but we use a vendor/platform/directory/binding.name format for the modules themselves. You can't just checkout node-sass-binaries into your vendor/ directory.
