### ISSUE TITLE
additional empty line with :expanded output style

### ISSUE THREAD

**Issue by philipdangpro** [sass/node-sass#1444]
When the output style is "expanded, the generated file should be (according to [http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style]) : 
```
#main {
  color: #fff;
  background-color: #000;
}
#main p {
  width: 10em;
}

.huge {
  font-size: 10em;
  font-weight: bold;
  text-decoration: underline;
}
```

Instead, it generates a file with an additional empty line between the 2 first selectors blocks:
```
#main {
  color: #fff;
  background-color: #000;
}

#main p {
  width: 10em;
}

.huge {
  font-size: 10em;
  font-weight: bold;
  text-decoration: underline;
}
```

**Comment by xzyfer** [comment]
This is a know issue with Ruby Sass. It's inconsistent with how it adds
newlines in all output formats.

**Comment by xzyfer** [comment]
We don't consider this a bug since it doesn't affect the output semantics.
