### ISSUE TITLE
Node-gyp g++ and libsass error

### ISSUE THREAD

**Issue by fivedoor** [sass/node-sass#1445]
I've been following the guide to install Zurb foundation but running into a consistent issue. 
`$ npm install foundation-cli --global `
is successful but :
`foundation fivedoor$ foundation new `
brings up:

```
++: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fivedoor/Documents/development/zurb/foundation/test130416-2/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/usr/local/bin/node" "/Users/fivedoor/Documents/development/zurb/foundation/test130416-2/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/fivedoor/Documents/development/zurb/foundation/test130416-2/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
```

The node-gyp issue forum pointed me to libsass who in turn pointed me to node-sass . I have seen similar errors in other github posts. To be honest being primarily a front end guy and new to node, I'm sure it's possible I may have been inept in implementing some of the various solutions suggested.

I have tried quite a few things without any joy:
	•	complete uninstall/ reinstall latest node & npm;
	•	clean npm cache; install with nvm, brew;
	•	updating git to latest version that supports snow leopard;
	•	npm --optional install ;
	•	installed macports and then updated GCC and G++;
	•	deleting .node-gyp folder and reinstall;
	•	uninstall and reinstall foundation-cli.

The last thing I tried was to switch to clang from gcc but I still hit pretty much the same errors. 
Except this time instead of the line: 
`g++: error: unrecognized command line option '-stdlib=libc++'`

I get 
`make: clang++: No such file or directory`

which perhaps suggest the commands I used to switch to clang were not sufficient: 
```
fivedoors-MacBook-Pro:~ fivedoor$ export CC=clang
fivedoors-MacBook-Pro:~ fivedoor$ export CXX=clang++
```

Been keeping an expanding troubleshooting log as I go. The most recent stuff at https://github.com/fivedoor/foundation-records/blob/master/my_installation_log_post_reinstall100416

Failing a silver bullet solution, could someone advise if upgrading to a later OS is likely to help or not? ( I know snow leopard is old but I've clung on to it for stability.) I did get some warnings from brew that " We (and Apple) do not provide support for OS 10.6"

	•	MACOS X Version 10.6.8
	•	npm 3.8.6
	•	node v4.4.2
	•	Xcode 3.2.6
	•	GCC 4.8.5
	•	g++ 4.8.5
	•	nvm 0.31.0
	•	git version 1.8.4.2
	•	curl 7.19.7
thanks

**Comment by fivedoor** [comment]
Updating to point to a dupe of this issue which was reported, addressed and resolved here: https://github.com/sass/libsass/issues/1998#issuecomment-211566181 
So I think this is good to be closed.
thanks!

**Comment by saper** [comment]
:) good to hear!
