### ISSUE TITLE
Failed to install node-sass@3.4.2 on windows 8.1

### ISSUE THREAD

**Issue by theljani** [sass/node-sass#1447]
I'm trying to install node-sass@3.4.2 but each time i get this error:
(node : v5.9.0 / npm: v3.7.3)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.11
npm WARN palatin@0.0.1 No repository field.
npm WARN palatin@0.0.1 license should be a valid SPDX license expression
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

Anyone can help ?

**Comment by saper** [comment]
Are you 32 bit or 64 bit?

**Comment by theljani** [comment]
it is 64 bit

**Comment by saper** [comment]
Can you try if the machine you are running this on can download https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-47_binding.node without any problems?

**Comment by theljani** [comment]
Yes, i can download it without any problem

**Comment by saper** [comment]
Is `npm install node-sass@beta` any better?

**Comment by saper** [comment]
Seems like others are bumping on a similar problem too: https://github.com/npm/npm/issues/8048 http://stackoverflow.com/questions/36008763/yeoman-installation-error-on-windows
Are you behind the proxy?

**Comment by theljani** [comment]
In fact i'm behind a proxy, but i configure it to enable module installation

**Comment by xzyfer** [comment]
This appears to be any npm issue. Please subscribe to https://github.com/npm/npm/issues/11265 for updates.
