### ISSUE TITLE
Failed at the node-sass@3.4.2 install script 'node scripts/install.js'

### ISSUE THREAD

**Issue by vicmonmena** [sass/node-sass#1448]
Hi! I've tried install ionic and I get and error about node-sass, then I decided install node-sass first and the same error same error is shown:

```
...:~ vicmonmena$ sudo npm install -g node-sass
Password:
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@3.4.2 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js

sh: node: command not found
/usr/local/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-sass"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vicmonmena/npm-debug.log
npm ERR! code 1
```

Any suggestion?

**+ info:**
OS X Yosemite (10.10.5)

Thanks!

**Comment by saper** [comment]
Is node on your $PATH after you run sudo?

**Comment by xzyfer** [comment]
Also make sure you have install scripts enabled

npm config set ignore-scripts false

On 4/19/16, Marcin Cieślak <notifications@github.com> wrote:
> Is node on your $PATH after you run sudo?
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/node-sass/issues/1448#issuecomment-211449762


-- 
Regards,
Michael

**Comment by kinorsi** [comment]
Thanks for @xzyfer. 'npm config set ignore-scripts false ' works fine.

**Comment by stschindler** [comment]
For people stumbling upon this and using Ubuntu or some other Debian derivative: Try `ln -s /usr/bin/nodejs /usr/bin/node`. This might probably be solved in node-sass itself, though.

**Comment by maurozenoni** [comment]
> For people stumbling upon this and using Ubuntu or some other Debian derivative: Try `ln -s /usr/bin/nodejs /usr/bin/node`. This might probably be solved in node-sass itself, though.

For alternative installations (e.g., via [nvm](https://github.com/nvm-sh/nvm) version manager), try:

`sudo ln -s $(which node) /usr/bin/node`
