### ISSUE TITLE
Error in ionic installation via npm

### ISSUE THREAD

**Issue by YatinGrover** [sass/node-sass#1454]
npm install ionic gives me the following error

> 
> > node-sass@3.4.2 install /root/node_modules/ionic/node_modules/node-sass
> > node scripts/install.js
> 
> 
> module.js:340
>     throw err;
>           ^
> Error: Cannot find module '/root/node_modules/ionic/node_modules/node-sass/scripts/install.js'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3
> /root
> `-- (empty)
> 
> npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
> npm WARN root No description
> npm WARN root No repository field.
> npm WARN root No README data
> npm WARN root No license field.
> npm ERR! Linux 3.16.0-30-generic
> npm ERR! argv "/root/.nvm/versions/node/v5.10.1/bin/node" "/root/.nvm/versions/node/v5.10.1/bin/npm" "install" "ionic"
> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
> npm ERR! Exit status 8
> npm ERR! 
> npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-sass
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls node-sass
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/npm-debug.log
> npm ERR! code 1
> 

I have tried installation via root also but got the same error.
npm version 3.8.3
node version v5.10.1

**Comment by xzyfer** [comment]
In the future please read the CONTRIBUTING.md before opening an issue. This error is [documented](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs), with solution.
