### ISSUE TITLE
Installation of 3.5.1 fails

### ISSUE THREAD

**Issue by minichate** [sass/node-sass#1455]
Getting:

 ```
00:01:24.100 npm info lifecycle node-sass@3.5.1~install: node-sass@3.5.1
00:01:24.124 
00:01:24.124 > node-sass@3.5.1 install /var/jenkins_home/workspace/build/node_modules/node-sass
00:01:24.124 > node scripts/install.js
00:01:24.125 
00:01:24.256 module.js:341
00:01:24.256     throw err;
00:01:24.256     ^
00:01:24.256 
00:01:24.256 Error: Cannot find module 'process-nextick-args'
00:01:24.256     at Function.Module._resolveFilename (module.js:339:15)
00:01:24.256     at Function.Module._load (module.js:290:25)
00:01:24.256     at Module.require (module.js:367:17)
00:01:24.256     at require (internal/module.js:16:19)
00:01:24.257     at Object.<anonymous> (/var/jenkins_home/workspace/build/node_modules/readable-stream/lib/_stream_readable.js:6:23)
00:01:24.257     at Module._compile (module.js:413:34)
00:01:24.257     at Object.Module._extensions..js (module.js:422:10)
00:01:24.257     at Module.load (module.js:357:32)
00:01:24.257     at Function.Module._load (module.js:314:12)
00:01:24.257     at Module.require (module.js:367:17)
00:01:24.281 npm info lifecycle node-sass@3.5.1~install: Failed to exec install script
```

additionally:
```
00:01:30.330  ERR! Linux 4.2.2-coreos-r1
00:01:30.330 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
00:01:30.330 npm ERR! node v5.9.0
00:01:30.330 npm ERR! npm  v3.7.3
00:01:30.330 npm ERR! code ELIFECYCLE
00:01:30.330 
00:01:30.330 npm ERR! node-sass@3.5.1 install: `node scripts/install.js`
00:01:30.330 npm ERR! Exit status 1
00:01:30.330 npm ERR! 
00:01:30.330 npm ERR! Failed at the node-sass@3.5.1 install script 'node scripts/install.js'.
00:01:30.330 npm ERR! Make sure you have the latest version of node.js and npm installed.
00:01:30.330 npm ERR! If you do, this is most likely a problem with the node-sass package,
00:01:30.330 npm ERR! not with npm itself.
00:01:30.330 npm ERR! Tell the author that this fails on your system:
00:01:30.331 npm ERR!     node scripts/install.js
00:01:30.331 npm ERR! You can get information on how to open an issue for this project with:
00:01:30.331 npm ERR!     npm bugs node-sass
00:01:30.331 npm ERR! Or if that isn't available, you can get their info via:
00:01:30.331 npm ERR!     npm owner ls node-sass
00:01:30.331 npm ERR! There is likely additional logging output above.
```

**Comment by xzyfer** [comment]
This seems like an npm issue not a node-sass issue. As described in out [documentation](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs) you probably not have permissions to run the install scripts. 

Try adding the `--unsafe-perm` to your `npm install`. 

```
npm install --unsafe-perm
```

Also make sure you have ignore-scripts set to false.

```
npm config set ignore-scripts false
```

**Comment by minichate** [comment]
Thanks! I'll try that out and close the ticket.

**Comment by minichate** [comment]
That doesn't appear to have fixed the problem. In case it helps, installation of `node-sass@3.4.2` works fine.

**Comment by xzyfer** [comment]
Unfortunately that doesn't help, but following the [troubleshooting documentation](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx) will.

Make sure to preserve **all** of the output into to [gist](https://gist.github.com/). Please do not post the output into this issue.

**Comment by minichate** [comment]
@xzyfer https://gist.github.com/minichate/03159498dfd5edb42a836512bf2f586d

This is running inside a docker container, which is why its running as `root`

**Comment by xzyfer** [comment]
We also need the npm debug log generated by the failed install. There have been issues with docker in the past.

**Comment by minichate** [comment]
I've added the debug log from the failed build: https://gist.github.com/minichate/03159498dfd5edb42a836512bf2f586d#file-install-log

**Comment by minichate** [comment]
To be clear; I don't want to prolong this ticket and keep it open if you're convinced that it isn't related to the recent node-sass release.

Thanks for your help :)

**Comment by xzyfer** [comment]
It's hard to say for sure since 3.5.0 was only just released a couple hours ago. Could you please provide the full log.

**Comment by minichate** [comment]
Unfortunately the full log has some internal things in it that I'm not quite comfortable sharing. I can wait and see if others report problems with ~3.5.1. In the meantime I can pin to an older version. Thanks!

**Comment by vladgurovich** [comment]
We have experienced the same problem that caused us to go back to 3.4.2

**Comment by xzyfer** [comment]
@vladgurovich unfortunately this statement does not help us resolve the issue. Please provide the information previously requested.

**Comment by minichate** [comment]
@xzyfer Interestingly I'm also seeing the same thing on OSX. I've updated the [gist](https://gist.github.com/minichate/03159498dfd5edb42a836512bf2f586d) to include debugging information from that machine as well -- and the entire npm.log from that run (with some file paths slightly obfuscated)

**Comment by xzyfer** [comment]
@minichate what's the output of

```
npm config get ignore-scripts
```

**Comment by minichate** [comment]
```
bash$ npm config get ignore-scripts
false
```

**Comment by xzyfer** [comment]
@minichate your logs are strangely unhelpful. I've never seen anything like it. They suggest an issue in `scripts/install.js` but provide no clue as to what the problem may be.

I can't reproduce this locally OSX. You may have to try debugging the file yourself locally.

**Comment by minichate** [comment]
@vladgurovich Yeah, similar symptoms here. I can install node-sass in isolation (`npm install node-sass`), but `npm install` in a repo that pulls in node-sass as an indirect dependency doesn't work.

We don't use shrinkwrap, so I don't think that is related.

**Comment by minichate** [comment]
Last update for the night from me :) If I do:
```
bash$ npm install node-sass@3.5.1; npm install
bash$ npm install node-sass@3.5.1; npm install
```

I can get it to install. The first line errors out, but retrying it works.

**Comment by josephlaw** [comment]
`npm install node-sass@3.4.2` success to install
`npm install node-sass@3.5.1 ` fail, how to fix it? 
i think it is not npm problem, thanks.

**Comment by basvandenheuvel** [comment]
We have a project running on a VM with WIndows behind a proxy. Because of the issue in 3.5.1 we can no longer download gulp-sass -> node-sass.  Isn't it possible to simply revert node-sass back to 3.5.0 so every one can continue with a working set-up and then fix the problem and re-release ?

**Comment by xzyfer** [comment]
@basvandenheuvel please stop commenting on so many issues. This issue is not related to your problem. We've released v3.5.2 which fixes your issue.

**Comment by basvandenheuvel** [comment]
@xzyfer good comment, your right. I'll check out 3.5.2 now.

**Comment by xzyfer** [comment]
@josephlaw unfortunately that doesn't help, but following the [troubleshooting documentation](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx) will.

Make sure to preserve **all** of the output, including the full npm log file, into to [gist](https://gist.github.com/). Please do not post the output into this issue.

**Comment by minichate** [comment]
The 3.5.3 update fixed the issue for us
