### ISSUE TITLE
Latest lib-sass bump can cause error with @extend

### ISSUE THREAD

**Issue by laurent-le-graverend** [sass/node-sass#1457]
[Bump to lib-sass 3.3.5](https://github.com/sass/node-sass/commit/5df330d2c2f5156305a6c9ca119c1488c8eabf7d) on the current version seems to have caused the following issue to appear:

> You may not @extend an outer selector from within @media

Maybe this rule and this breaking change makes sense, but raising the warning in case of it was not expected.

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. Ruby Sass raises this error if `@extend` is used incorrectly so we must also. LibSass assumes the your code is valid Sass, so as the project gets closer to Sass compatibility behaviour that is relying on LibSass bugs will stop working. 

LibSass 3.3.5 implemented some of the previously missing error checking for `@extend`. I could be that your Sass code has always been invalid but wasn't erring due LibSass bugs. It's impossible to confirm whether this is the case or if there is an actual LibSass bug from the information supplied. 

Please confirm you code compiled as expected with Sass.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by laurent-le-graverend** [comment]
I guess our code has always been invalid on this point but was properly compiled anyway.
Libsass 3.3.5 just raised the issue for the first time, as you said.

It wasn't a big refactoring to make it work compliant to this rule.
The error made sense with this rule. Not a bug.

**Comment by xzyfer** [comment]
You're not alone, we're seeing a lot of this as LibSass becomes more compliant. Thanks for looking into your issue.
