### ISSUE TITLE
Post Install fails inside a proxy

### ISSUE THREAD

**Issue by toninofox** [sass/node-sass#1458]
Dear all, 
I am trying to install node-sass inside a proxy properly configured in node npm via 
`npm config set proxy http://myproxy.com:8080`

all dependencies works but the post install of node-sass fails

 ```
npm info lifecycle node-sass@3.5.1~install: node-sass@3.5.1
 
  node-sass@3.5.1 install D:\...\node_modules\node-sass
  node scripts/install.js
 
 Cannot download "https://github.com/sass/node-sass/releases/download/v3.5.1/win32-ia32-47_binding.node": 
 
 getaddrinfo ENOTFOUND github.com github.com:443
 
 Hint: If github.com is not accessible in your location
       try setting a proxy via HTTP_PROXY, e.g. 
    export HTTP_PROXY=http://example.com:1234
 
 or configure npm proxy via
npm config set proxy http://example.com:8080


```

In the install.js script of the node-sass module, there is the proxy configuration reported below:

```
function applyProxy(options, cb) {
  var env = process.env;

  options.proxy = env.npm_config_https_proxy ||
                  env.npm_config_proxy ||
                  env.npm_config_http_proxy ||
                  env.HTTPS_PROXY ||
                  env.https_proxy ||
                  env.HTTP_PROXY ||
                  env.http_proxy;

  cb(options);
}
```

the older versions (that work inside the proxy) are configured with the function as below

```
function applyProxy(options, cb) {
  npmconf.load({}, function (er, conf) {
    var proxyUrl;

    if (!er) {
      proxyUrl = conf.get('https-proxy') ||
                 conf.get('proxy') ||
                 conf.get('http-proxy');
    }

    var env = process.env;

    options.proxy = proxyUrl ||
                    env.HTTPS_PROXY ||
                    env.https_proxy ||
                    env.HTTP_PROXY ||
                    env.http_proxy;

    cb(options);
  });
}
```

Thank You!

**Comment by thedarkdestructor** [comment]
We are experiencig the same exact issue!

shouldn't the search for a proxy rely on npm config properties instead of env variables?

A clarification will be highly appreciated.

**Comment by basvandenheuvel** [comment]
Same issue here.

**Comment by catchamonkey** [comment]
It worked before, just by using the env vars (which is nicer IMO).

**Comment by basvandenheuvel** [comment]
@xzyfer version 3.5.1 introduced proxy problems. Solution?

**Comment by xzyfer** [comment]
Unfortunately the library we used to get proxy configuration was
deprecated. We believed this to be equivalent behaviour.

I'm out at the moment but welcome a PR.

**Comment by basvandenheuvel** [comment]
@xzyfer  Im wondering. We use the gulp-sass package which uses the node-sass package as a dependency. We DIDN'T change the version of our gulp-sass but still get this error?

How can it be that some one changes dependencies in a live package instead of doing that in a new version?

**Comment by xzyfer** [comment]
Please provide the output of `env | grep proxy`

**Comment by xzyfer** [comment]
I've release v3.5.2 with a fix for this.

**Comment by xzyfer** [comment]
@catchamonkey could you please provide the output of 

```
env | grep -i proxy
```

**Comment by xzyfer** [comment]
Apologies everyone, these can be hard spot if not picked up by our beta testers.

**Comment by xzyfer** [comment]
Apologies everyone, these can be hard spot if not picked up by our beta testers.

**Comment by thedarkdestructor** [comment]
Thank you for your quick reaction. I'm going to test it and let you know.

**Comment by toninofox** [comment]
I am still have the issue using .npmrc file and trying to download the new 3.5.2. Does it work for someone?

**Comment by xzyfer** [comment]
Please provide the output you're seeing and the output from `npm ls
node-sass `

**Comment by toninofox** [comment]
npm info lifecycle node-sass@3.5.2~install: node-sass@3.5.2

> node-sass@3.5.2 install \src\main\webapp\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.5.2/win32-ia32-47_binding.node": 

getaddrinfo ENOTFOUND github.com github.com:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
npm info lifecycle ansi-regex@2.0.0~postinstall: ansi-regex@2.0.0
npm info lifecycle ansi-styles@2.2.1~postinstall: ansi-styles@2.2.1
npm info lifecycle minimatch@3.0.0~postinstall: minimatch@3.0.0
npm info lifecycle glob@7.0.3~postinstall: glob@7.0.3
npm info lifecycle has-ansi@2.0.0~postinstall: has-ansi@2.0.0
npm info lifecycle lodash@2.4.2~postinstall: lodash@2.4.2
npm info lifecycle lru-cache@2.7.3~postinstall: lru-cache@2.7.3
npm info lifecycle minimatch@0.3.0~postinstall: minimatch@0.3.0
npm info lifecycle glob@3.2.11~postinstall: glob@3.2.11
npm info lifecycle globule@0.2.0~postinstall: globule@0.2.0
npm info lifecycle gaze@1.0.0~postinstall: gaze@1.0.0
npm info lifecycle strip-ansi@3.0.1~postinstall: strip-ansi@3.0.1
npm info lifecycle supports-color@2.0.0~postinstall: supports-color@2.0.0
npm info lifecycle chalk@1.1.3~postinstall: chalk@1.1.3
npm info lifecycle node-sass@3.5.2~postinstall: node-sass@3.5.2

> node-sass@3.5.2 postinstall \src\main\webapp\node_modules\node-sass
> node scripts/build.js

"\src\main\webapp\node_modules\node-sass\vendor\win32-ia32-47\binding.node" exists. 
 testing binary.
Problem with the binary:
Error: %1 is not a valid Win32 application.
\\?\\src\main\webapp\node_modules\node-sass\vendor\win32-ia32-47\binding.node

**Comment by xzyfer** [comment]
I believe I've found the issue. We recently our http library and the new open appears to have issues with proxies. I'll revert this change and release v3.5.3 shortly.

**Comment by xzyfer** [comment]
Hello all, I've released v3.5.3 which should fix the proxy issue for good. My sincere apologies for the disruption this has cause you.

**Comment by toninofox** [comment]
Perfect it works! No problem and thank you for your prompt actions :)

**Comment by blowsie** [comment]
Anyone that ends up here might be intrested to know that `https://github.com/sass/node-sass/releases/download/v3.5.2/win32-ia32-47_binding.node` currently resolves to `github-cloud.s3.amazonaws.com`. So you may have to add exceptions to your corporate proxy accordingly

**Comment by nimatullah** [comment]
I have got same issue with version `4.11.0`

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-64_binding.node": 

read ECONNRESET

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080


```

**Comment by xzyfer** [comment]
The solution is the error message. We have no other advice to offer.
