### ISSUE TITLE
3.5.1 introduces a breaking change

### ISSUE THREAD

**Issue by kdzwinel** [sass/node-sass#1459]
Our build server just downloaded latest version of gulp-sass (2.3.0) which in turn downloaded node-sass 3.5.1. This caused a previously unseen critical error in the code that wasn't touched since January:

Message:

     21-Apr-2016 08:54:12	node_modules/style-guide/src/sass/_mixins.scss
     21-Apr-2016 08:54:12	Error: Mixins may not be defined within control directives or other mixins.
     21-Apr-2016 08:54:12	        on line 90 of node_modules/style-guide/src/sass/_mixins.scss
     21-Apr-2016 08:54:12	>>   @mixin mintBreakpoint($name) {
     21-Apr-2016 08:54:12	   --^

Relevant code:

https://github.com/brainly/style-guide/blob/42136dd914ea0626cc76f7d1a39ee37bf836c376/src/sass/_mixins.scss#L88

Last successful build was using version node-sass@3.4.2.

**Comment by xzyfer** [comment]
This project is just an implementation of the Sass language. It aims to be
100% compatible with Sass.

This is happening because your Sass is not valid. As the message says
mixins and functions cannot be defined in control structures like if
statements.

This previously worked due to a bug in LibSass which was fixed in latest
version.

**Comment by slarti-b** [comment]
I just had the same.  In my case it's grunt-sass which downloaded the dependency.  But suddenly my existing tags don't build anymore!

I have a mixin defined inside a @if not mixin-exists block which is apparently not allowed anymore.  Also variables defined inside @if not variable-exists now seem to be only valid within that block unless declared global.

It may be that these have been seen as bug fixes ("we weren't interpreting the sass spec properly, now we are" but they should still be flagged as breaking changes - by making the interpretation much stricter you are breaking stuff which worked.  And should therefore have been a version which did not come as "compatible" according to npm.

**Comment by kdzwinel** [comment]
@xzyfer thanks for explanation! I agree with @slarti-b though that it's a node-sass versioning issue.

**Comment by slarti-b** [comment]
@xzyfer : yeah, I guessed that.  But this much stricter is still a breaking change - even if a "breaking bug-fix"

**Comment by xzyfer** [comment]
To be clear this was never allowed but it mistakenly worked. This is no different to depending on an undocumented API. For that reason we do not consider these breaking changes. 

If valid Sass started breaking we would consider that a breaking change. We don't claim responsibility for bugs in the Sass code being compiled.

**Comment by kdzwinel** [comment]
That makes sense @xzyfer . Thank you for a quick response.

**Comment by igoradamenko** [comment]
Same issue here, but OK, I understand that this is a bug and it worked mistakenly. So is it possible to get a “legal” conditional import (in my case `@import` inside of `@if` does not work)?

**Comment by xzyfer** [comment]
Conditional imports are not possible in Sass.

**Comment by igoradamenko** [comment]
So sad. OK, thank you @xzyfer. I will search a workaround.
