### ISSUE TITLE
After updating node-sass from 3.4.2 -> 3.5.2 get errors in my App

### ISSUE THREAD

**Issue by VectorM** [sass/node-sass#1462]
I use Compass-mixins via webpack.
After then i update my package, i get error in console
http://i.imgur.com/aAiDGOB.png
First, i come back to old version my packages (sass-loader,css-loader) and still have this error.
So then i do same action with node-sass, and now all is fine.
So its problem with 3.5.2!?

**Comment by xzyfer** [comment]
This a bug in compass-mixins (https://github.com/Igosuki/compass-mixins/issues/85)
