### ISSUE TITLE
[FR] Enable libsass plugins

### ISSUE THREAD

**Issue by mgreter** [sass/node-sass#1463]
Just saw that node-sass does not seem to expose [plugin paths] [1]. Not sure if this was deliberately, but adding it should be trivial as it should follow the exact same logic as with include paths.

FYI: currently there (probably) only exist these two plugins:
- https://github.com/mgreter/libsass-glob
- https://github.com/mgreter/libsass-math

Would be great if this could be added to node-sass. Thanks!

[1]: https://github.com/sass/libsass/blob/master/docs/api-context.md

**Comment by xzyfer** [comment]
This is on purpose. We do not wish to support more experimental surface area at the moment.

**Comment by mgreter** [comment]
OK
