### ISSUE TITLE
v3.5.x fails with certain .scss code

### ISSUE THREAD

**Issue by dryoma** [sass/node-sass#1465]
Hi!

Starting with 3.5.0 (tested up to 3.5.3) `node-sass`, when processing certain code, neither produces CSS nor prints any errors. I managed to locate an exapmle from a real project to this minimal amount of code:
```
.btn {
  padding: 0;
  margin: 0;
  display: inline-block;
}

@mixin list-link() {
  a {
    &:not(.btn) {
      font: inherit;
    }
  }
}


.article-template {
  @include list-link();
}


.cub-btn {
  @extend .btn;
}

ul.list-link {
  @include list-link;
}
```
You can use a test repo to quickly reproduce it: https://github.com/dryoma/node-sass-test

`node-sass` 3.5.3, `gulp-sass` 2.2.0 and 2.3.0. Node.js 4.4.0.

**Comment by xzyfer** [comment]
Thanks for the report. This is a bug in LibSass. You can subscribe to it in https://github.com/sass/libsass/issues/2017

**Comment by dryoma** [comment]
Thanks!
