### ISSUE TITLE
New update is breaking compass-mixins

### ISSUE THREAD

**Issue by justrossthings** [sass/node-sass#1473]
Using grunt-sass (has node-sass dep) w/ compass-importer (imports compass-mixins for us with libsass)

I don't want to switch from grunt-sass to node-sass just to go back a version 👎

**Comment by jrowlingson** [comment]
https://github.com/Igosuki/compass-mixins/issues/85, https://github.com/Igosuki/compass-mixins/issues/84

**Comment by xzyfer** [comment]
This is a bug in compass mixins. Nothing we can do.
