### ISSUE TITLE
Cannot download "win32-x64-48_binding.node"

### ISSUE THREAD

**Issue by hzhengran** [sass/node-sass#1489]
Could you kindly help with this issue? Thanks:

Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node":

HTTP error 404 Not Found

My env:
node: 6.0.0
npm: 3.8.7

**Comment by xzyfer** [comment]
Node 6 is not yet support. Down grade node and you'll be fine.

On 4/27/16, hzhengran <notifications@github.com> wrote:
> Could you kindly help with this issue? Thanks:
>
> Cannot download
> "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node":
>
> HTTP error 404 Not Found
>
> My env:
> node: 6.0.0
> npm: 3.8.7
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/node-sass/issues/1489


-- 
Regards,
Michael

**Comment by hzhengran** [comment]
thank you very much for you light speed response!

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.
