### ISSUE TITLE
Allow to override SASS_BINARY_SITE with "file://" URI scheme

### ISSUE THREAD

**Issue by pgarciafc** [sass/node-sass#1490]
Hi.

We are doing a couple of builds in our company that requires node-sass, but our continuous integration servers don't have connection to the Internet to retrieve the Linux bindings file (or any other required for the build), so the build is failing.

I have tried a solution based in downloading node-sass to a path in my filesystem and then declare SASS_BINARY_SITE as "file:///path/to/my/node-sass/binaries" but it does not work: It seems that "file://" URI scheme is not supported.

Can you please provide a different solution or if there is not, allow SASS_BINARY_SITE to be used along with "file://" ?

Thanks in advance,
Pablo.

**Comment by xzyfer** [comment]
We have a clearly documented solution in our readme.

https://github.com/sass/node-sass#binary-configuration-parameters
