### ISSUE TITLE
Rebuild with NodeJS 6 makes huge trace every time node-sass used

### ISSUE THREAD

**Issue by iddqdidkfa** [sass/node-sass#1493]
After `npm rebuild node-sass` appeared: http://pastebin.com/S4wetaaX
and each time I use `grunt-sass` this huge trace appears in console.
Someone forgot to disable debug info?

**Comment by xzyfer** [comment]
Duplicate of https://github.com/sass/node-sass/issues/1484

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.
