### ISSUE TITLE
node-sass install (sub-install under ionic on OS X) throws error

### ISSUE THREAD

**Issue by alanhaw** [sass/node-sass#1494]
Attempting to install ionic which does a sub-install of node-sass. The node-sass install fails due to a permissions error, blocking the ionic install. This is on OS X 10.10.5 with node v4.4.3 and npm  v2.15.1 .
The attached files were generated with: sudo npm install -g -ddd ionic > npm.log 2> npm.err

[npm-debug.log.txt](https://github.com/sass/node-sass/files/239185/npm-debug.log.txt)
[npm.log.txt](https://github.com/sass/node-sass/files/239186/npm.log.txt)
[npm.err.txt](https://github.com/sass/node-sass/files/239188/npm.err.txt)

**Comment by xzyfer** [comment]
Npm installing with sudo is usually a bad idea. If you must then you need
the `--unsafe-perm` flG.

**Comment by alanhaw** [comment]
I discovered the ‘—unsafe-perm’ option separately today, and it worked. Will have to investigate how to setup without sudo. 
Thanks!
