### ISSUE TITLE
Heroku compile issues / Locking libsass version

### ISSUE THREAD

**Issue by chrisforrette** [sass/node-sass#1495]
Hello,

I've got a project using `node-sass` and Heroku and I'm leveraging the `postinstall` script to compile the CSS on deployment. Today I ran a deploy for the first time in a couple of weeks and saw a bunch of odd compile errors that seemed to be centered around scope, which I cannot reproduce locally.

This error popped up from where I was using an `@extend` against a class declaration that was generated from within an `@each` loop in another file (`.ico-carat-right`):

```json
{
  "formatted": "Error: You may not @extend an outer selector from within @media.\n       You may only @extend selectors within the same directive.\n       From \"@extend .ico-carat-right\" on line 95 of static/scss/pages/team/_roster.scss\n        on line 83 of static/scss/base/_shared.scss\n>> \n   --^\n",
  "message": "You may not @extend an outer selector from within @media.\nYou may only @extend selectors within the same directive.\nFrom \"@extend .ico-carat-right\" on line 95 of static/scss/pages/team/_roster.scss\n",
  "column": 3,
  "line": 83,
  "file": "/Users/chrisforrette/Code/remo/static/scss/base/_shared.scss",
  "status": 1
}
```

With this one I was setting a variable (`$color`) inside of an `@if/@else` statement, which seemed to munge the scope in the following lines:

```json
{
  "formatted": "Error: Undefined variable: \"$color\".\n        on line 163 of static/scss/base/_typography.scss\n>>   $notch-color: $color;\n   ----------------^\n",
  "message": "Undefined variable: \"$color\".",
  "column": 17,
  "line": 163,
  "file": "/Users/chrisforrette/Code/remo/static/scss/base/_typography.scss",
  "status": 1
}
```

I noticed there was a new `node-sass` release a few days ago that bumped the `libsass` version, so I suspect that might be at the root of these issues. So I'm hoping to find help on a few things—first, I realized I don't know how libsass is installed and/or what version of libsass is used when I deploy to Heroku. Locally I have libsass 3.3.4 installed with brew, does `node-sass` get installed with libsass binaries (on Heroku)?

And I know this is not quite in scope of this repo, but I'm hoping someone can tell me what Sass updates I may have missed where my code is now broken. Did some big scoping changes happen some time in the last few months that may have caused these issues?

Thanks!

**Comment by chriseppstein** [comment]
https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9

**Comment by mgreter** [comment]
Your getting https://github.com/sass/node-sass/issues/1457. Please use the [search] [1] before opening new issues. Thanks.

[1]: https://github.com/sass/node-sass/search?q=Error%3A+You+may+not+%40extend+an+outer+selector+from+within+%40media.&type=Issues&utf8=%E2%9C%93

**Comment by chrisforrette** [comment]
@chriseppstein Thanks!

@mgreter Thanks for the ticket link—and for the record, I did several searches first, just not with matching terms :)
