### ISSUE TITLE
Node 6.0 (win64): win32-x64-48_binding.node is missing

### ISSUE THREAD

**Issue by pmadziar** [sass/node-sass#1497]
The scripts/install.js tries to download win32-x64-48_binding.node file which is missing:
----------------------------------------
> node-sass@3.6.0 install C:\Source\github\dci\dcijs\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node":

HTTP error 404 Not Found
----------------------------------------

The file is not present in the repository.

node v6.0.0
npm 3.8.8

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/1484

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.

**Comment by MuthuAliasKumar** [comment]
am still facing the issue

[INFO] > node-sass@4.5.0 install D:\Application\FOR\siva\dev_sprint15_common_2\node_modules\@ionic\app-scripts\node_modules\node-sass
[INFO] > node scripts/install.js
[INFO]
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-48_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-48_binding.node":
[ERROR]
[ERROR] tunneling socket could not be established, statusCode=403
[ERROR]
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g.


I tried using npm rebuild node-sass, but no use

My setup:
Windows: 8.1
Node: 6.3.1
NPM: 4.2.0

Please tag me if any on going topic for this issue, or resolution

**Comment by xzyfer** [comment]
@MuthuAliasKumar the binary is not missing. It appears your proxy or network settings are preventing you from downloading it.

>tunneling socket could not be established, statusCode=403
