### ISSUE TITLE
Add Node v6.0.0 support

### ISSUE THREAD

**Issue by Snabel** [sass/node-sass#1504]
When using node v6.0.0 with node-sass and webpack i get the following error:
> webpack --config webpack.config.dev.js --watch

Hash: 9e5059f15d2b9c2485b1
Version: webpack 1.13.0
Time: 1991ms
 Asset     Size  Chunks             Chunk Names
app.js  1.13 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 285 hidden modules

ERROR in Node Sass does not yet support your current environment: OS X 64-bit with false
For more information on which environments are supported please see:
TODO URL
 @ ./src/style/main.scss 4:14-121

**Comment by lorem--ipsum** [comment]
I think it's done but needs a release, looking at the code.

**Comment by xzyfer** [comment]
We're blocked on appveyor adding mode 6 support.

**Comment by jhough10** [comment]
@xzyfer is there any info on when appveyor will add mode 6 support?

**Comment by xzyfer** [comment]
You know as much as I do

**Comment by lorem--ipsum** [comment]
Meanwhile, I did that (dirty as hell but who cares) to keep on working :
 - change the locally installed files according to https://github.com/sass/node-sass/commit/b0e1e1bf4c31c6e9b94d3de8574a3908a1877c6f
 - run `npm rebuild node-sass`

Enjoy (especially if you like flooded console outputs).

**Comment by jhough10** [comment]
@lorem--ipsum yeah, the stack traces are a good read especially when you have to find errors. 👍

**Comment by cosminn777** [comment]
+1 pls

**Comment by glen-84** [comment]
@cosminn777 Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) now, instead of +1 comments.

**Comment by glen-84** [comment]
Not sure if this is relevant: https://twitter.com/appveyor/status/725385312843632640

**Comment by xzyfer** [comment]
Yeap we're on it. We currently have s failing Windows test with node 6 in
CI only. Going to dig into it in the next 24hrs.

**Comment by mahdaen** [comment]
+1 :)

**Comment by JaLuxe** [comment]
I just failed installing on Windows 64 bit.

It seems as if it is tried to download a non-existing .node file "..x-64-48binding.node"

npm 3.8.8
node.js v 6.00

"Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-48binding.node":

HTTP error 404 Not Found"

Is there a way to install an older version to get it running until it's fixed?
Thank you in advance for your efforts.

JaLuxe

ps. Sorry if this comment shoould be misplaced

**Comment by Robert-Janagap** [comment]
@JaLuxe same here problem

**Comment by byCedric** [comment]
@JaLuxe Yes, de `48` version of the bindings are not released. Therefore it tries to make it from the source I think. This is because version `48`, or `node v6.0.0`, is not in the latest release. Let's hope everybody is as awesome as usual, and its fixed asap :).

**Comment by ketsugi** [comment]
I updated to Node 6.0.0 and now I'm getting these huge stack traces whenever the sass task runs. Am I right to understand that these are not errors and I can ignore them?

**Comment by xzyfer** [comment]
For those playing along at home we've spent the last 48hrs debugging a bug in Node 6 (https://github.com/nodejs/node/issues/6500) which is blocking us.

**Comment by robjens** [comment]
Well here it builds, it is just a deprecation warning (albeit annoying one) and it should be node 7 ready anyway. When I run `gulp` it spits out tons of JS/C stack dump but for the rest everything works.

**Comment by PepijnSenders** [comment]
Is there any way to silence these stack traces?

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.

**Comment by Muralilive** [comment]
'npm install gulp-sass ' this work for me
