### ISSUE TITLE
Error while installing node-sass

### ISSUE THREAD

**Issue by rakoes** [sass/node-sass#1507]
I received an error installing node-sass: npm install gulp-sass --save-dev

Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node": HTTP error 404 Not Found

I'm not behind a proxy. The file seems to be missing in your repo.

**Comment by spa46** [comment]
Do you use wifi? I had a similar log when I reject from the wifi connection.

**Comment by xzyfer** [comment]
Node 6 is not supported. There are always 3 other identical issues. Please
take the time to search before opening an issue.

**Comment by rakoes** [comment]
I'm pretty sure I read something about support for version 6. Obviously i'm mistaken, sorry for that.

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.
