### ISSUE TITLE
error installing gulp-sass in windows

### ISSUE THREAD

**Issue by Robert-Janagap** [sass/node-sass#1509]
npm -v : 3.8.6
node -v : v6

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> node-sass@3.6.0 install G:\projects-2016\janagap\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.6.0 postinstall G:\projects-2016\janagap\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe G:\projects-2016\janagap\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'G:\\projects-2016\\janagap\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@6.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (G:\projects-2016\janagap\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (G:\projects-2016\janagap\node_modules\which\which.js:72:29)
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\which\which.js:81:16
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at F (G:\projects-2016\janagap\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (G:\projects-2016\janagap\node_modules\which\which.js:72:29)
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\which\which.js:81:16
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (G:\projects-2016\janagap\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (G:\projects-2016\janagap\node_modules\which\which.js:72:29)
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\which\which.js:81:16
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at F (G:\projects-2016\janagap\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (G:\projects-2016\janagap\node_modules\which\which.js:72:29)
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\which\which.js:81:16
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at G:\projects-2016\janagap\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (G:\projects-2016\janagap\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at G:\projects-2016\janagap\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\projects-2016\\janagap\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd G:\projects-2016\janagap\node_modules\node-sass
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
janagap@1.0.0 G:\projects-2016\janagap
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "gulp-sass" "-D"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.6.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.6.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\projects-2016\janagap\npm-debug.log
npm ERR! code 1

**Comment by xzyfer** [comment]
Node 6 is not supported.. Please download grade.

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.
