### ISSUE TITLE
Missing file while instaling node-sass

### ISSUE THREAD

**Issue by Sonicelo** [sass/node-sass#1511]
During npm i node-sass I get an error:
Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node"

I checked on the repo and it does indeed not exist. I tried also with previous version and same hapends.

**Comment by byCedric** [comment]
It's because node v6.0.0 (48) is not yet supported, see #1504

**Comment by xzyfer** [comment]
node-sass@v3.7.0 has been released.

**Comment by Sonicelo** [comment]
Thank you.
