### ISSUE TITLE
v3.6.0 Node Sass does not yet support your current environment

### ISSUE THREAD

**Issue by alehro** [sass/node-sass#1515]
Gulp in Visual studio issues this error on Win10 x64 while trying to  open gulpfile.js. The error message tells that it wants x32 - cannot remember exact wording. 'npm rebuild node-sass' doesn't help. Reverting of node-sass to v3.5.0 fixed the error.

**Comment by saper** [comment]
Please quote the exact message - and this is pretty common issue with Visual Studio - just make sure the same node engine is used to build node-sass as well as execute it. Make sure to read our [Troubleshooting Guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#using-node-sass-with-visual-studio-2015-task-runner)

**Comment by DerekFoulk** [comment]
@saper - Could you please re-open this issue. Here is the message that I continue to see even after running the suggested `npm rebuild node-sass` command:

```
Error: Missing binding C:\Users\Owner\Source\Repos\nwca-nopcommerce\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node
Node Sass could not find a binding for your current environment: Windows 32-bit with Node 0.10.x
Found bindings for the following environments:
  - Windows 64-bit with Node.js 4.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (C:\Users\Owner\Source\Repos\nwca-nopcommerce\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Owner\Source\Repos\nwca-nopcommerce\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

I think the issue may be that Visual Studio 2015 (Community Edition) uses the x86 PowerShell to execute the built-in "Task Runner Explorer" CLI. I have no idea why that would matter, but it's a guess...

**My Environment:**
- Windows 10 Pro x64
- Node.js v4.4.4
- Gulp CLI v3.9.0
- gulp-sass v2.3.1

I tried to resolve this by opening the x86 PowerShell and running `npm rebuild node-sass`, then running the task again in VS, but the issue persisted.

**Comment by saper** [comment]
Please read the troubleshooting doc, it describes the problem with visual studio.... You end up using two different node engines at the same time, so you need binaries for both.

**Comment by nicksterx** [comment]
You can force Visual Studio to use your installed version of NodeJS instead of its built in version. Add the path of NodeJS to the top of External Web Tools under Tools -> Options. I was having the same issue as @DerekFoulk and this corrected it for me. 

Your External Web Tools should look similar to this:
![externaltoolsvs2015](https://cloud.githubusercontent.com/assets/440031/15933886/becadf08-2e1e-11e6-827d-073f4ae91a35.PNG)

This is the guide that pointed me in the right direction:
http://ryanhayes.net/synchronize-node-js-install-version-with-visual-studio-2015/

**Comment by DerekFoulk** [comment]
Thank you guys! I was unaware of the guide and workaround. Much appreciated!

**Comment by ankit217** [comment]
@nicksterx 
by adding nodejs path, It worked for me.
