### ISSUE TITLE
Install fail on windows with error

### ISSUE THREAD

**Issue by twoeo** [sass/node-sass#1521]
npm install node-sass

And got error below

=======================================================================

> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of dat
e with respect to npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "install" "node-sass" "--save"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! file C:\Users\longsheng\AppData\Roaming\npm-cache\invert-kv\1.0.0\package\package.json
npm ERR! code EJSONPARSE

> npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\longsheng\AppData\Roaming\npm-cache\invert-kv\1.0.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

> npm ERR! Please include the following file with any support request:
npm ERR!     E:\Codes\analyzer\frontend\npm-debug.log

**Comment by nschonni** [comment]
Sounds like you have a malformed package.json file, this isn't an issue with node-sass.

> npm ERR! File: C:\Users\longsheng\AppData\Roaming\npm-cache\invert-kv\1.0.0\package\package.json
> npm ERR! Failed to parse package.json data.
> npm ERR! package.json must be actual JSON, not just JavaScript.
