### ISSUE TITLE
Error building in FreeBSD

### ISSUE THREAD

**Issue by oriold** [sass/node-sass#1524]
I have a problem building this software on FreeBSD. Looks like the url to download a binary is wrong:

Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/freebsd-x64-47_binding.node"

It should be: https://github.com/sass/node-sass-binaries/releases/download/v3.7.0/freebsd-x64-47_binding.node

The url is sourced in scripts/install.js

Regards,

**Comment by xzyfer** [comment]
As there [v3.7.0 release states](https://github.com/sass/node-sass/releases/tag/v3.7.0) the FreeBSD binaries are not ready yet.

/cc @saper.

**Comment by saper** [comment]
Yes, the binaries are on the way.

**Comment by saper** [comment]
:tada: The binaries are ready! Thank you for your patience!
