### ISSUE TITLE
npm install bugs

### ISSUE THREAD

**Issue by SerjMalko** [sass/node-sass#1525]
13271 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
13271 verbose stack Exit status 1
13271 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
13271 verbose stack     at emitTwo (events.js:106:13)
13271 verbose stack     at EventEmitter.emit (events.js:191:7)
13271 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
13271 verbose stack     at emitTwo (events.js:106:13)
13271 verbose stack     at ChildProcess.emit (events.js:191:7)
13271 verbose stack     at maybeClose (internal/child_process.js:850:16)
13271 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13272 verbose pkgid node-sass@3.4.2
13273 verbose cwd d:\WebstormProjects\angular-http
13274 error Windows_NT 6.3.9600
13275 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
13276 error node v6.0.0
13277 error npm  v3.8.6
13278 error code ELIFECYCLE
13279 error node-sass@3.4.2 postinstall: `node scripts/build.js`
13279 error Exit status 1
13280 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
13280 error Make sure you have the latest version of node.js and npm installed.
13280 error If you do, this is most likely a problem with the node-sass package,
13280 error not with npm itself.
13280 error Tell the author that this fails on your system:
13280 error     node scripts/build.js
13280 error You can get information on how to open an issue for this project with:
13280 error     npm bugs node-sass
13280 error Or if that isn't available, you can get their info via:
13280 error     npm owner ls node-sass
13280 error There is likely additional logging output above.
13281 verbose exit [ 1, true ]

**Comment by xzyfer** [comment]
Update node-sass@v3.7.0 for Node.js 6 support.
