### ISSUE TITLE
Not able to install node-sass@0.8.6 on windows.

### ISSUE THREAD

**Issue by shoefler** [sass/node-sass#1529]
I am trying to install dependencies to a project and node-sass is holding me up.  I am using npm version 3.8.8 and node version 5.1.0.  
Attached is my log file.  Any help is appreciated. 
[npm-debug.zip](https://github.com/sass/node-sass/files/250800/npm-debug.zip)

**Comment by saper** [comment]
Node-sass 0.8.6 is ancient. Please use the current version (3.7.0).
