### ISSUE TITLE
Array for --include-path using CLI

### ISSUE THREAD

**Issue by justsayno** [sass/node-sass#1533]
Is it possible to have more than one "include path". For example if I have a folder scss and also want to include a scss file from my node_modules folder?

**Comment by xzyfer** [comment]
Yes, just pass multiple `--include-path`s.

**Comment by justsayno** [comment]
Sorry just for clarity. For example I could write something like this:

```
“scripts”: {
  “build-css”: “node-sass --include-path scss node_modules/bootstrap-sass scss/main.scss   public/css/main.css”
},
```

Seperated by a space as above?

**Comment by justsayno** [comment]
Should have just waited and tried it. This is how it seems to work:

```
  "scripts": {
    "build-css": "node-sass --include-path styles/scss --include-path node_modules/bootstrap-sass/assets/stylesheets styles/scss/main.scss styles/main.css"
  }
```

**Comment by xzyfer** [comment]
No sorry,`--include-path foo --include-path bar`

**Comment by bewards** [comment]
@xzyfer thanks for asking this question, i got it to work in powershell like below:

`node-sass --include-path=bower_components\breakpoint-sass\stylesheets\ --include-path=bower_components\bootstrap-sass\assets\stylesheets\ --include-path=bower_components\bxslider-4\src\css\ .\Includes\_scss\app.scss 'D:\Publish\SIM\VCA Sitecore\Website\Includes\_css\app2.css'`
