### ISSUE TITLE
CLI watcher's import graph is not updated when files are added or deleted

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1538]
Originally mentioned in https://github.com/sass/node-sass/issues/1095#issuecomment-176529490. This has been a known issue for a long time but has only recently come up.

### Background

Most watchers will niavely recompile all watched files when a watched file is modified. This is the case with tools like gulp and grunt.

### Smart watching

The Node Sass watcher is a bit smarted. When the CLI watcher is started up it builds graph of Sass imports for the files it's watching. With this graph it can determine which files to recompile when a partial is changed. This is sometimes referred to as incremental compilation.

### The bug

Currently this graph is only generated when the CLI watcher is started. This means the grpah isn't updated when files are added or deleted. This latter isn't much of problem, but the former results in new files not triggering recompiles.

The only way to register these files in the graph is to restarted the watcher.

**Comment by xzyfer** [comment]
/cc @d6u @ryankask @Karklis

I have also deleted your comments on #1095 because they were off topic and distracted from the original issue.

**Comment by nereski** [comment]
I’ve installed the latest version of `node-sass` directly from this repository willing to solve this, but I’m still facing the same problems you described above.

It seems that the `added` event of `gaze` does not trigger when a new file is added. So the `sass-graph` is not updated and neither the watched files by gaze.

The delete event works like a charm and the sass-graph is perfectly updated in that case. It seems I’m not the only one facing this problem with `gaze added emitter` not firing. Even with the information I've gathered in some issues from gaze, like this one [shama/gaze/issue#205](https://github.com/shama/gaze/issues/205), I can’t get this working.
I’m currently using node v6.2.0 in Mac OS X v10.11.5 .

Thanks for taking action in this bug. If you need further feedback from me, don’t hesitate to ask.
