### ISSUE TITLE
ERROR : Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.

### ISSUE THREAD

**Issue by sheha** [sass/node-sass#1540]
hi all, 
i cannot seem to get around this any way i try.
I'm executing an script on my laptop that needs to rsync my changes to a vagrant VM 

The version of npm is 3.8.6
and of nodejs is 6.1.0

Funny thing is, everything OK on my desktop PC, with npm 3.8.7 and nodejs 5.11.0
Also, on my desktop, npm in virtualenv is pointed to /usr/bin/npm
but on the laptop is pointing to the one in the VM.
I followed the same steps of installing everything as I did on the desktop pc.

126397 info lifecycle is-my-json-valid@2.13.1~postinstall: is-my-json-valid@2.13.1
126398 silly lifecycle is-my-json-valid@2.13.1~postinstall: no script for postinstall, continuing
126399 silly postinstall har-validator@2.0.6 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/har-validator-24f5853c
126400 info lifecycle har-validator@2.0.6~postinstall: har-validator@2.0.6
126401 silly lifecycle har-validator@2.0.6~postinstall: no script for postinstall, continuing
126402 silly postinstall request@2.72.0 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/request-8b4eef40
126403 info lifecycle request@2.72.0~postinstall: request@2.72.0
126404 silly lifecycle request@2.72.0~postinstall: no script for postinstall, continuing
126405 silly postinstall node-gyp@3.3.1 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/node-gyp-eb848113
126406 info lifecycle node-gyp@3.3.1~postinstall: node-gyp@3.3.1
126407 silly lifecycle node-gyp@3.3.1~postinstall: no script for postinstall, continuing
126408 silly postinstall eslint@0.24.0 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/eslint-bfa59ead
126409 info lifecycle eslint@0.24.0~postinstall: eslint@0.24.0
126410 silly lifecycle eslint@0.24.0~postinstall: no script for postinstall, continuing
126411 silly postinstall y18n@3.2.1 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/y18n-c41b0af9
126412 info lifecycle y18n@3.2.1~postinstall: y18n@3.2.1
126413 silly lifecycle y18n@3.2.1~postinstall: no script for postinstall, continuing
126414 silly postinstall yallist@2.0.0 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/yallist-0e8da368
126415 info lifecycle yallist@2.0.0~postinstall: yallist@2.0.0
126416 silly lifecycle yallist@2.0.0~postinstall: no script for postinstall, continuing
126417 silly postinstall lru-cache@4.0.1 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/lru-cache-cd7d51af
126418 info lifecycle lru-cache@4.0.1~postinstall: lru-cache@4.0.1
126419 silly lifecycle lru-cache@4.0.1~postinstall: no script for postinstall, continuing
126420 silly postinstall cross-spawn-async@2.2.2 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/cross-spawn-async-2ba3ce56
126421 info lifecycle cross-spawn-async@2.2.2~postinstall: cross-spawn-async@2.2.2
126422 silly lifecycle cross-spawn-async@2.2.2~postinstall: no script for postinstall, continuing
126423 silly postinstall cross-spawn@2.2.3 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/cross-spawn-4875b654
126424 info lifecycle cross-spawn@2.2.3~postinstall: cross-spawn@2.2.3
126425 silly lifecycle cross-spawn@2.2.3~postinstall: no script for postinstall, continuing
126426 silly postinstall yargs@3.27.0 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/yargs-01cc61e8
126427 info lifecycle yargs@3.27.0~postinstall: yargs@3.27.0
126428 silly lifecycle yargs@3.27.0~postinstall: no script for postinstall, continuing
126429 silly postinstall sass-graph@2.1.1 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/sass-graph-3f580cdb
126430 info lifecycle sass-graph@2.1.1~postinstall: sass-graph@2.1.1
126431 silly lifecycle sass-graph@2.1.1~postinstall: no script for postinstall, continuing
126432 silly postinstall node-sass@3.4.2 /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging/node-sass-2894c8d1
126433 info lifecycle node-sass@3.4.2~postinstall: node-sass@3.4.2
126434 verbose lifecycle node-sass@3.4.2~postinstall: unsafe-perm in lifecycle true
126435 verbose lifecycle node-sass@3.4.2~postinstall: PATH: /home/sheha/.virtualenvs/amerit-nuevo/lib/node_modules/npm/bin/node-gyp-bin:/home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/node-sass/node_modules/.bin:/home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.bin:/home/sheha/.virtualenvs/amerit-nuevo/bin:/home/sheha/.virtualenvs/amerit-nuevo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sheha/Code/reposAmerit/amerit-nuevo/bin
126436 verbose lifecycle node-sass@3.4.2~postinstall: CWD: /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/node-sass
126437 silly lifecycle node-sass@3.4.2~postinstall: Args: [ '-c', 'node scripts/build.js' ]
126438 silly lifecycle node-sass@3.4.2~postinstall: Returned: code: 1  signal: null
126439 info lifecycle node-sass@3.4.2~postinstall: Failed to exec postinstall script
126440 verbose unlock done using /home/sheha/.npm/_locks/staging-0e2fff4a49eb1ea3.lock for /home/sheha/Code/reposAmerit/amerit-nuevo/client/node_modules/.staging
126441 silly rollbackFailedOptional Starting
126442 silly rollbackFailedOptional Finishing
126443 silly runTopLevelLifecycles Starting
126444 silly runTopLevelLifecycles Finishing
126445 silly install printInstalled
126446 warn optional Skipping failed optional dependency /chokidar/fsevents:
126447 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
126448 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
126448 verbose stack Exit status 1
126448 verbose stack     at EventEmitter.<anonymous> (/home/sheha/.virtualenvs/amerit-nuevo/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
126448 verbose stack     at emitTwo (events.js:106:13)
126448 verbose stack     at EventEmitter.emit (events.js:191:7)
126448 verbose stack     at ChildProcess.<anonymous> (/home/sheha/.virtualenvs/amerit-nuevo/lib/node_modules/npm/lib/utils/spawn.js:24:14)
126448 verbose stack     at emitTwo (events.js:106:13)
126448 verbose stack     at ChildProcess.emit (events.js:191:7)
126448 verbose stack     at maybeClose (internal/child_process.js:850:16)
126448 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
126449 verbose pkgid node-sass@3.4.2
126450 verbose cwd /home/sheha/Code/reposAmerit/amerit-nuevo/client
126451 error Linux 4.4.9-1-MANJARO
126452 error argv "/home/sheha/.virtualenvs/amerit-nuevo/bin/node" "/home/sheha/.virtualenvs/amerit-nuevo/bin/npm" "install" "--loglevel" "error"
126453 error node v6.1.0
126454 error npm  v3.8.6
126455 error code ELIFECYCLE
126456 error node-sass@3.4.2 postinstall: `node scripts/build.js`
126456 error Exit status 1
126457 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
126457 error Make sure you have the latest version of node.js and npm installed.
126457 error If you do, this is most likely a problem with the node-sass package,
126457 error not with npm itself.
126457 error Tell the author that this fails on your system:
126457 error     node scripts/build.js
126457 error You can get information on how to open an issue for this project with:
126457 error     npm bugs node-sass
126457 error Or if that isn't available, you can get their info via:
126457 error     npm owner ls node-sass
126457 error There is likely additional logging output above.
126458 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
Node 6 is only supported with node-sass 3.7

**Comment by trisquel87** [comment]
I have the same problem in node node v4.2.1: 
https://github.com/sass/node-sass/issues/1581

**Comment by trisquel87** [comment]
@nschonni I have the same problem in node 4.2.1:
[](https://github.com/sass/node-sass/issues/1581)

**Comment by lougreenwood** [comment]
I have this problem with node 6.9.2 package from Dockerhub

```
npm ERR! Linux 4.4.27-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/ember/npm-debug.log
```

**Comment by bansanguy** [comment]
Any luck on this issue??

**Comment by flyingfish2016** [comment]
I had same issue today with gulpfile.  Guess my gulp-sass is too old for the lastest nodejs. 

I change the require('gulp-sass') to use require('node-sass') in the end to workaround the issue.

**Comment by lubkoKuzenko** [comment]
update package.json

"node-sass": "^4.5.2",
"sass-loader": "^6.0.3",

**Comment by shamank** [comment]
It's because of node support. I've installed nvm [https://github.com/creationix/nvm](url) `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash` and installed a version I thought it would work (by checking latest commits in my project) like this: `nvm install v4.8.2`. Try with v4.x. I'm not sure it will work with some version >= 6.

**Comment by priyaprabhu** [comment]
Uninstall the node if it is V6. Install node V8.x
Remove node_modules and npm install. This resolved the issue

**Comment by bghanchi** [comment]
i have proble with node v8.9.4
