### ISSUE TITLE
Not able to install node-sass on ubuntu

### ISSUE THREAD

**Issue by thenaughtychild** [sass/node-sass#1541]
I am not able to install node-sass using npm on my 64 bit ubuntu 14.04 LTS machine.

This is the error that I get:

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/ionic/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/ionic/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/ionic/node_modules/node-sass
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mayank/Documents/ionFullApp_1.3.0/npm-debug.log
npm ERR! code 1

[npm-debug.log](https://gist.github.com/thenaughtychild/0c887a488c863cd051325686be4bcb3f)

**Comment by xzyfer** [comment]
Node 6 is only supported in v3.7.0 and up.

**Comment by thenaughtychild** [comment]
Thanks. In that case, could you also tell me which version of nodejs to use?

**Comment by xzyfer** [comment]
Check the supported version matrix on the Github release for your version.

**Comment by thenaughtychild** [comment]
I have updated my node-sass to v3.7.0 but still getting the same error. I
updated mu npm cache and tried too.


Regards,

*Mayank Goel*
Core Member
Department of Visual Media
BITS Pilani
Mob : +91 97 835 77603
Email : f2014768@pilani.bits-pilani.ac.in
<https://in.linkedin.com/in/mayank-goel-636121b0>

**Comment by xzyfer** [comment]
Our contributing documentation clearly describes how to file an issue with insulations. Please read the documentation.
