### ISSUE TITLE
Not working with shrinkpack

### ISSUE THREAD

**Issue by mlarcher** [sass/node-sass#1542]
We're trying to make use of https://github.com/JamieMason/shrinkpack to deploy node_modules on a restricted box we can't tweak. All modules install correctly from the embedded tar.gz, except node-sass as it needs the network to build in the postinstall phase (cf https://github.com/sass/node-sass/blob/master/scripts/build.js#L79 ). Would it be possible not to rely on a network connection when building the module ?

**Comment by xzyfer** [comment]
This is covered in the readme - https://github.com/sass/node-sass#binary-configuration-parameters
