### ISSUE TITLE
Installation is too slow and blocked sometimes

### ISSUE THREAD

**Issue by creeperyang** [sass/node-sass#1544]
When I run `npm i node-sass`,  probability of a block:

```bash
> node-sass@3.7.0 install /Users/creeper/work/projects/SugarDevelop/node_modules/node-sass
> node scripts/install.js
```

It could be blocked here for a long time, and never go through. 😂

**Comment by xzyfer** [comment]
There is nothing to do here, we can't make the internet faster for you. 
We document [how to load the binaries from an alternate location](https://github.com/sass/node-sass#binary-configuration-parameters) if that's what you want.

**Comment by creeperyang** [comment]
@xzyfer thanks for your reply. 

Maybe it's better to tell user that the installation shell is downloading a binary. If not, it's more like a problem with installation shell itself.

```bash
> node-sass@3.7.0 install /Users/creeper/work/projects/SugarDevelop/node_modules/node-sass
> node scripts/install.js

# tell user it's downloading something
download sass binary...
```

**Comment by xzyfer** [comment]
That's s good point. We do say we've downloaded a file but it happens after
the download.

**Comment by zcoding** [comment]
简直不能忍了，连个进度条都没有

**Comment by creeperyang** [comment]
@zcoding An alternative:

```bash
npm i -g cnpm
cnpm i node-sass #cnpm will proxy the downloading
```

**Comment by xzyfer** [comment]
We use npm's proxy configuration if you set it.

**Comment by jirengu** [comment]
```
yarn add node-sass-install
```
This code will help.
