### ISSUE TITLE
Error: The `libsass` binding was not found

### ISSUE THREAD

**Issue by theofidry** [sass/node-sass#1548]
Hi,

I've seen this issue a couple of times already, but none of the solution worked.

I'm trying to run a gulp script on Travis. My dependencies are installed with a shrinkwrap and I do a rebuild right after the `npm install`. However I still get this error:

```
node_modules/gulp/bin/gulp.js build --env=prod
[10:56:29] Requiring external module babel-register
/home/travis/build/my/project/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
          ^
Error: The `libsass` binding was not found in /home/travis/build/my/project/node_modules/node-sass/vendor/linux-x64-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/travis/build/my/project/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/travis/build/my/project/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/my/project/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/my/project/node_modules/gulp-sass/index.js:186:21)
```

When doing `npm rebuild`, here's the stack I get for the `node-sass` part:

```
> node-sass@3.4.2 install /home/travis/build/my/project/node_modules/node-sass
> node scripts/install.js
> node-sass@3.4.2 postinstall /home/travis/build/my/project/node_modules/node-sass
> node scripts/build.js
` /home/travis/build/my/project/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
npm WARN prefer global node-gyp@3.2.1 should be installed with -g
```

(everything looks fine saving a warning).

Travis build specs:

- Ubuntu 12.04.5 LTS
- node 4.2.4
- npm 3.3.9

**Comment by xzyfer** [comment]
>Error: The `libsass` binding was not found in /home/travis/build/my/project/node_modules/node-sass/vendor/linux-x64-11/binding.node

The `linux-x64-11` tells me you're using Node 0.10.x.

>/home/travis/build/my/project/node_modules/node-sass/vendor/linux-x64-46/binding.node

The `linux-x64-46` tells me you're now using Node 4.x.

***

You're getting this error because you're running `npm install` with Node X. 
You're then running `gulp build` with Node 0.10. 

>This usually happens because your node version has changed.

This error is because you did not fetch the appropriate binding when you changed versions. This is what `npm rebuild node-sass` does for you.

***

For some reason your environment has multiple version of Node installed and you're switching versions without fetching the required binary. Hope this helps you debug your environment.

**Comment by theofidry** [comment]
Ha indeed. Looks like Travis scripts a run in brand new sessions so I have to resource nvm and reset the version of node used. Thanks for the help!

**Comment by barischj** [comment]
For any people with the same issue in the future this gave me a fix:
http://austinpray.com/ops/2015/09/20/change-travis-node-version.html

For my use case a few changes such as `- TRAVIS_NODE_VERSION="7"`.
