### ISSUE TITLE
Using @each directive for color array

### ISSUE THREAD

**Issue by bastengao** [sass/node-sass#1550]
I have a file util.scss 
```
// 72 line below, very similar with the official documentation http://sass-lang.com/documentation/file.SASS_REFERENCE.html#each-directive
@each $color in red, blue, green, gray, white, black {
  .#{"" + $color} {
    color: $color;
  }

  .bg-#{"" + $color} {
    background-color: $color;
  }
}
...
```

I use node-sass(3.7.0) through gulp-sass. Print these error when compile.

```

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: util.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:
       	util.scss:72
        on line 72 of util.scss
>>   .#{"" + $color} {
   --^

    at options.error (/Users/basten/dev/web-projects/util.css/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:271:32)
```

**Comment by xzyfer** [comment]
Sounds like you have a bug some where in your code. The error is likely due to incorrectly using `&` somewhere above this `@each`. Please confirm your code works with the offical Sass compiler. You can do this online with sassmeister.com.

You have not supplied enough working code us to reproduce this issue.

**Comment by bastengao** [comment]
@xzyfer I try using sassmeister.com to compile my sass code, see http://www.sassmeister.com/gist/c98d2dec48b7c49d4b9343295b5e5475. It's ok.

**Comment by xzyfer** [comment]
It also works fine when using LibSass 3.3.6 as you can see sassmeister.com. 

As I said earlier. The error your seeing is caused by the loop, from incorrectly using `&` some where that calls this this loop.
