### ISSUE TITLE
Getting error when trying to install on OS X

### ISSUE THREAD

**Issue by marcozehner** [sass/node-sass#1552]
Hi, 
I get the following output, when trying to install IONIC (sudo npm install - g ionic) on OSX.
I already reinstalled node, npm and cordova and I consistently get this error output (have also tried with the latest Node and npm versions): 

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/npm-debug.log

I also added the npm-debug.log
[npm-debug.log.txt](https://github.com/sass/node-sass/files/264995/npm-debug.log.txt)

Thanx for your support 
Marco

P.S.: Probably I am not the first having this issue - and I spent a lot of time searching for an existing solution but didn't find one yet. So, if you are able to help me find solutions by myself better in the future/or even on this issue - be my guest - but for now I do not have starting points for the search anymore.

**Comment by xzyfer** [comment]
You should never use npm with sudo. This prevents lifecycle scripts from running which many packages rely on. If you're recieving permission errors when doing `npm install -g` you should fix the permission of the directory on your machine.

If you_must_ use sudo with npm you'll need to use the `--unsafe-perms` flag.

```
sudo npm install -g --unsafe-perms ...
```

**Comment by marcozehner** [comment]
Thanks a ton - this actually worked.
