### ISSUE TITLE
Im not sure (but quite sure) if it is node-sass but it was earlier

### ISSUE THREAD

**Issue by landed1** [sass/node-sass#1553]
I got a wanring after I upgraded node past week. I am now on 6.0.0
npm rebuild node-sass
so I ran that and while I now am able to run things I get a lot of white in my cli..
`
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: SassTypes::Map::initPrototype(v8::Local<v8::FunctionTemplate>)
 3: SassTypes::SassValueWrapper<SassTypes::Map>::get_constructor_template()
 4: SassTypes::SassValueWrapper<SassTypes::Map>::get_constructor()
 5: SassTypes::Factory::initExports(v8::Local<v8::Object>)
 6: RegisterModule(v8::Local<v8::Object>)
 7: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 8: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 9: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
10: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
11: 0x158ecdd0961b
12: 0x158ece1747a4`

**Comment by xzyfer** [comment]
You need node-sass@v3.7.0 to use Node 6.
