### ISSUE TITLE
Use node-sass offline with npm 3.9.0

### ISSUE THREAD

**Issue by mriehema** [sass/node-sass#1554]
Hi, I just updated npm to 3.9.0 and using `npm install --cache-min=Infinity` which now works like an offline mode, but I got a problem with node-sass.

### Our setup:
We have a huge java/maven based workspace with some frontend stuff. We use the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) to call node/npm and grunt. This worksapce is build on Linux, MacOSX and Windows. For the frontend we use grunt-sass, which based on node-sass. Every `mvn clean install` will delete the `node_modules` folder and redownload all dependencies needed. This is important for our CI, because its the same way our customer are using the workspace. This works nice as long as you are online.

### Problem:
Some of our consultants and customers want/need to work offline. We couldn't support it yet, because of the problems with the npm cache. Since release 3.9.0 fixed this problem, it works offline with all our modules (if you at least build it once online = cached), but not with node-sass.

### Possible Solution:
1. Put the binaries into the bundle: not an option, like you said in https://github.com/sass/node-sass/issues/654#issuecomment-73477480 to save bandwidth.
2. Configure SASS_BINARY_PATH: not an option for us, because we have to put the binaries into our source workspace and need to configure it. So we have to maintain the binaries for all systems and versions... Sounds like an antipattern.
3. **Download and keep the binaries in a temp folder. Check this location, before redownloading them. This is how [phantomjs ](https://github.com/Medium/phantomjs)is doing it with their binaries. *My favorite solution*. This saves bandwidth and time AND would work offline too!**

Here is an extract of the npm log to show how phantomjs/node-sass are doing it:

phantomJS
```
[INFO] > phantomjs-prebuilt@2.1.7 install C:\workspace\basic-theme\node_modules\phantomjs-prebuilt
[INFO] > node install.js
[INFO]
[INFO] Considering PhantomJS found at C:\Program Files (x86)\phantomjs\bin\phantomjs.EXE
[INFO] Found PhantomJS at C:\Program Files (x86)\phantomjs\bin\phantomjs.EXE ...verifying
[INFO] PhantomJS detected, but wrong version 2.0.0 @ C:\Program Files (x86)\phantomjs\bin\phantomjs.EXE.
[INFO] Download already available at C:\Users\mriehema\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
[INFO] Verified checksum of previously downloaded file
[INFO] Extracting zip contents
[INFO] Removing C:\workspace\basic-theme\node_modules\phantomjs-prebuilt\lib\phantom
[INFO] Copying extracted folder C:\Users\mriehema\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1463578294927\phantomjs-2.1.1-windows -> C:\workspace\basic-theme\node_modules\phantomjs-prebuilt\lib\phantom
[INFO] Writing location.js file
[INFO] Done. Phantomjs binary available at C:\workspace\basic-theme\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
```

node-sass:
```
[INFO] > node-sass@3.7.0 install C:\workspace\basic-theme\node_modules\node-sass

[INFO] > node scripts/install.js
[INFO]
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/win32-x64-46_binding.node":
[ERROR]
[ERROR] getaddrinfo ENOENT github.com:443
[ERROR]
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g.
[ERROR]
[ERROR]       export HTTP_PROXY=http://example.com:1234
[ERROR]
[ERROR] or configure npm proxy via
[ERROR]
[ERROR]       npm config set proxy http://example.com:8080
```

So it would be a very cool feature, if node-sass could support cached/temp binaries to save bandwidth and to support an offline mode! Thx.

**Comment by xzyfer** [comment]
We have multiple ways to support offline binaries documented in the readme - https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by mriehema** [comment]
As fast as you closed this ticket, I think you didn't even read it. :(

**Comment by xzyfer** [comment]
I was able to close this quickly because it has come up multiple times.

I suggest setting up an internal mirror of the binaries so you have all the versions available locally within your firewall. It's the most robust solution and is how most of our enterprise users work around your issue.

I understand what you're asking for but it would complicate what is already a complicated install process.

**Comment by mriehema** [comment]
Please take at least a small look at the install script of [phantomJS](https://github.com/Medium/phantomjs/blob/master/install.js). That doesn't look to complicated to me to be integrated into your [install script](https://github.com/sass/node-sass/blob/master/scripts/install.js).

- [function findSuitableTempDirectory()]( https://github.com/Medium/phantomjs/blob/master/install.js#L104)
- [function downloadPhantomjs()](https://github.com/Medium/phantomjs/blob/master/install.js#L393)

**Comment by phofmann** [comment]
Hi,
no, a internal mirror is not an option. I am travelling a lot. Therefore I am not able to connect to an internal mirror installed within my company. I need to be able to run completely offline as mriehema described above.

**Comment by xzyfer** [comment]
I'm sorry that's not an option for you. There are two options, setup a local http mirror, or a local filesystem mirror.

The later is exactly the same as the solution suggested except that it's manual.

**Comment by politician** [comment]
Do you think you could document how to setup this cache for CircleCI/TravisCI?  I know those aren't your focus, but spending 2 minutes per build building node-sass is pretty gruesome.  

You'd be doing the world a favor in terms of reducing the amount of CO2 produced building node-sass on CI platforms around the planet.  Help the planet!

**Comment by xzyfer** [comment]
You should never have to build binaries. We put in a lot of work to make
sure pre-built binaries are publicly available.

On 23 Nov. 2017 5:00 pm, "politician" <notifications@github.com> wrote:

Do you think you could document how to setup this cache for
CircleCI/TravisCI? I know those aren't your focus, but spending 2 minutes
per build building node-sass is pretty gruesome.

You'd be doing the world a favor in terms of reducing the amount of CO2
produced building node-sass on CI platforms around the planet. Help the
planet!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/1554#issuecomment-346537057>, or mute
the thread

**Comment by michallepicki** [comment]
@xzyfer I can never pull a prebuilt binary. Currently I'm getting:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/linux-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/linux-x64-64_binding.node":
```

**Comment by xzyfer** [comment]
You've updated a major version of Node as soon as it was released. You
should expect some pain.

With that said you just need to update to the latest node-sass.
