### ISSUE TITLE
install fail in windows7

### ISSUE THREAD

**Issue by ymma** [sass/node-sass#1557]
node -v
v4.4.2

npm -v
2.15.0

![1](https://cloud.githubusercontent.com/assets/10007630/15415937/f4668e38-1e78-11e6-8ddc-e6e17c675c2d.png)

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
Trying to read the screenshot it looks like you're running Visual Studio 2005. You need at least 2013 if you want to compile this project from the source code.

**Comment by ymma** [comment]
Thanks,use cnpm can be installed successfully.    : )
