### ISSUE TITLE
Unable to install Ionic because node-sass 3.4.2 post install script failed node 'script/build.js

### ISSUE THREAD

**Issue by mishraanurag** [sass/node-sass#1558]
I have come across this issue whilst installing Ionic framework using NPM 
I have node 6.2.0 and npm 3.8.9 i.e. both latest  installed in my Windows 7 Enterprise 32 bit box.

In this process of Ionic installation , installation failed with following message as in screenshot below.

![image](https://cloud.githubusercontent.com/assets/12631335/15433054/4a0c218e-1e76-11e6-80a5-379770e858e2.png)

**Comment by xzyfer** [comment]
You need at lease node-sass@v3.7.0 for Node 6 supported.

**Comment by mpedersen15** [comment]
@mishraanurag , I had this same issue today and it looks like it was related to using Node v6.x. I uninstalled Node, reinstalled v4.4.4 with [Nodist](https://github.com/marcelklehr/nodist) and then installed ionic successfully through the command line! Hope this helps!
