### ISSUE TITLE
i cann't install ionic and node-sass don't work

### ISSUE THREAD

**Issue by omid-keihani** [sass/node-sass#1559]
$ npm install -g ionic
C:\Users\Omid Keihani\AppData\Roaming\npm\ionic -> C:\Users\Omid Keihani\Ap pData\Roaming\npm\node_modules\ionic\bin\ionic

> node-sass@3.4.2 install C:\Users\Omid Keihani\AppData\Roaming\npm\node_mo dules\ionic\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2 /win32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.4.2 postinstall C:\Users\Omid Keihani\AppData\Roaming\npm\nod e_modules\ionic\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Omid Keihani\AppData\Ro aming\npm\node_modules\ionic\node_modules\node-gyp\bin\node-gyp.js rebuild  --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_lib rary=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Omid Keihani\\AppData\\Roaming\\npm\\node_module s\\ionic\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.2.1
gyp info using node@6.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at F (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at F (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\Omid Keihani\AppData\Roaming\npm \node_modules\ionic\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Omid Keihani\AppData\Roaming\npm\no de_modules\ionic\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set th e PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Omid Keihani\AppData\Roaming\n pm\node_modules\ionic\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\Omid Keihani\AppData\Roaming\npm\node_module s\ionic\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Omid Kei hani\\AppData\\Roaming\\npm\\node_modules\\ionic\\node_modules\\node-gyp\\b in\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags="  "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Omid Keihani\AppData\Roaming\npm\node_modules\ionic\n ode_modules\node-sass
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nod ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.1.0
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/bui ld.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project w ith:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\Git\npm-debug.log
****

**Comment by xzyfer** [comment]
Please search previous issues before creating a new issue. Node 6 requires atleast node-sass@3.7.0.
