### ISSUE TITLE
underscore files being compiled when input directory is inside a directory that starts with . (dot)

### ISSUE THREAD

**Issue by lunalisk** [sass/node-sass#1564]
Sample output:

```
node-sass ./ --output=./css
Rendering Complete, saving .css file...
Wrote CSS to /Users/lluna/project/.mocos/css/_base.css
{
  "message": "Undefined variable: \"$gray-light\".",
  "column": 35,
  "line": 3,
  "file": "/Users/lluna/project/.mocos/scss/helpers/_helpers.scss",
  "status": 1
}
```

When building from a regular directory (e.g. mocos instead of .mocos) it works (doesn't attempt to compile the _ files).

Using node-sass --version:
node-sass	3.2.0	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]

**Comment by xzyfer** [comment]
Thanks for the report @lunalisk. Are you able to create a pull request with a test case for this?

**Comment by lunalisk** [comment]
Sure, I'll try to do it this weekend

**Comment by xzyfer** [comment]
Thanks! It'll be a big help.
