### ISSUE TITLE
node-sass compile error

### ISSUE THREAD

**Issue by freshpassport** [sass/node-sass#1565]
I just run:
npm install hexo-renderer-sass --save

and got a build error:

> node scripts/build.js

Building: /opt/node-v6.2.0-linux-x64/bin/node /home/gonglei/blog/git-blog/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/opt/node-v6.2.0-linux-x64/bin/node',
gyp verb cli   '/home/gonglei/blog/git-blog/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@6.2.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /opt/arm-linux-androideabi-4.9/bin/python2
gyp verb check python version `/opt/arm-linux-androideabi-4.9/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.5\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.2.0
gyp verb command install [ '6.2.0' ]
gyp verb install input version string "6.2.0"
gyp verb install installing version: 6.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.2.0
gyp verb build dir attempting to create "build" dir: /home/gonglei/blog/git-blog/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/gonglei/blog/git-blog/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/gonglei/blog/git-blog/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/gonglei/blog/git-blog/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/gonglei/blog/git-blog/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /opt/arm-linux-androideabi-4.9/bin/python2
gyp info spawn args [ '/home/gonglei/blog/git-blog/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gonglei/blog/git-blog/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gonglei/blog/git-blog/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gonglei/.node-gyp/6.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gonglei/.node-gyp/6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/gonglei/blog/git-blog/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/gonglei/blog/git-blog/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/gonglei/.node-gyp/6.2.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/gonglei/blog/git-blog/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/gonglei/.node-gyp/6.2.0/include/node -I/home/gonglei/.node-gyp/6.2.0/src -I/home/gonglei/.node-gyp/6.2.0/deps/uv/include -I/home/gonglei/.node-gyp/6.2.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:26: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
                          ^
compilation terminated.
binding.target.mk:103: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/gonglei/blog/git-blog/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gonglei/blog/git-blog/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/opt/node-v6.2.0-linux-x64/bin/node" "/home/gonglei/blog/git-blog/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/gonglei/blog/git-blog/node_modules/node-sass
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/opt/node-v6.2.0-linux-x64/bin/node" "/opt/node-v6.2.0-linux-x64/bin/npm" "install" "hexo-renderer-sass" "--save"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gonglei/blog/git-blog/npm-debug.log

How can I fix this error! Thanks.

**Comment by yagudaev** [comment]
also just ran into this error trying to use node-sass with node v6.0.0 on Mac OS X El Capitan

**Comment by xzyfer** [comment]
Please read the contributing documentation on how to file an issue. You have not supplied enough information for us to help you.

**Comment by saper** [comment]
@yaguda Please do not use nvm and try with one node version

**Comment by bensleveritt** [comment]
I'm seeing the same issue with node 6.1.0 (and 6.2.0) and NPM 3.8.6 (and 3.8.9).

**Comment by christophehurpeau** [comment]
@saper: same error, and I don't use nvm

**Comment by christophehurpeau** [comment]
upgrading `gulp-sass` from 2.2.0 to 2.3.1 solved the issue

**Comment by saper** [comment]
@freshpassport one question: why is your python coming from `/opt/arm-linux-androideabi-4.9/bin/python2` ?
