### ISSUE TITLE
Option to remove comments from SASS files

### ISSUE THREAD

**Issue by androdel** [sass/node-sass#1567]
With the current options list it is not possible to build the CSS without all the comments in the SASS files. Could this be added as an extra feature? Thx

**Comment by xzyfer** [comment]
The compressed output mode will remove comments. Unfortunately Sass does not offer the ability to remove comments any other way so there is nothing we can do.

If this is important to you I suggest using a minifier or some other post process.

**Comment by rahulbasu710** [comment]
@xzyfer Nope compressed doesn't remove comments. So I guess needs to be removed from the source-file itself then

**Comment by xakzona** [comment]
Don't remove comments too

**Comment by hassanzohdy** [comment]
For anyone wants to **force** removing comments try this out
```js
sass.render(sassOptions, (error, result) => {
    if (!error) {
        let compiledScssCode = result.css.toString();
        // remove comments from the css outpu
       compiledScssCode = compiledScssCode.replace(/\/\*[^*]*\*+([^\/][^*]*\*+)*\//, '');
    } 
});
```

**Comment by switchur** [comment]
passing in the compressed option does remove comments - both multiline and inline
