### ISSUE TITLE
npm install stops at "node scripts/install.js" without any error

### ISSUE THREAD

**Issue by realbugger** [sass/node-sass#1568]
So I got this really weird issue. I was running `npm install` in Ubuntu 14.04LTS, the installation just stops and exits at `node scripts/install.js` without throwing any error message. However, the installation went through without any problem on my windows 10 machine. Both machine has the same node and npm version (node: v5.9.0, npm: v3.7.3). I even tried different version of node and npm (node v5.11 and npm v3.8) but got the same issue. Has anyone encountered similar issue? 

Here is the screen output, which doesn't really say much. The `WARN`s doesn't seem to be an issue. Even after clear them by updating the packages in my `package.json` file, the issue persists.

```
ubuntu@ubuntu:~/proj$ npm install --unsafe-perm
npm WARN deprecated bootstrap-sass-loader@1.0.10: Replaced by bootstrap-loader. Please upgrade.
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> node-sass@3.7.0 install /home/ubuntu/adxfront/node_modules/node-sass
> node scripts/install.js

ubuntu@ubuntu:~/proj$

```

**Comment by xzyfer** [comment]
I have never seen this. With any luck an npm-debug.log file would have been
created with more information.

**Comment by realbugger** [comment]
It turned out to be a memory issue. The machine that had this issue was a AWS T2.micro instance with 1G memory. Normally 1G should be more than sufficient but in my case I have a long list of packages in my package.json. The installed node_modules folder is more than 160MB.

Later I tried the same installation on my Ubuntu virtual machine, which has exactly the same configuration as the AWS instance except it has 4G memory. And the installation went through with no problem. So I went back to the AWS instance and added 3G of swap space. Now everything is back to normal. This could be an easy problem but not throwing any error makes troubleshooting so much harder.

**Comment by bakura10** [comment]
Hi,

I'm having the exact same issue (it used to work correctly in the past so I don't due if it's due to a new version of a dependency):

```
> node-sass@3.7.0 install /Users/michael/Sites/skeleton/node_modules/node-sass
> node scripts/install.js
```

I've let it go for two full hours, and still stuck here. No errors, no npm-debug file generated... nothing :/. I was on Node 5.6, I've tried to upgrade to Node 6, same issue. Is this issue known?

**Comment by zhangmx** [comment]
@bakura10 

I use vagrant with homestead to make a laravel project, and stuck at node-sass installing.

node version is 5, npm 3.3.6.

After I use `npm install` with 'sudo',this problem had solved.

Maybe you can try `sudo npm install`

**Comment by xzyfer** [comment]
Please don't even use sudo with npm install. It'll will cause all kinds of
permission errors. If you're having permission problems try using the
`--unsafe-perm` flag running npm install.

**Comment by joshuaob** [comment]
This "hanging" issue could be caused by running on a machine without sufficient vcpu OR memory, this was the case for me using an aws ec2 t2 micro instance (1vCPU,1GiB). After switching to an ec2 t2 medium instance (2vCPU, 4GiB), builds ran as expected.
