### ISSUE TITLE
Stop remove empty selectors

### ISSUE THREAD

**Issue by camsong** [sass/node-sass#1569]
Sass will remove empty selectors by default, Is there an options to disable this?

Such as
```sass
.empty {
}
```
will compile to nothing, but I want it compile to `.empty{}` other I got error when using css-modules.

**Comment by xzyfer** [comment]
No there is no way to prevent this. This is not something we can change.

**Comment by camsong** [comment]
@xzyfer Can you please tell more more, we deadly need this.

**Comment by xzyfer** [comment]
It's a core language feature of the Sass language. You can open an issue
with the official Sass compiler - https://github.com/sass/sass. I would
suggest opening an issue with css modules to get this limitation resolved
on their end.

**Comment by camsong** [comment]
ref https://github.com/css-modules/css-modules/issues/140
