### ISSUE TITLE
Bug: Failed to parse package.json

### ISSUE THREAD

**Issue by EmmaRamirez** [sass/node-sass#1571]
Hi, I ran an npm script (npm run css "node-sass styles/sass/ --output styles/css/ --watch --output-style expanded"), and recieved an error pointing out to failing to parse json.

And it specifcally stated their might be an error with package.json

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Emma Ramirez\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'css' ]
2 info using npm@3.8.9
3 info using node@v4.4.3
4 verbose stack Error: Failed to parse json
4 verbose stack Trailing comma in object at 10:3
4 verbose stack   },
4 verbose stack   ^
4 verbose stack     at parseError (C:\Users\Emma Ramirez\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
4 verbose stack     at parseJson (C:\Users\Emma Ramirez\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
4 verbose stack     at C:\Users\Emma Ramirez\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
4 verbose stack     at C:\Users\Emma Ramirez\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd C:\Users\Emma Ramirez\Code\Clickopolis\game
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Emma Ramirez\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "css"
8 error node v4.4.3
9 error npm  v3.8.9
10 error file C:\Users\Emma Ramirez\Code\Clickopolis\game\package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error Trailing comma in object at 10:3
12 error   },
12 error   ^
13 error File: C:\Users\Emma Ramirez\Code\Clickopolis\game\package.json
14 error Failed to parse package.json data.
14 error package.json must be actual JSON, not just JavaScript.
14 error
14 error This is not a bug in npm.
14 error Tell the package author to fix their package.json file. JSON.parse
15 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
> 12 error Trailing comma in object at 10:3

You have a problem in your package.json
