### ISSUE TITLE
node-sass fails in npm 3.8.6

### ISSUE THREAD

**Issue by MythicAngel** [sass/node-sass#1574]
Opening a similar issue like #1484 that fails for npm 3.8.6. Please close it once it has been solved. I have got following error log in **Windows 7** workstation:

> 10509 error node v6.0.0
> 10510 error npm  v3.8.6
> 10511 error code ELIFECYCLE
> 10512 error node-sass@3.7.0 postinstall: `node scripts/build.js`
> 10512 error Exit status 1
> 10513 error Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
> 10513 error Make sure you have the latest version of node.js and npm installed.
> 10513 error If you do, this is most likely a problem with the node-sass package,
> 10513 error not with npm itself.
> 10513 error Tell the author that this fails on your system:
> 10513 error     node scripts/build.js
> 10513 error You can get information on how to open an issue for this project with:
> 10513 error     npm bugs node-sass
> 10513 error Or if that isn't available, you can get their info via:
> 10513 error     npm owner ls node-sass
> 10513 error There is likely additional logging output above.
> 10514 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
