### ISSUE TITLE
npm install fails on Windows when running via ssh remote command

### ISSUE THREAD

**Issue by demisx** [sass/node-sass#1590]
On Windows 2008 R2 server when our build server attempts to run this command via ssh installation of node-sass (see below) fails with this error and the process never exits. Other npm modules install without any problems. 

```
$ ssh host.com -i ~/.ssh/id_rsa  "/cygdrive/c/PROGRA~1/Git/bin/sh -c 'cd /c/projects/webcms2-core; npm install'"

> node-sass@3.7.0 install C:\projects\webcms2-core\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\projects\webcms2-core\node_modules\node-sass\vendor\win32-x64-46\binding.node
Assertion failed: 0, file c:\ws\deps\uv\src\win\req-inl.h, line 217
```

**Comment by nschonni** [comment]
Can you still reproduce this with 3.9.3? there were improvements to the binary downloads since 3.7

**Comment by demisx** [comment]
Seems to be working OK now. Thanks.
