### ISSUE TITLE
Command line examples

### ISSUE THREAD

**Issue by nojaf** [sass/node-sass#1591]
I'm missing some examples in the readme to use node-sass from the command line or npm scripts.
- One input file, one output file
- Multiple files
- Resolve folders
- Watch mode
- ...

**Comment by xzyfer** [comment]
I believe these use cases are mostly covered by the CLI help command

```
node-sass --help
```

This is the best place for these examples. It would be unreasonable to clutter our already over cluttered documentation with every CLI use cases.

**Comment by nojaf** [comment]
Yes indeed you are correct, sorry my bad.
