### ISSUE TITLE
Failed at the node-sass@3.7.0 install script 'node scripts/install.js'.

### ISSUE THREAD

**Issue by Liv1020** [sass/node-sass#1594]
![image](https://cloud.githubusercontent.com/assets/5382358/16070572/1567087a-3309-11e6-833d-25f8f634d467.png)
![image](https://cloud.githubusercontent.com/assets/5382358/16070590/3383aec6-3309-11e6-9fb5-23b3f053a557.png)

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)

**Comment by xzyfer** [comment]
Seems like a permissions issue. Try

```
npm install node-sass --unsafe-perm
```
