### ISSUE TITLE
Watch doesn't detect deletions, and appends entire file to self instead of rewrite

### ISSUE THREAD

**Issue by elliotec** [sass/node-sass#1598]
Using watch, if I delete any code, the compile is not run. I have to delete the entire output file and then save the .scss again in order to work, and even then it takes 2 saves. Then on the second save, it appends the entire css file to itself, if I delete that, the code of the original output is not correct.

**Comment by dmlukichev** [comment]
I have similar behaviour.
Every change appends compile result to the end of the output instead of replacing it.

`node-sass -v` output:
```
node-sass	3.10.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```

**Comment by nschonni** [comment]
Can either of you provide a simple step-by-step reproduction.

**Comment by dmlukichev** [comment]
node-sass is installed globally.

Let source look like this:
```
// src/styles.scss
body { background: #abc; }
```

After that:
`node-sass ./src/styles.scss > ./dist/styles.css -w`

If we change styles.scss a bit in result we get the following:
```
body {
  background: #abc; }

body {
  background: #abcdef; }
```

**Comment by nschonni** [comment]
Do you see that when you don't redirect stdout using `>`?
```console
node-sass -w src/style.scss dest/style.css
```

**Comment by dmlukichev** [comment]
Now I wonder how `>` ended in my code :)
Sorry for wasting your time.

**Comment by nschonni** [comment]
No worries, there is an example that uses that in the README https://github.com/sass/node-sass#usage-1
