### ISSUE TITLE
NSP issues

### ISSUE THREAD

**Issue by TDA** [sass/node-sass#1600]
The current version of node-sass (3.8.0) seems to have a few issues reported by NSP as security issues:
```
minimatch   2.0.10      >=3.0.2   node-sass@3.8.0 > node-gyp@3.3.1 > glob@4.5.3 > minimatch@2.0.10               https://nodesecurity.io/advisories/118 

 minimatch   0.3.0       >=3.0.2   node-sass@3.8.0 > gaze@1.0.0 > globule@0.2.0 > glob@3.2.11 > minimatch@0.3.0   https://nodesecurity.io/advisories/118 

 minimatch   0.2.14      >=3.0.2   node-sass@3.8.0 > gaze@1.0.0 > globule@0.2.0 > minimatch@0.2.14                https://nodesecurity.io/advisories/118 

 minimatch   1.0.0       >=3.0.2   node-sass@3.8.0 > node-gyp@3.3.1 > minimatch@1.0.0                             https://nodesecurity.io/advisories/118 
```
It would be nice if the dependencies were updated :) 
I am willing to put in a PR.

**Comment by xzyfer** [comment]
Open to a PR but the issues appear to be due to transitive dependencies in `node-gyp` and `gaze` which are currently using the latest version of. I expect you'll need to get them to update their dependencies.

**Comment by TDA** [comment]
@xzyfer I will try to get them to update as well, will put in a PR here once they update downstream :) Thank you for your response!

**Comment by TDA** [comment]
@xzyfer This can be closed. Downstream's were fixed and you guys are depending on the latest versions anyway. :)

**Comment by xzyfer** [comment]
Thanks for you work
