### ISSUE TITLE
npm ERR! node-sass@3.8.0 install: `node scripts/install.js`

### ISSUE THREAD

**Issue by imrealashu** [sass/node-sass#1601]
npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/curiosity/npm-debug.log

**Comment by DJW0519** [comment]
I am getting the same error.

**Comment by jamesob** [comment]
+1

**Comment by xzyfer** [comment]
Please read the contributing documentation on how to correctly file an
installation bug. Noone has supplied the information required for us to
help.

The first step is to delete your node_modules and run npm install.

**Comment by adamszymanowski** [comment]
I have the same error, here's the log:
[npm-debug.txt](https://github.com/sass/node-sass/files/328090/npm-debug.txt)

**Comment by kimmings** [comment]
Hello, We're experiencing the same issue now also.
debug files attached.

[npm.txt](https://github.com/sass/node-sass/files/328105/npm.txt)
[npm-debug.txt](https://github.com/sass/node-sass/files/328104/npm-debug.txt)

**Comment by imrealashu** [comment]
I've tried installing with flag `--unsafe-perm` and it worked.

`sudo npm install --unsafe-perm node-sass`

**Comment by kimmings** [comment]
That didn't work for us... and running npm as sudo is not recommended. 
Is anyone even looking into this bug?

**Comment by raskri** [comment]
+1

**Comment by pastorryanhayden** [comment]
I'm getting the same error.  
[npm-debug.txt](https://github.com/sass/node-sass/files/336189/npm-debug.txt)

**Comment by nschonni** [comment]
@kimmings you appear to have a problem with your npm setup. Looks like http://stackoverflow.com/a/31193300/455535 given the first line in the file

**Comment by omahm** [comment]
I had this error on Ubuntu 16.04 due to an install issue with nodejs and the wrong path setting 
To fix it I created the following symlink:  ln -s /usr/bin/nodejs /usr/bin/node
Now it works.

**Comment by pastorryanhayden** [comment]
@omahm Your solution worked like a charm for me.  Thanks.

**Comment by kimmings** [comment]
@nschonni thanks for the tip, however my Path only has `C:\Program Files\nodejs` in it.
node and npm work fine... it will run and install other packages, just won't install node-sass.

**Comment by nschonni** [comment]
@kimmings thanks for testing that. All the logs contain `Failed to exec install script` which means you aren't even hitting our install scripts. If you search other native binary repos (SqlLite, PhantomJs, etc..) this issue always gets bounce back to NPM because it indicates a problem with either the NPM or Node install on the machine. We can't really troubleshoot this since you aren't even executing our code when it bails out.

**Comment by kimmings** [comment]
@nschonni many thanks

**Comment by nickjohngray** [comment]
npm install --unsafe-perm node-sass  Worked for me, thanks imrealashu!
 -s /usr/bin/nodejs /usr/bin/node link already existed  and is needed, thanks omahm!

My setup is: 
all programs are running as root sudo -l  
Ubuntu 16.04 ( with all updates on and gnome desktop ) 
Node:  4.1.2
npm: 3.10.2

I noticed node-sass installed successfully before i updated it on 1/07/20016

**Comment by jimabramson** [comment]
`ln -s /usr/bin/nodejs /usr/bin/node`
fixed this for me (ubuntu:16.04)

**Comment by tolgaek** [comment]
Experiencing this issue on a centos box (node is accessible) while deploying through Amazon's Beanstalk

**Comment by fmagrosoto** [comment]
@omahm Thanks... that symlink works on me!!!

**Comment by Andrew-Dyachenko** [comment]
Symlink WORKS!

**Comment by mphj** [comment]
Symlink works for me too, Thanks alot

**Comment by WolfAtNight** [comment]
can someone help me? i get these error messages
npm WARN enoent ENOENT: no such file or directory, open '/home/anton/package.json'
npm WARN anton No description
npm WARN anton No repository field.
npm WARN anton No README data
npm WARN anton No license field.

i am using ubuntu budgie if that changes some things up
i already tried every help given in this forum

**Comment by WolfAtNight** [comment]
nevermind guys i just realized my stupid foult....

**Comment by DonMacorli** [comment]
@WolfAtNight what was your solution? I got the same errors messages that you got after trying to install it.

**Comment by ahmed32ali** [comment]
1- symlink: ln -s /usr/bin/nodejs /usr/bin/node 
Will work just run this command and 
2- then run "npm install gulp-sass " and it will work.

**Comment by dwd** [comment]
You can also, on Ubuntu/Debian, do:

`sudo apt-get install nodejs-legacy`

And then all this stuff will work fine.

**Comment by fabricelepro** [comment]
Hi 
`npm cache clean --force`
Work for me

**Comment by jskrnbindra** [comment]
Had the same problem, turned out I had kept my project at ~/<folder name> in sudo. 
Moving it to a non-sudo user worked for me.

I can't say why root/~/<folder name> couldn't install node-sass but <username>/~/<folder name> worked as expected.
