### ISSUE TITLE
Test cases failures ( npm test ) on powepc

### ISSUE THREAD

**Issue by ghatwala** [sass/node-sass#1602]
Hi All,

 I am part of team officially porting node-sass on power-pc ( ppc64le - Ubuntu/Rhel ) . I am getting test case failures while trying out the test case on both ubuntu/rhel using below..
```
$ git clone https://github.com/sass/node-sass.git && cd node-sass
$ git submodule update --init --recursive
$ npm install
$ node scripts/build -f
$ npm test
```
My set up details are as below ( ubuntu/rhel )
```
[root@p006vm11 ~]# lscpu
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             16
NUMA node(s):          1
Model:                 IBM pSeries (emulated by qemu)
L1d cache:             64K
L1i cache:             32K
NUMA node0 CPU(s):     0-15
```
node version details
```
jenkins@fcbcd185e28f:~$ node --version
v6.2.1
jenkins@fcbcd185e28f:~$ npm --version
3.9.3
```
Attaching both error logs for ubuntu/rhel .

Any pointers on resolve the test case failures. ?
[node-sass-rhel.txt](https://github.com/sass/node-sass/files/325107/node-sass-rhel.txt)
[node-sass-ubuntu.txt](https://github.com/sass/node-sass/files/325108/node-sass-ubuntu.txt)

**Comment by ghatwala** [comment]
Error log snippet , missed in above post 
```
$ npm test
1165 passing (16s)
  7 pending
  2 failing

  1) api binding missing error should be useful:
     Error: Node Sass does not yet support your current environment: Unsupported platform (Windows) Unsupported architecture (ppc64) with Node.js 6.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.8.0
      at Object.<anonymous> (lib/index.js:13:11)
      at require (internal/module.js:20:19)
      at test/api.js:1807:24
      at _tryBlock (assert.js:318:5)
      at _throws (assert.js:337:12)
      at Function.assert.throws (assert.js:367:3)
      at Context.<anonymous> (test/api.js:1806:16)

  2) api binding missing error should list currently installed bindings:
     Error: Node Sass does not yet support your current environment: Unsupported platform (Windows) Unsupported architecture (ppc64) with Node.js 6.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.8.0
      at Object.<anonymous> (lib/index.js:13:11)
      at require (internal/module.js:20:19)
      at test/api.js:1814:24
      at _tryBlock (assert.js:318:5)
      at _throws (assert.js:337:12)
      at Function.assert.throws (assert.js:367:3)
      at Context.<anonymous> (test/api.js:1813:16)



npm ERR! Test failed.  See above for more details.
Build step 'Execute shell' marked build as failure
```

**Comment by xzyfer** [comment]
@ghatwala on the bright side, these failures aren't anything to worry to about. Unfortunately I'm not completely sure how to go about working around it atm. 

We maintain a whitelist of supported environments so we can provide useful errors to users having installation issues. These specs could maybe be smarter.

I'd love to talk more about what you're doing seeing if we could move it upstream, if you could jump into our slack that'd be great - https://libsass-slack.herokuapp.com/

**Comment by ghatwala** [comment]
@xzyfer -  Thanks for the quick reply .I understand that these test case failures are not critical , however since we are officially porting package to ppc64le , we would expect the build + test cases succeed .

I have joined your slack , having known that "ppc64le" is not supported , i would want to know the way ahead on how to enable the same ( or adding new arch ) . Let me know if they are any steps to adding a new arch type to this code.

**Comment by xzyfer** [comment]
@ghatwala depending on the scope of changes required supporting a new environment can be quite straightforward. The minimum requirement is that someone from the community come on board to take on responsibility of maintaining support for that environment.

This involves organising or maintaining
- CI
- PRs / issues
- Building release binaries.

We would prefer these be as automated as possible.

**Comment by ghatwala** [comment]
@xzyfer - if adding new environment can be quite straightforward  , please do let me know which files will need changes/what changes , i can try this if it works on my ppc64le environment. 

Please do share more information about support to new arch/environment

**Comment by xzyfer** [comment]
Resolved via Slack.

**Comment by ghatwala** [comment]
@xzyfer : Thanks for all your help , should i upload the changes to the main branch ?

**Comment by xzyfer** [comment]
Sure thing. If you could open a PR so I can see the changes that'd be great. As discussed we wouldn't merge the PR at this time but I'm curious as to what was involved.

**Comment by ghatwala** [comment]
@xzyfer - have raised a PR as above
