### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by 2bdkid** [sass/node-sass#1609]
Node-sass is installing with mean.js applications. I'm running on a Raspberry Pi 2

Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 4.x

**Comment by xzyfer** [comment]
Related #1602.

As the message states we do not currently support the arm architecture. However this error should not prevent node-sass from attempting to compile locally. Can you confirm whether node-sass builds on arm.

```
npm rebuild node-sass
```

**Comment by 2bdkid** [comment]
Ok rebuilding node-sass worked fine.

**Comment by mrtcmn** [comment]
For future google searchers: please check your node-sass version. Try latest version.
