### ISSUE TITLE
node-sass@3.4.2 need linux-x64-48_binding.node

### ISSUE THREAD

**Issue by sasha6806** [sass/node-sass#1612]
>node-sass@3.4.2 install /root/angular-cn/node-modules/node-sass
>node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/linux-x64-48_binding.node"

HTTP error 404 Not Found

In fact, there has no linux-x64-48_binding.node in repo really. Only has linux-x64-47_binding.node.

**Comment by xzyfer** [comment]
That version doesn't support node 6. Upgrade to 3.8.0 or downgrade to node
5.
