### ISSUE TITLE
Add option to debounce watch

### ISSUE THREAD

**Issue by OliverJAsh** [sass/node-sass#1614]
When switching between git branches, node-sass’ watch seems to trigger before the checkout has complete, causing the build to fail.

Is it possible to debounce the watch to prevent this from happening?

**Comment by OliverJAsh** [comment]
https://github.com/sass/node-sass/pull/1615

**Comment by saper** [comment]
Closing per https://github.com/sass/node-sass/pull/1615#issuecomment-229325086
