### ISSUE TITLE
include-path does not work

### ISSUE THREAD

**Issue by fredericpfisterer** [sass/node-sass#1616]
I'm doing : 

`node-sass --include-path ./bower_components/normalize-scss/sass/ assets/scss/main.scss test.css`

and not getting the css from the includes related to bower_components/normalize-scss/sass/.

**Comment by xzyfer** [comment]
Include paths are just locations for your @imports to look into. You need
to @import the things you want from that directory. They don't get
magically added.

**Comment by fredericpfisterer** [comment]
Obviously I know that. 

I have @import 'bower'; in my main.scss and @import "../../bower_components/normalize-scss/sass/_normalize.scss"; in my _bower.css.

**Comment by xzyfer** [comment]
Apologies it was not obvious because you didn't provide any sample code
that would help be debug your issue.

**Comment by xzyfer** [comment]
The current directory is not implicitly added to your load paths. You'll
need --load-path=.

**Comment by fredericpfisterer** [comment]
Thanks for your answer but I can't find any documentation about --load-path. How am I supposed to use it and what does it do ?

**Comment by fredericpfisterer** [comment]
nevermind, I fixed it. It is because normalize scss needs `@include normalize();`
