### ISSUE TITLE
How to output two file in one CLI command

### ISSUE THREAD

**Issue by Yimiprod** [sass/node-sass#1618]
Is it possible, with the CLI, to output two files in one line, something like that :

`node-sass  --include-path src/scss src/scss/main.scss --output-style expanded dist/css/main.css  --output-style compressed dist/css/main.min.css`

That way we can get a non minified and a minified version without having to perform two builds.

**Comment by xzyfer** [comment]
@Yimiprod no this is not possible. Under the covers it'd still be executing node-sass twice.

This is not something we plan to add. IMHO this makes the CLI significantly more complicated whilst adding very little value.
