### ISSUE TITLE
Import of whole folder doesn't works.

### ISSUE THREAD

**Issue by inferusvv** [sass/node-sass#1620]
Looks like ruby sass support imports like:

`@import "_generated/*";`

And node-sass don't. It will be very comfortable, if your project structure have no dependency between each file in folder and all files can be included in any order.

**Comment by xzyfer** [comment]
Sorry but Ruby does not support glob style imports and has refused to
support them many times. A plugin is required to make it work. You can
probably find similar plugins for Node Sass.
