### ISSUE TITLE
3.8.0 breaks submit button on React

### ISSUE THREAD

**Issue by h8rry** [sass/node-sass#1622]
**Before**

![screen shot 2016-07-03 at 4 13 05 pm](https://cloud.githubusercontent.com/assets/1697380/16544454/20fbd4ac-4139-11e6-8b36-1ae04ce524f7.png)
![screen shot 2016-07-03 at 4 13 10 pm](https://cloud.githubusercontent.com/assets/1697380/16544455/21342be0-4139-11e6-811d-0b89b6db132c.png)

**After**

![screen shot 2016-07-03 at 4 12 19 pm](https://cloud.githubusercontent.com/assets/1697380/16544456/3236f63e-4139-11e6-9982-1481da8b102c.png)
![screen shot 2016-07-03 at 4 11 15 pm](https://cloud.githubusercontent.com/assets/1697380/16544457/32371556-4139-11e6-8c71-aba384cdaeb5.png)

Attributes `value` and `name` with empty values have been added to the submit button in a form.

**Comment by xzyfer** [comment]
Sass cannot change the dom. This is not a Sass issue.
