### ISSUE TITLE
Placeholder illegal nesting not generating error

### ISSUE THREAD

**Issue by Camzilla** [sass/node-sass#1625]
Hey, was writing some scss and upon saving there was no reaction from the compiler, also no error was displayed (running on --silent). Running without --silent does give a regular npm error but no clues whatsoever.
Tested the code at sassmeister and turned out i had an illegal nesting error that wasn't being displayed.

    %block-wysiwyg {
        ol, ul { padding-left: 17px 
            li { font-size: 1.6em; list-style-type: none; position: relative;
                &:before { content: " "; width: 7px; height: 7px; border-radius: 100%; }
            }
        }
    }

Apparently `Illegal nesting: Only properties may be nested beneath properties.` How come this isnt being displayed as an error?

**Comment by nschonni** [comment]
I think you're having an issue with some other wrapper (Gulp/Grunt?) since `silent` isn't an option in this library and running node-sass from the commanline also produces the following error
```json
{
  "formatted": "Error: Illegal nesting: Only properties may be nested beneath properties.\n        on line 3 of test.scss\n>>         li { font-size: 1.6em; list-style-type: none; position: relative;\n   ----------^\n",
  "message": "Illegal nesting: Only properties may be nested beneath properties.",
  "column": 11,
  "line": 3,
  "file": "/Users/nschonni/Documents/github/test/test.scss",
  "status": 1
}
```
