### ISSUE TITLE
How to get list of variables and values after compile?

### ISSUE THREAD

**Issue by ivansky** [sass/node-sass#1626]
I need to find and check some variables from context.
I am not found an answer :(

Please, could you help me?

**Comment by xzyfer** [comment]
I don't understand what you mean. Please provide a code sample and what you expect to see.

**Comment by ivansky** [comment]
SCSS example source:
```scss
$is-some: true;
$white-color: #fff;
$black-color: darken($white-color, 100%);
$shamrock-green-color: #096;
```

JS:
```js
const result = sass.renderSync({
    data: scssFileContent
});

result.context.variables['shamrock-green-color']; // #096
result.context.variables['black-color']; // #000
result.context.variables['is-some']; // true
```

**Comment by ivansky** [comment]
Do you understand my example? 
There is a way to resolve this issue?

**Comment by xzyfer** [comment]
This is not possible. You can however define your variables in javascript or JSON and use an importer to load them into scss. This will not get you calculated or changed values.
