### ISSUE TITLE
Installing node-sass with electron

### ISSUE THREAD

**Issue by davej** [sass/node-sass#1628]
I am able to install node-sass with Electron no problem, until it comes to testing the binary.

https://github.com/sass/node-sass/blob/master/scripts/build.js#L206
```js
require('../').renderSync({
  data: 's { a: ss }'
});
```

Everything seems to execute correctly but `binding.renderSync(options)` returns false:

https://github.com/sass/node-sass/blob/master/lib/index.js#L406
```js
status = binding.renderSync(options) // status === false
```

This is unusual because the `options.result` object seems to be correct and it does not contain an error object:

```js
console.log(options.result);

// {
//    stats: { entry: 'data', start: 1468329066780, includedFiles: [] },
//    css: <Buffer 73 20 7b 0a 20 20 61 3a 20 73 73 3b 20 7d 0a>
// }
```
Nevertheless the binary test fails because `status` is false so `node-sass` throws an error.

I know that this may be outside of the scope of `node-sass` but hopefully somebody can point me in the right direction as to why the `renderSync` function might be returning `false` even though all of the returned `options` data seems to be correct.

**Comment by davej** [comment]
@sedwards2009 I believe that's for windows only. I can get `node-sass` to work ok generally under Electron in OS X, it's only `renderSync` that doesn't work.

For example, the following works ok:

```js
sass.render({
  file: 'test.scss',
  outputStyle: 'compressed'
}, (err, result) => console.log(err, result))
```

**Comment by saper** [comment]
@davej can you try running `npm test`? I am especially interested in lowlevel.js tests

**Comment by davej** [comment]
@saper: This bug was related to the fact that I was using the prebuilt version of node-sass with Electron. Basically although Electron uses Node 6, it uses a different version of V8 so the prebuilt binaries don't work.

See here for similar issues: https://github.com/electron/electron/issues/6318 & https://github.com/electron/electron/issues/5851

I'm closing this as it's not really a node-sass issue.

**Comment by saper** [comment]
Yeah, using 48 node API identifier while being incompatible is a nasty thing.
