### ISSUE TITLE
missing binding error

### ISSUE THREAD

**Issue by joeaudette** [sass/node-sass#1633]
I'm getting this error:

Node Sass could not find a binding for your current environment: Windows 32-bit with Node.js 5.x
Found bindings for the following environments:
  - Windows 32-bit with Node 0.12.x
This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous>     (C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:15:11)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)

so I run the suggested command:

C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com>npm rebuild node-sass

> node-sass@3.8.0 install C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

> node-sass@3.8.0 postinstall C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com\node_modules\gulp-sass\node_modules\node-s
ass
> node scripts/build.js

"C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-14\bind
ing.node" exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.8.0 C:\_joe\__projects\_joeaudettecom\joeaudette.com\src\joeaudette.com\node_modules\gulp-sass\node_modules\node-sass

but the error remains
I'm using Visual Studio 2015 if that matters, I'm really trying to use gulp-sass which I guess depends on node-sass
my OS is Windows 10 64 bit which makes me think it is using the wrong binding
I thought maybe I should download a 64 bit windows version but when I look at the release downloads there are so many of them and I have no clue which one I should try or if I should try to use one of those at all.

any help or insights appreciated

**Comment by joeaudette** [comment]
after much googling I think the problem was I ran npm install from the command prompt rather than from visual studio package manager console. after deleting the node_modules folder and letting visual studio restore them I got a different error about gulp-sourcemaps, then I ran npm install gulp-sourcemaps from the visual studio package manager console and now there are no more errors

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#using-node-sass-with-visual-studio-2015-task-runner
