### ISSUE TITLE
Binaries on private npm

### ISSUE THREAD

**Issue by amiramw** [sass/node-sass#1635]
When running node-sass on corporate release build I'm getting error fetching binaries from https://github.com/sass/node-sass/releases/. This is because it is not allowed to access the internet in our release build.
Is it possible to publish these binaries in public npm so I can request them to be copied to our private npm?

**Comment by xzyfer** [comment]
Unfortunately this is not possible at the moment. We would need to publish
every binary. This would mean users are downloading almost 100mbs every
time they install node sass.

If you look at the bottom of the read me there are configuration variables
you can set for alternate binary download locations. This way you can
mirror the release binaries on a local server.

**Comment by amiramw** [comment]
Thanks for the quick response.
Does it make sense to publish the binaries in a separate repo to npm so they are there if needed by private npms but not downloaded for regular sass installations?
As far as I can see there is already a separate repo https://github.com/sass/node-sass-binaries.

**Comment by xzyfer** [comment]
I'm not sure how npm will deal with a big set of binaries. I'll reach out to some npm folk for some advice. Using s3 or github releases is the standard way at the moment.

**Comment by saper** [comment]
You can use --sass-binary-site or --sass-binary-path to use some other location for the precompiled binary. 

To compile FreeBSD binaries I have also a strict regime which does not allow me to do any networking during the build phase. https://github.com/saper/ports-exp/blob/master/textproc/node-sass/Makefile for BSD make fetches everything from npm in the fetch phase, the build phase does not need to download anything. For that however you need a working C++11 compiler.

**Comment by mriehema** [comment]
Sounds almost similiar to #1554 (Being offline vs. restricted internet access).

**Comment by henriklynggaard** [comment]
Can someone explain why node-sass doesn't (and/or can't) just be installed like normal NPM modules and respect the npm config registry setting?

What makes this module special?

**Comment by saper** [comment]
@henriklynggaard node-sass contains binary component written in C++ that enhances what node can do. Those functions cannot be written in JavaScript. Normally npm would always require you to have a working C++ compiler and it would build the module from your from source during `npm install`.

To make things easier for most users (who may not have a working C++11 compiler handy, for example) and also to save time our project provides precompiled binaries (see https://github.com/sass/node-sass-binaries) that will be downloaded if possible. All this download processing is coded by us (https://github.com/sass/node-sass/blob/master/scripts/install.js) and has nothing to do with the way how npm normally downloads its packages from the npm registry. Our binaries are downloaded directly from GitHub.

It would be nice to have a nice unified experience with npm, but this is not always possible. Examples: https://github.com/sass/node-sass/pull/1806 https://github.com/sass/node-sass/pull/1492.

You can always download the binary yourself or disable binary download and build from source yourself.

**Comment by xzyfer** [comment]
>respect the npm config registry setting?

@henriklynggaard node-sass does respect npm config. However we cannot store the compiled binaries in npm so we need to download them from somewhere.

**Comment by xzyfer** [comment]
I've had a chat with some folk and storing 100mbs of binaries in npm is not reasonable. We could store each binary as it's own package but that is too much of a maintenance burden. 

We get over 2.5M monthly downloads with only a handful of issues, due to unconventional environments. What we have is about as good as we can get it given the size of our team. We have documented options that should allow node-sass to be installed practically everywhere.
