### ISSUE TITLE
Is the exposed JS binding API documented anywhere?

### ISSUE THREAD

**Issue by EdwardDrapkin** [sass/node-sass#1636]
Hey guys,

I'm kind of a masochist and was trying to get my webpack setup running on top of the JVM instead of v8, and I ran into a wall where I can't obviously compile Node.JS modules for the JVM.  I'm willing to write a 'pass through' adapter that makes calls to sassc (or just sass) and conforms to the same API as the actual libsass bindings, if such a thing is possible, but I don't know what the binding API is supposed to be.

Can you help me out?

Thanks!

**Comment by nschonni** [comment]
This is what's generated off the JSDocs https://inch-ci.org/github/sass/node-sass
The native binding would be in https://github.com/sass/node-sass/blob/master/src/binding.cpp

**Comment by saper** [comment]
@EdwardDrapkin what you mght try to do is to pług libsass using the Java Native Interface (JNI). This way you can use all the power of libsass, even including custom importers. Beware of a very strange memory management of libsass.

**Comment by xzyfer** [comment]
I don't see anything we can do resolve this issue. Closing unless there is something actionable we can do.
