### ISSUE TITLE
ERROR in %1 is not a valid Win32 application?

### ISSUE THREAD

**Issue by Thstone37** [sass/node-sass#1638]
I use webpack,and also has installed sass-loader node-sass;when I webpack,Command line show this error,it confused me serval days,here is the command line log:

> ERROR in %1 is not a valid Win32 application

thanks for your anwser!

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)

**Comment by IsmaelKP** [comment]
did work for me thank you for the tip. the binding.node file was corrupted I guess

**Comment by knowngate** [comment]
for me tooo :)

**Comment by knowngate** [comment]
Thanks alot Sir
