### ISSUE TITLE
ARM binaries with CI with resin.io

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#1640]
I got an old PI to try out http://resin.io for arm builds. Does this make sense to you @xzyfer? I'll see if I can get it working with ARMv6 on a PI 2B, then pick up a 3 for ARMv7.
Couldn't find a CI that supported ARM CI for open source projects without BYOD 😦

**Comment by xzyfer** [comment]
I'd love to support ARM. I'm not sure I'm following how resin works. Is it still BYOD? 
If so have you looked a buildkite? It's my goto for BYOD CI.

**Comment by saper** [comment]
I was wondering if we shouldn't take a look at the cross-compilation possibilities. Building C++ code will be certainly faster on something else. The only problem left is when (every commit?) an when to run "npm test" on the target platform.

**Comment by nschonni** [comment]
@xzyfer I couldn't see a free tier for buildkite, unless it's buried somewhere.

@saper I think cross compilation on Travis should be fine, but I think being able to run the tests on the architecture before pushing out a release would be helpful

**Comment by xzyfer** [comment]
@nschonni you're correct. We should continue down the path that works for now. Ideally I'd like to eventually moved this to buildkite but no rush.

**Comment by nschonni** [comment]
Closing since I haven't had cycles to get the PI build setup
