### ISSUE TITLE
Npm install failure on Kubuntu

### ISSUE THREAD

**Issue by MkBeeCtrl** [sass/node-sass#1641]
Hello, here the error I keep receiving:

> 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "jshint" "gulp-util" "gulp-sass" "gulp-cssnano" "gulp-autoprefixer" "gulp-sourcemaps" "gulp-jshint" "jshint-stylish" "gulp-uglify" "gulp-concat" "gulp-rename" "gulp-plumber" "gulp-bower" "gulp-babel" "browser-sync"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

> npm

> ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

I can see thath dependency check failed and my system architecture is the source fo the problem. Try to google it but found only few old posts, confirmed not be helpful anymore.

That's why I am contacting you as stated in the terminal output.

**Comment by MkBeeCtrl** [comment]
I tried `npm install --no-optional` with similar effect

**Comment by MkBeeCtrl** [comment]
I've found the solution here: https://github.com/sass/node-sass/issues/1601

On ubuntu 16.04  you have to create symlink, but I dont like doing something when I am not sure what is it for so if you can explain it to me I will much appreciate it.

`ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by nschonni** [comment]
http://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory/26320915
The `node` package was registered a long time ago for something else, so it conflicts unless you use the link workaround. The old wiki page from the nodejs wiki seems to have been eaten from their repo reorg, but it explained this.

**Comment by xzyfer** [comment]
We used to have a work around for this which was removed in 3.5.0. I think
it'll be worth resurrecting. This has come up a couple times a this month.
