### ISSUE TITLE
Give '.min.css' and '.min.css.map' file extension for files compiled with --output-style compressed --source-map true

### ISSUE THREAD

**Issue by kimbaudi** [sass/node-sass#1642]
How would I be able to give a '.min.css' and '.min.css.map' file extension to the css files compiled with options `--output-style compressed` and `--source-map true` respectively? Preferably from the command line? Is this something that is possible? I currently have a npm command line script that will minify the css and create a source map, but I would like to give the minified css file a '.min.css' file extension and the source map file a '.min.css.map' file extension.

`node-sass app/scss/ -o app/css/ --output-style compressed --source-map true`

I'm able to do it using a script using `render()`, but its only limited to one file. What if I have multiple sass files in a directory that I want to compile? Does this mean I have to call `render()` for each of my sass files? Is there a way to pass a directory to `render` callback to compile every sass file in the given directory?

```
var sass = require('node-sass');
var fs = require('fs');

sass.render({
    file: 'app/scss/style.scss',
    outFile: 'app/css/style.min.css',
    sourceMap: true,
    outputStyle: 'compressed'
}, function(error, result) {
        if (error) {
            console.log('error message: ' + error.message);
            console.log('error line number: ' + error.line);
            console.log('error column number: ' + error.column);
            console.log('error status code: ' + error.status);
            console.log('error filename: ' + error.file);
        }
        else {
            fs.writeFile('app/css/style.min.css', result.css, function(err) {
                if (err) {
                    return console.log('error writing css');
                }
                console.log('success writing css');
            });
            fs.writeFile('app/css/style.min.css.map', result.map, function(err) {
                if (err) {
                    return console.log('error writing source map');
                }
                console.log('success writing source map');
            });
        }
});
```

**Comment by xzyfer** [comment]
> Is this something that is possible

No. We do not plan to add this feature. The CLI is already too complicated. You can do this easily with most shells and a simple script.

> Is there a way to pass a directory to render callback

No. You can call render in a loop. That's how grunt-sass and gulp-sass work.
