### ISSUE TITLE
Missing binding win32-ia32-46_binding.node

### ISSUE THREAD

**Issue by cope** [sass/node-sass#1646]
When trying to run Meteor on Windows:
```
=> Errors prevented startup:
While downloading fourseven:scss@3.2.0...:
error: Command failed: C:\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild --no-bin-links --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/win32-ia32-46_binding.node":
HTTP error 404 Not Found
```

**Comment by xzyfer** [comment]
You're using an old version of node-sass that does not support your version of Node. Update to a new node-sass.

**Comment by cope** [comment]
Well, it's not me, it's Meteor. But still, I would like to know if a reference to win32-ia32-46_binding.node is a mistake, or was 46 available before and is somehow removed now?

**Comment by xzyfer** [comment]
Then meteor does not support your version of node. The filename is generated locally during install based on your environment. Your version of node was never supported with node-sass@3.2.0.

**Comment by cope** [comment]
As I understood, Meteor uses it's own version of Node, independent of mine.
Maybe I'm wrong...

**Comment by xzyfer** [comment]
I honestly can't say. All I know is the node being used by npm install is
too new for the version of node-sass being installed.

**Comment by cope** [comment]
I've tracked this issue to `.meteor\packages\materialize_materialize\0.97.7`, as it seems to be the only place that uses fourseven:scss

**Comment by cope** [comment]
I've solved the issue by commenting out `materialize:materialize` from packages, then adding fourseven:scss and meteor started properly, as I expected, since it took the latest version of scss which is 3.8 something. Then I uncommented `materialize:materialize` and crossed my fingers. It worked.
