### ISSUE TITLE
Missing binding android-ia32-48

### ISSUE THREAD

**Issue by kick-the-bucket** [sass/node-sass#1648]
`node-sass@3.8.0 install /data/data/com.termux/files/home/PokemonGo-Map/node_modules/node-sass   > node scripts/install.js
                                                 Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/android-ia32-48_binding.node":                                                                                          HTTP error 404 Not Found`

**Comment by nschonni** [comment]
We don't offer binaries for Android as I don't believe NodeJS supports the platform natively.

**Comment by xzyfer** [comment]
v3.8.0 should have fallen back to a local compilation. Did that not happen @kick-the-bucket?

**Comment by sparkishy** [comment]
With termux application, we can download node js and webpack stuff. But cant download node sass because it doesnt have binary support

**Comment by balazsorban44** [comment]
It would have been great.

**Comment by kjarmicki** [comment]
I'd really like android/termux support too, would be nice since node works there.
Out of curiosity, are there problems with compilation or was it never tried?

**Comment by kick-the-bucket** [comment]
It did fall-back to compilation, but that failed as well due to numerous
unresolved dependancies, which I had to decipher from walls of debug text...

**Comment by xzyfer** [comment]
There a couple issues preventing this.

LibSass currently does not compile on Android. That would need to be fixed.

Neither the LibSass or Node Sass has the expertise to maintain, or triage Android issue.

Neither the LibSass or Node Sass have infrastructure (CI, build servers) to assert compatibility, and prevent regressions.

Without the above there is no way we can provide support for Android. If someone with those skills, expertise, and resources was willing to own that responsibility we happily add them to the team.

**Comment by kjarmicki** [comment]
Fair enough. Thank you for the response
