### ISSUE TITLE
Node-sass errors over LF?

### ISSUE THREAD

**Issue by Alber70g** [sass/node-sass#1650]
A file created on Windows 7 with the following contents result in this error.
Compiled using `node-sass style.sass` and `node-sass --linefeed lf style.sass`
In particular the `0a` Line Feed is problematic. What is wrong with this? Am I missing something?

**File**
```
h1 {
  color: red;
}
```

**File Hex**
```
00000000:  6831 207b 0a20 2063 6f6c 6f72 3a20 7265 643b 0a7d 0a         :h1 {.  color: red;.}.
```

**Error**
```
{
  "formatted": "Error: Invalid CSS after \"h1 {\": expected \"}\", was \"{\"\n        on line 1 of style.sass\n>> h1 { {\n   ----^\n",
  "message": "Invalid CSS after \"h1 {\": expected \"}\", was \"{\"",
  "column": 5,
  "line": 1,
  "file": "c:/other-projects/sass-error/style.sass",
  "status": 1
}
```

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
