### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Linux 64-bit with false

### ISSUE THREAD

**Issue by MRokas** [sass/node-sass#1651]
Using node-sass doesn't seem to work with v6.3.1 node on 64-bit Linux, even though there was a merge to support node v6

```
X@X:~/dev/node/test4$ node --version
v6.3.1
X@X:~/dev/node/test4$ node-sass src/scss/style.scss dist/css/style.css
/usr/lib/node_modules/node-sass/lib/index.js:12
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with false
For more information on which environments are supported please see:
TODO URL
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/lib/index.js:12:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/bin/node-sass:11:12)
    at Module._compile (module.js:541:32)
```

Any other info which I should post?

**Comment by xzyfer** [comment]
We have comprehensive documentation on how to file an issue with useful information.

It looks like you're using an old version of node-sass that came out before Node 6. Update to node-sass@v3.8.0

**Comment by MRokas** [comment]
node_modules/node-sass/package.json:

```
"_from": "node-sass@latest",
"_id": "node-sass@3.8.0",
...
"_resolved": "https://registry.npmjs.org/node-sass/-/node-sass-3.8.0.tgz",
```

I installed it yesterday, and my node is 6 for sure as per:
```
x@x:~/dev/node/test4$ node --version
v6.3.1
```

**Comment by xzyfer** [comment]
As documented, please provide the following

```
npm -v              
node -v
node -p process.versions
node -p process.platform
node -p process.arch
```

**Comment by MRokas** [comment]
```
X@X:~/dev/node/test4$ npm -v  
3.8.6
X@X:~/dev/node/test4$ node -v
v6.3.1
X@X:~/dev/node/test4$ node -p process.versions
{ http_parser: '2.7.0',
  node: '6.3.1',
  v8: '5.0.71.57',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '48',
  openssl: '1.0.2h' }
X@X:~/dev/node/test4$ node -p process.platform
linux
X@X:~/dev/node/test4$ node -p process.arch
x64
```

**Comment by xzyfer** [comment]
This error message is not possible with v3.8.0

>Error: Node Sass does not yet support your current environment: Linux 64-bit with false
>For more information on which environments are supported please see:
>TODO URL

The `TODO URL` was [removed in v3.7.0](https://github.com/sass/node-sass/releases/tag/v3.7.0).

You must have multiple versions of node-sass installed. You can confirm this with

```
npm ls node-sass
```

If you only see one node-sass and it's 3.8.0 then run the following to rebuild the binary

```
npm rebuild node-sass
```

**Comment by MRokas** [comment]
Problem persisted after that, but `npm uninstall node-sass -g && node cache clean && node install node-sass` fixed that. Thanks!

**Comment by xzyfer** [comment]
This means you hand an old global node-sass that was being used instead of your local. In future it's best to never install node-sass (or any npm modules) globally with `-g`.

**Comment by Atulg23** [comment]
Use the following command
npm rebuild node-sass

**Comment by BernardMarieOnzo** [comment]
try npm rebuild node-sass

**Comment by Dean-Foulds** [comment]
I am having this issue and would like to help solve it.  I have run `npm rebuild node-sass` to no avail.

`6.4.0
v10.6.0
{ http_parser: '2.8.0',
  node: '10.6.0',
  v8: '6.7.288.46-node.13',
  uv: '1.21.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h-fips',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
linux
x64`

**Comment by xzyfer** [comment]
Install the latest node-sass

**Comment by Dean-Foulds** [comment]
`
Building: /usr/bin/node10 /usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node10',
gyp verb cli   '/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.6.0
gyp verb command install [ '10.6.0' ]
gyp verb install input version string "10.6.0"
gyp verb install installing version: 10.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.6.0' ]
gyp verb install input version string "10.6.0"
gyp verb install installing version: 10.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.6.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/node-sass/.node-gyp/10.6.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.6.0' ]
gyp verb remove using node-gyp dir: /usr/local/lib/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.6.0
gyp verb remove removing development files for version: 10.6.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.6.0' ]
gyp verb remove using node-gyp dir: /usr/local/lib/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.6.0
gyp verb remove removing development files for version: 10.6.0
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.17.13-1-default
gyp ERR! command "/usr/bin/node10" "/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/node-sass
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-19T06_05_47_388Z-debug.log`

**Comment by Dean-Foulds** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node10',
1 verbose cli   '/usr/bin/npm-default',
1 verbose cli   'rebuild',
1 verbose cli   'node-sass' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 info readInstalled object
5 verbose rebuild path, id [ '/home/dean/code/CarehomeHaven/node_modules/node-sass',
5 verbose rebuild   'node-sass@4.5.0' ]
6 silly rebuild set [ '/home/dean/code/CarehomeHaven/node_modules/node-sass' ]
7 info build /home/dean/code/CarehomeHaven/node_modules/node-sass
8 info lifecycle node-sass@4.5.0~preinstall: node-sass@4.5.0
9 info linkStuff node-sass@4.5.0
10 silly linkStuff node-sass@4.5.0 has /home/dean/code/CarehomeHaven/node_modules as its parent node_modules
11 verbose linkBins [ { 'node-sass': 'bin/node-sass' },
11 verbose linkBins   '/home/dean/code/CarehomeHaven/node_modules/.bin',
11 verbose linkBins   false ]
12 verbose rebuildBundles [ 'cross-spawn' ]
13 info lifecycle node-sass@4.5.0~install: node-sass@4.5.0
14 verbose lifecycle node-sass@4.5.0~install: unsafe-perm in lifecycle false
15 verbose lifecycle node-sass@4.5.0~install: PATH: /usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/node-gyp-bin:/home/dean/code/CarehomeHaven/node_modules/node-sass/node_modules/.bin:/home/dean/code/CarehomeHaven/node_modules/.bin:/usr/sbin:/usr/bin:/sbin:/bin
16 verbose lifecycle node-sass@4.5.0~install: CWD: /home/dean/code/CarehomeHaven/node_modules/node-sass
17 silly lifecycle node-sass@4.5.0~install: Args: [ '-c', 'node scripts/install.js' ]
18 silly lifecycle node-sass@4.5.0~install: Returned: code: 0  signal: null
19 info lifecycle node-sass@4.5.0~postinstall: node-sass@4.5.0
20 verbose lifecycle node-sass@4.5.0~postinstall: unsafe-perm in lifecycle false
21 verbose lifecycle node-sass@4.5.0~postinstall: PATH: /usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/node-gyp-bin:/home/dean/code/CarehomeHaven/node_modules/node-sass/node_modules/.bin:/home/dean/code/CarehomeHaven/node_modules/.bin:/usr/sbin:/usr/bin:/sbin:/bin
22 verbose lifecycle node-sass@4.5.0~postinstall: CWD: /home/dean/code/CarehomeHaven/node_modules/node-sass
23 silly lifecycle node-sass@4.5.0~postinstall: Args: [ '-c', 'node scripts/build.js' ]
24 silly lifecycle node-sass@4.5.0~postinstall: Returned: code: 1  signal: null
25 info lifecycle node-sass@4.5.0~postinstall: Failed to exec postinstall script
26 verbose stack Error: node-sass@4.5.0 postinstall: `node scripts/build.js`
26 verbose stack Exit status 1
26 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/index.js:304:16)
26 verbose stack     at EventEmitter.emit (events.js:182:13)
26 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/lib/spawn.js:55:14)
26 verbose stack     at ChildProcess.emit (events.js:182:13)
26 verbose stack     at maybeClose (internal/child_process.js:961:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
27 verbose pkgid node-sass@4.5.0
28 verbose cwd /home/dean/code/CarehomeHaven
29 verbose Linux 4.17.13-1-default
30 verbose argv "/usr/bin/node10" "/usr/bin/npm-default" "rebuild" "node-sass"
31 verbose node v10.6.0
32 verbose npm  v6.1.0
33 error code ELIFECYCLE
34 error errno 1
35 error node-sass@4.5.0 postinstall: `node scripts/build.js`
35 error Exit status 1
36 error Failed at the node-sass@4.5.0 postinstall script.
36 error This is probably not a problem with npm. There is likely additional logging output above.
37 verbose exit [ 1, true ]`

**Comment by JohnKavanagh1050** [comment]
> Use the following command
> npm rebuild node-sass

Thank you was looking for a solution for over a freckin day!!

**Comment by Zerquix18** [comment]
If you're using gulp, try deleting `node_modules` and changing `gulp-sass` from 2.x to ^3.0.0

**Comment by rahulgupta60** [comment]
Please try with it will work with node 8 above vesion.

**Comment by markuszeller** [comment]
I was missing the packages `python2` and `g++`. After that, the installation of node-sass went thru.

**Comment by sjorsvanheuveln** [comment]
Also check your node version! I got the same errors as I installed the latest node version which wasn't compatible with my node-sass version.

**Comment by mmamoonkhan** [comment]
@Atulg23 it does not work for me do you have any other solution. let me share my error with you...
 ERROR in ./resources/sass/paying/app.scss (./node_modules/css-loader??ref--1-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--1-4!./resources/sass/paying/app.scss)
        Module build failed (from ./node_modules/sass-loader/lib/loader.js):
        Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (72)
        For more information on which environments are supported please see:
        https://github.com/sass/node-sass/releases/tag/v4.11.0
            at module.exports (/var/www/html/moneytransfer/node_modules/node-sass/lib/binding.js:13:13)
            at Object.<anonymous> (/var/www/html/moneytransfer/node_modules/node-sass/lib/index.js:14:35)
            at Module._compile (/var/www/html/moneytransfer/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
            at Module.load (internal/modules/cjs/loader.js:1002:32)
            at Function.Module._load (internal/modules/cjs/loader.js:901:14)
            at Module.require (internal/modules/cjs/loader.js:1044:19)
            at require (/var/www/html/moneytransfer/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
            at Object.sassLoader (/var/www/html/moneytransfer/node_modules/sass-loader/lib/loader.js:46:72)

**Comment by anouar1991** [comment]
> Problem persisted after that, but `npm uninstall node-sass -g && node cache clean && node install node-sass` fixed that. Thanks!

Do you mean 
`npm uninstall node-sass -g && npm cache clean --force && npm install node-sass`

**Comment by MaxiDeBox** [comment]
> > Problem persisted after that, but `npm uninstall node-sass -g && node cache clean && node install node-sass` fixed that. Thanks!
> 
> Do you mean
> `npm uninstall node-sass -g && npm cache clean --force && npm install node-sass`

Thank you, it helped
