### ISSUE TITLE
NPM warnings escalating to errors during provisioning

### ISSUE THREAD

**Issue by jeff1evesque** [sass/node-sass#1655]
I am trying to [install](https://github.com/jeff1evesque/machine-learning/blob/master/puppet/environment/docker/modules/package/manifests/webcompilers.pp#L19-L26) `node-sass`.  However, I'm getting the following [traceback](https://github.com/jeff1evesque/machine-learning/issues/2670) error:

```bash
$ cd /path/to/machine-learning
$ vagrant up
$ vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:~$ sudo su
root@vagrant-ubuntu-trusty-64:~$ apt-get -y install dos2unix
root@vagrant-ubuntu-trusty-64:~$ cd /vagrant
root@vagrant-ubuntu-trusty-64:~$ dos2unix build_docker && chmod u+x build_docker
root@vagrant-ubuntu-trusty-64:~$ apt-get -y install docker.io
root@vagrant-ubuntu-trusty-64:~$ echo "deb https://packages.docker.com/1.12/apt/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
root@vagrant-ubuntu-trusty-64:~$ apt-get -y update && sudo apt-get -y upgrade docker-engine
root@vagrant-ubuntu-trusty-64:~$ ./build_docker
...
Debug: /Package[uglify-js@2.6.2]: Provider npm does not support features virtual_packages; not managing attribute allow_virtual
Debug: /Package[imagemin@5.0.0]: Provider npm does not support features virtual_packages; not managing attribute allow_virtual
Debug: /Package[node-sass@3.5.2]: Provider npm does not support features virtual_packages; not managing attribute allow_virtual
Debug: /Package[babel-core@6.7.4]: Provider npm does not support features virtual_packages; not managing attribute allow_virtual
Debug: /Package[browserify@13.0.0]: Provider npm does not support features virtual_packages; not managing attribute allow_virtual
Debug: /Package[babelify@7.2.0]: Provider npm does not support features virtual_packages; not managing attribute allow_virtual
Debug: Creating default schedules
...
Debug: Executing: '/usr/bin/npm list --json --global'
Debug: Executing: '/usr/bin/npm install --global imagemin@5.0.0'
Notice: /Stage[main]/Package::Webcompilers/Package[imagemin@5.0.0]/ensure: created
Debug: /Package[imagemin@5.0.0]: The container Class[Package::Webcompilers] will propagate my refresh event
Debug: Executing: '/usr/bin/npm list --json --global'
Debug: Executing: '/usr/bin/npm install --global node-sass@3.4.2'
Error: Execution of '/usr/bin/npm install --global node-sass@3.4.2' returned : npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Error: /Stage[main]/Package::Webcompilers/Package[node-sass@3.4.2]/ensure: change from absent to present failed: Execution of '/usr/bin/npm install --global node-sass@3.4.2' returned : npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Debug: Executing: '/usr/bin/npm list --json --global'
Debug: Executing: '/usr/bin/npm install --global babel-core@6.7.4'
Error: Execution of '/usr/bin/npm install --global babel-core@6.7.4' returned : npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Error: /Stage[main]/Package::Webcompilers/Package[babel-core@6.7.4]/ensure: change from absent to present failed: Execution of '/usr/bin/npm install --global babel-core@6.7.4' returned : npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
...
```

**Note:** I should have [node 5.x](https://github.com/jeff1evesque/machine-learning/blob/master/puppet/environment/docker/manifests/install_packages.pp#L11-L20) installed.

**Note:** my [`build_docker`](https://github.com/jeff1evesque/machine-learning/blob/master/build_docker#L16-L22) bash script, is a series of docker containers, under a common docker network.  Each container instance is provision by corresponding puppet manifests.

**Comment by jeff1evesque** [comment]
My [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/master/.travis.yml#L101-108), implement the same dockerfiles, successfully during each Travis [build](https://travis-ci.org/jeff1evesque/machine-learning/builds).

**Comment by jeff1evesque** [comment]
My [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/master/.travis.yml#L101-108), implements the same dockerfiles (as the above [`build_docker`](https://github.com/jeff1evesque/machine-learning/blob/master/build_docker#L23-L30)) successfully during each Travis [build](https://travis-ci.org/jeff1evesque/machine-learning/builds).

Maybe there's a significant difference between the Ubuntu 14.04 image pull from Vagrant's [atlas repository](https://vagrantcloud.com/ubuntu), versus the [dockerhub repository](https://hub.docker.com/_/ubuntu/)?  But, if that's the case, then the docker implementation via the [travis ci](https://travis-ci.org/jeff1evesque/machine-learning/builds/150323217#L2938) would not succeed.  I think an alternative, could be that, the docker-engine installed on the [host laptop](https://docs.docker.com/engine/getstarted/step_one/#/docker-for-windows), could differ from that installed on the [vagrant](https://github.com/jeff1evesque/machine-learning#test-scripts) ubuntu guest:

```bash
root@vagrant-ubuntu-trusty-64:~$ apt-get -y install docker.io
root@vagrant-ubuntu-trusty-64:~$ echo "deb https://packages.docker.com/1.12/apt/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
root@vagrant-ubuntu-trusty-64:~$ apt-get -y update && sudo apt-get -y upgrade docker-engine
```

**Comment by jeff1evesque** [comment]
The problems generated from running the [`build_docker`](https://github.com/jeff1evesque/machine-learning/blob/master/build_docker#L16-L22) script, implements the exact same dockerfiles, when implemented via the [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/master/.travis.yml#L101-L108).  However, the travis ci [builds](https://travis-ci.org/jeff1evesque/machine-learning/builds), do not generate any errors.  Instead, the travis ci implementation, correctly installs, and implemented the `node-sass` package.

**Comment by xzyfer** [comment]
The error from npm, there's nothing we can do. Updating to a newer version of node-sass should resolve the things it's complaining about.
