### ISSUE TITLE
complie css Font units px to pc 

### ISSUE THREAD

**Issue by V-Tom** [sass/node-sass#1657]
it's so sorry for this issues!

here is my production `sass-loader`

```javascript
  styleLoader = ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!autoprefixer!sass')
```

but i saw the build css file,there are so many wrong css font units ,some `pc`,like this `height:43pc`,event pt,like this `width:44pt`

>in fact i had never use these css font units

what's wrong?

**Comment by V-Tom** [comment]
maybe i can use `command+r` in webstorm replace all `pt` or `pc` to `px` would resolve this problem

😄

**Comment by nschonni** [comment]
This isn't the sass-loader issue tracer
