### ISSUE TITLE
Watch flag not creating file when first run

### ISSUE THREAD

**Issue by gunnx** [sass/node-sass#1660]
When I add the flag `--watch` the output file/sourcemap is not created until I make a change, is this expected behaviour? I was assuming it would generate the file first then watch for changes.

my command
`
node-sass --source-map true --watch --output-style expanded ./src/main.scss ./dist/core.css
`

node-sass v3.8.0

**Comment by xzyfer** [comment]
This is the intended behaviour. Remove the watch flag compilation. There is no way to please every body here so this is the we've settled on.

**Comment by saper** [comment]
@xzyfer I am not using gaze myself, can you remind me what would be the use case for --watch not creating files for a first time?

**Comment by xzyfer** [comment]
@saper it's purely a usability this. I think we have have you used to build on watch which resulted the complaints. Being two discrete operations gives the user more control of their work flow. It also allows for better integration with build tools like gulp if someone wanted to use node-sass's smart watcher.

**Comment by rinatio** [comment]
Did you consider having a value for `--watch` flag? `--watch=force` for example. Writing here, because https://github.com/sass/node-sass/issues/1742 is closed.

**Comment by mangelozzi** [comment]
I was confused cause I expected `--update --watch` to perform the current default behaviour, and just `--watch` to compile once at startup and then watch, then everyone is happy! Yay!
