### ISSUE TITLE
Stuck at install.js

### ISSUE THREAD

**Issue by KirisuteRanza** [sass/node-sass#1663]
At this stage of installing node-sass via NPM: 

```
> node-sass@3.8.0 install C:\temp1\node_modules\node-sass
> node scripts/install.js

```
With the log at this stage:

```
npm sill doParallel update-linked 0
npm sill doSerial install 1
npm sill install node-sass@3.8.0 C:\temp1\node_modules\.staging\node-sass-265c51ce
npm info lifecycle node-sass@3.8.0~install: node-sass@3.8.0
```

Nothing happens. It remains as it is, forever... 

Full logging details can be found attached. 

[error.txt](https://github.com/sass/node-sass/files/413614/error.txt)
[info.txt](https://github.com/sass/node-sass/files/413616/info.txt)
[log.txt](https://github.com/sass/node-sass/files/413615/log.txt)

**Comment by saper** [comment]
Can you check if it is maybe downloading the binding and it takes a very long time? (for example `netstat` output might give you info about the open connections).

**Comment by xzyfer** [comment]
@saper bugs like this and https://github.com/sass/node-sass/issues/1662 are why I think the progress bar is a good idea.

**Comment by saper** [comment]
@xzyfer I understand but still not convinced. For those cases a simple message informing we are about to start the download would do.

**Comment by KirisuteRanza** [comment]
@saper It was a proxy issue. Company firewall was blocking all HTTPS traffic, which install.js uses. I agree with @xzyfer a progress bar or at least some more information in the install.js would be useful
