### ISSUE TITLE
Problem installing dashing-js

### ISSUE THREAD

**Issue by ivantsou** [sass/node-sass#1666]
Hi,
First, thank you for the help!

I would like to install dashing-js but I got error msg when I do npm install.
Here is what I did:
1. Download dashing-js from https://github.com/fabiocaseri/dashing-js 
2. Install the downloaded package(folder name is "dashing-js-master-2/")
sudo npm install -g dashing-js-master-2/

Here is the error I got:

ivan@da0704a-dhcp89:~/Downloads$ sudo npm install -g dashing-js-master-2/
npm WARN deprecated jade@0.35.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN engine punycode@2.0.0: wanted: {"node":">=6"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN excluding symbolic link test/fixtures/app/views/.#application.js.coffee.erb -> sam@pursuit.41266
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-sass@0.7.0 install /usr/local/lib/node_modules/dashing-js/node_modules/node-sass
> node build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Volumes/Data/HomeDirectory/.node-gyp/4.4.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp"
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:7:
../sass_context_wrapper.h:10:3: error: unknown type name 'uv_work_t'
  uv_work_t request;
  ^
../sass_context_wrapper.h:20:3: error: unknown type name 'uv_work_t'
  uv_work_t request;
  ^
../binding.cpp:13:20: error: unknown type name 'uv_work_t'
void WorkOnContext(uv_work_t* req) {
                   ^
../binding.cpp:19:22: error: unknown type name 'uv_work_t'
void MakeOldCallback(uv_work_t* req) {
                     ^
../binding.cpp:20:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../binding.cpp:29:31: error: no matching function for call to 'Null'
            Local<Value>::New(Null()),
                              ^~~~
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/v8.h:8130:18: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local<Primitive> Null(Isolate* isolate) {
                 ^
../binding.cpp:30:39: error: no member named 'New' in 'v8::String'
            Local<Value>::New(String::New(ctx->output_string))
                              ~~~~~~~~^
../binding.cpp:30:43: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
            Local<Value>::New(String::New(ctx->output_string))
                                          ^
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
../binding.cpp:33:24: error: member reference type 'v8::Persistent<v8::Function>' is not a pointer; maybe you meant to use '.'?
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~^~
                       .
../binding.cpp:33:26: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../binding.cpp:33:40: error: no member named 'GetCurrent' in 'v8::Context'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
../binding.cpp:38:39: error: no member named 'New' in 'v8::String'
            Local<Value>::New(String::New(ctx->error_message))
                              ~~~~~~~~^
../binding.cpp:38:43: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
            Local<Value>::New(String::New(ctx->error_message))
                                          ^
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
../binding.cpp:41:24: error: member reference type 'v8::Persistent<v8::Function>' is not a pointer; maybe you meant to use '.'?
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~^~
                       .
../binding.cpp:41:26: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../binding.cpp:41:40: error: no member named 'GetCurrent' in 'v8::Context'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
../binding.cpp:44:15: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
        node::FatalException(try_catch);
              ^
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            ^
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../binding.cpp:50:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> OldRender(const Arguments& args) {
                              ^~~~~~~~~
                              v8::internal::Arguments
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../binding.cpp:51:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/usr/local/lib/node_modules/dashing-js/node_modules/node-sass/.node-gyp/4.4.7/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../binding.cpp:55:23: error: expected ';' after expression
    String::AsciiValue astr(args[0]);
                      ^
                      ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/dashing-js/node_modules/node-sass
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "dashing-js-master-2/"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.7.0 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Data/HomeDirectory/Downloads/npm-debug.log


[npm-debug.log.zip](https://github.com/sass/node-sass/files/416276/npm-debug.log.zip)

**Comment by nschonni** [comment]
Sorry, 0.7 is a very old version of node-sass, and won't support NodeJS 4. Please update your node-sass version to latest.

**Comment by godrose** [comment]
Still reproducible with 3.10.1 version of node-sass

**Comment by xzyfer** [comment]
4.5.0 is the latest release

**Comment by frieman** [comment]
@nschonni  I'm still encounter this issue 

npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1

Did the node-sass dependency was updated? 
Thanks

**Comment by xzyfer** [comment]
> npm ERR! node-sass@0.7.0 install

0.7.0 is unsupported. Please upgrade to 4.5.0.

**Comment by kac-1324** [comment]
I'm having the same error. I used 'npm install node-sass' to get the latest version of node-sass.
Now when I do node-sass -v, it is giving version 4.5.0.
But still while installing dashing-js, it is taking 0.7 version.
How to resolve this issue?

**Comment by xzyfer** [comment]
You'll need to ask the dashing-js team to update their node-sass dependency
