### ISSUE TITLE
Windows 10 installation failure with COMSPEC set to MinGW sh.exe

### ISSUE THREAD

**Issue by legshooter** [sass/node-sass#1671]
Hey,

- Windows 10 x64
- node v4.5.0, v6.4.0 (also tried with older v6.3.x and v4.4.x before and same result)
- npm v3.10.6 (tried with an older minor/patch versions I can't remember and same result)
- Using Git's MinGW as a shell, but tried cmd.exe and it's all the same

I followed the troubleshooting guide, but `npm.log` is kinda empty, so I included `npm.err` and `npm-debug.log`:
- [npm.log](https://gist.github.com/legshooter/6beaca71cf76166a40bd14a66e4f3b6e)
- [npm.err](https://gist.github.com/legshooter/96f66c38372862ce1c499171a5ebb40d)
- [npm-debug.log](https://gist.github.com/legshooter/af38225a32e93d1cbc93d79ac0b2c446)

I noticed this weeks ago on new installations but just gave up and moved on. Now I've been stupid enough to mess around with a working installation I had that's actually uber important, so when reinstalling node / node_modules I hit into this again, and now I can't continue working :/

I could've obviously missed something, but I've searched Google and specifically the issues both now and before, and couldn't find what I thought to be my exact problem (went through all sorts of `--no-optional`, `--no-bin-links`, `--msvs_version=2013`, `--unsafe-perm`, cache cleaning, deleting everything, reinstalling, changing versions, etc. that didn't help).

Any help is super appreciated as I am really stuck without Sass compilation...

**Comment by saper** [comment]
Can you post the logs when doing this from the cmd.exe windows? (By the way, you can attach multiple files to one gist).

**Comment by legshooter** [comment]
Here you go: [cmd.exe-log](https://gist.github.com/legshooter/7c7f11cbc78be9b6852d84de12e7547f)
(Yeah, it's my OCD kicking in.. it just feels 'cleaner')

Kinda desperate with this one, really don't know what else I can do.

**Comment by saper** [comment]
`C:\Users\koby\Desktop\Portable\PortableGit\bin\sh.exe` this is no good.

Do you have `COMSPEC` set to this?

**Comment by legshooter** [comment]
Yes, that's Git's MinGW which I use over cmd.exe, but both exhibit the same errors/output.

**Comment by saper** [comment]
This will not work. Please unset `COMSPEC` and try again. You need to have `cmd.exe` as the command interpreter npm will be using.

**Comment by legshooter** [comment]
You sir are absolutely right. I could kiss you right now.

**Comment by saper** [comment]
It's enough if you close this bug as INVALID :)

**Comment by legshooter** [comment]
Seriously dude, thanks.

**Comment by saper** [comment]
@legshooter can you have a look at https://github.com/saper/node-sass/blob/ff2bcb795266060326b47e33feaad90c5b607b93/TROUBLESHOOTING.md#windows and see it is mentioned clearly enough?

**Comment by legshooter** [comment]
Yup, looks great.

I seem to be stuck on a different error now. I was satisfied at first because I was testing an isolated `node-sass` installation, but now I'm back to reinstalling my project's dependencies (in which `node-sass` is a dependency's dependency), and it seems that installation fails this time on `node-sass`' `build.js`:
```javascript
npm ERR! node-sass@3.6.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```
I'll open a new issue if I can't solve this myself, but do let me know if you prefer I continue here.

**Comment by saper** [comment]
Well, that dependency's dependency node-sass is too old. you need to update it somehow... Sometimes updating dependencies works.

**Comment by legshooter** [comment]
Thanks for the tip. It's `gulp-sass`' dependency, and it lists `"node-sass": "^3.4.2",` in `package.json`, so I'm not sure why it's not installing the latest `node-sass`.

**Comment by legshooter** [comment]
Ok, npm-shrinkwrap was messing with my head, I thought `npm install` will actually install newer versions and update shrinkwrap (similarly to composer's (PHP) behavior with `composer update` and `composer.lock`).

 Finally, a clean install!

**Comment by saper** [comment]
\o/
