### ISSUE TITLE
Suppress some warning massages

### ISSUE THREAD

**Issue by adumat** [sass/node-sass#1675]
I'm note sure this is a bug or a request for new feature.
In my build process i have some warning about image url like this:
```
WARNING: Image 'imageChartImages/sad-white.png' not found.
Backtrace:
	src/main/webapp/IA/styles/images/_generated-imagehelper.scss:46, in function `image-url`
	src/main/webapp/IA/styles/images.scss:6
```

This message are normal because the images are on other path that, after complete build, are copy on right place.
There is a parameter or a method for suppress this type of warning?

**Comment by xzyfer** [comment]
This is not possible in the sass language, and it's not something we can add.

You can try the `--quiet` flag to suppress output.
