### ISSUE TITLE
Is there any plan to support $SASS_PATH?

### ISSUE THREAD

**Issue by nottrobin** [sass/node-sass#1678]
I know `node-sass` has the `--include-path` option. However, the original Sass documentation mentioned the ability to provide include paths with a `SASS_PATH` environment variable.

This would be very helpful for me, as I need `node-sass` to look in a specific set of include paths *by default* in my environment. Specifying `--include-path` every time is not an option for me in this case.

There was a discussion about [including this in libsass](https://github.com/sass/libsass/issues/90), but they concluded that it should be the wrappers' job, rather than the job of libsass itself.

**Comment by xzyfer** [comment]
I was not aware of this feature. I agree this belongs in node sass not
libsass. We'd happily accept a PR.

**Comment by nottrobin** [comment]
Cool, I'll see if I can make one.
