### ISSUE TITLE
Get stucked when install node-sass@3.8.0

### ISSUE THREAD

**Issue by mycoin** [sass/node-sass#1681]
when I `npm install` a node project witch depends on `node-sass@3.8.0` 

```
caniuse-api: Generation ok
-
> node-sass@3.8.0 install /Users/apple/Group/opt/index-of/react-begin/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/darwin-x64-46_binding.node": 

read ECONNRESET
```

**Comment by saper** [comment]
Npm attempts to download the binary from GitHub. Your connection gets reset in the middle, probably by some aquatic animals living on your Internet connection (河蟹)

You might need to apply your local workaround to this problem.

**Comment by SandroSchweizer** [comment]
Have the same problem right now:

> node scripts/install.js

> Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-ia32-48_binding.node":

> connect ETIMEDOUT 192.30.253.112:443

I've a Maven Build which kicks off a gulp task. The problem exists since a few hours. Oddly enough everything builds properly with the binary  `win32-x64-46`.

**Comment by saper** [comment]
@SandroSchweizer apart from the timeout problem (which is definitely a networking problem) what happens in your case you are using different node engines - one for installing (npm install), another one to run the sass processing. Your problem is sometimes caused by [Visual Studio 2015 Task Runner as described in our TROUBLESHOOTING file](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#using-node-sass-with-visual-studio-2015-task-runner), but it will happen every time different node engines are used for those tasks.

**Comment by saper** [comment]
@mycoin @SandroSchweizer Did you get also this message from npm:

````
      Hint: If github.com is not accessible in your location
            try setting a proxy via HTTP_PROXY, e.g. 
            export HTTP_PROXY=http://example.com:1234
      or configure npm proxy via
            npm config set proxy http://example.com:8080
````

If not, it would be great to see the full output from your `npm install` as [gist](https://gist.github.com).

**Comment by SandroSchweizer** [comment]
Yeah, I got this. I think i got closer to the problem now. As far as I understand our infrastructur, it seems that we have an internal repo for all bindings and if that fails, it connects to github. My configuration should be okay. Though it should work on our internal system. Multiple other workmates haven't the problem and can build the project on the same system. Here's the full output:
[debug.txt](https://github.com/sass/node-sass/files/439265/debug.txt)

I will contact the server admin on monday and then write back again.

**Comment by saper** [comment]
@SandroSchweizer you can try fetching the binary file manually from github.com/sass/node-sass-binaries just you need to rename the file and put it in a platform-specific directory under `vendor`

**Comment by saper** [comment]
@SandroSchweizer our binary bindings are it the part of the npm package so the download process will goo github and not to your internal repo. Maybe your colleagues have Python 2.7, Visual Studio 2013 and some Windows SDK installed and it just compiled for them?

**Comment by SandroSchweizer** [comment]
@saper If I try to download the binary manually I get this weird error:
>Node Sass could not find a binding for your current environment: Windows 32-bit with Node.js 6.x

>Found bindings for the following environments:
>  - Windows 32-bit with Node.js 6.x

When I try to rebuild it, it fails as  above.


I had no problem until this morning. We are using Java EE for the backend server and Javascript (Angular) for the frontend application. Neither Python nor Visual Studio.

**Comment by saper** [comment]
You have at least two versions of node installed (32bit and 64bit), you should sort it out and make sure you are using one of them or you have both bindings installed.

**Comment by SandroSchweizer** [comment]
I have a 32bit node version installed and the 32bit binding included. Still the same message.
>Node Sass could not find a binding for your current environment: **Windows 32-bit** with Node.js 6.x

>Found bindings for the following environments:

>**Windows 32-bit** with Node.js 6.x

**Comment by ksmanikjava** [comment]
I too got the same error. Tried to clean the npm modules, and ran the following commands ,as mentione d in some forums . But nothing helped.
1.npm install npm@latest
2.npm rebuild node-sass
3. npm install --save-dev gulp-sass
4. npm install node-sass

I have the latest versions of Node (6.4.0), npm (3.10.3) , and my gulp version is 3.9.1. Kindly help me in this issue. Thanks in advance.

**Comment by saper** [comment]
Please follow https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md and post a full installation log before adding a "me too" comment here.

**Comment by ksmanikjava** [comment]
I have checked through the blog. I din't find any suitable solution there. Please find my installation log below.

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h                                                                                                    ttps://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher                                                                                                     to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher                                                                                                     to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade                                                                                                     to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o                                                                                                    n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible                                                                                                    . Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher                                                                                                     to avoid a RegExp DoS issue
npm WARN prefer global jshint@2.9.3 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.8.0 install D:\LocalProjectFolder\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-ia32-48_binding.node":

tunneling socket could not be established, statusCode=403

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.8.0 postinstall D:\LocalProjectFolder\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\LocalProjectFolder\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --                                                libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\FolderName\\projects\\ProjectName\\ui-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.4.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\LocalProjectFolder\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (D:\LocalProjectFolder\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (D:\LocalProjectFolder\node_modules\which\which.js:81:29)
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\which\which.js:90:16
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\LocalProjectFolder\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (D:\LocalProjectFolder\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (D:\LocalProjectFolder\node_modules\which\which.js:81:29)
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\which\which.js:90:16
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\LocalProjectFolder\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (D:\LocalProjectFolder\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (D:\LocalProjectFolder\node_modules\which\which.js:81:29)
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\which\which.js:90:16
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\LocalProjectFolder\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (D:\LocalProjectFolder\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (D:\LocalProjectFolder\node_modules\which\which.js:81:29)
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\which\which.js:90:16
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\LocalProjectFolder\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.10\r\n                                                "
gyp verb get node dir no --target version specified, falling back to host node version: 6.4.0
gyp verb command install [ '6.4.0' ]
gyp verb install input version string "6.4.0"
gyp verb install installing version: 6.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 6.4.0
gyp verb ensuring nodedir is created C:\Users\UserName\.node-gyp\6.4.0
gyp verb created nodedir C:\Users\UserName\.node-gyp\6.4.0
gyp http GET https://nodejs.org/download/release/v6.4.0/node-v6.4.0-headers.tar.gz
gyp verb download using proxy url: "http://UserName:Password@proxyname.com:portNumber/"
gyp WARN install got an error, rolling back install
gyp verb command remove [ '6.4.0' ]
gyp verb remove using node-gyp dir: C:\Users\UserName\.node-gyp
gyp verb remove removing target version: 6.4.0
gyp verb remove removing development files for version: 6.4.0
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\FolderName\\projects\\ProjectName\\ui-app\\node_modules\\node-gyp\\bin\\node-gyp.js                                                " "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\LocalProjectFolder\node_modules\node-sass
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
ProjectName@2.0.0 D:\FolderName\projects\ProjectName\ui-app
+-- browser-sync@2.14.0
| +-- browser-sync-client@2.4.2
| | +-- etag@1.7.0
| | `-- fresh@0.3.0
| | --It includes a series of many dependencies 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN ProjectName@2.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\LocalProjectFolder\npm-debug.log

I have already set up the proxy in my system and also in the corresponding node related files.
I have the latest versions of Node (6.4.0), npm (3.10.3) , and my gulp version is 3.9.1. 

Kindly help me in this issue. Thanks in advance.

**Comment by saper** [comment]
@ksmanikjava you have a problem with your proxy configuration or settings. Error code is 403 which means Permission denied. There is nothing node-sass team can do about it.

**Comment by mycoin** [comment]
Problem not resolved yet !  I have remove this module.

BTW, @saper  does `node-sass` really depends on `darwin-x64-46_binding.node` ? 

~~So ugly a dependency!!~~

**Comment by xzyfer** [comment]
Node Sass is a native extension. In order to save you recompiling it every install we do the hard work for and host the compiled file. When you install we check that your environment is supported, and if so we download the binary we pre-compiled for you.

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/darwin-x64-46_binding.node": 

read ECONNRESET
```

The error clearly stats you're experiencing a network issue connect to github where the binary is hosted. We cannot debug your network for you. Check your network config, and make sure if you're using a proxy you've set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

**Comment by mycoin** [comment]
After read the source code, `node-sass` was developed by `python`, `C++` 😱 ～～

```
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/apple/Public/OpenApi/node_modules/node-sass/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/apple/Public/OpenApi/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/apple/Public/OpenApi/node_modules/node-sass/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/apple/.node-gyp/4.4.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/apple/.node-gyp/4.4.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/apple/Public/OpenApi/node_modules/node-sass/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/apple/Public/OpenApi/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/apple/.node-gyp/4.4.4
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/Users/apple/.node-gyp/4.4.4/include/node -I/Users/apple/.node-gyp/4.4.4/src -I/Users/apple/.node-gyp/4.4.4/deps/uv/include -I/Users/apple/.node-gyp/4.4.4/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsas
```

I was frightened ! We made front-end devel so difficult to understand and use.

**Comment by mycoin** [comment]
Anyhow, Thank you for your patience. @saper Have a nice day 😄

**Comment by xzyfer** [comment]
Please read the documentation

>Node-sass is a library that provides binding for Node.js to LibSass, the C version of the popular stylesheet preprocessor, Sass.

Node Sass is a JavaScript API to LibSass. LibSass is written in C/C++ which is why it is much faster that Sass which is in Ruby. Lots of Node packages are written in C for speed, like filesystem watchers used by grunt and gulp.

Python is used by npm, not Node Sass, to compile all native extensions.
