### ISSUE TITLE
Did not find darwin-x64-49/binding.node

### ISSUE THREAD

**Issue by F-happy** [sass/node-sass#1683]
when i using electron, i found in 'process.versions.module' is 
49, but I have not found in the release this version of the package?Why is that?
<img width="691" alt="qq20160827-1 2x" src="https://cloud.githubusercontent.com/assets/8241236/18028982/b54166b8-6cbd-11e6-8ee8-b93d7d3471d0.png">

**Comment by nschonni** [comment]
As the message says, Electron isn't a supported platform

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/1682

**Comment by hdytsgt** [comment]
@F-happy take a look at these : https://github.com/sass/node-sass/issues/1682#issuecomment-248254180
