### ISSUE TITLE
Having problem with npm install of my project . Need help .

### ISSUE THREAD

**Issue by ksmanikjava** [sass/node-sass#1685]
I have set the proxy in my machine . But still i found some errors as the below trace. Have anyone faced an issue same like this ? Need your kind help.

$ npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve                                                                                                    nts@1.0.14
npm WARN project name@2.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                    node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path D:\Project_Folder\node_modules\.staging\lodash-ce0b32                                                                                                    d4
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename “Project_folder\node_modules\.staging\lodash-ce0b32d4' -> 'Project_Folder                                                                                                    \node_modules\sass-graph\node_modules\lodash'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal                                                                                                    l\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'Project_folder\node_modules\.staging\lodash-ce0b32d4' -> 'Project_Folder                                                                                                    \node_modules\sass-graph\node_modules\lodash'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'Project_Folder                                                                       \node_modules\.staging\lodash-ce0b32d4' -> ‘Project_Folder\node_modules\sass-graph\node_modules\lodash'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal                                                                                                    l\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename '                                                                           ProjectFolder\node_modules\.staging\lodash-ce0b32d4' -> 'Project_Folder                                                                                                    \node_modules\sass-graph\node_modules\lodash'
npm ERR!     at Error (native) parent: 'sass-graph' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     Project_Folder\npm-debug.log
npm ERR! code 1

**Comment by xzyfer** [comment]
>npm ERR! Error: EPERM: operation not permitted, rename ' ProjectFolder\node_modules.staging\lodash-ce0b32d4' -> 'Project_Folder \node_modules\sass-graph\node_modules\lodash'
>npm ERR! at Error (native) parent: 'sass-graph' }
>npm ERR!
>npm ERR! Please try running this command again as root/Administrator.

As the error message says, you don't have permission.

**Comment by ksmanikjava** [comment]
xzyfer , can you please be precise with the solution . Sorry i could not able to understand
