### ISSUE TITLE
npm install sass-loader@3.1.2 node-sass@3.4.2 --save-dev installation issue

### ISSUE THREAD

**Issue by venkyc07** [sass/node-sass#1687]
Am unable to install the node-sass in my ReactJS Application. While installing am getting the below error messages and npm warning message. Plz can any one help mee...!
node version: 6.3.1
npm version: 3.10.3
Operating System; windows 7 Home basic

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.4.2 install C:\Users\penguin\Desktop\Penguintest\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-48_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.company.com proxy.company.com:3000

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> spawn-sync@1.0.15 postinstall C:\Users\penguin\Desktop\Penguintest\node_modules\spawn-sync
> node postinstall

> node-sass@3.4.2 postinstall C:\Users\penguin\Desktop\Penguintest\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\penguin\Desktop\Penguintest\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\penguin\\Desktop\\Penguintest\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.3.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\penguin\Desktop\Penguintest\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\penguin\Desktop\Penguintest\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\penguin\Desktop\Penguintest\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\penguin\\Desktop\\Penguintest\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\penguin\Desktop\Penguintest\node_modules\node-sass
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
penguin-test@1.0.0 C:\Users\penguin\Desktop\Penguintest
`-- sass-loader@3.1.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN penguin-test@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sass-loader@3.1.2" "node-sass@3.4.2" "--save-dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\penguin\Desktop\Penguintest\npm-debug.log

Thanx in advance....:)

**Comment by xzyfer** [comment]
Please search before opening new issues. 

Node sass 3.4.2 is old and doesn't support Node 5 or 6. Update to node-sass@v3.8.0 or down grade node.

**Comment by venkyc07** [comment]
Thanqqqq ......!
Solved the issue...
