### ISSUE TITLE
OSX install hangs on node scripts/install.js

### ISSUE THREAD

**Issue by RYFN** [sass/node-sass#1690]
Running OSX 10.11.6
Node v6.1.0

node -p process.versions - 

```
{ http_parser: '2.7.0',
  node: '6.1.0',
  v8: '5.0.71.35',
  uv: '1.9.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '48',
  openssl: '1.0.2h' }
```
node -p process.platform - darwin
node -p process.arch - x64

Installing gulp-sass hangs on the dependancy install of node-sass. This is the same issue as raised here https://github.com/sass/node-sass/issues/1265 I just get:

```
npm info lifecycle node-sass@3.8.0~install: node-sass@3.8.0

> node-sass@3.8.0 install /Usersproject-path/node_modules/node-sass
> node scripts/install.js

Build timed out (after 35 minutes). Marking the build as failed.
```

However, I think in my case it may be a network issue (had no problems until recent network changes). What exactly is it that `scripts/install.js` does? Which URLs / ports should I be checking to see if they've been blocked or throttled?

**Comment by xzyfer** [comment]
This does sound like a networking problem. The installation fetching a prebuilt binary from a github release see https://github.com/sass/node-sass/releases.

If you have firewall contraints you can use a set of ENV variables to point the install script at a different location - https://github.com/sass/node-sass#binary-configuration-parameters

It's interesting that the fetch didn't timeout gracefully. A lack of timeouts could be related to some other issues we've seen @saper.

**Comment by RYFN** [comment]
Great, thanks for the info, will take a look at our end - it'll just be a http get though, right? I don't imagine the port is blocked... It may just be a general performance issue at our end.

Does it just attempt to download one of the `...binding.node` files? They're only a few MB for OSX by the looks of it.

**Comment by xzyfer** [comment]
Yes it's a simple HTTP GET which downloads one of the attached `binding.node` files based on the local environment.

**Comment by xzyfer** [comment]
We're going to add a timeout the binary fetch to hopefully prevent this in the future https://github.com/sass/node-sass/pull/1691.
