### ISSUE TITLE
Exported `test` directory harms Bamboo, Hudson and Jenkins build systems

### ISSUE THREAD

**Issue by Alain-Bearez** [sass/node-sass#1699]
On Linux systems, the Java based build systems cannot remove the directory `Sáss-UŢF8` due to the Unicode specific characters for diacritics. After the first build with the new release of `node-sass`, all following builds will fail with an exception while trying to remove this directory.

This has been tracked to the recent inclusion of `test` in the `files` section of the `package.json` in version **3.9.0**.

See [gulp-sass#529](https://github.com/dlmanning/gulp-sass/issues/529) for some reports of such side-effect.

**Comment by notsudo** [comment]
We ran into this as well today. For Jenkins you need to make sure the jvm option `-Dfile.encoding=UTF-8` is set for Jenkins master and all slaves. In addition on Linux the environment variable `LANG=en_US.UTF-8` or its locale equivalent needs to be added to the environment for Jenkins master​ and all slaves. We added it to `~/.bashrc` for the user on our Jenkins slaves. Hope this helps.

For more information on the Jenkins side you can check out:
https://issues.jenkins-ci.org/browse/JENKINS-12610
https://issues.jenkins-ci.org/browse/JENKINS-33478

**Comment by xzyfer** [comment]
@Alain-Bearez sounds like a Jenkins issue. For the time there appears to be work arounds. Thank you for your investigation @notsudo.
