### ISSUE TITLE
Should not publish tests with npm module

### ISSUE THREAD

**Issue by Joneser** [sass/node-sass#1701]
Hi, since the last release I have been having issues with path length names due to the length of file names. I've narrowed this down to the length of the test file names (specifically the fixtures/spec folder).

Do you think you could add an npmignore file to the project to prevent all of these test files from being published to npm or is there a specific reason that the tests need to be included in the published package?

Thanks

**Comment by xzyfer** [comment]
We published the test on purpose as of v3.9.0 at the request of the node-citgm team.

@nschonni looks like making sass-spec a devDependency is something we'll need to address asap.

**Comment by xzyfer** [comment]
For the time being we'll remove the tests until we have better solution.

**Comment by Joneser** [comment]
Thanks for the quick response!

**Comment by xzyfer** [comment]
Yes.
