### ISSUE TITLE
Issues with 3.9.2 due to missing binaries

### ISSUE THREAD

**Issue by jakub-g** [sass/node-sass#1702]
Hello

FYI our builds started failing this morning, this is due to 3.9.2 being published to npm while other stuff (binaries) is not yet available on server

Compare:
https://github.com/sass/node-sass/releases/download/v3.9.0/darwin-x64-14_binding.node works
https://github.com/sass/node-sass/releases/download/v3.9.2/darwin-x64-14_binding.node 404

I'm not sure what is your release process, is it normal that you put binaries in releases later on, or it was overlooked?

In fact our issue is more due to gulp-sass not freezing the dependency https://github.com/dlmanning/gulp-sass/blob/master/package.json#L26 but depending on semver compliancy (as it's common in node world, though I dislike it), but I thought I would let you know

Regards
Jakub

**Comment by erlendr** [comment]
The latest version bump commit is missing a version tag: https://github.com/sass/node-sass/commit/2c2f6a24478c253022b8e935012745674eedb320

**Comment by xzyfer** [comment]
v3.9.1 and v3.9.2 have been unpublished. If you clear your node_modules and npm install the issue should be fixed. We're release v3.9.3 to purge local caches but releases take an hour.

**Comment by Nickman87** [comment]
Would have been handy if this issue wasn't closed before it was actually fixed... I just got here by chance

**Comment by xzyfer** [comment]
As a rule of thumb always search closed issues. The repo search at the top of the page will do this by default. The GitHub work flow will close issues based on commit messages. This can happen long before a release.
