### ISSUE TITLE
Accessing current context from within Sass functions written in JS

### ISSUE THREAD

**Issue by ericmorand** [sass/node-sass#1708]
I'm currently playing with the experimental functions feature of libSass and am finding it very limited by the lack of context passed to the custom functions.

Typically, having the currently processed file passed as parameter to the custom functions would allow for on-the-fly URL conversion that would open the door to pure component-based approach.

Here is what I would like to do:

```
'url($url)': function(url, context) {
    return new sass.types.String('url("' + context.file.dirname + '/' + url.getValue() + '")');
}
```

This would rewrite every URL relatively to the currently processed file.

Let consider the following SCSS sources:

**src/common/index.scss:**
```

div {
    background-image: url('assets/images/bg.jpg');
}
```

**src/component1/index.scss:**

`@import "../common/index.scss";`

Rendering src/component1/index.scss would result to:

```
div {
    background-image: url('src/common/assets/images/bg.jpg');
}
```

Without URL rewriting, rendering src/component1/index.scss would result to:

```
div {
    background-image: url('assets/images/bg.jpg');
}
```

Which would lead to a 404 on the background image.

**Comment by xzyfer** [comment]
Sounds like a duplicate of #895. Some progress was made by adding additional context to `this` in custom functions.

**Comment by ericmorand** [comment]
@xzyfer You're right, this issue is a duplicate.

**Comment by ericmorand** [comment]
Closing this in favour of #895 .
