### ISSUE TITLE
Drop Node EOL versions support

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#1709]
Since node is dropping it from even security patching https://nodejs.org/en/blog/community/v5-to-v7/
- [ ] Remove from Appveyor
- [ ] Remove from Travis
- [ ] Update install script to print the version isn't supported. Something about the fact that it must be manually built and no bugs will be investigated.
- [ ] Update README supported version

0.10 and 0.12 may need their own issues depending on the timing since they EOL October and December respectively.

**Comment by xzyfer** [comment]
We can make reasonable determinations about support from the download count of the release binaries. We get +2M installs a month so we should have a good data. Download counts are exposed via the HG release API.

https://developer.github.com/v3/repos/releases/#get-a-single-release

**Comment by nschonni** [comment]
OK, I looked at the 3.8.0 release metrics since it was around for 2 months.
iojs seems to have only ~50 downloads per platform/arch, so I think it is safe to drop now.
5/47 still seems to have quite a few downloads, so I'm thinking that a warning message might be better for now

**Comment by xzyfer** [comment]
Dropping iojs support has come up a few times. My argument has always been that it really costs us nothing to support old version of Node at this point aside from CI time. Is there a particular reason you want to drop older versions?

It's also worth noting we're planning to release LibSass 3.4 soon. This will essentially be a major version bump for LibSass. I was thinking this might be an opportune time to bump the major for node-sass if we had something to land.

**Comment by nschonni** [comment]
I see it as one of those "why can't I run Windows XP forever things". Yes, it still works, but it's better to encourage people off platforms that don't get security updates anymore (especially devs)

**Comment by xzyfer** [comment]
I don't necessarily agree. It's not hurting anyone, doesn't cause any work for us. Either way I don't feel comfortable dropping any support without a major bump given the most people will lock to `^3`.

**Comment by xzyfer** [comment]
Looks like something went wrong here :) Mildly freaked out

**Comment by nschonni** [comment]
Ah, that's what happened #1705 was the one that was supposed to autoclose with that issue

**Comment by igor-savin-ht** [comment]
@nschonni So which versions are currently in-scope for removing within this task?

**Comment by xzyfer** [comment]
See https://github.com/sass/node-sass/issues/2111

**Comment by xzyfer** [comment]
This has been addressed in #2312
