### ISSUE TITLE
Intermittent missing "vendor" directory upon installation for 3.9.0 and 3.93

### ISSUE THREAD

**Issue by dtothefp** [sass/node-sass#1710]
## Reporting an installation issue
Running on Mac OSX 10.10.5. Intermittent issues with missing the `vendor` directory in `node-sass` upon installation.  Not sure why this was happening, seems like on fresh install of `node_modules` the `vendor` directory would be missing but if I just deleted `node-sass` from `node_modules` and re-installed it would be there?

```
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/***/node_modules/node-sass/vendor'
```

**Comment by xzyfer** [comment]
Please follow the [installation troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx).

**Comment by xzyfer** [comment]
Closing awaiting a response.
