### ISSUE TITLE
Error on installing node-sass on Windows

### ISSUE THREAD

**Issue by AliAlGallaf** [sass/node-sass#1722]
- NPM version: 1.4.28

- Node version: v0.10.33

- Node Process:
{ http_parser: '1.0',
  node: '0.10.33',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.29',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1j' }

- Node Platform: win32

- Node architecture: x64

- node-sass version: 
module.js:340
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3

- npm node-sass versions:
bptc@1.0.0 C:\xampp\htdocs\bptc
└── (empty)

C:\xampp\htdocs\bptc>npm install node-sass
npm WARN package.json laravel-elixir-vue@0.1.7 No repository field.
npm WARN package.json vue@1.0.26 No README data
npm WARN package.json gulp-minify-css@1.2.4 No repository field.
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"1.4.28"})
\
> node-sass@3.10.0 install C:\xampp\htdocs\bptc\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-11_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-11_binding.node":

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.10.0 postinstall C:\xampp\htdocs\bptc\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\bptc\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@0.10.33 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\xampp\htdocs\bptc\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at Object.oncomplete (fs.js:107:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\python27_x64\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed:
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:648:15)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:756:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:969:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:465:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\bptc\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\xampp\htdocs\bptc\node_modules\node-sass
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed

npm ERR! node-sass@3.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.10.0 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! cwd C:\xampp\htdocs\bptc
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by xzyfer** [comment]
As the error message says, npm was unable to download the precompiled binary. Check your network settings and try again.

> Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-11_binding.node
>Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-11_binding.node":
>
>tunneling socket could not be established, cause=getaddrinfo ENOTFOUND
>
>Hint: If github.com is not accessible in your location
>try setting a proxy via HTTP_PROXY, e.g.
>
>  export HTTP_PROXY=http://example.com:1234
>or configure npm proxy via
>
>  npm config set proxy http://example.com:8080
>node-sass@3.10.0 postinstall C:\xampp\htdocs\bptc\node_modules\node-sass
node scripts/build.js
