### ISSUE TITLE
node-sass download from sass-binary-site does not respect no_proxy env variable

### ISSUE THREAD

**Issue by mmrath** [sass/node-sass#1724]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:
- NPM version (`npm -v`):3.10.5
- Node version (`node -v`):v6.3.1
- Node Process (`node -p process.versions`):

`{ http_parser: '2.7.0',
  node: '6.3.1',
  v8: '5.0.71.57',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }`
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`): error
- npm node-sass versions (`npm ls node-sass`): error

When encountering a syntax, or compilation issue:
- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
  may link it back here, but any change will be required there, not here

_If you delete this text without following it, your issue will be closed._

If I remove HTTP_PROXY and HTTPS_PROXY env variables then install runs fine. But I have to keep then for other work. I have a NO_PROXY env variable which allows internal repos without proxy. but node-sass scripst/install.js does not honour this

**Comment by xzyfer** [comment]
Interesting I'm not familiar with the NO_PROXY variable. I'll look into it.

**Comment by xzyfer** [comment]
>no_proxy
>This variable should contain a comma-separated list of domain extensions proxy should not be used for. For instance, if the value of no_proxy is ‘.mit.edu’, proxy will not be used to retrieve documents from MIT.

http://www.gnu.org/software/wget/manual/html_node/Proxies.html

**Comment by xzyfer** [comment]
This looks like an oversight on our behalf

**Comment by mmrath** [comment]
I think node request honours this env setting. So it may be possible to let request handle all of the proxy stuff. The download should work exactly like npm downloading from npm registry. 

A workaround could be to introduce a new variable like for custom download site. If variable is set then don't use proxy. Something like sass-binary-no-proxy

**Comment by xzyfer** [comment]
I'm not sure why request isn't doing the right thing with regards to
no_proxy. However we can't solely rely on request for proxy settings
because we also need to respect the npm conf proxy settings.

**Comment by mmrath** [comment]
Yes we need to honour npm proxy settings as well. Do you know if it is possible to download as if npm is downloading the file. Npm downloading works perfectly with all these settings. 

What do you think about the work around configuration setting to bypass proxy?

**Comment by xzyfer** [comment]
npm only half supports no_proxy and it does it in a round-about what which makes it hard to emulate, see https://github.com/npm/npm/commit/40afd6aaf34c11a10e80ec87b115fb2bb907e3bd

I'm looking in to a work around.
