### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jyma1991** [sass/node-sass#1728]
warn ionic-project@1.1.1 No repository field.
49549 warn ionic-project@1.1.1 No license field.
49550 verbose stack Error: node-sass@3.10.0 postinstall: `node scripts/build.js`
49550 verbose stack Exit status 1
49550 verbose stack     at EventEmitter.<anonymous> (D:\Program\Nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
49550 verbose stack     at emitTwo (events.js:106:13)
49550 verbose stack     at EventEmitter.emit (events.js:191:7)
49550 verbose stack     at ChildProcess.<anonymous> (D:\Program\Nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
49550 verbose stack     at emitTwo (events.js:106:13)
49550 verbose stack     at ChildProcess.emit (events.js:191:7)
49550 verbose stack     at maybeClose (internal/child_process.js:877:16)
49550 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
49551 verbose pkgid node-sass@3.10.0
49552 verbose cwd E:\Code\Hybrid\Nail
49553 error Windows_NT 10.0.14926
49554 error argv "D:\\Program\\Nodejs\\node.exe" "D:\\Program\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
49555 error node v6.6.0
49556 error npm  v3.10.3
49557 error code ELIFECYCLE
49558 error node-sass@3.10.0 postinstall: `node scripts/build.js`
49558 error Exit status 1
49559 error Failed at the node-sass@3.10.0 postinstall script 'node scripts/build.js'.
49559 error Make sure you have the latest version of node.js and npm installed.
49559 error If you do, this is most likely a problem with the node-sass package,
49559 error not with npm itself.
49559 error Tell the author that this fails on your system:
49559 error     node scripts/build.js

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
