### ISSUE TITLE
Jenkins build issue

### ISSUE THREAD

**Issue by bgolubovic** [sass/node-sass#1735]
Dear,

After not changing any parameter or configuration we get on this error on deploying our app on Jenkins throw Maven build.

[INFO] > node-sass@3.10.0 install /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/linux-x64-14_binding.node
[INFO] Binary downloaded and installed at /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass/vendor/linux-x64-14/binding.node
[INFO] 
[INFO] > node-sass@3.10.0 postinstall /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[INFO] "/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass/vendor/linux-x64-14/binding.node" exists. 
[INFO]  testing binary.
[INFO] Problem with the binary:
[INFO] Error: /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass/vendor/linux-x64-14/binding.node: invalid ELF header
[INFO] Manual build incoming.
[INFO] Building: /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node/node /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[ERROR] gyp info it worked if it ends with ok
[ERROR] gyp verb cli [ '/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node/node',
[ERROR] gyp verb cli   '/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
[ERROR] gyp verb cli   'rebuild',
[ERROR] gyp verb cli   '--verbose',
[ERROR] gyp verb cli   '--libsass_ext=',
[ERROR] gyp verb cli   '--libsass_cflags=',
[ERROR] gyp verb cli   '--libsass_ldflags=',
[ERROR] gyp verb cli   '--libsass_library=' ]
[ERROR] gyp info using node-gyp@3.4.0
[ERROR] gyp info using node@0.12.4 | linux | x64
[ERROR] gyp verb command rebuild []
[ERROR] gyp verb command clean []
[ERROR] gyp verb clean removing "build" directory
[ERROR] gyp verb command configure []
[ERROR] gyp verb check python checking for Python executable "python2" in the PATH
[ERROR] gyp verb `which` succeeded python2 /usr/bin/python2
[ERROR] gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.6.6\n"
[ERROR] gyp verb get node dir no --target version specified, falling back to host node version: 0.12.4
[ERROR] gyp verb command install [ '0.12.4' ]
[ERROR] gyp verb install input version string "0.12.4"
[ERROR] gyp verb install installing version: 0.12.4
[ERROR] gyp verb install --ensure was passed, so won't reinstall if already installed
[ERROR] gyp verb install version not already installed, continuing with install 0.12.4
[ERROR] gyp verb ensuring nodedir is created /home/jenkins/.node-gyp/0.12.4
[ERROR] gyp verb created nodedir /home/jenkins/.node-gyp/0.12.4
[ERROR] gyp http GET https://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
[ERROR] gyp WARN install got an error, rolling back install
[ERROR] gyp verb command remove [ '0.12.4' ]
[ERROR] gyp verb remove using node-gyp dir: /home/jenkins/.node-gyp
[ERROR] gyp verb remove removing target version: 0.12.4
[ERROR] gyp verb remove removing development files for version: 0.12.4
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: self signed certificate
[ERROR] gyp ERR! stack     at Error (native)
[ERROR] gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
[ERROR] gyp ERR! stack     at TLSSocket.emit (events.js:104:17)
[ERROR] gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
[ERROR] gyp ERR! System Linux 3.8.13-16.2.1.el6uek.x86_64
[ERROR] gyp ERR! command "/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node/node" "/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[ERROR] gyp ERR! cwd /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node_modules/node-sass
[ERROR] gyp ERR! node -v v0.12.4
[ERROR] gyp ERR! node-gyp -v v3.4.0
[ERROR] gyp ERR! not ok 
[ERROR] Build failed
[ERROR] npm ERR! Linux 3.8.13-16.2.1.el6uek.x86_64
[ERROR] npm ERR! argv "/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node/node" "/u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.4
[ERROR] npm ERR! npm  v2.10.1
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! node-sass@3.10.0 postinstall: `node scripts/build.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-sass@3.10.0 postinstall script 'node scripts/build.js'.
[ERROR] npm ERR! This is most likely a problem with the node-sass package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node scripts/build.js
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls node-sass
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /u01/workspace/Maven__capturing_dcm_develop-webpad/webpad/webpad-client-backbone/npm-debug.log

Can someone help us?

Thank you very much.

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by atais** [comment]
I know it is closed but it is positioned number 1. on Google, so I might help someone.

We observed this issue only on our machine with Jenkins (CentOS 7) and were clueless what is going on. Checking the logs carefully showed the error:

```
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/var/lib/jenkins/workspace/WSC-SBT/frontend/admin/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/var/lib/jenkins/.node-gyp/5.12.0/include/node -I/var/lib/jenkins/.node-gyp/5.12.0/src -I/var/lib/jenkins/.node-gyp/5.12.0/deps/uv/include -I/var/lib/jenkins/.node-gyp/5.12.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++: Command not found
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
make: Leaving directory `/var/lib/jenkins/workspace/WSC-SBT/frontend/admin/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/lib/jenkins/workspace/WSC-SBT/frontend/admin/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.0-327.28.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/var/lib/jenkins/workspace/WSC-SBT/frontend/admin/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/lib/jenkins/workspace/WSC-SBT/frontend/admin/node_modules/node-sass
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

The source of the issue is this:
```
make: g++: Command not found
```

Resolved with simple
```
yum install gcc-c++
```

Hope others won't have to search through the logs :+1:

**Comment by saper** [comment]
@atais to build node-sass from scratch a decent C++11 compiler is required, and also Python.
