### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by Hypher** [sass/node-sass#1737]
Yeah it's a duplicate of #918 but the problem and solution differs.
On OSX 11 I got that problem right after installing.
I just reopened bash to get it working.
Probably a session/env related problem. But imho that's worth to mention the "solution".
Maybe you have to fix something to make it work on the first time.
Thank you

**Comment by Hypher** [comment]
No comments?

**Comment by xzyfer** [comment]
> Probably a session/env related problem

This is well documented in may other issues. The solution is `npm rebuild node-sass`.

**Comment by saper** [comment]
@Hypher could provide the debug info as documented in the template? It would be good to understand what went wrong here.
