### ISSUE TITLE
why depend on node-gyp

### ISSUE THREAD

**Issue by graingert** [sass/node-sass#1740]
Does this project mean to depend on node-gyp, isn't this always already installed?

It just seems to make npm complain:
```
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 3.10.3
- Node version (`node -v`): v6.7.0
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '6.7.0',
  v8: '5.1.281.83',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '48',
  openssl: '1.0.2j' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): node-sass	3.10.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): redcated@1.0.0 /home/redacted/projects/redacted/frontend
└── node-sass@3.10.1

**Comment by saper** [comment]
We might need a newer node-gyp version than currently supplied with some old npm. "Prefer global"is a strange feature of npm and it seems to be a moving target how to get ot "right".

**Comment by graingert** [comment]
@saper can't you just set the required npm version in the engine field?

**Comment by saper** [comment]
Will it cause a better node-gyp to be automatically installed?

**Comment by graingert** [comment]
it would tell people to upgrade npm

**Comment by xzyfer** [comment]
We have no right to tell people to upgrade their software. Especially when
there are perfectly good solutions in place.

On 6 Oct 2016 1:40 AM, "Thomas Grainger" <notifications@github.com> wrote:

it would tell people to upgrade npm

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/1740#issuecomment-251694639>, or mute
the thread

**Comment by graingert** [comment]
well this line is already doing the upgrade

**Comment by xzyfer** [comment]
I don't see an issue here. It works as is and has worked for a long time. Changing it would mean it stops working for some (many?) people.

**Comment by xzyfer** [comment]
It's installing a known good version of node-gyp, that's locally scope to this package. It's not updating the global npm which, if I understand correctly, is what you're suggesting we tell people to do.

People have the right to run whatever versions of software they want or need to. It's not on us to unnecessarily dictate terms. Where reasonable we should support our users. 

A single line of output from npm is well within reason.
