### ISSUE TITLE
Remove deprecated dependency lodash.assign

### ISSUE THREAD

**Issue by ppitonak** [sass/node-sass#1741]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 3.10.3
- Node version (`node -v`): 6.7.0
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '6.7.0',
  v8: '5.1.281.83',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`): 3.10.1

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

Project depends on deprecated dependency:

```
$ npm install
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
```

**Comment by xzyfer** [comment]
Object.assign is not support in node 0.10 and 0.12 which we still support. IMHO this depreciation warning is a hostile move on behalf of lodash. It has been discussed heavily on Twitter recently.

**Comment by jdalton** [comment]
Just a heads up. I've pulled the deprecation message until 0.12 is dropped in Jan.

**Comment by xzyfer** [comment]
@jdalton thanks this is good to know.

Since this is a build tool and not a production dependency I expect we'll be supporting Node 0.10-0.12 well beyond their EOL.

**Comment by jdalton** [comment]
If and when I add the deprecation back it'll be on a major bump so shouldn't effect folks already using the package.

**Comment by jdalton** [comment]
Also I take issue with your "hostile" comment. The purpose of deprecation is to give devs a heads. I didn't pull functionality (that would have been hostile).
