### ISSUE TITLE
Compiling efficiency

### ISSUE THREAD

**Issue by coxrichuk** [sass/node-sass#1747]
This may not be the best place to ask this question, so please feel free to point me elsewhere.

We have approximately 1000+ SCSS maps which are approximately 400 lines each.

From your experience what is the best way to compile these?

As individuals partials or just send them straight through as data?

We have attempted to compile from a single .scss file, but node-sass just hangs - I assume node-sass can't cope with the file size ...

**Comment by saper** [comment]
How exactly are you trying to compile this? You might be running into some sort of a race condition, like #857

**Comment by xzyfer** [comment]
We have made significant improvements to our memory usage in 4.2 which should help.
