### ISSUE TITLE
Fails to install with node-gyp error

### ISSUE THREAD

**Issue by alex321** [sass/node-sass#1749]
Hey,

I am trying to install node-sass and am running into this error from node-gyp. I tried to attach the log file but it failed. 
Node: 6.8.0 (tried with 6.2.2 as well)
npm: 3.10.8 
node-gyp: 3.4.0

gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\dev\\firebase-starter-pack\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
C:\dev\firebase-starter-pack\node_modules\node-gyp\gyp\pylib\gyp\input.py:888: Warning: 'as' will become a reserved keyw
ord in Python 2.6
Traceback (most recent call last):
  File "C:\dev\firebase-starter-pack\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\dev\firebase-starter-pack\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\dev\firebase-starter-pack\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 888
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\dev\firebase-starter-pack\node_modules\node-gyp\lib\configure.js:305:16)

gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\firebase-starter-pack\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\dev\firebase-starter-pack\node_modules\node-sass
gyp ERR! node -v v6.8.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm WARN firebase-starter-pack@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.1 (node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by alex321** [comment]
Using the timeless method of trial and error, I managed to get it working with Python v.2.7.12. It is highly unfortunate as the check that it performs for python is >2.5.0 and <3. 

Good luck to anybody else out there!

**Comment by stevematdavies** [comment]
Ive had this issue for months on Mojave with latest node npm and node-sass and i have yet tohave it fixed with any solutions here. We have even reverted to css because of it

**Comment by nschonni** [comment]
@stevematdavies please open a new issue and follow the template
