### ISSUE TITLE
Compact Output Style add a line break between all properties

### ISSUE THREAD

**Issue by afmarchetti** [sass/node-sass#1754]
Hi, thank you for you amazing job, maybe  i found a bug, when node-sass compile and output the css code in compact form the CSS have a line break between all the properties.

Like sass the documentation say the correct logic would be:

"Nested rules are placed next to each other with no newline, while separate groups of rules have newlines between them"

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_15

You can see the problem here:

<img width="509" alt="5b8e755c-958a-11e6-91a7-225572780496" src="https://cloud.githubusercontent.com/assets/8080212/19548144/e717608a-969c-11e6-8a50-c1a291f1fc67.png">
<img width="449" alt="5a4eb4fe-958a-11e6-86b3-d195c7741bad" src="https://cloud.githubusercontent.com/assets/8080212/19548145/e71842ca-969c-11e6-88bc-1434abc04d3a.png">

Thank you again,
have  a nice day,

Andrea Marchetti

MarchettiDesign.net

**Comment by xzyfer** [comment]
This is a LibSass issue. Output style issues are their lowest priority so this is likely not to be fixed since it's close enough.

**Comment by afmarchetti** [comment]
Sorry but this is not correct, how can i try to solve the problem? I want maintain node as a compiler, please let me know.
