### ISSUE TITLE
Unable to do npm install node-sass

### ISSUE THREAD

**Issue by ravichandrut** [sass/node-sass#1755]
Hi,

My working environment is proxy and firewall protected, I have done the proxy setting and trying for npm install, some package installed properly, But the gulp-sass package not installed.

OS-windows 8.1 enterprise

only the specific node-sass is failing

Kindly help to resolve the issue

- NPM version (`npm -v`):3.10.8
- Node version (`node -v`):v4.6.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '4.6.1',
  v8: '4.5.103.37',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2j' }

- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`):ia32
- node-sass version (`node -p "require('node-sass').info"`):node-sass@3.10.1
- npm node-sass versions (`npm ls node-sass`):

Kindly find the below FYR.

C:\Users\588834\Ravi\Temp4>npm install node-sass
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> bufferutil@1.2.1 install C:\Users\588834\Ravi\Temp4\node_modules\bufferutil
> node-gyp rebuild

C:\Users\588834\Ravi\Temp4\node_modules\bufferutil>if not defined npm_config_nod
e_gyp (node "C:\Users\588834\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuil
d )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._
finishInit (_tls_wrap.js:586:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ss
l.onhandshakedone (_tls_wrap.js:428:38)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\588834\
\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp
.js" "rebuild"
gyp ERR! cwd C:\Users\588834\Ravi\Temp4\node_modules\bufferutil
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> utf-8-validate@1.2.1 install C:\Users\588834\Ravi\Temp4\node_modules\utf-8-val
idate
> node-gyp rebuild

C:\Users\588834\Ravi\Temp4\node_modules\utf-8-validate>if not defined npm_config
_node_gyp (node "C:\Users\588834\AppData\Roaming\npm\node_modules\npm\bin\node-g
yp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" re
build )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._
finishInit (_tls_wrap.js:586:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ss
l.onhandshakedone (_tls_wrap.js:428:38)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\588834\
\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp
.js" "rebuild"
gyp ERR! cwd C:\Users\588834\Ravi\Temp4\node_modules\utf-8-validate
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> node-sass@3.10.1 install C:\Users\588834\Ravi\Temp4\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/
v3.10.1/win32-ia32-46_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.1/win
32-ia32-46_binding.node":

tunneling socket could not be established, statusCode=403

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.10.1 postinstall C:\Users\588834\Ravi\Temp4\node_modules\node-sass

> node scripts/build.js

Building: C:\Program Files (x86)\nodejs\node.exe C:\Users\588834\Ravi\Temp4\node
_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cfl
ags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\588834\\Ravi\\Temp4\\node_modules\\node-gyp\\bin\\nod
e-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\588834\Ravi\Temp4\node
_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\588834\Ravi\Temp4\node_modules\which\
which.js:69:19)
gyp verb `which` failed     at E (C:\Users\588834\Ravi\Temp4\node_modules\which\
which.js:81:29)
gyp verb `which` failed     at C:\Users\588834\Ravi\Temp4\node_modules\which\whi
ch.js:90:16
gyp verb `which` failed     at C:\Users\588834\Ravi\Temp4\node_modules\isexe\ind
ex.js:44:5
gyp verb `which` failed     at C:\Users\588834\Ravi\Temp4\node_modules\isexe\win
dows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print
(platform.python_version());"` returned: "2.7.12\r\n"
gyp verb get node dir no --target version specified, falling back to host node v
ersion: 4.6.1
gyp verb command install [ '4.6.1' ]
gyp verb install input version string "4.6.1"
gyp verb install installing version: 4.6.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 4.6.1
gyp verb ensuring nodedir is created C:\Users\588834\.node-gyp\4.6.1
gyp verb created nodedir C:\Users\588834\.node-gyp\4.6.1
gyp http GET https://nodejs.org/download/release/v4.6.1/node-v4.6.1-headers.tar.
gz
gyp verb download using proxy url: "http://proxy.cognizant.com:6050/"
gyp WARN install got an error, rolling back install
gyp verb command remove [ '4.6.1' ]
gyp verb remove using node-gyp dir: C:\Users\588834\.node-gyp
gyp verb remove removing target version: 4.6.1
gyp verb remove removing development files for version: 4.6.1
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._
finishInit (_tls_wrap.js:586:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ss
l.onhandshakedone (_tls_wrap.js:428:38)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\588834\
\Ravi\\Temp4\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "-
-libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\588834\Ravi\Temp4\node_modules\node-sass
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32
"})
npm WARN ResiliencePlatform@1.1.0 No description
npm WARN ResiliencePlatform@1.1.0 No repository field.
npm WARN ResiliencePlatform@1.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\b
ufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-
gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.1 (node_modul
es\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.1 install: `n
ode-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\588834\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.10.1 postinstall script 'node scripts/build.j
s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\588834\Ravi\Temp4\npm-debug.log

**Comment by xzyfer** [comment]
You proxy is not configured correctly.


```
Start downloading binary at https://github.com/sass/node-sass/releases/download/
v3.10.1/win32-ia32-46_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.1/win
32-ia32-46_binding.node":

tunneling socket could not be established, statusCode=403

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080
```

**Comment by xzyfer** [comment]
>statusCode=403

Implied github.com is blocked
