### ISSUE TITLE
How to exclude a specific folder using CLI

### ISSUE THREAD

**Issue by yaooluu** [sass/node-sass#1759]
Hi, my project has the following structure:

/app
/app/folderA
/app/folderB
/app/node_modules

I'm trying to use this command to compile my SCSS files under folderA and folderB. 
`node-sass --recursive 'app' --output 'build/app'`, however this will also compile the SCSS files in node_modules. Is there an option that I can use to exclude `node_modules` folder in this case?

I've tried this, `node-sass --recursive ['app/folderA', 'app/folderB'] --output 'build/app'`, which doesn't work, giving the error `No input file was found`.

**Comment by xzyfer** [comment]
No this is not possible with the CLI.

**Comment by xzyfer** [comment]
I recommend calling calling node-sass CLI once per directory.

**Comment by sant123** [comment]
@xzyfer I think this feature would be really good. Some people (like me) in small projects puts every .scss file into the root, the problem happens when `node_modules` folder is there; node-sass will try to compile some .scss files inside the folder and that's bad. 😢

**Comment by arxpoetica** [comment]
Hear hear. Excludes for the win.

**Comment by NoelAbrahams** [comment]
I've run into a related problem. My output directory is a sub-directory of the watched directory, e.g.

```
/app
/app/folderA
/app/folderB
/app/node_modules
/app/output  <----output directory
```

When the `/app` directory is watched recursively, every changed `.scss` file results in 2 output files. First `/app/folderA/file.scss` is output to `/app/output/folderA/file.css`; this in turn triggers a second compilation and I get another output file at `/app/output/output/folderA/file.css`.

While this may be a bug in itself (also not sure why `.css` files are being watched), if I can exclude `/app/output` from being watched, then that would solve the problem.

Furthermore, in our case the build process tries to remove the output directory and if it is being watched, I'm getting access denied errors.

**Comment by xzyfer** [comment]
Folders cannot be excluded with the cli. The output folder cannot be inside
the input folder.

**Comment by xzyfer** [comment]
.CSS files can be imported with node-sass so they must be watched. This is
why this restriction exists.

**Comment by NoelAbrahams** [comment]
> Folders cannot be excluded with the cli

Yes... any chance of re-opening this issue in the light of these use-cases?

Having the output folder in the watched directory is very common for Visual Studio projects.

**Comment by xzyfer** [comment]
It's really not possible without changing how @import works which cannot be
done. You can maybe try using includePath to include only the folder you
want watched, without a source folder.
