### ISSUE TITLE
Conversion of files starting with _

### ISSUE THREAD

**Issue by dcpanda18** [sass/node-sass#1761]
We are using the gulp-sass plugin which is based on node-sass. We faced a weird issue that whenever we pass a file starting with "_" to the plugin it doesn't convert it into the css and discard the file altogether. 

So for example we try it with _test.scss and it yields no result but when we try with test.scss then it process the file. Is it something known.

**Comment by xzyfer** [comment]
This is the correct behaviour. Files beginning with an `_` are called partials and are never compiled by Sass.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials
