### ISSUE TITLE
dyld: Symbol not found: _uv_mutex_init

### ISSUE THREAD

**Issue by billwing** [sass/node-sass#1762]
dyld: lazy symbol binding failed: Symbol not found: _uv_mutex_init
       Referenced from: /Users/bill/Projects/mcore/node_modules/node-sass/vendor/darwin-x64-48/binding.node
       Expected in: flat namespace

    dyld: Symbol not found: _uv_mutex_init
       Referenced from: /Users/bill/Projects/mcore/node_modules/node-sass/vendor/darwin-x64-48/binding.node
       Expected in: flat namespace
    
    make: *** [dev] Trace/BPT trap: 5

    node: v6.9.1
    npm: 3.10.8
    node-sass: 3.10.1

This issue occurs when I use webpack build the sass files.

**Comment by xzyfer** [comment]
You've decided to ignore the instructions for opening an issue. As a result we don't have the information we need to help you. Please open a new issue following the instructions provided in the new issue template.
