### ISSUE TITLE
Missing binding for Windows x64-51

### ISSUE THREAD

**Issue by JonathanWolfe** [sass/node-sass#1765]
## Errors saying not compatible with platform and version.

- NPM version: `3.10.9`
- Node version: `7.0.0`
- Node Platform: `win32`
- Node architecture: `x64`
- node-sass version:
```
node-sass       3.10.1  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```
- npm node-sass versions: `3.10.1`

### Let me know if this should be moved to LibSass

**Comment by saper** [comment]
We do not have binaries for node 7.0. You might either recompile the binding yourself or downgrade your node installation.

**Comment by nschonni** [comment]
You can subscribe to #1766
