### ISSUE TITLE
Request for '--log', or '-l' cli flag for logfile

### ISSUE THREAD

**Issue by jeff1evesque** [sass/node-sass#1767]
I will most likely [implement](https://github.com/jeff1evesque/machine-learning/blob/99e7c86c6c9f429615cc10a552f3f48c49fe7a60/puppet/environment/vagrant/modules/compiler/manifests/start_sass.pp#L20) `node-sass` with a watcher:

```bash
node-sass -w "$1"/src/scss/ -o "$1"/interface/static/css/ --output-style compressed &
```

It would be nice if I could add a `--log /path/to/my/logfile.txt` to the above command, with the intention that all stdout from any watch invocations, would get logged into `logfile.txt`:

```bash
node-sass -w "$1"/src/scss/ -o "$1"/interface/static/css/ --log /path/to/my/logfile.txt --output-style compressed &
```

The reason I'd like to have this feature, is because my earlier implementation of `node-sass` had a hack of an [implementation](https://github.com/jeff1evesque/machine-learning/blob/master/puppet/environment/vagrant/modules/compiler/scripts/sass#L20-L24) using `inotifywait`:

```bash
# track execution of script
log_file="$1"/log/webcompiler/sass.log
set -x;
exec &> >(while read -r line; do
  log_date=$(date +%Y-%m-%d:%H:%M:%S)
  printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
done)

# watch '[root_dir]/src/scss/' subdirectory
inotifywait "$1"/src/scss/ -m -r -e close_write -e move |

  # compile with 'scss'
  node-sass "$1"/src/scss/style.scss "$1"/interface/static/css/style.min.css --output-style compressed
```

Anytime the `node-sass` executes, any stdout, including errors, would get stored into `/vagrant/log/webcompiler/sass.log`.  I'd like to have this implementation, if I were to replace the latter hack with `inotifywait`, when I use the inherent `node-sass` watcher.

**Comment by xzyfer** [comment]
Sorry but this is not something we will implement. The CLI's duty is to turn Sass into CSS. Anything outside of that is considered out of scope unless there is significant demand.

Piping to standard out gives a lot flexibility for the vast majority of users. Anything beyond should be handled in a higher level tool, or a build pipeline task.

**Comment by jeff1evesque** [comment]
Thank you @xzyfer, I' m sure your suggestion will work, and I will attempt piping the watcher:

```bash
node-sass -w "$1"/src/scss/ -o "$1"/interface/static/css/ --output-style compressed & | tee -a /vagrant/log/webcompiler/sass.log
```

**Comment by jeff1evesque** [comment]
@xzyfer, got my sass logger [working](https://github.com/jeff1evesque/machine-learning/pull/2778#issuecomment-256341265).
