### ISSUE TITLE
Request for '--minpath', or '-mp' cli flag

### ISSUE THREAD

**Issue by jeff1evesque** [sass/node-sass#1769]
I will most likely [implement](https://github.com/jeff1evesque/machine-learning/blob/99e7c86c6c9f429615cc10a552f3f48c49fe7a60/puppet/environment/vagrant/modules/compiler/manifests/start_sass.pp#L20) `node-sass` with a watcher:

```bash
node-sass -w "$1"/src/scss/ -o "$1"/interface/static/css/ --output-style compressed &
```

However, the result of the above watcher will generate filesnames that end with `*.css` extension.  I think for some cases it would be preferable if the compiled asset would signify that `--output-style compressed` was implemented, in my cases by the file extension.  Specifically, if I had a source `style.css`, and `node-sass` compiled it, I'd like the file to be called `style.min.css`.

I attempted to [workaround](https://github.com/jeff1evesque/machine-learning/blob/master/puppet/environment/vagrant/modules/compiler/scripts/sass#L20-L24) with `inotifywait`.  This implementation worked for most cases, except on initial `vagrant up` build, I needed to `sudo service sass restart`, to get it to work after initial `touch` of all files in specific directories for an initial compilation:

```bash
# track execution of script
log_file="$1"/log/webcompiler/sass.log
set -x;
exec &> >(while read -r line; do
  log_date=$(date +%Y-%m-%d:%H:%M:%S)
  printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
done)

# watch '[root_dir]/src/scss/' subdirectory
inotifywait "$1"/src/scss/ -m -r -e close_write -e move |

  # compile with 'scss'
  node-sass "$1"/src/scss/style.scss "$1"/interface/static/css/style.min.css --output-style compressed
```

But, setting aside bad practices, any attempt via puppet to restart my `sass` service was ignored (after initial `vagrant up`), even though in the virtual machine, a manual attempt refreshed the sass compiler (or even `sudo reboot`).  This is why I have converted the above syntax to more of a `node-sass` syntax implementation.

**Comment by jeff1evesque** [comment]
I think this request is more appropriate for this repository than other add-on [packages](https://github.com/armin-pfaeffle/sass-autocompile/issues/97).  If the reliance is placed on other packages, then they would likely have to implement their own watcher (~2x more resource intensive) just to adjust the compiled file extensions adjusted, unless other packages knew how to cleverly hook into `node-sass`, which puts a burden on requiring another package.

**Comment by jeff1evesque** [comment]
Perhaps this could be a default behavior, with an option to remove the appended filename.

**Comment by xzyfer** [comment]
Sorry but this is not something we will implement. The CLI's duty is to turn Sass into CSS. Anything outside of that is considered out of scope unless there is significant demand.

This functionality belongs in a higher level tool, or a build pipeline task.

**Comment by jeff1evesque** [comment]
How would a build pipeline tool know that a compiled asset is minified?

**Comment by xzyfer** [comment]
Compressed output is a poor substitute for minification. I suggest handling
compression as a separate concern as a post process.

On 26 Oct 2016 10:36 PM, "Jeff Levesque" <notifications@github.com> wrote:

How would a build pipeline tool know that a compiled asset is minified?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/issues/1769#issuecomment-256321934>, or mute
the thread
