### ISSUE TITLE
Gulp Failed at the node-sass@0.9.6 install script 'node build.js'.

### ISSUE THREAD

**Issue by mdunbavan** [sass/node-sass#1770]
Hi,

I've ran into an issue on my mac osx sierra 10.12.1.

Heres a breakdown below of what I am using:

- NPM version (`npm -v`): 
`3.10.9`
- Node version (`node -v`): 
`7.0.0`
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '7.0.0',
  v8: '5.4.500.36',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '51',
  openssl: '1.0.2j' }
```
- Node Platform (`node -p process.platform`):
darwin
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
```
module.js:474
    throw err;
    ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:32)
    at bootstrap_node.js:345:29
```
- npm node-sass versions (`npm ls node-sass`):
```
/Users/mdunbavan
└─┬ gulp-sass@2.3.2
  └── node-sass@3.10.1
```
The stack trace of the error I get is in this gist file here: http://bit.ly/2eGRfaM

Thanks,
Mark

**Comment by nschonni** [comment]
0.9.6 is very old and will not support node 7. Follow #1766 for when the support is added to the latest version

**Comment by mdunbavan** [comment]
I have updated node-sass globally but I still get the error when doing `npm install` in my project folder, when I run `npm ls node-sass` I get this:

```
├─┬ gulp-sass@2.3.2
│ └── node-sass@3.10.1
└── node-sass@3.10.1
```

This looks okay but do you think its gulp sass thats breaking it @nschonni ?
