### ISSUE TITLE
Icon fonts don't render correctly - backslash stripped

### ISSUE THREAD

**Issue by dmk12** [sass/node-sass#1771]
In my source scss file I have this to render a font icon (note the backslash before character code):
```
.icon-check:before {
    content: "\e900";
}
```
After running the plugin I get the following (note backslash is stripped):
```
.icon-check[_ngcontent-lcj-2]:before{content:"e900"}
```

Tried all outputStyle options, no luck.

**Comment by xzyfer** [comment]
You haven't followed the instructions shows when opening an issue. As a result we don't have the information we need to help you. Please open a new issue following the instructions provided in the new issue template.
