### ISSUE TITLE
How to get the env variables in sass file

### ISSUE THREAD

**Issue by ManitoYu** [sass/node-sass#1778]
I have a need that compiles sass file in different env, but I haven't an idea.

**Comment by xzyfer** [comment]
The best way to do this is by using include paths.

```
|- sass
  |- index.scss
  |- production
    |- settings
      |- settings.scss
  |- development
    |- settings
      |- settings.scss
```
```
// index.scss
@import "settings/settings";
```
```js
var settingsPath = 'sass/development';
if (process.NODE_ENV == 'production') {
  settingsPath = 'sass/production';  
}

sass.render({
  includePaths: ['.', settingsPath],
})
```

**Comment by nschonni** [comment]
The only environment variable that is read (for import paths only) is [$SASS_PATH](https://github.com/sass/node-sass/issues/1719). If you are looking for anything else, you'd need to write a custom importer on your own.

**Comment by ManitoYu** [comment]
thanks so much.
