### ISSUE TITLE
Paths to icon fonts being expanded incorrectly

### ISSUE THREAD

**Issue by atrauzzi** [sass/node-sass#1779]
I have an SCSS file in my project that is referencing this file: https://github.com/google/material-design-icons/blob/master/iconfont/material-icons.css in my `node_modules` directory.

Unfortunately, it seems like node-sass is expanding the URI such that the generated CSS is now: `url(../../node_modules/material-design-icons-iconfont/dist/fonts/MaterialIcons-Regular.woff2)`

This obviously doesn't work once things hit the browser as our CSS is built into a completely separate directory structure.  Is there any way to tell node-sass to not do any kind of special treatment to `url`s, and just pass them through to the outputted CSS as-is?

- NPM version (`npm -v`): 2.15.5
- Node version (`node -v`): v4.4.5
- Node Process (`node -p process.versions`): 
```
{ 
  http_parser: '2.5.2',
  node: '4.4.5',
  v8: '4.5.103.35',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2h' 
}
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 3.10.1

**Comment by xzyfer** [comment]
I can't think of anyway node-sass could be changing those paths. Are you sure you're not using a custom importer to PostCSS plugin?

**Comment by xzyfer** [comment]
I'm fairly certain this is not a node-sass issue.

**Comment by atrauzzi** [comment]
Sorry, was on holiday.

No, I'm not using any custom importer to PostCSS plugin -- not even sure what those are :)

**Comment by xzyfer** [comment]
Can you please provide an example of this issue in a http://www.sassmeister.com/
