### ISSUE TITLE
gulp-sass

### ISSUE THREAD

**Issue by Desirez** [sass/node-sass#1790]
I'm using windows 10, node v7.0, npm v3.10.8 

trying to install gulp-sass following error. don't know what to do 

<details>
<summary>Log</summary>
C:\Users\abdur\Desktop\Projcts_HOC\proj>npm i gulp-sass --save-dev
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.11.2 install C:\Users\abdur\Desktop\Projcts_HOC\proj\node_modules\node-sass
> node scripts/install.js

npm WARN app@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "gulp-sass" "--save-dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.11.2 install: `node scripts/install.js`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the node-sass@3.11.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm WARN app@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "gulp-sass" "--save-dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! file C:\WINDOWS\system32
npm ERR! path C:\WINDOWS\system32
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32

npm ERR! node-sass@3.11.2 install: `node scripts/install.js`
npm ERR! spawn C:\WINDOWS\system32 ENOENT
npm ERR!
npm ERR! Failed at the node-sass@3.11.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\abdur\Desktop\Projcts_HOC\proj\npm-debug.log
</details>

**Comment by yukoff** [comment]
Same here - I never managed to get node-sass working on windows (I used v4.5.0/v6.4.0 previously, currently - v4.6.1, v4.9.1 & v7.0.0) - result always the same:
* on v4.5.0
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Apps\\node-v4.5.0-win-x64\\node.exe" "D:\\Apps\\node-v4.5.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! @ gulp: `gulp`
npm ERR! Exit status 1
```

* on v6.9.1
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Apps\\node-v6.9.1-win-x64\\node.exe" "D:\\Apps\\node-v6.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ gulp: `gulp`
npm ERR! Exit status 1
```

**Comment by nschonni** [comment]
Sounds similar to https://github.com/sass/node-sass/issues/1012#issuecomment-115715502

**Comment by yukoff** [comment]
I have nothing neither in ('HKCU:Software\Microsoft\Command Processor').Autorun nor in ('HKLM:Software\Microsoft\Command Processor').Autorun

**Comment by saper** [comment]
Do you have node-sass's binding.node somewhere in node_modules? If yes, which directory is it in?

**Comment by xzyfer** [comment]
Closing as awaiting response
