### ISSUE TITLE
node-sass fails to install with npm

### ISSUE THREAD

**Issue by FlemmingBehrend** [sass/node-sass#1791]
Getting the following error when trying to install node-sass:

D:\temp\sasstest>node -p process.env.comspec
C:\windows\system32\cmd.exe

D:\temp\sasstest>npm -v
3.10.8

D:\temp\sasstest>node -v
v6.9.0

D:\temp\sasstest>node -p process.versions
{ http_parser: '2.7.0',
  node: '6.9.0',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }

D:\temp\sasstest>node -p process.platform
win32

D:\temp\sasstest>node -p process.arch
x64

D:\temp\sasstest>npm cache clean

D:\temp\sasstest>npm install -ddd node-sass > npm.log 2> npm.err

D:\temp\sasstest>dir
 Disken i drev D er DATA
 Diskens serienummer er 3C68-9ED2

 Indhold af D:\temp\sasstest

07-11-2016  11:20    <DIR>          .
07-11-2016  11:20    <DIR>          ..
07-11-2016  11:20    <DIR>          node_modules
07-11-2016  11:20           755.744 npm-debug.log
07-11-2016  11:20         2.095.875 npm.err
07-11-2016  11:20               601 npm.log
               3 fil(er)        2.852.220 byte
               3 mappe(r)   4.311.171.072 byte ledig

D:\temp\sasstest>npm ls node-sass
D:\temp\sasstest
`-- (empty)

npm ERR! code 1

[npm.log](https://gist.github.com/FlemmingBehrend/7e45045c2dee4bdf51ffec36a1adbdc7)  
[npm.err](https://gist.github.com/FlemmingBehrend/56345efc5659debb61c705d7bdbe94a5)

**Comment by xzyfer** [comment]
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.11.2/win32-x64-48_binding.node": 

connect ETIMEDOUT 192.30.253.113:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

**Comment by xzyfer** [comment]
Looks like you're having networking issues. Are you able to download the binary directly?

> https://github.com/sass/node-sass/releases/download/v3.11.2/win32-x64-48_binding.node

**Comment by FlemmingBehrend** [comment]
I can download it directly, but setting the http_proxy and https_proxy seemed to solve the problem.

Closing this issue as it seams to be network settings at my company.

**Comment by muhamed87** [comment]
What did you do to fix the problem please?

**Comment by gowthamaraj** [comment]
This error says that npm could not download the xxx.node file. 

**solution:**

1. Check whether you can download the file using the browser.
2. If it is not getting downloaded in the browser and getting network timeout, then you know that there is a problem with your internet.
3. check your internet. Try changing to different internet provider. 
4. The time you able to access it from the browser, you will be able to install also.

**Comment by muhamed87** [comment]
> This error says that npm could not download the xxx.node file.
> 
> **solution:**
> 
> 1. Check whether you can download the file using the browser.
> 2. If it is not getting downloaded in the browser and getting network timeout, then you know that there is a problem with your internet.
> 3. check your internet. Try changing to different internet provider.
> 4. The time you able to access it from the browser, you will be able to install also.

Yes I already downloaded it from the browser and every thing works fine, the problem is that I'm working on a bank and we suffer with the network team limitations :D

Anyway, thank you :)
