### ISSUE TITLE
Issue installing via alternative npm registiry

### ISSUE THREAD

**Issue by joshdanhall** [sass/node-sass#1795]
Hi,

I am trying to install node-sass from a machine that does not have access to the internet directly. 
I do not have the option of setting a proxy, as the proxy is unavailable from this build server.
Packages must be installed via Artifactory (strict corporate requirement). For all other packages, this works fine once I have set the npm alternate registry via the following command:
`npm config set registry https://our.protected.com/artifactory/api/npm/our-artifactory-npm-registry`

However for node-sass, it fails with the following error:
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.11.2/linux-x64-48_binding.node": 
getaddrinfo ENOTFOUND github.com github.com:443
```

So it looks like in the case of node-sass, the npm registry setting is being ignored?

Please advise how I can install node-sass via the alternate npm registry?

Environment info requested as follows:
```
npm -v
3.10.8
node -v
v6.9.1
node -p process.versions
{ http_parser: '2.7.0',
   node: '6.9.1',
   v8: '5.1.281.84',
   uv: '1.9.1',
   zlib: '1.2.8',
   ares: '1.10.1-DEV',
   icu: '57.1',
   modules: '48',
   openssl: '1.0.2j' }
node -p process.platform
linux
node -p process.arch
x64
```

Many thanks.

**Comment by xzyfer** [comment]
Node Sass pulls down a binary from github, which is causing this error. You have two options.

1) compile the binary locally every time. This should happen automatically if node-sass is unable to download the remote binary.

2) mirror the release binaries somewhere you can access and use the documented environment variables to let node-sass know where your binaries are hosted. https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by joshdanhall** [comment]
Thanks @xzyfer . Perfect, that's fixed my issue ;)

**Comment by saper** [comment]
@regrag see the solutions given by @xzyfer below. If you build/download the binary and put it into the vendor directory there will be no problem.
