### ISSUE TITLE
shade() seems to be broken

### ISSUE THREAD

**Issue by khankuan** [sass/node-sass#1797]
Sass
```
$white: #ffffff

$grayish: shade($white, 60%)

.test
  color: $grayish
```

Output
```
.test {
  color: #666666;
}
```

It seems to working back in v3.4.

- NPM version (`npm -v`):
3.8.8

- Node version (`node -v`):
4.4.3

- Node Process (`node -p process.versions`):
{ http_parser: '2.5.2',
  node: '4.4.3',
  v8: '4.5.103.35',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2g' }

- Node Platform (`node -p process.platform`):
darwin

- Node architecture (`node -p process.arch`):
x64

- node-sass version (`node -p "require('node-sass').info"`):
3.11.2

- npm node-sass versions (`npm ls node-sass`):
3.11.3

**Comment by xzyfer** [comment]
Where is `shade` defined?

**Comment by nschonni** [comment]
On Sassmeister, I'm only seeing it work on Ruby Sass 3.4
This appears to be a Compass thing https://css-tricks.com/snippets/sass/tint-shade-functions/, so I'm not sure why it worked in any version

**Comment by xzyfer** [comment]
Sounds like you're using compass. Compass will never work with node-sass. Use http://bourbon.io/docs/#tint-shade instead.

**Comment by khankuan** [comment]
My bad, just realized it's a bourbon feature. Thanks for helping!

**Comment by xzyfer** [comment]
If you're using bourbon and it's producing different output then it would be a node-sass bug. Please let us know if this is the case.
