### ISSUE TITLE
Failing to build node-sass on AIX

### ISSUE THREAD

**Issue by gdams** [sass/node-sass#1802]
- NPM version (`npm -v`): v3.10.8
- Node version (`node -v`): v6.9.1
- Node Process (`node -p process.versions`): n/a
- Node Platform (`node -p process.platform`): aix
- Node architecture (`node -p process.arch`): ppc64
- node-sass version (`node -p "require('node-sass').info"`): 3.12.2
- npm node-sass versions (`npm ls node-sass`): empty?

when trying to build node-sass on aix I get the following error:
```
gyp info spawn gmake
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
gmake: 0403-030 The fork function failed. Too many processes already exist.
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/home/georgeadams95/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System AIX 1
gyp ERR! command "/home/georgeadams95/.nvm/versions/node/v6.9.1/bin/node" "/home/georgeadams95/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/georgeadams95/node-sass
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
ERR! node-sass build Build failed with error code: 1

npm ERR! AIX 1
npm ERR! argv "/home/georgeadams95/.nvm/versions/node/v6.9.1/bin/node" "/home/georgeadams95/.nvm/versions/node/v6.9.1/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.12.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.12.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

```
It looks like a memory issue (`gmake: 0403-030 The fork function failed. Too many processes already exist.`)

The question is, why should aix require so much more memory to build node-sass?

Any help appreciated

**Comment by nschonni** [comment]
> Any help appreciated

Sorry, AIX/PowerPC isn't supported by node so we can't really help you

**Comment by gibfahn** [comment]
@nschonni As of Node v6 they are. https://nodejs.org/en/download/

**Comment by GeorgeAdams95** [comment]
@nschonni I don't expect you to be able to test on AIX, but if I can identify the source of the issue would you consider a PR?

**Comment by xzyfer** [comment]
@GeorgeAdams95 both LibSass and Node Sass are open to PRs that enable support on new platforms. However cannot officially support new platforms without someone experienced in that system, and willing to maintain support for it, joins our team.

**Comment by saper** [comment]
The message `gmake: 0403-030 The fork function failed. Too many processes already exist.` is pretty clear - you are hitting the limit of the number of processes running on the system or for the user. You need to check your limits.

**Comment by xzyfer** [comment]
Closing this since we don't have the resources to support AIX, and noone has stepped up to champion it.

**Comment by phpdave** [comment]
FYI for anyone else running into this problem I'm getting the same issue and here's the npm-debug.log if anyone is brighter than I and understands whats going wrong I'd love to understand.  Thanks!

https://gist.github.com/phpdave/b67651344010ac47620b4384c0d82649

**Comment by phpdave** [comment]
Also https://spaces.litmis.com/ offers a place to try out building on AIX on i

**Comment by phpdave** [comment]
Even though npm fails there is a binary for node-sass which throws an unsupportedEnvironment so I guess that would need to be PR changed before this would work.
```
[usriva5l@SPACES]~/node_modules/node-sass% ~/node_modules/node-sass/bin/node-sass
/home/USRIVA5L/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Unsupported platform (aix) Unsupported architecture (ppc) with Node.js 6.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (/home/USRIVA5L/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/USRIVA5L/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/USRIVA5L/node_modules/node-sass/bin/node-sass:11:10)
```
