### ISSUE TITLE
Using deprecated APIs in node v6

### ISSUE THREAD

**Issue by ThePeach** [sass/node-sass#1809]
Recently upgraded to Node 6.9.1 on my project and when running a simple task involving node-sass, I get the following output: 

```
(node) v8::FunctionTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```
The full output is this:
http://pastebin.com/v8yp8NTe

I've read that this is just a warning and can be ignored, but the stack trace is a bit verbose as you can see and wondering when this is going to be addressed.

The gulp task invoked is the following:

```JS
var gulp = require( 'gulp' );
var sass = require( 'gulp-sass' );

var cssInput = './source/css/**/*.scss';
var cssOutput = './public/css';
var sassOptions = {
  errLogToConsole: true,
  outputStyle    : 'expanded',
  includePaths   : [
    './node_modules/susy/sass/',
    './node_modules/breakpoint-sass/stylesheets'
  ]
};

gulp.task( 'sass:style', function () {
  gulp.src( cssInput )
  .pipe( sass( sassOptions ).on( 'error', sass.logError ) )
  .pipe( gulp.dest( cssOutput ) );
});
```

### detailed versions
- NPM version (`npm -v`): 3.10.8
- Node version (`node -v`): v6.9.1
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
```
node-sass       3.7.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@3.7.0

**Comment by marvinhagemeister** [comment]
Have you tried using a more recent sass version? The latest published version of node-sass on npm is `3.13.0`

**Comment by xzyfer** [comment]
Node 6 support was added in 3.7.0. They have deprecated other APIs in releases since then. Try a newer node-sass release. If the problem persists we can look at making new binaries for Node 6.

**Comment by ThePeach** [comment]
@marvinhagemeister thank you for your reply, I didn't notice the semver in `package.json` had me locked with that version.

I've now installed version `3.13.0` and I get the same stack trace, starting with:

``` 
(node) v8::FunctionTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

Relevant changes:
```
$ node -p "require('node-sass').info"
node-sass       3.13.0  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```

`npm ls node-sass`: `node-sass@3.13.0`

Apparently this bug is still valid @xzyfer .

**Comment by xzyfer** [comment]
@ThePeach I can't imagine why you're getting this warning. I am unable to reproduce this on OSX or Linux. 

What OS/distro are you on?
How are you installing Node?
What command are you running?
Can you provide a sample .scss file producing this warning?

**Comment by ThePeach** [comment]
@xzyfer I'm on Arch Linux (latest). 
Node is installed via `nvm`. 
The initial comment shows the gulpfile.js task that triggers that, by just invoking `gulp sass:style`. 
I can try to get a simple .scss file to see if I can still reproduce that.

**Comment by xzyfer** [comment]
Oh that makes more sense. We don't officially support Arch Linux, so there are some issues. There's not really anything we can do at the moment. We're looking statically compiling the binary with musl but haven't had much luck.

The warning is harmless. If it bothers you, you can build the binary locally with `npm rebuild node-sass --force`.

**Comment by ThePeach** [comment]
@xzyfer thanks for the reply. That makes sense. I'm absolutely in favour to have the binary statically compiled, although it makes me wonder if this is actually a problem with `nvm` rather than ArchLinux at all.

**Comment by xzyfer** [comment]
If you search our issues you'll see some regarding Arch Linux. I don't think nvm is to blame. All in all nvm is pretty simple. It just juggles some symlinks and downloads the release binaries from the Node website.

**Comment by ThePeach** [comment]
@xzyfer apparently doing the `npm rebuild node-sass --force` didn't do much:

```
npm WARN using --force I sure hope you know what you are doing.

> node-sass@3.13.0 install /home/peach/workspace/texan/styleguide/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/peach/workspace/texan/styleguide/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.13.0 postinstall /home/peach/workspace/texan/styleguide/node_modules/node-sass
> node scripts/build.js

Binary found at /home/peach/workspace/texan/styleguide/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
node-sass@3.13.0 /home/peach/workspace/texan/styleguide/node_modules/node-sass
```

after this rebuild nothing changed 😞
