### ISSUE TITLE
Failing to install node-sass in the official node:7.1-alpine docker image

### ISSUE THREAD

**Issue by alexbardas** [sass/node-sass#1810]
- NPM version (`npm -v`): 3.10.9
- Node version (`node -v`): 7.1.0
- Node Process (`node -p process.versions`): { http_parser: '2.7.0', node: '7.1.0', v8: '5.4.500.36', uv: '1.10.0', zlib: '1.2.8', ares: '1.10.1-DEV', modules: '51', openssl: '1.0.2j', icu: '58.1', unicode: '9.0', cldr: '30.0.2', tz: '2016g' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): N/A
- npm node-sass versions (`npm ls node-sass`): N/A

when trying to build node-sass in the node:7.1-alpine docker image I get the following error:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.27-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```
npm-debug.log:
```
89638 verbose stack Error: node-sass@3.13.0 postinstall: `node scripts/build.js`
89638 verbose stack Exit status 1
89638 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
89638 verbose stack     at emitTwo (events.js:106:13)
89638 verbose stack     at EventEmitter.emit (events.js:191:7)
89638 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
89638 verbose stack     at emitTwo (events.js:106:13)
89638 verbose stack     at ChildProcess.emit (events.js:191:7)
89638 verbose stack     at maybeClose (internal/child_process.js:885:16)
89638 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

My understanding is that node 7 and the official node 7 docker alpine image are now fully supported.

**Comment by xzyfer** [comment]
Node 7 is supported however alpine is not so npm will fallback to compiling
the binary locally.

This error sounds like you're running npm as root. This will cause lots of
issues. For you now you run `npm install --unsafe-perm`

**Comment by alexbardas** [comment]
Actually I've managed to compile & build the binary locally (after install python, make and g++ in the alpine container) and this worked. I then encounter a problem when actually running it (symbol was not found).
