### ISSUE TITLE
node-sass package not installing on aix

### ISSUE THREAD

**Issue by Cwill50** [sass/node-sass#1811]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):v3.10.9
- Node version (`node -v`):v7.1.0
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):aix
- Node architecture (`node -p process.arch`):ppc
- node-sass version (`node -p "require('node-sass').info"`): Error  modules.js 474
- npm node-sass versions (`npm ls node-sass`):
npm ERR! peer dep missing: grunt@^1.0.1, required by grunt-nw-builder@2.0.3
npm ERR! code 1

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*
npm WARN grunt-nw-builder@2.0.3 requires a peer of grunt@^1.0.1 but none was installed.
npm ERR! AIX 2
npm ERR! argv "/usr/local/node-v7.1.0/bin/node" "/usr/local/node-v7.1.0/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /wm2k/exe_dev/web/gwc-js/npm-debug.log

**Comment by nschonni** [comment]
AIX isn't a supported platform, you can follow #1802 for the feature request

**Comment by saper** [comment]
@Cwill50 I don't see why `node scripts/build.js` is failing, can try to run it from the node-sass directory and see why it is failing?
