### ISSUE TITLE
Running node-sass on arm, get unsupported architecture

### ISSUE THREAD

**Issue by paulashford1975** [sass/node-sass#1816]
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/scss/style.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 6.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.0

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

PS: ARM isn't a supported architecture for the prebuilt binaries
