### ISSUE TITLE
--sass-binary-path ignored on 'rebuild'

### ISSUE THREAD

**Issue by cambridgemike** [sass/node-sass#1818]
It seems that sass-binary-path is ignored when doing npm rebuild node-sass.

Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 3.8.9
- Node version (`node -v`): 6.2.-0
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.2.0',
  v8: '5.0.71.47',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	3.13.0	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by nschonni** [comment]
I think this is "by design" since rebuild is used to fall back to locally rebuild the binaries instead of using a prebuilt. Did you have an alternate flow in mind?

**Comment by cambridgemike** [comment]
No, I think that makes sense. I just came across this while getting node-sass to rebuild using a different binding on an offline CI.

**Comment by xzyfer** [comment]
Thanks for the query @cambridgemike
