### ISSUE TITLE
Using devtool and iron-node: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime

### ISSUE THREAD

**Issue by lexholden** [sass/node-sass#1821]
I'm creating an app using webpack and sass-loader to build my assets on the fly. Everything works perfectly just running using node, but not when I try run using a debug tools to launch the node process (tried with [devtool](https://www.npmjs.com/package/devtool) and [iron-node](https://www.npmjs.com/package/iron-node)) .

- NPM version (`npm -v`): `v6.9.1`
- Node version (`node -v`): `3.10.8`
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }`
- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`): `node-sass	3.13.0	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]`
- npm node-sass versions (`npm ls node-sass`): only node-sass

It feels like perhaps like `node-sass` won't try unless it explicitly understands the environment and running it within a strange version of chromium throws it for a loop? (total guesswork). I have also tried this on ubuntux64 and Windows.

If the answer isn't as obvious as "We just need to add a line here to accept these runtimes" I can create a small sample app to demonstrate the problem.

The below output is repeated for each `.scss` file in the repo.

```
Hash: [1m45c0ece9cb755f6c847f[22m
Version: webpack [1m1.13.3[22m
Time: [1m17750[22mms
              [1mAsset[22m     [1mSize[22m  [1mChunks[22m  [1m[22m     [1mChunk Names[22m
[1m[32mpolyfills.bundle.js[39m[22m   308 kB       [1m0[22m  [1m[32m[39m[22m     polyfills
     [1m[32mmain.bundle.js[39m[22m   1.7 MB       [1m1[22m  [1m[32m[39m[22m     main
   [1m[32mvendor.bundle.js[39m[22m  2.13 MB       [1m2[22m  [1m[32m[39m[22m     vendor
      [1m[32mpolyfills.map[39m[22m   371 kB       [1m0[22m  [1m[32m[39m[22m     polyfills
           [1m[32mmain.map[39m[22m  1.89 MB       [1m1[22m  [1m[32m[39m[22m     main
         [1m[32mvendor.map[39m[22m  2.39 MB       [1m2[22m  [1m[32m[39m[22m     vendor

[1m[31mERROR in 
/.../node_modules/sass-loader/index.js

/.../node_modules/node-sass/lib/index.js
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (50)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.0
 @ ./src/core/ui/styles/main.scss 4:14-133 13:2-17:4 14:20-139[39m[22m
```

**Comment by saper** [comment]
There is some confusion in your report. The debug output we are asking for shows a perfectly running node-sass on node runtime 48. That one works.

**Comment by oreqizer** [comment]
Got a similar error, 1st time today:

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/browser/css/app.scss
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
```

**Comment by xzyfer** [comment]
@oreqizer Node 7 support was not added until 3.11.0. You need to update.

**Comment by xzyfer** [comment]
Native extensions are compiled against a Node runtime. Runtime version 50 is not an official version hence the error you're receiving. It appears your devtool is using it's own version of Node, in which node-sass' native code will need to be recompiled. You can do this with

```
npm rebuild node-sass
```

You'll need to do this within the devtool environment. You can confirm you're in the correct Node environment by checking that the followed returns `50`.

```
console.log(process.versions.modules)
```
