### ISSUE TITLE
What changed in 4.0.0?

### ISSUE THREAD

**Issue by samit4me** [sass/node-sass#1833]
I'm not familiar with this repo at all, sorry, but I do use it, so thank you!

Just noticed a major version bump, but was curious what changed before updating, so took a look at CHANGELOG.md but couldn't find any details. Can anyone shed some light on v4?

**Comment by xzyfer** [comment]
Sorry we need to update changelog. The release notes are on the GH release. There are no breaking API changes, just a large LibSass bump.

**Comment by samit4me** [comment]
Ahhh, today I learn, thank you :+1: 
https://github.com/sass/node-sass/releases
