### ISSUE TITLE
node-sass@4.0.0 can not install in node v6.9.2

### ISSUE THREAD

**Issue by lh8725473** [sass/node-sass#1837]
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sass" "-save-dev"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.0.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by lh8725473** [comment]
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Users/liuhao/my-github/pc-translate/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/liuhao/my-github/pc-translate/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/liuhao/my-github/pc-translate/node_modules/node-sass
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by xzyfer** [comment]
Pease follow the instructions requested when opening a new issue. Without
that information and a complete install log we cannot help you.

**Comment by sknightq** [comment]
I had same problem and cost me 4 hours!
![fc 8xp kkue qsgo5wvqkm](https://cloud.githubusercontent.com/assets/8033144/21488989/dea3a68e-cc20-11e6-9dd9-96ba8a539c41.png)

**Comment by rakibler** [comment]
@sknightq what was your solution?  I'm getting the same error when installing angular-cli

**Comment by keerthivasan-r** [comment]
I'm getting into the same problem :worried: :sweat:

**Comment by sknightq** [comment]
@rakibler I'm sorry! I don't have perfect solution. I tried 10+ times to install my npm package in my project and successed in one time. And then I used this [node_modulesp] folder to do my work.  😟

**Comment by hitao123** [comment]
how to solve this problem! the problem as above, i worked in windows, my node version is  4.4.7 npm version 2.15.8

**Comment by xzyfer** [comment]
```
rm -rf node_modules
npm install
```

If that fails open a new issue and follow the steps in the issue template.
