### ISSUE TITLE
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (50)

### ISSUE THREAD

**Issue by ikitty** [sass/node-sass#1841]
I'm using `gulp-sass` in node.js project with electron . I found this issue when run `require('gulp-sass')` .
here are some infomation:

- NPM version (`npm -v`): 4.0.5
- Node version (`node -v`): 6.9.2
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.9.2',
  v8: '5.1.281.88',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	4.0.0	(Wrapper)	[JavaScript]
libsass  	3.4.0	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):
└─┬ gulp-sass@3.0.0
  └── node-sass@4.0.0 

And when I run `process.versions.modules ` in the devtools of electron , it returns 50.

I try to `npm rebuild node-sass` , but it remains show this issue . thanks for your reading. 

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by nschonni** [comment]
Electron isn't a supported environment. You can search the issue tracker to find the relevant discussions.

**Comment by ikitty** [comment]
thank u all the same .
