### ISSUE TITLE
npm install node-sass error

### ISSUE THREAD

**Issue by hentaicreep** [sass/node-sass#1842]
hi,when I use `npm install node-sass` I always get an error：
error Windows_NT 10.0.14393
error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program \\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
node v7.2.1
npm  v3.10.10
code ELIFECYCLE
node-sass@3.10.1 postinstall: `node scripts/build.js`
Exit status 1
error Failed at the node-sass@3.10.1 postinstall script 'node scripts/build.js'.
error Make sure you have the latest version of node.js and npm installed.
error If you do, this is most likely a problem with the node-sass package,
error not with npm itself.
error Tell the author that this fails on your system:
error     node scripts/build.js
error You can get information on how to open an issue for this project with:
error     npm bugs node-sass
error Or if that isn't available, you can get their info via:
error     npm owner ls node-sass
error There is likely additional logging output above.
verbose exit [ 1, true ]

- NPM version (`npm -v`):
3.10.10
- Node version (`node -v`):
7.2.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '7.2.1',
  v8: '5.4.500.44',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j',
  icu: '58.1',
  unicode: '9.0',
  cldr: '30.0.2',
  tz: '2016g' }
- Node Platform (`node -p process.platform`):
win32
- Node architecture (`node -p process.arch`):
x64

**Comment by xzyfer** [comment]
Try
```
npm install node-sass --unsafe-perm
```

**Comment by hentaicreep** [comment]
@xzyfer get same error :(

**Comment by xzyfer** [comment]
Please post a complete output log as a [gist](gist.github.com). It appears you've cut off important debugging information.

**Comment by nschonni** [comment]
3.10 doesn't support Node 7, but you should see a clear message about that unless there is something cut out of the log

**Comment by hentaicreep** [comment]
@xzyfer @nschonni hi,yesterday i reinstall my dev environment(node,npm,cordova,ionic and so on),create a new project use `npm install node-sass` it works~~ today i don't repeat this error,so i can't give you detail log  ,sorry for that：(

**Comment by PKeidel** [comment]
I had a similar error on ubuntu, turned out that the script wants to execute a `node ..` command, but I only had a `nodejs` binary. So I linked /usr/bin/node to /usr/bin/nodejs and it worked as expected.
