### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by silverbucket** [sass/node-sass#1857]
Whenever I run the ember command I get a: Bus error (core dumped). I've tried with both v7.3.0 and v7.4.0 of node.js with the same results. When I downgrade to node v6.9.4 the error goes away. So this is probably an issue with new code in the node 7.x branch. I'll open a bug there referencing this as well.

Output from `ember version --verbose && npm --version`:
```
$ cat node_modules/node-sass/package.json  | grep version
 "version": "3.13.1"
$ ember version --verbose
Bus error (core dumped)
$ npm info ember | grep version:
  version: '1.0.0-pre.2',
$ npm -v
4.0.5
$ node -v
v7.4.0
```

```
$ strace ember
... <snip> ...

stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/node_modules", 0x7ffc3a361e50) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/node_modules", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/node_modules/mkdirp", 0x7ffc3a361e50) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/node_modules/mkdirp.js", 0x7ffc3a361e10) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/node_modules/mkdirp.json", 0x7ffc3a361e10) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/node_modules/mkdirp.node", 0x7ffc3a361e10) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules", {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/mkdirp", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/mkdirp/index.js", {st_mode=S_IFREG|0644, st_size=2630, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/binding", 0x7ffc3a362190) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/binding.js", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
lstat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/binding.js", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
open("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/binding.js", O_RDONLY|O_CLOEXEC) = 13
fstat(13, {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
read(13, "/*!\n * node-sass: lib/binding.js"..., 388) = 388
close(13)                               = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/errors", 0x7ffc3a361e90) = -1 ENOENT (No such file or directory)
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/errors.js", {st_mode=S_IFREG|0644, st_size=1332, ...}) = 0
lstat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/errors.js", {st_mode=S_IFREG|0644, st_size=1332, ...}) = 0
open("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/lib/errors.js", O_RDONLY|O_CLOEXEC) = 13
fstat(13, {st_mode=S_IFREG|0644, st_size=1332, ...}) = 0
read(13, "/*!\n * node-sass: lib/errors.js\n"..., 1332) = 1332
close(13)                               = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/vendor/linux-x64-51/binding.node", {st_mode=S_IFREG|0755, st_size=330289, ...}) = 0
stat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/vendor/linux-x64-51/binding.node", {st_mode=S_IFREG|0755, st_size=330289, ...}) = 0
lstat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/vendor", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/vendor/linux-x64-51", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/vendor/linux-x64-51/binding.node", {st_mode=S_IFREG|0755, st_size=330289, ...}) = 0
futex(0x7f37d06410a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/home/nkj/code/kosmos/hyperchannel/node_modules/node-sass/vendor/linux-x64-51/binding.node", O_RDONLY|O_CLOEXEC) = 13
read(13, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\20\n\0\0\0\0\0"..., 832) = 832
fstat(13, {st_mode=S_IFREG|0755, st_size=330289, ...}) = 0
mmap(NULL, 4414968, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 13, 0) = 0x7f37c9282000
mprotect(0x7f37c94a2000, 2093056, PROT_NONE) = 0
mmap(0x7f37c96a1000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 13, 0x21f000) = 0x7f37c96a1000
--- SIGBUS {si_signo=SIGBUS, si_code=BUS_ADRERR, si_addr=0x7f37c96b0580} ---
+++ killed by SIGBUS (core dumped) +++
Bus error (core dumped)
```

**Comment by silverbucket** [comment]
also posted here: https://github.com/nodejs/node/issues/10782

**Comment by saper** [comment]
Can you get s stack backtrace with gdb ?

**Comment by JackFish** [comment]
same issue with yarn install
error /home/jhipster/app/node_modules/node-sass: Command failed.
Exit code: 135
Command: sh
Arguments: -c node scripts/build.js
Directory: /home/jhipster/app/node_modules/node-sass
Output:
Binary found at /home/jhipster/app/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Bus error (core dumped)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jberk** [comment]
same here
`building your project
        using yarn
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
error /opt/app/copy/node_modules/node-sass: Command failed.
Exit code: 135
Command: sh
Arguments: -c node scripts/build.js
Directory: /opt/app/copy/node_modules/node-sass
Output:
Binary found at /opt/app/copy/node_modules/node-sass/vendor/linux_musl-x64-48/binding.node
Testing binary
Bus error
{ Error: Command failed: yarn install -s && yarn run build
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at buildProject (/opt/app/generate-target.js:99:9)
    at /opt/app/node_modules/async/dist/async.js:3830:24
    at replenish (/opt/app/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/opt/app/node_modules/async/dist/async.js:931:17)
    at /opt/app/node_modules/async/dist/async.js:906:16
    at /opt/app/node_modules/async/dist/async.js:3835:13
    at rsync.shell.flags.exclude.source.destination.execute.error (/opt/app/generate-target.js:81:17)
    at Rsync.<anonymous> (/opt/app/node_modules/rsync/rsync.js:530:13)
  error: null,
  cmd: 'yarn install -s && yarn run build',
  file: '/bin/sh',
  args: [ '/bin/sh', '-c', 'yarn install -s && yarn run build' ],
  options: 
   { stdio: [ [Object], [Object], [Object] ],
     encoding: 'utf8',
     shell: true,
     file: '/bin/sh',
     args: [ '/bin/sh', '-c', 'yarn install -s && yarn run build' ],
     envPairs: 
      [ 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        'HOSTNAME=5b8e812a6cfe',
        'no_proxy=*.local, 169.254/16',
        'HOME=/root' ] },
  envPairs: 
   [ 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
     'HOSTNAME=5b8e812a6cfe',
     'no_proxy=*.local, 169.254/16',
     'HOME=/root' ],
  stderr: null,
  stdout: null,
  pid: 15,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
✨  Done in 155.24s.
`
running in a docker alpine linux container

**Comment by xzyfer** [comment]
Are you able to gist the dockerfile so I can reproduce it locally?

**Comment by jberk** [comment]
it's a custom container we use to build our react projects....

it's dying in this function (and it *was* working).  We're having some networking issues in my office, so I've got other moving parts I need to check:

```
function buildProject(callback) {
    console.log('building your project');

    let installer = fs.existsSync('yarn.lock') ? 'yarn' : 'npm';
    console.log(`\tusing ${installer}`);

    try{
        execSync(`${installer} install -s && ${installer} run build`, {'stdio':[0,1,2], 'encoding': 'utf8'})
    }catch(error){
        return callback(error);
    }

    callback(null, 'project built');
}
```

**Comment by jberk** [comment]
I changed nothing, and now that our network issue was resolved, all my builds are green....

**Comment by cmdelatorre** [comment]
Something similar happened to us. Given [this comment](https://github.com/sass/node-sass/issues/1962#issuecomment-298876189) I think it may be related to internet issues during the install.

**Comment by gardevgranade** [comment]
same here! Our internet connection was slow.. (2mbits). After the internet connection worked fine again,  everthing works...
