### ISSUE TITLE
Error: Unrecognised input in file ...

### ISSUE THREAD

**Issue by lukedanielson** [sass/node-sass#1864]
Have looked on [gulp-sass](), [node-sass](https://github.com/sass/node-sass), and [LibSass](https://github.com/sass/LibSass/issues/new) for this issue for about an hour, but haven't found anything pertinent, so I am opening here.

I had a permissions issue with the `node_modules` folder, so I ran `rm -Rf node_modules` followed by an `npm install`.

For some reason, now, when I try to run my styles task, I get:

```bash
Starting 'styles'...
Unrecognised input in file /path/to/assets/styles/common/_variables.scss line no. 2
```

Line 2 of that file is: `$brandColors: (` as it is the start of a simple [sass map](http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#maps)

If I comment out the `@import` of that particular file, it just throws an error on the next imported file, such as:

```bash
// common/_global.scss
$gray-lightest: lighten($gray-lighter, 4%);

// this throws the error:
//  Unrecognised input in file /path/to/assets/styles/common/_global.scss line no. 1
```

For the life of me, I can't figure out what is causing the issue.  Any references or places to point me to solve this would be greatly appreciated.  Apologies If I posted this to the wrong place.

Output of my environment versions/config here:

```bash
$ npm -v
3.8.0

$ node -v
v7.4.0

$ node -p process.versions
{ http_parser: '2.7.0',
  node: '7.4.0',
  v8: '5.4.500.45',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

$ node -p process.platform
darwin

$ node -p process.arch
x64

$ node -p "require('node-sass').info"
node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]

$ npm ls node-sass
sage@8.4.2 /Users/luke/code/vagrant/ehyd-ubu-14.04-php7/www/ehyd/public/wp-content/themes/ehydrate
└─┬ gulp-sass@2.3.2
  └── node-sass@3.13.1 
```

**Comment by xzyfer** [comment]
It's probably just a bug with the line number in the error message. Sounds
like the _global.scss cannot be found or read. Check the permission and
check that your includePath is configured correctly

**Comment by lukedanielson** [comment]
"bug with the line number in the error message"?  Like I said, no matter which SCSS files are referenced in my `main.scss`, it seems to not be processing the sass syntax properly.  My include paths, when it was working, was simply `[.]`, but have tried adding all possibly related paths into the array, but to no avail.

And randomly, sometimes the error seems to relate to not finding a .less file when is should be looking for a .scss file:

```bash
'bootstrap/responsive-utilities.less' wasn't found. Tried - /path/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/responsive-utilities.less,bootstrap/responsive-utilities.less in file /path/bower_components/bootstrap-sass-official/assets/stylesheets/_bootstrap.scss line no. 50
```

Anyone come across this, where node/gulp/sass treats a third-party SASS file dependency as missing and looks for the .less equivalent?

Is this a file permissions or ownsership issue?

**Comment by lukedanielson** [comment]
After further debugging, the issue seems to be which version of node is being used.  Downgrading node back to `v5.12.0`, in either the Linux VM itself or through brew on the host, from `v7.4.0` allowed gulp to process the sass without issue.

As you can probably tell, I'm not super knowledgeable as to the particulars of what the overall problem is, but it most likely has nothing to do with node-sass.

So I'll close this ; )
