### ISSUE TITLE
watcher unresponsive or tremendously slow starting with 3.12.0

### ISSUE THREAD

**Issue by mmase** [sass/node-sass#1869]
Issue: ~~After 3.9.3, watcher is virtually unresponsive or extremely slow/delayed.~~

Edit: I have narrowed it to https://github.com/sass/node-sass/releases/tag/v3.12.0

- NPM version (`npm -v`): 3.10.8
- Node version (`node -v`): 6.9.0
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.7.0',
  node: '6.9.0',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```

**Comment by xzyfer** [comment]
Are you mistakenly watching your `node_modules` directory? We don't currently offer a way to exclude certain directories and I'd prefer not to add yet another cli flag.

**Comment by xzyfer** [comment]
It's entirely possible there's a leak in the files array. I had suspected there might be at the time but I couldn't see it.

**Comment by mmase** [comment]
No, definitely not watching `node_modules`. However, we do have a fairly large sass codebase. That being said, prior to this version (3.12.0), node-sass watch triggered instantly on all of our changes. I can see if I can scrape together an example to send over.

**Comment by xzyfer** [comment]
I suspect there may be a memory leak in how we're tracking the graph. I suggest doing some debugging around [this array](https://github.com/sass/node-sass/blob/master/bin/node-sass#L266) and the graph object. Their size should stay stable if you're not adding or removing files. If they're growing as you're saving then there is something wrong.

**Comment by xzyfer** [comment]
I spent some time looking into this and have been unable to find any kind of leak. I'm not sure how to proceed atm.

**Comment by xzyfer** [comment]
Ok after a lot of experimentation I was able to reproduce the issue. I was looking the watcher getting progressively slower over time which would suggest a memory leak. However the actual issue is that the watcher is slow to trigger changes on a files with lots of `@imports`. I've confirmed this is much slower in v3.12.0.

**Comment by mmase** [comment]
Thanks @xzyfer! I've confirmed this fixes things on our end as well. Nice find.

**Comment by xzyfer** [comment]
Thanks for the confirmation, the fix will be in the next release.
