### ISSUE TITLE
Watch files when calling render function

### ISSUE THREAD

**Issue by andyrichardson** [sass/node-sass#1872]
Apologies in advance if this question has already been asked, I've been unable to find any open or closed issues on this matter.

I'm trying to configure node-sass to watch for changes to the entry file or associated files and, in turn, restart compilation. I know this is very easily done via the CLI but from inside a node script, it doesn't seem to be possible.

I was expecting something along the lines of this.
```
  sass.render({
    file: entry_sass,
    watch: true
  }
```

Is there a reason that watching hasn't been implemented outside of the CLI environment?

**Comment by andyrichardson** [comment]
I've found a third party plugin to implement said functionality although it would be a nice feature to have built into node-sass. 

https://github.com/kottenator/node-sass-watcher

**Comment by super-cache-money** [comment]
Hmm...I also have this issue and node-sass-watcher is too immature and buggy. This might be a silly question, but shouldn't this be fairly trivial to implement here, since all the watch logic already exists (as used in the CLI).

**Comment by super-cache-money** [comment]
For example, having this would make also doing postcss a breeze...
