### ISSUE TITLE
node-sass installation failed

### ISSUE THREAD

**Issue by jagroop** [sass/node-sass#1875]
Hey I was trying to install node-sass and got the below error

```bash
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/home/jagroop/.nvm/versions/node/v6.9.4/bin/node" "/home/jagroop/.nvm/versions/node/v6.9.4/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.4.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@4.4.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/dev/laravelmix/npm-debug.log
```

And the information you asked for

- NPM version: 3.10.10
- Node version: v6.9.4
- Node Process:                      { http_parser: '2.7.0',
                                                 node: '6.9.4',
						  v8: '5.1.281.89',
						  uv: '1.9.1',
						  zlib: '1.2.8',
						  ares: '1.10.1-DEV',
						  icu: '57.1',
						  modules: '48',
						  openssl: '1.0.2j' }
- Node Platform : `linux`
- Node architecture : x64
- node-sass version : Exception thrown
- npm node-sass versions: Exception thrown

**Comment by jagroop** [comment]
sorry for the false alarm it worked second time . but not sure what was the issue

**Comment by cmdelatorre** [comment]
Something similar happened to us. Given [this comment](https://github.com/sass/node-sass/issues/1962#issuecomment-298876189) I think it may be related to internet issues during the install.
