### ISSUE TITLE
Compass mixins are compiled wrong

### ISSUE THREAD

**Issue by wzup** [sass/node-sass#1878]
Not sure, but it looks like the error comes from `node-sass`.

In short, the issue looks like this:

![compass - compact - google chrome 2017-02-01 00 57 14](https://cloud.githubusercontent.com/assets/3880497/22475386/c9f2e780-e819-11e6-8aab-4c30522d6da9.png)

![compass - compact - google chrome 2017-02-01 01 01 20](https://cloud.githubusercontent.com/assets/3880497/22475497/157e520c-e81a-11e6-98a5-57cd34ccb11c.png)

How it happens.
I have React app. I use `webpack` and `sass-loader` to compile my `.scss` assets. I also use Compass mixins.
Here is example of `.scss` file. The output you can see above, it is invalid.

```
@charset "utf-8";
@import "compass/css3/flexbox";
@import "compass/css3/transition";
@import "compass/css3/box-shadow";
@import "compass/css3/border-radius";

.let {
    color: #ccc;
    @include box-shadow(0px 1px 5px 1px #c4c3c3);
    @include transition(color .2s ease-in);
    &.active {
        color: #00bcd4;
        @include transition(color .2s ease-in);
    }
}
```

Q: 
Why does it happen?
How to solve it?
What to use instead of compass?

I saw this question https://github.com/sass/node-sass/issues/1004
I didn't understand your answers, what you meant. So I have asked one more time.

**Comment by mgol** [comment]
For prefixes use [Autoprefixer](https://github.com/postcss/autoprefixer); you don't even have to use mixins then, it will just prefix what's needed.

**Comment by nschonni** [comment]
Compass isn't supported as per the issues you've already linked. StackOverflow would be a better place to ask a general external library question rather than the bug tracker.

**Comment by xzyfer** [comment]
I assume this is referring to the [compass-mixins](https://github.com/Igosuki/compass-mixins) project, not compass itself. 

If that's the case make sure you are using at least v0.12.8. The compass-mixins project is deprecated. I recommend using [bourbon](http://bourbon.io/) which is a drop in replacement for compass' mixins.

**Comment by wzup** [comment]
@mgol @xzyfer 
Yep, agree, [postCSS ](https://github.com/postcss/postcss) and [Autoprefixer ](https://github.com/postcss/autoprefixer) appeared to be better choices.

I have migrated from Webpack v1 to Webpack v2, have set up postCSS with Autoprefixer and got rid of Compass completely. So far I'm satisfied.

Bourbon is Ruby based, same as Compass was.

**Comment by xzyfer** [comment]
@wzup for what it's worth bourbon is not Ruby, it's pure Sass versions of the compass mixins.

```
npm install --save bourbon
```
