### ISSUE TITLE
selector-parse succeeds in error.

### ISSUE THREAD

**Issue by chriseppstein** [sass/node-sass#1881]
In ruby sass:

```
$ sass -i
>> selector-parse('&:hover')
SyntaxError: $selector: "&:hover" is not a valid selector: Invalid CSS after "": expected selector, was "&:hover" for `selector-parse'
```

In node-sass:

```
$ echo ".foo { a: selector-parse('&:hover'); }" | node-sass
.foo {
  a: &:hover; }
```

**Comment by chriseppstein** [comment]
IMO, it's dumb and may be a bug that ruby Sass doesn't support `&` here. @nex3 thoughts?

**Comment by nex3** [comment]
No selector functions support `&` (except for `selector-nest()` in parameters after the first). I think this makes some sense—it's not valid CSS, and (at least in LibSass) it isn't interpreted the same way as it is in any other context. And it's straightforward to express this idea already by using `selector-append(&, ":hover")`.

**Comment by chriseppstein** [comment]
@nex3 I find the partial support to be strange and cumbersome. I need to manipulate the sub selectors before passing it to `selector-nest`. as it stands now, I have to do a lot of string manipulation to end up with a less flexible solution.

**Comment by nex3** [comment]
Can you give me some more background on your use case?

**Comment by chriseppstein** [comment]
I'll start a thread on the sass issue tracker as it's separate from this
particular one.

On Thu, Feb 2, 2017 at 4:01 PM, Natalie Weizenbaum <notifications@github.com
