### ISSUE TITLE
Does node-sass support spaces in map keys?

### ISSUE THREAD

**Issue by rhysburnie** [sass/node-sass#1883]
Hi,

I'm using a library which has a palette function that throws an error when using node-sass when a map key has spaces.

For details see:
https://github.com/danlevan/google-material-color/issues/13

Even though spaces in key names doesn't seem like a good idea they are supported in other sass bindings.

Can you confirm if they are supported or not?

**Comment by xzyfer** [comment]
If it's in Sass it should in Node Sass. We can't confirm every possible use case. If you can confirm it doesn't work please open an issue.
