### ISSUE TITLE
npm install node-sass Error

### ISSUE THREAD

**Issue by ganchengyuan1990** [sass/node-sass#1884]
error log:
npm WARN optional Skipping failed optional dependency /chok
npm WARN notsup Not compatible with your operating system o
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs2\\node.exe" "D:\\nodejs2\\node_mo
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script
npm ERR! Make sure you have the latest version of node.js a
npm ERR! If you do, this is most likely a problem with the
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue fo
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support
npm ERR!     D:\nodejs\hexo\themes\yilia\npm-debug.log

node v6.3.1  npm  v3.10.3 node-sass@3.13.1(but in package.json is node-sass: ^3.9.3)

So anyone can help?  Thx a lot  ;)

**Comment by xzyfer** [comment]
This log tells us nothing. You ignored the issue template so we cannot help.
