### ISSUE TITLE
ARM compiled binary runtime error

### ISSUE THREAD

**Issue by BradlySharpe** [sass/node-sass#1893]
Hi,

Much like #1609, I've cloned this repo and successfully compiled the binary. In my `package.json` I've included the local copy of node-sass using `"node-sass":"file:../node-sass/"` however at runtime I get the following error:

```
ERROR in Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 7.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.0
@ ./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"appStyles":"/home/bradly/garden-pi/src/css/master.scss","useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/home/bradly/garden-pi/.bootstraprc","bootstrapPath":"/home/bradly/garden-pi/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js 4:14-1222 13:2-17:4 14:20-1228
 webpack: Failed to compile.
```

- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): v6.9.5
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '6.9.5',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): arm
- node-sass version (`node -p "require('node-sass').info"`):node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):garden-pi@1.0.0 /home/bradly/garden-pi
└── node-sass@4.5.0  invalid
npm ERR! invalid: node-sass@4.5.0 /home/bradly/garden-pi/node_modules/node-sass

**Comment by xzyfer** [comment]
This error happens if the binary was not found. If you'll need to make sure the binary is named correctly.

```
arm-x64-48_binding.node
```
