### ISSUE TITLE
bash on windows ERROR in Missing binding

### ISSUE THREAD

**Issue by ShanZiJun** [sass/node-sass#1897]
npm install & npm rebuild node-sass   Did not solve the problem
 
ERROR in Missing binding /mnt/d/Gits/pepper/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
 @ ./src/pages/cinema/bonus.scss 4:14-365 13:2-17:4 14:20-371

**Comment by xzyfer** [comment]
Looks like you ran `npm install` on Windows 64-bit with Node.js 4, but you're trying run node-sass on `Linux 64-bit with Node.js 6`. This can happen when doing mounting files into a docker container or vm for instance.

You need to fetch the correct binary for your environment with `npm rebuild node-sass`.

**Comment by xzyfer** [comment]
The rebuild needs to be run inside the Linux environment.

**Comment by saper** [comment]
Looks like we got a right OS during the download time, but we get it wrong when it comes to running it, maybe bash is a bit too much unixlike here for us?
