### ISSUE TITLE
transform: scale(0); becomes transform: 0;

### ISSUE THREAD

**Issue by thejamespower** [sass/node-sass#1898]
- NPM version (`npm -v`): 4.0.5
- Node version (`node -v`): 7.4.0
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '7.4.0',
  v8: '5.4.500.45',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
node-sass       4.5.0   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):
└─┬ gulp-sass@3.1.0
  └── node-sass@4.5.0

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here.

Syntax issue, working in LibSass 3.5 and all other compilers using SassMeister.

Input:
```
transform: scale(0);
```

Becomes:
```
transform: 0;
```

*If you delete this text without following it, your issue will be closed.*

**Comment by nschonni** [comment]
Are you running PostCSS or something else in your Gulp build? I can't reproduce this locally or on Sassmiester. If you can please create a libsass bug since it is a compilation issue.

**Comment by thejamespower** [comment]
Only other CSS processing I'm using is autoprefixer, but have confirmed the issue is not with that. Can't reproduce the bug in Libsass, so I'm at a bit of loss !

**Comment by nschonni** [comment]
Since this can't be reproduced using the plain `node-sass` on the commandline or libsass, the issue lies somewhere else in your build pipeline.
Aside: I'm assuming `scale(0)` and `0` are functionally identical and something is just optimizing it for you

**Comment by thejamespower** [comment]
Thanks for the help anyway @nschonni. I'll keep investigating.

FYI, from a CSS point of view, `transform: scale(0)`, makes the element shrink, while `transform: 0` does nothing at all.
