### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by feldum** [sass/node-sass#1899]
Hi,
i tried several times to install node sass on my machine. i have to say that i am behind a proxy
i attached the log and you can see below the information about node and the error logs:

- NPM version (`npm -v`):   **4.1.2.**
- Node version (`node -v`):  **v6.9.5**
- Node Process (`node -p process.versions`):
**{ http_parser: '2.7.0',
  node: '6.9.5',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2k' }**
- Node Platform (`node -p process.platform`): **win32**
- Node architecture (`node -p process.arch`): **x64**

**logs:**
...
26385 silly install printInstalled
26386 warn enoent ENOENT: no such file or directory, open 'C:\FD\sass\mysass\package.json'
26387 verbose enoent ENOENT: no such file or directory, open 'C:\FD\sass\mysass\package.json'
26387 verbose enoent This is most likely not a problem with npm itself
26387 verbose enoent and is related to npm not being able to find a file.
26388 warn mysass No description
26389 verbose If you need help, you may report this error at:
26389 verbose     <https://github.com/npm/npm/issues>
26390 warn mysass No repository field.
26391 verbose If you need help, you may report this error at:
26391 verbose     <https://github.com/npm/npm/issues>
26392 warn mysass No README data
26393 verbose If you need help, you may report this error at:
26393 verbose     <https://github.com/npm/npm/issues>
26394 warn mysass No license field.
26395 verbose If you need help, you may report this error at:
26395 verbose     <https://github.com/npm/npm/issues>
26396 verbose stack Error: node-sass@4.5.0 postinstall: `node scripts/build.js`
26396 verbose stack Exit status 1
26396 verbose stack     at EventEmitter.<anonymous> (C:\Users\feliciadu\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
26396 verbose stack     at emitTwo (events.js:106:13)
26396 verbose stack     at EventEmitter.emit (events.js:191:7)
26396 verbose stack     at ChildProcess.<anonymous> (C:\Users\feliciadu\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
26396 verbose stack     at emitTwo (events.js:106:13)
26396 verbose stack     at ChildProcess.emit (events.js:191:7)
26396 verbose stack     at maybeClose (internal/child_process.js:877:16)
26396 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26397 verbose pkgid node-sass@4.5.0
26398 verbose cwd C:\FD\sass\mysass
26399 error Windows_NT 6.1.7601
26400 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\feliciadu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
26401 error node v6.9.5
26402 error npm  v4.1.2
26403 error code ELIFECYCLE
26404 error node-sass@4.5.0 postinstall: `node scripts/build.js`
26404 error Exit status 1
26405 error Failed at the node-sass@4.5.0 postinstall script 'node scripts/build.js'.
26405 error Make sure you have the latest version of node.js and npm installed.
26405 error If you do, this is most likely a problem with the node-sass package,
26405 error not with npm itself.
26405 error Tell the author that this fails on your system:
26405 error     node scripts/build.js
26405 error You can get information on how to open an issue for this project with:
26405 error     npm bugs node-sass
26405 error Or if that isn't available, you can get their info via:
26405 error     npm owner ls node-sass
26405 error There is likely additional logging output above.
26406 verbose exit [ 1, true ]

**Comment by saper** [comment]
Do you have your proxy configured for npm? We might need to see earlier log entries to see why the download failed from GitHub

**Comment by glore** [comment]
me too, I download   linux-x64-48_binding.node from github failed, it is ok from npm.taoao.org
` https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64-48_binding.node`
`https://npm.taobao.org/mirrors/node-sass/v4.5.0/linux-x64-48_binding.node`

**Comment by xzyfer** [comment]
The binaries are not available in the repository so you shouldn't be using npm mirrors.

**Comment by nschonni** [comment]
Binaries aren't available on NPM, but from GitHub Releases. If that doesn't work for you, you can use the cache settings to try and setup something else https://github.com/sass/node-sass#binary-configuration-parameters
