### ISSUE TITLE
NPM Install fails, appears to be missing symbolic link to node?

### ISSUE THREAD

**Issue by iyerusad** [sass/node-sass#1900]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 3.5.2
- Node version (`node -v`): The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
- Node Process (`node -p process.versions`): The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
- Node Platform (`node -p process.platform`): The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
- Node architecture (`node -p process.arch`): The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
- node-sass version (`node -p "require('node-sass').info"`): The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
- npm node-sass versions (`npm ls node-sass`): /home/user
└── (empty)

npm ERR! code 1

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

Forgive me for any mistakes, I do not regularly file issues. The logs would seem to indicate this failure I am experiencing might be the right spot as it appears to fail on node-sass despite it appearing to be a issue a few levels higher (os level package?). Regardless I thought its possible there are references that might not be address in this particular depedency that might need an update? I seem to have resolved this, see my first follow up comment.

**Repro steps:**

Fresh install Ubuntu 16.0.4.1

> sudo apt-get update 
> sudo apt-get upgrade 
> reboot 

I then configure machine as 'shell' runner for Gitlab and give it the following job:

    stages:
      - build
    build:
      stage: build
      before_script:
      - sudo apt-get update -qq
      - sudo apt-get install -y -qq nodejs npm
      script:
      - sudo npm install

Following error past npminstall:

    npm ERR! Linux 4.4.0-31-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
    npm ERR! node v4.2.6
    npm ERR! npm  v3.5.2
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    
    npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
    npm ERR! spawn ENOENT
    npm ERR! 
    npm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/install.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs node-sass
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

cat /home/user/npm-debug.log:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'node-sass' ]
    2 info using npm@3.5.2
    3 info using node@v4.2.6
    4 verbose config Skipping project config: /home/user/.npmrc. (matches userconfig)
    5 silly fetchPackageMetaData node-sass
    6 silly fetchNamedPackageData node-sass
    7 silly mapToRegistry name node-sass
    8 silly mapToRegistry using default registry
    9 silly mapToRegistry registry https://registry.npmjs.org/
    10 silly mapToRegistry uri https://registry.npmjs.org/node-sass
    11 verbose request uri https://registry.npmjs.org/node-sass
    12 verbose request no auth needed
    13 info attempt registry request try #1 at 10:47:53 AM
    14 verbose request id dba7e6c42e3a374c
    15 http request GET https://registry.npmjs.org/node-sass
    16 http 200 https://registry.npmjs.org/node-sass
    17 verbose headers { server: 'nginx/1.10.1',
    17 verbose headers   'content-type': 'application/json',
    17 verbose headers   'last-modified': 'Mon, 13 Feb 2017 06:54:16 GMT',
    17 verbose headers   etag: 'W/"58a15818-3b57a"',
    17 verbose headers   'content-encoding': 'gzip',
    17 verbose headers   'cache-control': 'max-age=300',
    17 verbose headers   'content-length': '23993',
    17 verbose headers   'accept-ranges': 'bytes',
    17 verbose headers   date: 'Tue, 14 Feb 2017 17:47:53 GMT',
    17 verbose headers   via: '1.1 varnish',
    17 verbose headers   age: '211',
    17 verbose headers   connection: 'keep-alive',
    17 verbose headers   'x-served-by': 'cache-den6020-DEN',
    17 verbose headers   'x-cache': 'HIT',
    17 verbose headers   'x-cache-hits': '26',
    17 verbose headers   'x-timer': 'S1487094473.869312,VS0,VE0',
    17 verbose headers   vary: 'Accept-Encoding' }
    18 silly get cb [ 200,
    18 silly get   { server: 'nginx/1.10.1',
    18 silly get     'content-type': 'application/json',
    18 silly get     'last-modified': 'Mon, 13 Feb 2017 06:54:16 GMT',
    18 silly get     etag: 'W/"58a15818-3b57a"',
    18 silly get     'content-encoding': 'gzip',
    18 silly get     'cache-control': 'max-age=300',
    18 silly get     'content-length': '23993',
    18 silly get     'accept-ranges': 'bytes',
    18 silly get     date: 'Tue, 14 Feb 2017 17:47:53 GMT',
    18 silly get     via: '1.1 varnish',
    18 silly get     age: '211',
    18 silly get     connection: 'keep-alive',
    18 silly get     'x-served-by': 'cache-den6020-DEN',
    18 silly get     'x-cache': 'HIT',
    18 silly get     'x-cache-hits': '26',
    18 silly get     'x-timer': 'S1487094473.869312,VS0,VE0',
    18 silly get     vary: 'Accept-Encoding' } ]
    19 verbose get saving node-sass to /home/user/.npm/registry.npmjs.org/node-sass/.cache.json
    20 verbose makeDirectory /home/user/.npm creation not in flight; initializing
    21 silly makeDirectory /home/user/.npm uid: 1000 gid: 1000
    22 silly bugs url https://github.com/sass/node-sass/issues
    23 verbose stack Error: spawn xdg-open ENOENT
    23 verbose stack     at exports._errnoException (util.js:870:11)
    23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    23 verbose stack     at onErrorNT (internal/child_process.js:344:16)
    23 verbose stack     at nextTickCallbackWith2Args (node.js:441:9)
    23 verbose stack     at process._tickCallback (node.js:355:17)
    24 verbose cwd /home/user
    25 error Linux 4.4.0-31-generic
    26 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "node-sass"
    27 error node v4.2.6
    28 error npm  v3.5.2
    29 error path xdg-open
    30 error code ENOENT
    31 error errno ENOENT
    32 error syscall spawn xdg-open
    33 error enoent spawn xdg-open ENOENT
    34 error enoent spawn xdg-open ENOENT
    34 error enoent This is most likely not a problem with npm itself
    34 error enoent and is related to npm not being able to find a file.
    35 verbose exit [ 1, true ]

**Comment by iyerusad** [comment]
Running the following appears to resolve the issue:

> sudo ln -s /usr/bin/nodejs /usr/bin/node
> sudo rm -rf node_modules/

I am able to successfully do npm install once I link nodejs to node and remove the node_modules folder. Comment in https://github.com/rappasoft/laravel-5-boilerplate/issues/579 lead me to this suggestion.

**Comment by nschonni** [comment]
Yes, that is what the log suggesting to fix `sudo apt install nodejs-legacy` which does the linking.

**Comment by ajit-drag** [comment]
Doing this https://github.com/sass/node-sass/issues/1900#issuecomment-279790681  will corrupt linking for npm. It will start throwing `npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"` errors. 
To resolve this we need to link npm also. To do that execute ` ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by iyerusad** [comment]
@ajit-drag You referenced my comment which included
`sudo ln -s /usr/bin/nodejs /usr/bin/node`
and your suggestion was to do (to avoid "corrupting" linking for npm)
`ln -s /usr/bin/nodejs /usr/bin/node`

Is it clerical error? It would seem you indicating to do the same....

**Comment by ajit-drag** [comment]
Thanks for pointing that out @iyerusad, it was indeed a clerical error. I have updated my comment.

**Comment by balackbee** [comment]
@ajit-drag  ln -s /usr/local/bin/npm /usr/bin/npm : it telling
ln: failed to create symbolic link '/usr/bin/npm': File exists
