### ISSUE TITLE
index variable reference issues in for loops within functions

### ISSUE THREAD

**Issue by meodai** [sass/node-sass#1904]
I was wondering why we use a beta version of libsass. Mainly because its the only version that has [index variable reference issues in for loops within functions](https://github.com/sass/libsass/issues/2330) issue, that causes some problems on multiple projects that I maintain. A library that I wrote depends on this.

Let me know if I should also post the whole issue here.

- NPM version (`npm -v`): 4.2.0
- Node version (`node -v`): v7.5.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '7.5.0',
  v8: '5.4.500.48',
  uv: '1.10.2',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
``` 
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
└─┬ gulp-sass@3.1.0
  └── node-sass@4.5.0
```

When encountering a syntax, or compilation issue:

- [Open issue on `LibSass`](https://github.com/sass/libsass/issues/2330).

**Comment by xzyfer** [comment]
I am the maintainer of both node-sass and libsass. The libsass beta tag is misleading, it simply means that it doesn't have the full 3.5 feature set.

We consider libsass 3.5.0.beta.2 to be stable. The issue you ran into is unfortunate but that's why we have issue trackers. For every issue caused by a libsass release 10s of other issues are fixed.

**Comment by meodai** [comment]
@xzyfer Good to know, no worries. I was just wondering. Thank you

**Comment by xzyfer** [comment]
We're sorry this caused a problem. Thank you for opening an issue, we'll try to get it fixed asap.

If you're not using any Sass 3.5 features you can down grade to `node-sass@~4.3.0`.

**Comment by meodai** [comment]
This is what I did. Just had to figure out what gulp-sass version whould use `node-sass@~4.3.0`

**Comment by oriweingart** [comment]
+1
