### ISSUE TITLE
laravel 5.4 npm install failure on node-sass

### ISSUE THREAD

**Issue by glore** [sass/node-sass#1905]
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node-v7.5.0-linux-x64/bin/node',
1 verbose cli   '/opt/node/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'node-sass' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 silly fetchPackageMetaData node-sass
5 silly fetchNamedPackageData node-sass
6 silly mapToRegistry name node-sass
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'node-sass',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'node-sass',
9 silly mapToRegistry   name: 'node-sass',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/node-sass
11 verbose request uri https://registry.npmjs.org/node-sass
12 verbose request no auth needed
13 info attempt registry request try #1 at 5:14:55 PM
14 verbose request id c3711c505ac6d421
15 http request GET https://registry.npmjs.org/node-sass
16 http 200 https://registry.npmjs.org/node-sass
17 verbose headers { server: 'nginx/1.10.1',
17 verbose headers   'content-type': 'application/json',
17 verbose headers   'last-modified': 'Mon, 13 Feb 2017 06:54:16 GMT',
17 verbose headers   etag: 'W/"58a15818-3b57a"',
17 verbose headers   'content-encoding': 'gzip',
17 verbose headers   'cache-control': 'max-age=300',
17 verbose headers   'content-length': '23993',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Thu, 16 Feb 2017 09:14:55 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '2',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-nrt6135-NRT',
17 verbose headers   'x-cache': 'HIT',
17 verbose headers   'x-cache-hits': '1',
17 verbose headers   'x-timer': 'S1487236495.924381,VS0,VE0',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 200,
18 silly get   { server: 'nginx/1.10.1',
18 silly get     'content-type': 'application/json',
18 silly get     'last-modified': 'Mon, 13 Feb 2017 06:54:16 GMT',
18 silly get     etag: 'W/"58a15818-3b57a"',
18 silly get     'content-encoding': 'gzip',
18 silly get     'cache-control': 'max-age=300',
18 silly get     'content-length': '23993',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Thu, 16 Feb 2017 09:14:55 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '2',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-nrt6135-NRT',
18 silly get     'x-cache': 'HIT',
17 verbose headers   'x-cache-hits': '1',
17 verbose headers   'x-timer': 'S1487236495.924381,VS0,VE0',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 200,
18 silly get   { server: 'nginx/1.10.1',
18 silly get     'content-type': 'application/json',
18 silly get     'last-modified': 'Mon, 13 Feb 2017 06:54:16 GMT',
18 silly get     etag: 'W/"58a15818-3b57a"',
18 silly get     'content-encoding': 'gzip',
18 silly get     'cache-control': 'max-age=300',
18 silly get     'content-length': '23993',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Thu, 16 Feb 2017 09:14:55 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '2',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-nrt6135-NRT',
18 silly get     'x-cache': 'HIT',
18 silly get     'x-cache-hits': '1',
18 silly get     'x-timer': 'S1487236495.924381,VS0,VE0',
18 silly get     vary: 'Accept-Encoding' } ]
19 verbose get saving node-sass to /home/git/.npm/registry.npmjs.org/node-sass/.cache.json
20 verbose correctMkdir /home/git/.npm correctMkdir not in flight; initializing
21 silly bugs url https://github.com/sass/node-sass/issues
22 verbose stack Error: Command failed: xdg-open https://github.com/sass/node-sass/issues
22 verbose stack /usr/bin/xdg-open: line 402: htmlview: command not found
22 verbose stack /usr/bin/xdg-open: line 402: firefox: command not found
22 verbose stack /usr/bin/xdg-open: line 402: mozilla: command not found
22 verbose stack /usr/bin/xdg-open: line 402: netscape: command not found
22 verbose stack /usr/bin/xdg-open: line 402: links: command not found
22 verbose stack /usr/bin/xdg-open: line 402: lynx: command not found
22 verbose stack xdg-open: no method available for opening 'https://github.com/sass/node-sass/issues'
22 verbose stack
22 verbose stack     at ChildProcess.exithandler (child_process.js:211:12)
22 verbose stack     at emitTwo (events.js:106:13)
22 verbose stack     at ChildProcess.emit (events.js:192:7)
22 verbose stack     at maybeClose (internal/child_process.js:890:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
23 verbose cwd /srv/center
24 error Linux 2.6.32-573.8.1.el6.x86_64
25 error argv "/opt/node-v7.5.0-linux-x64/bin/node" "/opt/node/bin/npm" "bugs" "node-sass"
26 error node v7.5.0
27 error npm  v4.1.2
28 error code 3
29 error Command failed: xdg-open https://github.com/sass/node-sass/issues
29 error /usr/bin/xdg-open: line 402: htmlview: command not found
29 error /usr/bin/xdg-open: line 402: firefox: command not found
29 error /usr/bin/xdg-open: line 402: mozilla: command not found
29 error /usr/bin/xdg-open: line 402: netscape: command not found
29 error /usr/bin/xdg-open: line 402: links: command not found
29 error /usr/bin/xdg-open: line 402: lynx: command not found
29 error xdg-open: no method available for opening 'https://github.com/sass/node-sass/issues'
30 error If you need help, you may report this error at:
30 error     <https://github.com/npm/npm/issues>
31 verbose exit [ 1, true ]

**Comment by xzyfer** [comment]
Nothing in this output suggest an error install node-sass. Please follow the issue template when opening an issue.
