### ISSUE TITLE
Error relocating when npm i with the packages.json, not with the library

### ISSUE THREAD

**Issue by Armays** [sass/node-sass#1906]
Hello I have an issue when I npm i my packages.json, but i don't have any issue when i npm i node-sass :+1: 

npm 3.10.10
node v6.9.5

Node Process
{ http_parser: '2.7.0',
  node: '6.9.5',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2k' }

Node Platform
Alpine

Node architecture
x64

node-sass version
3.10.10

npm node-sass versions
npm info using npm@3.10.10
npm info using node@v6.9.5
Argalis@0.0.1 /src/formation-front
+-- UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^0.6.2
+-- UNMET PEER DEPENDENCY eslint-plugin-react@^4.3.0
+-- UNMET PEER DEPENDENCY font-awesome@>=4.3.0
`-- sasslint-webpack-plugin@1.0.4
  `-- node-sass@3.13.1 

npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^0.6.2, required by eslint-config-airbnb@7.0.0
npm ERR! peer dep missing: eslint-plugin-react@^4.3.0, required by eslint-config-airbnb@7.0.0
npm ERR! peer dep missing: font-awesome@>=4.3.0, required by font-awesome-webpack@0.0.4

`Binary found at /src/formation-front/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Binary has a problem: Error: Error relocating /src/formation-front/node_modules/node-sass/vendor/linux-x64-51/binding.node: __strtod_internal: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/src/formation-front/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/src/formation-front/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
Building the binary locally
Building: /usr/local/bin/node /src/formation-front/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
`

Can you please help me ? Thanks !

Could you please help me ? Thanks !

**Comment by xzyfer** [comment]
We only support Alpine from node-sass@4.2.0 and up. Please update your package.json to download a newer version of node-sass.
