### ISSUE TITLE
node-sass does not seem like it is installing with version 4.5

### ISSUE THREAD

**Issue by xtianus79** [sass/node-sass#1909]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 4.1.2
- Node version (`node -v`): 7.5
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`): 4.5.0
- npm node-sass versions (`npm ls node-sass`): 4.5.0

When encountering a syntax, or compilation issue:

node-sass 

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

i have installed node-sass and can see it is there but when i do node-sass -v or -help it doesn't do anything.

**Comment by oolongtea** [comment]
I'm also having issues with node-sass 4.5.0. My `node_modules/` directory is empty. Here are the details:

```
$ npm ls node-sass
/home/developer/tmp/temp1
└── (empty)
$ npm -v
4.1.2
$ node -v
v7.6.0
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '7.6.0',
  v8: '5.5.372.40',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
$ node -p process.platform
linux
$ node -p process.arch
x64
```

Here are gists of my npm.err and npm.log: https://gist.github.com/oolongtea/724b7fe70c0a47a867862ee785118f94

**Comment by xzyfer** [comment]
@xtianus79 without any logs or OS information there is nothing we can do. I can confirm 4.5.0 is has been installed over a million times since release so there must be something about your environment.

@oolongtea unfortunately your logs are truncated before getting to the actual installation failure. You can turn the log level down.
