### ISSUE TITLE
install node-sass error ELIFECYCLE on window 8.1 64 bit

### ISSUE THREAD

**Issue by thanhhuc25** [sass/node-sass#1910]
i am on window 8.1 64 bit
node: 6.9.5
npm: 4.2.0
visual studio 2015
error when i run: npm install node-sass
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-ddd" "node-sass"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! file C:\Windows\system32\cmd.exe;%JAVA_HOME%\bin;
npm ERR! path C:\Windows\system32\cmd.exe;%JAVA_HOME%\bin;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;%JAVA_HOME%\bin;

**Comment by xzyfer** [comment]
Because you haven't followed the issue template there is not enough information to help.
