### ISSUE TITLE
Error with node-sass on debian

### ISSUE THREAD

**Issue by Armays** [sass/node-sass#1913]
Hello I am building my web application with gitlab, i go from a docker image of node 7.4, i upgraded sass-loader to 4.1.0, when i npm install i dont understand why it first installs node-sass @3 whereas sass-loader 4 installs node-sass 4. This causes my ci build on gitlab to fail. Here is the error :
> node-sass@3.13.1 install /src/node_modules/sasslint-webpack-plugin/node_modules/node-sass
> node scripts/install.js

[91m
[0m[91m
[0mThe command '/bin/sh -c npm set progress=false && npm install node-sass --save-dev && npm install' returned a non-zero code: 1
[31;1mERROR: Build failed: exit code 1

Thanks ! :)

**Comment by xzyfer** [comment]
Sounds like an issue for sass-loader
