### ISSUE TITLE
Caching of the binding.node artefact under yarn

### ISSUE THREAD

**Issue by deployable** [sass/node-sass#1914]
The [`getCachePathCandidates`](https://github.com/sass/node-sass/blob/9905a597d7963555d8fae9e39880041e343e3e42/lib/extensions.js#L279-L284) method  provides caching candidates for the install.js script to use to find a copy of the `*-binding.node` file

```
function getCachePathCandidates() {
  return [
    process.env.npm_config_sass_binary_cache,
    process.env.npm_config_cache,
  ].filter(function(_) { return _; });
}
```

The default `npm_config_cache` variable doesn't resolve in yarn so there is no default external cache for the `binding.node` file which means the file is downloaded every time the local installed copy is missing or needs updating. 

```
yarn install v0.20.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠈ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-48_binding.node
```

There is a yarn issue to include the `npm_config_cache` or `npm_config_*` env variables in yarns environment https://github.com/yarnpkg/yarn/issues/1632. 
The only way I know how to get at the yarn cache dir is to use the command `yarn cache dir`.
At first glance the only thing I can see that indicates yarn running the install instead of npm looks to be the environment variable `npm_config_user_agent` which includes `yarn/0.20.3 npm/? node/v6.9.5 darwin x64`.

```
→npm -v
3.10.10
→yarn --version
0.20.3
→node -v
v6.9.5
→node -p process.versions
{ http_parser: '2.7.0',
  node: '6.9.5',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2k' }
→node -p process.platform
darwin
→node -p process.arch
x64
→node -p "require('node-sass').info"
node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.4.3	(Sass Compiler)	[C/C++]
→npm ls node-sass
www@0.1.0 /clones/www
└─┬ assets@0.10.1
  └─┬ gulp-sass@3.1.0
    └── node-sass@4.5.0

**Comment by xzyfer** [comment]
Thanks for the issue @deployable. I'm aware of the yarn issue, as I opened it for this exact reason see #1804. We consider the binding caching an enhancement which doesn't break node-sass working with yarn.

For the time being we will not be special casing for yarn because it would require significant changes to our CI process and increases to our build times.
