### ISSUE TITLE
npm install failing node sass terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by vikramsunilpatil** [sass/node-sass#1919]
I get this error when i do ```npm install --save node-sass```
```
> node-sass@4.5.0 install /home/ubuntu/www/project_name/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/ubuntu/.npm/node-sass/4.5.0/linux-x64-48_binding.node

> node-sass@4.5.0 postinstall /home/ubuntu/www/project_name/node_modules/node-sass
> node scripts/build.js

Binary found at /home/ubuntu/www/project_name/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device::__x86_rdrand(void)
Aborted (core dumped)
```
using nvm for version control
- NPM version (`npm -v`): 4.3.0
- Node version (`node -v`): 6.9.4
- npm node-sass versions (`npm ls node-sass`): empty

**Comment by xzyfer** [comment]
Please provide all the requested output from the issue template. It's
important we know which is and version you're on, and any other
non-standard node environment info I.e. are you in an electron shell.

For now you can try npm cache clear before npm install.
