### ISSUE TITLE
npm install node-sass -g -s  failed

### ISSUE THREAD

**Issue by bitqiang** [sass/node-sass#1920]
npm install node-sass -g -s
C:\Users\qiang\AppData\Roaming\npm\node-sass -> C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-48_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
Building: C:\Program Files\nodejs\node.exe C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\qiang\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.5.0
gyp info using node@6.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\qiang\AppData\Local\Programs\Python\Python35-32\python.EXE
gyp verb check python version `C:\Users\qiang\AppData\Local\Programs\Python\Python35-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.5.1\r\n"
gyp verb could not find "C:\Users\qiang\AppData\Local\Programs\Python\Python35-32\python.EXE". checking python launcher
gyp verb could not find "C:\Users\qiang\AppData\Local\Programs\Python\Python35-32\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\qiang\AppData\Local\Programs\Python\Python35-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\qiang\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\qiang\AppData\Roaming\npm\node_modules\node-sass
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed with error code: 1

**Comment by nschonni** [comment]
The error message is telling you there is a proxy problem, this has also been answered before.

**Comment by iamsaksham** [comment]
@nschonni Please link it to the question where its answered before
