### ISSUE TITLE
Node Sass does not support environment: OSX new nodejs version

### ISSUE THREAD

**Issue by liesislukas** [sass/node-sass#1922]
```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.8.0
```

while in https://github.com/sass/node-sass/releases/tag/v3.8.0 it says it does support OS X with node 7

After removing node_modules and running fresh install it works again, i done it because when edited https://github.com/sass/node-sass/blob/5521bb6b870d0275d7e0e090ea6d7d9e71e17264/lib/extensions.js#L60 to return true i got error more extended with hint that it might be because of node was updated and node_modules were installed with older version of node. So the bug here is with error message, it should say not just `Unsupported runtime` but also give a hint to remove & fresh install npm modules.

- NPM version (`npm -v`): 4.1.2
- Node version (`node -v`): v7.7.2
- Node Process (`node -p process.versions`):
```{ http_parser: '2.7.0',
  node: '7.7.2',
  v8: '5.5.372.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
/Users/lukas/Desktop/www/node_modules/node-sass/lib/index.js:13
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.8.0
    at Object.<anonymous> (/Users/lukas/Desktop/www/node_modules/node-sass/lib/index.js:13:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
```
- npm node-sass versions (`npm ls node-sass`):
```
geekystats@1.0.0 /Users/lukas/Desktop/www/geekystats
├── node-sass@3.8.0 
└── UNMET PEER DEPENDENCY react@15.3.1

npm ERR! peer dep missing: react@^15.4.2, required by react-addons-css-transition-group@15.4.2 
```

**Comment by xzyfer** [comment]
This is an error in the release notes. Node 7 support only added in [v3.11.0](https://github.com/sass/node-sass/releases/tag/v3.11.0)

**Comment by xzyfer** [comment]
We backported the Node 7 binaries, however we cannot retroactively update the installer scripts. You can download the binding manually from that release if you cannot upgrade. However you're a major version behind so updating is your best course of action.
