### ISSUE TITLE
Better plugin support

### ISSUE THREAD

**Issue by Hackzzila** [sass/node-sass#1924]
I hope this is the right place.

I would like better plugin support for Sass, like [how Less does it](http://lesscss.org/usage/#plugins). On my project that supports both Sass and Less, I had to make my own compile command just for Sass while I could just use Less plugins for everything on the Less side. If this is done, please have actual good docs unlike Less. This would make my life easier, and it would make my app easier to use for Sass.

**Comment by saper** [comment]
libsass has [a plugin system](https://github.com/sass/libsass/blob/master/docs/plugins.md), but those plugins need to be written in C/C++

Some of the preprocessing can be done via custom importers feature.
