### ISSUE TITLE
Imports external to recursively watched directories get compiled

### ISSUE THREAD

**Issue by arxpoetica** [sass/node-sass#1928]
When I run the following command:

```
node-sass --include-path client/scss --source-comments -r client/source -o client/source
```
Everything imported via `@import` from the `client/css` directory gets compiled to `.css` files. For example, if I put `@import 'basics';` in any file in `client/source` and then go save something in that `client/css/basics.scss` file, it compiles the file to `client/css/basics.css`, even though nowhere have I specified `-r client/css`. Note that it's `-r client/source`, NOT `-r client/css`.

It seems wrong that it's compiling stuff external to `-r client/source`. Bug?

- YARN version: 0.21.3 (I am not using NPM)
- Node version: 7.5.0
- Node Process:
```
{ http_parser: '2.7.0', node: '7.5.0', v8: '5.4.500.48', uv: '1.10.2', zlib: '1.2.8', ares: '1.10.1-DEV', modules: '51', openssl: '1.0.2k', icu: '58.2', unicode: '9.0', cldr: '30.0.3', tz: '2016j' }
```
- Node Platform: darwin
- Node architecture: x64
- node-sass version:
```
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- yarn node-sass versions:
```
yarn list v0.21.3
└─ node-sass@4.5.0
✨  Done in 0.46s.
```

**Comment by xzyfer** [comment]
The node-sass watch builds an graph of the imports in all the entry files.
This means that's if any files in client/source or client/scss import a
file from client/css node-sass knows about it and watches it too.

I can't see any reason why node-sass produce and output file in client/scss
since you have specified the output directory to be client/scss.

**Comment by arxpoetica** [comment]
Here's a good reason: those files are *only* import files, with variables and mixins, no actual CSS. So it renders empty `.css` files. Right now I have to hide them w/ my git ignore file. There ought to be a way to either exclude files, or, more intuitively, the `node-sass` command ought to ONLY compile the files I've told it to, in this case, the files that are in `client/source` and not the other folder with external imports.

Doesn't it seem odd to you to have it compiling files outside of the scope of the folder I've told it to compile?

**Comment by arxpoetica** [comment]
Oh wait. Or are you saying you don't see WHY this is broken? Do I need to include a more solid example, so you see how it's actually broken?

**Comment by xzyfer** [comment]
Files that done produce output should start with an underscore. These are
called partials in Sass. Any file not starting with and underscore will
produce a . css file.

**Comment by nschonni** [comment]
Closing, as @xzyfer mentioned, this is a core language feature. Check sass-lang.org if you need more information

**Comment by arxpoetica** [comment]
@xzyfer that's very helpful to know about the underscore, and (I think) solves the problem. Thanks.

THAT SAID, @nschonni I *am* surprised to note that you guys don't think this is problematic in any way. Compiling files out of scope? Tsk, tsk. Oh well, it's your library, not mine. ;)

Just the same (no sarcasm), thanks for the great library. 👍
