### ISSUE TITLE
npm ERR! missing: node-sass@^4.2.0, required by gulp-sass@3.1.0

### ISSUE THREAD

**Issue by JohnSmithers23** [sass/node-sass#1930]
I had a separate issue and in trying to resolve that I installed visualstudio. Since then gulp-sass has failed to implement.

I have searched for a solution for a week. I have followed the troubleshooting: https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#windows

Here are my details (taken from the top, running gulp):

$ gulp
fs.js:913
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\lib\extensions.js:122:13)
    at foundBinariesList (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev
$ node -v
v7.7.2

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev
$ mkdir \temp1

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev
$ cd \temp1

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ node -p process.env.comspec
C:\Windows\system32\cmd.exe

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ npm -v
4.3.0

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ node -v
v7.7.2

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '7.7.2',
  v8: '5.5.372.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ node -p process.platforms
undefined

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ node -p process.arch
x64

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ npm cache clean

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ npm install -ddd node-sass > npm.log 2> npm.err

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ npm ls node-sass
wpinitiation@1.0.0 C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gulp-dev
`-- gulp-sass@3.1.0
  `-- UNMET DEPENDENCY node-sass@^4.2.0

npm ERR! missing: node-sass@^4.2.0, required by gulp-sass@3.1.0

User@User-PC MINGW64 /c/Bitnami/wampstack-5.6.30-1/apache2/htdocs/20170302bumwp/wp-content/themes/gulp-dev/temp1
$ cd node_modules\node-sass\vendor
bash: cd: node_modulesnode-sassvendor: No such file or directory

Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by nschonni** [comment]
Can you take the bash shell out of the equation, you appear to be switching between the console and windows commandlines between your operations.

**Comment by JohnSmithers23** [comment]
My apologies. Other factors got in the way of this one. Tried and got this from CMD:

module.js:472
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302
bumwp\wp-content\themes\gulp-dev\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

C:\Bitnami\wampstack-5.6.30-1\apache2\htdocs\20170302bumwp\wp-content\themes\gul
p-dev>cd node-modules
The system cannot find the path specified.
