### ISSUE TITLE
Watch flag is watching for changes to .css

### ISSUE THREAD

**Issue by bsuresh** [sass/node-sass#1933]
I got a project where I am using -wr to watch directory recursively for changes and I got some css files in the same folder.

Whenever the css file is changed, it triggers Sass compilation, although none of Sass file has been changed. Css file is not imported/related to Sass files, it is completely independent. 

I can see from the [below commit](https://github.com/sass/node-sass/issues/1075) it includes file extension of '*.css' to the watch option.

[https://github.com/sass/node-sass/issues/1075]|(https://github.com/sass/node-sass/issues/1075)

Not sure if this is an bug or intended behaviour.

Npm: 3.10.10
Node: v6.10.1
Node Process: { http_parser: '2.7.0',
  node: '6.10.1',
  v8: '5.1.281.95',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
Node Process Platform: darwin
Node architecture: x64
node-sass version: node-sass	4.5.1	(Wrapper)	[JavaScript]
                                 libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
npm node-sass versions: node-sass@4.5.1

**Comment by gavinwahl** [comment]
This is causing bugs when the input and output directories are the same. The watcher notices its own changes to css files and triggers and endless loop.

**Comment by gavinwahl** [comment]
#1845 seems to say that this is intentional.

**Comment by xzyfer** [comment]
This is intentional due to a known issue with LibSass. We recommend having
different input and output directories. There is nothing new can do in the
mean time.
