### ISSUE TITLE
Error: Undefined operation in multiplication

### ISSUE THREAD

**Issue by maartenbusstra** [sass/node-sass#1935]
We're having the following issue: https://github.com/sass/libsass/issues/2309 This has been fixed by the following release of libsass: https://github.com/sass/libsass/releases/tag/3.5.0.beta.3. Is there a possibility that libsass could be bumped to this version?

Thanks in advance! :)

**Comment by kenborge** [comment]
Shouldn't there be a version of nodesass using  libsass 3.4.4 instead? It's the newest stable release with backported fixes from 3.5, and some fixes that are not released in a 3.5 beta yet.

**Comment by danez** [comment]
Same here, also waiting for a bump, still using node-sass 3 because of some issues, which should be fixed in latest release.

**Comment by xzyfer** [comment]
Follow the progress in https://github.com/sass/node-sass/pull/1908

> Shouldn't there be a version of nodesass using libsass 3.4.4 instead

Node sass will not see any further 3.4 bumps. We're on the 3.5 track now.

**Comment by gauthierm** [comment]
https://github.com/sass/node-sass/issues/1966 is a duplicate of this issue.

**Comment by xzyfer** [comment]
Fixed in 4.8.0
