### ISSUE TITLE
Uncaught Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (50)

### ISSUE THREAD

**Issue by tyrellrummage** [sass/node-sass#1937]
Hello, I'm trying to use node-sass in an electron app I'm building and when I install it and require it from a file it throws this error into the console:

Uncaught Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (50)

I'm using: 

- NPM 4.4.4
- Node 7.7.4
- Node process: 

{ http_parser: '2.7.0',
  node: '7.7.4',
  v8: '5.5.372.42',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

- Node Platform: win32
- Node arch: x64
- node-sass version: 
node-sass       4.5.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions: 
`-- node-sass@4.5.2

I've tried using:

- npm cache clean
- npm rebuild nose-sass

and uninstalling and installing it again but nothing worked

**Comment by nschonni** [comment]
Yes, Electron isn't a supported environment, this has been discussed a few times previously if you search the repo

**Comment by tyrellrummage** [comment]
@nschonni hello, sorry I dind't read that, what alternative do I have then? Thanks in advance!

**Comment by foongpon** [comment]
Delete the physical folder node_modules in your project
Then run npm install. it should fix the problem.

**Comment by thatisuday** [comment]
`npm rebuild` will do it.

**Comment by ramankarman** [comment]
Command `npm rebuild`, `npm rebuild node-sass` didn't help me. But after installing Python 2.7 and Visual C++ Build Tools I deleted node_modules folder, opened CMD from Administrator and ran `npm install --msvs_version=2015`. Aaand it installed successfully!
I also found helpful [this comment](https://github.com/nwjs/nw-gyp/issues/63#issuecomment-77660581) and [this link](https://github.com/nodejs/node-gyp#on-windows).
