### ISSUE TITLE
node scripts/install.js failing in my system while installing node-sass on windows 7

### ISSUE THREAD

**Issue by dvkchaitanya** [sass/node-sass#1938]
getting the error while running the below command:  node scripts/install.js
npm ERR! node-sass@4.5.2 install: `node scripts/install.js`
npm ERR! spawn C:\Windows\system32\cmd.exe;C:\Users\venkata.desu\AppData\Roaming\npm ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.5.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js

**•NPM version ( npm -v ):** 4.1.2
**•NPM version ( npm -v ):** v7.7.4
**•Node Process ( node -p process.versions ):**
{ http_parser: '2.7.0',
  node: '7.7.4',
  v8: '5.5.372.42',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

**•Node Platform ( node -p process.platform ):**
win32
**•Node architecture ( node -p process.arch ):**
x64
**•node-sass version ( node -p "require('node-sass').info" ):**
module.js:472
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at Object.runInThisContext (vm.js:95:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:392:29)
**•npm node-sass versions ( npm ls node-sass ):**
'CALL "C:\Users\venkata.desu\AppData\Roaming\nvm\v7.7.4\\node.exe" "C:\Users\venkata.desu\AppData\Roaming\nvm\v7.7.4\\node_modules\npm\bin\npm-cli.js" prefix -g' is not r
as an internal or external command,
operable program or batch file.
hello@0.0.0 C:\Users\venkata.desu\angularStuff\hello
`-- UNMET PEER DEPENDENCY node-sass@^3.4.2 || ^4.0.0

npm ERR! peer dep missing: node-sass@^3.4.2 || ^4.0.0, required by sass-loader@4.1.1

**Comment by gerv** [comment]
I'm getting a very similar issue on Ubuntu 16.04 when trying to compile simplenote:

npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.1.1 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.1.1 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/simplenote-electron/npm-debug.log

/usr/src/simplenote-electron/npm-debug.log doesn't exist.

**Comment by xzyfer** [comment]
Unfortunately you've both cut off the important part of the log so there is no useful information. Please upload the complete npmlog as a github gist so I can see what happened.

**Comment by gerv** [comment]
That's all that's printed to the console. The file it references, /usr/src/simplenote-electron/npm-debug.log doesn't exist.

**Comment by gerv** [comment]
Oh, you mean the part _above_? I'll see if I can find that.

**Comment by xzyfer** [comment]
There should be some error in the output. We don't currently support electron so that's probably what's causing the error. You can try running electron-rebuild but I have no idea if it'll work.

**Comment by gerv** [comment]
Oh, so if Simplenote are using your code in an electron context than your view is "well, OK, but you're on your own"?

(That would be an entirely reasonable view; I just want to make sure the position is clear :-)

**Comment by xzyfer** [comment]
We have no position. Electron ships with version of V8 that are sometimes not compatible with Node. In those cases there is nothing we can do. I development with Electron but as I understand it they should have documentation on how to rebuild native extensions for their environment.
