### ISSUE TITLE
Linux 64-bit with Unsupported runtime (53)

### ISSUE THREAD

**Issue by owwo** [sass/node-sass#1939]
## I use webpack sass-loader in archlinux

```
 ERROR  Failed to compile with 1 errors                                                                                                                               10:19:32 AM

 error  in ./~/materialize-css/sass/materialize.scss

Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (53)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2

```
## My environment
```
$ npm -v
4.4.4
$ node -v
v7.7.3
$ node -p process.versions
{ http_parser: '2.7.1',
  node: '7.7.3',
  v8: '5.5.372.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.12.0',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
$ node -p process.platform
linux
$ node -p process.arch
x64
$ node -p "require('node-sass').info"
node-sass       4.5.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
$ npm ls node-sass
xxxxxxxxxxxxxxx
└── node-sass@4.5.2 
```

## then...
**Help me!** T.T

**Comment by xzyfer** [comment]
Looks like you're using an Node 8 beta, or electron. Neither of these are
supported.
You can run `npm rebuild node-sass` to try to compile a binary locally or
downgrade Node 7.

Regards,
Michael

**Comment by owwo** [comment]
@xzyfer I did not use node 8 beta, I updated to the last release node 7.8.0, still can not work.
But it is normal in ubuntu system and node 7.8.0.

```npm rebuild node-sass``` is invalid.

**Comment by xzyfer** [comment]
>Linux 64-bit with Unsupported runtime (53)

This error suggests you're not using Node 7. Judging by [this table][1] the module version for Node 7.8.0 is 51. I have confirmed this myself. I've only seen 53 in the Node 8 betas.

>I did not use node 8 beta, I updated to the last release node 7.8.0

```
{ http_parser: '2.7.1',
  node: '7.7.3',
  v8: '5.5.372.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.12.0',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
```

As you can see from your dump above, your modules version is 51. I looks you have two version so Node installed that do not agree.

>npm rebuild node-sass is invalid.
I don't know what you mean.

[1]: https://nodejs.org/en/download/releases/

**Comment by owwo** [comment]
@xzyfer I have not installed node 8 beta and I can not find this.

**Comment by owwo** [comment]
@xzyfer Thank you very much!

I found that my program was executed from electron. I
ts module version is 53. 

Orz...

**Comment by BernardMarieOnzo** [comment]
Removing node_modules and running npm install fixed those errors for me.

**Comment by mfaridzia** [comment]
try changing the node-sass version to the node-sass version:  4.10.0 and it works fine

**Comment by Serhiiilnytskyi** [comment]
Removing node_modules and downgrade to node10 from node12 was helpful for me

**Comment by emirhg** [comment]
> Removing node_modules and downgrade to node10 from node12 was helpful for me

Just removing node_modules was enough for my. Running with Node 12
