### ISSUE TITLE
It always had problems when I 'npm install node-sass' or 'npm install sass',help me

### ISSUE THREAD

**Issue by YepFury** [sass/node-sass#1941]
It always had problems when I 'npm install node-sass' or 'npm install sass', it showed 

- npm ERR! Windows_NT 6.1.7601
- npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\
- \bin\\npm-cli.js" "install" "node-sass" "--save--dev"
- npm ERR! node v6.10.0
- npm ERR! npm  v3.10.10
- npm ERR! code ELIFECYCLE
- 
- npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
- npm ERR! Exit status 1
- npm ERR!
- npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
- npm ERR! Make sure you have the latest version of node.js and npm installed.
- npm ERR! If you do, this is most likely a problem with the node-sass package,
- npm ERR! not with npm itself.
- npm ERR! Tell the author that this fails on your system:
- npm ERR!     node scripts/build.js
- npm ERR! You can get information on how to open an issue for this project with:
- npm ERR!     npm bugs node-sass
- npm ERR! Or if that isn't available, you can get their info via:
- npm ERR!     npm owner ls node-sass
- npm ERR! There is likely additional logging output above.
- 
- npm ERR! Please include the following file with any support request:
- npm ERR!     E:\Study\mySlideApp\myapp\npm-debug.log

what should I do for this problem?

**Comment by feebala** [comment]
I have the same issue - also tried updating my version of Node and npm...

**Comment by feebala** [comment]
@YepFury What ended up working for me (After trying to update Node via homebrew in terminal, to no avail)  - I just went to the download page for Node.js and re-downloaded the latest packaged and installed it through the regular installation ui. https://nodejs.org/en/download/

**Comment by YepFury** [comment]
@feebala I also re-downloaded my nodejs & npm, and I also 'npm install -g npm', it still showed error msg, I really don't konw how to resolve

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
