### ISSUE TITLE
CSS variables aren't properly compiled

### ISSUE THREAD

**Issue by TakhirMamirov** [sass/node-sass#1943]
I have set up the latest version of node-sass compiler (4.5.2 at the moment). Everything in scss is compiled perfectly except for CSS variables. Accordingly to this: https://github.com/sass/libsass/issues/2076 variables compilation should already be in there if SASS 3.5 is used. Am I missing something to make variables compiled correctly?

**Comment by xzyfer** [comment]
Please provide an example

**Comment by TakhirMamirov** [comment]
For instance, I would like this:

```
 #datatable {            
            --paper-datatable-column-header: { 
                 font-size: 16px;                 
                 color: #34495e; 
                 background-color: #fbfbfb;                       
            }
}
```

to be compiled correctly. By default, after SASS compilation it's transformed into:

```
 #datatable {            
            --paper-datatable-column-header-font-size: 16px; 
            --paper-datatable-column-header-color: ... etc
}
```
   which, apparently, doesn't work.

**Comment by nschonni** [comment]
@TakhirMamirov the issue in libsass you've linked to hasn't been implemented yet. This would need to be implemented there and then have the libsass version of node-sass updated for this to be supported.

**Comment by xzyfer** [comment]
The LibSass issue https://github.com/sass/libsass/issues/2076

**Comment by Pickra** [comment]
The libsass issue reported by @xzyfer has [been updated](https://github.com/sass/libsass/pull/2534)

**Comment by xzyfer** [comment]
Fixed in 4.8.0

**Comment by frlinw** [comment]
Well, I'm using webpack and css variable like:
```
:root {
  --primary: $primary
}
``` 
`$primary` is not replaced with its value in v4.8.x
It works in v4.7.x

**Comment by xzyfer** [comment]
Please search the identical closed issues.

**Comment by jemomi** [comment]
We ran into this problem as well, with gulp-sass, and after a long time of trying to fix the problem, and maybe a bit of yelling, we ended up force installing version 4.7.2 on the solution, which solved the problem.

Hope this can help some of you that run into the same problem with node-sass 4.8.x, try installing node-sass 4.7.x

**Comment by xzyfer** [comment]
This is not an issue, it's the correct functionality. Older versions of node-sass will be deprecated. We highly recommend fixing your bugs.

```
:root {
  --foo: #{$bar};
}
```
