### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by Rudloff** [sass/node-sass#1944]
Hello,

I'm trying to run node-sass on Android. `npm install` seems to work fine but when I run `./node_modules/.bin/node-sass`, it crashes with a segfault:
```
WARNING: linker: /data/data/com.termux/files/home/go/src/github.com/mattermost/platform/webapp/node_modules/node-sass/vendor/android-arm-48/binding.node has text relocations. This is wasting memory and prevents security hardening. Please fix.
Segmentation fault
```

- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): v6.10.1
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '6.10.1',
  v8: '5.1.281.95',
  uv: '1.11.0',
  zlib: '1.2.8',
  ares: '1.12.0',
  modules: '48',
  openssl: '1.0.2k' }
```
- Node Platform (`node -p process.platform`): android
- Node architecture (`node -p process.arch`): arm
- node-sass version (`node -p "require('node-sass').info"`):  It crashes.
- npm node-sass versions (`npm ls node-sass`): `node-sass@4.5.0` (I can also reproduce on master.)

**Comment by nschonni** [comment]
Android isn't a supported platform

**Comment by Rudloff** [comment]
Maybe you could make that more explicit by adding an [os](https://docs.npmjs.com/files/package.json#os) key in `package.json` then?

**Comment by akehir** [comment]
@Rudloff I managed to build node-sass on my android/termux. See http://blog.akehir.com/2017/05/building-node-sass-libsass-python.html for how to do it on your end.

At the moment I'm investigating, if it's possible to build the binary automatically for android and providing it to node-sass (see sass/node-sass#1960)
