### ISSUE TITLE
Raspi 3 Arm Arch

### ISSUE THREAD

**Issue by danquack** [sass/node-sass#1947]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/linux-arm-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-arm-51_binding.node": 

HTTP error 404 Not Found

- NPM version (`npm -v`):
4.2.0
- Node version (`node -v`):
v7.8.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '7.8.0',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
- Node Platform (`node -p process.platform`):
linux
- Node architecture (`node -p process.arch`):
arm

**Comment by danquack** [comment]
@xzyfer this is actually similar to #1602 #1609. Probably a duplicate

**Comment by nschonni** [comment]
Yes, #1340 explains the background and why their is no support
