### ISSUE TITLE
node 4.5.2 missing linux-x64-48_binding.node

### ISSUE THREAD

**Issue by ayhkusa** [sass/node-sass#1948]
Hi folks, the installation is not finding linux-x64-48_binding.node. Please advise. Thanks.

$ npm -v
3.10.8
$ node -v
v6.9.1
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
$ node -p process.platform
linux
$ node -p process.arch
x64
$ node -p "require('node-sass').info"
module.js:471
    throw err;
    ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at bootstrap_node.js:357:29
$ npm ls node-sass
/tmp/temp1
âââ (empty)
npm ERR! code 1

attempt to install node-sass 4.5.2
$ npm install node-sass
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

> node-sass@4.5.2 install /tmp/temp1/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-48_binding.node":

**Comment by xzyfer** [comment]
I can confirm the binary exists at that location. Please try again, if
problems persist check your network snd proxy settings.

**Comment by ayhkusa** [comment]
Being we aren't allowed install via the proxy. Is there a way to tell node-sass install to look for the binding.node file in our internal artifactory? Thanks.

**Comment by xzyfer** [comment]
The bindings are hosted on github releases. You can mirror them on an internal server and set the config documented at https://github.com/sass/node-sass#binary-configuration-parameters
