### ISSUE TITLE
Installation fails WRT python

### ISSUE THREAD

**Issue by IdanAdar** [sass/node-sass#1950]
When trying to build a Docker container image with the following Dockerfile, the installation fails with:

> gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/src/app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/usr/src/app/node_modules/node-sass/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/src/app/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.node-gyp/6.9.4/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.node-gyp/6.9.4',
gyp info spawn args '-Dnode_gyp_dir=/usr/src/app/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=node.lib',
gyp info spawn args '-Dmodule_root_dir=/usr/src/app/node_modules/node-sass',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.node-gyp/6.9.4
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/usr/src/app/node_modules/which/which.js:13:12)
gyp ERR! stack at F (/usr/src/app/node_modules/which/which.js:68:19)
gyp ERR! stack at E (/usr/src/app/node_modules/which/which.js:80:29)
gyp ERR! stack at /usr/src/app/node_modules/which/which.js:89:16
gyp ERR! stack at /usr/src/app/node_modules/isexe/index.js:42:5
gyp ERR! stack at /usr/src/app/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.9.13-moby
gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/src/app/node_modules/node-sass
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
Build failed with error code: 1
npm info lifecycle node-sass@3.13.1~postinstall: Failed to exec postinstall script

The used Dockerfile is:

```
FROM node:6.9.4-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install python
RUN apk add --update python py-pip

# Use .npmrc 
COPY ./.npmrc /usr/src/app
ARG NPM_TOKEN  

# Will prevent npm install if nothing has changed
COPY ./package.json /usr/src/app
RUN cd /usr/src/app && npm install

# Bundle app source
COPY . /usr/src/app
 
EXPOSE 8080
CMD [ "npm", "start" ]
```

However if I use this section for the python installation, it does work:

```
# Install python
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && pip install virtualenv \
    && rm -rf /var/cache/apk/*
```

When using `RUN apk add --update python py-pip` for the python installation, am I missing a requirement?

- NPM version (`npm -v`): v3.10.10
- Node version (`node -v`): v6.9.4

As the installation fails during the `docker build` run I am unable to provide the below.
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by xzyfer** [comment]
You're using an old version of npm that doesn't support node 6 so npm is
building the extension locally. To do that npm requires python 2.

Update node-sass to v4 or install the python build tools.

**Comment by IdanAdar** [comment]
> Update node-sass to v4 or install the python build tools.
... or update to a newer npm?

**Comment by xzyfer** [comment]
Updating npm wont make a difference. Npm depends on node-gyp to build native extensions, which requires python2.7.

If you use a newer version of node-sass we supply the pre-built binaries so you don't need to build it locally.
