### ISSUE TITLE
Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (53)

### ISSUE THREAD

**Issue by mavajee** [sass/node-sass#1951]
I have 3 electron-webpack project, my and two boilirplate. When I have added sass-loader with node-sass to my project I have an error only in my project 
`Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (53)`
node sass version identical 
```
mxm@pc ~/D/e/social_pool1> ./node_modules/.bin/node-sass -v
node-sass	4.5.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
mxm@pc ~/D/e/social_pool1> node -v
v7.5.0

```
I try:

- remove-install node-modules folder
- rebuild node-sass
- change version

...and after node-sass not work only for my project

plz help my

**Comment by andrefa** [comment]
Same here, different env:
`Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)`

**Comment by mavajee** [comment]
@andrefa, I have changed the version but nothing has changed(

**Comment by nschonni** [comment]
Sorry, Electron isn't a runtime that is supported. You can read the various issues previously opened https://github.com/sass/node-sass/search?q=electron&type=Issues&utf8=%E2%9C%93

**Comment by misstt123** [comment]
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (64)
