### ISSUE TITLE
Add option to skip testing binary

### ISSUE THREAD

**Issue by mhart** [sass/node-sass#1955]
Currently there's no way to skip the "Testing binary" step after downloading a `*.node` binary during install – even though you can specify a particular binary/architecture via `--sass-binary-name`, `process.env.SASS_BINARY_NAME`, etc.

So this, for example, fails on MacOS:

```
npm install node-sass --sass-binary-name=linux-x64-48
...
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-48_binding.node
...
Binary has a problem: Error: dlopen(/node_modules/node-sass/vendor/linux-x64-48/binding.node, 1): no suitable image found.  Did find:
	/node_modules/node-sass/vendor/linux-x64-48/binding.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/node_modules/node-sass/vendor/linux-x64-48/binding.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
...
```

As well it should fail, by default.

However, it would be great for *deploying* to environments where you already know the correct architecture (for example, AWS Lambda) to be able to manually skip this test step. Something like:

```
npm install node-sass --sass-binary-name=linux-x64-48 --sass-skip-binary-test
```
Or `--sass-ignore-binary-test`, etc, etc

There's no way I can currently see to skip this binary test step

**Comment by xzyfer** [comment]
The bug here appears to be that the binary check isn't respecting the flags that alter the binary lookup. Disabling the check is the wrong solution.

**Comment by mhart** [comment]
If you say so – I thought the two concerns might be separate – in cases where the current architecture cannot be gleaned for whatever reason.

**Comment by xzyfer** [comment]
Sorry I think I may misread the issue. 

For context,

- the check exists as an early warning to make sure the binary was not corrupted during transit, or the environment detection failed
- the binary install flags exist for users who are behind corporate firewalls, or otherwise unable to access the hosted binaries

Are you trying to install the binary for a different environment than what you're running `npm install` on?

**Comment by mhart** [comment]
In my case, yes, I'm using a different environment – from the issue description:

> it would be great for deploying to environments where you already know the correct architecture (for example, AWS Lambda) to be able to manually skip this test step

I'm not sure what you mean by:

> the binary install flags exist for users who are behind corporate firewalls, or otherwise unable to access the hosted binaries

The flag I'm talking about: `--sass-binary-name`, `SASS_BINARY_NAME`, etc is still used for downloading the hosted binaries – it just overrides any architecture checks and downloads the actual binary you specify

In my case I'd be fine with the tests not being run by default – I just thought there were perhaps cases where people would still want the tests run, even though they're specifying the binary manually.

**Comment by mhart** [comment]
See here for the code I'm talking about: https://github.com/sass/node-sass/blob/6eb31f5a034d94ba1c8fd627b67cf8ace07b506f/lib/extensions.js#L175-L202

Test later at: https://github.com/sass/node-sass/blob/9905a597d7963555d8fae9e39880041e343e3e42/scripts/build.js#L134-L149

**Comment by xzyfer** [comment]
>I'm not sure what you mean by...
>... even though they're specifying the binary manually.

Sorry, to be clear - these flags exists purely to allow users to self-host the binaries. Node Sass always assumes the correct binary has been installed.

>In my case I'd be fine with the tests not being run by default

Disabling this check by default isn't an option for us. It prevents all many of bugs early.

****

We would like to understand your use case better. We're very reluctant to add any new install flag as we're currently working to remove some of the existing ones.

An alternative might be to supply a separate binary for just for downloading the binaries, but at that point wget is probably a better option.

**Comment by mhart** [comment]
My use case is running npm install on an architecture that's not the architecture I'm deploying to (ie, install and bundle on Mac, deploy to Linux).

AWS Lambda runs on Linux – I want to create my Lambda bundle from my Mac and deploy to Lambda – I can't do that with node-sass with a standard `npm install` because it install the Mac binaries – so I want to specify a different architecture to install for (the only way to do this right now is to deploy from Docker – or manually download the correct Linux binary over the top of the installed Mac one)

This would be useful for anyone using a CI/CD environment that doesn't match their deployment environment.

**Comment by saper** [comment]
Question to @mhart :

Do things work if you have both Mac and Linux binaries in your vendor directory on your dev machine and deploy both out there?

I think this is really part of a general problem that bundling binaries with an npm package is not really supported.

**Comment by mhart** [comment]
@saper in my case I don't mind – I'm happy to do it just as a bundle and deploy step. I don't really care if it runs on my Mac or not (and I wouldn't want to deploy the Mac binary)

Living side by side would be nice, but not necessary.

**Comment by saper** [comment]
ok, I can imagine we could turn off testing when the explicit binary is given by the user.

It depends how strict deployment procedures you have, if you need to have one deployable component that works everywhere, storing multiple binaries there for the platforms needed is the only option I think.

**Comment by jmcmullen** [comment]
Hey guys, this issue is blocking me on a current project so I'd like to jump in and submit a fix. Before I start, what's your preferred way of achieving this. Another flag such as `--sass-skip-binary-test` or just not testing if `--sass-binary-name` is present?

**Comment by mellogarrett** [comment]
Curious on the status of this. Where can I manually download binaries for another architecture?

I have the exact same usecase in mind of deploying to AWS Lambda

**Comment by xzyfer** [comment]
npm rebuild node-sass

**Comment by xzyfer** [comment]
Please let me know how that goes.

**Comment by mellogarrett** [comment]
Actually, that's not ideal... That means every time the Lambda launches it will have to rebuild node-sass before actually compiling sass which means more $$$ and more time.

It would really be nice to specify a `target` architecture

**Comment by xzyfer** [comment]
It doesn't an actual rebuild. It just downloads the correct binary the
current environment.

**Comment by mellogarrett** [comment]
Well then the naming is off... But either way, doing something on every execution that should be done once upfront is bad.

**Comment by xzyfer** [comment]
The naming is out of our control. That's in node-gyp. You also do not need to do it on every execution, just on deploy.

**Comment by xzyfer** [comment]
npm rebuild node-sass in your new environment is the recommended way to do
that

**Comment by mikeumus** [comment]
@mhart, I was able to get the binary installed in my docker container with this script inside a `start.sh` script: 

``` bash
# install node-sass binary if no binary for linux exists
if [[ $OSTYPE = *"linux"* ]]; then
  node node_modules/node-sass/scripts/install.js
fi
```

**Comment by saper** [comment]
There is no support to cross-build to another environment (this is not a node-sass problem, but the surrounding node-gyp infrastructure).

I am not recommending this because many build scripts in other modules are not prepared for this. For MacOS you will get `fsevents` installed but not for other platforms. There may be unexpected dependency issues.

If one tries to build on architecture A and deploy on architecture B anyway, please do the following:

# Make sure your node and npm versions are the same on A and B. This is a non-optional step.
# Install node-sass normally for architecture A. You will have a binary downloaded and put in the `vendor` subdirectory.
# Manually download the matching binary for architecture B and put it alongside binary for architecture A in the `vendor` subdirectory.
# Create your deployment package containing both binaries, for A and B.
# Bonus points: you can run node-sass tests locally on architecture A.
