### ISSUE TITLE
Segmentation fault with @extend and :global(> .sth)

### ISSUE THREAD

**Issue by tleunen** [sass/node-sass#1961]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 4.5.0
- Node version (`node -v`): 7.9.0
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.7.0',
  node: '7.9.0',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.5.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
superproject@365.0.0 /mydir
└── node-sass@4.5.2  

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

Here's a content that will fail:
```
.item {
    display: inline-block;

    :global(> .ext-link) {
        background: #000;
    }
}

.link {
    color: red;
}

.textLink {
    @extend .link;
    padding: 0 10px;
}
```

Looks like `:global(>` is very important here. Because without it, it works, or `:global(.sth)` works too.

**Comment by xzyfer** [comment]
Fixed in 4.8.0
