### ISSUE TITLE
Error while installing node-sass with node 6.10.2 on linux

### ISSUE THREAD

**Issue by techyrajeev** [sass/node-sass#1962]
I have read all the troubleshooting guidelines but couldn't find any solution.
**Required information**:
- NPM version (`npm -v`):3.10.10
- Node version (`node -v`):6.10.2
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '6.10.2',
  v8: '5.1.281.98',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '48',
  openssl: '1.0.2k' }

- Node Platform (`node -p process.platform`):linux
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):[1]    12122 bus error (core dumped)  node -p "require('node-sass').info"

- npm node-sass versions (`npm ls node-sass`):-- node-sass@3.13.1 

*If you delete this text without following it, your issue will be closed.*

I am facing the issue while installing node-sass. Please help me to find the issue.

npm install node-sass
also tried 
npm install node-sass@latest

npm WARN prefer global node-gyp@3.6.1 should be installed with -g

> node-sass@4.5.2 install /home/testProj/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-48_binding.node": 

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.2 postinstall /home/testProj/node_modules/node-sass
> node scripts/build.js

```
Binary found at /home/testProj/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Bus error (core dumped)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.
npm WARN sass-loader@3.2.3 requires a peer of node-sass@^3.4.2 but none was installed.
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass@latest"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@4.5.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/testProj/npm-debug.log
```

**Comment by xzyfer** [comment]
Te binary download timed out so the binary is corrupted. Remove node
modules and run npm install. This problem is fix in node-sass@4.5.0

**Comment by techyrajeev** [comment]
So I need to do 
`rm -rf node_modules
`then
`npm install --save node-sass@4.5.0
`
is **node-sass@4.5.0** stable version?

**Comment by xzyfer** [comment]
The most stable release is the newest. You're a major version behind so
there will be issues.

**Comment by techyrajeev** [comment]
Thanks for help. It worked with version 4.5.0.
