### ISSUE TITLE
Gulp sass unable to override already existing file

### ISSUE THREAD

**Issue by jainishan2323** [sass/node-sass#1963]
Gulp sass/gulp watch command is unable to override the already existing/generated .css file. So when there is no generated css file in the folder, the command works fine. But, if the file exists on the folder I am getting below error.

[12:17:39] Error: EPERM: operation not permitted, open 'C:\My folder\project\components\site-products\demo\app\css\style.css'

My config:

var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', function () {
  return gulp.src('./demo/app/scss/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./demo/app/css'));
});

gulp.task('sass:watch', function () {
  gulp.watch('./demo/app/scss/**/*.scss', ['sass']);
});

Not sure its relevant but I am not using gulp-compass. I am using node-sass instead. Thanks in advance for help.

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
