### ISSUE TITLE
Custom Functions Experimental

### ISSUE THREAD

**Issue by Pezmc** [sass/node-sass#1964]
Are `importer` and `functions` still considered experimental in libsass as noted in the [documentation](https://github.com/sass/node-sass#functions--v300---experimental)? I can't find a reference to their stability in the [libsass documentation](http://sass-lang.com/libsass).

---

I'm not sure the versions are relevant here, but as the issue requirements asks for them:

- NPM version (`npm -v`): 4.2.0
- Node version (`node -v`): v7.8.0
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 3.13.1
- npm node-sass versions (`npm ls node-sass`): node-sass@4.5.2

**Comment by saper** [comment]
Yes, those are still experimental features - the current interface is subject to change.
