### ISSUE TITLE
Problem installing dashing-js on windows 10

### ISSUE THREAD

**Issue by sshelake25** [sass/node-sass#1968]
Hello All, can anybody help me on this issue.
versions am using as below 
windows =>10 
node => v7.0.0
npm => 3.10.8

>npm install -g dashing-js
npm WARN deprecated jade@0.35.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN excluding symbolic link test\fixtures\app\views\.#application.js.coffee.erb -> sam@pursuit.41266
C:\npm-global\npm\dashing-js -> C:\npm-global\npm\node_modules\dashing-js\bin\dashing-js

> node-sass@0.7.0 install C:\npm-global\npm\node_modules\dashing-js\node_modules\node-sass
> node build.js

(node:19536) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.

C:\npm-global\npm\node_modules\dashing-js\node_modules\node-sass>if not defined npm_config_node_gyp (node "C:\Users\sshelake\AppData\Roaming\nvm\v7.0.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or
 3) add the location of the component to the system path if it is installed elsewhere.  [C:\npm-global\npm\node_modules\dashing-js\node_modules\node-sass\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\sshelake\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sshelake\\AppData\\Roaming\\nvm\\v7.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\npm-global\npm\node_modules\dashing-js\node_modules\node-sass
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
C:\npm-global\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "dashing-js"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
**npm ERR! Failed at the node-sass@0.7.0 install script 'node build.js'.**
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by nschonni** [comment]
node-sass@0.7.0 is very old and won't support Node 7

**Comment by sshelake25** [comment]
what is way to solve it. how do you close this ticket. give resolution to it

**Comment by nschonni** [comment]
The releases page mentions what node versions are supported https://github.com/sass/node-sass/releases

**Comment by xzyfer** [comment]
@sshelake25 unfortunately dashing-js hasn't been touched in 3 years and is likely no longer maintained. You'll need to use Node 0.10 if you want to use it, but the version of node-sass you'll be using is very old and broken.
