### ISSUE TITLE
npm ERR! Failed at the node-sass@4.5.2 install script 'node scripts/install.js windows 7

### ISSUE THREAD

**Issue by dmspba** [sass/node-sass#1970]
![untitled](https://cloud.githubusercontent.com/assets/28757812/26158008/4124b880-3b38-11e7-964a-fe77c6d592f9.png)

**Comment by dmspba** [comment]
Which file?

**Comment by dmspba** [comment]
npm install -g node-sass
I get follwing error

npm ERR! Failed at the node-sass@4.5.2 install script 'node scripts/install.js

**Comment by xzyfer** [comment]
![image](https://cloud.githubusercontent.com/assets/579928/26157859/8fbc78fc-3b1a-11e7-91bf-912a48d096c5.png)

**Comment by gdandy** [comment]
I had the same problem trying to install the latest version (4.5.3).  I was able to install the previous version successfully by running:

`npm install -g node-sass@4.5.2`

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by ceoaliongroo** [comment]
I opened similar issue #1980

**Comment by ilhamdoanggg** [comment]
some error in my sample project laravel

![screenshot from 2017-11-18 20-32-50](https://user-images.githubusercontent.com/9218660/32980800-e5a2d7d6-cc9f-11e7-9633-3347b4206835.png)

**Comment by mustafa-hanif** [comment]
I think node-sass is one of the most difficult package to install anywhere, better we move to something else.
