### ISSUE TITLE
4.5.3 regression on Travis CI breaks builds

### ISSUE THREAD

**Issue by bjornharrtell** [sass/node-sass#1971]
The failure is `Error: ENOENT: no such file or directory, scandir '.../node_modules/node-sass/vendor`. Downgrading to version 4.5.2 resolves the issue.

Cannot reproduce locally and as it's a managed environment I can only extract some of the version information from the build log:

$ node --version
v6.10.3
$ npm --version
3.10.10
$ nvm --version
0.33.2

Travis configuration:
https://github.com/miguelcobain/ember-paper/blob/cef52e7638615e44249775b0663ba8f48d7bb8c1/.travis.yml

Failing job:
https://travis-ci.org/miguelcobain/ember-paper/jobs/233735922

Successful job:
https://travis-ci.org/miguelcobain/ember-paper/jobs/233735922

The only difference is the `node-sass` version.

**Comment by nschonni** [comment]
The only think 4.5.3 added as support for another module version of Node 8 https://github.com/sass/node-sass/compare/v4.5.2...v4.5.3
This looks like another general yarn caching issue https://github.com/sass/node-sass/issues/1804

**Comment by bjornharrtell** [comment]
Sounds like a reasonable explanation but using `--force` or removing Yarn cache usage in `.travis.yml` does not appear to help.

**Comment by xzyfer** [comment]
Please file an issue with yarn. They're actively trying to address
node-sass incompatibilities

**Comment by bjornharrtell** [comment]
Confirmed to be more or less the same issue as described in https://github.com/yarnpkg/yarn/issues/1981. The workaround `npm rebuild node-sass` run as the `postinstall` script works in my case.

**Comment by StfBauer** [comment]
Had the same issue but instead of adding it inside the package.json a put the following code in the `.travis.yml`

```
before_script: npm rebuild node-sass;
```

Works great for me.
