### ISSUE TITLE
Run compiler on initiation in watch mode

### ISSUE THREAD

**Issue by TheColorRed** [sass/node-sass#1973]
```
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

I am using `node-sass` with the `-w` option and when I initiate the command it doesn't compile the sass code. I have to edit a file such as add a space to the end of a line then save the file for the compiler to run.

I would like to propose that when the command is ran with the `-w` option that it runs the compiler then starts to watch for changes.

Here is the command that I am running on this project https://github.com/TheColorRed/prefab:

```
node-sass -w ./src/sass/main.scss ./public/assets/css/prefab.min.css --output-style compressed
```

**Comment by nschonni** [comment]
Not easy to find, but this has been requested and refused already #1742

**Comment by coldtelling** [comment]
@nschonni Hey, Is there a chance to see this feature this year ? It's been over 527 days since the last thread😭
