### ISSUE TITLE
node-sass "v3.4.2/win32-x64-51_binding.node" does not exist!

### ISSUE THREAD

**Issue by K69G4JRA725W** [sass/node-sass#1974]
D:\swamp\vuejs-java-starter>npm rebuild node-sass

> node-sass@3.4.2 install D:\swamp\vuejs-java-starter\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-51_binding.node":

HTTP error 404 Not Found

**Comment by xzyfer** [comment]
Node sass 3.4 is very old, you need to update to 4.5 for node 7 support.
