### ISSUE TITLE
Encoding issues (with FontAwesome) 

### ISSUE THREAD

**Issue by timo002** [sass/node-sass#1976]
Hello,

I'm using gulp-sass to compile a custom set of icons from FontAwesome. In the FontAwesome `_variables.scss`, there is a variable `$fa-var-home`
```
$fa-var-home: "\f015";
```
After running gulp-sass, this is compiled into a weird character:
```
.fa-home:before {
  content: "";
}
```
Why doesn't it say `\f015`?

I added `@charset "UTF-8";` at the top of my main.scss file.

Versions:
- NPM version: 3.10.10
- Node version: 6.10.2
- Node Process:
  - http_parser: '2.7.0',
  - node: '6.10.2',
  - v8: '5.1.281.98',
  - uv: '1.9.1',
  - zlib: '1.2.11',
  - ares: '1.10.1-DEV',
  - icu: '58.2',
  - modules: '48',
  - openssl: '1.0.2k'
- Node Platform: darwin
- Node architecture: x64
- node-sass version: error running cmd
- npm node-sass versions: empty, ERR! code 1

I also added this issue first on the gulp-sass page. https://github.com/dlmanning/gulp-sass/issues/603#issuecomment-296236512

**Comment by xzyfer** [comment]
This is on purpose and part of the CSS spec. It's a different way to encode
the character.

**Comment by runthis** [comment]
This causes very reproducible side-effects. Notably, running a simple lighthouse accessibility test in chrome leaves fonts broken when complete.
