### ISSUE TITLE
Why node-sass asks visuall C++ and python 27? I need node-sass use for only angular 2 projects.

### ISSUE THREAD

**Issue by venkateshrntbci** [sass/node-sass#1978]
Project "D:\Public\Program Files\Apache Software Foundation\Apache2.2\htdocs\an
gular\cemApp\node_modules\node-sass\build\binding.sln" on node 1 (default targe
ts).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [D:\Public\Program Files\Apache Software Foundation\Ap
ache2.2\htdocs\angular\cemApp\node_modules\node-sass\build\binding.sln]
Done Building Project "D:\Public\Program Files\Apache Software Foundation\Apach
e2.2\htdocs\angular\cemApp\node_modules\node-sass\build\binding.sln" (default t
argets) -- FAILED.

Build FAILED.

"D:\Public\Program Files\Apache Software Foundation\Apache2.2\htdocs\angular\ce
mApp\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe
". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Vis
ual Studio 2005 or 3) add the location of the component to the system path if i
t is installed elsewhere.  [D:\Public\Program Files\Apache Software Foundation\
Apache2.2\htdocs\angular\cemApp\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.89
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Public\Program Files\Apache Softwa
re Foundation\Apache2.2\htdocs\angular\cemApp\node_modules\node-gyp\lib\build.js
:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Public\\Program Files\\nodejs\\node.exe" "D:\\Public\\Prog
ram Files\\Apache Software Foundation\\Apache2.2\\htdocs\\angular\\cemApp\\node_
modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--l
ibsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Public\Program Files\Apache Software Foundation\Apache2.2\htdocs
\angular\cemApp\node_modules\node-sass
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
Build failed with error code: 1
npm info lifecycle node-sass@4.5.3~postinstall: Failed to exec postinstall script

- NPM version (3.10.10):
- Node version (`6.10.3):
- Node Process (
{ http_parser: '2.7.0
  node: '6.10.3',
  v8: '5.1.281.101',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
):
- Node Platform (`win32`):
- Node architecture (`x64`):
- node-sass version (Can't install):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by xzyfer** [comment]
The log has been chopped off but my guess is that there was a network error when downloading the binary. As a result node tried to build the binary which requires c++ and python 2.7. Check you log for the network error.
