### ISSUE TITLE
Query params in background url are rearranged in alphabetical order

### ISSUE THREAD

**Issue by picosam** [sass/node-sass#1979]
- NPM version (`npm -v`): `4.6.1`
- Node version (`node -v`): `v7.10.0`
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0', node: '7.10.0', v8: '5.5.372.43', uv: '1.11.0',  zlib: '1.2.11', ares: '1.10.1-DEV', modules: '51', openssl: '1.0.2k', icu: '58.2', unicode: '9.0', cldr: '30.0.3', tz: '2016j' }`
- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
`node-sass	4.5.3	(Wrapper)	[JavaScript]`
`libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]`
- npm node-sass versions (`npm ls node-sass`): `node-sass@4.5.3`

Using `angular-cli`, when running `ng build --prod`, query parameters of background-image URLs in my scss file are not maintained in the same order they were.

Original line in scss file:

`background: url('https://fnbfb.imgix.net/https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ffamilinb-web.appspot.com%2Fo%2FUnused%2520-%252054148193_xxl.jpg%3Falt%3Dmedia%26token%3D25f08c08-ed7d-4b3b-a041-4368f8d8d451?auto=format&fit=crop&w=600&h=400&expires=1496488841&s=3bdd3f89855db0ee92aaa2db61f3ffe4')`

Line in main.xxx.bundle.js:

`background:url(https://fnbfb.imgix.net/https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ffamilinb-web.appspot.com%2Fo%2FUnused%20-%2054148193_xxl.jpg%3Falt%3Dmedia%26token%3D25f08c08-ed7d-4b3b-a041-4368f8d8d451?auto=format&expires=1496488841&fit=crop&h=400&s=3bdd3f89855db0ee92aaa2db61f3ffe4&w=600)`

I filed the bug [here](https://github.com/angular/angular-cli/issues/6441) and the folks there told me to reach out. Any ideas?

**Comment by nschonni** [comment]
Can you file an issue with https://github.com/sass/libsass/issues and link it back here, thanks!

**Comment by picosam** [comment]
Thank you, here it is: https://github.com/sass/libsass/issues/2406

**Comment by xzyfer** [comment]
This isn't because of LibSass. We just copy the exact URL over. It's probably being changed a minifier or some webpack loader.

**Comment by picosam** [comment]
Oh boy. I wish I had an idea which tool that would be! `angular-cli` doesn't actually give me control over webpack loaders except if I eject.

**Comment by mgreter** [comment]
From a 2 minute google search I would take a look at 
https://www.npmjs.com/package/query-string

> .stringify(object, [options])
> Stringify an object into a query string, sorting the keys.
