### ISSUE TITLE
node-sass issue with node v7.0 

### ISSUE THREAD

**Issue by shgattu** [sass/node-sass#1981]
Seeing below error with latest version of node.

npm ERR! Linux 3.10.0-327.28.3.el7.x86_64
npm ERR! argv "/rmbs/apps/node/node-v7.10.0-linux-x64/bin/node" "/apps/node/node-v7.10.0-linux-x64/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /user/sgattu/.npm/_logs/2017-05-29T00_05_42_250Z-debug.log

**Comment by xzyfer** [comment]
node-sass@3.13.1 is very old. Use Node 4 or upgrade to node-sass@4.5.2

**Comment by shgattu** [comment]
Same issue with latest version also

gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1050:11)
gyp ERR! stack     at TLSWrap.onread (net.js:582:26)
gyp ERR! System Linux 3.10.0-327.28.3.el7.x86_64
gyp ERR! command "/rmbs/apps/node/node-v7.10.0-linux-x64/bin/node" "/user/sgattu/pghosh-140/devices/cmservice/microservices/orchestrator/src/main/webapp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /user/sgattu/pghosh-140/devices/cmservice/microservices/orchestrator/src/main/webapp/node_modules/node-sass
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1
cm@1.4.0 /user/sgattu/pghosh-140/devices/cmservice/microservices/orchestrator/src/main/webapp
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN cm@1.4.0 No repository field.
npm ERR! Linux 3.10.0-327.28.3.el7.x86_64
npm ERR! argv "/rmbs/apps/node/node-v7.10.0-linux-x64/bin/node" "/apps/node/node-v7.10.0-linux-x64/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /user/sgattu/.npm/_logs/2017-05-29T03_07_41_007Z-debug.log

**Comment by shgattu** [comment]
Please don't close the issue without showing some resolution

**Comment by xzyfer** [comment]
This is a different issue. It looks like a networking issue.

>gyp ERR! stack Error: read ECONNRESET

But it's hard to tell because you haven't provided enough information

>npm ERR! There is likely additional logging output above.
>npm ERR! Please include the following file with any support request:
>npm ERR! /user/sgattu/.npm/_logs/2017-05-29T03_07_41_007Z-debug.log

**Comment by shgattu** [comment]
Saw the below error. Can this be a proxy issue. I don't see any problem with other npm installs why should this be different.

node-sass@4.5.3 install /../node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-51_binding.node": 

write EPROTO 140060545701696:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:


Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall /../node_modules/node-sass
> node scripts/build.js

**Comment by mydata** [comment]
any update on this?

**Comment by shgattu** [comment]
It's still not fixed yet.

**Comment by xzyfer** [comment]
Sounds like a proxy issue. Have you tried following the instructions?

```
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

**Comment by shgattu** [comment]
Finally could get around the issue by downloading linux-x64-51_binding.node and using the sass-binary-path option. 
But node-sass has issues with corporate proxy
