### ISSUE TITLE
Support Node 8

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#1985]
Tracking issue for Node 8 support to stop all the duplicate issues. Support was added in 4.5.3 but the binaries still need to be built.

- [x] OS X x64 (@xzyfer)
- [x] Linux x86 (@xzyfer)
- [x] Linux x64 (@xzyfer)
- [x] Alpine (@xzyfer)
- [x] Windows x86 (@nschonni)
- [x] Windows x64 (@nschonni)

Please don't comment, there nothing to add to this issue. To stay updated clicked the subscribe button on the right --->

**Comment by xzyfer** [comment]
@am11 are you able to build the Windows binaries whilst we wait for AppVeyor to catch up please?

**Comment by Emeryao** [comment]
+1
node `v8.0.0`
npm `v5.0.0`
os `windows10 x64`
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-57_binding.node"

**Comment by nschonni** [comment]
Fudged the appveyor to get it to produce the bindings, just waiting on the queue https://ci.appveyor.com/project/sass/node-sass/build/2531

**Comment by nschonni** [comment]
@xzyfer windows bindings are done

**Comment by xzyfer** [comment]
Are you able to add binaries to releases?

**Comment by xzyfer** [comment]
I've hit a snag with the Linux binaries. We build them on CentOS 5 which recently EOL'd so our docker image isn't currently working.

**Comment by nschonni** [comment]
Yes, not sure if we're running into each other since i'm getting "binary already exists". I'll give it a few minutes in case you're doing it right now

**Comment by xzyfer** [comment]
I'm not touching releases atm.

**Comment by xzyfer** [comment]
I don't see it on the release so I can't explain that error.

**Comment by nschonni** [comment]
Think I tried to drag and drop a few and it choked. I'll just start over and ping this when i'm done

**Comment by nschonni** [comment]
Think my Firefox wasn't playing nice, but I got it uploaded with Edge

**Comment by xzyfer** [comment]
@nschonni if you've got time, I've been using https://github.com/lox/node-sass-build-alpine-binaries for building the Alpine binaries. These lines will need to be updated https://github.com/lox/node-sass-build-alpine-binaries/blob/master/build.sh#L4-L5

**Comment by nschonni** [comment]
```console
HEAD is now at 48bbed1... 4.5.3
Generating Dockerfile.8
Building node-sass-alpine-builder:8
Sending build context to Docker daemon 18.72 MB
Step 1/8 : FROM node:8-alpine
manifest for node:8-alpine not found
Nicks-MacBook-Pro:node-sass-build-alpine-binaries nschonni$ 
```
Looks like the image for node 8 doesn't exist yet

**Comment by xzyfer** [comment]
This appears to be the upstream tracking issue for the alpine image update - https://github.com/nodejs/docker-node/pull/411

**Comment by nschonni** [comment]
Trying https://hub.docker.com/r/mhart/alpine-node/ to see if it will work. It's running now

**Comment by nschonni** [comment]
Test seem to pass, but it is an Alpine 3.6 base. Should I upload it or wait for the official Node image to get fixed?

**Comment by xzyfer** [comment]
Upload it. I don't think Alpine gets that much use atm. Ideally we'd regenerate all the Alpine binaries with 3.6 to hopefully fix https://github.com/sass/node-sass/issues/1879

**Comment by nschonni** [comment]
Done, but it looks like it's half the size of the last one

**Comment by xzyfer** [comment]
Interesting. Well https://github.com/nodejs/docker-node/pull/411 just got merged so we'll be able to confirm shortly.

**Comment by xzyfer** [comment]
The official Node 8 docker images are live. I'll try to sort out linux tonight.

**Comment by nschonni** [comment]
Did you figure out what the new base should be? I'm playing around with some dockerfiles to add to the repo and I'll add them in if you have

**Comment by xzyfer** [comment]
For the sake of safety I was going to try whatever the lowests supported centos is.

**Comment by nschonni** [comment]
Makes sense.
BTW, I built using the official Node image and the Apline binding was the same size. Maybe it's just improvements with the 3.6 image

**Comment by xzyfer** [comment]
Nice. I wonder if Alpine 3.6 resolves #1879. If I'd been keen to update all the existing Alpine binaries suing the mhart image.

**Comment by xzyfer** [comment]
I've created the linux binaries based of CentOS 6. I _think_ they're legit. Is anyone able to confirm they work as expected?

**Comment by xzyfer** [comment]
Twitter says 👍  - https://twitter.com/ckotzbauer1/status/870283705398571008
