### ISSUE TITLE
Cross building

### ISSUE THREAD

**Issue by Telokis** [sass/node-sass#1990]
Is there a way to run `npm install node-sass` with a specific target build?

I am trying to install npm dependencies on an external drive so that I can use it on another computer which doesn't have internet access and on which I am not administrator. I'd like to install everything before so I can dev even without internet access.

Specifically, I am currently on `Windows 64-bit with Node.js 7.x` and would like to build for `Windows 32-bit with Node.js 5.x`.

**Comment by xzyfer** [comment]
No, but I think you can use `SASS_BINARY_NAME` to force node-sass fetch a specific binary. The install will fail but it will fetch the binary.

```
SASS_BINARY_NAME=win32-ia32-44_binding.node npm install node-sass
```

**Comment by Telokis** [comment]
So I **have** to find a way to be able to compile it on the targeted computer?

**Comment by saper** [comment]
I think nobody from us ever tried it, https://github.com/netbeast/docs/wiki/Cross-Compile-NPM-modules suggests using a flag to `npm`. Almost certainly you will need to specify `--nodedir` as well to get the right node development headers.

Worst case you will need to go to the `build` directory and see if the generated VisualStudio project files need to be changed there. After changing those, running `msbuild` there should work.

**Comment by Telokis** [comment]
I might have found a solution. I manually ran `node-gyp` from within `node_modules/node-sass` and told it to target the specific settings I needed.
However, I cannot test it until tomorrow. I hope it will work.
