### ISSUE TITLE
Can't install node-sass with NPM 5.0.0

### ISSUE THREAD

**Issue by hheexx** [sass/node-sass#1991]
```
> node-sass@4.5.3 install C:\Users\hexbo\Documents\cx_public\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/win32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall C:\Users\hexbo\Documents\cx_public\node_modules\node-sass
> node scripts/build.js
```

Can't install with NPM 5.0.0
It works with NPM 4.6.1

Node v6.9.2
Windows 10

**Comment by nschonni** [comment]
Think it's somehow mangling it in here https://github.com/sass/node-sass/blob/master/lib/extensions.js#L176
My guess is NPM is now setting `process.env.npm_config_sass_binary_name` automagically https://github.com/sass/node-sass/blob/master/lib/extensions.js#L185

**Comment by nschonni** [comment]
Actually the line would be https://github.com/sass/node-sass/blob/master/lib/extensions.js#L240 where is is somehow resolving `pkg.version` with `https://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz`

**Comment by nschonni** [comment]
Sounds similar to https://github.com/npm/npm/issues/15050, but I think this probably needs an upstream but if you haven't already opened one

**Comment by ruchern** [comment]
I have the exact same issue here.

Downloading binary from [https://github.com/sass/node-sass/releases/download/v`https://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/win32-x64-48_binding.node`](https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/win32-x64-48_binding.node)

The issue lies here were it is installing from a url instead of the version number.

**Comment by xzyfer** [comment]
This is likely due to changes to shrinkwrap in npm@5. Please try npm@5.01. If the problem persist please comment on npm/npm#15050 or open an issue with npm and ping me in it.

**Comment by MattJeanes** [comment]
@xzyfer issue persists on npm 5.0.1

**Comment by billowapp** [comment]
Same here:

```javascript
Downloading binary from https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/darwin-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/darwin-x64-48_binding.node": 

HTTP error 404 Not Found

```

**Comment by xzyfer** [comment]
Pleasr don't comments on this issue. It's out of our hands for now. Downgrade to npm@4 in the mean time.

**Comment by mmoll** [comment]
could anybody lock this issue for now, then?

**Comment by xzyfer** [comment]
Please don't comments on this issue. This is out of our hands for now. Downgrade to npm@4 in the mean time. 

Leaving this issue open incase someone comes up with a work around. Unhelpful "me too" comments will be removed.

**Comment by oceanapplications** [comment]
I experienced this problem by running npm install with an older version of npm, updating npm and running install again.

My solution was to delete package-lock.json and run npm install while on the latest version of npm.

**Comment by vksgautam1** [comment]
any one found solution of this

**Comment by marc1n** [comment]
As a workaround, manually change entry in `package-lock.json` or `npm-shrinkwrap.json` 

from:
```
    "node-sass": {
      "version": "http://npmcache.softax.local/node-sass/-/node-sass-4.5.3.tgz",
      "integrity": "sha1-0JydEXlkEjnRuX/8YjH9zsU+FWg="
    },
```

to:
```
    "node-sass": {
      "version": "4.5.3",
      "resolved": "http://npmcache.softax.local/node-sass/-/node-sass-4.5.3.tgz",
      "integrity": "sha1-0JydEXlkEjnRuX/8YjH9zsU+FWg="
    },
```

**Comment by xzyfer** [comment]
rm -rf node_modules
rm package-lock.json
npm install

**Comment by seneyr** [comment]
Echoing what @xzyfer recommends...

Deleting the local npm cache and the node_modules directory and then rebuilding the shrinkwrap file is ultimately what worked for my team's project.  

Depending on your preferences for installing newer dependencies you might also want to downgrade dependencies back to their previous versions using npm install <package>@version in case they are upgraded during the npm install command.

**Comment by ruchern** [comment]
I would like to report back/update that this issues seemed to be resolved with `npm 5.0.2` @xzyfer

**Comment by xzyfer** [comment]
My understanding is that is due to files left over by previous npm versions.

```
rm -rf node_modules
rm package-lock.json
npm cache clean
npm install
```

**Comment by vprasanth** [comment]
Still have the issue:
npm v5.0.3

**Comment by ruchern** [comment]
@vprasanth `rm -rf node_modules` and run `npm install` again.
