### ISSUE TITLE
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

### ISSUE THREAD

**Issue by ruchern** [sass/node-sass#1993]
- NPM version (`npm -v`): v5.0.1
- Node version (`node -v`): v8.0.0
- Node Process (`node -p process.versions`): v8.0.0
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Error see below
- npm node-sass versions (`npm ls node-sass`): node-sass@4.5.3

Error that appeared with node-sass during compilation as below:

```
throw new Error(errors.missingBinary());
      ^

Error: Missing binding /var/www/htdocs/PROJECT_DIR/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 7.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/var/www/htdocs/PROJECT_DIR/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/htdocs/PROJECT_DIR/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
```

**Comment by ruchern** [comment]
This issue is probably related to #1985

**Comment by xzyfer** [comment]
Tracking in #1985

**Comment by khushbookalia** [comment]
This error comes when you have an updated node version but the project which you are running still has the old version. So, probably can use the command

npm rebuild node-sass --force

then, serve your project again

**Comment by SatishMHiremath** [comment]
I have faced and fixed this issue relates node-sass and python error.Try installing latest angular cli command with the steps below

Set the system variable path as well:
C:\Users\windowsusername\AppData\Roaming\npm

C:\Users\windowsusername\AppData\Roaming\npm\node_modules@angular\cli\bin;

C:\Program Files\nodejs;

Then start using angular cli command prompt using:
angular client project folder path>npm install -g @angular/cli@latest

angular client project folder path>npm install -g node-gyp
