### ISSUE TITLE
Missing bindings for Node.js 8.x

### ISSUE THREAD

**Issue by dherges** [sass/node-sass#1998]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): `5.0.0`
- Node version (`node -v`): `8.0.0`
- Node Process (`node -p process.versions`): 
- Node Platform (`node -p process.platform`): 
- Node architecture (`node -p process.arch`): 
- node-sass version (`node -p "require('node-sass').info"`): `4.5.3`
- npm node-sass versions (`npm ls node-sass`): `4.5.3`

```
$ nvm install node
Downloading and installing node v8.0.0...
Downloading https://nodejs.org/dist/v8.0.0/node-v8.0.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v8.0.0 (npm v5.0.0)
```

During install the following message shows up:

```
/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^
Error: Missing binding node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
Found bindings for the following environments:
  - Linux 64-bit with Node.js 7.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (dist/lib/steps/assets.js:4:12)
```

I guess that bindings for Node 8 are not yet available.

**Comment by TuxBoy** [comment]
Hi, 
Did you try to make a 
`yarn add node-sass`
 in order to update it? Because I use it with Gulp and I had to do this so that it works with nodejs 8.

**Comment by xzyfer** [comment]
You need to reinstall your node modules when you change node versions.

**Comment by robsonsobral** [comment]
To reinstall isn't enough, @xzyfer . I already tried that. `npm install`, `yarn install`, to remove `node_modules`...

**Comment by xzyfer** [comment]
Make sure you're install node-sass@4.5.3 and that you don't have
dependencies on older node-sass. You can use npm ls node-sass to confirm
all node-sass dependencies, and their parents.

**Comment by robsonsobral** [comment]
To update gulp-sass from 2 to 3 made it. Thank you, @xzyfer . And, please, forgive me for have bothered you. Thank you!

**Comment by monochrome-yeh** [comment]
it doesn't work with any solutions of google answer,
I think the issue is coming from people who use `nvm` and `yarn` and both are gonna be idiot status, the node-sass don't know who is he, what node version is.

**Comment by monochrome-yeh** [comment]
I've removed whole the node_modules, rubuilt several times switch lots of version to remove node-sass and re-install again, it do NOT work.

**Comment by xzyfer** [comment]
Make sure you have the latest node-sass version. You can see your version
with npm ls node-sass

**Comment by monochrome-yeh** [comment]
```
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x
```

I've removed all the time, even though I'm certainly in `node.js 6`, `the node-sass` always try to find binding on `Node.js 8`.
Also I've removed `node-sass` when I switched to `node.js 8`.

**Comment by monochrome-yeh** [comment]
I did:
- remove node-sass on node.js 6
- remove node-sass on node.js 8
- rebuild node-sass
- npm cache clean
- reinstall node-sass on node.js 6

**Comment by monochrome-yeh** [comment]
okay, I did `nvm uninstall 8` and then execute my project, it still show
```
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x
```

how come...

**Comment by monochrome-yeh** [comment]
conclusion is that node-sass gonna build correctly, but finding incorrectly

**Comment by xzyfer** [comment]
It appears you're somehow installing or rebuilding with Node 6, but trying to execute with Node 8. This is a local envorinment issue, and nothing to do with node-sass.

There isn't anything we can do. You need to figure out how your Node versions are changing. If you're running node-sass in special environment like electron, or an IDE it may have it's own version of Node bundled.

**Comment by monochrome-yeh** [comment]
@xzyfer , ya, you are right, `electron` is alway peer `@types/node@8.10.0`, even though I installed electron on `node.js 6`.

**Comment by Singh-KiaTec** [comment]
please try my solution here https://stackoverflow.com/a/49669424/9601544

**Comment by jfcartier** [comment]
Ok so I found a working solution for this problem. Have a look at [this one](https://github.com/nodejs/node-gyp/issues/809#issuecomment-356900158)
