### ISSUE TITLE
scss in NODE version 8.0.0

### ISSUE THREAD

**Issue by anjnaharsora** [sass/node-sass#2000]
i have updated to node 8.0.0 after that i tried to load my old project , which gives me error
"Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)"
is there any solution for that?

- NPM version (`4.5.0`):
- Node version (`8.0.0`):
- Node Process (`{ http_parser: '2.7.0',
  node: '8.0.0',
  v8: '5.8.283.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2k',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
`):
- Node Platform (`win32`):
- Node architecture (`x64`):
- node-sass version (`Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime `):
- npm node-sass versions (`ERR`):

**Comment by xzyfer** [comment]
Please please please search for issues before opening a new one. This has been answered many times.

```
rm -rf node_modules
npm install
```

**Comment by n1ru4l** [comment]
delete you node_modules folder and run npm install
