### ISSUE TITLE
Error downloading binnary

### ISSUE THREAD

**Issue by MiquelAdell** [sass/node-sass#2001]
*version information at the bottom*

I had some strange npm behaviour and I tried to delete node_modules and reinstall.

With an empty node_modules when executing `npm install` I get:

```
ss@4.5.2 install /Users/miqueladell/code/vagrant-local/www/entesa/htdocs/wp-content/themes/entesa/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.2.tgz/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.2.tgz/darwin-x64-57_binding.node":

HTTP error 404 Not Found
```

The url it's trying to donwload from looks like more than one url fused together.

I've tried installing without dependencies on packages.j

If I try to install with a minimal package json:

```
{
  "dependencies": {
    "gulp-sass": "^3.1.0"
  }
}

```

I get:

```
> pngquant-bin@3.1.1 postinstall /Users/miqueladell/code/vagrant-local/www/entesa/htdocs/wp-content/themes/entesa/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant built successfully

```

And it takes forever as it seems to be compiling everything from source every dependency because it can not download precompiled binaries.

Something is wrong because both `node -p process.arch` and `npm ls node-sass` gave me errors

- NPM version (`npm -v`):
5.0.3

- Node version (`node -v`):
v8.0.0

- Node Process (`node -p process.versions`):
→ node -p process.versions
{ http_parser: '2.7.0',
  node: '8.0.0',
  v8: '5.8.283.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

- Node Platform (`node -p process.platform`):
darwin

- Node architecture (`node -p process.arch`):
x64

- node-sass version (`node -p "require('node-sass').info"`):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

- npm node-sass versions (`npm ls node-sass`):
└──  extraneous error: Invalid version: "https://registry.npmjs.org/node-sass/-/node-sass-4.5.2.tgz

**Comment by xzyfer** [comment]
```
Downloading binary from https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.2.tgz/darwin-x64-57_binding.node
```

This is a duplicate. See #1991.

> And it takes forever as it seems to be compiling everything from source every dependency because it can not download precompiled binaries.

This will always happens for new major versions of Node. It takes for native extension to update. Best not to update Node versions in a rush.

```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
```
You need the latest node-sass for Node 8 support.

**Comment by tinpont** [comment]
How about node 8.1.0?

**Comment by TTtuntuntutu** [comment]
v8.9.1 works but v9.1.0 not

**Comment by xzyfer** [comment]
Please search before opening new issues. You'll need the latest node SaaS
for node 9 support
