### ISSUE TITLE
Visual Studio 2013 WD download link is broken

### ISSUE THREAD

**Issue by cshanejennings** [sass/node-sass#2002]
The link for Visual Studio 2013 WD in the README is giving a 404:  https://www.microsoft.com/en-us/download/details.aspx?id=44914

**Comment by nschonni** [comment]
We'll need to update the docs, but you can follow the Installation instructions from node-gyp https://github.com/nodejs/node-gyp#installation

**Comment by cshanejennings** [comment]
Ok, thanks!
