### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by megamindbrian** [sass/node-sass#2003]
I think I have more issues with this package than any other.  Why does this depend on node-gyp?  Why does this package need to download and build stuff during installation?

Downloading binary from https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.2.tgz/win32-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.2.tgz/win32-x64-51_binding.node":

HTTP error 404 Not Found

Where did the vhttps:// come from in the URL above?

**Comment by saper** [comment]
Please downgrade your npm. The newest version has some issues. We need node-gyp since node-sass is a component connecting node programs in JavaScript with a native C++ library (http://github.com/sass/libsass). Sorry for the inconvenience!

**Comment by megamindbrian** [comment]
Right, but isn't there a JavaScript interpreter and compiler for SASS?  If
I am only using node and not using C, why doesn't it just compile my sass
files using a node-module?  Can't the C++ library be generalized with LLVM
that you can offer a binary package along side the NPM package?  No
compiling or "windows-build-tools" necessary! :D

**Comment by megamindbrian** [comment]
Downgrade NPM or downgrade node-sass?

**Comment by nschonni** [comment]
See #1991
