### ISSUE TITLE
node-sass install caught in infinite loop

### ISSUE THREAD

**Issue by thomblake** [sass/node-sass#2006]
This is in a Docker container using npm 5. I'm not sure how reproducible it is, but I thought it would be of interest anyway. It's possible that this happens because the temporary directory it's trying to use as a backup is the same as the install directory.

I can probably fix this by fixing my permissions, but an infinite loop seems undesirable.

- NPM version (`npm -v`):
5.0.3
- Node version (`node -v`):
6.9.5
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.9.5',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform (`node -p process.platform`):
linux
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):
```
└─┬ ember-cli-sass@5.6.0
  └─┬ broccoli-sass-source-maps@1.8.1
    └── node-sass@3.13.1
```

Log snippet:

```
19:53:38.709 gyp verb install --ensure was passed, so won't reinstall if already installed
19:53:38.709 gyp verb install version not already installed, continuing with install 6.9.5
19:53:38.709 gyp verb ensuring nodedir is created /usr/src/app/node_modules/node-sass/.node-gyp/6.9.5
19:53:38.709 gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/src/app/node_modules/node-sass/.node-gyp/6.9.5"
19:53:38.709 gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/src/app/node_modules/node-sass/.node-gyp"
19:53:38.709 gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
19:53:38.709 gyp verb command install [ '6.9.5' ]
19:53:38.709 gyp verb install input version string "6.9.5"
19:53:38.710 gyp verb install installing version: 6.9.5
19:53:38.710 gyp verb install --ensure was passed, so won't reinstall if already installed
19:53:38.710 gyp verb install version not already installed, continuing with install 6.9.5
19:53:38.710 gyp verb ensuring nodedir is created /usr/src/app/node_modules/node-sass/.node-gyp/6.9.5
19:53:38.710 gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/src/app/node_modules/node-sass/.node-gyp/6.9.5"
19:53:38.710 gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/src/app/node_modules/node-sass/.node-gyp"
19:53:38.710 gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
19:53:38.710 gyp verb command install [ '6.9.5' ]
```

(continues like that forever)

**Comment by saper** [comment]
Probably interesting combination of a node-gyp issue (poor fallback on lack of permissions) and npm bug (infinite retry). npm 5 is hard to get working, does downgrade help?

**Comment by thomblake** [comment]
Yeah, it only happens in npm 5. I think the infinite retry is likely node-gyp's issue. Solved the permissions issue by the tried-and-true method of `npm install --unsafe-perm` so I'm not actually seeing this anymore.

**Comment by thomblake** [comment]
Probably the same as https://github.com/nodejs/node-gyp/issues/115

**Comment by arodu** [comment]
Same problem, I solved it like this
```
# npm -g --unsafe-perm install node-sass
```
thanks to @thomblake

**Comment by rey-fox** [comment]
same problem also on npm 5.5.1 either still solved with:
```
# npm -g --unsafe-perm install node-sass`
```

**Comment by nschonni** [comment]
Closing as this only appears to be an issue that happens when installing as root as documented by NPM https://docs.npmjs.com/misc/config#unsafe-perm
Running as root unsets this flag, but that permission is required for install scripts

**Comment by theferrit32** [comment]
This doesn't seem resolved.  Installing node-sass globally fails when not run as root, and loops infinitely when run as root.  

Is the expectation that node-sass must not be installed globally, or the user must pass --unsafe-perm when installing globally?

**Comment by xzyfer** [comment]
We don't recommend installing anything globally. We suggest using npx. If
you must then you'll need the --unsafe-perms flag for any module with post
install scripts

**Comment by 93lucasp** [comment]
You can try to change your node version with the [recommended LTS](https://nodejs.org/it/). with  [nvm](https://github.com/nvm-sh/nvm)

On my mac I did this:

`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash`

`nvm install node`

`nvm install --lts`

`nvm use --lts`

It fixed my problem without changing npm permission ;)
