### ISSUE TITLE
vendor folder doesn't get installed at random

### ISSUE THREAD

**Issue by hyperknot** [sass/node-sass#2007]
- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): v6.10.3
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '6.10.3',
  v8: '5.1.281.101',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): └── node-sass@4.5.3
- yarn --version: 0.24.5
- OS: OS X 10.11.6

I'm using yarn to install node-sass via package.json. There is no install warning, yet at random the vendor subfolder is skipped. I'd say 1 out of 3 times. It makes node-sass non-functional.

`rm -rf node_modules` and `yarn install` always fixes it.

**Comment by jharris4** [comment]
I'm having the exact same issue. Seems to be random (about 1/3 times) for me too.

Same steps are required to fix things for me as well (`rm -rf node_modules` and `yarn install`)

**Comment by nschonni** [comment]
You can follow the general yarn tracking issue #1804 it isn't something that this project can fix
