### ISSUE TITLE
`node-sass` support for NodeJS 8

### ISSUE THREAD

**Issue by christianwico** [sass/node-sass#2012]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): `5.0.3`
- Node version (`node -v`): `v8.1.0`
- Node Process (`node -p process.versions`):
```typescript
{ http_parser: '2.7.0',
  node: '8.1.0',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```
- Node Platform (`node -p process.platform`): `win32`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
```
- npm node-sass versions (`npm ls node-sass`):
```
upterm@0.2.158 C:\Users\Christian Wico\Documents\Projects\upterm
`-- (empty)
```

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

Any word on when `node-sass` support for NodeJS 8 will come out? Some project of ours has dependencies with issues against NodeJS 6 _(LTS)_, so as to why I didn't bother just trying to downgrade... *(I know this is a bad excuse, but some genius decided to upgrade NodeJS to that shiny new number.)*

*(Having second thoughts on whether to post this here or on the [LibSass repo](https://github.com/sass/LibSass/issues/new)... My apologies if I got this one wrong.)*

**Comment by xzyfer** [comment]
Node sass added support for node 8 in 4.5.3
