### ISSUE TITLE
compressed outputStyle breaks selectors with color name

### ISSUE THREAD

**Issue by evilebottnawi** [sass/node-sass#2013]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): `5.0.3`
- Node version (`node -v`): `v8.1.0`
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '8.1.0',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

```
- Node Platform (`node -p process.platform`): `linux`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```shell
my-project
└── node-sass@4.5.3 
```

Ref: https://gist.github.com/evilebottnawi/c56515c6b4ef5238a714afaba9d626c7 (using [sassmeister](https://www.sassmeister.com/))

When encountering a syntax, or compilation issue:

- https://github.com/sass/libsass/issues/2409

Original issues: https://github.com/webpack-contrib/sass-loader/issues/416

*If you delete this text without following it, your issue will be closed.*

**Comment by nschonni** [comment]
Closing since the upstream issue is closed
