### ISSUE TITLE
npm install node-sass fails

### ISSUE THREAD

**Issue by skaraman** [sass/node-sass#2014]
node-sass@3.13.1 install C:\omitted\
 node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Looking into it, 3.13.1 only has release files up to /win32-x64-51_binding.node
https://github.com/sass/node-sass/releases/tag/v3.13.1

**Comment by skaraman** [comment]
when i used -g it worked properly and got the latest version...
node-sass@4.5.3 install C:\omitted
node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-57_binding.node
Download complete..] - :

**Comment by nschonni** [comment]
Correct, Node 8 is only supported with 4.5.3

**Comment by skaraman** [comment]
if node 8 is only supported with 4.5.3 then why would running 'nom install node-sass' request version 3.13.1 ?

**Comment by xzyfer** [comment]
You can run npm ls node-sass to see which dependency is pulling in the
older node-sass.

**Comment by renolmachado** [comment]
1. Run npm install node-sass@latest -g
2. Modify package.json from your project to new version of node-sass
3. Run npm install

It works for me.
