### ISSUE TITLE
npm 5 strips "libsass" entry from the package.json

### ISSUE THREAD

**Issue by danielgindi** [sass/node-sass#2016]
Now because "libsass" does not exist in the package.json,
the `'LIBSASS_VERSION="<!(node -e "process.stdout.write(require(\'../package.json\').libsass)")"'` gyp define fails with `Invalid data, chunk must be a string or buffer, not undefined`, as the result is obviously `undefined`.

- NPM version (`npm -v`): 5.0.3
- Node version (`node -v`): v8.1.0
- Node Process (`node -p process.versions`): 
```
  { 
  http_parser: '2.7.0',
  node: '8.1.0',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b'
  }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
  node-sass	4.5.3	(Wrapper)	[JavaScript]
  libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):
  inmaze-dashboard@1.0.0 /home/user/git/dashboard
  `-- node-sass-middleware@0.11.0
    `-- node-sass@4.5.3

**Comment by xzyfer** [comment]
Since this is the first report of this issue, and we have many npm@5 users I'm sure there is more to this issue. By choosing to ignore the issue template you've really tied our hands in helping you.

**Comment by danielgindi** [comment]
Apologies. Updated.

**Comment by danielgindi** [comment]
I had to go and add the missing line to the package.json after npm strips it - and the `npm install` again. That allows me to continue working with it.

**Comment by saper** [comment]
@danielgindi - I do not seem to be able to reproduce this with npm v5.3.0, can you be more specific at which stage it gets "stripped"? Are you using your own package registry? There was similar problem in #1030 https://github.com/sass/node-sass/issues/1030#issuecomment-120625294

**Comment by danielgindi** [comment]
Well this does not happen anymore, and I'm on `npm 5.3.0` now too.
It happened on `npm 5.0.3`, which was quite buggy. node-sass was unusable and I had to manually install it.

Just for the sake of completion - the `libsass` was stripped from the dependencies of `node-sass`'s  package.json, after it was copied to `node_modules` by `npm`. Then what happened was `libsass` not getting installed at all, and `node-sass` complaining of course.

There was no local npm or any other registry involved. Although in a different project I did encounter `npm` removing local package links from package.json after an `npm install`, and it was on the same version of `npm`.

I think you can close this now, as it's an issue with a specific buggy version of `npm`, which should not be used by anyone. I've encountered many other problems with that version of `npm`, and I don't think there's anything that you can do for being "compatible" with that one.
