### ISSUE TITLE
Cannot download binaries

### ISSUE THREAD

**Issue by applinktony** [sass/node-sass#2017]
Not sure if a bug, but I will try to explain myself and what I've done to get it.

So, basically I've just setup a droplet in DigitalOcean and tried to deploy a Laravel application and I've got a 404 error when it tries to download this file:

https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node

If I visit the link it actually returns a 404 page.

After a few hours of reading other issues posted here (and other forums) someone suggested to manually copy the binary to the ~/.npm folder (which I did with no success).

This is what I have there:

**npm -v**
5.0.3

**node -v**
v8.1.0

**node -p process.versions**
{ http_parser: '2.7.0',
  node: '8.1.0',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

**node -p process.platform**
linux

**node -p process.arch**
x64

**node -p "require('node-sass').info"**
node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]

**npm ls node-sass**
laravel-elixir@3.4.3
-----gulp-sass@2.3.2
----------node-sass@3.13.1 

I have another droplet with a different environment (npm 3.8.3/node v5.10.1) and when I try to deploy the same project, everything works perfectly.

**Comment by bcrosnier** [comment]
The [v3.13.1 release](https://github.com/sass/node-sass/releases/v3.13.1) of node-sass, required by gulp-sass 2.x, does not contain binaries for node 5 (module version 57), which is why you get a 404.
Try upgrading your gulp-sass to version 3 or above.

See also: dlmanning/gulp-sass#610

**Comment by applinktony** [comment]
Thanks @bcrosnier 

At the moment upgrading gulp-sass is not an option unfortunately. Should I downgrade node to a previous version then?

**Comment by nschonni** [comment]
Node 8 is only supported with node-sass 4.5.3

**Comment by xzyfer** [comment]
Yes you can downgrade to Node 4 to use gulp-sass@2. It's worth noting there
are no breaking changes between gulp-sass 2 and 3 so upgrade should be
painless.

**Comment by DanielRuf** [comment]
> Node 8 is only supported with node-sass 4.5.3

That is basically not right. You just have to build it with `node-gyp` (and `windows-build-tools` on Windows).
