### ISSUE TITLE
node-sass compiles with full uri in package version

### ISSUE THREAD

**Issue by jornare** [sass/node-sass#2018]
After upgrading to Node 8, node-sass package.json is generated to include the full uri to the downloadable .tar file in its "version" parameter. (We are using an npm proxy internally)

This causes the version to be semantically incorrect, which causes the further installation to fail finding the correct binary for lib-sass online, which then triggers a complete build which in turn also is corrupted.

- NPM version (`npm -v`): 5.0.3
- Node version (`node -v`): 8.1.1 (also tried 8.0.0)
- Node Process (`node -p process.versions`): 
  http_parser: '2.7.0',
  node: '8.1.1',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' 
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): node-sass\thttp://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz\t(Wrapper)\t[JavaScript]\r\nlibsass  \t3.5.0.beta.2\t(Sass Comp
iler)\t[C/C++]
- npm node-sass versions (`npm ls node-sass`):  N/A

**Comment by xzyfer** [comment]
I'm sorry but I don't understand the issue. Please provide the install out
that shows the issue.

Node sass hasn't changed anything for node 8 so the issue is either
environmental on your end or an issue with npm 5/node 8.

**Comment by jornare** [comment]
the node-sass package.json
------------------------------

{
  "_args": [
    [
      "node-sass@http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz",
      "D:\\myproject"
    ]
  ],
  "_from": "node-sass@http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz",
  "_id": "node-sass@4.5.3",
  "_inBundle": false,
  "_integrity": "sha1-0JydEXlkEjnRuX/8YjH9zsU+FWg=",
  "_location": "/node-sass",
  "_phantomChildren": {},
  "_requested": {
    "type": "remote",
    "raw": "node-sass@http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz",
    "name": "node-sass",
    "escapedName": "node-sass",
    "rawSpec": "http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz",
    "saveSpec": "http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz",
    "fetchSpec": "http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_spec": "http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz",
  "_where": "D:\\myproject",
  "author": {
    "name": "Andrew Nesbitt",
    "email": "andrewnez@gmail.com",
    "url": "http://andrew.github.com"
  },
  "bin": {
    "node-sass": "bin/node-sass"
  },
  "bugs": {
    "url": "https://github.com/sass/node-sass/issues"
  },
  "dependencies": {
    "async-foreach": "^0.1.3",
    "chalk": "^1.1.1",
    "cross-spawn": "^3.0.0",
    "gaze": "^1.0.0",
    "get-stdin": "^4.0.1",
    "glob": "^7.0.3",
    "in-publish": "^2.0.0",
    "lodash.assign": "^4.2.0",
    "lodash.clonedeep": "^4.3.2",
    "lodash.mergewith": "^4.6.0",
    "meow": "^3.7.0",
    "mkdirp": "^0.5.1",
    "nan": "^2.3.2",
    "node-gyp": "^3.3.1",
    "npmlog": "^4.0.0",
    "request": "^2.79.0",
    "sass-graph": "^2.1.1",
    "stdout-stream": "^1.4.0"
  },
  "description": "Wrapper around libsass",
  "devDependencies": {
    "coveralls": "^2.11.8",
    "eslint": "^3.4.0",
    "istanbul": "^0.4.2",
    "mocha": "^3.1.2",
    "mocha-lcov-reporter": "^1.2.0",
    "object-merge": "^2.5.1",
    "read-yaml": "^1.0.0",
    "rimraf": "^2.5.2",
    "sass-spec": "3.5.0-1"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "files": [
    "bin",
    "binding.gyp",
    "lib",
    "scripts",
    "src",
    "test",
    "vendor"
  ],
  "gypfile": true,
  "homepage": "https://github.com/sass/node-sass",
  "keywords": [
    "css",
    "libsass",
    "preprocessor",
    "sass",
    "scss",
    "style"
  ],
  "libsass": "3.5.0.beta.2",
  "license": "MIT",
  "main": "lib/index.js",
  "name": "node-sass",
  "nodeSassConfig": {
    "binarySite": "https://github.com/sass/node-sass/releases/download"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sass/node-sass.git"
  },
  "scripts": {
    "build": "node scripts/build.js --force",
    "coverage": "node scripts/coverage.js",
    "install": "node scripts/install.js",
    "lint": "eslint bin/node-sass lib scripts test",
    "postinstall": "node scripts/build.js",
    "prepublish": "not-in-install && node scripts/prepublish.js || in-install",
    "test": "mocha test/{*,**/**}.js"
  },
  "version": "http://npmproxy:8089/repository/npm/node-sass/-/node-sass-4.5.3.tgz"
}


The install output
-------------------

node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/vhttp://npmproxy:8089/repository/npm/node-sass/
-/node-sass-4.5.3.tgz/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/vhttp://npmproxy:8089/repository/npm/node-sass/-/node-
sass-4.5.3.tgz/win32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.
export HTTP_PROXY=http://example.com:1234 or configure npm proxy via
npm config set proxy http://example.com:8080

**Comment by jornare** [comment]
I just did a downgrade to node 6.1.1 (npm 5.0.3) and got the same result.

**Comment by nschonni** [comment]
Did you try https://github.com/sass/node-sass/issues/1991#issuecomment-306437979

**Comment by jornare** [comment]
@nschonni Thank you, that looks like the same issue. I flushed all cache, deleted node_modules and package-lock.json, installed lastest node & npm and it ran like a charm. :)
