### ISSUE TITLE
filter: progid:  will compile fail

### ISSUE THREAD

**Issue by cjd6568358** [sass/node-sass#2024]
when i write css with:
filter: progid: DXImageTransform.Microsoft.AlphaImageLoader(src="/images/common/choose.png", sizingMethod="scale");
node-sass will compile fail with space (progid: DXImageTransform),
and that will success (progid:DXImageTransform)

**Comment by nschonni** [comment]
This also fails in Ruby Sass https://www.sassmeister.com/gist/085f6099e951f9ba6e1cc9bf11ab004b
