### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by pconnell99** [sass/node-sass#2029]
Installed on Windows 10 globally (npm install -g node-sass)

In a directory with a single custom.scss file with the following contents:-
```
$primaryColor: #eeffcc;

body {
    background: $primaryColor;
}
```
 Trying the following command throws the issue error:-

**node-sass --watch --recursive --output css --source-map true**
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at getOptions (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:186:40)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:390:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

Searching for this issue shows widespread problems with different libraries where path strings are being asserted instead of returning empty string if null.  Tried quoting the 'css' path but no change.  Suggestions were to downgrade to Node 5 from 6 (I do not wish to so this).

- NPM version:
5.0.3
- Node version:
v6.10.0
- Node Process:
{ http_parser: '2.7.0',
  node: '6.10.0',
  v8: '5.1.281.93',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform:
win32
- Node architecture:
x64
- node-sass version:
Fails
- npm node-sass versions:
(empty (installed globally) but node-sass -v returns
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]

**Comment by xzyfer** [comment]
I'm not a computer ATM but I believe you are using the source map flag
incorrectly. Please double check the documentation for the --source-mal
flag.

**Comment by pconnell99** [comment]
Removed that flag, now running

`node-sass --watch --recursive --output css`

Same error.

**Comment by xzyfer** [comment]
This won't work because you've not told node-sass which file or directory
to watch

**Comment by pconnell99** [comment]
I was following the command line documentation?  If you just type `node-sass` it shows you an example.  I just added . to the command and it worked.  Thanks, the command line examples aren't very clear though.

Command that works is `node-sass . --watch --recursive --output css`

**Comment by xzyfer** [comment]
The full example in the documentation spans two lines, an easy mistake to make

```sh
node-sass --watch --recursive --output css --source-map true --source-map-contents sass
```

The above command works because the CLI is instructed to compile files in the `sass` directory and put the output into the `css` directory.


```
node-sass . --watch --recursive --output css
```
The same goes for the above. Node Sass is compiling files from the `.` directory to the `css` directory.

**Comment by pconnell99** [comment]
Makes sense.  Thank you.

**Comment by xzyfer** [comment]
We should provide better error handling. We'll work on that.
