### ISSUE TITLE
Error 404 on npm install

### ISSUE THREAD

**Issue by storm1er** [sass/node-sass#2034]
I tried multiple method install like none/global/save but no result, always same error with weird link : 

```bash
Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-3.13.1.tgz/linux-x64-57_binding.node":

HTTP error 404 Not Found
```

https://pastebin.com/3J5SNvdB

- NPM version (`npm -v`): 5.0.4
- Node version (`node -v`): 8.1.3
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '8.1.3',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       https://registry.npmjs.org/node-sass/-/node-sass-3.13.1.tgz     (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
/home/storm1er/Documents/dev/wheelEvent
└──  extraneous error: Invalid version: "https://registry.npmjs.org/node-sass/-/node-sass-3.13.1.tgz

npm ERR! extraneous: node-sass /home/storm1er/Documents/dev/wheelEvent/node_modules/node-sass
npm ERR! error in /home/storm1er/Documents/dev/wheelEvent/node_modules/node-sass: Invalid version: "https://registry.npmjs.org/node-sass/-/node-sass-3.13.1.tgz"
```

- [X] *If you delete this text without following it, your issue will be closed.*

**Comment by xzyfer** [comment]
Update node sass to v4.5 or down grade node to v6

**Comment by jeremybalog** [comment]
This isn't really an acceptable solution.  Popular packages use 3.13.1 as a dependency which breaks any new installs, such as Laravel Elixir (2000+ installs/day: https://www.npmjs.com/package/laravel-elixir).  It seems pretty ridiculous that a legacy version would be removed knowing it would cause a boatload of cascading issues with node-sass being such a popular dependency.

**Comment by nschonni** [comment]
@jeremybalog nothing was removed, there was never support for Node 8 in anything but release 4.5.3

**Comment by jeremybalog** [comment]
@nschonni Then why are there numerous issues created saying just that?  The download links all return 404 and causes install failures.  Version 3.13.1 MUST have existed at some point, but is not listed as a release under releases anymore.  Something somewhere had to have been deleted, right?

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

**Comment by jeremybalog** [comment]
^ actually I see the issue with that is node8 per the 57 ending, but even if I downgrade to node6 it still fails because 3.13.1 is not a version anymore...

**Comment by jeremybalog** [comment]
^ actually I think I may have solved it--going to try installing node 7 and see if that does it.

**Comment by saper** [comment]
@nschonni do you have any idea why some users seem to be stuck with 3.13.1?
