### ISSUE TITLE
HTTP error 404 downloading node-sass 4.5.3 binding binary for Windows 10 X64

### ISSUE THREAD

**Issue by claudio4** [sass/node-sass#2035]
When I do "npm install" in my project's folder the download of the binding binary fails returning me this:

> Downloading binary from https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/win32-x64-57_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-4.5.3.tgz/win32-x64-57_binding.node":
> 
> HTTP error 404 Not Found
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 

- NPM version (`npm -v`): 5.0.3
- Node version (`node -v`): v8.1.3
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0',
  node: '8.1.3',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }`
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/1991#issuecomment-306437979

**Comment by boom1234** [comment]
What is the solution for the 404 error, pls? I ve got the same problem.

**Comment by xzyfer** [comment]
Install the latest node-sass
