### ISSUE TITLE
Can not install on windows 10

### ISSUE THREAD

**Issue by gustavom** [sass/node-sass#2038]
Quando tento instalar o projeto Wes Bos "learn node", ocorre para mim:

npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.0 install C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= -
-libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\which\\which.js:13:12)\n
   at F (C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\Aprendend
oNodeJS\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Lenovo\\Document
s\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\isexe\\windows.js:
36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\which\\which.js:13:12)\n
  at F (C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\Aprendendo
NodeJS\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Lenovo\\Documents
\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\isexe\\windows.js:3
6:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lenovo\\Documents\\Projetos\\WesBos\\LearnNode\\AprendendoNodeJS\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--li
bsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Lenovo\Documents\Projetos\WesBos\LearnNode\AprendendoNodeJS\node_modules\node-sass
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2017-07-03T23_59_02_686Z-debug.log

**Comment by xzyfer** [comment]
You need 4.5.3 for Node 8.

```
npm install node-sass@^4.5.3
```

**Comment by iof76** [comment]
Same error here. I "upgrade" the node-sass version as says xzyfer and the error es still there.

**Comment by navarrorc** [comment]
@iof76 I was having the same problem but it was due to the fact that I was behind a corporate firewall at work, who knows what things it blocked. I disconnect from that network and used the hotspot on my phone and it worked.
