### ISSUE TITLE
node sass error--Ionic project

### ISSUE THREAD

**Issue by sabarinathen** [sass/node-sass#2042]
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)

**Comment by sabarinathen** [comment]
Any Idea?

          Thanks

**Comment by xzyfer** [comment]
Iconic doesn't support node 8.

**Comment by sabarinathen** [comment]
how do I resolve?

**Comment by xzyfer** [comment]
Install Node 6.

**Comment by EduardoOliveira** [comment]
Hi, is there a fix that doesn't make me roll back to older versions? is this packages deprecated/not maintained?

Thank you

**Comment by xzyfer** [comment]
Install the latest version of node sass.
