### ISSUE TITLE
Failed at the node-sass@4.5.3

### ISSUE THREAD

**Issue by satyap123** [sass/node-sass#2046]
When I run npm i to install ag-grid-angualr-seed it  failed at the node-sass

118084 info lifecycle xmlbuilder@4.2.1~postinstall: xmlbuilder@4.2.1
118085 silly lifecycle xmlbuilder@4.2.1~postinstall: no script for postinstall, continuing
118086 silly postinstall xml2js@0.4.4 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\xml2js-7c55a9d5
118087 info lifecycle xml2js@0.4.4~postinstall: xml2js@0.4.4
118088 silly lifecycle xml2js@0.4.4~postinstall: no script for postinstall, continuing
118089 silly postinstall selenium-webdriver@2.53.3 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\selenium-webdriver-58d7db46
118090 info lifecycle selenium-webdriver@2.53.3~postinstall: selenium-webdriver@2.53.3
118091 silly lifecycle selenium-webdriver@2.53.3~postinstall: no script for postinstall, continuing
118092 silly postinstall webdriver-js-extender@1.0.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\webdriver-js-extender-2eef753f
118093 info lifecycle webdriver-js-extender@1.0.0~postinstall: webdriver-js-extender@1.0.0
118094 silly lifecycle webdriver-js-extender@1.0.0~postinstall: no script for postinstall, continuing
118095 silly postinstall xml2js@0.4.17 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\xml2js-4685ffd2
118096 info lifecycle xml2js@0.4.17~postinstall: xml2js@0.4.17
118097 silly lifecycle xml2js@0.4.17~postinstall: no script for postinstall, continuing
118098 silly postinstall webdriver-manager@12.0.6 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\webdriver-manager-28105586
118099 info lifecycle webdriver-manager@12.0.6~postinstall: webdriver-manager@12.0.6
118100 silly lifecycle webdriver-manager@12.0.6~postinstall: no script for postinstall, continuing
118101 silly postinstall selenium-webdriver@3.0.1 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\selenium-webdriver-3c98a0f0
118102 info lifecycle selenium-webdriver@3.0.1~postinstall: selenium-webdriver@3.0.1
118103 silly lifecycle selenium-webdriver@3.0.1~postinstall: no script for postinstall, continuing
118104 silly postinstall xmldom@0.1.27 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\xmldom-983cf70f
118105 info lifecycle xmldom@0.1.27~postinstall: xmldom@0.1.27
118106 silly lifecycle xmldom@0.1.27~postinstall: no script for postinstall, continuing
118107 silly postinstall img-stats@0.5.2 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\img-stats-6513eba5
118108 info lifecycle img-stats@0.5.2~postinstall: img-stats@0.5.2
118109 silly lifecycle img-stats@0.5.2~postinstall: no script for postinstall, continuing
118110 silly postinstall directory-encoder@0.7.2 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\directory-encoder-bdf36f54
118111 info lifecycle directory-encoder@0.7.2~postinstall: directory-encoder@0.7.2
118112 silly lifecycle directory-encoder@0.7.2~postinstall: no script for postinstall, continuing
118113 silly postinstall postcss-url@5.1.2 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\postcss-url-f3a65eeb
118114 info lifecycle postcss-url@5.1.2~postinstall: postcss-url@5.1.2
118115 silly lifecycle postcss-url@5.1.2~postinstall: no script for postinstall, continuing
118116 silly postinstall xmlhttprequest-ssl@1.5.3 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\xmlhttprequest-ssl-e5b7f033
118117 info lifecycle xmlhttprequest-ssl@1.5.3~postinstall: xmlhttprequest-ssl@1.5.3
118118 silly lifecycle xmlhttprequest-ssl@1.5.3~postinstall: no script for postinstall, continuing
118119 silly postinstall xtend@4.0.1 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\xtend-fe7c8ee9
118120 info lifecycle xtend@4.0.1~postinstall: xtend@4.0.1
118121 silly lifecycle xtend@4.0.1~postinstall: no script for postinstall, continuing
118122 silly postinstall stream-http@2.7.2 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\stream-http-7c99ac65
118123 info lifecycle stream-http@2.7.2~postinstall: stream-http@2.7.2
118124 silly lifecycle stream-http@2.7.2~postinstall: no script for postinstall, continuing
118125 silly postinstall node-libs-browser@2.0.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\node-libs-browser-6a2ebde2
118126 info lifecycle node-libs-browser@2.0.0~postinstall: node-libs-browser@2.0.0
118127 silly lifecycle node-libs-browser@2.0.0~postinstall: no script for postinstall, continuing
118128 silly postinstall y18n@3.2.1 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\y18n-a5033b84
118129 info lifecycle y18n@3.2.1~postinstall: y18n@3.2.1
118130 silly lifecycle y18n@3.2.1~postinstall: no script for postinstall, continuing
118131 silly postinstall yargs@6.6.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\yargs-cc891624
118132 info lifecycle yargs@6.6.0~postinstall: yargs@6.6.0
118133 silly lifecycle yargs@6.6.0~postinstall: no script for postinstall, continuing
118134 silly postinstall webpack-dev-server@2.3.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\webpack-dev-server-2da48aea
118135 info lifecycle webpack-dev-server@2.3.0~postinstall: webpack-dev-server@2.3.0
118136 silly lifecycle webpack-dev-server@2.3.0~postinstall: no script for postinstall, continuing
118137 silly postinstall yargs@6.6.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\yargs-24984e34
118138 info lifecycle yargs@6.6.0~postinstall: yargs@6.6.0
118139 silly lifecycle yargs@6.6.0~postinstall: no script for postinstall, continuing
118140 silly postinstall webpack@2.2.1 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\webpack-c1214cd7
118141 info lifecycle webpack@2.2.1~postinstall: webpack@2.2.1
118142 silly lifecycle webpack@2.2.1~postinstall: no script for postinstall, continuing
118143 silly postinstall yallist@2.1.2 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\yallist-f6f86b50
118144 info lifecycle yallist@2.1.2~postinstall: yallist@2.1.2
118145 silly lifecycle yallist@2.1.2~postinstall: no script for postinstall, continuing
118146 silly postinstall lru-cache@4.1.1 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\lru-cache-a567eea1
118147 info lifecycle lru-cache@4.1.1~postinstall: lru-cache@4.1.1
118148 silly lifecycle lru-cache@4.1.1~postinstall: no script for postinstall, continuing
118149 silly postinstall cross-spawn@3.0.1 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\cross-spawn-fae86d53
118150 info lifecycle cross-spawn@3.0.1~postinstall: cross-spawn@3.0.1
118151 silly lifecycle cross-spawn@3.0.1~postinstall: no script for postinstall, continuing
118152 silly postinstall camelcase@3.0.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\camelcase-0b71849f
118153 info lifecycle camelcase@3.0.0~postinstall: camelcase@3.0.0
118154 silly lifecycle camelcase@3.0.0~postinstall: no script for postinstall, continuing
118155 silly postinstall yargs-parser@5.0.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\yargs-parser-903ddcd6
118156 info lifecycle yargs-parser@5.0.0~postinstall: yargs-parser@5.0.0
118157 silly lifecycle yargs-parser@5.0.0~postinstall: no script for postinstall, continuing
118158 silly postinstall camelcase@3.0.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\camelcase-2ce712ed
118159 info lifecycle camelcase@3.0.0~postinstall: camelcase@3.0.0
118160 silly lifecycle camelcase@3.0.0~postinstall: no script for postinstall, continuing
118161 silly postinstall is-fullwidth-code-point@1.0.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\is-fullwidth-code-point-8809abd8
118162 info lifecycle is-fullwidth-code-point@1.0.0~postinstall: is-fullwidth-code-point@1.0.0
118163 silly lifecycle is-fullwidth-code-point@1.0.0~postinstall: no script for postinstall, continuing
118164 silly postinstall string-width@1.0.2 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\string-width-191e5c71
118165 info lifecycle string-width@1.0.2~postinstall: string-width@1.0.2
118166 silly lifecycle string-width@1.0.2~postinstall: no script for postinstall, continuing
118167 silly postinstall yargs@7.1.0 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\yargs-b18772eb
118168 info lifecycle yargs@7.1.0~postinstall: yargs@7.1.0
118169 silly lifecycle yargs@7.1.0~postinstall: no script for postinstall, continuing
118170 silly postinstall sass-graph@2.2.4 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\sass-graph-ae282e1e
118171 info lifecycle sass-graph@2.2.4~postinstall: sass-graph@2.2.4
118172 silly lifecycle sass-graph@2.2.4~postinstall: no script for postinstall, continuing
118173 silly postinstall node-sass@4.5.3 C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging\node-sass-89c44775
118174 info lifecycle node-sass@4.5.3~postinstall: node-sass@4.5.3
118175 verbose lifecycle node-sass@4.5.3~postinstall: unsafe-perm in lifecycle true
118176 verbose lifecycle node-sass@4.5.3~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\node-sass

\node_modules\.bin;C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS 

Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files\Intel\Intel(R) Management 

Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) 

Management Engine Components\IPT;C:\Program Files (x86)\Java\jre8\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server

\130\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server

\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files 

(x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files

\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS

\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine 

Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Java\jre8\bin;C:

\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn

\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program 

Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL 

Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\GIT\Git\cmd
118177 verbose lifecycle node-sass@4.5.3~postinstall: CWD: C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\node-sass
118178 silly lifecycle node-sass@4.5.3~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
118179 silly lifecycle node-sass@4.5.3~postinstall: Returned: code: 1  signal: null
118180 info lifecycle node-sass@4.5.3~postinstall: Failed to exec postinstall script
118181 verbose unlock done using C:\Users\UserName\AppData\Roaming\npm-cache\_locks\staging-ffa0a58a6d08f2de.lock for C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli\node_modules\.staging
118182 silly rollbackFailedOptional Starting
118183 silly rollbackFailedOptional Finishing
118184 silly runTopLevelLifecycles Finishing
118185 silly install printInstalled
118186 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
118187 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
118188 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
118188 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
118188 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
118188 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
118189 warn ag-grid-angular@10.1.0 requires a peer of ag-grid@10.1.x but none was installed.
118190 verbose If you need help, you may report this error at:
118190 verbose     <https://github.com/npm/npm/issues>
118191 warn ag-grid-enterprise@10.1.0 requires a peer of ag-grid@10.1.x but none was installed.
118192 verbose If you need help, you may report this error at:
118192 verbose     <https://github.com/npm/npm/issues>
118193 warn @angular/tsc-wrapped@4.3.0 requires a peer of typescript@^2.1.5 but none was installed.
118194 verbose If you need help, you may report this error at:
118194 verbose     <https://github.com/npm/npm/issues>
118195 warn tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.
118196 verbose If you need help, you may report this error at:
118196 verbose     <https://github.com/npm/npm/issues>
118197 verbose stack Error: node-sass@4.5.3 postinstall: `node scripts/build.js`
118197 verbose stack Exit status 1
118197 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
118197 verbose stack     at emitTwo (events.js:106:13)
118197 verbose stack     at EventEmitter.emit (events.js:191:7)
118197 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
118197 verbose stack     at emitTwo (events.js:106:13)
118197 verbose stack     at ChildProcess.emit (events.js:191:7)
118197 verbose stack     at maybeClose (internal/child_process.js:891:16)
118197 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
118198 verbose pkgid node-sass@4.5.3
118199 verbose cwd C:\AG-GRID\AG\ag-grid-angular-seed-master\angular-cli
118200 error Windows_NT 6.1.7601
118201 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
118202 error node v6.11.1
118203 error npm  v3.10.10
118204 error code ELIFECYCLE
118205 error node-sass@4.5.3 postinstall: `node scripts/build.js`
118205 error Exit status 1
118206 error Failed at the node-sass@4.5.3 postinstall script 'node scripts/build.js'.
118206 error Make sure you have the latest version of node.js and npm installed.
118206 error If you do, this is most likely a problem with the node-sass package,
118206 error not with npm itself.
118206 error Tell the author that this fails on your system:
118206 error     node scripts/build.js
118206 error You can get information on how to open an issue for this project with:
118206 error     npm bugs node-sass
118206 error Or if that isn't available, you can get their info via:
118206 error     npm owner ls node-sass
118206 error There is likely additional logging output above.
118207 verbose exit [ 1, true ]

**Comment by saper** [comment]
Please fill in the issue template properly.
