### ISSUE TITLE
yarn modules-folder parameter reveal >>>Error: Cannot find module 'mkdirp'<<<

### ISSUE THREAD

**Issue by stopsopa** [sass/node-sass#2050]
about [modules-folder](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-modules-folder)

Error doesn't happen with other libraries, for example lodash

Environment:
----
    node: v6.10.0
    npm: 3.10.10
    yarn: v0.21.3

![image](https://user-images.githubusercontent.com/3743506/28494396-8bb51e3e-6f2d-11e7-90ac-4a7a3f70958b.png)

Steps to reproduce error:
----

    D:\www>mkdir test

    D:\www>cd test

    D:\www\test>yarn add node-sass
    yarn add v0.21.3
    info No lockfile found.
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 173 new dependencies.
    ├─ abbrev@1.1.0
    ├─ ajv@4.11.8
    ├─ amdefine@1.0.1
    ├─ ansi-regex@2.1.1
    ├─ ansi-styles@2.2.1
    ├─ .
    ├─ ..
    ├─ ...
    ├─ y18n@3.2.1
    ├─ yallist@2.1.2
    ├─ yargs-parser@5.0.0
    └─ yargs@7.1.0
    Done in 7.11s.

    D:\www\test>dir
     Volume in drive D is Magazyn
     Volume Serial Number is 54AB-00D8

     Directory of D:\www\test

    2017-07-22  10:17 PM    <DIR>          .
    2017-07-22  10:17 PM    <DIR>          ..
    2017-07-22  10:17 PM    <DIR>          node_modules
    2017-07-22  10:17 PM                59 package.json
    2017-07-22  10:17 PM            36,046 yarn.lock
                   2 File(s)         36,105 bytes
                   3 Dir(s)  32,325,296,128 bytes free

    D:\www\test>rm -rf node_modules

    D:\www\test>yarn install --modules-folder=public
    yarn install v0.21.3
    warning No license field
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    [1/1] ⠄ node-sass
    [-/1] ⠄ waiting...
    [-/1] ⠄ waiting...
    [-/1] ⠄ waiting...
    error public\node-sass: Command failed.
    Exit code: 1
    Command: C:\WINDOWS\system32\cmd.exe
    Arguments: /d /s /c node scripts/install.js
    Directory: public\node-sass
    Output:
    module.js:471
        throw err;
        ^

    Error: Cannot find module 'mkdirp'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\www\test\public\node-sass\scripts\install.js:7:11)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    D:\www\test>

**Comment by saper** [comment]
I am assuming you are getting node-sass v4.5.3 ? Your log does not seem to be saying that.

Our [install.js](https://github.com/sass/node-sass/blob/48bbed1b923ab3f6338f866e8dc3fe906909803b/scripts/install.js#L7) is using normal `require('mkdirp')` which is a node feature that works since the early days. 

Even after reading https://github.com/yarnpkg/yarn/issues/1684 I have no idea what is the purpose of this option; it seems that everybody seems to use `node_modules` as a part of their path, like in 

    yarn install --modules-folder=public/node_modules

`node_modules` is hardcoded in node and there is no way to override that. npm refused to implement anything to change that directory for npm https://github.com/npm/npm/issues/775

Feel free to ask https://github.com/yarnpkg/yarn/issues/1684 for more details, but I would refrain from using this option if it is not understood well.

**Comment by stopsopa** [comment]
Yes, seems that there is no other way to tell npm to install libraries in other directory then in node_modules but by changing global variable **process.env.NODE_PATH**. And problems with that reveals on node-sass but not on lodash because node-sass has scripts that runs immediately after install. Lodash don't have it. 

Because this script is working on unchanged environment (without redirected *NODE_PATH*) that's why it can't find *mkdirp* library.

Took me a while to find that, and in the process i thought that this is error of node-sass itself, but is not.

Solution is to change *NODE_PATH* and then install libraries, like:

    for /f "tokens=*" %a in ('echo %cd%\public') do @set NODE_PATH=%a
    echo %NODE_PATH%
    yarn install --modules-folder=public
    

And because of that, actually this problem is not related with *yarn* at all, it's probably gonna happen with **npm** install as well.

Thank you for help anyway.

**Comment by saper** [comment]
Thanks for bringing this to out attention, I didn't know yarn can do this. Npm cannot.

**Comment by nageshjawanjal** [comment]
create new project of same version and then go to node_modules copy "mkdirp" folder and paste it to your  Project's node_module folder

**Comment by tranhl** [comment]
@saper I'm not sure about other people, but I typically use `--modules-folder` during multistage Docker builds to cache dependency installation. It allows me to install both the dependencies needed for the build process, as well as the production dependencies earlier in the build process, which significantly improves build time (from 3 mins to ~10 seconds).

For example:
```
RUN yarn install --prod --link-duplicates --modules-folder ./prod_node_modules
RUN yarn install --modules-folder ./node_modules
```
