### ISSUE TITLE
npm ERR! node-sass@4.5.3 fail `node scripts/build.js`

### ISSUE THREAD

**Issue by german1608** [sass/node-sass#2052]
I'm getting the following error:
https://pastebin.com/ZaWSKHbJ

This is the log
https://pastebin.com/kEiV4eXx

I'm currently using node v6.11.1 and npm 3.10.10 on ubuntu

**Comment by saper** [comment]
Can please fill in issue template? We need the output of `node -v`

**Comment by tscislo** [comment]
Same happens here. I got the following error I guess it's connected with expired SSL certificate:

 Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-47_binding.node": 
02:21:00 [ERROR] 
02:21:00 [ERROR] tunneling socket could not be established, statusCode=403
02:21:00 [ERROR] 
02:21:00 [ERROR] Hint: If github.com is not accessible in your location
02:21:00 [ERROR]       try setting a proxy via HTTP_PROXY, e.g. 
02:21:00 [ERROR] 
02:21:00 [ERROR]       export HTTP_PROXY=http://example.com:1234
02:21:00 [ERROR] 
02:21:00 [ERROR] or configure npm proxy via
02:21:00 [ERROR] 
02:21:00 [ERROR]       npm config set proxy http://example.com:8080

**Comment by ashishsantikari** [comment]
Added issue template on behalf of @german1608 

- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.9.5
- Node Process (`node -p process.versions`): { http_parser: '2.7.0', node: '6.9.5', v8: '5.1.281.89',uv: '1.9.1', zlib: '1.2.8', ares: '1.10.1-DEV', icu: '57.1', modules: '48', openssl: '1.0.2k' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): node-sass	4.5.2(Wrapper)[JavaScript] 
   libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):

**Comment by saper** [comment]
The problem here is that there are different versions of node in use. The version you are going to use with node-sass must be on a system PATH

**Comment by saper** [comment]
@tscislo please check your firewall/proxy settings. To the best of my knowledge Github didn't let their SSL certificate expire recently.

**Comment by Jan-Bart** [comment]
I think it has nothing to do with firewall and/or proxy settings.
If you try to download the file at https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-47_binding.node 
you get a Deceptive Site! warning.

```This web page at github-production-release-asset-2e65be.s3.amazonaws.com has been reported as a deceptive site and has been blocked based on your security preferences.

Deceptive sites are designed to trick you into doing something dangerous, like installing software, or revealing your personal information, like passwords, phone numbers or credit cards.

Entering any information on this web page may result in identity theft or other fraud.```

**Comment by tscislo** [comment]
@Jan-Bart 
That exactly where the problem is. Any ideas why this SSL certificate is invalid?

**Comment by Jan-Bart** [comment]
@tscislo The SSL certificate is valid. But the url is reported as "deceptive site".

**Comment by tscislo** [comment]
That is correct, this is the problem...

Kind regards / Pozdrawiam
Tomasz Scislo
scislot@gmail.com
http://scislo.eu
http://mobilenext.scislo.eu

**Comment by tscislo** [comment]
I already reported this to github... no ETA

**Comment by saper** [comment]
I have tried to fetch the URL via the corporate firewall I have access to and it worked fine for Firefox and IE11. Maybe you should contact your proxy or browser vendor for a fix.
