### ISSUE TITLE
Error while detecting new changes to Scss Files

### ISSUE THREAD

**Issue by jinuem** [sass/node-sass#2053]
- NPM version : 3.10.10
- Node version: 6.11.0
- Node Platform: Win32
- Node architecture: x64
- node-sass version : 4.5.3 
- npm node-sass versions : 4.5.3
- Node process Versions : {http_parser: 2.7.0, node: 6.11.0, v8: 5.1.281.102, uv: 1.11.0, zlib: 1.2.11, ares: 1.10.1-dev, icu: 58.2, modules: 48, openssl: 1.0.2k}

I am using this Sass watch in my create-react-app. Integrated as per the Create-React-App Documentation.

```
  "build-css": "node-sass src/ -o src/",
  "watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive"
```
When i do `npm run watch-css`, it starts watching for my Scss files and converts properly. Everything Complies perferctly.
But When i tried to change any Scss file and I save the file, it detects the change and throws the Error.

Attaching the Debug Log:

> 17 error Windows_NT 6.1.7601
> 18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 19 error node v6.11.0
> 20 error npm  v3.10.10
> 21 error code ELIFECYCLE
> 22 error eli@0.1.0 start: `npm-run-all -p watch-css start-js`
> 22 error Exit status 1
> 23 error Failed at the eli@0.1.0 start script 'npm-run-all -p watch-css start-js'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the eli package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     npm-run-all -p watch-css start-js
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs eli
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls eli
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by saper** [comment]
This does not seem to come from node-sass, only from the `eli` package which tries to run `npm-run-all`. Maybe if you prepare a small reproduction case in the self-contained repository we can have a look further.

**Comment by jinuem** [comment]
@saper Thanks for checking it out.

```
  "scripts": {
    "start-js": "react-scripts-ts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject",
    "build-css": "node-sass src/ -o src/",
    "watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive"
  }
```

`Eli `is the Project Name. `npm-run-all` to run both `watch-css` command and `npm start`.
But still, even if i run `watch-css` also i get same issue.

**Comment by saper** [comment]
@jinuem sorry, please simplify your case since it is not clear what is happening. I do not know how could I reproduce the problem.
