### ISSUE TITLE
Equivalent to the ruby sass-convert in node-sass?

### ISSUE THREAD

**Issue by Spunkie** [sass/node-sass#2060]
Is there is an equivalent to the ruby `sass-convert` in node-sass? I can't seem to find any mention of it in docs or GH issues.

I know there is `sass2scss` bundled with libsass but I believe that only handles 1 way conversions of `sass --> scss` while rubys `sass-convert` allows a multiway conversion like `sass <-> scss <-- css`.

I'm converting over old build/watch scripts based on ruby sass to npm scripts with node-sass and everything has been easy so far except one small script. The script watches a dir for any new `css` files and uses `sass-convert` to convert it to a well formatted and nested `scss` file. I've tried doing cmds like `node-sass input.css output.scss --output scss` but this does not actually transform the `css` in any way.
___
```
- NPM version: 4.2.0
- Node version: v8.1.3
- Node Process: { 
    http_parser: '2.7.0',
    node: '8.1.3',
    v8: '5.8.283.41',
    uv: '1.12.0',
    zlib: '1.2.11',
    ares: '1.10.1-DEV',
    modules: '57',
    openssl: '1.0.2l',
    icu: '59.1',
    unicode: '9.0',
    cldr: '31.0.1',
    tz: '2017b' 
  }
- Node Platform: win32
- Node architecture: x64
- node-sass version:
    node-sass       4.5.3   (Wrapper)       [JavaScript]
    libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions: node-sass@4.5.3
```
https://github.com/sass/libsass/issues/2455

**Comment by xzyfer** [comment]
We have no equivalent and don't plan on added one for the foreseeable
future.
