### ISSUE TITLE
v3.13.1/linux-x64-57_binding.node does not exit

### ISSUE THREAD

**Issue by deeana2** [sass/node-sass#2061]
Hello, 
my angular project by itself requires the latest node-sass, and there is no any problem with that, but some dependency requires 
https://github.com/sass/node-sass/releases/download/v3.10.0/linux-x64-57_binding.node

but there is no such thing, only v3.10.0/linux-x64-51_binding.node exists, but need 57.
Would you be able to produce and give me such binary?

INFO:
- NPM version (`npm -v`): 5.3.0
- Node version (`node -v`): v8.2.1
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.8.283.41',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64

**Comment by saper** [comment]
Your version of node-sass does not support node 8 yet. Use a newer node-sass or downgrade your node engine.
