### ISSUE TITLE
Error when yarn install node-sass@3.13.1 in devDependencies from package.json

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [sass/node-sass#2069]
**$ yarn install** (package.json devDependencies already has "node-sass": "^3.13.1",)

remove node-sass from package.json, and yarn install ok , yarn.lock generated.
and then  use **$ yarn add node-sass** will ok and update .lock file.
besides,
package already has **node-sass": "^3.13.1** , then **yarn upgrade node-sass** will broken and output error 
> "\node_modules\node-sass: Command failed"

**Comment by xzyfer** [comment]
Please open an issue with yarn
