### ISSUE TITLE
MSBUILD error

### ISSUE THREAD

**Issue by rohit1049** [sass/node-sass#2074]
I have tried the troubleshooting steps for installing node-sass. But it did not work fine. It did not installed the node-sass and generated the npm.err and npm.log files.
The log file is attached.
[npm_log.txt](https://github.com/sass/node-sass/files/1244831/npm_log.txt)
How can it be solved?

**Comment by xzyfer** [comment]
Long contents

```

> node-sass@4.5.3 install C:\DCDx\test\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node

> node-sass@4.5.3 postinstall C:\DCDx\test\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\DCDx\test\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 8/23/2017 2:31:46 PM.
Project "C:\DCDx\test\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\DCDx\test\node_modules\node-sass\build\binding.sln]
Done Building Project "C:\DCDx\test\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\DCDx\test\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) -> 
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\DCDx\test\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.53
```

**Comment by xzyfer** [comment]
What `npm` command did you run?

**Comment by rohit1049** [comment]
npm install -ddd node-sass > npm.log 2> npm.err

**Comment by jtq** [comment]
I don't know if it's connected, but it appears that something fairly major has changed in npm-sass between Aug 22, 2017 15:33 and Aug 22, 2017 20:13 (GMT), without changing the version number.

Both of the following builds are using node-sass@4.5.0, downloaded from https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64-48_binding.node.  See if you can spot the difference:

15:33:
`mkdirp build/docs/styleguide && node-sass src/resources/sass/*.scss | postcss --config config/postcss.styleguide.js > build/docs/styleguide/style.css
15:36:01 
15:36:03 ✔ Finished stdin (71ms)
15:36:04 Style guide build completed successfully!`

20:13:
`mkdirp build/docs/styleguide && node-sass src/resources/sass/*.scss | postcss --config config/postcss.styleguide.js > build/docs/styleguide/style.css
20:16:13 
20:16:13 Rendering Complete, saving .css file...
20:16:13 Wrote CSS to /apps/ctp/jenkins/workspace/excalibur/ctp-loro-react-ui-toolkit/sanity-check-and-document-ctp-loro-react-ui-toolkit-2.x/src/resources/sass/sports.scss
20:16:13 ✖ Input Error: Did not receive any STDIN`

**Comment by saper** [comment]
Something is wrong with Visual Studio installation, vcbuild is a pretty old thing.

**Comment by nschonni** [comment]
Please follow the refer to the minimum requirements for `node-gyp` as in our README https://github.com/nodejs/node-gyp#on-windows
You should be able to just download our precompiled binaries. If you had an issue with that, that is also covered in our TROUBLESHOOTING guide.

**Comment by garhbod** [comment]
Install all the required tools and configurations using Microsoft's windows-build-tools by running `npm install -g windows-build-tools` from an elevated PowerShell (run as Administrator).

It takes a while.

Then run `npm config set msvs_version 2015 -g`

sorted the issue for me

**Comment by mohamedebrahim96** [comment]
@garhbod work like the charm .
this line enough
`npm install -g windows-build-tools`
.
.

![rtertret](https://user-images.githubusercontent.com/16405013/34608523-630d9a16-f221-11e7-9fc3-eb12ecd1ab04.JPG)

**Comment by Freemahn** [comment]
@garhbod Thanks a lot, that helped

**Comment by hani647** [comment]
@garhbod Man, you just save a life ! Spent my hours and after that I found your fix and worked like a charm ! (y)

**Comment by carlosquijano** [comment]
@garhbod  Worked for me, No need for Visual Studio. This has what you need:

`npm install --global --production windows-build-tools1`

Thanks!

**Comment by gsidler** [comment]
I ran into the exact same issue that the original post reported. The fix suggested above by garhbod and confirmed by many others did not work for me. `npm install -g windows-build-tools` was always hanging. 

I finally managed to get it working by downgrading Node.js from the version 10 branch to the version 8 branch.

**Comment by andersand** [comment]
@gsidler it was hanging here too (npm version 6.1.0, node version 8.11.2),  but as `npm install -g windows-build-tools` stopped logging (logs to file C:\Users\MyUserName\.windows-build-tools\build-tools-log.txt ) I just hit ctrl-c to terminate and after running `npm config set msvs_version 2015 -g` I could successfully run `npm install`, which in turn wants to compile (...)\node_modules\node-sass\build\binding.sln

**Comment by ScubaDrew** [comment]
Same thing happened to me on same versions as @andersand - his suggestion to run npm config set msvs_version 2015 -g worked. I was able to do npm install after that.

**Comment by rajatkhare619** [comment]
@garhbod Thanks! It worked.

**Comment by dwale** [comment]
nice one @garhbod

**Comment by AaronOliver94** [comment]
An additional step that might prevent further problems is that you should run the npm install for your project in an elevated PowerShell (I usually just do it from the terminal in VSC - which lacks permissions). Thanks @garhbod.
