### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node" 404

### ISSUE THREAD

**Issue by liuyimx** [sass/node-sass#2078]
when use npm install node-sass , the console print :
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node"
HTTP error 404 Not Found

npm 8.4
npm ---- https://registry.npmjs.org/
win10
my pc can access github. no need proxy

**Comment by nschonni** [comment]
Upgrade to 4.5.3 for Node 8 support

**Comment by mohamed-boukhlif** [comment]
@nschonni pllz how to upgrade it when you are in ionic project and node-sass is not in package.json

thanks in advance

**Comment by xzyfer** [comment]
npm update node-sass

**Comment by mohamed-boukhlif** [comment]
but node-sass isn't a dependency !
the command gives no result

**Comment by xzyfer** [comment]
Try npm install --save node-sass@latest

**Comment by mohamed-boukhlif** [comment]
no he still gives me this error when running npm install

npm WARN deprecated babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-preset-minify

> node-sass@4.5.0 install C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\@ionic\app-scripts\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\@ionic\app-scripts\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.8.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:80:29)\n    at C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:89:16\n    at C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\isexe\\index.js:42:5\n    at C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:80:29)\n    at C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\which\\which.js:89:16\n    at C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\isexe\\index.js:42:5\n    at C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\Archive\\JoCarts 7\\JoCarts\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Projects\Archive\JoCarts 7\JoCarts\node_modules\@ionic\app-scripts\node_modules\node-sass
gyp ERR! node -v v8.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN @ionic-native/admob-free@3.4.4 requires a peer of @ionic-native/core@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/camera@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/diagnostic@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/geolocation@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/google-analytics@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/in-app-browser@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/location-accuracy@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/network@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/onesignal@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/photo-viewer@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/social-sharing@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/splash-screen@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/status-bar@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/toast@3.1.0 requires a peer of @ionic-native/core@3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/app-scripts@1.2.2 requires a peer of typescript@~2.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-03-10T16_41_06_720Z-debug.log

**Comment by GuiCamargoX** [comment]
See this site : https://www.npmjs.com/package/node-gyp
