### ISSUE TITLE
how can i fixed this issue(win7, npm 5.3.0, vc++ 2013/2015)

### ISSUE THREAD

**Issue by joecfan** [sass/node-sass#2083]
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! personal@4.1.0 watch: `webpack-dev-server --hot --inline --progress --c
olors --port 5000`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the personal@4.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2017-08-30T13_49_47_656Z-d
ebug.log

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
