### ISSUE TITLE
Can't Install 4.5.3: npm ERR! 404 Not Found ansi-styles-2.2.0.tgz

### ISSUE THREAD

**Issue by ant-fx** [sass/node-sass#2084]
- NPM version (`npm -v`): 5.3.0
- Node version (`node -v`): v6.11.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.11.1',
  v8: '5.1.281.103',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Wont install
- npm node-sass versions (`npm ls node-sass`): UNMET DEPENDENCY node-sass@4.5.3

When install the module `npm install node-sass@4.5.3` I get the following:

```
npm ERR! code E404
npm ERR! 404 Not Found: ansi-styles@http://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
```

It seems that `node-sass@4.5.3` uses `chalk@^1.1.1` which uses `ansi-styles-2.2.0` which is no longer available on npmjs.

I suppose the solution should be to upgrade `chalk` to the latest version `2.1.0`?

**Comment by xzyfer** [comment]
This seems like a transient issue. I was able to successfully install node-sass.

```
└─┬ node-sass@4.5.3
  ├── async-foreach@0.1.3
  ├─┬ chalk@1.1.3
```

Remove your node_modules and try again.

**Comment by Harish2887** [comment]
tried but still not working
