### ISSUE TITLE
Have to rebuild node-sass each time I restart server

### ISSUE THREAD

**Issue by rhysburnie** [sass/node-sass#2087]
Hi every time I stop my local server I have to rebuild node-sass `npm rebuild node-sass`

version `node-sass@4.5.3`

Due to this error - extremely frustrating

```
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/rgb/code/afsk/node_modules/node-sass/vendor'
```

Any advice? I have used node-sass for a long time across many projects and frameworks never had this issue until the last two weeks.

**Comment by xzyfer** [comment]
Something is deleting `node_modules/node-sass/vendor` folder. You'll need to track down what is doing that and stop it. There isn't anything we can do.
