### ISSUE TITLE
Node-Sass forces me to manually install/rebuild on TeamCity agent every time

### ISSUE THREAD

**Issue by josemaia** [sass/node-sass#2088]
I am running a TeamCity build, utilizing Cake as the build script, that builds a react application.

This application includes node-sass, and, every time the build agent is restarted, the build breaks.

The build is running inside a TeamCity agent in a Linux (Ubuntu 16.04 LTS) container. Development is performed on windows, but our git repositories do not include node_modules, and so npm install will always have to take care of node-sass w/ the correct OS.

npm -v > 3.10.10
node -v > v6.11.2
node -p process.versions > 
    { http_parser: '2.7.0',
      node: '6.11.2',
      v8: '5.1.281.103',
      uv: '1.11.0',
      zlib: '1.2.11',
      ares: '1.10.1-DEV',
      icu: '56.1',
      modules: '48',
      openssl: '1.0.2l' }

node -p process.platform > linux
node -p process.arch > x64

The other two commands did not return immediately, as the build was breaking and not even installing node-sass. If I manually access the Web app's directory and perform an NPM install, I obtain:

node-sass version: 
    node-sass       4.5.3   (Wrapper)       [JavaScript]
    libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]

npm ls node-sass:
     omnia-ui@0.1.1 /opt/buildagent/work/3bddefdef5cc256e/src/Web/WebApp
    ├── UNMET PEER DEPENDENCY jquery@>=3.0.0
    ├── node-sass@4.5.3
    └── UNMET PEER DEPENDENCY popper.js@^1.11.0

    npm ERR! peer dep missing: jquery@>=3.0.0, required by bootstrap@4.0.0-beta
    npm ERR! peer dep missing: popper.js@^1.11.0, required by bootstrap@4.0.0-beta

We are not using JQuery on purpose, the error is expected.

I attached the package.json and an excerpt of the relevant part of the build log with verbosity enabled:
[OmniaPlatform_LinuxBuild_0.1.111.txt](https://github.com/sass/node-sass/files/1274124/OmniaPlatform_LinuxBuild_0.1.111.txt)

[package.json](https://github.com/sass/node-sass/files/1274130/package.json.txt)

I can provide any more information that can help triage the issue.

**Comment by xzyfer** [comment]
Unfortunately there isn't anything useful in this log. 
```
[15:16:17]W:	 [Step 1/1] npm info lifecycle node-sass@4.5.3~install: node-sass@4.5.3
[15:16:17] :	 [Step 1/1] 
[15:16:17] :	 [Step 1/1] > node-sass@4.5.3 install /opt/buildagent/work/3bddefdef5cc256e/src/Web/WebApp/node_modules/node-sass
[15:16:17] :	 [Step 1/1] > node scripts/install.js
[15:16:17] :	 [Step 1/1] 
[15:16:17]W:	 [Step 1/1] 
[15:16:17]W:	 [Step 1/1] 
[15:16:17]W:	 [Step 1/1] An error occurred when executing task 'Restore-Node'.
[15:16:17]W:	 [Step 1/1] Error: Npm: Process returned an error (exit code 1).
[15:16:18]W:	 [Step 1/1] Process exited with code 1
[15:16:18]E:	 [Step 1/1] Process exited with code 1
[15:16:18]E:	 [Step 1/1] Step Command Line failed
```
Without more information there isn't much help we can offer.

**Comment by josemaia** [comment]
Is there any way I can set things up to get more information? I'm already running npm install with the verbose command.

**Comment by josemaia** [comment]
Things I have already tried:

- Add --unsafe-perm to npm install.
- Force npm rebuild node-sass every time before i do npm run-script build (not relevant, as it doesn't get this far).

**Comment by saper** [comment]
You have yo figure out how to make Restore-Node task to preserve the binary module. I could not find anything on the net about it so you are on your own here. Alternatively you can store the binary in the safe place and use environment variables to point to the binary binding file.
