### ISSUE TITLE
Can't install node-sass on heroku

### ISSUE THREAD

**Issue by pencilcheck** [sass/node-sass#2089]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

*It's on heroku. The information of versioning are listed below:*

# Heroku stack
Auto Cert Mgmt: false
Dynos:          web: 1
Region:         us
Repo Size:      22 MB
Slug Size:      70 MB
Stack:          heroku-16

# Heroku push log
Counting objects: 20, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (20/20), 11.33 KiB | 0 bytes/s, done.
Total 20 (delta 16), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  ~6.11.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version ~6.11.x...
remote:        Downloading and installing node 6.11.3...
remote:        Using default npm version: 3.10.10
remote:        Resolving yarn version (latest)...
remote:        Downloading and installing yarn (1.0.0)...
remote:        Installed yarn 1.0.0
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (disabled)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.0.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.1.1: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning "babel-loader@7.0.0" has incorrect peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
remote:        warning "babel-loader@7.0.0" has incorrect peer dependency "webpack@2".
remote:        warning "webpack-dev-middleware@1.10.2" has incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
remote:        warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
remote:        warning "react-dates@12.3.0" has incorrect peer dependency "moment@^2.18.1".
remote:        warning "react-moment-proptypes@1.4.0" has incorrect peer dependency "moment@>=1.6.0".
remote:        warning "sass-loader@6.0.6" has incorrect peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
remote:        warning "sw-precache-webpack-plugin@0.11.3" has incorrect peer dependency "webpack@^1 || ^2 || ^2.1.0-beta || ^2.2.0-beta".
remote:        warning "babel-preset-react-app@3.0.0" has incorrect peer dependency "babel-runtime@^6.23.0".
remote:        warning "glamorous@3.23.4" has incorrect peer dependency "glamor@>=2".
remote:        warning "url-loader@0.5.9" has incorrect peer dependency "file-loader@*".
remote:        warning "react-html-attributes@1.3.0" has incorrect peer dependency "html-element-attributes@^1.0.0".
remote:        [4/4] Building fresh packages...
remote:        error An unexpected error occurred: "/tmp/build_3ca45f1523c41f3b3d69f74657245a36/node_modules/node-sass: EROFS: read-only file system, access '/usr/local/bin'".
remote:        info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_3ca45f1523c41f3b3d69f74657245a36/yarn-error.log".
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
remote:        https://devcenter.heroku.com/articles/nodejs-support#build-behavior
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy....
remote:
remote: !       Push rejected .
remote:
To 
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to ''

- NPM version (`npm -v`): 
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):

Was trying to install
node-sass@^4.5.3

- npm node-sass versions (`npm ls node-sass`):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by marekstabla** [comment]
Same error here.

**Comment by pencilcheck** [comment]
Would like this to be resolved asap as this never happened before, one of my applications somehow is blocked because of this issue. And unfortunately node-sass is a requirement atm, one of the dependencies of the software we developed.

**Comment by xzyfer** [comment]
Nothing has changed with node-sass. This sounds like an heroku issue. I
suggest you start your debugging by googling the error in the logs

EROFS: read-only file system, access

**Comment by King-Ran** [comment]
Same error here.

**Comment by marekstabla** [comment]
@pencilcheck @xzyfer @King-Ran this is actually yarn issue. Don't have link to the issue right now but 
forcing older yarn engine in packages.json resolved my issue

` "engines": {
   "yarn": "0.28.4"
  }`

**Comment by King-Ran** [comment]
@marekstabla  
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install --save-dev node-sass

resolved my issue

**Comment by ordinathorreur** [comment]
I had been having this issue for the last couple of days too, but I just managed to do a successful deployment with no changes on my end. Can anyone confirm that this issue has been resolved?

**Comment by PoslinskiNet** [comment]
@ordinathorreur I still have this issue (node >= 7.*)

**Comment by fighella** [comment]
Same issue. (node >= 7.*)

**Comment by PaulRBerg** [comment]
Still happening

**Comment by nschonni** [comment]
Closing since this seems related to Heroku file system permissions rather than something related/fixable in node-sass
