### ISSUE TITLE
AIX Node.js SDK - Unable to locate "aix-ppc64-48_binding.node" (V6) or "aix-ppc64-57_binding.node" (V8)

### ISSUE THREAD

**Issue by jparmet** [sass/node-sass#2090]
Hello,

First time post and new to Node, Angular, GitHub, so I thought I would try here first. Please provide guidance if this is the wrong place. If this is an issue in some part of the IBM code, I can go ask on developerWorks.  

I am attempting to install "'@'angular/cli" using the IBM Node.js SDK. I've tried two different versions of the SDK and both produce similar results, save for the version:

=====================

Version 6 SDK:

"# npm --version"
3.10.10
"# node --version"
v6.11.2

"# npm install  '@'angular/cli"

> node-sass@4.5.3 install /tmp/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/aix-ppc64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/aix-ppc64-48_binding.node": 

HTTP error 404 Not Found

=====================

Version 8 SDK:

"# npm --version"
5.0.3
"# node --version"
v8.1.4

"# npm install '@'angular/cli"

> node-sass@4.5.3 install /tmp/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/aix-ppc64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/aix-ppc64-57_binding.node": 

HTTP error 404 Not Found

=====================

I've noticed that the 'download' directory doesn't exist.  Was the tree changed?

Thanks.

**Comment by nschonni** [comment]
Neither AIX or PPC64 are supported platforms so there is no binaries.

**Comment by saper** [comment]
But if you have gcc or maybe even xlC installed it should be possible to compile it from source. Compilation follows automatically if there is no binary available.

**Comment by jparmet** [comment]
Thanks for the replies.
