### ISSUE TITLE
Install multiple bindings

### ISSUE THREAD

**Issue by greggb** [sass/node-sass#2091]
Is it possible to install bindings for multiple OSs? We're running into an issue where we might `yarn install` on a host MacOS and then run node-sass in an ubuntu VM. I searched through the issues, but didn't see a way to hint to the installer that we'd like to have bindings for multiple OSs.

**Comment by saper** [comment]
Yes, you can have multiple directories in `vendor` with all the binding files you needed.

**Comment by greggb** [comment]
Awesome. I did see that I have two directories in vendor. Did I miss the flag for getting both of them at install time on a single OS?

**Comment by saper** [comment]
There are no flags for this. If you do additional npm install and do not clean the build, you will accumulate bindings there. Just copy bindings manually around and you will have a full set. Remember to regency/rebuild them on node upgrade.

**Comment by greggb** [comment]
Great, thanks for the help

**Comment by saper** [comment]
Glad to help :)
