### ISSUE TITLE
*Critical* Segmentation Fault on Android

### ISSUE THREAD

**Issue by RSCipher001** [sass/node-sass#2094]
- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.11.3
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.11.3',
  v8: '5.1.281.107',
  uv: '1.11.0',
  zlib: '1.2.8',
  ares: '1.13.0',
  modules: '48',
  openssl: '1.0.2l' }

- Node Platform (`node -p process.platform`): android
- Node architecture (`node -p process.arch`): arm64
- node-sass version (`node -p "require('node-sass').info"`):
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:353:27)

- npm node-sass versions (`npm ls node-sass`): npm ERR! code 1

Running `npm install node-sass -g` is unable to install node-sass, it fails before downloading node binary with 404 error and again fails at compilation. I installed python2, make and clang for compilation but after compilation it says 'segmentation fault' at every run, I can't do anything, I've already tried troubleshooting and trying after clean setup, I'm stuck and you know what is worst?? node-binary takes half hour to compile and result is segmentation fault, it is annoying.

FYI: I am using an old project and it used to work file.
FYI2: I've first tried 'npm install -g node-sass' and then began with project to make sure I've latest node-sass

**Comment by RSCipher001** [comment]
Node: 6.11.3
NPM: 3.10.10

**Comment by nschonni** [comment]
Android isn't a supported platform. You can see the previous discussions if you search the issue tracker

**Comment by RSCipher001** [comment]
WTH, it used to work with Android

**Comment by xzyfer** [comment]
It was never intended to work on Android. It only worked by chance. As a
result support could break at any time.

**Comment by RSCipher001** [comment]
You're right I didn't know about that, I knew that it used to work before, BTW I'll use ruby sass compiler until I found any working solution.
