### ISSUE TITLE
Allow CLI watching *with* piping

### ISSUE THREAD

**Issue by lunelson** [sass/node-sass#2099]
This is a feature request concerning the `node-sass` CLI.

Although it's possible to pipe the result of a CLI compile command to another process, e.g. `postcss-cli`, and it's also possible to watch files with the CLI, it seems it's not possible to do both at the same time. It would be nice if this was possible without needing another process to wrap it. In the meantime however, it can be done that way e.g. [node-sass-watcher](https://github.com/kottenator/node-sass-watcher).

**Comment by xzyfer** [comment]
I'm looking at this for v5. Could you please show an example command you'd expect to use? So that I can verify its working as expected.

**Comment by lunelson** [comment]
Well I guess the underlying pattern would be this...
```sh
node-sass [options] [relative-input-path] | [other-app] [other-app-options] > [relative-output-path]
```
...and the actual use-case that I had in mind, basically this
```sh
node-sass -w input.scss | postcss -u autoprefixer > output.css
```

**Comment by xzyfer** [comment]
Do you have an example of a tool that does this. It's not clear to me how
this would work given that the watch flag make node-sass a long running
process.

**Comment by lunelson** [comment]
No, and I can see that my expectation WRT syntax here is naïve and probably not possible. If I understand it right, node-sass' CLI can't really be 'aware' of what comes after the `|` character right? But essentially what I'm asking for is for node-sass to go in to watch mode and *pipe itself* to another process every time it runs. So if it's not possible in the form above, maybe the entire args after the `|` (which could in theory might be more than one piping) needs to be passed to node-sass as an arg? Like
```sh
node-sass -w input.scss --pipe 'postcss -u autoprefixer > output.css'
```

**Comment by saper** [comment]
You can pipe a stream of bytes. But how the receiver would know that the file is over and the next one begins? Even if this would be applied to one file only, how do we tell 'the file is complete, now waiting for changes'

I can imagine something like this stream the endless tape archive, but probably there are no tools to receive such a stream and process it accordingly.

What could work is streaming just if file names, line by line.

**Comment by ruppalsingh** [comment]
`chokidar-cli` lets you do the following:

```
chokidar 'src/scss/**/*.scss' -c 'npm run build-task:scss-compile && npm run build-task:autoprefixer'
```

Effectively, it *only* watches the files for changes and runs the provided commands on change. The instruction could itself then include an instruction to process sass files, among other things (such as in my case, an autoprefixer).

**Comment by lunelson** [comment]
That's a pretty good alternative, but IIRC `node-sass` makes internal use `sass-graph` in watch mode to track the actual `@import` graph of the entry file you give it, rather than a catch-all glob (which could run the build unnecessarily)

**Comment by xzyfer** [comment]
So I've done a bunch of looking around for prior art or conventions in this
space and couldn't find anything.

I'm very hesitant to add this bespoke behaviour to node-sass. I wanted to
suggest a generic glue tool instead.

That chokidar things is interesting. The sass-spec point bus a good one.
You could however use the sass-graph bin to figure out the ancestors of the
changed file to know which to pipe into node-sass.

**Comment by xzyfer** [comment]
We could export a second binary that encapsulates the additional sass-graph
logic for these use cases
