### ISSUE TITLE
Windows 10 install failing with Node 8 on 4.5.3

### ISSUE THREAD

**Issue by Noitidart** [sass/node-sass#2101]
I read the trouble shooting guide. I successfully run and installed `npm install --global --production windows-build-tools` in admin mode. However afterwards, when I do `npm install node-sass` I get the follow error: I gisted my debug log - https://gist.github.com/Noitidart/8574e82e647f403a6f05899744d46f91

I am installing on my desktop Windows 10 computer.

* NPM version (`npm -v`): 5.4.2
* Node version (`node -v`): v8.4.0
* Node Process (`node -p process.versions`):

```
{ http_parser: '2.7.0',
  node: '8.4.0',
  v8: '6.0.286.52',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.22.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

* Node Platform (`node -p process.platform`): win32
* Node architecture (`node -p process.arch`): x64
* node-sass version (`node -p "require('node-sass').info"`): 

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)
```

- npm node-sass versions (`npm ls node-sass`): `-- (empty)`

Please help.

**Comment by Stachuu87** [comment]
I have similar problem on Linux Mint when trying to install.

That's what i get in my console:


`loadDep:uuid → cache add  ▀ ╢██████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> node-sass@4.5.3 install /home/piotr/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN enoent ENOENT: no such file or directory, open '/home/piotr/package.json'
npm WARN piotr No description
npm WARN piotr No repository field.
npm WARN piotr No README data
npm WARN piotr No license field.
npm ERR! Linux 4.8.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/piotr/test/npm-debug.log
`

Last lines fo npm-debug.log are the same as in Noitidart's log. :

`17956 error Linux 4.8.0-53-generic
17957 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass"
17958 error node v4.2.6
17959 error npm  v3.5.2
17960 error file sh
17961 error code ELIFECYCLE
17962 error errno ENOENT
17963 error syscall spawn
17964 error node-sass@4.5.3 install: `node scripts/install.js`
17964 error spawn ENOENT
17965 error Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
17965 error Make sure you have the latest version of node.js and npm installed.
17965 error If you do, this is most likely a problem with the node-sass package,
17965 error not with npm itself.
17965 error Tell the author that this fails on your system:
17965 error     node scripts/install.js
17965 error You can get information on how to open an issue for this project with:
17965 error     npm bugs node-sass
17965 error Or if that isn't available, you can get their info via:
17965 error     npm owner ls node-sass
17965 error There is likely additional logging output above.
17966 verbose exit [ 1, true ]`

**Comment by Stachuu87** [comment]
I have similar problem on Linux Mint when trying to install.

That's what i get in my console:

>  install /home/piotr/node_modules/node-sass
node scripts/install.js
sh: 1: node: not found
npm WARN enoent ENOENT: no such file or directory, open '/home/piotr/package.json'
npm WARN piotr No description
npm WARN piotr No repository field.
npm WARN piotr No README data
npm WARN piotr No license field.
npm ERR! Linux 4.8.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass"
npm ERR! node v4.2.6
npm ERR! npm v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-sass@4.5.3 install: node scripts/install.js
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! /home/piotr/test/npm-debug.log

Last lines fo npm-debug.log are the same as in Noitidart's log. :

> 17956 error Linux 4.8.0-53-generic
17957 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass"
17958 error node v4.2.6
17959 error npm  v3.5.2
17960 error file sh
17961 error code ELIFECYCLE
17962 error errno ENOENT
17963 error syscall spawn
17964 error node-sass@4.5.3 install: `node scripts/install.js`
17964 error spawn ENOENT
17965 error Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
17965 error Make sure you have the latest version of node.js and npm installed.
17965 error If you do, this is most likely a problem with the node-sass package,
17965 error not with npm itself.
17965 error Tell the author that this fails on your system:
17965 error     node scripts/install.js
17965 error You can get information on how to open an issue for this project with:
17965 error     npm bugs node-sass
17965 error Or if that isn't available, you can get their info via:
17965 error     npm owner ls node-sass
17965 error There is likely additional logging output above.
17966 verbose exit [ 1, true ]

**Comment by xzyfer** [comment]
>sh: 1: node: not found

Node is not in your path.

**Comment by GXZL** [comment]
I'm getting the following:


```
PS C:\Users\gxzladmin\amps-automation> npm install grunt-sass

> node-sass@3.13.1 install C:\Users\gxzladmin\amps-automation\node_modules\grunt-sass\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node":

HTTP error 404 Not Found`

```

Doesn't look like this exists?  https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node

**Comment by xzyfer** [comment]
Node 8 support was added in 4.5.3. update your node sass or downgrade node.

**Comment by Noitidart** [comment]
@xzyfer thank youbut to get 4.5.3 which was released 4 months ago I am doing `npm install node-sass`, is there soemthing else to do?

**Comment by GXZL** [comment]
I have node-sass at 4.5.3, but I still get the same error message when trying to install grunt-sass...

` Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node
 Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-ia32-57_binding.node":

 HTTP error 404 Not Found`

Any additional help you could provide would be greatly appreciated.

**Comment by Noitidart** [comment]
I apologize folks, I might be missing something. Are any of the comments helpful for my Windows 10 situation? I seem to find they don't apply, I might be mistaken.

**Comment by yangdan8** [comment]
我也是装不上

**Comment by nschonni** [comment]
I've deleted all the unrelated comments from this issue and updated the title.

@Noitidart can you run the `node -p process.env.comspec` command from the TROUBLESHOOTING because it looks like there are other arguments getting passed to the install script https://gist.github.com/Noitidart/8574e82e647f403a6f05899744d46f91#file-gistfile1-txt-L5007

**Comment by Noitidart** [comment]
Thanks you sir very much, @nschonni -

When I run `node -p process.env.comspec` it spits out to me:

```
C:\WINDOWS\system32\cmd.exe
```

**Comment by BringerOD** [comment]
+1  same issue.

**Comment by markadrake** [comment]
+1 same issue and same versions except:

Node `v8.6.0` and NPM `v5.3.0`. My platform and architecture are the same.

**Comment by Kaidanov** [comment]
Any solutions yet ? Can't work with ionic now..

node-sass@4.5.0 install C:\Users\2bher\WebstormProjects\ionic3-angular4_2\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.nod
e
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall C:\Users\2bher\WebstormProjects\ionic3-angular4_2\node_modules\node-sass
> node scripts/build.js

**Comment by kf-garethwilliams** [comment]
I was having a similar issue. I am using VS2017 to compile my gulp file. Mine was specifically an issue with VS but was giving a similar error in the output log.

I resolved this by going to Tools > Options > Projects and Solutions > Web Package Management 
and making sure the $(Path) is above the $(VSINDSTALLDIR)\Web\External

**Comment by nschonni** [comment]
@Kaidanov 4.50 doesn't support Node 8, only 4.5.3. I'm deleting your comment. Ionic is also unsupported

**Comment by xzyfer** [comment]
>I have node-sass at 4.5.3, but I still get the same error message when trying to install grunt-sass...
>
>` Downloading binary from v3.13.1 win32-ia32-57_binding.node (download)
>Cannot download "v3.13.1 win32-ia32-57_binding.node (download)":

The path `v3.13.1 win32-ia32-57_binding.node` shows that you are installing node-sass@v3.13.1 not 4.5.3. Run `npm ls node-sass` to see that modules are depending on older versions of node-sass and update them accordingly

**Comment by Noitidart** [comment]
@xzyfer thank you for that reply, but I don't think your response (and close) applies to the OP post. Am I correct sir?

**Comment by xzyfer** [comment]
@Noitidart true. I've removed the irrelevant comments, and reopened the issue.

**Comment by Noitidart** [comment]
Thanks sir, excuse the confusion please.

**Comment by xzyfer** [comment]
Relevant section of the log.
```
3354 silly install node-sass@4.5.3
3355 info lifecycle node-sass@4.5.3~install: node-sass@4.5.3
3356 verbose lifecycle node-sass@4.5.3~install: unsafe-perm in lifecycle true
3357 verbose lifecycle node-sass@4.5.3~install: PATH: C:\Users\Mercurius\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Mercurius\Documents\GitHub\Chrome-Store-Foxified\node_modules\node-sass\node_modules\.bin;C:\Users\Mercurius\Documents\GitHub\Chrome-Store-Foxified\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Users\Mercurius\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\LLVM\bin;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\Mercurius\AppData\Local\Android\sdk\platform-tools;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\Mercurius\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Users\Mercurius\AppData\Local\atom\bin;C:\Users\Mercurius\AppData\Local\Microsoft\WindowsApps;C:\Users\Mercurius\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd;C:\perl\bin\;C:\Users\Mercurius\AppData\Local\Yarn\.bin;C:\Users\Mercurius\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\bin;C:\Users\Mercurius\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Mercurius\AppData\Roaming\npm
3358 verbose lifecycle node-sass@4.5.3~install: CWD: C:\Users\Mercurius\Documents\GitHub\Chrome-Store-Foxified\node_modules\node-sass
3359 silly lifecycle node-sass@4.5.3~install: Args: [ '/d /s /c', 'node scripts/install.js' ]
3360 silly lifecycle node-sass@4.5.3~install: Returned: code: 1  signal: null
3361 info lifecycle node-sass@4.5.3~install: Failed to exec install script
3362 verbose unlock done using C:\Users\Mercurius\AppData\Roaming\npm-cache\_locks\staging-c0e7f46aa6e01775.lock for C:\Users\Mercurius\Documents\GitHub\Chrome-Store-Foxified\node_modules\.staging
3363 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
3364 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
3365 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3365 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
3365 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
3365 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3366 verbose stack Error: node-sass@4.5.3 install: `node scripts/install.js`
3366 verbose stack Exit status 1
3366 verbose stack     at EventEmitter.<anonymous> (C:\Users\Mercurius\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
3366 verbose stack     at emitTwo (events.js:125:13)
3366 verbose stack     at EventEmitter.emit (events.js:213:7)
3366 verbose stack     at ChildProcess.<anonymous> (C:\Users\Mercurius\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
3366 verbose stack     at emitTwo (events.js:125:13)
3366 verbose stack     at ChildProcess.emit (events.js:213:7)
3366 verbose stack     at maybeClose (internal/child_process.js:927:16)
3366 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3367 verbose pkgid node-sass@4.5.3
3368 verbose cwd C:\Users\Mercurius\Documents\GitHub\Chrome-Store-Foxified
3369 verbose Windows_NT 10.0.15063
3370 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mercurius\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-sass"
3371 verbose node v8.4.0
3372 verbose npm  v5.4.2
3373 error code ELIFECYCLE
3374 error errno 1
3375 error node-sass@4.5.3 install: `node scripts/install.js`
3375 error Exit status 1
3376 error Failed at the node-sass@4.5.3 install script.
3376 error This is probably not a problem with npm. There is likely additional logging output above.
3377 verbose exit [ 1, true ]
```

**Comment by xzyfer** [comment]
@Noitidart are you able to dump your npm config. Please make sure to remove any sensitive information.

>npm config ls
and 
>npm config ls -l

**Comment by Noitidart** [comment]
Thanks very very much for the attention sir I have been stumped on this for a long time. Excuse my delay in response.

Doing `npm config ls` gives me:

```
PS C:\Users\Mercurius\Desktop\trustedplatform_android> npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.4.2 node/v8.4.0 win32 x64"

; userconfig C:\Users\Mercurius\.npmrc
init.author.email = "noitidart@gmail.com"
init.author.name = "Noitidart"

; globalconfig C:\Users\Mercurius\AppData\Roaming\npm\etc\npmrc
msvs_version = "2015"
python = "C:\\Users\\Mercurius\\.windows-build-tools\\python27\\python.exe"

; builtin config undefined
prefix = "C:\\Users\\Mercurius\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\Mercurius\Desktop\trustedplatform_android
; HOME = C:\Users\Mercurius
; "npm config ls -l" to show all defaults.
```

and doing `npg config ls -l` gives me:

```
PS C:\Users\Mercurius\Desktop\trustedplatform_android>  npm config ls -l
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.4.2 node/v8.4.0 win32 x64"

; userconfig C:\Users\Mercurius\.npmrc
init.author.email = "noitidart@gmail.com"
init.author.name = "Noitidart"

; globalconfig C:\Users\Mercurius\AppData\Roaming\npm\etc\npmrc
msvs_version = "2015"
python = "C:\\Users\\Mercurius\\.windows-build-tools\\python27\\python.exe"

; builtin config undefined
prefix = "C:\\Users\\Mercurius\\AppData\\Roaming\\npm"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
auth-type = "legacy"
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\Mercurius\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\Mercurius\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\Mercurius\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\Mercurius\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-version = "8.4.0"
offline = false
onload-script = null
only = null
optional = true
package-lock = true
parseable = false
prefer-offline = false
prefer-online = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
progress = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "C:\\Users\\MERCUR~1\\AppData\\Local\\Temp"
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\Mercurius\\.npmrc"
version = false
versions = false
viewer = "browser"
```

**Comment by xzyfer** [comment]
Does it work without the `--global` flag? The error looks like a permission issue which typically happens with global installs.

**Comment by Noitidart** [comment]
Oh I can I successfully run  `npm install --global --production windows-build-tools`. I did this without problem. However afterwards, when I do `npm install node-sass` I get the error. I edited the OP clarifying that.

**Comment by xzyfer** [comment]
This sounds a lot like a permission issue that's out of our hands. Try installing node-sass in a temp directory where you have permissions.

```
> mkdir \temp1
> cd \temp1
> npm cache clean
> npm install -ddd node-sass > npm.log 2> npm.err
> npm ls node-sass
```

**Comment by Noitidart** [comment]
Oh wow! I think that worked!

```
PS C:\Users\Mercurius\Documents\GitHub> cd temp1
cd : Cannot find path 'C:\Users\Mercurius\Documents\GitHub\temp1' because it does not exist.
At line:1 char:1
+ cd temp1
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Mercur...ts\GitHub\temp1:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\Mercurius\Documents\GitHub> cd \temp1
PS C:\temp1> ls
PS C:\temp1> npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything
is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mercurius\AppData\Roaming\npm-cache\_logs\2017-10-06T15_03_30_069Z-debug.log
PS C:\temp1> npm install -ddd node-sass > npm.log 2> npm.err
PS C:\temp1> npm ls node-sass
C:\temp1
`-- node-sass@4.5.3
```

I have no idea why permissions are blocking me from installing into the other directory. Thank you sir very much I will keep exploring and share with you all how I fix the permissions.
