### ISSUE TITLE
can't work in linux and node 8?

### ISSUE THREAD

**Issue by zzzgit** [sass/node-sass#2102]
![image](https://user-images.githubusercontent.com/1060733/30780487-7ea585d8-a13e-11e7-8f81-a122c75d8ad9.png)

![image](https://user-images.githubusercontent.com/1060733/30780489-8c210c46-a13e-11e7-819d-6fada7b30f7f.png)
![image](https://user-images.githubusercontent.com/1060733/30780490-8c232af8-a13e-11e7-981b-d7d42dc83625.png)

I remember that there was an compatibility table which showed me that `node-sass` is not supported on `linux` `node 8`.
But now the table is removed,and then I install `node 8` on` linux`,and then `node-sass` don't work any more.
Why don't you guys tell us the truth in the `README` file?

**Comment by xzyfer** [comment]
```
npm rebuild node-sass
```
