### ISSUE TITLE
High Sierra10.13: ERROR in Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

### ISSUE THREAD

**Issue by varjay** [sass/node-sass#2105]
High Sierra10.13: ERROR in Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

- NPM version (5.3.0):
- Node version (v8.4.0):
- Node Process ({ http_parser: '2.7.0',
  node: '8.4.0',
  v8: '6.0.286.52',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.22.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }):
- Node Platform (none):
- Node architecture (x64):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (node-sass@3.11.1):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by xzyfer** [comment]
node-sass@3.11.1 is very very old. You need node-sass@4.5.3 for Node 8.

**Comment by dylanh724** [comment]
If that's the case, that should be the error message -- the current one is very unclear.
