### ISSUE TITLE
node-sass v3.7.0 installation fails after installing node 8

### ISSUE THREAD

**Issue by Mikikkk** [sass/node-sass#2106]
Hi,

I'm working with node-sass v3.7.0 and today I installed node v8.1.0 after working with node v6.9.0 for a very long time, and for some reason now the installation of node-sass fails and I get the error:

> Cannot download "http://localhost/node-sass/v3.7.0/win32-x64-57_binding.node

I download the binaries manually from [](https://github.com/sass/node-sass/releases/tag/v3.7.0) (and hosting it on iis) and the file doesn't exists there.
Which is wired because I uninstalled node v8.1.0 and installed v6.9.0 and the installation worked.

I've looked at many issues but none of them helped me.

- NPM version (`npm -v`): 5.0.3
- Node version (`node -v`): 8.1.0
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0',
node: '8.1.0',
v8: '5.8.283.41',
uv: '1.12.0',
zlib: '1.2.11',
ares: '1.10.1-DEV',
modules: '57',
openssl: '1.0.21',
icu: '59.1',
unicode: '9.0',
cldr: '31.0.1',
 tz: '2017b' }`
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): `throw error`
- npm node-sass versions (`npm ls node-sass`): `-- (empty)`

**Comment by saper** [comment]
node-sass 3.7.0 is too old for node 8. Either switch back to node 6 or upgrade your node-sass to the newest version.
