### ISSUE TITLE
npm rebuild node-sass error

### ISSUE THREAD

**Issue by iamcharles777** [sass/node-sass#2107]
`gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/var/www/vhosts/xxx.com/dan-phillips-web/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.0.beta.2"' -I/root/.node-gyp/6.11.3/include/node -I/root/.node-gyp/6.11.3/src -I/root/.node-gyp/6.11.3/deps/uv/include -I/root/.node-gyp/6.11.3/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:2:
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Vectorized<T>::hash()’:
../src/libsass/src/ast.hpp:328: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:331: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:331: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:331: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:331: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:331: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:331: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
../src/libsass/src/ast.hpp:362: error: ‘class Sass::ExpressionMap’ has no member named ‘reserve’
../src/libsass/src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
../src/libsass/src/ast.hpp:391: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:395: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’ to ‘bool’
../src/libsass/src/ast.hpp:396: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:396: error: expected ‘)’ before ‘return’
In file included from ../src/libsass/src/ast.cpp:2:
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
../src/libsass/src/ast.hpp:1133: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1137: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1137: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1137: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1137: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1137: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1137: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
../src/libsass/src/ast.hpp:1472: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1474: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1474: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1474: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1474: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1474: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1474: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Number::hash()’:
../src/libsass/src/ast.hpp:1627: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1629: error: expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1629: error: expected ‘;’ before ‘for’
../src/libsass/src/ast.hpp:1629: error: expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1629: error: expected ‘)’ before ‘for’
../src/libsass/src/ast.hpp:1629: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1631: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1631: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1631: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1631: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1631: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1631: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘bool Sass::String_Schema::has_interpolants()’:
../src/libsass/src/ast.hpp:1802: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1805: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:1805: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.hpp:1805: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:1805: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
../src/libsass/src/ast.hpp:1812: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1814: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1814: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1814: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1814: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1814: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1814: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Compound_Selector::hash()’:
../src/libsass/src/ast.hpp:2752: error: ‘template<class T> class Sass::Vectorized’ used without template parameters
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Selector_List::hash()’:
../src/libsass/src/ast.hpp:2997: error: ‘template<class T> class Sass::Vectorized’ used without template parameters
../src/libsass/src/ast.hpp: In member function ‘virtual void Sass::Selector_List::set_media_block(Sass::Media_Block*)’:
../src/libsass/src/ast.hpp:3014: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:3017: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:3017: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:3017: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:3017: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:3017: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:3017: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual bool Sass::Selector_List::has_placeholder()’:
../src/libsass/src/ast.hpp:3019: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:3022: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:3022: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.hpp:3022: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:3022: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘virtual void Sass::Arguments::set_delayed(bool)’:
../src/libsass/src/ast.cpp:59: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:63: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.cpp:63: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.cpp:63: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.cpp:63: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::has_parent_ref() const’:
../src/libsass/src/ast.cpp:132: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:135: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:135: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:135: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:135: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::has_real_parent_ref() const’:
../src/libsass/src/ast.cpp:140: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:143: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:143: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:143: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:143: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List_Obj, std::string)’:
../src/libsass/src/ast.cpp:777: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:780: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:780: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:780: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:780: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘Sass::Selector_List* Sass::Complex_Selector::resolve_parent_refs(Sass::Context&, std::vector<Sass::SharedImpl<Sass::Selector_List>, std::allocator<Sass::SharedImpl<Sass::Selector_List> > >&, bool)’:
../src/libsass/src/ast.cpp:1344: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:2459: error: expected primary-expression at end of input
../src/libsass/src/ast.cpp:2459: error: expected ‘;’ at end of input
../src/libsass/src/ast.cpp:2459: error: expected primary-expression at end of input
../src/libsass/src/ast.cpp:2459: error: expected ‘)’ at end of input
../src/libsass/src/ast.cpp:2459: error: expected statement at end of input
../src/libsass/src/ast.cpp:2459: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp:2459: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp: At global scope:
../src/libsass/src/ast.cpp:2459: error: expected ‘}’ at end of input
../src/libsass/src/units.hpp:10: warning: ‘Sass::PI’ defined but not used
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1

make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
make: Leaving directory `/var/www/vhosts/xxx.com/dan-phillips-web/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/vhosts/xxx.com/dan-phillips-web/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 2.6.32-042stab112.15
gyp ERR! command "/usr/bin/node" "/var/www/vhosts/xxx.com/dan-phillips-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/vhosts/xxx.com/dan-phillips-web/node_modules/node-sass
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
`
Please help

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
