### ISSUE TITLE
Can't install node-sass on Windows

### ISSUE THREAD

**Issue by emzero** [sass/node-sass#2117]
Followed [this troubleshooting steps](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#windows)

Here are the logs:
https://gist.github.com/emzero/57802b5e1d293fbc1514e9a413cfe2c5

- NPM version (`npm -v`):
`5.3.0`
- Node version (`node -v`):
`8.6.0`
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.7.0',
  node: '8.6.0',
  v8: '6.0.287.53',
  uv: '1.14.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```
- Node Platform (`node -p process.platform`):
`win32`
- Node architecture (`node -p process.arch`):
`x64`
- node-sass version (`node -p "require('node-sass').info"`):
`Error: Cannot find module 'node-sass'`

- npm node-sass versions (`npm ls node-sass`):
`-- (empty)`

**Comment by nschonni** [comment]
You're trying to install 3.13.1 with Node 8, there are many issues that explain this isn't supported

**Comment by emzero** [comment]
![image](https://user-images.githubusercontent.com/412489/31825805-b60e0a2c-b589-11e7-9f7b-087dda1576a0.png)

So which versions are actually supported...?
