### ISSUE TITLE
Getting error while installing angular-cli

### ISSUE THREAD

**Issue by sasirekaK** [sass/node-sass#2124]
I am getting the following issue while trying to install @angular/cli in my Windows 10 system:
 
22892 info lifecycle uglify-js@2.8.29~postinstall: uglify-js@2.8.29
22893 silly postinstall uglifyjs-webpack-plugin@0.4.6
22894 info lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: uglifyjs-webpack-plugin@0.4.6
22895 verbose lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: unsafe-perm in lifecycle true
22896 verbose lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: PATH: C:\Users\Mohankumar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Mohankumar\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\uglifyjs-webpack-plugin\node_modules\.bin;C:\Users\Mohankumar\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.bin;C:\Users\Mohankumar\AppData\Roaming\npm\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Broadcom\Broadcom 802.11;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Mohankumar\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
22897 verbose lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: CWD: C:\Users\Mohankumar\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\uglifyjs-webpack-plugin
22898 silly lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Args: [ '/d /s /c', 'node lib/post_install.js' ]
22899 info lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Failed to exec postinstall script
22900 silly lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Returned: code: -4058  signal: null
22901 info lifecycle uglifyjs-webpack-plugin@0.4.6~postinstall: Failed to exec postinstall script
22902 verbose unlock done using C:\Users\Mohankumar\AppData\Roaming\npm-cache\_locks\staging-3b85464ed07ccdb8.lock for C:\Users\Mohankumar\AppData\Roaming\npm\node_modules\.staging
22903 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\@angular\cli\node_modules\fsevents):
22904 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
22905 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
22905 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
22905 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
22905 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
22906 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\@angular\cli\node_modules\node-sass):
22907 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 install: `node scripts/install.js`
22907 warn optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd ENOENT
22908 verbose optional SKIPPING OPTIONAL DEPENDENCY:
22908 verbose optional Failed at the node-sass@4.5.3 install script.
22908 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
22909 verbose stack Error: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
22909 verbose stack spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd ENOENT
22909 verbose stack     at exports._errnoException (util.js:1018:11)
22909 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
22909 verbose stack     at onErrorNT (internal/child_process.js:367:16)
22909 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
22909 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
22910 verbose pkgid uglifyjs-webpack-plugin@0.4.6
22911 verbose cwd C:\WINDOWS\system32
22912 verbose Windows_NT 10.0.10240
22913 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mohankumar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
22914 verbose node v6.11.1
22915 verbose npm  v5.3.0
22916 error file C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd
22917 error path C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd
22918 error code ELIFECYCLE
22919 error errno ENOENT
22920 error syscall spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd
22921 error uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
22921 error spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files\Git\cmd ENOENT
22922 error Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
22922 error This is probably not a problem with npm. There is likely additional logging output above.
22923 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
