### ISSUE TITLE
unable to install node-sass or gulp-sass on windows 10

### ISSUE THREAD

**Issue by savgiannis** [sass/node-sass#2125]
**NPM version** :  5.3.0

**Node version**:  v8.8.1

**Node Process**:  
{ http_parser: '2.7.0',
  node: '8.8.1',
  v8: '6.1.534.42',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

**Node Platform**: win32

**Node architecture**:x64

 **node-sass version**: I typed the command but nothing happens

**npm node-sass versions**: I typed npm -g ls node-sass and I get 
C:\Users\Giannis\AppData\Roaming\npm

**And when i type npm install -g node-sass I get**:

C:\Users\Giannis\AppData\Roaming\npm\node-sass -> C:\Users\Giannis\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass

> node-sass@4.5.3 install C:\Users\Giannis\AppData\Roaming\npm\node_modules\node-sass
> node scripts/install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Giannis\AppData\Roaming\npm-cache\_logs\2017-10-26T18_38_13_172Z-debug.log

I have also tried to install it with different versions of node and npm and happens the same.

Thanks

**Comment by saper** [comment]
Looks like Node is motion your PATH, is this on purpose?
