### ISSUE TITLE
Module build failed: color: #4a4ae5d1;

### ISSUE THREAD

**Issue by wzup** [sass/node-sass#2126]
When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): v3.10.10
- Node version (`node -v`): v6.11.5
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '6.11.5',
  v8: '5.1.281.108',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2l' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): 
```
app@1.0.0 C:\Users\user\app
`-- node-sass@4.5.3
```

When encountering a syntax, or compilation issue: 

**I DON"T KNOW WHAT KIND OF ISSUE THIS IS BY YOUR STANDARDS!** 
Inform me plz and I'll open an issue there if it is so.
I've already open one here, though. FYI. https://github.com/webpack-contrib/sass-loader/issues/503

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

## Finally Actual Issue

What's wrong with this CSS rule?
It works just fine in a browser but throws in Webpack `sass-loader`:

```
&:after {
    content: "\f08e";
    font-family: FontAwesome;
    position: absolute;
    font-size: 9px;
    margin-left: 3px;
    color: #4a4ae5d1;  // <== What's wrong with it? `node-sass` throws
}
```

Error:

```
ERROR in ./src/sass/Index.local.scss
    Module build failed: ModuleBuildError: Module build failed:
                                        color: #4a4ae5d1;
                                              ^
          Invalid CSS after "...         color:": expected expression (e.g. 1px, bold), was "#4a4ae5d1;"
          in C:\Users\user\app\src\sass\Index.local.scss (line 651, column 44)
        at runLoaders (C:\Users\user\app\node_modules\webpack\lib\NormalModule.js:195:19)
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:364:11
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:230:18
        at context.callback (C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (C:\Users\user\app\node_modules\sass-loader\lib\loader.js:55:13)
        at Object.<anonymous> (C:\Users\user\app\node_modules\async\dist\async.js:2244:31)
        at Object.callback (C:\Users\user\app\node_modules\async\dist\async.js:906:16)
        at options.error (C:\Users\user\app\node_modules\node-sass\lib\index.js:294:32)
     @ ./src/js/DashboardTest.js 19:10-37
     @ ./src/js/routes.js
     @ ./src/js/browser.js
```

**Comment by xzyfer** [comment]
Node sass doesn't currently support 8 digit hex colours. This is coming
soon.

**Comment by reddysridhar53** [comment]
Which release has this been added...?
