### ISSUE TITLE
File to import not found or unreadable (node-sass . -o .)

### ISSUE THREAD

**Issue by dehghani-mehdi** [sass/node-sass#2131]
- NPM version (`npm -v`): `3.10.10`
- Node version (`node -v`): `6.11.0`
- Node Process (`node -p process.versions`):

```
{ http_parser: '2.7.0',
  node: '6.11.0',
  v8: '5.1.281.102',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
```

- Node Platform (`node -p process.platform`): `win32`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):

```
node-sass       4.5.0   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

- npm node-sass versions (`npm ls node-sass`): `-- node-sass@4.5.0`

Consider following structure:

```
--assets
------scss
----------my-sass-file.scss
--_config.scss
```

`my-sass-file.scss` contains:

```
@import "../../_config.scss";
body { color: red; }
```

When I using `node-sass . -o .`, I got `File to import not found or unreadable ...` error. but with following:

```
--assets
------scss
----------my-sass-file.scss
----------_config.scss
```
And 
```
@import "_config.scss";
body { color: red; }
```
Everything works as expected. did I miss something or it's a bug?

Thanks.

**Comment by nschonni** [comment]
What happens if you remove the fix your import to just `config`. The underscore has special meaning in Sass, and the file extension shouldn't be included.

**Comment by dehghani-mehdi** [comment]
@nschonni  I tested that before I report the issue here, no success without `_` or/and `.scss`

**Comment by nschonni** [comment]
Can you provide a simple repository with that we can use toe reproduce the error

**Comment by dehghani-mehdi** [comment]
@nschonni  Seems like I had a mistake about path of `_config.scss` file (_I have no idea!_) (folder structure of my real project is not as simple as my example here), I tired to provide some testcase same as my example, here but even with `_` and/or `.scss` everything works as expected.

Thanks for your time.
