### ISSUE TITLE
missing release notes for 4.6.0

### ISSUE THREAD

**Issue by also** [sass/node-sass#2135]
https://github.com/sass/node-sass/releases/tag/v4.6.0 currently reads

> $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)

![screen shot 2017-11-03 at 1 53 03 pm](https://user-images.githubusercontent.com/15624/32388570-8560d2a4-c09e-11e7-85b9-49f6ebcf411e.png)

**Comment by nschonni** [comment]
Thanks, I've added some high level notes and our platform support table.
