### ISSUE TITLE
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)

### ISSUE THREAD

**Issue by WebTerminator** [sass/node-sass#2142]
I have the following package.json file:

```
{
  "name": "react-chart",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server"
  },
  "author": "Alessandro Santese",
  "license": "ISC",
  "dependencies": {
    "html-webpack-plugin": "^2.30.1",
    "node-sass": "^4.6.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-easy-chart": "^0.3.0",
    "recharts": "^1.0.0-beta.0",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.4"
  },
  "devDependencies": {
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0"
  }
}

```

when I run "npm run start" I get:

<img width="1018" alt="screen shot 2017-11-06 at 13 13 34" src="https://user-images.githubusercontent.com/4947347/32442738-5881650c-c2f4-11e7-839f-d84e0783bc8c.png">

**Comment by WebTerminator** [comment]
Had to do the following:

sudo npm cache clean -f
sudo npm install -g n
sudo n 6.0.0

**Comment by Wolf00Bomber** [comment]
The above fix was not able to solve my case:

```
>npm install -g n
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@2.1.8: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```
So after going through the Web, found [another site](https://stackoverflow.com/questions/47198243/ionic-serve-error-node-sass-does-not-yet-support-your-current-environment-windo) where i was suggested to downgrade the Node version from 9.2.0 to the Stable version 8.9.1.

And remove the Node Packages and install npm again inside the folder.

Which worked for me.

**Comment by marcvangend** [comment]
Downgrading Node may not be necessary. I had the same error (albeit on Linux: "Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (59)") running node-sass 4.5.3, installed as dependency of gulp-sass. A regular `npm update` will only check the top-level packages, but after running `npm --depth 9999 update`, node-sass was updated to 4.7.2 and the problem was solved.
