### ISSUE TITLE
npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js

### ISSUE THREAD

**Issue by bnjmnmyers** [sass/node-sass#2143]
- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.11.5
- Node Process (`node -p process.versions`): 
  http_parser: '2.7.0',
  node: '6.11.5',
  v8: '5.1.281.108',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2l'
- Node Platform (`node -p process.platform`): Win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): not installed
- npm node-sass versions (`npm ls node-sass`): npm ERR! code 1

When I run npm install node-sass I get the following error:
137219 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
137219 verbose stack Exit status 1
137219 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
137219 verbose stack     at emitTwo (events.js:106:13)
137219 verbose stack     at EventEmitter.emit (events.js:191:7)
137219 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
137219 verbose stack     at emitTwo (events.js:106:13)
137219 verbose stack     at ChildProcess.emit (events.js:191:7)
137219 verbose stack     at maybeClose (internal/child_process.js:920:16)
137219 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
137220 verbose pkgid node-sass@3.4.2
137221 verbose cwd C:\Users\myersb.PILOTCORP\Source\Repos\PFJ Website\source\PilotFlyingJCorporate.Web\frontend
137222 error Windows_NT 10.0.10586
137223 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
137224 error node v6.11.5
137225 error npm  v3.10.10
137226 error code ELIFECYCLE
137227 error node-sass@3.4.2 postinstall: `node scripts/build.js`
137227 error Exit status 1
137228 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
137228 error Make sure you have the latest version of node.js and npm installed.
137228 error If you do, this is most likely a problem with the node-sass package,
137228 error not with npm itself.
137228 error Tell the author that this fails on your system:
137228 error     node scripts/build.js
137228 error You can get information on how to open an issue for this project with:
137228 error     npm bugs node-sass
137228 error Or if that isn't available, you can get their info via:
137228 error     npm owner ls node-sass
137228 error There is likely additional logging output above.
137229 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
That version of node-sass doesn't support Node 6. Either downgrade your Node version, or update node-sass
