### ISSUE TITLE
Unable to install using custom SASS_BINARY_PATH

### ISSUE THREAD

**Issue by chandas** [sass/node-sass#2146]
Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):5.3.0
- Node version (`node -v`):v8.4.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '8.4.0',
  v8: '6.0.286.52',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.22.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`): 
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)

- npm node-sass versions (`npm ls node-sass`):
csh-ui@0.0.0 C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI
`-- @angular/cli@1.5.0
  `-- UNMET OPTIONAL DEPENDENCY node-sass@4.6.0

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

So while trying to do an node-sass install, getting the following error as shown below, i am not sure from where it's trying to access 4.6.0 when the binary path is set in .npmrc as 'sass_binary_path=C:\Users\vu313e\AppData\Roaming\npm-cache\node-sass\4.5.3\' and i had placed the win32-x64-57_binding.node under the 4.5.3 folder
-------------------------------------------------------------------------------
$ npm install node-sass

> node-sass@4.6.0 install C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass
> node scripts/install.js

node-sass build Binary found at C:\Users\vu313e\AppData\Roaming\npm-cache\node-sass\4.5.3\

> node-sass@4.6.0 postinstall C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\vu313e\AppData\Roaming\npm-cache\node-sass\4.5.3\
Testing binary
Binary has a problem: { Error: Cannot find module 'C:\Users\vu313e\AppData\Roaming\npm-cache\node-sass\4.5.3\'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12) code: 'MODULE_NOT_FOUND' }
Building the binary locally
Building: C:\Program Files\nodejs\node.exe C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.0\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.4.0
gyp verb command install [ '8.4.0' ]
gyp verb install input version string "8.4.0"
gyp verb install installing version: 8.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.4.0
gyp verb ensuring nodedir is created C:\Users\vu313e\.node-gyp\8.4.0
gyp verb created nodedir C:\Users\vu313e\.node-gyp\8.4.0
gyp http GET https://nodejs.org/download/release/v8.4.0/node-v8.4.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.4.0' ]
gyp verb remove using node-gyp dir: C:\Users\vu313e\.node-gyp
gyp verb remove removing target version: 8.4.0
gyp verb remove removing development files for version: 8.4.0
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-gyp\lib\install.js:193:21)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestError (C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\request\request.js:884:8)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:401:9)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at TLSSocket.emit (events.js:210:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, lstat 'C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass\node_modules'
npm WARN  { Error: EPERM: operation not permitted, lstat 'C:\Users\vu313e\Documents\CSHS_Bing\CSHS\SourceCode\CSH-UI\node_modules\node-sass\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, lstat \'C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\node-sass\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'lstat',
npm WARN   path: 'C:\\Users\\vu313e\\Documents\\CSHS_Bing\\CSHS\\SourceCode\\CSH-UI\\node_modules\\node-sass\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.6.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.6.0 postinstall script.

**Comment by saper** [comment]
Please check your network connectivity and read out TROUBLESHOOTING.md information to set a proxy if required.
