### ISSUE TITLE
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js

### ISSUE THREAD

**Issue by boochamoocha** [sass/node-sass#2148]
- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): 9.1.0
- Node Process (`node -p process.versions`):

{ http_parser: '2.7.0',
  node: '9.1.0',
  v8: '6.2.414.32-node.8',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

node-sass       4.6.0   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`): └── node-sass@4.6.0 

macOS 10.13 (17A405)
Darwin 17.0.0

Use node-sass with webpack. 
Recently upgraded to MacOS High Sierra and started using node via nvm. 

Now i got message:
`
ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader/lib/loader.js?sourceMap!./src/components/schema/SchemaControls.css
Module build failed: Error: Missing binding /Users/user/Work/project/frontend/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x
`

Trying all troubleshooting actions, trying to change node version to 6.1.4.

**Comment by saper** [comment]
This is what the message says: you have changed node engine from 6 to 8 without recompiling node-sass binary. `npm rebuild node-sass` every time you switch. Or collect multiple binaries in the `vendor` directory.

**Comment by boochamoocha** [comment]
`npm rebuild node-sass ` not working for me. I mentioned above i tried all troubleshooting actions

**Comment by boochamoocha** [comment]
Collect all binaries in vendor and it helps me

**Comment by CallMeXYZ** [comment]
@boochamoocha could you explain your solution detaily?

**Comment by v3nt** [comment]
@boochamoocha hello - how did you do that?

**Comment by AlexSegen** [comment]
> Collect all binaries in vendor and it helps me

Thank you, for NOT tell us how you solved your problem.
