### ISSUE TITLE
--watch not working on 4.6.x

### ISSUE THREAD

**Issue by webjay** [sass/node-sass#2155]
It works with `"node-sass": "4.5.x"`.

- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): 8.9.1
- Node Process (`node -p process.versions`): 

```
    { 
      http_parser: '2.7.0',
      node: '8.9.1',
      v8: '6.1.534.47',
      uv: '1.15.0',
      zlib: '1.2.11',
      ares: '1.10.1-DEV',
      modules: '57',
      nghttp2: '1.25.0',
      openssl: '1.0.2m',
      icu: '59.1',
      unicode: '9.0',
      cldr: '31.0.1',
      tz: '2017b' 
    }
```

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

    node-sass 4.5.3 (Wrapper) [JavaScript]
    libsass   3.5.0.beta.2  (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):

**Comment by xzyfer** [comment]
Please search before opening new issues.

**Comment by webjay** [comment]
Sorry about that; I did search, but couldn't find a similar issue.
Which issue can I track?

**Comment by xzyfer** [comment]
The original tracking issue is #2139. The problems should be resolve din 4.7.1
