### ISSUE TITLE
sass syntax `:root` is error?

### ISSUE THREAD

**Issue by oti** [sass/node-sass#2156]
`:root` is error?

[style.sass]
```sass
:root
  font-size: 16px
```

`$ node-sass style.sass style.css -w`

```
=> changed: /Users/oti/test/style.sass
{
  "status": 1,
  "file": "/Users/oti/test/style.sass",
  "line": 1,
  "column": 1,
  "message": "Invalid CSS after \"r\": expected 1 selector or at-rule, was \"root: {\"",
  "formatted": "Error: Invalid CSS after \"r\": expected 1 selector or at-rule, was \"root: {\"\n        on line 1 of style.sass\n>> root: {\n   ^\n"
}
```
It seems to me that the colon is not interpreted correctly.

Use sassmeister.com, does not error.🤔

### NPM version (`npm -v`):
5.5.1
### Node version (`node -v`):
v8.8.1
### Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '8.8.1',
  v8: '6.1.534.42',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```
### Node Platform (`node -p process.platform`):
darwin
### Node architecture (`node -p process.arch`):
x64
### node-sass version (`node -p "require('node-sass').info"`):
```
node-sass 4.7.1 (Wrapper) [JavaScript]
libsass 3.5.0.beta.2 (Sass Compiler) [C/C++]
```
### npm node-sass versions (`npm ls node-sass`):
```
(git)-[oti/test]
test@1.0.0 /Users/oti/test/
└── node-sass@4.7.1
```

**Comment by nschonni** [comment]
As mentioned in the issue template, compilation issues should be reported upstream. Please link back here if you create an issue there

**Comment by nschonni** [comment]
Closing since the correct error message should be shown in 4.8.3 now

**Comment by oti** [comment]
I tried it. Is this `correct` ?
![Uploading スクリーンショット 2018-03-29 15.20.49.png…]()
