### ISSUE TITLE
node-sass@3.41 404 darwin-x64-48_binding.node

### ISSUE THREAD

**Issue by reggi** [sass/node-sass#2160]
For `node-sass@3.41`

The binary is leading to a 404 page:

https://github.com/sass/node-sass/releases/download/v3.4.1/darwin-x64-48_binding.node

**Comment by xzyfer** [comment]
That means v3.4.1 doesn't support your version of node. Update to a newer node-sass or downgrade your version of node.

v3.4.1 is very old and predates that version of node.
