### ISSUE TITLE
Missing binding /myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node while build 

### ISSUE THREAD

**Issue by Thavaprakash** [sass/node-sass#2162]
Hi ,

I'm getting following error while build my project. Actually error says "Missing binding /myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node", but i have "/myproject/node_modules/node-sass/vendor/linux-x64-48/binding.node". I don't know Why it is not refering "linux-x64-48"?

Error says Run `npm rebuild node-sass --force`, i did so but no luck. Please help me git rid of this issue.

node version: v8.9.1
npm version: 5.5.1
node-sass version:  4.5.3

Error:
====
```ERROR in ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-6ef6ca5e","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0&bustCache!./src/components/UserProfile.vue
Module build failed: Error: Missing binding /myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/myproject/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/myproject/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/myproject/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-6ef6ca5e","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0&bustCache!./src/components/MyProfile.vue 4:14-346 13:3-17:5 14:22-354
 @ ./src/components/UserProfile.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/assets/scss/main.scss
Module build failed: Error: Missing binding /myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x```

**Comment by xzyfer** [comment]
Looks like you upgraded node to version 8 but didn't delete your
node_modules folder.

**Comment by Thavaprakash** [comment]
Hi @xzyfer,

I have deleted node_modules, then i run `npm install`(node modules got reinstalled successfully). However I'm getting same error while run `npm run build`.

**Comment by Thavaprakash** [comment]
`npm rebuild node-sass` worked well for me. Thanks @xzyfer. You can close this issue.

**Comment by goufang** [comment]
Uncaught Error: Module build failed: ModuleBuildError: Module build failed: Error: Missing binding /project/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 7.x


Having same issue as described above for macOS 10.12.6. 
nodejs 9.0
npm 5.8.0
nvm 7.0

tried:
npm uninstall node-sass
npm install node-sass
nvm version 7.0
nvm version 8.0
npm rebuild node-sass

Tried multiple node-sass 4.x.x versions no luck.

Please help

**Comment by xzyfer** [comment]
@goufang please the comments above. You error message tells you what's going on and how to resolve it.

>Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

You're using Node 8.

>OS X 64-bit with Node.js 7.x

But you ran `npm install` with Node 7.

>This usually happens because your environment has changed since running `npm install`.
>Run `npm rebuild node-sass --force` to build the binding for your current environment.

**Comment by suhaibqaiser** [comment]
@xzyfer try running your windows power shell as administrator. And re-run npm rebuild node-sass --force
