### ISSUE TITLE
Latest release has vulnerable tunnel-agent as a dependency

### ISSUE THREAD

**Issue by dominykas** [sass/node-sass#2164]
When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): 6.12.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '6.12.0',
  v8: '5.1.281.108',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2m' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.7.2 

---

https://github.com/sass/node-sass/commit/187d8c91dff15d4655bfe0cb1155d5ca8a256184 pinned `request` to `v2.79.x`, which depends on a [vulnerable version of `tunnel-agent`](https://snyk.io/vuln/npm:tunnel-agent:20170305).

I understand that the change was done because newer versions of `request` require node v4+ and the intention of node-sass is to support older versions of node? This is probably the wrong place to have the debate whether the obsolete, unmaintained, insecure versions of node _should_ be supported, but I wonder if there is any decision on what is the plan for deprecating them (if any)?

If the intention is to keep the support for old-node, then aside from ignoring the vulnerability in projects consuming node-sass (bad idea), the fix would be to not use request, but rather to look for an alternative? Would a PR to do that be acceptable?

**Comment by nschonni** [comment]
Discussions for the next major are happening here https://github.com/sass/node-sass/issues/2111
This dependency is only used for our install and not for any runtime code
