### ISSUE TITLE
v4.7.2/win32-x64_binding.node cannot be download.

### ISSUE THREAD

**Issue by liminghuan1995** [sass/node-sass#2166]
I cannot download the release "win32-x64_binding.node",either via browser or my npm.
I start a ionic project,it requires that,but I couldn't just download it anyway!

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by liminghuan1995** [comment]
Never mind ,I have resolved it with "cnpm" instead.
