### ISSUE TITLE
Exit status 3221226356

### ISSUE THREAD

**Issue by sunwenxiu** [sass/node-sass#2168]
##when I exe "npm start",  I get 

webpack: Compiled successfully.
npm ERR! code ELIFECYCLE
npm ERR! errno 3221226356
npm ERR! rbac-app@1.0.0 start: `ng serve --open --disable-host-check`
npm ERR! Exit status 3221226356
npm ERR!
npm ERR! Failed at the rbac-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2017-11-28T06_22_39_188Z-debug.log

---------------------------------------------------------------------
- NPM version (`npm -v`):
  npm  v5.5.1
- Node version (`node -v`):
  node v8.9.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`):
win32
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):
`-- @angular/cli@1.5.4
  `-- node-sass@4.7.2

**Comment by nschonni** [comment]
Can you supply the log in a gist too?

**Comment by tapassingh** [comment]
I am also getting the same error. Log file have nothing new what it shows in console.
webpack: Compiled successfully.
npm ERR! code ELIFECYCLE
npm ERR! errno 3221226356
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 3221226356
npm ERR!
npm ERR! Failed at the apm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
--------------------------
npm version - 5.5.1

> node: 6.9.1
> os: win32 x64
> @angular/animations: 4.4.6
> @angular/common: 4.4.6
> @angular/compiler: 4.4.6
> @angular/core: 4.4.6
> @angular/forms: 4.4.6
> @angular/http: 4.4.6
> @angular/platform-browser: 4.4.6
> @angular/platform-browser-dynamic: 4.4.6
> @angular/router: 4.4.6
> @angular/cli: 1.2.4
> @angular/compiler-cli: 4.4.6
> @angular/language-service: 4.4.6

**Comment by nschonni** [comment]
You both seem to be hitting this through the angular-cli, I suggest you file an issue in that repo.

**Comment by krilllind** [comment]
I know this might be a late answer, but you can run `npm rebuild node-sass` which should fix your given problem. Leaving this for everyone facing the same problem.
