### ISSUE TITLE
Can't find Executable Python

### ISSUE THREAD

**Issue by Mutasem-Halawani** [sass/node-sass#2173]
error when installing node-sass

Z:\mutasemh\Desktop\bridge-to-europe>npm install

> node-sass@4.7.2 install Z:\mutasemh\Desktop\bridge-to-europe\node_modules\node
-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7
.2/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win3
2-x64-57_binding.node":

tunneling socket could not be established, cause=Hostname/IP doesn't match certi
ficate's altnames: "Host: github.com. is not in the cert's altnames: DNS:a.sni.f
astly.net, DNS:a.sni.global-ssl.fastly.net"

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 postinstall Z:\mutasemh\Desktop\bridge-to-europe\node_modules\
node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe Z:\mutasemh\Desktop\bridge-to-europe\
node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass
_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\node-gyp\
\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (Z:\mutasemh\Desktop\bridge-to-e
urope\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:68:19)
gyp verb `which` failed     at E (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:80:29)
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\which\which.js:89:16
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\index.js:42:5
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (Z:\mutasemh\Desktop\bridge-to-e
urope\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:68:19)
gyp verb `which` failed     at E (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:80:29)
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\which\which.js:89:16
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\index.js:42:5
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundE
rror (Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\which\\which.js:13:
12)\n    at F (Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\which\\whi
ch.js:68:19)\n    at E (Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\w
hich\\which.js:80:29)\n    at Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modu
les\\which\\which.js:89:16\n    at Z:\\mutasemh\\Desktop\\bridge-to-europe\\node
_modules\\isexe\\index.js:42:5\n    at Z:\\mutasemh\\Desktop\\bridge-to-europe\\
node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)
',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (Z:\mutasemh\Desktop\bridge-to-e
urope\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:68:19)
gyp verb `which` failed     at E (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:80:29)
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\which\which.js:89:16
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\index.js:42:5
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (Z:\mutasemh\Desktop\bridge-to-e
urope\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:68:19)
gyp verb `which` failed     at E (Z:\mutasemh\Desktop\bridge-to-europe\node_modu
les\which\which.js:80:29)
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\which\which.js:89:16
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\index.js:42:5
gyp verb `which` failed     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules
\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundEr
ror (Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\which\\which.js:13:1
2)\n    at F (Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\which\\whic
h.js:68:19)\n    at E (Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\wh
ich\\which.js:80:29)\n    at Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modul
es\\which\\which.js:89:16\n    at Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_
modules\\isexe\\index.js:42:5\n    at Z:\\mutasemh\\Desktop\\bridge-to-europe\\n
ode_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)'
,
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (Z:\mutasemh\Desktop\bridge-to-e
urope\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (Z:\mutasemh\Desktop\bridge-to-eu
rope\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at Z:\mutasemh\Desktop\bridge-to-europe\node_modules\graceful
-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "Z:\\mutasemh\\Desktop\\b
ridge-to-europe\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
 "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd Z:\mutasemh\Desktop\bridge-to-europe\node_modules\node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'Z:\mutasemh\Desktop\bri
dge-to-europe\node_modules\yargs-parser\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'Z:\mutasemh\Desktop\
bridge-to-europe\node_modules\yargs-parser\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'Z:\\mutasemh
\\Desktop\\bridge-to-europe\\node_modules\\yargs-parser\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'Z:\\mutasemh\\Desktop\\bridge-to-europe\\node_modules\\yargs-p
arser\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

------------------------------------------------------------------------------------------------------------------

- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): 8.9.1

- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

- Node Platform (`node -p process.platform`): win 32

- Node architecture (`node -p process.arch`): x64

- node-sass version (`node -p "require('node-sass').info"`):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)

- npm node-sass versions (`npm ls node-sass`):
Z:\mutasemh\Desktop\bridge-to-europe>npm ls node-sass   
generator-frontend-webpack@1.0.0 Z:\mutasemh\Desktop\bridge-to-europe`-- (empty)

**Comment by nschonni** [comment]
The build requirements for windows are covered by the troubleshooting guide. NPM is also telling you how to fix the proxy issues if you want to use our pre-built binaries

**Comment by DominicTobias** [comment]
Hi where is the troubleshooting guide and how do I install the pre-built bin? Installing from executable is blocked at work as is connection to windows to do e.g. `npm --add-python-to-path='true' --debug install --global windows-build-tools` so I'd prefer not to say before you can run this UI app download the Python source and whatever steps are needed to build it and modify your PATH variable that gets reset every log off" thanks
