### ISSUE TITLE
When I'm 'yarn', make this mistake， Who Can Help Me?

### ISSUE THREAD

**Issue by weijing4003** [sass/node-sass#2174]
node: 8.9.1
yarn : 0.27.5

**Error message:**
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check.                                                                                                                                                                                                Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error E:\nuxt-template\node_modules\node-sass: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node scripts/build.js
Directory: E:\nuxt-template\node_modules\node-sass
Output:
Binary found at E:\web\win32-x64-48_binding.node
Testing binary
Binary has a problem: Error: The module '\\?\E:\web\win32-x64-48_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (E:\nuxt-template\node_modules\node-sass\lib\binding.js:19                                                                                                                                                                                               :10)
    at Object.<anonymous> (E:\nuxt-template\node_modules\node-sass\lib\index.js:                                                                                                                                                                                               14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
Building the binary locally
Building: C:\Program Files\nodejs\node.exe E:\nuxt-template\node_modules\node-gy                                                                                                                                                                                               p\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_l                                                                                                                                                                                               dflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\nuxt-template\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\nuxt-template\node_modules\w                                                                                                                                                                                               hich\which.js:13:12)
gyp verb `which` failed     at F (E:\nuxt-template\node_modules\which\which.js:6                                                                                                                                                                                               8:19)
gyp verb `which` failed     at E (E:\nuxt-template\node_modules\which\which.js:8                                                                                                                                                                                               0:29)
gyp verb `which` failed     at E:\nuxt-template\node_modules\which\which.js:89:1                                                                                                                                                                                               6
gyp verb `which` failed     at E:\nuxt-template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\nuxt-template\node_modules\isexe\windows.js:36                                                                                                                                                                                               :5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\nuxt-template\node_modules\w                                                                                                                                                                                               hich\which.js:13:12)
gyp verb `which` failed     at F (E:\nuxt-template\node_modules\which\which.js:6                                                                                                                                                                                               8:19)
gyp verb `which` failed     at E (E:\nuxt-template\node_modules\which\which.js:8                                                                                                                                                                                               0:29)
gyp verb `which` failed     at E:\nuxt-template\node_modules\which\which.js:89:1                                                                                                                                                                                               6
gyp verb `which` failed     at E:\nuxt-template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\nuxt-template\node_modules\isexe\windows.js:36                                                                                                                                                                                               :5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundE                                                                                                                                                                                               rror (E:\\nuxt-template\\node_modules\\which\\which.js:13:12)\n    at F (E:\\nux                                                                                                                                                                                               t-template\\node_modules\\which\\which.js:68:19)\n    at E (E:\\nuxt-template\\n                                                                                                                                                                                               ode_modules\\which\\which.js:80:29)\n    at E:\\nuxt-template\\node_modules\\whi                                                                                                                                                                                               ch\\which.js:89:16\n    at E:\\nuxt-template\\node_modules\\isexe\\index.js:42:5                                                                                                                                                                                               \n    at E:\\nuxt-template\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWr                                                                                                                                                                                               ap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print                                                                                                                                                                                               (platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node v                                                                                                                                                                                               ersion: 8.9.1
gyp verb command install [ '8.9.1' ]
gyp verb install input version string "8.9.1"
gyp verb install installing version: 8.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.1
gyp verb build dir attempting to create "build" dir: E:\nuxt-template\node_modul                                                                                                                                                                                               es\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\nuxt-template\node_modul                                                                                                                                                                                               es\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\nuxt-template\node_module                                                                                                                                                                                               s\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\nuxt-template\node_modules\node-                                                                                                                                                                                               sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\nuxt-template\node_modules\node-                                                                                                                                                                                               sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'E:\\nuxt-template\\node_modules\\node-gyp\\gyp\\gyp_main.                                                                                                                                                                                               py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\nuxt-template\\node_modules\\node-sass\\build\\config                                                                                                                                                                                               .gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\nuxt-template\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\1\\.node-gyp\\8.9.1\\include\\node\\common.gyp                                                                                                                                                                                               i',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\1\\.node-gyp\\8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\nuxt-template\\node_modules\\node-gyp'                                                                                                                                                                                               ,
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\1\\.node-gyp\\8.9.1\\<(target_                                                                                                                                                                                               arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\nuxt-template\\node_modules\\node-s                                                                                                                                                                                               ass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\nuxt-template\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\1\.node-gyp\8.9.1
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
������ʱ��Ϊ 2017/11/30 19:51:36��
�ڵ� 1 �ϵ���Ŀ��E:\nuxt-template\node_modules\node-sass\build\binding.sln��(Ĭ��Ŀ��                                                                                                                                                                                               )��
ValidateSolutionConfiguration:
  �������ɽ���������á�Release|x64����
��Ŀ��E:\nuxt-template\node_modules\node-sass\build\binding.sln��(1)���ڽڵ� 1 ����                                                                                                                                                                                               �ɡ�E:\nuxt-template\node_modules\node-sass\build\binding.vcxproj.metaproj��(2) (                                                                                                                                                                                               Ĭ��Ŀ��)��
��Ŀ��E:\nuxt-template\node_modules\node-sass\build\binding.vcxproj.metaproj��(2)                                                                                                                                                                                               ���ڽڵ� 1 �����ɡ�E:\nuxt-template\node_modules\node-sass\build\src\libsass.vcxpro                                                                                                                                                                                               j��(3) (Ĭ��Ŀ��)��
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToo                                                                                                                                                                                               lsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was                                                                                                                                                                                                not found. Install the required version of Windows SDK or change the SDK versio                                                                                                                                                                                               n in the project property pages or by right-clicking the solution and selecting                                                                                                                                                                                                "Retarget solution". [E:\nuxt-template\node_modules\node-sass\build\src\libsass.                                                                                                                                                                                               vcxproj]
�����������Ŀ��E:\nuxt-template\node_modules\node-sass\build\src\libsass.vcxproj�                                                                                                                                                                                               �(Ĭ��Ŀ��)�Ĳ��� - ʧ�ܡ�
�����������Ŀ��E:\nuxt-template\node_modules\node-sass\build\binding.vcxproj.meta                                                                                                                                                                                               proj��(Ĭ��Ŀ��)�Ĳ��� - ʧ�ܡ�
�����������Ŀ��E:\nuxt-template\node_modules\node-sass\build\binding.sln��(Ĭ��Ŀ��                                                                                                                                                                                               )�Ĳ��� - ʧ�ܡ�

����ʧ�ܡ�

��E:\nuxt-template\node_modules\node-sass\build\binding.sln��(Ĭ��Ŀ��) (1) ->
��E:\nuxt-template\node_modules\node-sass\build\binding.vcxproj.metaproj��(Ĭ��Ŀ�                                                                                                                                                                                               �) (2) ->
��E:\nuxt-template\node_modules\node-sass\build\src\libsass.vcxproj��(Ĭ��Ŀ��) (3                                                                                                                                                                                               ) ->
(Desktop_PlatformPrepareForBuild Ŀ��) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformT                                                                                                                                                                                               oolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 w                                                                                                                                                                                               as not found. Install the required version of Windows SDK or change the SDK vers                                                                                                                                                                                               ion in the project property pages or by right-clicking the solution and selectin                                                                                                                                                                                               g "Retarget solution". [E:\nuxt-template\node_modules\node-sass\build\src\libsas                                                                                                                                                                                               s.vcxproj]

    0 ������
    1 ������

����ʱ�� 00:00:02.72
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail                                                                                                                                                                                               ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nuxt-template\node_modules\node-gy                                                                                                                                                                                               p\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                                                                                                               s.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\nuxt-template\\node_                                                                                                                                                                                               modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--l                                                                                                                                                                                               ibsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\nuxt-template\node_modules\node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this                                                                                                                                                                                                command.

**Comment by xzyfer** [comment]
Delete your node_modules and try again.

**Comment by weijing4003** [comment]
thank you very much,I have changed node version 6.11.2, trying  it successed.

**Comment by rafaheringer** [comment]
Today I have the same problem with Node v8.9.1.
I've downgraded to version 6.11.2 and it works.

**Comment by kiditran** [comment]
Thank rafaheringer  so much. I've downgraded Node to version 6.x.x and it works fine.
