### ISSUE TITLE
Security Issue "Uninitialized Exposure"

### ISSUE THREAD

**Issue by FelixRamirezJr** [sass/node-sass#2180]
Before I begin, I just want to say thanks to the maintainers and contributors for putting in all this work in making this NPM package awesome!

My team and I use Snyk on Heroku which is a add-on that checks for security issues in our NPM packages. Your latest version of this package has a venerable module from 'Tunnel Agent' which has an "Uninitialized Memory Exposure". 
Introduced through: app@null › node-sass@4.7.2 › request@2.79.0 › tunnel-agent@0.4.3 

Also, we use Yarn.

Our version of node-sass is "4.7.2"
NPM: 5.5.1
Node: 8.9.1
Node Process:
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

process.platform: linux

node-sass version:
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]

npm node-sass:
node-sass@4.7.2

**Comment by xzyfer** [comment]
Thanks for the report. This is a known issue. However we cannot update request because they broke support for node < 4 https://github.com/request/request/issues/2772
