### ISSUE TITLE
Environment mismatch - cannot find binding

### ISSUE THREAD

**Issue by nolanmclark** [sass/node-sass#2182]
I've looked everywhere and can find no solution to this. The app builds fine on my machine, but when I send the files to Ionic Pro to be built, I run into this mismatch in environments. I've shared my issue on their forum here: https://forum.ionicframework.com/t/node-sass-binding-environment-ionic-pro-building-error/114708 , as well as with their support team.

My project has been purely developed on Mac OSX, no Linux machine involved.

My hypothesis is that they are running a Linux based back-end when building my application, which is creating my current issue. This is why I'm coming here last, but would greatly appreciate an explanation to the issue. 

Application build stack trace -
```
Running with gitlab-ci-multi-runner 9.1.0 (0118d89)
  on Snapshot Builds (c9648220)
Using Shell executor...
Running on ip-10-2-215-6...
Cloning repository...
Cloning into '/home/gitlab-runner/builds/c9648220/3/project-1'...
Checking out bd821341 as master...
Skipping Git submodules setup
$ run "fetch-updates"
Running Job: 5158522
Checking for build process updates...
$ run "build-app"
Running Job: 5158522
Attempting to restore cached packages...
No cache found for packages, installing...
$ npm install --quiet --no-optional
up to date in 6.063s
Saving package cache...
Package cache saved!
$ npm run build
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm info lifecycle paths@0.0.1~prebuild: paths@0.0.1
npm info lifecycle paths@0.0.1~build: paths@0.0.1

> paths@0.0.1 build /usr/src/app
> ionic-app-scripts build

/usr/src/app/node_modules/@ionic/app-scripts/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /usr/src/app/node_modules/@ionic/app-scripts/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/usr/src/app/node_modules/@ionic/app-scripts/node_modules/node-sass/lib/binding.js:15:13)
    at Object. (/usr/src/app/node_modules/@ionic/app-scripts/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object. (/usr/src/app/node_modules/@ionic/app-scripts/dist/core/bundle-components.js:6:16)
npm info lifecycle paths@0.0.1~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! paths@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the paths@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2017-12-08T20_47_32_313Z-debug.log
npm run build failed
Running after script...
$ run "clean-up"
Running Job: 5158522
ERROR: Job failed: exit status 1
```

- NPM version (`npm -v`): 5.3.0
- Node version (`node -v`): v8.6.0
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0',
  node: '8.6.0',
  v8: '6.0.287.53',
  uv: '1.14.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }`

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
`node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]`
- npm node-sass versions (`npm ls node-sass`): 
`paths@0.0.1 /Users/nolanclark/Nolan/Development/Pathways
├─┬ @ionic/app-scripts@3.1.5
│ └── node-sass@4.5.3
└── node-sass@4.7.2`

**Comment by xzyfer** [comment]
The error suggests you're sending your `node_modules` (installed on osx) to a service who is running on linux. This cannot work with a native modules like node-sass. The linux service needs to run `npm install` from a clean `node_modules`. You should always run a clean `npm install` when changing Node versions or environments (i.e. os, architecture). There's nothing we can do here.

**Comment by nolanmclark** [comment]
Totally fine, I just wanted to know where this error was originating, I have it narrowed down now. Thank you.
