### ISSUE TITLE
Unsupported runtime (59) on Mac Os X Darwin

### ISSUE THREAD

**Issue by nirus** [sass/node-sass#2183]
Before opening an issue:
- Check that the version of node-sass you're trying to install supports your version of Node by looking at the release page for that version https://github.com/sass/node-sass/releases
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): node/9.2.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '9.2.1',
  v8: '6.2.414.44-node.11',
  uv: '1.16.1',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
- Node Platform (`node -p process.platform`): Mac OS X darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):  4.5.3 
- npm node-sass versions (`npm ls node-sass`): node-sass@4.5.3

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Log:**
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)

**Resolution:**
Support required for 59

**Comment by xzyfer** [comment]
Your node-sass version is too old. Update to 4.7.2
