### ISSUE TITLE
Watch mode watches its own output recursively if output directory descends from the input directory.

### ISSUE THREAD

**Issue by shirakaba** [sass/node-sass#2184]
## Minimum reproduction

Module.scss:

```SCSS
.moduleStyle {
    opacity: 1;
}
```

```bash
node_modules/.bin/node-sass --watch src/scss --output src/scss/css_prebuild
```

## Behaviour

In watch mode, it emits to `src/scss/css_prebuild`, then emits again to `src/scss/css_prebuild/css_prebuild`. This may happen recursively (albeit limited to one level by some safety factor).

```bash
my-mac:myProject me$ node_modules/.bin/node-sass --watch src/scss --output src/scss/css_prebuild
=> changed: /Users/me/Sites/myProject/src/scss/video.scss
Rendering Complete, saving .css file...
Wrote CSS to /Users/me/Sites/myProject/src/scss/css_prebuild/video.css
=> changed: /Users/me/Sites/myProject/src/scss/css_prebuild/video.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/me/Sites/myProject/src/scss/css_prebuild/css_prebuild/video.css
```

## Proposal

Two options:

* `--watch` mode should not default to adding the `--recursive` flag.

* There should be a way to exclude paths or ignore directories, and the output directory should be implicitly ignored.

## Configuration

- NPM version (`npm -v`): 5.4.2
- Node version (`node -v`): 8.7.0
- Node Process (`node -p process.versions`):
```Javascript
{ http_parser: '2.7.0',
  node: '8.7.0',
  v8: '6.1.534.42',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
```bash
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):

```bash
myProject@1.0.0 /Users/me/Sites/myProject
└── node-sass@4.7.2 
```

**Comment by xzyfer** [comment]
Please search issues before opening a new issue.

Node Sass cannot currently support outputting to the input directory when
watching. This is because CSS files are importable in LibSass due to a
feature/bug.
