### ISSUE TITLE
Vs2017+ Node Sass Installation problem

### ISSUE THREAD

**Issue by bharathpbk** [sass/node-sass#2186]
pm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-12-13T03_31_48_046Z-debug.log
PS C:\xxx\xxx\xx.UI> npm run-script build

> my-xxx.ui@0.0.0 build C:\xxx\xxx\xx.UI
> ng build

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-portal.ui@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-portal.ui@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

i installed VS2017 and Node version 8.9 . When i am trying to install sass though npm i am getting above issue.

**Comment by bgever** [comment]
Did you get any errors before that? We noticed download/connection issues of the node-sass binaries today, and were clearing the cache before the npm (Yarn) install, hence it wouldn't use the cached version from the last run.

**Comment by ssageghi** [comment]
@bgever Hi 
I'm Getting Not Found Error while trying to install node-sass !!!!!
Is this related?
if so What's the status? thanks

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
