### ISSUE TITLE
Can not install node-sass on Mac OS 

### ISSUE THREAD

**Issue by dehboris** [sass/node-sass#2189]
Hi, 
I want to install node but not work
**Information**

- NPM version (`5.6.0`):
- Node version (`8.9.2`):

- Node Process (`node -p process.versions`):
`{ http_parser: '2.7.0',
  node: '8.9.2',
  v8: '6.1.534.48',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }`

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
`module.js:538
    throw err;
    ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)`

- npm node-sass versions (`npm ls node-sass`): empty

**Log**

After lunch npm install i have this error
`
2404 verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`
2404 verbose stack Exit status 1
2404 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
2404 verbose stack     at emitTwo (events.js:126:13)
2404 verbose stack     at EventEmitter.emit (events.js:214:7)
2404 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2404 verbose stack     at emitTwo (events.js:126:13)
2404 verbose stack     at ChildProcess.emit (events.js:214:7)
2404 verbose stack     at maybeClose (internal/child_process.js:925:16)
2404 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2405 verbose pkgid node-sass@4.7.2
2406 verbose cwd /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food
2407 verbose Darwin 16.7.0
2408 verbose argv "/usr/local/Cellar/node/8.9.2/bin/node" "/usr/local/bin/npm" "install"
2409 verbose node v8.9.2
2410 verbose npm  v5.6.0
2411 error code ELIFECYCLE
2412 error errno 1
2413 error node-sass@4.7.2 postinstall: `node scripts/build.js`
2413 error Exit status 1
2414 error Failed at the node-sass@4.7.2 postinstall script.
2414 error This is probably not a problem with npm. There is likely additional logging output above.
2415 verbose exit [ 1, true ]`

Thank to help me

**Comment by xzyfer** [comment]
There is likely additional logging output above. 2415 verbose exit

We need the whole log file to see what's wrong.

**Comment by allycol** [comment]
I'm having the same issue.

Complete log:

```> node-sass@4.7.2 install /Users/allycolquhoun/temp1/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/allycolquhoun/temp1/node_modules/node-sass/vendor/darwin-x64-59 : { Error: EACCES: permission denied, mkdir '/Users/allycolquhoun/temp1/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:905:18)
    at sync (/Users/allycolquhoun/temp1/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/allycolquhoun/temp1/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/allycolquhoun/temp1/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/allycolquhoun/temp1/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/allycolquhoun/temp1/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/allycolquhoun/temp1/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/allycolquhoun/temp1/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/allycolquhoun/temp1/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.2.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/allycolquhoun/temp1/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/allycolquhoun/temp1/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/allycolquhoun/temp1/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/allycolquhoun/temp1/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/allycolquhoun/temp1/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/allycolquhoun/temp1/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/allycolquhoun/temp1/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/allycolquhoun/temp1/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/allycolquhoun/temp1/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/allycolquhoun/temp1/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/allycolquhoun/temp1/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/allycolquhoun/temp1/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/allycolquhoun/temp1/node_modules/which/which.js:13:12)\n    at F (/Users/allycolquhoun/temp1/node_modules/which/which.js:68:19)\n    at E (/Users/allycolquhoun/temp1/node_modules/which/which.js:80:29)\n    at /Users/allycolquhoun/temp1/node_modules/which/which.js:89:16\n    at /Users/allycolquhoun/temp1/node_modules/isexe/index.js:42:5\n    at /Users/allycolquhoun/temp1/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.2.1
gyp verb command install [ '9.2.1' ]
gyp verb install input version string "9.2.1"
gyp verb install installing version: 9.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.2.1
gyp verb build dir attempting to create "build" dir: /Users/allycolquhoun/temp1/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/allycolquhoun/temp1/node_modules/node-sass/build'
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/allycolquhoun/temp1/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/allycolquhoun/temp1/node_modules/node-sass
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open '/Users/allycolquhoun/temp1/package.json'
npm WARN temp1 No description
npm WARN temp1 No repository field.
npm WARN temp1 No README data
npm WARN temp1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/allycolquhoun/.npm/_logs/2017-12-16T21_46_40_504Z-debug.log
```

**Comment by xzyfer** [comment]
Unable to save binary
/Users/allycolquhoun/temp1/node_modules/node-sass/vendor/darwin-x64-59
: { Error: EACCES: permission denied


Looks like a permission issue. Maybe from running npm as audo at some
point. Fix your permissions and try again.

**Comment by dehboris** [comment]
All ouput after run `sudo npm install`

`> node-sass@4.7.2 install /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/8.9.2/bin/node /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/8.9.2/bin/node',
gyp verb cli   '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.2
gyp verb command install [ '8.9.2' ]
gyp verb install input version string "8.9.2"
gyp verb install installing version: 8.9.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.2
gyp verb build dir attempting to create "build" dir: /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.9.2/bin/node" "/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pro/.npm/_logs/2017-12-17T05_45_04_299Z-debug.log`

**Comment by xzyfer** [comment]
Unable to save binary /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_
modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission
denied, mkdir '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_
modules/node-sass/vendor'

Also looks like a permission issue

**Comment by btinoco** [comment]
@xzyfer you keep saying it looks like a permission issue but I do not know about that man... again I may be wrong but I created a new folder under `~/.npm-global` to install global npm modules and I get the same error as @dehboris.  I even went to ~/.npm-global and chmod 777 and I get the same issue.  I tried with sudo and without sudo and I still keep getting that. I deleted npm and reinstalled it and still the same issue... I might be wrong (again) but I believe I covered most of the permission issues and no success.  Is there something else I am missing on the permission side?

**Comment by dehboris** [comment]
@xzyfer 
I still have the same problem, I have not been able to solve that yet.
Thank you for sharing your solution with me.

**Comment by dimitri320** [comment]
I have the exact same problem, and no solution yet.

**Comment by btinoco** [comment]
Anyone got this working? Love it how node-sass ignores our comments.

**Comment by Alexcortes** [comment]
Any solution?

**Comment by robincard** [comment]
I also have the same problem.

**Comment by nschonni** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions
