### ISSUE TITLE
No such file or directory, scandir

### ISSUE THREAD

**Issue by odrik** [sass/node-sass#2193]
Hello.

What's the current problem please ?

<img width="738" alt="screenshot559" src="https://user-images.githubusercontent.com/16124915/34168820-d71c4b62-e4e5-11e7-8d2e-f116f61a2d52.png">
<img width="710" alt="screenshot560" src="https://user-images.githubusercontent.com/16124915/34168824-d8a1ec76-e4e5-11e7-9ae2-8fcf78982838.png">

I use node v9.3.0 and npm v5.5.1

Thanks.

**Comment by xzyfer** [comment]
Looks like npm didn't install successfully
