### ISSUE TITLE
Failed at the node-sass@3.13.1 postinstall script. 

### ISSUE THREAD

**Issue by kabircse** [sass/node-sass#2196]
I am fetching this message when I am running npm install.  What can I do ?

- NPM version (`npm -v`):  5.6.0
- Node version (`node -v`): 8.9.3
- Node Process (`node -p process.versions`):
{ 
http_parser: '2.7.0',
  node: '8.9.3',
  v8: '6.1.534.48',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b'
 }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
    node-sass       4.7.2   (Wrapper)       [JavaScript]
    libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`): 
     E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel
     `-- node-sass@4.7.2

**Comment by kabircse** [comment]
Is there any suggestion/solution for me ?

**Comment by kabircse** [comment]
npm install gives me error, error details:

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-sass@3.13.1 install E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\HAMKO 3\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\HAMKO 3\.windows-build-tools\python27\python.exe C:\Users\HAMKO 3\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\HAMKO 3\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.3
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.3
gyp verb build dir attempting to create "build" dir: E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\HAMKO 3\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\gulp-sass\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\HAMKO 3\\.node-gyp\\8.9.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\HAMKO 3\\.node-gyp\\8.9.3',
gyp info spawn args   '-Dnode_gyp_dir=E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\HAMKO 3\\.node-gyp\\8.9.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\gulp-sass\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\gulp-sass\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\HAMKO 3\.node-gyp\8.9.3
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 21-Dec-17 1:52:38 PM.
Project "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" (1) is building "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj]
Done Building Project "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.
Done Building Project "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.
Done Building Project "E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(Desktop_PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\xampp\\htdocs\\dev_web_admin_eshop_hee\\laravel\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\xampp\htdocs\dev_web_admin_eshop_hee\laravel\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN The package babel-preset-env is included as both a dev and production dependency.
npm WARN The package bootstrap-sass is included as both a dev and production dependency.
npm WARN The package gulp is included as both a dev and production dependency.
npm WARN The package laravel-elixir is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HAMKO 3\AppData\Roaming\npm-cache\_logs\2017-12-21T07_52_39_331Z-debug.log

**Comment by xzyfer** [comment]
Version 3 is is very old and doesn't support node 5. You need to upgrade to
node-sass@4 or downgrade to node 0.12

**Comment by kabircse** [comment]
@sabbir hossain, Alreday I have applied your tricks but nothing. 
Now trying the solution of xzyfer.

Thanks all.

**Comment by kabircse** [comment]
Yet failed ....

**Comment by kabircse** [comment]
I solved this problem using Ubuntu. There is no problem.

**Comment by Hancock-Xu** [comment]
I also have the same problem....Hope anyone can help
