### ISSUE TITLE
Uninitialized Memory Exposure on request@2.79.0

### ISSUE THREAD

**Issue by bosco688** [sass/node-sass#2197]
My team uses Snyk to check for security issues in our NPM packages. The latest version of this package has a vulnerable module which has an "Uninitialized Memory Exposure".

Vulnerable module: tunnel-agent
Introduced through: node-sass@4.7.2 › request@2.79.0 › tunnel-agent@0.4.3  

**Remediation:  Upgrade to request@2.81.0.**

**Comment by xzyfer** [comment]
This is a known issue. See https://github.com/sass/node-sass/pull/2170
