### ISSUE TITLE
Assertion Failed! Expression: persistent().IsNearDeath()

### ISSUE THREAD

**Issue by NTXAggie** [sass/node-sass#2199]
Before opening an issue:
- Check that the version of node-sass you're trying to install supports your version of Node by looking at the release page for that version https://github.com/sass/node-sass/releases
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 5.6.0

- Node version (`node -v`): v8.9.3

- Node Process (`node -p process.versions`): 
{ http_parser: '2.7.0',
  node: '8.9.3',
  v8: '6.1.534.48',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

- Node Platform (`node -p process.platform`): win32

- Node architecture (`node -p process.arch`): x64

- node-sass version (`node -p "require('node-sass').info"`): 
node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`): node-sass@4.7.2

When encountering a syntax, or compilation issue: 

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

I am encountering an issue when trying to run any node-sass tasks. 

![image](https://user-images.githubusercontent.com/16783541/34440481-2507bfd6-ec7b-11e7-9cc8-eb374bbb22f2.png)

Not sure where to even begin with debugging but I am willing to give you any info required, just please point me to what I need to do. Thank you guys!

**Comment by NTXAggie** [comment]
ALSO: Please note, I have tried the debugging instructions here: https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#debugging-installation-issues 
This did not make a difference.

**Comment by saper** [comment]
Do you know if there is any way to reproduce that problem?

**Comment by NTXAggie** [comment]
@saper I'm not sure the right way to reproduce, but I know it had to do with running nodejs v8....I downgraded all the way to v4 and all the issues resolved themselves.

**Comment by saper** [comment]
@NTXAggie a backtrace would be nice... There is a PDB file you can download for your node-sass version http://github.com/sass/node-sass/releases to produce a meaningful backtrace if possible.
