### ISSUE TITLE
Meteor error downloading node-sass v3.8.0

### ISSUE THREAD

**Issue by pedrofg** [sass/node-sass#2200]
![image](https://user-images.githubusercontent.com/8161635/34494048-9263c072-efbc-11e7-8885-274216819622.png)

Working on Windows 10.
Meteor version 1.6.0.1
Meteor node version 8.9.3

Getting this error after updating the meteor version from 1.5 to 1.6 in the project. 
Looks like this package angular2-compilers@0.6.6 tries to download this node-sass version which is not in the repository.

Have anyone had this issue?

**Comment by daniel-duliga** [comment]
Same issue here while trying to start the Ionic Framework "tabs" sample.

**Comment by pedrofg** [comment]
In my case, i am using with Meteor which uses its own node.

**Comment by xzyfer** [comment]
The version compatibility chart in the issue template your ignored would
have told you node-sass 3.x does not support Node 8.

Use node 4 or update node-sass to 4.7

**Comment by pedrofg** [comment]
The issue is also related to Meteor, how does it work on Linux but not on Windows?

**Comment by xzyfer** [comment]
Please open an issue with meteor if they've pinned to an old version of node-sass. Node-sass v3 cannot run with Node 8.

It's not a Windows vs Linux matter, it's purely about the version of Node being used.

**Comment by SosaWiseHome** [comment]
I'm having the same problem.  Here is my configuration:
- Meteor Version 1.6.01
- Node Version 4.8.4  (Is there a meteor version of Node?  If so I'm showing here the global version.  Not sure how to get the version of node that meteor is using).

	Errors prevented startup:

	While loading package angular2-compilers@0.6.6:
	error: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\Owner\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild --update-binary
	Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-57_binding.node":

	HTTP error 404 Not Found

	Hint: If github.com is not accessible in your location
	try setting a proxy via HTTP_PROXY, e.g.

I also update node-sass to 4.7 using the following command:
	npm install -global node-sass
	and 
	meteor npm install -global node-sass

**Comment by pedrofg** [comment]
@SosaWiseHome what I have done was uninstall both node and meteor and install just meteor again. It worked for me.

**Comment by SosaWiseHome** [comment]
Which version of meteor did you install?

**Comment by xzyfer** [comment]
You need node-sass 4.7 to run on node 9. Node sass 3.8 on only supports
upto node 4.

**Comment by SosaWiseHome** [comment]
Thanks man.  I’m running my app in Meteor.  It appears that Meteor has it’s own Node instance so I had to revert back to a previous version of Meteor and it all works now.  Very frustrated.

**Comment by xzyfer** [comment]
I suggest opening an issue with meteor to update their node-sass version to
be compatible with their bundled node version.

**Comment by SosaWiseHome** [comment]
I will check but I believe someone has already done that.  

 

Thanks so much for your help.  You have been very helpful to me.

 

-Andres Sosa
