### ISSUE TITLE
Failed at the node-sass@4.7.2 postinstall script 'node scripts/build.js'.

### ISSUE THREAD

**Issue by vinnipadi** [sass/node-sass#2203]
Before opening an issue:
- Check that the version of node-sass you're trying to install supports your version of Node by looking at the release page for that version https://github.com/sass/node-sass/releases
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by ni8mr** [comment]
I am facing same issue while installing node-sass@4.7.2. My versions are -

- NPM version: 5.6.0

- Node version: 8.9.4

- Node process: `{ http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
`

- Node Platform: linux

- Node architecture: x64

**Comment by xzyfer** [comment]
@ni8mr please open a new issue with the information requested in the template

**Comment by andrewhouser** [comment]
This issue was closed, but what was the resolution. I am still facing the same issue.

**Comment by xzyfer** [comment]
This issue was closed no useful information was provided. If you're having
issues please create a new issue and follow the steps.

**Comment by kodemasta** [comment]
Also seeing this: node-sass@4.7.2 postinstall: `node scripts/build.js`

Binary has a problem: [Error: ../node_modules/node-sass/vendor/linux-x64-46/binding.node: ELF file OS ABI invalid]
