### ISSUE TITLE
Failed to install node-sass on Ubuntu

### ISSUE THREAD

**Issue by jecs-imperial** [sass/node-sass#2204]
Hi, 

I cannot seem to install node-sass at all on Ubuntu.

The last few lines of the npm debug log are:

+++

http 304 https://registry.npmjs.org/path-exists
2726 verbose headers { date: 'Sat, 06 Jan 2018 21:00:42 GMT',
2726 verbose headers   via: '1.1 varnish',
2726 verbose headers   'cache-control': 'max-age=300',
2726 verbose headers   etag: '"59e9bb28-1c55"',
2726 verbose headers   age: '11632',
2726 verbose headers   connection: 'keep-alive',
2726 verbose headers   'x-served-by': 'cache-lhr6346-LHR',
2726 verbose headers   'x-cache': 'HIT',
2726 verbose headers   'x-cache-hits': '8',
2726 verbose headers   'x-timer': 'S1515272442.150871,VS0,VE0',
2726 verbose headers   vary: 'Accept-Encoding, Accept' }
2727 silly get cb [ 304,
2727 silly get   { date: 'Sat, 06 Jan 2018 21:00:42 GMT',
2727 silly get     via: '1.1 varnish',
2727 silly get     'cache-control': 'max-age=300',
2727 silly get     etag: '"59e9bb28-1c55"',
2727 silly get     age: '11632',
2727 silly get     connection: 'keep-alive',
2727 silly get     'x-served-by': 'cache-lhr6346-LHR',
2727 silly get     'x-cache': 'HIT',
2727 silly get     'x-cache-hits': '8',
2727 silly get     'x-timer': 'S1515272442.150871,VS0,VE0',
2727 silly get     vary: 'Accept-Encoding, Accept' } ]
2728 verbose etag https://registry.npmjs.org/path-exists from cache
2729 verbose get saving path-exists to /home/james/.npm/registry.npmjs.org/path-exists/.cache.json
2730 verbose correctMkdir /home/james/.npm correctMkdir not in flight; initializing
2731 verbose stack TypeError: Cannot convert undefined or null to object
2731 verbose stack     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
2731 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
2731 verbose stack     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
2731 verbose stack     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
2731 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
2731 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
2732 verbose cwd /home/james/Development/Occam
2733 error Linux 4.4.0-104-generic
2734 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-sass"
2735 error node v6.12.3
2736 error npm  v3.10.10
2737 error Cannot convert undefined or null to object
2738 error If you need help, you may report this error at:
2738 error     <https://github.com/npm/npm/issues>
2739 verbose exit [ 1, true ]

+++

Let me know if you need more.

Looking at 'fetch-package-metadata.js' I see the offending line...

 var versions = Object.keys(pkg.versions)

...so clearly the problem is that pkg is null or undefined.

I've tried re-installing node but the error remains the same. I have no idea where to go from here.

- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.12.3
- Node Process (`node -p process.versions`):

{ http_parser: '2.7.0',
  node: '6.12.3',
  v8: '5.1.281.111',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2n' }

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): (none installed)
- npm node-sass versions (`npm ls node-sass`):

npm@3.10.10 /usr/lib/node_modules/npm
└── (empty)

npm ERR! code 1

Regards,

James

**Comment by leandroruel** [comment]
same here... i'm stuck


Module build failed: Error: Missing binding /var/www/myapp/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 9.x

**Comment by leandroruel** [comment]
hey @jecs-imperial your nodejs version is 3.10? looks pretty old

**Comment by xzyfer** [comment]
This was an npm issue that's now been resolved

https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by jecs-imperial** [comment]
@leandroruel Thanks for the tip! I'd previously installed a later version of node this way but had forgotten to do so when I re-installed node this time to see if that would fix this problem. I'm up to node 8.9 and npm 5.6 again now.

**Comment by jecs-imperial** [comment]
@xzyfer Right, this makes sense. Out of desperation I tried installing each of the dependencies manually, fortunately there weren't too many. A few of them, such as `glob` failed to install although once I was done, installing `node-sass` did actually work. Go figure.

I might as well close this issue, thanks both for the speedy response.
