### ISSUE TITLE
SASS files within same directory not geting mixin without importing, why?

### ISSUE THREAD

**Issue by abhishek-0** [sass/node-sass#2207]
Hi, I'm making an application in angular 5. I've made a common folder for all SASS files, where I've kept all my basic styles like,
mixin.scss,
base.scss
variables.scss
and now I've made one another scss file within same folder and trying to implement one mixin defined in mixin.scss, but it's showing error message "mixin not defined", where as when i import mixin.scss to that new.scss file it works. I've also implemented these mixins in base.scss file where i didn't have to import mixin.scss

Can anyone please explain this to me.?

**Comment by nschonni** [comment]
Hi @abhishek-0 general Sass issues are probably better asked on StackOverflow rather than the bug tracker.
