### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by UX-Unicorn** [sass/node-sass#2212]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v6.9.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Trying to install 4.7.2
- npm node-sass versions (`npm ls node-sass`):

Tyring to install on a machine that cannot access the internet I accidentally downloaded the wrong binary.  During install I got 
Binary found at /data/npm/binaries/binding.node
During post-install I got 
Binary has a problem: Error: Module did not self-register.

I realized my mistake and got the right binary, but I am still getting the same errors.  How do I fix the issue?

**Comment by xzyfer** [comment]
You may still have the broken binary on disk or cache. Delete your
node_modules and npm cache clean
