### ISSUE TITLE
Binary has a problem: Error: Module did not self-register.

### ISSUE THREAD

**Issue by 42shadow42** [sass/node-sass#2213]
Node Version: 8.9.4
NPM Version: 5.6.0
Node Platform: win32
Node Architecture: x64
Node Process: { 
  http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

Installation Logs:
node-sass@4.7.2 install node_modules\node-sass

> node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-57_binding.node
> Download complete  ] - :
> Binary saved to node_modules\node-sass\vendor\win32-x64-57\binding.node
> Caching binary to npm-cache\node-sass\4.7.2\win32-x64-57_binding.node
> 
> node-sass@4.7.2 postinstall node_modules\node-sass
> node scripts/build.js
> 
> Binary found at node_modules\node-sass\vendor\win32-x64-57\binding.node
> Testing binary
> Binary has a problem: Error: Module did not self-register.
>     at Object.Module._extensions..node (module.js:672:18)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>     at Module.require (module.js:587:17)
>     at require (internal/module.js:11:18)
>     at module.exports (node_modules\node-sass\lib\binding.js:19:10)
>     at Object.<anonymous> (node_modules\node-sass\lib\index.js:14:35)
>     at Module._compile (module.js:643:30)
>     at Object.Module._extensions..js (module.js:654:10)
> Building the binary locally

I have already tried the following fixes:
https://github.com/sass/node-sass/issues/2212

**Comment by nschonni** [comment]
Did you delete from `npm-cache\node-sass\4.7.2\win32-x64-57_binding.node` as well as the local node_modules?

**Comment by 42shadow42** [comment]
Yes, I deleted the cache, but there was no local version.

The log indicates it had to download the binary.

**Comment by 42shadow42** [comment]
Despite the clean nodejs installation this appears to be a system issue, I have confirmed that this works on other machines, and that it fails with other C++ node modules.

**Comment by nschonni** [comment]
Thanks for sharing your results @42shadow42 :+1:
