### ISSUE TITLE
background-image url error

### ISSUE THREAD

**Issue by MarkSky** [sass/node-sass#2218]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): 8.9.4
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',  node: '8.9.4',  v8: '6.1.534.50',  uv: '1.15.0',  zlib: '1.2.11',  ares: '1.10.1-DEV',  modules: '57',  nghttp2: '1.25.0',  openssl: '1.0.2n',  icu: '59.1',  unicode: '9.0',  cldr: '31.0.1',  tz: '2017b' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`): -- (empty)

my sass file and css file in different folders.
`node-sass SCSS/main.sass wwwroot/assets/styles/main.css`

```
Project folder
├SCSS
│ └main.sass
└wwwroot
    └assets
        └styles
            └main.css
```
But the background-image url didn't change for the new site, so opening page in browser, I can't see the pics.

How Should I setting for the background-image path? Or it's a bug?

**Comment by xzyfer** [comment]
Sass just compiles to CSS. I doesn't know about url paths. You should code your urls to be relative to the output file.
