### ISSUE TITLE
Can not install node-saas in Ubuntu 16.04

### ISSUE THREAD

**Issue by pranay22** [sass/node-sass#2221]
Can not install node-saas in Ubuntu 16.04

- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): 9.3.0
- Node Process (`node -p process.versions`): http_parser: '2.7.0',
  node: '9.3.0',
  v8: '6.2.414.46-node.15',
  uv: '1.18.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c'
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64

`psarkar@psarkar-pc:~/vue-site2$ npm -g install node-saas
npm ERR! code E404
npm ERR! 404 Not Found: node-saas@latest
`

**Comment by bojake** [comment]
i tried the same and got 404 from the GitHub download of SASS:

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-ia32-14_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-ia32-14_binding.node":

HTTP error 404 Not Found

the "/download/" part of the URL is no longer valid.

**Comment by nschonni** [comment]
@bojake  you issue isn't the same or for the same platform, please open your own issue

**Comment by nschonni** [comment]
@pranay22 please provide the log, there is nothing we can troubleshoot from that one line

**Comment by kohrVid** [comment]
Also getting this error in Debian Stretch

This is the command used followed by the error:

    $ npm -g install node-saas npm
    npm ERR! code E404 
    npm ERR! 404 Not Found: node-saas@latest
                                                                                                                               
    npm ERR! A complete log of this run can be found in: 
    npm ERR!     /home/jessica/.npm/_logs/2018-01-22T13_59_21_162Z-debug.log


The log is as follows:

    0 info it worked if it ends with ok
    1 verbose cli [ '/home/jessica/.nvm/versions/node/v8.9.4/bin/node',
    1 verbose cli   '/home/jessica/.nvm/versions/node/v8.9.4/bin/npm',
    1 verbose cli   '-g',
    1 verbose cli   'install',
    1 verbose cli   'node-saas',
    1 verbose cli   'npm' ]
    2 info using npm@5.6.0
    3 info using node@v8.9.4
    4 verbose npm-session 9c4d720a37b9109f
    5 silly install loadCurrentTree
    6 silly install readGlobalPackageData
    7 http fetch GET 304 https://registry.npmjs.org/npm 117ms (from cache)
    8 silly pacote tag manifest for npm@latest fetched in 152ms
    9 http fetch GET 404 https://registry.npmjs.org/node-saas 1707ms
    10 silly fetchPackageMetaData error for node-saas@latest 404 Not Found: node-saas@latest
    11 verbose stack Error: 404 Not Found: node-saas@latest
    11 verbose stack     at fetch.then.res (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
    11 verbose stack     at tryCatcher (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    11 verbose stack     at Promise._settlePromiseFromHandler (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    11 verbose stack     at Promise._settlePromise (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    11 verbose stack     at Promise._settlePromise0 (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    11 verbose stack     at Promise._settlePromises (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    11 verbose stack     at Async._drainQueue (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
    11 verbose stack     at Async._drainQueues (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
    11 verbose stack     at Immediate.Async.drainQueues (/home/jessica/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    11 verbose stack     at runCallback (timers.js:789:20)
    11 verbose stack     at tryOnImmediate (timers.js:751:5)
    11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
    12 verbose cwd /home/jessica/Documents/projects/orderweb
    13 verbose Linux 4.9.0-5-amd64
    14 verbose argv "/home/jessica/.nvm/versions/node/v8.9.4/bin/node" "/home/jessica/.nvm/versions/node/v8.9.4/bin/npm" "-g" "install" "node-saas" "npm"
    15 verbose node v8.9.4
    16 verbose npm  v5.6.0
    17 error code E404
    18 error 404 Not Found: node-saas@latest
    19 verbose exit [ 1, true ]

**Comment by kohrVid** [comment]
Yes that'll be it (I copy and pasted @pranay22's command into my terminal because his error looked similar to mine)! The issue I had was a little more specific to my setup and I did have to clear my cache at one point but I was able to build the app that depended on this in the end so perhaps this really isn't an issue anymore?

**Comment by xzyfer** [comment]
This package is node-sass not node-saas
