### ISSUE TITLE
ELIFECYCLE Error

### ISSUE THREAD

**Issue by Clickys** [sass/node-sass#2224]
NPM version (npm -v): 5.6.0
Node version (node -v): v9.4.0
Node Process (node -p process.versions): { http_parser: '2.7.0', node: '9.4.0', v8: '6.2.414.46-node.17', uv: '1.18.0', zlib: '1.2.11', ares: '1.13.0', modules: '59', nghttp2: '1.29.0', openssl: '1.0.2n', icu: '60.1', unicode: '10.0', cldr: '32.0', tz: '2017c' }
Node Platform (node -p process.platform): win32
Node architecture (node -p process.arch): x64
node-sass version (node -p "require('node-sass').info"): node-sass 4.7.2 (Wrapper) [JavaScript] libsass 3.5.0.beta.2 (Sass Compiler) [C/C++]
npm node-sass versions (npm ls node-sass): node-sass@4.7.2
The commands i followed to install sass:

npm init
npm install node-sass --save-dev
I edited the package.json and in "scripts" i added "compile:sass": "node-sass myInputSassPath outputCssStyles -w"
npm run compile:sass
And iam getting this error , npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! starter@1.0.0 compile:sass: node-sass sass/main.scss css/style.css -w npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the starter@1.0.0 compile:sass script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\clickys\AppData\Roaming\npm-cache_logs\2018-01-21T11_43_08_053Z-debug.log

The full error is here -> https://gist.github.com/Clickys/c3fcde9ae1099c814b174bd8127fcd49

Yesterday it was working properly without any issue. Iam not sure what happened today. Thank you for your patient.

**Comment by rnprince** [comment]
Hey, I think a lot of people are having this issue, based on the Q&A section of an online class I'm taking, and the fact that I'm having the issue right now. Could you add info on what you did to get around this issue?

Thanks!
