### ISSUE TITLE
Always failed when install node-sass@4.7 on ubuntu 16 in node v8.

### ISSUE THREAD

**Issue by xsmartweb** [sass/node-sass#2226]
When I install node-sass using npm i node-sass, i can lots of errors.

I installed node-gyp , gcc globally , but still remain many many errors.

I saw these errors before when I'm using Angular cli , but it seems node-sass team didn't solve this issues yet.

**Comment by xzyfer** [comment]
Make sure you're installing the latest node-sass with npm update node-sass

**Comment by xsmartweb** [comment]
I tried with npm update node-sass, but not solved issue.

**Comment by ImreC** [comment]
I have the same problem trying to install an app with npm install
Ubuntu 16.04
Node v 9.4.0
npm v5.6.0
node-sass 4.7

**Comment by ImreC** [comment]
update node-sass does not resolve the issue

**Comment by xzyfer** [comment]
Please open a new issue.
