### ISSUE TITLE
When angular compile files, the "0vh" becomes "0"

### ISSUE THREAD

**Issue by Sneko** [sass/node-sass#2231]
Hi,

I'm not sure I'm at the right place... but I don't see where I should post that : 

When my Ionic (Angular) app generates a compiled main.css each value equal to "0vh" will be replaced by "0". And that's a big problem because browsers will invalid the CSS rule including this "0".

For example :
`transform: translate3d(calc(50vw - #{$width / 2} + #{$x}), calc(100vh - #{$height} - #{$y}), $distance * $zUnit);`

If $x was defined as 0vh in SASS, after compilation the first transform param will be:
calc(50vw - 25vh + 0)

and not:
calc(50vw - 25vh + 0vh)

That makes browsers refusing this transform :( 

I know that I could remove $x if I know it equals 0. But the idea is to keep it dynamic because it could change in the future.

If you have any idea, please I would be thankful :)

**Comment by xzyfer** [comment]
An explained in the issue template you deleted that is a LibSass issue.
Please open an issue with LibSass with the exact sass input and brokwn
output.
