### ISSUE TITLE
Running "sass:vendor" (sass) task

### ISSUE THREAD

**Issue by nani118066** [sass/node-sass#2232]
while building the project using mvn clena install I'm getting the below warning and the build is getting failed. Can some one help me how to solve this. Thank you 

Running "sass:vendor" (sass) task
[INFO] Warning: spawn sass ENOENT Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
