### ISSUE TITLE
Warning: spawn sass ENOENT Use --force to continue.

### ISSUE THREAD

**Issue by nani118066** [sass/node-sass#2234]
While building the project using "mvn clean install -PautoInstallPackage" I'm getting the below warning and the build is getting failed. Can some one help me how to solve this. Thank you 

Running "sass:vendor" (sass) task
[INFO] Warning: spawn sass ENOENT Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.

Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:grunt (grunt build) on project application: Failed to run task: 'grunt build' failed. (error code 6)

My environment is as below:

- NPM version (`npm -v`): 5.6.0

- Node version (`node -v`): 8.9.4

- Node Process (`node -p process.versions`): { http_parser: '2.7.0', node: '8.9.4', v8: '6.1.534.50', uv: '1.15.0', zlib: '1.2.11', ares: '1.10.1-DEV', modules: '57', nghttp2: '1.25.0', openssl: '1.0.2n', icu: '59.1', unicode: '9.0', cldr: '31.0.1', tz: '2017b' }

- Node Platform (`node -p process.platform`): darwin

- Node architecture (`node -p process.arch`): x64

- node-sass version (`node -p "require('node-sass').info"`): 
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]

- npm node-sass versions (`npm ls node-sass`):
rco@1.0.0 /Users/username/Documents/project_folder
└── node-sass@4.7.2

**Comment by nschonni** [comment]
Thanks for providing the extra information @nani118066 ! Unfortunatly that indicates that node-sass has installed correctly and that your issue is likely coming from from your Grunt config having a bad file reference somewhere
https://duckduckgo.com/?q=ENOENT&t=ffcm&ia=about

**Comment by saper** [comment]
Please make sure the maven project is not trying to start "sass" from the command line, which is Ruby Sass.

**Comment by nani118066** [comment]
I did $sudo uninstall sass & $sudo install compass. Then the build worked.
