### ISSUE TITLE
Node-sass install error in AWS ubuntu server

### ISSUE THREAD

**Issue by xsmartweb** [sass/node-sass#2235]
I installed already build-essential, and node-gyp globally .

But when I try to install node-sass, I'm always failed.

I can see node-gyp failed errors in console.
I tried many times to find correct answer, but didn't find solution even though I can see many similar issues. 

I think node-sass team should provide guide for this .
before I opened several issues related with this, but node-sass team closed all without correct answer, and not checked  comment.

**Comment by xzyfer** [comment]
When you ignore the issue template we don't have enough information to help. Please open an issue with the information we have requested.
