### ISSUE TITLE
pass directory to render/rendersync

### ISSUE THREAD

**Issue by z1haze** [sass/node-sass#2241]
Why is there no possible way to pass a input file directory to node-sass with using the javascript api? It doesnt make sense that you can only pass a input directory via command line, but you HAVE to pass a file when using the script API. please do something about this, we can can bring our node-sass task into a separate script.

**Comment by xzyfer** [comment]
> It doesnt make sense

It makes perfect sense. Node Sass *only* turns a single input file into a single output file. Full stop.

> you can only pass a input directory via command line

You can only pass an input directory when using `--watch`. In this case Node Sass watches the whole directory for changes, and compiles the changed files one at a time.

***

Compiling a whole directory is a feature we could consider for [version 5][1]

[1]: https://github.com/sass/node-sass/issues/2111

**Comment by z1haze** [comment]
So why can we not use watch from the JavaScript all then. It still doesn't make sense that you have functionally in the cli that, isnt doable from the script api.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Michael Mifsud <notifications@github.com> Date: 2/4/18  10:48 PM  (GMT-05:00) To: sass/node-sass <node-sass@noreply.github.com> Cc: Stephen Hendricks <stephen.hendricks87@gmail.com>, Author <author@noreply.github.com> Subject: Re: [sass/node-sass] pass directory to render/rendersync (#2241) 

It doesnt make sense

It makes perfect sense. Node Sass only turns a single input file into a single output file. Full stop.

you can only pass a input directory via command line

You can only pass an input directory when using --watch. In this case Node Sass watches the whole directory for changes, and compiles the changed files one at a time.

Compiling a whole directory is a feature we could consider for version 5

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sass/node-sass","title":"sass/node-sass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sass/node-sass"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xzyfer in #2241: \u003e It doesnt make sense\r\n\r\nIt makes perfect sense. Node Sass *only* turns a single input file into a single output file. Full stop.\r\n\r\n\u003e you can only pass a input directory via command line\r\n\r\nYou can only pass an input directory when using `--watch`. In this case Node Sass watches the whole directory for changes, and compiles the changed files one at a time.\r\n\r\n***\r\n\r\nCompiling a whole directory is a feature we could consider for [version 5][1]\r\n\r\n[1]: https://github.com/sass/node-sass/issues/2111"}],"action":{"name":"View Issue","url":"https://github.com/sass/node-sass/issues/2241#issuecomment-362974616"}}}
