### ISSUE TITLE
2018 has come. Will it be far away in 2020? When will it be upgraded to python3

### ISSUE THREAD

**Issue by ncc0706** [sass/node-sass#2242]

**Comment by xzyfer** [comment]
The python requirements is a dependency of node-gyp. Take your complaints there.

**Comment by gabefair** [comment]
You can bypass this by not using the package nom recommends:
`npm explore npm -g -- npm install node-gyp@latest`
and then
`npm explore npm -g -- npm install node-sass@latest`
