### ISSUE TITLE
Error: Cannot find module 'boom' -- when trying to install

### ISSUE THREAD

**Issue by aryzing** [sass/node-sass#2243]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v9.3.0
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.7.0',
  node: '9.3.0',
  v8: '6.2.414.46-node.15',
  uv: '1.18.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.2',
  unicode: '10.0',
  cldr: '32.0.1',
  tz: '2017c' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.7.2
- npm node-sass versions (`npm ls node-sass`): 4.7.2

# Error

When attempting to install with yarn, the following error is thrown:

```
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/eduard.bardaji/Downloads/test/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

**Comment by xzyfer** [comment]
Try npm update node-sass

**Comment by aryzing** [comment]
For some reason, it was failing with yarn. With `npm i` it installed just fine

**Comment by davewasmer** [comment]
FWIW, seeing the same on CI, using yarn. Should we reopen?

**Comment by xzyfer** [comment]
There's nothing node-sass can do. Sounds like an npm issue. It looks like the package is available. Maybe try clearing your npm/yarn caches.

```
npm info boom
```

**Comment by Cinamonas** [comment]
Had the same issue on a clean CI machine (no cache). As a temporary workaround, switching from Yarn 1.3.2 to 0.28.4 solves the issue.

**Comment by athergeek** [comment]
I explicitly had to do 'npm install boom' and it worked for me.
