### ISSUE TITLE
Unable to use relative path in sass_binary_path

### ISSUE THREAD

**Issue by HeavenlyHost** [sass/node-sass#2246]
linked to issue 2081 [here](https://github.com/sass/node-sass/issues/2081)

I am having the same issue using local .npmrc file on Windows and relative path,

sass_binary_path=".\binaries\win32-x64-51_binding.node"

reports that "Cannot find module 'binaries/win32-x64-51_binding.node'"

**Comment by nschonni** [comment]
As the other issue mentioned, it's not supported
