### ISSUE TITLE
Can't install node-sass, it says not found. Can anyone help please..

### ISSUE THREAD

**Issue by Ahmdrza** [sass/node-sass#2249]
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\ahmdrza_w\node2\chapter-01\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Manager PKteam\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\Manager PKteam\.windows-build-tools\python27\python.exe C:\Users\Manager PKteam\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\Manager PKteam\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.2.0
gyp verb command install [ '9.2.0' ]
gyp verb install input version string "9.2.0"
gyp verb install installing version: 9.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.2.0
gyp verb build dir attempting to create "build" dir: E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Manager PKteam\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-sass-middleware\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Manager PKteam\\.node-gyp\\9.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Manager PKteam\\.node-gyp\\9.2.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Manager PKteam\\.node-gyp\\9.2.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-sass-middleware\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-sass-middleware\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Manager PKteam\.node-gyp\9.2.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 2/12/2018 10:24:50 AM.
Project "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.sln" (1) is building "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.
Done Building Project "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.
Done Building Project "E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
  E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.05
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\ahmdrza_w\node2\chapter-01\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\ahmdrza_w\\node2\\chapter-01\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\ahmdrza_w\node2\chapter-01\node_modules\node-sass-middleware\node_modules\node-sass
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by xzyfer** [comment]
v3.13.1 is very old and only supports Node 0.10 or Node 0.12. You need to upgrade to 4.7.2.

```
npm install node-sass@latest
```

**Comment by Ahmdrza** [comment]
i used node-sass:'^4.7.2' in package.json, but it was downloading 3.13.1 by default. i downloaded 4.7.2, and it downloaded fine, but why it was downloading 3.13.1 when i mentioned 4.7.2 in package.json???

**Comment by xzyfer** [comment]
You must have a dependency that depends on an older version. You can see that with `npm ls node-sass`

**Comment by Ahmdrza** [comment]
this is what i get 
+-- node-sass@4.7.2
`-- node-sass-middleware@0.9.8
  `-- node-sass@3.13.1

**Comment by xzyfer** [comment]
Correct. You have two versions of node-sass. You're using an old version of
node-sass-middleware which uses an old version of node-sass. Update
node-sass-middleware to latest
