### ISSUE TITLE
Download fails using SASS_BINARY_SITE but downloads using dist-url

### ISSUE THREAD

**Issue by reggi** [sass/node-sass#2250]
I am trying to install an older version of sass `v3.4.1` and I have set the proper version of node `v4.2.4` and I have the following global variables set. 

```
export NODEJS_ORG_MIRROR=<private-cdn-url>/nodejs/content/sites/npm-remotes/content-compressed/
export SASS_BINARY_SITE=<private-cdn-url>/nodejs/content/sites/npm-remotes/sass/node-sass/releases/download
```

Here's the output

```
> node-sass@3.4.1 install ...

Cannot download "<private-cdn-url>/nodejs/content/sites/npm-remotes/sass/node-sass/releases/download/v3.4.1/darwin-x64-46_binding.node":

tunneling socket could not be established, cause=Parse Error

gyp verb download using dist-url <private-cdn-url>/nodejs/content/sites/npm-remotes/content-compressed/
```

Here is the node versions

```
✗ node -v
v4.2.4
✗ npm -v
2.14.12
```

The install is successful. I am wondering how I can suppress the "Cannot download" message. Why it has to check the first URL then get the `dist-url`.

**Comment by reggi** [comment]
@xzyfer I can't due to breaking changes. Is it possible if I added a PR to 3.4.1 that we could release a 3.4.1 with proxy support? Or is that nuts?

**Comment by xzyfer** [comment]
Out of curiosity what breaking changes are blocking you? I'd rather enabled
you to roll forward
