### ISSUE TITLE
node.js 8.9.3 incompatible node-sass4.7.2

### ISSUE THREAD

**Issue by javaLuo** [sass/node-sass#2254]
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
 - Windows 64-bit with Node.js 6.x

if node-sass can not work on Node.js 8.x , I have no chose but to use Less, because less is working.

**Comment by xzyfer** [comment]
Delete your node_modules folder and run npm install
