### ISSUE TITLE
Update request version to 2.83.0

### ISSUE THREAD

**Issue by YusirahW** [sass/node-sass#2257]
Ran a nsp check and found that there's a vulnerability of prototype pollution attack related to the version of _hoek_. from other threads and updating _request_ this issue has been fixed. Just needs _request_ dependency to update its version dependency.

name: hoek
node-sass@4.7.2 > request@2.79.0 > hawk@3.1.3 > hoek@2.16.3 

https://nodesecurity.io/advisories/566
https://hackerone.com/reports/310439

**Comment by xzyfer** [comment]
Duplicate of #2170 #2256
