### ISSUE TITLE
add quiet as non-cli option?

### ISSUE THREAD

**Issue by selfagency** [sass/node-sass#2265]
i use [grunt-sass](https://github.com/sindresorhus/grunt-sass) which implements node-sass. i know that node-sass offers a `quiet` option, but when i pass `{"quiet": true}` as an option, i continue to get debug warnings during compilation. i believe this is because `quiet` is not actually implemented as an option outside the cli. that being the case, it would be wonderful if you could pass `quiet` as an option when instantiating node-sass. please consider implementing this enhancement.

thanks!

**Comment by xzyfer** [comment]
The quiet flag only quiets CLI output. I'm not sure what you'd expect it to do via the Node API.

There is no way to quiet `@debug` and `@warning` in either the CLI or Node API.

**Comment by selfagency** [comment]
um, is grunt not a cli application?

**Comment by xzyfer** [comment]
Node Sass is split into two parts, the CLI and the Node API. The CLI has a quiet option for informational output from the CLI. The Node API has not output that can be quieted.

`@debug` and `@warn` are part of the Sass language, they cannot be turned off.
