### ISSUE TITLE
Grunt-sass error

### ISSUE THREAD

**Issue by naveenlb** [sass/node-sass#2266]
Hi all,

When I run the command "grunt watch" it was running properly before, but I installed slickJS npm then I started getting the error 

 Local Npm module "grunt-sass" not found. Is it installed?

Then I tried installing using the command : npm install grunt-sass

>  node-sass@3.13.1 install C:\xampp\htdocs\feedprojects\docroot\sites\all\themes                                                                                                                                                                                               \feed\born\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.1                                                                                                                                                                                               3.1/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win                                                                                                                                                                                               32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\xampp\htdocs\feedprojects\docroot\sites\all\th                                                                                                                                                                                               emes\feed\born\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\feedprojects\docroot\                                                                                                                                                                                               sites\all\themes\feed\born\node_modules\node-gyp\bin\node-gyp.js rebuild --verbo                                                                                                                                                                                               se --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\feedprojects\\docroot\\sites\\all\\themes\\fe                                                                                                                                                                                               ed\\born\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\xampp\htdocs\feedprojects\docroot\sites\all\th                                                                                                                                                                                               emes\feed\born\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at F (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\xampp\htdocs\feedprojects\docroot\sites\all\th                                                                                                                                                                                               emes\feed\born\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at F (C:\\xampp                                                                                                                                                                                               \\htdocs\\feedprojects\\docroot\\sites\\all\\themes\\feed\\born\\node_modules\\w                                                                                                                                                                                               hich\\which.js:40:28)\n    at E (C:\\xampp\\htdocs\\feedprojects\\docroot\\sites                                                                                                                                                                                               \\all\\themes\\feed\\born\\node_modules\\which\\which.js:43:29)\n    at C:\\xamp                                                                                                                                                                                               p\\htdocs\\feedprojects\\docroot\\sites\\all\\themes\\feed\\born\\node_modules\\                                                                                                                                                                                               which\\which.js:54:16\n    at FSReqWrap.oncomplete (fs.js:166:21)' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\xampp\htdocs\feedprojects\docroot\sites\all\th                                                                                                                                                                                               emes\feed\born\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at F (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\xampp\htdocs\feedprojects\docroot\sites\all                                                                                                                                                                                               \themes\feed\born\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\xampp\htdocs\feedprojects\docroot\sites\all\th                                                                                                                                                                                               emes\feed\born\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at F (C:\\xampp\                                                                                                                                                                                               \htdocs\\feedprojects\\docroot\\sites\\all\\themes\\feed\\born\\node_modules\\wh                                                                                                                                                                                               ich\\which.js:40:28)\n    at E (C:\\xampp\\htdocs\\feedprojects\\docroot\\sites\                                                                                                                                                                                               \all\\themes\\feed\\born\\node_modules\\which\\which.js:43:29)\n    at C:\\xampp                                                                                                                                                                                               \\htdocs\\feedprojects\\docroot\\sites\\all\\themes\\feed\\born\\node_modules\\w                                                                                                                                                                                               hich\\which.js:54:16\n    at FSReqWrap.oncomplete (fs.js:166:21)' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT                                                                                                                                                                                               HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\xampp\htdocs\feedprojects\do                                                                                                                                                                                               croot\sites\all\themes\feed\born\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\xampp\htdocs\feedprojects\doc                                                                                                                                                                                               root\sites\all\themes\feed\born\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\xampp\htdocs\feedprojects\docroot\sites\all\themes\feed                                                                                                                                                                                               \born\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\feedp                                                                                                                                                                                               rojects\\docroot\\sites\\all\\themes\\feed\\born\\node_modules\\node-gyp\\bin\\n                                                                                                                                                                                               ode-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsas                                                                                                                                                                                               s_ldflags=" "--libsass_library="
gyp ERR! cwd C:\xampp\htdocs\feedprojects\docroot\sites\all\themes\feed\born\nod                                                                                                                                                                                               e_modules\node-sass
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is inst                                                                                                                                                                                               alled. You must install peer dependencies yourself.
npm WARN born No description
npm WARN born No repository field.
npm WARN born No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                                                               ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\naveen.bhandari\AppData\Roaming\npm-cache\_logs\2018-03-03                                                                                                                                                                                               T08_59_20_829Z-debug.log

I see that the link from github is not working when I try to open in a new tab, looks like file is not available now. Please let me know how I can fix this error.

**Comment by nschonni** [comment]
3.13.1 is very old and doesn't support Node 9, please upgrade your node-sass (by upgrading your grunt-sass version) or downgrade your node version to a supported version as indicated on the 3.13.1 release page
