### ISSUE TITLE
error: missing binding

### ISSUE THREAD

**Issue by gustis40g** [sass/node-sass#2267]
I know i'm retarded,
Error: missing binding
.......\node_modules\node-sass\binding.node
Node Sass could not find a binding for your current environment: windows 32-bit with electron 1.6
found bindings for the following environments:
-Windows 54 bit with node.js 9x
........

This happen after i rebuilded all my modules
I didn't update node.js i didn't do anything really but to rebuild my modules
I tried re installing all modules via the package.json i have
I cant find anything on the internet neather
I tried to rebuild the modules again
My system: 64-bit Windows 10
Node.js: 9.7.1
This worked yesterday
![skarmklipp](https://user-images.githubusercontent.com/35926005/36937526-1c85b148-1f15-11e8-84c2-7c11a4718348.PNG)

**Comment by saper** [comment]
You are mixing two environments with two different node engines. 

Your situation is very similar to this one described in our documentation:

https://github.com/sass/node-sass/blob/abbc65770ea6f16d2591cfc8046021301ed29d2d/TROUBLESHOOTING.md#using-node-sass-with-visual-studio-2015-task-runner
