### ISSUE TITLE
custom importer output is not used after first import 

### ISSUE THREAD

**Issue by shukriadams** [sass/node-sass#2272]
I've written a custom import handler function to manage some Sass modules. The importer checks which file is doing the import, reads some metadata (not shown) to do a semver match for the best file to satisfy the import, then returns that file, a bit like :
    
    a.scss
    >import 'common';        (expects and gets common.scss version 1.0.0)
    >import 'b'; 

    b.scss
    > import 'common';        (expects common.scss version 2.0.0, gets 1.0.0)

If a given name like 'common' is imported more than once, Sass ignores the output of the import function on calls after the first, that is to say, it seems to caching and reusing 'common' from the first import, and I cannot have more than one version of a given name in a single compile context. Is this by design? Can it be disabled?

**Comment by xzyfer** [comment]
This is the intended behaviour. As you have guessed there is an importer cache. Only the first instance of a unique `@import` is resolved.

LibSass expects custom importers to be stateless. @nex3 can you please confirm whether this is the expected behaviour of custom importers?

**Comment by shukriadams** [comment]
@xzyfer Makes sense. I'm guessing this is a limitation imposed by Sass' simple file-based import model - a file's content should be static, so no need to resolve it twice. It's tempting to build a pseudo module importer by resolving a simple name to a file, but it doesn't really work if everything's being concatenated into the same scope before compilation. Thanks for your time - I realize my request wouldn't work in the end anyway.

**Comment by nex3** [comment]
@xzyfer That's right. Dart Sass does the same thing.

**Comment by xzyfer** [comment]
@nex3 thanks for the clarification
