### ISSUE TITLE
no suitable image found

### ISSUE THREAD

**Issue by iGalaxyz** [sass/node-sass#2277]
here is the error log
https://pastebin.ubuntu.com/p/Mwpjvb4y4V/

refer to the Line4 and https://github.com/sass/node-sass/releases/
there is no `darwin-x64-59_binding.node`, please fix this, thanks.

- NPM version (`npm -v`): 9.8.0
- Node version (`node -v`): 5.6.0
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0',
  node: '9.8.0',
  v8: '6.2.414.46-node.21',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '2',
  openssl: '1.0.2n',
  icu: '60.2',
  unicode: '10.0',
  cldr: '32.0.1',
  tz: '2017c' }`
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): --
- npm node-sass versions (`npm ls node-sass`): 4.8.0

**Comment by iGalaxyz** [comment]
I saw the `darwin-x64-59_binding.node` on the bottom just now, and I replace the same file in  `~/.npm/node-sass/4.8.0`, everything goes well.

**Comment by nschonni** [comment]
Thanks, there was an issue with the download code and it was removed from NPM. #2276 should fix it and be published as 4.8.1
Your workaround is correct though
