### ISSUE TITLE
Missing release v4.8.1/linux-x64-51_binding.node

### ISSUE THREAD

**Issue by stasusov** [sass/node-sass#2278]
Today I run a build on the server and got the error because the necessary build is missing (v4.8.1/linux-x64-51_binding.node).

Somewhere in Angular dependencies `node-sass` is requested with `latest` version, so the 4.8.1 is found, but release for that setup was not found:

> npm info addNameTag [ 'node-sass', 'latest' ]
> ...
> npm http fetch GET https://registry.npmjs.org/node-sass/-/node-sass-4.8.1.tgz
> npm http fetch 200 https://registry.npmjs.org/node-sass/-/node-sass-4.8.1.tgz
> ...
> npm info lifecycle node-sass@4.8.1~install: node-sass@4.8.1
> 
> node-sass@4.8.1 install /app/node_modules/node-sass
> node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.1/linux-x64-51_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.1/linux-x64-51_binding.node": 
> 
> HTTP error 404 Not Found

Could you please clarify why is this release missing and can there be some fix for this situation from your side? For example, previous v4.7.2 may be used.

- NPM version (`npm -v`): 4.2.0
- Node version (`node -v`): v7.10.1
_Sorry, but I can't provide you with the information below, because failed `npm i` was run in the container on the server and I can't get access to it._
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by nschonni** [comment]
@xzyfer Node 7 is still listed as supported on https://github.com/sass/node-sass/releases/tag/v4.8.1
Was this still being worked out with CentOS builds?

@stasusov Thanks for pointing it out. FYI, Node 7 will be dropped in the next release since it is EOL.

**Comment by xzyfer** [comment]
Apologies this is a mistake in the build script. Building the Node 7 binary now.

**Comment by xzyfer** [comment]
The missing Node 7 binaries have been added.

**Comment by ehdwns980416** [comment]
@xzyfer The same situation is repeated now. Please check.
```
> node-sass@4.8.1 install /builds/rscg/pottokids-webadmin/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.1/linux_musl-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.1/linux_musl-x64-57_binding.node": 

HTTP error 404 Not Found
```

**Comment by xzyfer** [comment]
@ehdwns980416 unfortunately [Node 7 is end-of-life](https://github.com/nodejs/Release#nodejs-release-working-group). As a result an up to date [official Alpine image](https://hub.docker.com/_/node/) is no long available. This prevented up building Node 7 binaries for Alpine as reflected in the [support table in the release notes](https://github.com/sass/node-sass/releases).

**Comment by xzyfer** [comment]
@ehdwns980416 I've done some digging and looks like I can build the Node 7 Alpine binary. It'll be uploaded in about 10 mins.

**Comment by ehdwns980416** [comment]
@xzyfer Thanks for it! 👍

**Comment by xzyfer** [comment]
Keep in mind Node 7 is EOL. We'll be forced to stop supporting it in Node Sass v5. I suggest upgrading to LTS or current release.

**Comment by ehdwns980416** [comment]
Thanks for the good information. 👋

**Comment by xzyfer** [comment]
The Node 7 Alpine binary is live now.

**Comment by ehdwns980416** [comment]
Ok. I'll try again. Thanks for your help.
