### ISSUE TITLE
How to lock/pin libsass with node-sass to avoid breaking changes?

### ISSUE THREAD

**Issue by jacobq** [sass/node-sass#2282]
The following used to be fine (=compiled without complaint even though the resultant CSS was not valid):
```sass
:not('.some-class') {
    display: block;
}
```

However, now quoting a selector like this generates an error.
For example, the input `:not('div') {}` results in the following:
```
Error: Invalid CSS after ":not(": expected selector, was "'div') {}"
        on line 1 of stdin
>> :not('div') {}

   ^
```
(shell hack to see this for yourself: `echo ":not('div') {}"|node-sass 2>&1|xargs -0 node -e "console.log(JSON.parse(process.argv.slice(1).join('')).formatted)"`)

[sassmeister.com](https://www.sassmeister.com/) shows the error when using SASS v3.4.21 but not with v3.3.14, so it seems like this was caused by a change in LibSass, not node-sass. Also, I realize this [is not valid](https://jsbin.com/feqemiq/edit?html,css,output) (and am a little embarrassed at my styling ignorance). However, this leaves me with a few questions:

* **How can I insulate a project against a "breaking" change like this?** (Before the change, some invalid CSS got injected into the project, which was no big deal, but after the change the compilation process failed causing major disruption to developers not aware of the invalid SASS/CSS that had been lying in a  forgotten corner of the app for ages.). I am using yarn with a lockfile for my project and tried checking out an older (known working) commit and re-building, but it failed because of the quoted-selector problem mentioned above. Obviously I've now addressed the SassCompiler error message and it's working again, but I would have much preferred to encounter this during an upgrade.
* Where can I find a LibSass changelog? Would the [release notes](https://github.com/sass/libsass/releases) be the most appropriate place? (Maybe this is related to https://github.com/sass/libsass/issues/2082 ?)

### Extra info (though not believed to be relevant here)
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v8.10.0
- Node Process (`node -p process.versions`):
```
{
  http_parser: '2.7.0',
  node: '8.10.0',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c'
}
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
```
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): `node-sass@4.7.2`

**Comment by xzyfer** [comment]
Please see https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9.

tl:dr; if your code is invalid Sass it is impossible to offer semver guarantees.

**Comment by jacobq** [comment]
@xzyfer I understand there are no semver guarantees in that case. However, is it not possible to lock code to a specific version of a dependency?

**Comment by xzyfer** [comment]
In npm 5 you get dependency tree pinning by default. Alternatively if you
depend directly on node-sass you can use a more restrictive server range
prefix (~ instead of ^) or just lock to specific version by removing the
range prefix.

**Comment by jacobq** [comment]
@xzyfer Thanks for your response.

I am familiar with `package-lock.json` and `yarn.lock`, which is why I filed this issue (thinking that `node-sass` was doing something with libsass that was outside the scope of these somehow). Your response suggested otherwise, so I dug a bit deeper. It turns out that although I had `node-sass` locked via yarn, the build pipeline for my app was using [`broccoli-sass-source-maps`](https://github.com/aexmachina/broccoli-sass-source-maps) without [configuring it to use the local `node-sass` version](https://github.com/aexmachina/broccoli-sass-source-maps#choosing-the-version-of-node-sass). I'm glad to now know where this needed to be set in my case.
