### ISSUE TITLE
include-path not working since v4.8.0

### ISSUE THREAD

**Issue by vhkrausser** [sass/node-sass#2287]
We are working with node-sass using it in package.json as "^4.5.3". On new installations we notice that the build process wasn't able to find one file anymore. This file is imported and found in a folder that we pass as `--include-path` to the compilation process (through webpack's `sass-loader`).

After some research I noticed that the `--include-path` option works until version 4.7.2. And from 4.8.0 it returns that is unable to find the imported file.

I've created a repository https://github.com/vhkrausser/node-sass-test that has the minimum structure to reproduce the problem and instructions

I'm posting this here but I couldn't be sure if the problem is at node-sass or libsass. Sorry if I'm at the wrong place.

- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v8.9.4
- Node Process (`node -p process.versions`):{ http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.8.2   (Wrapper)       [JavaScript]
libsass         3.5.1   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):  node-sass@4.8.2

**Comment by xzyfer** [comment]
We have identified the issue in LibSass https://github.com/sass/libsass/issues/2588.

The work around for now is to not use `./` or `../` in include paths.
