### ISSUE TITLE
Improper css in node-sass/test/fixtures/precision/index.scss

### ISSUE THREAD

**Issue by dlxu** [sass/node-sass#2289]
- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

Not sure if it is a real issue, but please take a look

in File node-sass/test/fixtures/precision/index.scss,  node-sass/test/fixtures/precision/expected.css
the `margin: 1.23456789 px;` should be ` margin: 1.23456789px; `, there is an extra space.

**Comment by xzyfer** [comment]
Thanks for the report. This is not problem however.
