### ISSUE TITLE
Latest release v4.8.1 not published

### ISSUE THREAD

**Issue by awendt** [sass/node-sass#2301]
I'm trying to install 4.8.1, it's the [latest release](https://github.com/sass/node-sass/releases/tag/v4.8.1) here on Github but https://yarnpkg.com/en/package/node-sass still lists:

- latest: 4.7.2
- next: 4.8.3

Can you please publish 4.8.1?

**Comment by xzyfer** [comment]
4.8.1 is broken. 4.7.2 is the latest stable. 4.8.2 is the latest unstable
