### ISSUE TITLE
gulp local sass

### ISSUE THREAD

**Issue by deepti2511** [sass/node-sass#2303]
Hi,

When I run gulp local it is taking me an hour to run the command. It is getting stuck at the sass for a long time.
I have attached the image below

- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`):6.11.5
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.11.5',
  v8: '5.1.281.108',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2l' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`): `-- (empty)
npm ERR! code 1
<img width="326" alt="capture" src="https://user-images.githubusercontent.com/37667623/37784054-fbd46070-2dc4-11e8-821b-b66806e9ef47.PNG">

**Comment by xzyfer** [comment]
There's not much we can do.

A. I don't know what gulp local sass is
B. The output of the node sass version commands suggests you don't even
have node sass installed.
