### ISSUE TITLE
[Question] Why is using a non-existing directive doesn't throw an error

### ISSUE THREAD

**Issue by ericmorand** [sass/node-sass#2306]
Consider the following SASS source:

```
.foo {
    @foo bar();
}
```

I'm using here a directive that is not supported by the language. For some reason compiling this source doesn't throw an error using node-sass@4.8.3.

Is this by design?

**Comment by xzyfer** [comment]
Yes. CSS allows for any valid identifier for follow an `@`.

**Comment by ericmorand** [comment]
@xzyfer, thanks for the clarification.
