### ISSUE TITLE
Can not download  node-sass (ppc64le)

### ISSUE THREAD

**Issue by QxiaoQ** [sass/node-sass#2311]
When I run npm install in **Ubantu 14.04.1 LTS Linux**  .There is an error says it can not find this package and then It runs postinstall to build itself. Is there a work around solution to support my **ppc64le**?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/31646170/38227576-6cd6c2d4-3731-11e8-8eb0-a0df9b4526d0.png">

**Comment by xzyfer** [comment]
Node sass < 4 is very old and no longer supported. Additionally we don't
currently support ppc.

**Comment by xzyfer** [comment]
You can upgrade to 4.8.3 and try running `npm rebuild node-sass --force` to try a local compilation of node-sass.
