### ISSUE TITLE
Failed at the node-sass@4.7.2 postinstall script.

### ISSUE THREAD

**Issue by loki4u** [sass/node-sass#2314]
**when i run "sudo ionic start App_name blank" in mac terminal i'm getting following error.
OS:Mac siera**

> node-sass@4.7.2 install /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/8.9.2/bin/node /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/8.9.2/bin/node',
gyp verb cli   '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.2
gyp verb command install [ '8.9.2' ]
gyp verb install input version string "8.9.2"
gyp verb install installing version: 8.9.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.2
gyp verb build dir attempting to create "build" dir: /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.9.2/bin/node" "/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pro/.npm/_logs/2017-12-17T05_45_04_299Z-debug.log

**Comment by saper** [comment]
You have no permission to write to `/Users/pro/Dcolsay/Agency/Develop/Dcolsay/food/node_modules/node-sass/vendor/darwin-x64-57`, because you have started a whole thing as `root` (under `sudo`).

Do not use sudo for this and you should be fine.

**Comment by loki4u** [comment]
@saper i installed the ionic with sudo. when i tried to create an app i have to use following command right **sudo ionic start Test blank**?
