### ISSUE TITLE
Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by srjkrl20011991** [sass/node-sass#2315]
npm install node-sass --save

> node-sass@4.8.3 install D:\Demo\Angular4\templates\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-57_binding.node":

getaddrinfo EAI_AGAIN github.com:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.8.3 postinstall D:\Demo\Angular4\templates\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\Demo\Angular4\templates\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Demo\\Angular4\\templates\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Demo\Angular4\templates\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Demo\Angular4\templates\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Demo\Angular4\templates\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Demo\Angular4\templates\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Demo\Angular4\templates\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Demo\Angular4\templates\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:13:12)\n    at F
(D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:80:29)\n    at D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:89:16\n    at D:\\Demo\\Angular4\\templates\\node_modules\\isexe\\index.js:42:5\n    at D:\\Demo\\Angular4\\templates\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\Demo\Angular4\templates\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Demo\Angular4\templates\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Demo\Angular4\templates\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\Demo\Angular4\templates\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Demo\Angular4\templates\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Demo\Angular4\templates\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Demo\Angular4\templates\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:13:12)\n    at F (D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:80:29)\n    at D:\\Demo\\Angular4\\templates\\node_modules\\which\\which.js:89:16\n    at D:\\Demo\\Angular4\\templates\\node_modules\\isexe\\index.js:42:5\n    at D:\\Demo\\Angular4\\templates\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Demo\Angular4\templates\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Demo\Angular4\templates\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\Demo\Angular4\templates\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Demo\\Angular4\\templates\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Demo\Angular4\templates\node_modules\node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.8.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\suraj.karale\AppData\Roaming\npm-cache\_logs\2018-04-04T09_10_51_713Z-debug.log

**Comment by srjkrl20011991** [comment]
ng serve

ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Demo\Angular4\templates\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:173:18
ERROR in ./src/app/app.component.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Demo\Angular4\templates\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\Demo\Angular4\templates\node_modules\loader-runner\lib\LoaderRunner.js:173:18

**Comment by xzyfer** [comment]
Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080

**Comment by srjkrl20011991** [comment]
can you suggest any proxy addess for npm?

**Comment by xzyfer** [comment]
You'll have to check with your network admin about what your proxy settings
are.

**Comment by massina** [comment]
I have the same problem!. What is the problem with node-sass@4.9.2? Why is can't be downloaded like any other packages?
Please, can anyone explain this to me?

**Comment by MrPeker** [comment]
I have the same problem!

**Comment by Cubxity** [comment]
I have this same problem, Github is accessible in my location tho
