### ISSUE TITLE
Missing binary for 4.8.3

### ISSUE THREAD

**Issue by rafaaugusto22** [sass/node-sass#2319]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/linux-x64-57_binding.node":

My node:
 node -p process.versions
{ http_parser: '2.7.0',
  node: '8.10.0',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

**Comment by nschonni** [comment]
That file exists, so you've likely got a network issue on your end.
Check your install log since it will tell you how to fix it if you're hitting proxy issues.
