### ISSUE TITLE
Download binary v4.5.3

### ISSUE THREAD

**Issue by alex986** [sass/node-sass#2320]
binary https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node

Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall /root/pabis-fe/node_modules/node-sass
> node scripts/build.js

**Comment by alex986** [comment]
And this binary same https://github.com/sass/node-sass/releases/download/v3.10.1/linux-x64-59_binding.node

**Comment by coryzibell** [comment]
Got this too for https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node

**Comment by xzyfer** [comment]
These versions of node-sass are very old and unsupported. You'll newer
node-sass versions to support Node >= 4.

Each modern release has a Node version compatibility chart e.g.
https://github.com/sass/node-sass/releases/tag/v4.8.3

**Comment by coryzibell** [comment]
So the releases were deleted from the github history? I'm confused, as other very close versions still exist: https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-11_binding.node

I believe this issue should be re-opened, as it appears that very specific binary versions are missing from the history, that countless projects across NPM are referencing and depend on.

**Comment by alex986** [comment]
I use node-sass@4.8.3 and the browser send this error 
![image](https://user-images.githubusercontent.com/5686138/38337717-2b66e71a-382c-11e8-8f1c-221a92ec0f48.png)

**Comment by alex986** [comment]
yes is a build tool, but when I use that version, send this error. In the other version this tool compile correct
