### ISSUE TITLE
node-sass-prebuilt for Node 8x

### ISSUE THREAD

**Issue by kpaxton** [sass/node-sass#2321]
I am making use of the Angular-CLI tool which depends on node-sass. However, I am on a closed network and don't have access to github for the install to download a pre-compiled binary. So the next step it takes is to try and build the binary from node sources. Well I don't have access to those either. 

When I was on Node 6.x I was able to work around it with the node-sass-prebuilt npm package that it seems you used to publish. Is there any chance you can update that package with compatible binaries for Node 8.x?

- NPM version (`npm -v`): 5.x
- Node version (`node -v`): 8.x
- Node platform: linux
- Node arch: x64
- npm node-sass versions (`npm ls node-sass`): 4.7.2

**Comment by xzyfer** [comment]
We do not publish node-sass-prebuilt. Generally speaking we recommend against using other packages to download our binaries as they could tampered with.

We offer [many ways to configure the binary discovery][1] that should account for just about any use case.


[1]: https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by kpaxton** [comment]
@xzyfer I was previously making use of those configuration options when using the prebuilt package. I do not have access to any internet address that has the binaries so I cannot use any of the other configuration properties.

**Comment by xzyfer** [comment]
We recommend mirroring the binaries at a network accessible web address or filesystem. You can use those configurations for point at the new location.

Aside from that there is nothing we can do. Alternative you can reach out the maintainer of node-sass-prebuilt to update their package. We have no association with that project.

**Comment by xzyfer** [comment]
This looks like that repository you're after. It appears to be abandoned.

https://github.com/ankurp/node-sass

**Comment by kpaxton** [comment]
@xzyfer ok thanks, I was not aware that it was a separate thing since that npm page linked to you guy directly. My apologies.
