### ISSUE TITLE
 node-sass@3.13.1 postinstall Error 

### ISSUE THREAD

**Issue by netEmmanuel** [sass/node-sass#2325]
- NPM version (`5.8.0`):
- Node version (`8.1.2`):
- Node Process (`http_parser: '2.7.0',
  node: '8.1.2',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b'`):
- Node Platform (`win32`):
- Node architecture (`x64`):
- npm node-sass versions (``-- gulp-sass@3.2.1
  `-- node-sass@4.8.3`):

When i run `npm install --python=python2.7`

This is the error I get. Kindly help me resolve this issue.

> node-sass@3.13.1 install C:\wamp\www\estatezilla\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\wamp\www\estatezilla\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\wamp\www\estatezilla\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\wamp\\www\\estatezilla\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2.7" in the PATH
gyp verb `which` succeeded python2.7 C:\Python27\python2.7.EXE
gyp verb check python version `C:\Python27\python2.7.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"gyp verb get node dir no --target version specified, falling back to host node version: 8.1.2
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.1.2
gyp verb build dir attempting to create "build" dir: C:\wamp\www\estatezilla\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\wamp\www\estatezilla\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\wamp\www\estatezilla\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\wamp\www\estatezilla\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\wamp\www\estatezilla\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python2.7.EXE
gyp info spawn args [ 'C:\\wamp\\www\\estatezilla\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\wamp\\www\\estatezilla\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\wamp\\www\\estatezilla\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dammy\\.node-gyp\\8.1.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dammy\\.node-gyp\\8.1.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\wamp\\www\\estatezilla\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\dammy\\.node-gyp\\8.1.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\wamp\\www\\estatezilla\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\wamp\\www\\estatezilla\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\dammy\.node-gyp\8.1.2
gyp verb found first Solution file build/binding.sln
gyp verb `which` succeeded for `msbuild` C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.EXE
Build failed with error code: 3221225477
npm WARN estatezilla No repository field.
npm WARN estatezilla No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by xzyfer** [comment]
Node sass 3 is old and unsupported. It only works on node 0.10 and 0.12.
either downgrade Node or upgrade node-sass to version 4.
