### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Nodejs\nodejs-wmc\uploads\04-11-2018-13:20:09*-8.jpg'  at Error (native) when upload image using multer

### ISSUE THREAD

**Issue by Pratiwiratri** [sass/node-sass#2328]
i want to upload an image using multer, but when i change my **app.js**, i have tried many solution but didnt work for me :(

`    
     var multer = require('multer');
     var path = require('path');
     var id_photo = uuidv1();

    global.appRoot = __dirname;

    var storage = multer.diskStorage({

    destination: function(req, file, callback) {
    callback(null, './uploads')
    },
    filename: function(req, file, callback) {
    callback(null, file.fieldname + '-' + id_photo + path.extname(file.originalname));
    }
    })

    var upload = multer({
    storage: storage,
    fileFilter: function(req, file, callback) {
    var ext = path.extname(file.originalname)
    if (ext !== '.png' && ext !== '.jpg' && ext !== '.gif' && ext !== '.jpeg') {
        req.fileValidationError = "Only Image Allowed";
        return callback(null, false, req.fileValidationError)
    }
    callback(null, true)
    }
    }).any();

    app.use(upload);
    connection.init();
`
**became**

`    var multer = require('multer');
     var path = require('path');

    global.appRoot = __dirname;

    var storage = multer.diskStorage({

    destination: function(req, file, callback) {
    callback(null, './uploads')
    },
    filename: function(req, file, callback) {
    var id_photo = new Date();
    var dd = id_photo.getDate();
    var mm = id_photo.getMonth() + 1; //January is 0!
    var yyyy = id_photo.getFullYear();
    var h = id_photo.getHours();
    var i = id_photo.getMinutes();
    var s = id_photo.getSeconds();
    if (dd < 10) {
        dd = '0' + dd
    }

    if (mm < 10) {
        mm = '0' + mm
    }

    if (h < 10) {
        h = '0' + h
    }

    if (i < 10) {
        i = '0' + i
    }

    if (s < 10) {
        s = '0' + s
    }
    id_photo = mm + '-' + dd + '-' + yyyy + '-' + h + ':' + i + ':' + s;
    callback(null, id_photo + "*-" + file.originalname);

    }
     })

     var upload = multer({
    storage: storage,
    }).any();

    app.use(upload);
    connection.init();`

i get an error like this

Error: ENOENT: no such file or directory, open 'C:\Nodejs\nodejs-wmc\uploads\04-11-2018-13:20:09*-8.jpg' at Error (native)

whereas file uploads already exist, when i use app.js the first runs smoothly. what wrong with my code?

please help me ... thank you :)

**Comment by xzyfer** [comment]
I think you have the wrong project.

**Comment by AbduQnauy** [comment]
rewrite "./uploads" to "/uploads", and try again
