### ISSUE TITLE
Bump Node module version to be compatible with Node 10

### ISSUE THREAD

**Issue by igor-savin-ht** [sass/node-sass#2341]
It looks like Node 10 will actually launch with module version 64:
https://github.com/nodejs/node/blob/master/src/node_version.h

https://github.com/sass/node-sass/blob/master/lib/extensions.js -> still defines it as 63.

**Comment by xzyfer** [comment]
Sigh, yes I noticed this. Thanks, we'll release a 4.9.0 shortly with this change.

**Comment by xzyfer** [comment]
Fixed in #2343

**Comment by kibertoad** [comment]
@xzyfer When can we expect an updated version published?

**Comment by xzyfer** [comment]
Hopefully before Node 10 goes stable.
