### ISSUE TITLE
Cannot install node-sass 4.8.3

### ISSUE THREAD

**Issue by whiteblackkeys** [sass/node-sass#2350]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node":

HTTP error 404 Not Found

- NPM version (`npm -v`): 6.0.0
- Node version (`node -v`): 10.0.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.0.0',
  v8: '6.6.346.24-node.5',
  uv: '1.20.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }

**Comment by xzyfer** [comment]
https://github.com/sass/node-sass/issues/2345

**Comment by aseth8** [comment]
I faced the same issue , I dowloaded the required file win32-x64-64_binding.node manually (just google the name required) then i was able to do nom install node-sass successfully.

Hope this helps

**Comment by joharputr** [comment]
how to solve that?

**Comment by nschonni** [comment]
Use a compatible combination as listed on the readme https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimium-support
