### ISSUE TITLE
Security issue: Prototype pollution attack(Introduced by the request@2.79.0 => hawk@3.1.3 => hoek@2.16.3)

### ISSUE THREAD

**Issue by alex-kovoy** [sass/node-sass#2352]
This is a dup of https://github.com/sass/node-sass/issues/2288 which is marked as fixed but it seems that this commit was overridden. Package.json still has the old version

```
    "request": "~2.79.0",
```

**Comment by alex-kovoy** [comment]
The issue is not fixed as package.json still has an old version. The commit with the fix has been lost.

**Comment by xzyfer** [comment]
It cannot be fixed without break node < 4 support
