### ISSUE TITLE
install of 4.8.3 fails with 404 not found

### ISSUE THREAD

**Issue by ajk2018** [sass/node-sass#2357]
Installing the npm package for 4.8.3 fails with 

Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node":

HTTP error 404 Not Found

It looks like nothing is at that URL location.  Found some packages at https://github.com/sass/node-sass/releases/v4.8.3/, but not the one 4.8.3 is trying to use.

**Comment by xzyfer** [comment]
Node 10 support requires node-sass@4.9.0.
