### ISSUE TITLE
Support for macos 10.13.4 (High Sierra)

### ISSUE THREAD

**Issue by murraycollingwood** [sass/node-sass#2360]
I have just upgraded to a new macos version 10.13.4 (High Sierra)

I downloaded Node 10.0.0 as the current stable version but this had an error, so I installed 8.11.1 over the top, hoping that would work.

I'm getting the following problem (with 8.11.1) when trying to run 'gulp':

kohekohe:trunk murraycollingwood$ gulp
/Users/murraycollingwood/dev/sobs-git/trunk/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/murraycollingwood/dev/sobs-git/trunk/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/murraycollingwood/dev/sobs-git/trunk/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/murraycollingwood/dev/sobs-git/trunk/node_modules/gulp-sass/index.js:187:21)

I did visit the page suggested but it didn't mean much to me.
OS X 64-bit has been out for a while now, in fact my previous mac is running OS X 64-bit and I was running Node-Sass on this machine without a problem.  So I think there is something amiss with the error message, or I am missing a particular matching software version.

- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): 8.11.1
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): kohekohe:trunk murraycollingwood$ node -p "require('node-sass').info"
/Users/murraycollingwood/dev/sobs-git/trunk/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

- npm node-sass versions (`npm ls node-sass`): sobs@1.0.0 /Users/murraycollingwood/dev/sobs-git/trunk
└─┬ gulp-sass@2.3.2
  └── node-sass@3.13.1 

I've been using sass for a couple of years, so I'm still relatively new.  If there is any versions to change please include copies of the commands I should use to uninstall/install/update/replace etc.

Cheers
Murray

**Comment by xzyfer** [comment]
This isn't an OSX support issue.

You're using node-sass@v3.13.1 which is very very old. You'll need node-sass@V4.9.0 for Node 10 support. You can get that with gulp-sass@v3.

**Comment by murraycollingwood** [comment]
Solved with:
npm rebuild node-sass
