### ISSUE TITLE
[Meta] Adding new separate issue templates

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#2365]
There is now support for directed issue templates https://blog.github.com/2018-05-02-issue-template-improvements/

Here is what I'm thinking:
1. "I'm having trouble installing node-sass". Collect our regular version/OS info and ensure they're running the latest version or we can't/won't troubleshoot
1. "I think the compiled results are wrong".  Encourage them to search/open a libsass issue if they are running the latest version of node-sass
1. "My security software is flagging Request/Hoek". Please do not open and issue, and point them to the one we've left open
1. "I want to request a feature". Ask them to point to the implementation in Ruby/Dart Sass and how they'd want it to behave here.

I don't have access to the settings panel, but I can probably help with the template parts if we agree on them

**Comment by xzyfer** [comment]
I am in violent agreement that we should adopt this feature.

I jump on a plane in 48hrs for a couple weeks holiday so wont have a chance to look at this myself.

**Comment by nschonni** [comment]
OK, I'll see what I can do before then. Whenever you're back you can do the Settings part

**Comment by xzyfer** [comment]
Do you not have access to do that? If that that should definitely be fixed, if you want.

**Comment by nschonni** [comment]
No, it's fine this is the first time the Settings stuff has been needed. I'm less likely to accidentally enable a weird CI/Linting/Bot service when I'm just trying to kick the tires on another repo 😛

**Comment by nschonni** [comment]
OK, these are setup now. It looks like I got the naming wrong for the files, so that's why they didn't get automatically picked up.
