### ISSUE TITLE
Missing binary for 4.8.3

### ISSUE THREAD

**Issue by DustinBrett** [sass/node-sass#2368]
https://github.com/sass/node-sass/releases/download/v4.8.3/linux_musl-x64-64_binding.node

Is 404 not found. I know 4.9.0 has it but this dependency for 4.8.3 is from a package that isn't mine.

**Comment by nschonni** [comment]
There will be no 10 support for 4.8

**Comment by xzyfer** [comment]
Update to 4.9.0 for Node 10 support
