### ISSUE TITLE
Unsupported Environment (Ubuntu & Debian Linux 64-bit)

### ISSUE THREAD

**Issue by rbt** [sass/node-sass#2369]
Upgraded from Node 8.x to Node 10.0.0.  Downgrading Node to 8.11.1 resolves this issue.

The error occurs on both Ubuntu 18.04 and Debian Stretch with the same yarn packages.

# Ubuntu 18.04
$ uname -a
Linux xps13 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ yarn -v
1.6.0

$ npm -v
5.6.0

$ node -v
v10.0.0

$ node -p process.versions
{ http_parser: '2.8.0',
  node: '10.0.0',
  v8: '6.6.346.24-node.5',
  uv: '1.20.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }

$ node -p process.platform
linux

$ node -p process.arch
x64

$ node -p "require('node-sass').info"
/home/rbt/budgie/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.0
    at module.exports (/home/rbt/budgie/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/rbt/budgie/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1

$ npm ls node-sass
npm WARN npm npm does not support Node.js v10.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
budgie@1.0.0 /home/rbt/budgie
└── node-sass@4.9.0

**Comment by xzyfer** [comment]
I can't explain what is going on here.

>Unsupported runtime (64)

This shouldn't be possible with 4.9.0. Please try a clean slate install.

```
rm -rf node_modules
npm cache clean
npm install node-sass
```

If that doesn't work you may need to upgrade npm@6.

>npm WARN npm npm does not support Node.js v10.0.0
>npm WARN npm You should probably upgrade to a newer version of node as we
>npm WARN npm can't make any promises that >npm will work with this version.
>npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.

**Comment by xzyfer** [comment]
Make sure you're running node-sass@4.9.0. older versions cannot run on node
10

**Comment by TerrySlack** [comment]
After updating node and npm. Every package forced to update to latest with ncu.  Closed all powershell windows.  Reopened and verified the cache.  
No luck.  
Deleted node_modules and reinstalled.  
No luck. 
Deleted the node_modules again and the package.lock.json file. 
No luck.     
But then...it's Windows and the golden rule applies...when in doubt...reboot.  Everything works now.

**Comment by nschonni** [comment]
The binding file is available at https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-64_binding.node so something might have gone wrong with your local setup.
We don't have a binding for Debian, so you'd need a local buildchain to try and produce your own for that.

**Comment by TomK32** [comment]
@rbt you probably have to downgrade `libicu`, the [nodesass releases](https://github.com/sass/node-sass/releases) only go up to *59* and I constantly have this trouble on my manjaro machine.

**Comment by xzyfer** [comment]
FYI we added supper for 64 (node 10) in 4.9.0

**Comment by acebesmonte** [comment]
im using node 6.10, npm 6, ubuntu 18
and i still  cant build this email template that i can building successfully in ubuntu 16
https://foundation.zurb.com/emails/email-templates.html

**Comment by xzyfer** [comment]
Your version of node-sass too old. Update to a newer 4.x version for node 6 support

**Comment by LC43** [comment]
@xzyfer suggestion to just update node-sass ( on my case, by updating grunt-sass ), fixed this issue. thanks!

**Comment by gilbertlucas46** [comment]
run: 
`sudo npm cache clean -f`
`npm rebuild`
