### ISSUE TITLE
link to troubleshooting guide returns 404.

### ISSUE THREAD

**Issue by rupav** [sass/node-sass#2370]
On https://www.npmjs.com/package/node-sass link to `troubleshooting guide` returns [404](https://www.npmjs.com/package/TROUBLESHOOTING.md#installing-node-sass-4x-with-node--4) .

**Comment by xzyfer** [comment]
Thanks for the report. Npm scrapes readme but doesn't adjust the link when
displaying it in their site. We need to update the links on the readme to
be absolute URLs to our GitHub page.

This a good first contribution for anyone interested.

**Comment by rupav** [comment]
I am making a PR then 😃

**Comment by xzyfer** [comment]
Fixed in #2371
