### ISSUE TITLE
missing binaries for alpine v4.8.1/linux_musl-x64-64_binding.node ?

### ISSUE THREAD

**Issue by benyitzhaki** [sass/node-sass#2373]
There seems to be an issue downloading node-sass. i'm guessing from the previous issues that those are missing binaries? this is the log:
`11:28:17 > node-sass@4.8.1 install /clientFiles/node_modules/node-sass
11:28:17 > node scripts/install.js
11:28:17 
11:28:17 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.1/linux_musl-x64-64_binding.node
11:28:18 Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.1/linux_musl-x64-64_binding.node": 
11:28:18 
11:28:18 HTTP error 404 Not Found
11:28:18 
11:28:18 Hint: If github.com is not accessible in your location
11:28:18       try setting a proxy via HTTP_PROXY, e.g. 
11:28:18 
11:28:18       export HTTP_PROXY=http://example.com:1234
11:28:18 
11:28:18 or configure npm proxy via
11:28:18 
11:28:18       npm config set proxy http://example.com:8080
11:28:18 `

running it via node:alpine docker image.

thanks

**Comment by xzyfer** [comment]
Node 10 support was added in 4.9.0. Update your node-sass

**Comment by benyitzhaki** [comment]
thanks, i solved it by downgrading my node version (using docker image node:9-alpine)
