### ISSUE TITLE
Node-Sass 4.5.3 download url fail

### ISSUE THREAD

**Issue by TechedImpala** [sass/node-sass#2380]
Hi

We have a build server that build our web app.
It is failing due to the node-sass package not being able to be downloaded.

Previous Url (Worked 100%)
https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-57_binding.node

Url Now (Not working)
https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-64_binding.node

This is a big issue for us because our build server does not cache npm packages so this is failing

Please regard this as urgent
Kind Regards
Pieter du Buisson

**Comment by xzyfer** [comment]
You need node-sass@4.9.0 for Node 10 support.
