### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-51_binding.node":  ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by arifinofficial** [sass/node-sass#2381]
npm install
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.9.0 install /var/www/news/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-51_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.0 postinstall /var/www/news/node_modules/node-sass
> node scripts/build.js

Building: /home/laradock/.nvm/versions/node/v7.10.0/bin/node /var/www/news/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/home/laradock/.nvm/versions/node/v7.10.0/bin/node',
gyp verb cli   '/var/www/news/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@7.10.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/news/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/news/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/news/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/news/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/news/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/news/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/var/www/news/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/news/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/news/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/news/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/news/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/news/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/var/www/news/node_modules/which/which.js:13:12)\n    at F (/var/www/news/node_modules/which/which.js:68:19)\n    at E (/var/www/news/node_modules/which/which.js:80:29)\n    at /var/www/news/node_modules/which/which.js:89:16\n    at /var/www/news/node_modules/isexe/index.js:42:5\n    at /var/www/news/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:114:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/news/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/news/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/news/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/news/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/news/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/news/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/var/www/news/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/var/www/news/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/var/www/news/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /var/www/news/node_modules/which/which.js:89:16
gyp verb `which` failed     at /var/www/news/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /var/www/news/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (/var/www/news/node_modules/which/which.js:13:12)\n    at F (/var/www/news/node_modules/which/which.js:68:19)\n    at E (/var/www/news/node_modules/which/which.js:80:29)\n    at /var/www/news/node_modules/which/which.js:89:16\n    at /var/www/news/node_modules/isexe/index.js:42:5\n    at /var/www/news/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:114:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/var/www/news/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/news/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/var/www/news/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/var/www/news/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/news/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/news/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/news/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Linux 4.9.87-linuxkit-aufs
gyp ERR! command "/home/laradock/.nvm/versions/node/v7.10.0/bin/node" "/var/www/news/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/news/node_modules/node-sass
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/home/laradock/.nvm/versions/node/v7.10.0/bin/node" "/home/laradock/.nvm/versions/node/v7.10.0/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-05-15T09_48_17_458Z-debug.log

> Node v7.10.0
> NPM 4.2.0

**Comment by xzyfer** [comment]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-51_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

  export HTTP_PROXY=http://example.com:1234
or configure npm proxy via

  npm config set proxy http://example.com:8080

**Comment by xzyfer** [comment]
Looks like a network issue. Make sure you can access the binding url. If so try npm to run the install again. If you're behind a proxy make sure you have configured npm to use your proxy.
