### ISSUE TITLE
Update `request` dependency

### ISSUE THREAD

**Issue by dbartholomae** [sass/node-sass#2384]
Currently this project relies on `request@2.79`. In that packages dependency tree there is a (package with a vulnerability)[https://nodesecurity.io/advisories?search=is-my-json-valid&version=2.17.1]. This dependency has been fixed in more recent versions of `request`. Please update the dependency of `request` to the newest version `2.86`, if possible (I haven't checked yet whether there have been breaking changes).

**Comment by xzyfer** [comment]
Search before opening new issues.
