### ISSUE TITLE
When trying to create a helloWorld file

### ISSUE THREAD

**Issue by TrevorBedsaul** [sass/node-sass#2387]
This is the command I used: ionic start helloWorld blank              
    

This is the problem:
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):
        npm ERR! Failed at the node-sass@4.7.2 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        > node-sass@4.7.2 install C:\Users\student\helloWorld\node_modules\node-sass
        > node scripts/install.jsdent\AppData\Roaming\npm-cache\_logs\2018-05-17T18_12_38_161Z-debug.log

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":
        \student>cd helloWorld
        HTTP error 404 Not Found
        \student\helloWorld>ionic serve
        Hint: If github.com is not accessible in your locationdules\@ionic\app-scripts'
               try setting a proxy via HTTP_PROXY, e.g. s/cjs/loader.js:571:15)
        unction.Module._load (internal/modules/cjs/loader.js:497:25)
               export HTTP_PROXY=http://example.com:12346:17)

        or configure npm proxy vias\student\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ion
        ar\app-scripts.js:9:16)
               npm config set proxy http://example.com:8080
        :\Users\student\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:107:75
        > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\student\helloWorld\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.jsstudent\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:103:16)
        bject.importAppScripts (C:\Users\student\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\li
        angular\app-scripts.js:7:20)
        > node-sass@4.7.2 postinstall C:\Users\student\helloWorld\node_modules\node-sass
        > node scripts/build.js..

        Building: C:\Program Files\nodejs\node.exe C:\Users\student\helloWorld\node_modules\node-gyp\bin\node-gyp.js
        rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\student\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',    .
        gyp verb cli   '--libsass_ext=',.
        gyp verb cli   '--libsass_cflags=',roid
        gyp verb cli   '--libsass_ldflags=',_history
        gyp verb cli   '--libsass_library=' ]g
        gyp info using node-gyp@3.6.2  .eclipse
        gyp info using node@10.1.0 | win32 | x64g
        gyp verb command rebuild []    .idlerc
        gyp verb command clean []      .ionic
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError
        (C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at
        C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:89:16\n    at
        C:\\Users\\student\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\Users\\student\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete
        (fs.js:165:21)',<DIR>          Saved Games
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError
        (C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at
        C:\\Users\\student\\helloWorld\\node_modules\\which\\which.js:89:16\n    at
        C:\\Users\\student\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\Users\\student\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete
        (fs.js:165:21)',for help on <term>
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error command> --key value
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython
        (C:\Users\student\helloWorld\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous>
        (C:\Users\student\helloWorld\node_modules\node-gyp\lib\configure.js:508:16)                         \ Running co
        gyp ERR! stack     at C:\Users\student\helloWorld\node_modules\graceful-fs\polyfills.js:284:29      - Running co
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:165:21)                                                 / Runn
        gyp ERR! System Windows_NT 10.0.16299
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
        "C:\\Users\\student\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
        "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\student\helloWorld\node_modules\node-sass
        gyp ERR! node -v v10.1.0ins file(s) that could conflict. Would you like to overwrite the directory with this ne
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok elloWorld - done!
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted
        {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
        integrations enable cordova --quiet
        npm ERR! code ELIFECYCLEa - done!
        npm ERR! errno 1iles to project - done!
        npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.7.2 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\student\AppData\Roaming\npm-cache\_logs\2018-05-18T17_28_45_753Z-debug.log

**Comment by chriseppstein** [comment]
@TrevorBedsaul As it says in the stack trace, you do not have python installed, this is causing the build of the node-sass native library to fail. The reason you're building node-sass instead of downloading an executable is that you're using a version of node-sass that was published before node `v10` was released. For node `v10` support please use node-sass `4.9.0` or greater.

**Comment by TrevorBedsaul** [comment]
@chriseppstein Ok, well I have programmed in python on this computer through pycharm, so how do I show npm that I in fact do have Python installed?

**Comment by xzyfer** [comment]
The issue is that you're using an older version of node-sass that doesn't
support node 10. Update to node-sass@4.9.0 or downgrade your Node

**Comment by TrevorBedsaul** [comment]
@xzyfer So I did do that before running this because I thought that could be the issue...and this is what happened when I installed it, but I don't know how to solve this problem:

C:\Users\student\NodePackMan>npm install node-sass

> node-sass@4.9.0 install C:\Users\student\NodePackMan\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-64_binding.node
Download complete..] - :
Binary saved to C:\Users\student\NodePackMan\node_modules\node-sass\vendor\win32-x64-64\binding.node
Caching binary to C:\Users\student\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-64_binding.node

> node-sass@4.9.0 postinstall C:\Users\student\NodePackMan\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\student\NodePackMan\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\student\NodePackMan\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\student\NodePackMan\package.json'
npm WARN NodePackMan No description
npm WARN NodePackMan No repository field.
npm WARN NodePackMan No README data
npm WARN NodePackMan No license field.

+ node-sass@4.9.0
added 187 packages in 26.971s

**Comment by xzyfer** [comment]
That error is not about node-sass. It looks like you don't have a
package.json in that directory and yarn is unhappy about it. Try yarn init
before npm install, and make sure you're in the right directory.

**Comment by TrevorBedsaul** [comment]
If you can't tell, I don't have a ton of experience with this, and the tutorial I used was confusing. I basically just installed npm in my student directory, then made a directory called NodePackMan, and within that I did everything. I have tried using the command yarn init and it says it doesn't recognize yarn. I am on a windows computer by the way. Should I be using a specific directory that was made when I installed node that I should be using for this? Thanks
