### ISSUE TITLE
404 when downloading Linux binding

### ISSUE THREAD

**Issue by toreonify** [sass/node-sass#2392]
In releases there is no 46 version in list for linux_musl. Every other platform has it.
https://github.com/sass/node-sass/releases/download/v4.6.1/linux_musl-x64-64_binding.node

Log:
> node-sass@4.6.1 install /src/node_modules/node-sass 
> node scripts/install.js 
 
Downloading binary from https://github.com/sass/node-sass/releas… 
Cannot download "https://github.com/sass/node-sass/releas…": 
 
HTTP error 404 Not Found

**Comment by xzyfer** [comment]
Correct. You need node-sass@4.9.0 for Node 10.

**Comment by xzyfer** [comment]
The release notes for 4.6.1 will tell you versions of Node are supported
