### ISSUE TITLE
node-sass doesn't return POSIX paths, correct?

### ISSUE THREAD

**Issue by npetruzzelli** [sass/node-sass#2393]
This is a general question, which I could not find guidelines for in <https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md>

My understanding is that source maps only work with URLs (though I have [an issue open to confirm this]( https://github.com/mozilla/source-map/issues/340 )), not file system paths, though I found the following comment in a popular node package

<https://github.com/webpack-contrib/sass-loader/blob/2529c0716b1bca321c22d16636b1385682b1c730/lib/loader.js#L90-L94>
```javascript
            // node-sass returns POSIX paths, that's why we need to transform them back to native paths.
            // This fixes an error on windows where the source-map module cannot resolve the source maps.
            // @see https://github.com/webpack-contrib/sass-loader/issues/366#issuecomment-279460722
            result.map.sourceRoot = path.normalize(result.map.sourceRoot);
            result.map.sources = result.map.sources.map(path.normalize);
```

Can you confirm whether or not this comment is accurate?

**Comment by xzyfer** [comment]
We don't use Mozilla sourcemaps. Our sourcemaps are generated in C++ by
LibSass.

**Comment by xzyfer** [comment]
As far I know LibSass returns source map paths as relative filesystem paths.

**Comment by npetruzzelli** [comment]
Got it!

I'll ask in the LibSass repo then. I was under the assumption that both the Mozilla node module and LibSass were adhering to the to the same document ([Source Map Revision 3 Proposal]( https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit )), but from what you are saying, that may not be the case.

Thank you for your time and for pointing me in the right direction!
