### ISSUE TITLE
Interpolating inside content of pseudo element changes value

### ISSUE THREAD

**Issue by sethstha** [sass/node-sass#2400]
I am trying to use the `rtlcss` in the compiled CSS file. The problem is `node-sass` brings multiline comment on the same line to new line.clear

While I was able to place a multiline comment on the same line using interpolation which works great on another part except for the content of pseudo-elements. While compiling it adds strange block on the content.

```
a:after {
	position: absolute;
	content: "\f105" #{"/*rtl: newvalue */"};
	line-height: 1.2;
}
```
is compiled to 
```
 a:after {
	position: absolute;
	content: "" /*rtl: newvalue */;
	line-height: 1.2;
}
```
- NPM version: 6.1.0
- Node version : 8.9.4
- Node Process: 
  http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform : darwin
- Node architecture : x64
- node-sass version :
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
- npm node-sass versions :
 gulp-sass@3.2.1
  └── node-sass@4.9.0

**Comment by xzyfer** [comment]
The block is fine. It's another way of representing unicode characters.
