### ISSUE TITLE
css not working after running after running npm install node-sass

### ISSUE THREAD

**Issue by alexantosh** [sass/node-sass#2403]
Hi all. After changing the environment, I run into the expected error: ERROR in ./src/app/components/../../.component.scss
Module build failed: Error: Missing binding ..\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x
Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

So as usual, i run npm install and/or npm update, then npm install node-sass
It compiled well, but when i check the website, this time the css is all broken. 
project cli version: 1.7.1
my current version 1.7.3

anybody got an idea why this is the case? thank you very much.

**Comment by xzyfer** [comment]
npm rebuild node-sass

**Comment by alexantosh** [comment]
I tried that too. still broken.
