### ISSUE TITLE
Installing node-sass on ubuntu 18.04 returns this error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by SenTisso** [sass/node-sass#2404]
I'm trying to install node-sass on ubuntu, beacuse I want to use sass-autocompile, but even when I try to compile (just when I save it)
It returns this error:

> fs.js:904
    return binding.readdir(pathModule._makeLong(path), options.encoding);        
 Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/usr/lib/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/usr/lib/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/lib/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/lib/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/lib/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

I tried to use this command `npm rebuild node-sass` and it didn't fix the problem, even with `--force`
And removing nodejs and node-sass and npm and installing again didn't fix the problem and yes I do have ruby installed.
But one thing is really strange: this path `node_modules/node-sass/vendor'` exists in home folder, basically `node_modules` exists in home folder even with that vendor folder. Can you help me out ?

![screenshot from 2018-06-02 14-03-35](https://user-images.githubusercontent.com/38100632/40874305-e0b083e6-666d-11e8-801b-ddd78214f952.png)

![screenshot from 2018-06-02 14-04-00](https://user-images.githubusercontent.com/38100632/40874308-eeba5354-666d-11e8-9020-686e47658b76.png)

**Comment by xzyfer** [comment]
What is the output of `npm rebuild node-sass`?

**Comment by sickp** [comment]
Running in CircleCI, docker image `circleci/node:8.11.3`... confirmed `npm rebuild node-sass` fixes issue. Lock file originally specified 4.9.3, seems to be rebuilding from 4.9.2. Output:

```
#!/bin/bash -eo pipefail
npm rebuild node-sass

> node-sass@4.9.2 install /home/circleci/project/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.2/linux-x64-57_binding.node
Download complete
Binary saved to /home/circleci/project/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/circleci/.npm/node-sass/4.9.2/linux-x64-57_binding.node

> node-sass@4.9.2 postinstall /home/circleci/project/node_modules/node-sass
> node scripts/build.js

Binary found at /home/circleci/project/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
node-sass@4.9.2 /home/circleci/project/node_modules/node-sass
```

**Comment by Goran7777** [comment]
Here is the solution sudo npm install --unsafe-perm node-sass

**Comment by mohsenhaghighatkhah** [comment]
> Here is the solution sudo npm install --unsafe-perm node-sass


With the solution, my problem was solved , tnx !
