### ISSUE TITLE
Can't set decimal precision

### ISSUE THREAD

**Issue by robsonsobral** [sass/node-sass#2405]
- NPM version (`npm -v`): 6.1.0
- Node version (`node -v`): 10.3.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '10.3.0',
  v8: '6.6.346.32-node.9',
  uv: '1.20.3',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.9.0
- npm node-sass versions (`npm ls node-sass`): `-- (empty)`

Hi! I just discovered I can't change the decimal precision on node-sass. It doesn't matter what I try, it keeps set at `5`:

```
node-sass ./tests --output ./tests --precision 10
```

Thank you!

**Comment by robsonsobral** [comment]
Thank you, @nschonni .

I'm not sure, but I think I tested thus way too. I gonna check it when I get home.

**Comment by robsonsobral** [comment]
I tested, @nschonni . Even using `node-sass --precision 10 --output ./tests ./tests`, I get only 5 decimal places.

**Comment by xzyfer** [comment]
Please provide minimal example scss code that shows the incorrect precision output so that we can confirm

**Comment by robsonsobral** [comment]
I'm sorry. It looks like I had an character which ins't a space on my script. I have no idea where it came from.

I´m sorry. Thank you for your patience.
