### ISSUE TITLE
Changes in css generation after updating to node sass 4.9.0

### ISSUE THREAD

**Issue by Nazar32** [sass/node-sass#2406]
- NPM version (`npm -v`): 6.1.0
- Node version (`node -v`): 9.11.1
- Node Process (`node -p process.versions`): 
{ http_parser: '2.8.0',
  node: '9.11.1',
  v8: '6.2.414.46-node.23',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):
└── node-sass@4.9.0 

After updating to node-sass 4.9.0, and compiling scss, I have encounter such changes in compilation, which were not encoutered before:
`background: linear-gradient(transparent, black);` => `background: linear-gradient(rgba(0, 0, 0, 0), black);`
`.disabled.form__submit, [disabled].form__submit {` => `.disabled.form__submit, .form__submit[disabled] {`

**Is this issue related to new version of node-sass?**
**How can it be fixed?**

**Comment by xzyfer** [comment]
This change is on purpose. It's semantically equivalent to the old code. There is no fix.

**Comment by gabegorelick** [comment]
See https://github.com/sass/sass/issues/1782 and https://github.com/sass/libsass/issues/2298.
