### ISSUE TITLE
node6.x support

### ISSUE THREAD

**Issue by jang675953** [sass/node-sass#2407]
when i build project with node6.9.2,  it suggests that 
node_modules\node-sass\vendor\win32-x64-48\binding.node
[ERROR] Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

**Comment by jang675953** [comment]
here is my os information:
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64

**Comment by xzyfer** [comment]
`npm rebuild node-sass`

**Comment by jang675953** [comment]
It doesn't work

**Comment by xzyfer** [comment]
Thats not a helpful response. What output do you see?
