### ISSUE TITLE
Relative path for sass_binary_dir parameter does not work.

### ISSUE THREAD

**Issue by Brainman643** [sass/node-sass#2409]
## Problem
My computer is not connected to the Internet. I put node-sass binary files in the folder "sass-binaries" in my project and I set sass_binary_dir setting in the .npmrc file:
`sass_binary_dir=../../sass-binaries/`

After installation, I received the following error message:

C:\Projects\rst\RST.Web.UI>npm install node-sass --save-dev

> node-sass@4.9.0 install C:\Projects\rst\RST.Web.UI\node_modules\node-sass
> node scripts/install.js

node-sass build Binary found at ..\..\sass-binaries\win32-x64-57\binding.node

> node-sass@4.9.0 postinstall C:\Projects\rst\RST.Web.UI\node_modules\node-sass
> node scripts/build.js

**Binary found at** ..\..\sass-binaries\win32-x64-57\binding.node
Testing binary
Binary has a problem: { Error: **Cannot find** module '..\..\sass-binaries\win32-x64
-57\binding.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Projects\rst\RST.Web.UI\node_modules\node-sass\lib\bin
ding.js:19:10)
    at Object.<anonymous> (C:\Projects\rst\RST.Web.UI\node_modules\node-sass\lib
\index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12) code: 'MODULE_NOT_FOUND' }
Building the binary locally
Building: C:\Program Files\nodejs\node.exe C:\Projects\rst\RST.Web.UI\node_modul
es\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= -

## Solution
If I set the absolute path, then everything works well.
`sass_binary_dir=C:\Projects\rst\RST.Web.UI\sass-binaries\`

The file at first was found by the relative path, and then not. Most likely, because the current directory was changed. It is necessary to convert a relative path to an absolute path in `getBinaryDir()` or `getBinaryPath()` methods.

## Info
node-sass v4.9.0

- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v8.9.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):
rst-ui@0.0.0 C:\Projects\rst\RST.Web.UI
+-- @angular-devkit/build-angular@0.6.8
| `-- node-sass@4.9.0  deduped
`-- node-sass@4.9.0

**Comment by xzyfer** [comment]
Please search for issues before creating a new one.

Duplicate https://github.com/sass/node-sass/issues/2081
