### ISSUE TITLE
color property build error/weird behavior

### ISSUE THREAD

**Issue by ryuukibeat** [sass/node-sass#2410]
- NPM version (`npm -v`): `5.10.0`
- Node version (`node -v`): `v8.9.1`
- Node Process (`node -p process.versions`):

```javascript
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```
- Node Platform (`node -p process.platform`): `win32`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):

  ```js
  node-sass       4.9.0   (Wrapper)       [JavaScript]
  libsass         3.5.4   (Sass Compiler) [C/C++]```
- npm node-sass versions (`npm ls node-sass`):
```
test@0.7.1 E:\laragon\www\test\assets\sass
`-- node-sass@4.9.0
```
I got an error whenever I tried to compile my sass file.
Already tried running the syntax at https://www.sassmeister.com/ and it seems no problem.
![Syntax](https://puu.sh/ABK3s.png)

My build command is:
`node-sass --output-style expanded --source-map true style.sass ../css/style.css`

The compile error is:
```
{
  "status": 1,
  "file": "E:/laragon/www/test/assets/sass/sass/extensions/style.sass",
  "line": 14,
  "column": 34,
  "message": "Invalid CSS after \"...255,255,0.3); }\": expected 1 selector or at-rule, was \"{\"",
  "formatted": "Error: Invalid CSS after \"...255,255,0.3); }\": expected 1 selector or at-rule, was \"{\"\n        on line 14 of sass/extensions/style.sass\n        from line 4 of sass/extensions/_all.sass\n        from line 10 of style.sass\n>>   color: rgba(255,255,255,0.3); } {\n\n   ---------------------------------^\n"
}
```

The .sass file syntax is this:
```sass
.foot-copyrights
        color: rgba(255,255,255,0.3)
	background-color: rgba(0, 0, 0, 0.2)
	padding: 1.5rem 0
	font-size: 1rem
	line-height: 1.8
```

So if I place the color in another line, for example:
```sass
.foot-copyrights
	background-color: rgba(0, 0, 0, 0.2)
	padding: 1.5rem 0
        color: rgba(255,255,255,0.3)
	font-size: 1rem
	line-height: 1.8
```

The compile not encountered error, but the result is weird, so in `style.css` file is like this:
```css
.foot-copyrights {
  background-color: rgba(0, 0, 0, 0.2);
  padding: 1.5rem 0;
  padding-color: rgba(255,255,255,0.3);
  font-size: 1rem;
  line-height: 1.8;
}
```

That's what I'm reporting in. What is the problem and the solution?
I'm sorry if this case is solved somewhere or I just missing something. 

Thanks in advance.

**Comment by nschonni** [comment]
You have mixed tabs and spaces in your selector. The `color: rgba(255,255,255,0.3)` is indented with 8 spaces so the indented syntax thinks it's a malformed nested class. There are benefits to using the SCSS syntax 😉
