### ISSUE TITLE
Can't install node-sass anymore

### ISSUE THREAD

**Issue by michelecocuccio** [sass/node-sass#2411]
Hello. For some reason I can't install node-sass anymore. I have already installed node-sass on this computer and on different projects (macOS High Sierra - v 10.13.4) and up until last week everything was working fine. I started a new project recently and I am getting an error now. 

I am on the last version of Node and npm and I am trying to install node-sass: 4.9.0. I have tried running the command as Sudo but no luck. Here is the error and the information requested (I have also attached the error log file).

**npm**: v6.1.0

**node**: v8.11.2

**node process**: { http_parser: '2.8.0',
  node: '8.11.2',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

**node platform**: darwin

**node architecture:** x64

**node sass version**: 4.9.0

**error**
> node-sass@4.9.0 install /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/vendor' }

> node-sass@4.9.0 postinstall /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.11.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:13:12)\n    at F (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:68:19)\n    at E (/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:80:29)\n    at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/which/which.js:89:16\n    at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/isexe/index.js:42:5\n    at /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.2
gyp verb command install [ '8.11.2' ]
gyp verb install input version string "8.11.2"
gyp verb install installing version: 8.11.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.2
gyp verb build dir attempting to create "build" dir: /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass/build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/michelecocuccio/Documents/STUDIO/JavaScript/React/expensify/node_modules/node-sass
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap@4.1.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-jsx@0.26.0 requires a peer of postcss-syntax@>=0.26.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-styled@0.27.0 requires a peer of postcss-syntax@>=0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN expensify@1.0.0 No description
npm WARN expensify@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michelecocuccio/.npm/_logs/2018-06-09T22_43_52_510Z-debug.log
[2018-06-09T22_31_10_020Z-debug.log](https://github.com/sass/node-sass/files/2087403/2018-06-09T22_31_10_020Z-debug.log)

**Comment by xzyfer** [comment]
You should not use side with npm. If you must then you'll need to use the
--unsafe-perms flag

**Comment by michelecocuccio** [comment]
Thanks for the reply. Can you please be more specific? What do you mean by "I shouldn't use "side" with NPM? "

Thanks

**Comment by xzyfer** [comment]
Sorry I mean you should never use sudo with npm because you'll have
permission errors.

**Comment by DadaConsultant** [comment]
Fixed this issue by using yarn instead.
