### ISSUE TITLE
Function in css variable declaration aren't compiled

### ISSUE THREAD

**Issue by SuperDJ** [sass/node-sass#2412]
- NPM version (`npm -v`): 6.1
- Node version (`node -v`): 8.11.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):
`-- node-sass@4.9.0

I'm trying to use a function for declaring a CSS `var()` but instead of compiling it into a value it just returns the exact declaration:

SCSS:

    $xs-gutter: 16px;

    @function em-calc( $sp, $default: 16 ) {
	@if( type_of( $sp ) != null AND str_index( quote( $sp ), px ) != null )
	{
		@return $sp / ( $default + 0px ) * 1em;
	} @else if( type_of( $sp ) != null AND str_index( quote( $sp ), px ) == null )
	{
		@return ( $sp + 0px ) / ( $default + 0px ) * 1em;
	} @else {
		@warn 'Wrong argument parsed to em-calc';
	}
    }

    :root {
	--gutter: em-calc($xs-gutter);
    }

CSS output:

    :root {--gutter: em-calc($xs-gutter); }

Expected CSS output:

    :root {--gutter: 1em; }

**Comment by xzyfer** [comment]
You have to use interpolation around your Sass variables.

```scss
#{$myVariable}
```

**Comment by SuperDJ** [comment]
@xzyfer That should not be necessary as it is working everywhere except within a CSS variable

**Comment by xzyfer** [comment]
It is necessary for calc because you can have mixed unit math in calc which
Sass can't understand

**Comment by SuperDJ** [comment]
@xzyfer That makes sense thanks for clarifying
