### ISSUE TITLE
Fail to install node-sass during npm install

### ISSUE THREAD

**Issue by connelevalsam** [sass/node-sass#2415]
- NPM version (`npm -v`): 3.10.9
- Node version (`node -v`):v6.9.2
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.9.2',
  v8: '5.1.281.88',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '48',
  openssl: '1.0.2j' }
- Node Platform (`node -p process.platform`):linux
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
connelblaze@connelblaze:go_jessy$ npm ls node-sass
buffalo@1.0.0 /home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy
`-- UNMET DEPENDENCY node-sass@~4.7.2

npm ERR! missing: node-sass@~4.7.2, required by buffalo@1.0.0
npm ERR! code 1
- npm node-sass versions (`npm ls node-sass`):

**Comment by xzyfer** [comment]
Looks like you're using sudo. If so you need to use the --unsafe-perms flag
with npm install

**Comment by connelevalsam** [comment]
i didn't use sudo, i just did npm install.

so i should do : npm install --unsafe-perms  ??

**Comment by xzyfer** [comment]
You can try. The issue isn't node-sass it's npm so there isn't much we can
do.

**Comment by connelevalsam** [comment]
npm siad it's node
now node is saying it's npm
I'm not getting...

**Comment by nschonni** [comment]
Can you provide a Gist with the install log. The above information just indicates that node-sass hasn't been installed at all.

**Comment by connelevalsam** [comment]
I don't know, what's the name of the file where the install log will be?

**Comment by nschonni** [comment]
If you run `npm install` and it fails it will list a file with the details steps. Our troubleshooting guide also explains how to test out the install to figure out if it is a project specific or machine issue https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#debugging-installation-issues

Currently it just appears that you never did the NPM install at all.

**Comment by connelevalsam** [comment]
I've tried everything i know.
I've tried what i saw there. Don't know why it's failing
[2018-06-15T19_40_14_500Z-debug.log](https://github.com/sass/node-sass/files/2107307/2018-06-15T19_40_14_500Z-debug.log)

**Comment by connelevalsam** [comment]
`npm install node-sass@beta`

this helped

**Comment by xzyfer** [comment]
Honestly I have no idea what's going on. The below is from the log
```
2002 silly install node-sass@4.9.0
2003 info lifecycle node-sass@4.9.0~install: node-sass@4.9.0
2004 verbose lifecycle node-sass@4.9.0~install: unsafe-perm in lifecycle true
2005 verbose lifecycle node-sass@4.9.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy/node_modules/node-sass/node_modules/.bin:/home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy/node_modules/.bin:/home/connelblaze/google-cloud-sdk/bin:/usr/local/heroku/bin:/home/connelblaze/.rbenv/plugins/ruby-build/bin:/home/connelblaze/.rbenv/shims:/home/connelblaze/.rbenv/bin:/home/connelblaze/mongodb/mongodb-linux-x86_64-ubuntu1604-3.4.4/bin/:/home/connelblaze/node_modules/.bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/connelblaze/android/android-sdk-linux/tools:/home/connelblaze/android/android-sdk-linux/platform-tools:/bin:/home/connelblaze/go/bin:/usr/local/go/bin://home/connelblaze/go/src
2006 verbose lifecycle node-sass@4.9.0~install: CWD: /home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy/node_modules/node-sass
2007 silly lifecycle node-sass@4.9.0~install: Args: [ '-c', 'node scripts/install.js' ]
2008 silly lifecycle node-sass@4.9.0~install: Returned: code: 0  signal: null
2009 timing action:install Completed in 65885ms

...snip...

2031 silly postinstall node-sass@4.9.0
2032 info lifecycle node-sass@4.9.0~postinstall: node-sass@4.9.0
2033 verbose lifecycle node-sass@4.9.0~postinstall: unsafe-perm in lifecycle true
2034 verbose lifecycle node-sass@4.9.0~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy/node_modules/node-sass/node_modules/.bin:/home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy/node_modules/.bin:/home/connelblaze/google-cloud-sdk/bin:/usr/local/heroku/bin:/home/connelblaze/.rbenv/plugins/ruby-build/bin:/home/connelblaze/.rbenv/shims:/home/connelblaze/.rbenv/bin:/home/connelblaze/mongodb/mongodb-linux-x86_64-ubuntu1604-3.4.4/bin/:/home/connelblaze/node_modules/.bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/connelblaze/android/android-sdk-linux/tools:/home/connelblaze/android/android-sdk-linux/platform-tools:/bin:/home/connelblaze/go/bin:/usr/local/go/bin://home/connelblaze/go/src
2035 verbose lifecycle node-sass@4.9.0~postinstall: CWD: /home/connelblaze/go/src/bitbucket.org/gomarket/go_jessy/node_modules/node-sass
2036 silly lifecycle node-sass@4.9.0~postinstall: Args: [ '-c', 'node scripts/build.js' ]
2037 silly lifecycle node-sass@4.9.0~postinstall: Returned: code: 1  signal: null
2038 info lifecycle node-sass@4.9.0~postinstall: Failed to exec postinstall script
2039 timing action:postinstall Completed in 482ms
```

**Comment by xzyfer** [comment]
It looks like you previously had node-sass@4.7.2 installed.

```
22 silly resolveWithNewModule node-sass@4.9.0 checking installable status
23 silly removeObsoleteDep removing node-sass@4.7.2 from the tree as its been replaced by a newer version or is no longer required
```

Maybe try clearing your cache. 

```
rm -rf node_modules
npm cache clean
```

**Comment by bryantnate** [comment]
Okay... so I'm not sure if my problem is the same as this, but it sure looks similar. I'm using Ubuntu 16.04 and I was about to install "Harp.js" when I ecountered the error.

```
npm WARN optional Skipping failed optional dependency /harp/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.6
npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "harp"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.9.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```
I used the command ***sudo npm install -g harp*** and I found removing the ***sudo*** worked for me.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root
