### ISSUE TITLE
Node sass is searching for node8 binding when i have node 10

### ISSUE THREAD

**Issue by GiancarlosIO** [sass/node-sass#2418]
- NPM version (`npm -v`): 6.1.0
- Node version (`node -v`): 10.4.1
- Node Process (`node -p process.versions`): `{ http_parser: '2.8.0',
  node: '10.4.1',
  v8: '6.7.288.45-node.7',
  uv: '1.20.3',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }`
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): `node-sass	4.9.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
`
- npm node-sass versions (`npm ls node-sass`): 
`├─┬ gulp-sass@2.3.2`
`│   └── node-sass@3.13.1 `
`├── node-sass@4.9.0 `
`└─┬ node-sass-chokidar@1.3.0`
` --└── node-sass@4.9.0 `
`

I'm using child_process.spawn to run webpack programmatically:

`const WEBPACK_DEV_SERVER_PATH = './node_modules/webpack-dev-server/bin/webpack-dev-server.js';`

`spawn(WEBPACK_DEV_SERVER_PATH, [..args], {...spawnOptions});`

and I'm getting the error:
![captura de pantalla de 2018-06-15 12-28-32](https://user-images.githubusercontent.com/17274950/41486113-cd2eb80c-70a8-11e8-8740-e0f810a41572.png)

Why node-sass is looking for node8? I actually have node10
`Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x`

I'm actually have bindings for node10(current version):
`Found bindings for the following environments:`
`  - Linux 64-bit with Node.js 10.x`

I already run: `npm rebuild node-sass --force` but it no resolve the error.

pdt: If I use `npm start` it run without problems, maybe it is related with `spawn` module?

**Comment by xzyfer** [comment]
You must have multiple node versions installed. Check that you'mr editor is
configured to use the system node instead of the embedded Node.

**Comment by GiancarlosIO** [comment]
I don't know why but i just switch to node8, run `npm rebuild node-sass --force` and now the `spawn` command run without problems :thinking: 
Thanks.
