### ISSUE TITLE
fails to download release binary file

### ISSUE THREAD

**Issue by ctimoteo-fixeads** [sass/node-sass#2422]
Hi,

I am trying to download node-sass release 4.9.0 for linux,

Is failing, appears to be some github issue...

The file that I am trying to download is 

[linux-x64-48_binding.node](https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-48_binding.node)

anyone has the same issue?

**Comment by th3battula** [comment]
I'm having the same issue with v3.13.1 - linux-x64-57_binding.node

**Comment by nschonni** [comment]
@th3battula @michaelolo24 3.13.1 never supported Node 8

@ctimoteo-fixeads please fill out the issue template, we have no information to try and troubleshoot when you delete it

**Comment by xzyfer** [comment]
node-sass 3.x only supports node 0.10 and 0.12. It is very old and
unsupported. Please update to node-sass@4.9.9.
