### ISSUE TITLE
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime

### ISSUE THREAD

**Issue by trusktr** [sass/node-sass#2425]
This is the same report as https://github.com/sass/node-sass/issues/1764

But in my case `npm rebuild node-sass` or `rm -rf node_modules/node-sass && npm i` both don't fix the problem in my case.

**Comment by trusktr** [comment]
I'm running this code in electron in 64bit macOS. Not sure if that's related.

**Comment by AElouai** [comment]
I did have the same issue as you but i downgraded the version and it workes perfectly for now 
i hope they fix it soon

**Comment by saper** [comment]
Running node-sass under Ekectron is not supported

**Comment by hssa-saslanka** [comment]
It's working fine.

dependencies :::
Step 1:
"gulp-sass": "^2.0.4"

change this to
"gulp-sass": "^3.1.0"

step 2: now run
$ npm install

in the command prompt
done.
