### ISSUE TITLE
Can't install node-sass 4.9

### ISSUE THREAD

**Issue by gamevnlc** [sass/node-sass#2426]
- NPM version (`npm -v`): 6.1
- Node version (`node -v`): 10.4.1
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.8.0',         
  node: '10.4.1',               
  v8: '6.7.288.45-node.7',      
  uv: '1.20.3',                 
  zlib: '1.2.11',               
  ares: '1.14.0',               
  modules: '64',                
  nghttp2: '1.32.0',            
  napi: '3',                    
  openssl: '1.1.0h',            
  icu: '61.1',                  
  unicode: '10.0',              
  cldr: '33.0',                 
  tz: '2018c' } 
```
- Node Platform (`node -p process.platform`): linux 
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

I tried to install latest version of node-sass but it's not work. i use laradock . 

![image](https://user-images.githubusercontent.com/2215185/41804782-d4e92ff6-76ce-11e8-9f24-93a59d31dc90.png)

**Comment by nschonni** [comment]
Can you reproduce this without "laradock"? The platform and version look compatible, but I have no idea was "laradock" is adding in between the environment.

**Comment by xzyfer** [comment]
Laradock looks looks a linux docker with some stuff to make Laravel work.

I've had a look around and this appears to be a Node issue, not node-sass specific. Typically appears to happen with mounted drives, network drives, SD cards etc. There isn't anything that can change on the node-sass side.

**Comment by atmar** [comment]
Same issue here, can't find a solution anywhere.

**Comment by mehdiBENSMA** [comment]
Same issue for me, i'm working with a docker image based on node:10.7.0-jessie,
(npm: 6.1.0), any idea ? Thanks
