### ISSUE TITLE
how to import cdn css in .scss

### ISSUE THREAD

**Issue by chavesgu** [sass/node-sass#2428]
- NPM version (`npm -v`):5.6.0
- Node version (`node -v`):8.9.4
- Node Process (`node -p process.versions`):{ http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`):darwin
- Node architecture (`node -p process.arch`):64
- node-sass version (`node -p "require('node-sass').info"`):4.9.0
- npm node-sass versions (`npm ls node-sass`):4.9.0

how to import cdn css in .scss？
when i use @import url('some cdn');
throw error can't find path;
but i use this in style lang='scss'    it work success
why?

**Comment by nschonni** [comment]
Importing CSS directly into CSS isn't supported and was removed in the latest release. You can read the details in #2362
