### ISSUE TITLE
Can't install node-sass on Ubuntu (err 405)

### ISSUE THREAD

**Issue by ZPPD** [sass/node-sass#2431]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v10.1.0
- Node Process (`node -p process.versions`): 
```
    { http_parser: '2.8.0',
  node: '10.1.0',
  v8: '6.6.346.27-node.6',
  uv: '1.20.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
```

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

 I have been trying to install node-sass on my UBUNTU 14.04 and I keep getting a 405 err message:
```
$ npm install node-sass
npm ERR! code E405
npm ERR! 405 Method Not Allowed: node-sass@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/puh4o/.npm/_logs/2018-06-30T15_30_59_185Z-debug.log
```
This is the debug log I receive :
https://gist.github.com/ZPPD/6c5970ad6da685e94e374f407330373d

**Comment by nschonni** [comment]
This sounds like a general network/npm issue like https://stackoverflow.com/questions/48915738/npm-err-405-method-not-allowed-expresslatest rather than a problem with node-sass
