### ISSUE TITLE
keep getting error MSB4019 while installing node-sass

### ISSUE THREAD

**Issue by Narasinha** [sass/node-sass#2433]
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 5.2.11
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8 (cli-only)
@angular-devkit/core         0.6.8 (cli-only)
@angular-devkit/schematics   0.6.8 (cli-only)
@schematics/angular          0.6.8 (cli-only)
@schematics/update           0.6.8 (cli-only)
rxjs                         5.5.11
typescript                   2.7.2
webpack                      4.14.0

Not able to install the node-sass .. keep getting error MSB4019. 
node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.
Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Can someone able to help on this?

**Comment by xzyfer** [comment]
What version of node-sass are you trying to install?

**Comment by Narasinha** [comment]
I'm trying to install node-sass 4.9.0

**Comment by xzyfer** [comment]
Please provide the full install output as a github gist.

**Comment by generalov** [comment]
@Narasinha, open Command Prompt as Administrator: [Win+x] -> Command Prompt (Admin) and run the following commands:

    npm install -g --production windows-build-tools
    set VCTargetsPath=%programfiles(x86)%\MSBuild\Microsoft.Cpp\v4.0\V140
    npm install -g node-gyp

then try to install node-sass one more time.

**Comment by codiddle** [comment]
didn't work, also your syntax needs to look more like this:
`set VCTargetsPath=%"programfiles(x86)%\MSBuild\Microsoft.Cpp\v4.0\V140"`

**Comment by codiddle** [comment]
I fixed it by uninstalling node v10...whatever the latest is, and going back to version 8.14 from here https://nodejs.org/dist/latest-v8.x/.  I did start installing VS2015 just because I thought it was trying to target it's C++ libraries... but I don't think that was the fix.  
```
$ npm install

> proj@1.0.0 preinstall C:\ORNLDev\Code\Web\UI
> node ./BuildTools/Scripts/checkVersions

Node version must be at least 8+. Verifying...
CAUTION: Node version should be 8.11.1.
Node version OK. Using v8.14.0
Node is executing from C:\Program Files\nodejs\node.exe
NPM version must be 5+. Verifying...
NPM version OK, using 6.4.1


> node-sass@4.8.3 install C:\dev\Code\Web\UI\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\me\AppData\Roaming\npm-cache\node-sass\4.8.3\win32-x64-57_binding.node

> node-sass@4.8.3 postinstall C:\dev\Code\Web\UI\node_modules\node-sass
> node scripts/build.js

Binary found at C:\dev\Code\Web\UI\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
```

**Comment by codiddle** [comment]
I fixed it by uninstalling node v10...whatever the latest is, and going back to version 8.14 from here https://nodejs.org/dist/latest-v8.x/. I did start installing VS2015 just because I thought it was trying to target it's C++ libraries... but I don't think that was the fix.
```
$ npm install

> proj@1.0.0 preinstall C:\dev\Code\Web\UI
> node ./BuildTools/Scripts/checkVersions

Node version must be at least 8+. Verifying...
CAUTION: Node version should be 8.11.1.
Node version OK. Using v8.14.0
Node is executing from C:\Program Files\nodejs\node.exe
NPM version must be 5+. Verifying...
NPM version OK, using 6.4.1


> node-sass@4.8.3 install C:\dev\Code\Web\UI\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\me\AppData\Roaming\npm-cache\node-sass\4.8.3\win32-x64-57_binding.node

> node-sass@4.8.3 postinstall C:\dev\Code\Web\UI\node_modules\node-sass
> node scripts/build.js

Binary found at C:\dev\Code\Web\UI\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
```

**Comment by trogne** [comment]
Or if using VS 2017 , path is "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets"

**Comment by rosnaib11** [comment]
Node v10.15.0
npm 6.4.1

I also facing this issue now.

Aldready did.

npm install -g --production windows-build-tools
set VCTargetsPath=%programfiles(x86)%\MSBuild\Microsoft.Cpp\v4.0\V140
npm install -g node-gyp

Run admin, reinstall, change privillege of msbuild folder etc. Unlucky.

This node-sass package is the most common issue when I deploy or migrate the project. If its not the version then dependencies. You have to adjust by ur self just to run npm install.

**Comment by Harvzor** [comment]
I was having similar issues when I was using Node `10.15.3`, switched to `8.15.1` and it `npm install`ed correctly.

**Comment by celucode** [comment]
The @generalov comment worked for me. Just make sure to close all consoles before trying to install node-sass again.
