### ISSUE TITLE
tunnel-agent vulnerability issue

### ISSUE THREAD

**Issue by vishnugupta20** [sass/node-sass#2436]
I am getting a vulnerability issue for tunnel agent.  **NODE-SECURITY-598    tunnel-agent    0.4.3**
Here what I get when I execute `npm list tunnel-agent`
├─┬ @angular-devkit/build-angular@0.6.8
│ └─┬ node-sass@4.9.0
│   ├─┬ node-gyp@3.7.0
│   │ └─┬ request@2.81.0
│   │   └── tunnel-agent@0.6.0  deduped
│   └─┬ request@2.79.0
│     └── tunnel-agent@0.4.3 
├─┬ karma@2.0.4
│ └─┬ log4js@2.10.0
│   └─┬ loggly@1.1.1
│     └─┬ request@2.75.0
│       └── tunnel-agent@0.4.3 
└─┬ request@2.87.0
  └── tunnel-agent@0.6.0 

Please suggest me how to fix it.

**Comment by nschonni** [comment]
The 0.4.3 version flagged isn't part of the node-sass package, it uses 0.6.0

**Comment by nschonni** [comment]
Actually, I see it now because the formatting of your issue is hard to read, this is just a variant of #2355 so subscript to that issue
