### ISSUE TITLE
file imported by a custom importer are not being watched

### ISSUE THREAD

**Issue by lokeshdaiya** [sass/node-sass#2449]
I have below files

**test.scss** 

```
@mixin test() {
    .test {
        color: red;
        background: green;
    }
}

@include test();
```
**test1.scss**

```
@import 'test.scss';

.test1 {
    color: blue;
}
```
**test.js**

 ```
var path = require('path');

module.exports = function(file) {console.log('>>>>>>>>>>');
console.log('path is',path.resolve(path.join(process.cwd(), 'test/', file + (path.extname(file) ? '' : '.scss'))));
  return {
      file: path.resolve(path.join(process.cwd(), 'test/', file + (path.extname(file) ? '' : '.scss')))
  };
};
```

when I run the command 

`node-sass test1 --importer test.js -o dist -w`

and make change in test.scss then its not compiling while making changes in test1.scss compiles 

- NPM version (`npm -v`): 5.6
- Node version (`node -v`): v10.0.0
- node-sass version (`node -p "require('node-sass').info"`):4.9.2

**Comment by saper** [comment]
Yes, this is a limitation of the command line interface we have. Watcher currently has no way to figure out what files are used by the custom importer.

Custom importer could in theory load any file and we have no way of knowing this.
