### ISSUE TITLE
C++ errors when using node-sass v4.9.2

### ISSUE THREAD

**Issue by exotype** [sass/node-sass#2451]
- NPM version (`npm -v`): `5.6.0`
- Node version (`node -v`): `v9.11.2`
- Node Process (`node -p process.versions`):
```
{ 
  http_parser: '2.8.0',
  node: '9.11.2',
  v8: '6.2.414.46-node.23',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' 
}
```
- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.9.2	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):

```
My Project...
├─┬ gulp-sass@2.3.2
│ └── node-sass@3.13.1
└── node-sass@4.9.2
```

I'm encountering the following errors 

`libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector`

and

`[1]    74423 segmentation fault  npm run watch`

Whenever i try to run my scripts using this version of `node-sass` i've been forced to remove my caret in package.json and strictly define my node-sass version as v4.7.2 and now it works.

**Comment by exotype** [comment]
Might be worth mentioning that i'm running `node-sass` in this case through Webpack ^2.3.0 and it's Sass-loader ^6.0.6, maybe this version of node-sass doesn't work right in Webpack 2?

**Comment by nschonni** [comment]
you have a reference to `gulp-sass` running an old version that is incompatible with Node 9

**Comment by xzyfer** [comment]
It's possible node is trying to load both versions of node-sass and causing
issues.

It's also possible you have some weird Sass code that is causing and
unhandled error in node-sass.

Are you able to remove everything that isn't node-sass and see if the error
still happens?

**Comment by exotype** [comment]
As @nschonni pointed out it seems to be `gulp-sass` that causes the issue, if i update `gulp-sass` the issue goes away.
Thanks for your help
