### ISSUE TITLE
Specify node-sass binary location via file path and not HTTP

### ISSUE THREAD

**Issue by croucha** [sass/node-sass#2455]
Hi, 

I'm just wondering why the only option to fetch the node sass binaries is through HTTP with the option to give an alternative HTTP url for them.  How come I just can't download the ones for my project and put something in .npmrc to specify where they are on the file system?  

I thought sass_binary_path or sass_binary_dir would solve this but it seems those two options just allow you to determine where the binaries will store after their download.

Thanks,

Andre

**Comment by xzyfer** [comment]
SASS_BINARY_DIR should do what you're after. Make sure it's an absolute path, and that the binary name is unchanged.

**Comment by croucha** [comment]
Interesting.  I did try that and I get the following error:

![node-sass-binary-issue](https://user-images.githubusercontent.com/2465008/42975678-150d7448-8b83-11e8-8668-5f5ce262b10a.png)

My npmrc looks like this:

![npmrc](https://user-images.githubusercontent.com/2465008/42975744-8ba89542-8b83-11e8-9c32-b50d3d4d52e3.png)

**Comment by xzyfer** [comment]
Try using an environment variable. I don't believe we supply .npmrc

**Comment by croucha** [comment]
Thanks @xzyfer, I'll give it a try.  However, it seems documented here as an .npmrc value:

https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by nschonni** [comment]
Can you supply the value you set and an annonimized gist for the log. It's hard do go off screenshots

**Comment by croucha** [comment]
Hi @xzyfer.  I created an environmental variable as you advised but ran into a different error.   I believe we might have a bug on our hands?  Hopefully, you can reproduce?

![node_sass_fun](https://user-images.githubusercontent.com/2465008/42976522-925c939e-8b87-11e8-811f-01bc6ea08505.png)
![capture](https://user-images.githubusercontent.com/2465008/42976525-94713356-8b87-11e8-8126-0c9670db97c5.PNG)

**Comment by nschonni** [comment]
It also seems like the value you might want to set is `SASS_BINARY_PATH` not `DIR`

**Comment by croucha** [comment]
I've tried path too but it always wants to download for the first time.

**Comment by croucha** [comment]
Thanks @nschonni  and @xzyfer, if I set both path and dir (.npmrc), using the same absolute path, it seems to work but feels wrong?  Shouldn't it just be one config value and done?

![node-sass-super-fun](https://user-images.githubusercontent.com/2465008/42976692-ae97fb42-8b88-11e8-9f09-0af5daabfbc5.png)

sass_binary_path = C:\gitprojects\mySecrectPath\nodeSass\win32-x64-57_binding.node
sass_binary_dir = C:\gitprojects\mySecrectPath\nodeSass\win32-x64-57_binding.node

**Comment by nschonni** [comment]
Maybe, I've never really used those variables. For my offline machines I actually just stuff the binary in the NPM cache on any offline machines so the install just picks it up after I do that once for the Node/Node-Sass combo.
I'm taking a look at the docs now though

**Comment by xzyfer** [comment]
SASS_BINARY_DIR is exactly that, a directory. The binary name will be appended to the resolved directly.

If you want alter the binary name for some reason use SASS_BINARY_NAME (don't do this).

**Comment by xzyfer** [comment]
I have using these options all week so I'm certain they work :)

**Comment by croucha** [comment]
yeah, it's not working.  Even when I just give the path, I get a maximum call stack exceeded.  @nschonni, I've thought about going the npm-cache route too.  However, it does work if I give both the path and dir with absolute path to file so at least that counts for something but seems pretty wonky.  Should just be one simple option.

**Comment by croucha** [comment]
I have to say this thing with configuring binaries is extremely annoying when stuck behind a firewall.  I don't understand why they just can't be part of the project unless it's related to versioning and file size?

**Comment by xzyfer** [comment]
SASS_BINARY_PATH is the absolute path of the binary file i.e. 
```sh
SASS_BINARY_PATH=/tmp/test/darwin-x64-57_binding.node npm install node-sass
```

SASS_BINARY_DIRECTORY is the absolute path to alternate location for the binaries instead to `node-sass/vendor`
```sh
SASS_BINARY_PATH=/tmp/test npm install node-sass
```

The binary path is a directory that is expected to mirror the layout of vendor i.e.
```
$ ls test
darwin-x64-57
$ ls test/darwin-x64-57
binding.node
```

>I don't understand why they just can't be part of the project unless it's related to versioning and file size?

Because no one wants to install 100s of mbs of binaries - https://github.com/sass/node-sass/releases/tag/v4.9.2

If you can do bette we welcome your PR.

**Comment by croucha** [comment]
That great it works for you in OSX @xzyfer.  I doesn't in windows and I would not considered this closed.

**Comment by xzyfer** [comment]
Please read my previous comment. It's clear from your screen shot above you've setting `SASS_BINARY_DIR` incorrectly.

If you're using `SASS_BINARY_DIR` it's expected that inside that directly there is `win32-x64-57/binding.node`. The `SASS_BINARY_DIR` **must not** include the `win32-x64-57/binding.node`.

Alternatively user `SASS_BINARY_PATH` to the full path to the `.node` file.

**Comment by croucha** [comment]
I've tried SASS_BINARY_PATH stand alone and it always tries to download.  I think there is something wrong with your code.  What I require only works when both SASS_BINARY_DIR and SASS_BINARY_PATH are included.   I think there's a malfunction in the code related to when it has to choose to download or not and saving that binary to a location for use later.

**Comment by jonasohrn** [comment]
I've struggeled with this too for too long until I found a solution using the "cache_dir"-config:
In project_root/.npmrc:
sass_binary_cache=../../myNpmCacheDir/node-sass/vendor
in project_root/myNpmCacheDir/node-sass/vendor I put the cached binary(ies) in the following structure:
node-sass/4.10.0/win32-x64-64_binding.node
Complete path:
`project_root/myNpmCacheDir/node-sass/vendor/node-sass/4.10.0/win32-x64-64_binding.node
`which will only then be used by the package.json-install-script

I wasn't very well documented so it's probably better and easier to write example configs instead of trying to explain the structure in docs.

**Comment by jtmcn** [comment]
This took me a while to get right as well. It's not stated in the documentation, but as said above `SASS_BINARY_DIR` expects a specific directory structure.

For example, with node-sass 4.10.0 you'd download the binary:
[v4.10.0/linux-x64-57_binding.node](https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-57_binding.node)

Rename the file to `binding.node` and place it in a new folder `linux-x64-57`.

If using `/opt/lib` the full binary path would be `/opt/lib/node-sass/linux-x64-57/binding.node`

Used with the environment variable:
`SASS_BINARY_PATH=/opt/lib/node-sass`

**Comment by OutgoingOpossum** [comment]
For those having the same issue and looking for the official documentation of these variables, see https://github.com/sass/node-sass/tree/master#binary-configuration-parameters
