### ISSUE TITLE
@each looping through variable declarations doesn't work in node-sass 4.9.2

### ISSUE THREAD

**Issue by culshaw** [sass/node-sass#2458]
- NPM version (`npm -v`): `5.6.0`
- Node version (`node -v`): `9.11.1`
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '9.11.1',
  v8: '6.2.414.46-node.23',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
```
- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`): `4.9.2`
- npm node-sass versions (`npm ls node-sass`): `└── node-sass@4.9.2`

The following expression doesn't work in `4.9.2`. It works as expected in `4.7.2`. It hasn't worked since `4.8.0` (Also tested in `4.8.1`, `4.8.3`, `4.9.0`, `4.9.2`)

https://www.sassmeister.com/gist/336a7d9871344d4bf9fb7f47641a1d0a

### Source
```
:root {
  $colors: (
        lightgreen1: #47d7ac,
        lightgreen2: #5ddfbd,
        lightgreen3: #91e7cd,
        lightgreen4: #b5efde,
        lightgreen5: #daf7ee,
        darkgreen1: #0bbf91,
        darkgreen2: #1ca683,
        darkgreen3: #88b4a9,
        darkgreen4: #289071,
    );

    @each $color, $colorValue in $colors {
        --color-#{$color}: $colorValue;
    }
}
```

### Expected output
```
:root {
  --color-lightgreen1: #47d7ac;
  --color-lightgreen2: #5ddfbd;
  --color-lightgreen3: #91e7cd;
  --color-lightgreen4: #b5efde;
  --color-lightgreen5: #daf7ee;
  --color-darkgreen1: #0bbf91;
  --color-darkgreen2: #1ca683;
  --color-darkgreen3: #88b4a9;
  --color-darkgreen4: #289071;
}

```
### Actual output (`4.9.2`)
```
:root  {
  --color-lightgreen1: $colorValue;
  --color-lightgreen2: $colorValue;
  --color-lightgreen3: $colorValue;
  --color-lightgreen4: $colorValue;
  --color-lightgreen5: $colorValue;
  --color-darkgreen1: $colorValue;
  --color-darkgreen2: $colorValue;
  --color-darkgreen3: $colorValue;
  --color-darkgreen4: $colorValue;
}
```

**Comment by xzyfer** [comment]
The old behaviour was a bug which you can confirm in your sassmeister gist by using Sass 3.5, LibSass, or Dart Sass.

In order to full support CSS custom properties Sass cannot parse the value of the custom property declaration. We make an exception for interpolation (`#{}`).

```scss
    @each $color, $colorValue in $colors {
        --color-#{$color}: #{$colorValue};
    }
```

**Comment by lsadam0** [comment]
@xzyfer While I completely agree that adhering to the standard is better, this qualifies as a breaking change.  Does node-sass not use semantic versioning for releases?

**Comment by nschonni** [comment]
Not when libsass was doing the wrong think unintentionally. This was related to another one of those bug/features but covers it pretty well https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9
