### ISSUE TITLE
Security vulnerability in node-sass 

### ISSUE THREAD

**Issue by abhinukala** [sass/node-sass#2466]
- NPM version (`npm -v`):6.1.0
- Node version (`node -v`):10.5.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.5.0',
  v8: '6.7.288.46-node.8',
  uv: '1.20.3',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`): 
node-sass       4.9.2   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):-- node-sass@4.9.2

There is a vulnerability in the hoek package which is used by node-sass. 

npm-audit security report:

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   node-sass [dev]

  Path            node-sass > node-gyp > request > hawk > boom > hoek

  More info       https://nodesecurity.io/advisories/566

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   node-sass [dev]

  Path            node-sass > node-gyp > request > hawk > cryptiles > boom >
                  hoek

  More info       https://nodesecurity.io/advisories/566

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   node-sass [dev]

  Path            node-sass > node-gyp > request > hawk > hoek

  More info       https://nodesecurity.io/advisories/566

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   node-sass [dev]

  Path            node-sass > node-gyp > request > hawk > sntp > hoek

  More info       https://nodesecurity.io/advisories/566

found 4 moderate severity vulnerabilities in 9425 scanned packages
  4 vulnerabilities require manual review. See the full report for details.

I have tried to downgrade to 4.7.0 as suggested in the [issue2355](https://github.com/sass/node-sass/issues/2355) but it was still installing the latest version(4.9.2).

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/2355#issuecomment-407949157
