### ISSUE TITLE
Can you bundle binding.node as part of node-saas node module instead of downloading at install time

### ISSUE THREAD

**Issue by tnpradeep** [sass/node-sass#2468]
Hi,

during install of node-saas module, the scrip is downloading binding.node file (https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-48_binding.node).

In case of corporate network this call is blocked by firewall.
Is it possible to bundle all required files as part of node module available in npm registry ?

Thanks
Pradeep

**Comment by xzyfer** [comment]
We would need to bundle 60+ bindings. See https://github.com/sass/node-sass/releases/tag/v4.9.2

You can use the following options to use a local or offline mirror: https://github.com/sass/node-sass#binary-configuration-parameters

Or use HTTP_PROXY or HTTPS_PROXY to configure your proxy.

**Comment by hamzahamidi** [comment]
Any documentation please on how to use  local or offline mirror: https://github.com/sass/node-sass#binary-configuration-parameters ?
