### ISSUE TITLE
node-sass doesn't work on Ubuntu-18, with node version 10.6.0 and npm version 6.1.0

### ISSUE THREAD

**Issue by ganeshdeshmukh1612** [sass/node-sass#2469]
from [troubleshooting](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) guide I have given my configuration and machine's details as follows.
```

gd@gd10:~/Desktop/portfolio/portfolio$ npm -v
6.1.0
gd@gd10:~/Desktop/portfolio/portfolio$ node -v
v10.6.0
gd@gd10:~/Desktop/portfolio/portfolio$ node -p process.versions
{ http_parser: '2.8.0',
  node: '10.6.0',
  v8: '6.7.288.46-node.13',
  uv: '1.21.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
gd@gd10:~/Desktop/portfolio/portfolio$ node -p process.platform
linux
gd@gd10:~/Desktop/portfolio/portfolio$ node -p process.arch
x64
gd@gd10:~/Desktop/portfolio/portfolio$ npm ls node-sass
portfolio@1.0.0 /home/gd/Desktop/portfolio/portfolio
└── node-sass@4.9.2

gd@gd10:~/Desktop/portfolio/portfolio$ node -p "require('node-sass').info"
node-sass       4.9.2   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
gd@gd10:~/Desktop/portfolio/portfolio$ npm ls node-sass
portfolio@1.0.0 /home/gd/Desktop/portfolio/portfolio
└── node-sass@4.9.2

gd@gd10:~/Desktop/portfolio/portfolio$
```

when I run command as `node-sass -w scss/ -o dist/css/ --recursive`, it stucks and doesn't proceeds.
no any main.css file is generated in ` dist/css ` folder

**Comment by nschonni** [comment]
Watch (`-w`) does not compile the file till it is touched, you need to compile first if you're expecting the file to be there without you changing the file

**Comment by ganeshdeshmukh1612** [comment]
thanks @nschonni for reply , 
I have written code in `main.scss` and then I ran command `node-sass -w scss/ -o dist/css/  --recursive`

after running It should have compiled, as expected.

if I am wrong,  please explain how can I do it, 
how can I compile it then?

**Comment by mihinduranasinghe** [comment]
Same issue
