### ISSUE TITLE
nvm node is recognised by npm install script.

### ISSUE THREAD

**Issue by AjayChoudary** [sass/node-sass#2470]
- NPM version (`npm -v`): 6.1.0
- Node version (`node -v`): v10.7.0
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '10.7.0',
  v8: '6.7.288.49-node.15',
  uv: '1.22.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- npm node-sass versions (`npm ls node-sass`): missing: node-sass@4.9.0, required by @angular/cli@1.6.5
- PATH (`echo $PATH`): /root/.nvm/versions/node/v10.7.0/bin:/sbin:/bin:/usr/sbin:/usr/bin

I installed node with `nvm install`  and PATH variable is having node
When try to install node-sass, install script is not able to identify node command.
Note: I am doing all these activity in root shell

### **Command Output:**
$ npm install node-sass

\> node-sass@4.9.2 install /home/ajayg/Kora-Web/node_modules/node-sass
\> node scripts/install.js

sh: node: command not found
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-sass@4.9.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.9.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-08T13_59_17_167Z-debug.log

### **Log:**
1772 warn ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
1773 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
1774 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1775 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1775 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1775 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1775 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1776 verbose stack Error: node-sass@4.9.2 install: `node scripts/install.js`
1776 verbose stack spawn ENOENT
1776 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
1776 verbose stack     at ChildProcess.emit (events.js:182:13)
1776 verbose stack     at maybeClose (internal/child_process.js:961:16)
1776 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
1777 verbose pkgid node-sass@4.9.2
1778 verbose cwd /home/ajayg/Kora-Web
1779 verbose Linux 3.10.0-514.el7.x86_64
1780 verbose argv "/root/.nvm/versions/node/v10.7.0/bin/node" "/root/.nvm/versions/node/v10.7.0/bin/npm" "install" "node-sass"
1781 verbose node v10.7.0
1782 verbose npm  v6.1.0
1783 error file sh
1784 error code ELIFECYCLE
1785 error errno ENOENT
1786 error syscall spawn
1787 error node-sass@4.9.2 install: `node scripts/install.js`
1787 error spawn ENOENT
1788 error Failed at the node-sass@4.9.2 install script.
1788 error This is probably not a problem with npm. There is likely additional logging output above.
1789 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
Sorry, if it's not in the path, there is no way for the install scripts to use them. This would be true for any other project

**Comment by AjayChoudary** [comment]
I already below $PATH value in the issue description.
$`echo $PATH`
/root/.nvm/versions/node/v10.7.0/bin:/sbin:/bin:/usr/sbin:/usr/bin
$ `which node`
/root/.nvm/versions/node/v10.7.0/bin/node
$ `which npm`
/root/.nvm/versions/node/v10.7.0/bin/npm

node is available in the PATH, but still it is not picking.

I found a workaround
`npm install --unsafe-perm node-sass`

But my question is, why should i pass `--unsafe-perm` ?

**Comment by xzyfer** [comment]
npm runs life cycle scripts as a restricted user. If that user doesn't have
the appropriate permissions you'll need --unsafe-perms. This is why you
should never run npm as sudo.
