### ISSUE TITLE
Question: What's the number at the end of the binary filenames mean?

### ISSUE THREAD

**Issue by tonst79** [sass/node-sass#2471]
Sorry for the stupid question but what does the number on the end of the filename of the binaries indicate?

i.e. within 4.9.0
win32-x64-48_binding.node
win32-x64-57_binding.node

I ask because my machine, via npm, gets the 48 one rather than the 57 one that my colleagues are getting. npm is configured to get 4.9.0.

Thanks

**Comment by nschonni** [comment]
That is the "Module Version"/C++ ABI. You can see what version corresponds to the Node version here https://nodejs.org/en/download/releases/

**Comment by tonst79** [comment]
Thank you, it all makes sense now!
