### ISSUE TITLE
Updating node-gyp to v3.8.0

### ISSUE THREAD

**Issue by Berkmann18** [sass/node-sass#2473]
Since there were security vulnerabilities (related to `node-gyp`) that are now supposedly fixed as of `node-gyp@3.8.0` (cf. [this PR](https://github.com/nodejs/node-gyp/pull/1492)) and that #2443 was closed due to an "out of control" situation which should be back under the collaborators' control, I opened this issue as a reminder so the vulnerability warnings would be resolved.

**Comment by nschonni** [comment]
Duplicate of #2472 and #2355
