### ISSUE TITLE
unable to save binary due to EACCESS installing  node-sass on FreeBSD

### ISSUE THREAD

**Issue by tsgan** [sass/node-sass#2475]
```
npm -v
6.3.0

node -v
v6.14.3

node -p process.versions
{ http_parser: '2.8.0',
  node: '6.14.3',
  v8: '5.1.281.111',
  uv: '1.22.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  icu: '62.1',
  modules: '48',
  napi: '3',
  openssl: '1.0.2k-freebsd' }

node -p process.platform

freebsd

node -p process.arch
x64

...
> node-sass@4.9.3 install /usr/home/ateam-local/foreman/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/home/ateam-local/foreman/node_modules/node-sass/vendor/freebsd-x64-48 : { Error: EACCES: permission denied, mkdir '/usr/home/ateam-local/foreman/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:932:18)
    at sync (/usr/home/ateam-local/foreman/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/home/ateam-local/foreman/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/home/ateam-local/foreman/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/home/ateam-local/foreman/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/home/ateam-local/foreman/node_modules/node-sass/vendor' }
> node-sass@4.9.3 install /usr/home/ateam-local/foreman/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/home/ateam-local/foreman/node_modules/node-sass/vendor/freebsd-x64-48 : { Error: EACCES: permission denied, mkdir '/usr/home/ateam-local/foreman/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:932:18)
    at sync (/usr/home/ateam-local/foreman/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/home/ateam-local/foreman/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/home/ateam-local/foreman/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/home/ateam-local/foreman/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/home/ateam-local/foreman/node_modules/node-sass/vendor' }
```

**Comment by xzyfer** [comment]
```
Error: EACCES: permission denied, mkdir '/usr/home/ateam-local/foreman/node_modules/node-sass/vendor'
```
You need to fix your permissions. Make sure you're not running npm as sudo.

**Comment by yogeshpatil143** [comment]
HI ALL,

Please add below command on your folder.
 sudo npm install -g --unsafe-perm node-sass.
 it's working 100%.

**Comment by RaphiStein** [comment]
@xzyfer make sure you are **not** using `sudo` ??

**Comment by akshay27395** [comment]
U may give permission to the user -
In linux - Ubuntu 18.04
ll -thr    // to see the list of folders and there permissions.

sudo chown -R $USER:$USER ICICI_UI/      //To give permission to the user.

**Comment by mecharmor** [comment]
> U may give permission to the user -
> In linux - Ubuntu 18.04
> ll -thr // to see the list of folders and there permissions.
> 
> sudo chown -R $USER:$USER ICICI_UI/ //To give permission to the user.

This worked for me!!!
For those running into the issue with `mkdir` failure, please check if your user OWNS that folder by running the command `ll`. The fix for me was to simply run npm install on my project. DONT RUN AS SUDO. if you run as sudo it creates directories owned by `root` which cannot be used by your local user so the directories fail to create. I Hope this helps!!!!

**Comment by Ale-cc** [comment]
> HI ALL,
> 
> Please add below command on your folder.
> 
> sudo npm install -g --unsafe-perm node-sass
> 
> it's working 100%.

It works， thx!!
`sudo npm install --unsafe-perm sass sass-loader node-sass wepy-compiler-sass`

**Comment by vicmajri** [comment]
> > HI ALL,
> > Please add below command on your folder.
> > sudo npm install -g --unsafe-perm node-sass
> > it's working 100%.
> 
> It works， thx!!
> `sudo npm install --unsafe-perm sass sass-loader node-sass wepy-compiler-sass`

THANKS IT FINELY WORKS!!!

**Comment by kwende** [comment]
> @xzyfer make sure you are **not** using `sudo` ??
> 
> That's not intuitive (but you're right)

Why is this an issue when running as root? I understand it's not a good idea to run as root, but I'm curious _why_ this becomes a problem when running as such. Is something explicitly prevented when running as root?

**Comment by xzyfer** [comment]
It _can_ be an issue because the downloaded binary is written to dial with permissions that prevent non-root users executing it. This becomes an issue if you're not also running your node process as root.

If you're doing everything as root by default then you won't encounter this issue.

**Comment by OpsAhmad** [comment]
`sudo chmod -R 777 /folder-project`

`npm i`

**Comment by yueyesuifeng** [comment]
> `sudo chmod -R 777 /folder-project`
> 
> `npm i`

It works. very thanks.
