### ISSUE TITLE
v4.9.3 has no compatibility table, postinstall fails

### ISSUE THREAD

**Issue by DzmVasileusky** [sass/node-sass#2476]
Node 8.10.0
NPM 6.2.0

> node-sass@4.9.3 postinstall /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-sass
> node scripts/build.js

Building: /Users/dzmvasilevsky/.nvm/versions/node/v8.10.0/bin/node /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/Users/dzmvasilevsky/.nvm/versions/node/v8.10.0/bin/node',
gyp verb cli   '/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.10.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:13:12)\n    at F (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:68:19)\n    at E (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:80:29)\n    at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/which/which.js:89:16\n    at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/isexe/index.js:42:5\n    at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.10
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.10.0
gyp verb command install [ '8.10.0' ]
gyp verb install input version string "8.10.0"
gyp verb install installing version: 8.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.10.0
gyp verb build dir attempting to create "build" dir: /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-sass/build'
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/dzmvasilevsky/.nvm/versions/node/v8.10.0/bin/node" "/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-sass
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

**Comment by xzyfer** [comment]
Compatibility is the same as the previous version. I'll add the table.


```
EACCES: permission denied, mkdir '/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/node-sass/build'
```
You need to fix permissions and make sure you're not running npm as sudo.
