### ISSUE TITLE
Unable to update to 3.13.1: Missing file from release 3.13.1: win32-x64-57_binding.node

### ISSUE THREAD

**Issue by ericnewton76** [sass/node-sass#2484]
```
node --version
8.11.4
npm --version
5.6.0
```

Problem installing node-sass@3.13.1

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

and I didn't have python on this machine so the install failed.

First Question: what is the source of the 57 in "win32-x64-57_binding.node" is it wise to just modify it to 51?   Is the 57 related to the node version 8.11?

**Comment by ericnewton76** [comment]
Wanted to log this for posterity.

Next course of action is to add python2 to this machine.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404-downloading-bindingnode-file
