### ISSUE TITLE
Replace async-foreach?

### ISSUE THREAD

**Issue by honzajavorek** [sass/node-sass#2487]
This project is using `async-foreach`, which is an unlicensed and unmaintained package. Is it possible to replace it? I see @EightArmCode is trying to fix the situation here https://github.com/cowboy/javascript-sync-async-foreach/pull/10 but that's unlikely to get merged and released as @cowboy [did not touch the project for 5 years](https://github.com/cowboy/javascript-sync-async-foreach/graphs/contributors).

Technically it is illegal to dynamically link code without explicit license, which renders `node-sass` unusable in any environment where people care about licensing.

**Comment by nschonni** [comment]
Looks like it's used in the CLI bin file only https://github.com/sass/node-sass/blob/d3aebe72d2735b79e68019b3801000fe8178f18b/bin/node-sass
Happy to review something that replaces the functionality. Not sure if this was used for old Node compatibility, if so we might be able to take an ES6+ patch in the v5 branch

**Comment by honzajavorek** [comment]
To me the easiest and I believe drop-in replacement would be `var forEach = require('async/each')` https://caolan.github.io/async/docs.html#each

**Comment by cowboy** [comment]
Please use a different library. There are much better choices than that code I wrote seven years ago.

Also, the node-sass project maintainers should consider dropping support for very old versions of node. Doing so will decrease the costs of maintaining the project. I recommend looking at other projects that are likely to be used with node-sass. For example, webpack, babel and eslint all appear to require node 6+.

**Comment by xzyfer** [comment]
We will be dropping support for node < 6 in v5

**Comment by xzyfer** [comment]
Addressed this in #2312

**Comment by xzyfer** [comment]
Fixed in #2312
