### ISSUE TITLE
Module build failed: Error: Missing binding /app/client/node_modules/node-sass/vendor/linux-x64-64/binding.node

### ISSUE THREAD

**Issue by Jeerjmin** [sass/node-sass#2490]
- NPM version (`npm -v`): 6.1.0
- Node version (`node -v`): 10.6.0
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '10.6.0',
  v8: '6.7.288.46-node.13',
  uv: '1.21.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
node-sass	4.9.3	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):node-sass@4.9.3 

I have trouble with deploying to heroku.

> 
> /src/style2/index.scss
> Module build failed: Error: Missing binding /app/client/node_modules/node-sass/vendor/linux-x64-64/binding.node
> Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x
> 
> Found bindings for the following environments:
>   - OS X 64-bit with Node.js 10.x
> 
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass` to download the binding for your current environment.

I re-read many topics with same problem, but 
these solutions do not help:
sudo npm rebuild node-sass --force 
sudo rm -rf node_modules    &&  npm install

In path myproject/node_modules/node-sass/vendor there is only one folder darwin-x64-64.
I think this is the problem, beacuse on heroku's server installed linux. How install multiplatform node_sass in node_modules? Or how to solve the problem differently?
Thank you!

**Comment by xzyfer** [comment]
Looks like you're sending your node_modules directory to heroku which you should avoid. If you must continue to do this (please stop doing this) you'll need to force npm to reinstall node-sass. You can do this by running this command inside the heroku container.

```sh
npm rebuild node-sass
```
The easiest way to do this with heroku is probably to add the command a postinstall script in your package.json.

```json
{
  ...
  "scripts": {
    "postinstall": "npm rebuild node-sass"
  }
}
```

Again, this probably goes away if you stop sending your node_modules folder to heroku. Heroku by default will do the right thing and run `npm install` for you.
