### ISSUE TITLE
Node-sass@4.9.3 not installing in ubuntu 18.04

### ISSUE THREAD

**Issue by pedrro** [sass/node-sass#2493]
- NPM version (`npm -v`): 6.3.0
- Node version (`node -v`): 8.11.3
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

```
- Node Platform (`node -p process.platform`): linux @ ubuntu 18.04

- Node architecture (`node -p process.arch`): x64

# Error trace

> 
> verb build dir attempting to create "build" dir: /home/pedrosilva/Projects/afropython-site/node_modules/node-sass/build
> gyp ERR! configure error 
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pedrosilva/Projects/afropython-site/node_modules/node-sass/build'
> gyp ERR! System Linux 4.15.0-33-generic
> gyp ERR! command "/usr/bin/node" "/home/pedrosilva/Projects/afropython-site/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /home/pedrosilva/Projects/afropython-site/node_modules/node-sass
> gyp ERR! node -v v8.11.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> Build failed with error code: 1
> npm WARN AfroPython@1.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-sass@4.9.3 postinstall script.

**Comment by xzyfer** [comment]
EACCES: permission denied, mkdir '/home/pedrosilva/Projects/
afropython-site/node_modules/node-sass/

Fix your permissions and make sure you're running npm as sudo.
