### ISSUE TITLE
Clone a project from git and use npm install, error to install node-sass

### ISSUE THREAD

**Issue by choi12191995** [sass/node-sass#2495]
- NPM version (`npm -v`): 6.2.0
- Node version (`node -v`): 8.11.3
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
module.js:549
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:466:27)

- npm node-sass versions (`npm ls node-sass`):
/Users/mango
└── (empty)

In package.json:
![image](https://user-images.githubusercontent.com/31662836/45544616-5f413600-b84a-11e8-970c-0b4cf87794ae.png)

Then, I `sudo npm install` in my mac. It happend error on installing node-sass, the error:
> node-sass@4.9.2 install /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/vendor' }

> node-sass@4.9.2 postinstall /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:13:12)\n    at F (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:68:19)\n    at E (/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:80:29)\n    at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/which/which.js:89:16\n    at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/isexe/index.js:42:5\n    at /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.3
gyp verb command install [ '8.11.3' ]
gyp verb install input version string "8.11.3"
gyp verb install installing version: 8.11.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.3
gyp verb build dir attempting to create "build" dir: /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass/build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mango/Desktop/Working Desk/Client Reg Form Revamp/clone/frontend/node_modules/node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mango/.npm/_logs/2018-09-14T10_09_20_725Z-debug.log

Error log from node:
[https://file.io/qaBcss](url)

**Comment by xzyfer** [comment]
The docs explicitly say to not install with sudo..please read the issue
template before opening issues.

**Comment by xzyfer** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md
