### ISSUE TITLE
Update request to 2.88

### ISSUE THREAD

**Issue by Gwerlas** [sass/node-sass#2496]
The package `extend 3.0.1`, which is a dependency of `request 2.87` has a vulnerability :
https://hackerone.com/reports/381185

Is it possible to upgrade ro `request 2.88` which has fix his own `package.json` to use the fixed `extend 3.0.2` ?

**Comment by xzyfer** [comment]
PRs welcome. If CI is happy we're happy to merge it.

**Comment by drakonen** [comment]
Is there a release with this fix?

**Comment by Gwerlas** [comment]
Not yet.

I don't know who can make a new release.

**Comment by drakonen** [comment]
@xzyfer Is there a release planned with this fix? I'd like to use a release instead of a git commit in my package.json.

**Comment by danconnell** [comment]
Sorry to do this, but: @xzyfer @andre @deanmao @bwilkins @keithamus @LaurentGoderre @nschonni @adamyeats @am11 

Can someone please release this to npm?

**Comment by xzyfer** [comment]
v4.9.4 released

**Comment by gaz77a** [comment]
https://github.com/angular/angular/issues/21202
As you can see in the link above, there is a similar issue where upgrading `request` module from 2.87.0 to 2.88.0 also introduces the punycode module `v2.1.1` which [dropped support for IE11 in `v2.0.0`](https://github.com/bestiejs/punycode.js/releases/tag/v2.0.0).

```
├─┬ node-sass@3.13.1
│ └─┬ request@2.88.0
│   ├─┬ har-validator@5.1.3
│   │ └─┬ ajv@6.10.0
│   │   └─┬ uri-js@4.2.2
│   │     └── punycode@2.1.1 
```
Can you suggest how we can fix this for `node-sass@3.13.1` without upgrading it to a major version.

**Comment by nschonni** [comment]
The version of `request` that node-sass uses should have no affect on your application if you require a particular version for your app. EX: set your `request` version in you package.json and NPM will separate out node-sass and your apps version

**Comment by gaz77a** [comment]
Thanks @nschonni, your suggestion worked perfectly! I'm certainly impressed by the quick turnaround of the contributors of this project :)
