### ISSUE TITLE
Getting 404 downloading node-sass v3.13.1

### ISSUE THREAD

**Issue by cjo2118** [sass/node-sass#2499]
We have a dependency (gulp-helpers) which depends on node-sass. Today downloading the binary file https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node stopped working - we get a 404. 

Node - 8.10
npm - 5.6.0
Node Process -
 `{ http_parser: '2.7.0',
  node: '8.10.0',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }`

Node process platform - linux
Node architecture - x64
Node-sass version threw error:

`node -p "require('node-sass').info"`
`module.js:549
    throw err;
    ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)`

----------
this is what we see in our build using CircleCi - 

`Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 

HTTP error 404 Not Found`

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404-downloading-bindingnode-file

**Comment by kodsaikiran** [comment]
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install"

Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node": 

I'm getting this error. Please help me how to solve this.

**Comment by xzyfer** [comment]
You need to upgrade to node-asass@4.13.0
