### ISSUE TITLE
node-sass --watch doesn't work for directories

### ISSUE THREAD

**Issue by peterjmag** [sass/node-sass#250]
I noticed that the `--watch` command line switch added by #147 isn't documented in README.md, so I was going to fork and add it, but shortly realized that  `--watch` doesn't actually seem to work. A couple issues here:

First of all, I imagine that `node-sass --watch` should work without specifying an input file, like [the SASS Ruby gem](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#using_sass). However, it doesn't appear to work that way:

```
peterjmag@peterjmags-iMac ~/node/node-sass-watch 
$ node-sass --watch scss/
Compile .scss files with node-sass.
Usage: node-sass [options] <input.scss> [<output.css>]

Options:
[...]

Argument check failed: function (argv){
    if (argv.help) { return true; }
    if (argv._.length < 1) { return false; }
  }
peterjmag@peterjmags-iMac ~/node/node-sass-watch 
$ node-sass --watch=scss/
Compile .scss files with node-sass.
Usage: node-sass [options] <input.scss> [<output.css>]

Options:
[...]

Argument check failed: function (argv){
    if (argv.help) { return true; }
    if (argv._.length < 1) { return false; }
  }
```

If I then add an input file argument (a dummy file for instance, just to satisfy the requirement), I get the following:

```
peterjmag@peterjmags-iMac ~/node/node-sass-watch 
$ ls scss/
test.scss  test2.scss
peterjmag@peterjmags-iMac ~/node/node-sass-watch 
$ node-sass scss/ --watch=scss/
error reading file "scss/"

peterjmag@peterjmags-iMac ~/node/node-sass-watch 
$ node-sass scss/test.scss --watch=scss/
Rendering Complete, saving .css file...
Wrote CSS to /Users/admin/node/node-sass-watch/test.css
[saved a minor change to test2.scss, which triggers the following]
NaN
Rendering Complete, saving .css file...
Wrote CSS to /Users/admin/node/node-sass-watch/test.css
[saved test2.scss again]
NaN
Rendering Complete, saving .css file...
Wrote CSS to /Users/admin/node/node-sass-watch/test.css
```

It's also entirely possible that I'm missing something obvious here, so let me know if that's the case. Either way, I'm happy to update the docs once this is resolved! :-)

**Comment by CrowdHailer** [comment]
I also don't think the watch option works as expected. I am using version 3.0.0 of node-sass
this command works fine
```
./node_modules/.bin/node-sass src/styles/ -o www/styles/
```
however the same with the `--watch` or `-w` flag does not
```
./node_modules/.bin/node-sass src/styles/ --watch -o www/styles/
```
I get a no directory error
Error: ENOENT, no such file or directory 'path/to/project/src/styles/**'

**Comment by kkopachev** [comment]
https://github.com/sass/node-sass/pull/952

**Comment by xzyfer** [comment]
@kaelig fixed in v3.1.1

**Comment by andrezzoid** [comment]
I'm sorry for bringing this up again, but I cannot seem to get it to work. I'm trying to `node_modules/node-sass/bin/node-sass assets/scss/main.scss -o static/css/ -w assets/scss/`, but get the following output:
```
Rendering Complete, saving .css file...
Error: EISDIR, open '/vagrant/assets/scss'
```

**Comment by Darksoulsong** [comment]
I've got the same error as @CrowdHailer.

**Comment by amrography** [comment]
sass looks for all files inside current working directory, and rebuild if you `@import ` any changed files to your current file.

**structure example**
main.scss
folder1/_file1.scss
folder2/file2.scss

**main.scss**
```scss
@import 'folder1/file1';
```
**file2.scss**
```scss
@import '../main';
```

```shell
sass --watch main.scss:style.css
```
This command fires if you do change on file1.scss, file2.scss and main.scss of course

```shell
sass --watch folder2/file2:../style.css
```
This command fires only when you save file2.scss and doesn't fire if you save main.scss

**Comment by xzyfer** [comment]
I'm actually not sure if watching a partial (file beginning with _) is
valid. However your last example would not work because main.scss is not in
your include path. The default include path is the directory of the file
being compiled (or watched). Try using the --include-path=/path/to/main.scss

**Comment by moosebay** [comment]
Use '-r' to recursively watch
`node-sass -r --watch scss -o css`

**Comment by shaltaev** [comment]
I'm use this script runner in package.json

```json
"scripts": {
   "scss:tocss": "./node_modules/.bin/node-sass --watch ./src/css/scss --output ./src/css/ "
}
```

One thing with this, that it work only on change in folder. So to rebuild **.css** you should save your **.scss** file.

For first build just run without **--watch** , like:

```sh
./node_modules/.bin/node-sass ./src/css/scss --output ./src/css/
```

**Comment by tusharshuklaa** [comment]
I'm still facing this issue when watching folder from cmd.
This is the error that occurs on entering this command: node-sass --watch ./buynow2/scss/* --output .buynow2/css/

fs.js:941
  binding.lstat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, lstat 'Z:\etc\designs\healthcare\commonframework\clientlibs\themes\Nasivin\buynow2\scss\*'
    at Object.fs.lstatSync (fs.js:941:11)
    at Object.module.exports.parseDir (C:\Users\tusshukl\AppData\Roaming\npm\node_modules\node-sass\node_modules\sass-graph\sass-graph.js:153:10)
    at Object.watcher.reset (C:\Users\tusshukl\AppData\Roaming\npm\node_modules\node-sass\lib\watcher.js:17:21)
    at watch (C:\Users\tusshukl\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:260:20)
    at run (C:\Users\tusshukl\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:319:5)
    at Object.<anonymous> (C:\Users\tusshukl\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass:405:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
