### ISSUE TITLE
v3.13.1/linux-x64-57_binding.node has vanished

### ISSUE THREAD

**Issue by gjbaxter** [sass/node-sass#2500]
We're using a library that ultimately depends on this version, and it seems the last commit deleted this version.

**Comment by nschonni** [comment]
Nothing was deleted, the version you're running is too new for your node-sass version https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404-downloading-bindingnode-file

**Comment by gjbaxter** [comment]
We have been running this for over a year.  We're using gulp-helper -> gulp-sass -> node-sass v3.13.1/linux-x64-57_binding.node.  That asset WAS THERE.. and now it's not?

**Comment by nschonni** [comment]
No, you've updated your version of Node to a newer version than you were running before. We don't delete bindings, and only support certain combos as described in the troubleshooting
