### ISSUE TITLE
node-sass is compiling the directory recursively even without the flag

### ISSUE THREAD

**Issue by ltlombardi** [sass/node-sass#2504]
**How to execute**
node-sass --watch  ./src/main/css --output ./src/main/css 
where ./src/main/css can be any directory you want that has sass files.

**Result**
Watches and compiles all the .scss in the directory and it's sub-directories, i.e. recursively.

**Expected**
Should watch for changes and only compile the .scss files in the directory, not the ones present in the sub-directories, i.e. non-recursively / without recursion.
_____________________
**To give more details as to how and why:** 
My app follows the [BEM methodology](http://getbem.com/) with sass, and because of that I have a styles folder structure like this (screen from vscode IDE). I use node-sass CLI with the IDE:

![capture](https://user-images.githubusercontent.com/898124/46363626-f0d1e580-c649-11e8-95dc-9409c26feea7.PNG)

I need node-sass to watch and compile only the files in the /css folder (app.scss and chartist.scss).
Right now it's compiling also the settings.scss, normalization.scss and all the rest of the .scss files that don't start with the `_` 
_____________________
**When reporting any bug, YOU MUST PROVIDE THE FOLLOWING INFORMATION
or your issue will be closed without discussion**
-->

- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): v8.11.4
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.8.0',
  node: '8.11.4',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2p',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'node-sass'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at [eval]:1:1
>     at ContextifyScript.Script.runInThisContext (vm.js:50:33)
>     at Object.runInThisContext (vm.js:139:38)
>     at Object.<anonymous> ([eval]-wrapper:6:22)
>     at Module._compile (module.js:652:30)
>     at evalScript (bootstrap_node.js:466:27)

- npm node-sass versions (`npm ls node-sass`): node-sass@4.9.3

**Comment by ltlombardi** [comment]
Even tried this with same result:
node-sass --watch  ./src/main/resources/public/css/ --output ./src/main/resources/public/css/ --recursive false

**Comment by nschonni** [comment]
AFAIK, `--recursive` flag only affects the `watch` flag.
General Sass thing, is any stylesheets that are not intended for compilation and only for `@import` should be `_`. This doesn't mean this isn't a bug, just a general pattern/comment

**Comment by ltlombardi** [comment]
To give more details: 
My app follows the [BEM methodology](http://getbem.com/) with sass, and because of that I have a styles folder structure like this:

![capture](https://user-images.githubusercontent.com/898124/46363626-f0d1e580-c649-11e8-95dc-9409c26feea7.PNG)


I need node-sass to watch and compile only the files in the /css folder (app.scss and chartist.scss).
Right now it's compiling also the settings.scss, normalization.scss and all the rest of the .scss files that don't start with the `_`

**Comment by nschonni** [comment]
Don't think `--recursive false` works. The CLI uses https://github.com/sindresorhus/meow so it would probably be `--no-recursive`

**Comment by saper** [comment]
Are there any dependencies? For example, is `app.scss` importing `settings/settings.scss`

Can you produce a quick repository to reproduce it? (Btw. please copy text output and not images if possible)

**Comment by ltlombardi** [comment]
Hey. I'm no longer developing with this ecosystem :-( .
I don't have anymore, files pertaining to it.

**Comment by saper** [comment]
No worries, we have enough watcher bugs around :) Thank you.

Everybody: please have a look at https://github.com/sass/node-sass/labels/Module%20-%20Watcher and see if there is one that is a duplicate to this one. Test cases welcome!
