### ISSUE TITLE
module did not self register

### ISSUE THREAD

**Issue by sandeep100690** [sass/node-sass#2507]
I am getting module did not self register error in normal scss cli application. i check the binary in npm-cache folder, it is downloaded perfectly(win32-x64-57_binding). 

I also tried with clearing npm cache, deleting node-modules folder & changing npm & node versions but getting same issue. 

- System: Windows v10.18.1.3 
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 8.11.3

- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
  
- Node Platform (`node -p process.platform`):win32

- Node architecture (`node -p process.arch`):x64

- node-sass version (`node -p "require('node-sass').info"`):
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\angular\myapp\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (C:\angular\myapp\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
	
- npm node-sass versions (`npm ls node-sass`):
myapp@0.0.0 C:\angular\myapp
+-- @angular-devkit/build-angular@0.8.4
| `-- node-sass@4.9.3
`-- node-sass@4.9.3

**Comment by xzyfer** [comment]
Looks node-sass didn't install correctly. This usually due to permission issues, or running npm as sudo. Delete your `node_modules` and run `npm install node-sass@latest` without sudo.

**Comment by xzyfer** [comment]
There is nothing new to contribute to this issue. Please search closed issues for "Module did not self-register" and see if any of the existing solutions work for you.
