### ISSUE TITLE
i have same problem please suggest

### ISSUE THREAD

**Issue by rabi-999** [sass/node-sass#2508]
![image](https://user-images.githubusercontent.com/31726626/46463870-9cae3900-c7e2-11e8-907f-dd93b745048f.png)

_Originally posted by @rabi-999 in https://github.com/_render_node/MDU6SXNzdWUyNzA2MzMzNTc=/issues/unread_timeline#issuecomment-426941963_

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
