### ISSUE TITLE
Isssue when directory name contains [ ] character

### ISSUE THREAD

**Issue by Teknono** [sass/node-sass#2510]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v10.11.0
- Node Process (`node -p process.versions`): 

{ http_parser: '2.8.0',
  node: '10.11.0',
  v8: '6.8.275.32-node.28',
  uv: '1.23.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.33.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }

- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):

node-sass       4.9.3   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`): `-- node-sass@4.9.3

Hi everybody,

I am encountering a problem when i want to transpile a sass directory into a another one. When the full path of the project contains [ and ] characters, node-sass return "No input file was found". Example :

D:\Example\**[**Project Name**]**\node node-sass -r \Content\css -o \Content\bundle\css

But if you remove only [ or ], it works !

**Comment by nschonni** [comment]
You'd probably need to escape the brackets (`\[...\]`) since those are special characters in RegExp which is what the globs package assumes https://github.com/isaacs/node-glob#glob-primer
