### ISSUE TITLE
Support for AARCH64 architecture

### ISSUE THREAD

**Issue by ossdev07** [sass/node-sass#2513]
Hi,

I am trying to build the Node-Sass package for aarch64 architecture.

I have started compiling the Node-Sass source code and I have managed to compile the source code successfully.

**Also, I am able to the generate the binary on my aarch64 board**.

Please let me know, what should be the next step to get Node-Sass in the official aarch64 repository.

Regards,

**Comment by nschonni** [comment]
See the previous discussions in issue #1340 and PR #2253
