### ISSUE TITLE
Segmentation fault when using 25 or more entries in sass-list

### ISSUE THREAD

**Issue by QballDevelop** [sass/node-sass#2514]
When adding the bottom two to this list I'm getting a segfault from node-sass
Seems to be something with the length of the list because it works when you remove one entry.

$sizes: (
  auto: auto,
  0: 0,
  -5: -5px,
  -80: -80px,
  15: 15px,
  20: 20%,
  25: 25%,
  30: 30px,
  40: 40px,
  50: 50px,
  half: 50%,
  60: 60px,
  68: 68px,
  sm-icons: 70px,
  75: 75%,
  250: 250px,
  290: 290px,
  320: 320px,
  380: 380px,
  600: 600px,
  970: 970px,
  100px: 100px,
  100: 100%,
  100vh: 100vh,
  100vw: 100vw,
) !default;

**Comment by xzyfer** [comment]
The issue template is not optional. Open a new issue with the issue filled in.

**Comment by QballDevelop** [comment]
Sorry, it's fixed by updating node-sass
