### ISSUE TITLE
Issue with installation of node-sass

### ISSUE THREAD

**Issue by Abhijeet1990** [sass/node-sass#2515]
npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-sass"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.9.4 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.9.4 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/abhijeet/PowerWeb/npm-debug.log

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
