### ISSUE TITLE
Postinstall script failing on Node v 11

### ISSUE THREAD

**Issue by rileyjsumner** [sass/node-sass#2524]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 11.0.0
- Node Process (`node -p process.versions`): 
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.9.4
- npm node-sass versions (`npm ls node-sass`): 4.9.4

Just after updating my node version, my deploy scripts are failing with the error `Failed at the node-sass@4.9.4 postinstall: 'node scripts/build.js'`

**Comment by xzyfer** [comment]
Duplicate
