### ISSUE TITLE
linux-x64-67_binding.node ?

### ISSUE THREAD

**Issue by xiongyayun428** [sass/node-sass#2526]
- NPM version (6.4.1):
- Node version (11.0.0):
- Node Process (
{ http_parser: '2.8.0',
  node: '11.0.0',
  v8: '7.0.276.28-node.5',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i \n',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
):
- Node Platform (linux):
- Node architecture (x64):
- node-sass version (
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:316:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at evalScript (internal/bootstrap/node.js:715:27)
):
- npm node-sass versions (
└─┬ @angular-devkit/build-angular@0.8.6
  └── UNMET OPTIONAL DEPENDENCY node-sass@^4.9.3
):

> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-64_binding.node/v4.9.4/linux-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-64_binding.node/v4.9.4/linux-x64-67_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

**Comment by xzyfer** [comment]
Duplicate node 11

**Comment by Gundelino85** [comment]
I have the same problem. Why is this issue closed with "Duplicate node 11"?

**Comment by Gundelino85** [comment]
Going down with node to version 10 was my solution...

**Comment by xzyfer** [comment]
67 is node 11. There is a node 11 support issue already open
