### ISSUE TITLE
parceljs @import conflict

### ISSUE THREAD

**Issue by rambo-panda** [sass/node-sass#2527]
- NPM version (`6.4.1`):
- Node version (`v8.12.0, v10`):
- Node Process (`{ http_parser: '2.8.0',
  node: '8.12.0',
  v8: '6.2.414.66',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2p',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }`):
- Node Platform (`darwin, win 64bit`):
- Node architecture (`x64`):
- node-sass version (
`node-sass	4.9.4	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]`):
- npm node-sass versions (`node-sass@4.9.4`):

when [parcel](https://github.com/parcel-bundler/parcel) parses the `url` passed by `node-sass's importer` ,  it will be stuck when the number of files is too large.

like  https://github.com/parcel-bundler/parcel/issues/2199

**Comment by rambo-panda** [comment]
this is my about `node-sass importer` test file

```javascript
'use strict';

const Parcel_SASS = require('parcel-bundler/src/assets/SASSAsset');

const my_root_dir = '<here is my root dir>';

const test = (url,prev, done) => {
	var sass = new Parcel_SASS(prev, {
		rootDir: `${my_root_dir}/parcel`,
		rendition: {
			type: 'scss',
			value : '@import "../../../../../deps/function.scss";',
			modules: false
		}
	});

	// call parse
	sass.parse('@import "../../../../../deps/function.scss";')
	.then(file => {
		done(file);
	});
};

// ['a', 'b', 'c'].forEach(name => {  // TODO this is ok
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'].forEach(name => {  // TODO this is will be stuck.
	test(
		'../../../../../deps/function.scss',
		`${my_root_dir}parcel/mobile/parent/read/src/components/${name}.vue`,
		(file) => {
			console.log('res file %s', file);
		}
	)
});

// placholder
setTimeout(() => {
}, 10000000);

```

![image](https://user-images.githubusercontent.com/2776050/47634425-75058300-db8c-11e8-8340-f514c8e304db.png)

**Comment by rambo-panda** [comment]
this is my about `parcel` **Resolver.js** test file

#### It works fine

```js
'use strict';
const Resolve = require('parcel-bundler/src/Resolver'),
	parseCSSImport = require('parcel-bundler/src/utils/parseCSSImport');

const my_root_dir = '<here is my root dir>';

const test = (url,prev, done) => {
	var resolver = new Resolve({
		extensions: ['.scss', 'sass'],
		rootDir: `${my_root_dir}/parcel`
	});

	url = parseCSSImport(url);

	resolver
	.resolve(url, prev === 'stdin' ? this.name : prev)
	.then(resolved => resolved.path)
	.then(file => done({file}))
	.catch(() => url)
};

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'].forEach(name => {
	y(
		'../../../../../deps/function.scss',
		`${my_root_dir}/parcel/mobile/parent/read/src/components/${name}.vue`,
		(file) => {
			console.log(file);
		}
	)
});

// placeholder
setTimeout(() => {
}, 100000);

```

**Comment by saper** [comment]
We have a limitation of maximum 4 threads in the background. If you are doing lots of fancy things in your importer, including I/O operations, it is likely to hang.

Please have a look at the documented issue.

https://github.com/sass/node-sass/issues/857

The only workaround is to increase background thread pool size to something larger.
