### ISSUE TITLE
installation error throw npm

### ISSUE THREAD

**Issue by Rekhajikki** [sass/node-sass#2529]
Im trying to install node-sass mounting over the docker container .

I get the below error
![image](https://user-images.githubusercontent.com/19817281/47772200-eae42880-dd0b-11e8-9a68-e6006750f26b.png)

Can any one help me out regarding the issue.

Thanks,
Rekha

**Comment by xzyfer** [comment]
Read through thege troubleshooting guide. If you still have issues open a
new issue and FOLLOW THE TEMPLATE
