### ISSUE TITLE
problems running an ember application

### ISSUE THREAD

**Issue by marbaque** [sass/node-sass#2532]
When I try to run this or any application that uses node-sass I get this error:

*Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.2*

Does it not support my version of node (v11.0.0) or my Mac OS version (10.14.01) ?

**Comment by xzyfer** [comment]
Node 11 is not currently supported. Subscribe to open Node 11 duppy issue
for updates.
