### ISSUE TITLE
"File to import not found or unreadable" using relative imports

### ISSUE THREAD

**Issue by FedericoBiccheddu** [sass/node-sass#2537]
Hi, as mentioned in the title, I'm getting that error while importing a library from  `node_modules` having the following folder structure:
```
asset/
└── scss
    └── app.scss
node_modules/
└── boostrap
    └── scss
        └── boostrap.scss
```
`app.scss`'s content:
```
@import "../node_modules/bootstrap/scss/bootstrap";
```

I can use `@import "node_modules/bootstrap/scss/bootstrap";` but then the autocomplete in the IDE will not work anymore.

Command: `node-sass asset/scss/ --output public/css/ --output-style expanded --source-map-embed --source-map-content`.

Full error:
```
{
  "status": 1,
  "file": "/srv/asset/scss/app.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap.",
  "formatted": "Error: File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap.\n        on line 1 of asset/scss/app.scss\n>> @import \"../node_modules/bootstrap/scss/bootstrap\";\n   ^\n"
}
```

- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v10.13.0
- Node Process (`node -p process.versions`): 
```
{ http_parser: '2.8.0',
  node: '10.13.0',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.9.4	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): `-- node-sass@4.9.4

**Comment by nschonni** [comment]
Your relative path is only going up one level rather than 2 to get to the root of your code folder.
EX: @import "../../node_modules/bootstrap/scss/bootstrap";

**Comment by pacocom** [comment]
Use https://github.com/sass/dart-sass instead of https://github.com/sass/node-sass resolve this problem for me.
