### ISSUE TITLE
Keep changelog up to date or delete it

### ISSUE THREAD

**Issue by caesar** [sass/node-sass#2538]
`CHANGELOG.md` is 8 months out of date. It would be good to either keep it up to date with each new release, or just delete it.

I always advocate for a changelog, but since `node-sass`'s changelog has only ever consisted of links to the GitHub releases page, maybe just deleting it would be the best option and then nobody would have to worry about keeping it up to date.

Or the entire contents could just be replaced by:
`See https://github.com/sass/node-sass/releases`

**Comment by nschonni** [comment]
I see the value of the CHANGELOG for people looking at their local node_modules to see what changed. What we probably need is a script that can keep the changelog updated automatically as part of tagging the new release

**Comment by caesar** [comment]
Agreed, except that at present it contains no information other than links to the GitHub Releases page anyway.
Ideally it would contain the same information that is currently on the Releases page.

Perhaps [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) could be used if a commit message convention were enforced.
