### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node

### ISSUE THREAD

**Issue by Hatimjamali** [sass/node-sass#2539]
got below error when i type npm i in command prompt, and at last i mentioned all version for node and npm
i check from browser i cant find v4.7.2/win32-x64-64_binding.node in github
i am very new to all these, please provide step by step solution which i can easily troubleshoot
-------------------------------------------------------------------------------------------------------
D:\App3010>npm i

> node-sass@4.7.2 install D:\App3010\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

tunneling socket could not be established, statusCode=301

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\App3010\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.7.2 postinstall D:\App3010\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\App3010\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\App3010\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (D:\\App3010\\node_modules\\which\\which.js:13:12)\n    at F (D:\\App3010\\node_modules\\which\\which.js:68:19)\n    at E (D:\\App3010\\node_modules\\which\\which.js:80:29)\n    at D:\\App3010\\node_modules\\which\\which.js:89:16\n    at D:\\App3010\\node_modules\\isexe\\index.js:42:5\n    at D:\\App3010\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (D:\\App3010\\node_modules\\which\\which.js:13:12)\n    at F (D:\\App3010\\node_modules\\which\\which.js:68:19)\n    at E (D:\\App3010\\node_modules\\which\\which.js:80:29)\n    at D:\\App3010\\node_modules\\which\\which.js:89:16\n    at D:\\App3010\\node_modules\\isexe\\index.js:42:5\n    at D:\\App3010\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\App3010\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\App3010\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\App3010\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\App3010\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\App3010\node_modules\node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marketing\AppData\Roaming\npm-cache\_logs\2018-11-06T18_15_35_827Z-debug.log

Below are Versions
--------------------------------------------------------------------------------------------------------
D:\App3010>node -v
v10.13.0

D:\App3010>npm -v
6.4.1

D:\App3010>node -p process.versions
{ http_parser: '2.8.0',
  node: '10.13.0',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }

D:\App3010>node -p process.platform
win32

D:\App3010>node -p process.arch
x64

D:\App3010>node -p "require('node-sass').info
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)

D:\App3010>npm ls node-sass
ionstore2@0.0.1 D:\App3010
`-- (empty)

**Comment by Hatimjamali** [comment]
my operating system is windows 10

**Comment by nschonni** [comment]
That version is too old for Node 10. Upgrade node-sass, or downgrade your Node

**Comment by Hatimjamali** [comment]
First i tried with upgrade... npm update node-sass but didn't resolve then i removed cache
npm cache clean and then install latest node-sass. it try to install node-sass@4.7.2 but cant download files then it install node-sass@4.10.0.
got error for python checking for Python executable "python2" in the PATH
please tell me step by step procedure by writing which command i have to run (i am very new to these so i dont know any command and procedure)

--------------------------------------

D:\App3010>npm install node-sass@latest

> node-sass@4.7.2 install D:\App3010\node_modules\@ionic\app-scripts\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 install D:\App3010\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-64_binding.node
Download complete .] - :
Binary saved to D:\App3010\node_modules\node-sass\vendor\win32-x64-64\binding.node
Caching binary to C:\Users\Marketing\AppData\Roaming\npm-cache\node-sass\4.10.0\win32-x64-64_binding.node

> node-sass@4.7.2 postinstall D:\App3010\node_modules\@ionic\app-scripts\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\App3010\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\App3010\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (D:\\App3010\\node_modules\\which\\which.js:13:12)\n    at F (D:\\App3010\\node_modules\\which\\which.js:68:19)\n    at E (D:\\App3010\\node_modules\\which\\which.js:80:29)\n    at D:\\App3010\\node_modules\\which\\which.js:89:16\n    at D:\\App3010\\node_modules\\isexe\\index.js:42:5\n    at D:\\App3010\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\App3010\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\App3010\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\App3010\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\App3010\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\App3010\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\App3010\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (D:\\App3010\\node_modules\\which\\which.js:13:12)\n    at F (D:\\App3010\\node_modules\\which\\which.js:68:19)\n    at E (D:\\App3010\\node_modules\\which\\which.js:80:29)\n    at D:\\App3010\\node_modules\\which\\which.js:89:16\n    at D:\\App3010\\node_modules\\isexe\\index.js:42:5\n    at D:\\App3010\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\App3010\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\App3010\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\App3010\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\App3010\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\App3010\node_modules\@ionic\app-scripts\node_modules\node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN @angular/compiler-cli@5.2.10 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/app-rate@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/app-version@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/email-composer@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/keyboard@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/onesignal@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/paypal@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/social-sharing@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/status-bar@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/stripe@4.7.0 requires a peer of @ionic-native/core@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular4-paystack@2.1.1 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular4-paystack@2.1.1 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.27.5 requires a peer of typescript@>=2.4.2 <2.8 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marketing\AppData\Roaming\npm-cache\_logs\2018-11-07T04_50_10_000Z-debug.log

D:\App3010>

**Comment by xzyfer** [comment]
Looks like you're ended up with both versions of node-sass. Delete your
node modules and do a fresh install. If the issue persists run npm ls
node-sass to see where the duplicate versions are coming from.
