### ISSUE TITLE
Hello, when I execute the following command, the operation stops...

### ISSUE THREAD

**Issue by daqiang123** [sass/node-sass#2541]
Hello, when I execute the following command, the operation stops...

D:\project\eyeshot\eyeshot\project>npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-sass@3.8.0 install D:\project\eyeshot\eyeshot\project\node_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass
> node scripts/install.js

Can you help solve this problem? 
Thank you!

- NPM version (`npm -v`):5.6.0
- Node version (`node -v`):v8.11.3

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by daqiang123** [comment]
C:\Users\lenovo>node -p process.versions
{ http_parser: '2.8.0',
  node: '8.11.3',
  v8: '6.2.414.54',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

C:\Users\lenovo>node -p process.platform
win32

C:\Users\lenovo>node -p process.arch
x64

C:\Users\lenovo>node -p "require('node-sass').info"
module.js:549
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:466:27)

C:\Users\lenovo>npm ls node-sass
C:\Users\lenovo
`-- (empty)

**Comment by nschonni** [comment]
3.8.0 doesn't support Node 8 https://github.com/sass/node-sass/releases/tag/v3.8.0
Upgrade node-sass or downgrade your Node
