### ISSUE TITLE
Missing 4.9.x binaries for linux

### ISSUE THREAD

**Issue by dpetit62** [sass/node-sass#2545]
Doing 
`npm i node-sass@4.9.0`
or
`npm i node-sass@4.9.4`
on linux give me a 404 error

You can try this URL : https://github.com/sass/node-sass/releases/download/v4.9.0/linux_musl-x64-67_binding.node

this is the url resolved by my npm install to found the binary

- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 10.11.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.11.0',
  v8: '6.8.275.32-node.28',
  uv: '1.23.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.33.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.9.0 to 4.9.4
- npm node-sass versions (`npm ls node-sass`):

**Comment by xzyfer** [comment]
The binaries for your environment are not missing. The installer would have
output the URL it's trying to download from. You can follow the URL to see
the binary.

**Comment by dpetit62** [comment]
If you read carefully what i said before I'm on Node 10 (LTS).

**Comment by nschonni** [comment]
"67" means you're running Node 11

**Comment by xzyfer** [comment]
My comment was to @rozarkk

**Comment by xzyfer** [comment]
The url you added to the issue is for node 11 on Alpine Linux. Which is not supported on node-sass 4.9.0.

**Comment by dpetit62** [comment]
Yes but as you can see my node - v return v10. And i ran that on an official node:10-alpine docker image. In that case why when i do a npm i node-sass@4.9.0 it look after a x64-67 which doesn t exist?

**Comment by xzyfer** [comment]
Is the URL you posted actually the URL being output to the terminal or did you just copy why @rozarkk posted?

When you opened the issue you posted the output of `node -p process.versions` which clearly shows that `modules` is 64. So there is no way the install is trying to download the x64_67 binary.

Please post the exact actual installer output

**Comment by nschonni** [comment]
Duplicate of #2535
