### ISSUE TITLE
Needs correct install instructions in README

### ISSUE THREAD

**Issue by sgehrman** [sass/node-sass#2546]
After searching for 30 minutes and trying everything, I finally found the correct install command.

Why is this so difficult? Why is it not in your readme or troubleshooting?

Here it is for anyone trying to install node-sass:

sudo npm install --unsafe-perm=true -g node-sass

**Comment by xzyfer** [comment]
That is only true if you're running as a privileged user which is not
recommended when running npm. This is true for all npm package with install
scripts or native packages. It's also documented in the troubleshooting
guide which is the first line of the read me.
