### ISSUE TITLE
Node 10 requires 4.9, this is mentioned in the issue template. I'll try to make that even more explicit

### ISSUE THREAD

**Issue by yasarece** [sass/node-sass#2551]
_Originally posted by @nschonni in https://github.com/sass/node-sass/issues/2383#issuecomment-389539548_

**Comment by yasarece** [comment]
am using Node 10.14.0 bu facing the below issue 
> node-sass@4.5.3 install D:\Yasar\wiproshopTracker\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

**Comment by nschonni** [comment]
Added another note in https://github.com/sass/node-sass/commit/dfe1f05aba0f681eb237bc146d8cf1716d1086c4
