### ISSUE TITLE
mixins may not be defined within control directives or mixins

### ISSUE THREAD

**Issue by xxxxzz** [sass/node-sass#2552]
npm version ： 6.4.1
node version ：10.14.0
node Platform ： win32
node architecture ： x64
node-sass vesion ：4.10.0

![image](https://user-images.githubusercontent.com/22461433/49353067-90692e00-f6f6-11e8-9299-90ee7644f158.png)

**Comment by xzyfer** [comment]
This is expected. Check the Sass language documentation for more
information.
