### ISSUE TITLE
install.js 

### ISSUE THREAD

**Issue by Konraddd** [sass/node-sass#2554]
I am trying to build node-sass, rebuilding also doesn't work.

My node version: v11.3.0
My OS: Amazon Linux 2 AMI

After executing the `scripts/install.js`
I cannot download `linux-x64-67_binding.node`due to 

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-67_binding.node": 

HTTP error 404 Not Found

```

Thanks for help!

**Comment by xzyfer** [comment]
Consult the Node compatibility table on the release notes for your
node-sass version.
