### ISSUE TITLE
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

### ISSUE THREAD

**Issue by miojamo** [sass/node-sass#2563]
I have previously used node for windows but now using Ubuntu WSL and I have an error:

Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  Windows 64-bit with Node.js 6.x

npm -v 3.5.2
node -v v8.10.0
node-sass       4.11.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
tried node-sass recompile (with force option), uninstal npm and install again nothing works

**Comment by xzyfer** [comment]
Looks like you have two versions of Node installed. Node 6 and Node 8.

**Comment by miojamo** [comment]
>Looks like you have two versions of Node installed. Node 6 and Node 8.
How can be fixed? should I uninstall node globally?

**Comment by miojamo** [comment]
strange it worked when I removed rm- R PROJECT_DIR/node_modules/node-sass

**Comment by jcubic** [comment]
For some reason Ubuntu on WLS had two version of node: nodejs and node. removing nodejs (I've also installed nvm) solved the issue. Maybe because grunt suggested to run `sudo apt install node-grunt-cli` and it installed lot of packages (installed all without even looking).
