### ISSUE TITLE
node-sass 4.11 FreeBSD Supported Environments 

### ISSUE THREAD

**Issue by francoricci** [sass/node-sass#2566]
node-sass 4.11 seems not support FreeBSD.
Why? 
Until version 4.10 FreeBSD was regularly supported.

**Comment by nschonni** [comment]
There is no CI for our FreeBSD binaries, so @saper has to build them manually when he can.
Node 11 also dropped support for our previous baseline FreeBSD version, so that might also be slowing it down.

**Comment by saper** [comment]
I'll check that and see when we can have this. Should not be a big problem.

**Comment by ipeshev** [comment]
If we have node-sass installed globally, why it insist to compile it every time  on our BSD machines ?

**Comment by ipeshev** [comment]
We also having problems adding node-sass to .npm/_prebuilds for freebsd. It just does not respect any format of prebuild file name.

**Comment by ipeshev** [comment]
ok it is because of postinstall scripts

**Comment by ipeshev** [comment]
Error: ENOENT: no such file or directory, scandir '.../node_modules/node-sass/vendor' npm install node-sass --ignore-scripts. So we are doomed to rebuild it till the end of times !!!

**Comment by saper** [comment]
I have uploaded FreeBSD binaries for node 8, 10 and 12 (as available in FreeBSD ports). It should no longer need to compile. Enjoy!
