### ISSUE TITLE
Postinstall script build fails with node 10

### ISSUE THREAD

**Issue by guylhermetabosa** [sass/node-sass#2567]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 10.14.1
- Node Process (`node -p process.versions`): `{ http_parser: '2.8.0',
  node: '10.14.1',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
`
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
`node-sass	4.11.0	(Wrapper)	[JavaScript]   libsass  	3.5.4	(Sass Compiler)	[C/C++]`
- npm node-sass versions (`npm ls node-sass`):
```
 └─┬ @angular/cli@1.4.9
   └── node-sass@4.11.0 

```

Hello, unfortunately i'm having problems running `npm install` on my project, as you can see, my node-sass version is 4.11.0 what should work fine with node version 10+, however it tries to run build onto node-sass 3.13.1 as the message says: 

```npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: node scripts/build.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guylhermetabosa/.npm/_logs/2018-12-11T19_35_32_524Z-debug.log
```

I'm using n as node version manager, the issue only happens with v10 of node, with v6 it was working fine.

Here is the link of the command complete log: 
[`npm install log`](https://gist.github.com/guylhermetabosa/966ff63b37a49aed4d19d287ecfcabb5)

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimium-support

**Comment by xzyfer** [comment]
Looks like you have two versions of node-sass in your dependency tree. You
can confirm with npm ls node-sass

**Comment by guylhermetabosa** [comment]
Hello @xzyfer, there is only one node-sass version that comes angular-cli version 1.4.9 with node-sass 4.11.0

**Comment by guylhermetabosa** [comment]
**Update:** One of my private libs was using gulp-sass version 4.0.1, which uses node-sass version: 4.8.3, that might be the root cause.

Thanks for the support, 
Regards.

**Comment by Santosh8055** [comment]
> **Update:** One of my private libs was using gulp-sass version 4.0.1, which uses node-sass version: 4.8.3, that might be the root cause.
> 
> Thanks for the support,
> Regards.

How do you solve this?

**Comment by xzyfer** [comment]
npm update node-sass
