### ISSUE TITLE
unable to install node-sass in latest arch linux , latest stable node and npm

### ISSUE THREAD

**Issue by manslogic** [sass/node-sass#2569]
- NPM version (`npm -v`): find in below screenshot
- Node version (`node -v`):find in below screenshot
- Node Process (`node -p process.versions`):find in below screenshot
- Node Platform (`node -p process.platform`):find in below screenshot
- Node architecture (`node -p process.arch`):find in below screenshot
- node-sass version (`node -p "require('node-sass').info"`):find in below screenshot
- npm node-sass versions (`npm ls node-sass`):find in below screenshot
![image](https://user-images.githubusercontent.com/1926423/50055328-74906e00-0173-11e9-90e1-0cb17e784d88.png)

while installing i am facing below issue.  i have tried multiple times.

Please see the the complete log along with the commands below.

				[root@arch finance]# npm install --unsafe-perm node-sass

		> node-sass@4.9.3 install /root/project/finance/finance/node_modules/@angular-devkit/build-angular/node_modules/node-sass
		> node scripts/install.js

		Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-67_binding.node
		Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-67_binding.node":

		HTTP error 404 Not Found

		Hint: If github.com is not accessible in your location
			  try setting a proxy via HTTP_PROXY, e.g.

			  export HTTP_PROXY=http://example.com:1234

		or configure npm proxy via

			  npm config set proxy http://example.com:8080

		> node-sass@4.11.0 install /root/project/finance/finance/node_modules/node-sass
		> node scripts/install.js

		Cached binary found at /root/.npm/node-sass/4.11.0/linux-x64-67_binding.node

		> node-sass@4.9.3 postinstall /root/project/finance/finance/node_modules/@angular-devkit/build-angular/node_modules/node-sass
		> node scripts/build.js

		Building: /usr/bin/node /root/project/finance/finance/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
		gyp info it worked if it ends with ok
		gyp verb cli [ '/usr/bin/node',
		gyp verb cli   '/root/project/finance/finance/node_modules/node-gyp/bin/node-gyp.js',
		gyp verb cli   'rebuild',
		gyp verb cli   '--verbose',
		gyp verb cli   '--libsass_ext=',
		gyp verb cli   '--libsass_cflags=',
		gyp verb cli   '--libsass_ldflags=',
		gyp verb cli   '--libsass_library=' ]
		gyp info using node-gyp@3.8.0
		gyp info using node@11.4.0 | linux | x64
		gyp verb command rebuild []
		gyp verb command clean []
		gyp verb clean removing "build" directory
		gyp verb command configure []
		gyp verb check python checking for Python executable "python2" in the PATH
		gyp verb `which` succeeded python2 /usr/bin/python2
		gyp ERR! configure error
		gyp ERR! stack Error: Command failed: /usr/bin/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
		gyp ERR! stack   File "<string>", line 1
		gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
		gyp ERR! stack                                ^
		gyp ERR! stack SyntaxError: invalid syntax
		gyp ERR! stack
		gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
		gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
		gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
		gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
		gyp ERR! System Linux 4.19.8-arch1-1-ARCH
		gyp ERR! command "/usr/bin/node" "/root/project/finance/finance/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
		gyp ERR! cwd /root/project/finance/finance/node_modules/@angular-devkit/build-angular/node_modules/node-sass
		gyp ERR! node -v v11.4.0
		gyp ERR! node-gyp -v v3.8.0
		gyp ERR! not ok
		Build failed with error code: 1

		> node-sass@4.11.0 postinstall /root/project/finance/finance/node_modules/node-sass
		> node scripts/build.js

		Binary found at /root/project/finance/finance/node_modules/node-sass/vendor/linux-x64-67/binding.node
		Testing binary
		Binary is fine
		npm WARN @angular/elements@7.1.3 requires a peer of @angular/core@7.1.3 but none is installed. You must install peer dependencies yourself.
		npm WARN @angular/elements@7.1.3 requires a peer of @angular/platform-browser@7.1.3 but none is installed. You must install peer dependencies yourself.
		npm WARN @angular/material@7.1.1 requires a peer of @angular/cdk@7.1.1 but none is installed. You must install peer dependencies yourself.
		npm WARN @angular/material-moment-adapter@7.1.1 requires a peer of moment@^2.18.1 but none is installed. You must install peer dependencies yourself.
		npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
		npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
		npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 (node_modules/@angular-devkit/build-angular/node_modules/node-sass):
		npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 postinstall: `node scripts/build.js`
		npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

		+ node-sass@4.11.0
		updated 1 package and audited 49539 packages in 22.113s
		found 0 vulnerabilities

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimium-support
