### ISSUE TITLE
installing node-sass@4.11.0 on windows 64 with Node 10.14.1 and NPM 6.4.1 fails

### ISSUE THREAD

**Issue by sukeshlaghate** [sass/node-sass#2572]
- `NPM version (`npm -v`): NPM 6.4.1`
- `Node version (`node -v`):Node v10.14.1`
- `Node Process (`node -p process.versions`):` ```
{ http_parser: '2.8.0',
  node: '10.14.1',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
- `Node Platform (`node -p process.platform`): win32`
- `Node architecture (`node -p process.arch`): x64`
 when trying to install node-sass@latest complains 
```
[ERROR] npm ERR! code E404
[ERROR] npm ERR! 404 Not Found: node-saas@4.11.0
```

Are Node 10.14.1 and NPM 6.4.1 not supported? 
Any workaround apart from downgrading node and npm?

Appreciate pointers to resolve this issue

**Comment by xzyfer** [comment]
Yes they are. This is not an error node-sass produces.

**Comment by nschonni** [comment]
@sukeshlaghate you've misspelled the package as "node-saas" instead of "node-sass"
