### ISSUE TITLE
when downloading node-sass v4.8.3/linux_musl-x64-64_binding.node" not found

### ISSUE THREAD

**Issue by antonyd89** [sass/node-sass#2579]
Hi,

Can you help me with this issue? I got follow error with node-sass. 

    node-sass@4.8.3 postinstall /app/node_modules/node-sass
    node scripts/build.js

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/linux_musl-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/linux_musl-x64-64_binding.node":

HTTP error 404 Not Found
```

I did follow commands to solve this issue: 
```
rm -rf node_modules
rm package-lock.json
npm cache clean
npm install
```

... after that I did

```
npm install node-sass@latest
npm rebuild node-sass --force
```
But unfortunately nothing help

My settings:

- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v10.15.0
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '10.15.0',
  v8: '6.8.275.32-node.45',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
      node-sass	4.11.0	(Wrapper)	[JavaScript]
      libsass  	3.5.4	(Sass Compiler)	[C/C++]

- npm node-sass versions (`npm ls node-sass`): node-sass@4.11.0

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s
4.8.3 is too old to run on Node  10
