### ISSUE TITLE
width: max-content -> width: max-content; width: -moz-max-content;

### ISSUE THREAD

**Issue by The-Code-Monkey** [sass/node-sass#2584]
- NPM version (`npm -v`): 6.5.0
- Node version (`node -v`): V11.7.0
- Node Process (`node -p process.versions`): 
```
{ node: '11.7.0',
  v8: '7.0.276.38-node.16',
  uv: '1.24.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  llhttp: '1.0.1',
  http_parser: '2.8.0',
  openssl: '1.1.0j',
  cldr: '34.0',
  icu: '63.1',
  tz: '2018e',
  unicode: '11.0' }
```

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 

```
node-sass       4.11.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

- npm node-sass versions (`npm ls node-sass`): node-sass@4.11.0 

My issue is with the css `width: max-content` doesn't compile with a version for firefox as firefox uses `width: -moz-max-content` is this intentional not to put the compiled css to `width: max-content; width: -moz-max-content;` as to me it should be compiled same way that `border-radius` is done

**Comment by nschonni** [comment]
Sass doesn't do any content re-writing for values. I'd recommend you look at a tool like https://github.com/postcss/autoprefixer for that functionality.
