### ISSUE TITLE
--linefeed settings is ignored by --source-map-contents true

### ISSUE THREAD

**Issue by Clockwerk300** [sass/node-sass#2585]
Hello,

if I build css file with "node-sass --source-map-embed --source-map-contents --linefeed lf to/path/file.scss" via npm script, then the containing "sourcesContent" linefeed is on Linux \n and on Windows \r\n.

e.g. decoded base64 source maps on Linux:
```
{
	"version": 3,
	"file": "src/main/resources/test/resource/index.css",
	"sources": [
		...
	],
	"sourcesContent": [
		"@import \"abstracts/mixins\";\n@import \"base/editor\";\n
		...
	],
	"names": [],
	"mappings": ...
}
```
and Windows:
```
{
	"version": 3,
	"file": "src/main/resources/test/resource/index.css",
	"sources": [
		...
	],
	"sourcesContent": [
		"@import \"abstracts/mixins\";\r\n@import \"base/editor\";\r\n
		...
	],
	"names": [],
	"mappings": ...
}
```
The setting: "--source-map-contents" should use the settings of --linefeed.

- NPM version: 3.10.10 and 6.4.1
- Node version: v6.10.0 and v10.15.0
- Node Process: { http_parser: '2.7.0',
  node: '6.10.0',
  v8: '5.1.281.93',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform: win32
- Node architecture: ia32
- node-sass version:
      node-sass       4.11.0  (Wrapper)       [JavaScript]
      libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions: `-- node-sass@4.11.0

Thank you for the help!

Related: https://github.com/sass/libsass/issues/2820

**Comment by nschonni** [comment]
can you open something in libsass and link it back here? Any change to implement this will need to be done there

**Comment by saper** [comment]
This has been closed upstream as invalid, because we should include original source files as they are.
