### ISSUE TITLE
HUGE BUG electron 4.0.2

### ISSUE THREAD

**Issue by cvlr** [sass/node-sass#2586]
node (macOS) | v11.8.0
electron 4.0.2 using node 10.11.0
node-sass 4.11.0

index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="./out/index.css">
  </head>
  <body>
    <div id="client"></div>

    <script>
      console.log(process.versions);

      const sass = require('node-sass');

      console.log(sass.renderSync({
        data: 'body{color:#f00;}',
      }));

      require('./out/index');
    </script>
  </body>
</html>
```

error

> Uncaught Error: Missing binding /Users/marek/Desktop/redred/node_modules/node-sass/vendor/darwin-x64-64/binding.node
> Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 10.x
> 
> Found bindings for the following environments:
>   - OS X 64-bit with Node.js 11.x
> 
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass` to download the binding for your current environment.

**Comment by xzyfer** [comment]
Webl don't support electron.
