### ISSUE TITLE
Error: Cannot find module '/Users/(...)/node_modules/scss-lint/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'

### ISSUE THREAD

**Issue by DerZyklop** [sass/node-sass#2591]
When i run `npm rebuild node-sass` i get this error:

```
Error: Cannot find module '/Users/(...)/node_modules/scss-lint/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
Build failed

```

I installed `node-gyp` with 

`npm install --save-dev node-gyp`

and tried it again with 

`npm rebuild node-sass`

but i get the same Error. 

- NPM version (`npm -v`): 6.7.0
- Node version (`node -v`): v9.2.1
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '9.2.1',
  v8: '6.2.414.44-node.11',
  uv: '1.16.1',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.11.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):

```
dr-plano@1.9.1 /Users/nils/S/plano/projects/scheduler.frontend.ng2
+-- @angular-devkit/build-angular@0.13.0
| `-- node-sass@4.11.0  deduped
+-- node-sass@4.11.0 
`-- scss-lint@0.0.0
  `-- node-sass@2.1.1
```

**Comment by xzyfer** [comment]
scss-lint is using an ancient version of node-sass that's too old to
install now. Try updating scss-lint or open an issue with them.
