### ISSUE TITLE
sass_binary_dir not working for 4.5.3

### ISSUE THREAD

**Issue by nitingautam** [sass/node-sass#2600]
Node Latest v8
node-sass: 4.5.3
Windows 10

We recently started using private npm repo in which no access to github hence when we install node-sass it try to download binary from github which fails.

I saw documentation in which we can use certain parameter like --sass_binary_dir but it is not working with 4.5.3 though this works with node-sass 4.9.4.

Is there a way i can make it working for my 4.5.3 version ?

**Comment by nitingautam** [comment]
![image](https://user-images.githubusercontent.com/1903388/53201742-6420c780-35ea-11e9-9eae-2d9066160c09.png)

**Comment by xzyfer** [comment]
Sorry. It a feature is missing or has a bug in an old version there isn't
anything we can do .

**Comment by nitingautam** [comment]
Thank you. Any guidance on any alternative i can use to fix in local ? as upgrading will be more effort at this point as i have to looks complete application.

**Comment by nschonni** [comment]
You can manually put the binary in your NPM cache, and it will be picked up by the install https://stackoverflow.com/a/47495931/455535

**Comment by nitingautam** [comment]
Thank you this works for me :)

**Comment by nitingautam** [comment]
Documented here as well [http://www.techbuddha.in/2019/02/22/nitingautam/node-sass-module-issues-while-working-with-private-npm-registry-or-artifactory-like-jfrog/](http://www.techbuddha.in/2019/02/22/nitingautam/node-sass-module-issues-while-working-with-private-npm-registry-or-artifactory-like-jfrog/)
