### ISSUE TITLE
"npm i node-sass" fails

### ISSUE THREAD

**Issue by melbayad** [sass/node-sass#2601]
I'm facing an issue when I'm trying to install node-sass :

```
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-64_binding.node":

getaddrinfo ENOTFOUND github.com github.com:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.
      export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
      npm config set proxy http://example.com:8080
```

As you see, the installation fails because of node-sass which is trying to download sass-spec from git repository.
Note that we have a proxy that blocks to download all of these kind of modules which are linked directly to github.

Windows 10
Npm: 6.4.1
Node: 10.14.2

Can you please suggest me a solution to bypass/resolve this issue?

**Comment by mintymatt** [comment]
Also having trouble with installing node-sass with a pretty similar error.

Tried `$ yarn add node-sass` and `$ npm rebuild node-sass` independantly.

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

**Comment by nschonni** [comment]
@melbayad The NPM message is indicating that you need to set your proxy or you DNS is failing. Nothing we can do.
@mintymatt this isn't related, your trying to install an unsupported combination https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s
