### ISSUE TITLE
Support CSS env() function

### ISSUE THREAD

**Issue by robvdl** [sass/node-sass#2602]
I don't know if this is a libsass feature or a node-sass feature.

Basically I am trying to import a CSS file into my project using @import('~@fancyapps/fancybox/dist/jquery.fancybox.min') without the .css extension this should work according to docs I've been reading, however since the CSS file contains the new env() function node-sass doesn't seem to like it.

https://developer.mozilla.org/en-US/docs/Web/CSS/env

```
{
  "status": 1,
  "file": "/code/frontend/node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.css",
  "line": 1,
  "column": 6916,
  "message": "\"env(safe-area-inset-right)\" is not a number for `max'",
  "formatted": "Error: \"env(safe-area-inset-right)\" is not a number for `max'\n        on line 1 of node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.css, in function `max`\n        from line 1 of node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.css\n        from line 4 of scss/infoplus.scss\n>> :max(0px)){.fancybox-caption{padding:75px max(44px,env(safe-area-inset-right\n   ------------------------------------------^\n"
}
```

Any ideas if this can be fixed, in the mean time I am not compiling the fancybox css in, but it would be nice to be able to do this.

**Comment by nschonni** [comment]
Probably similar to https://github.com/sass/libsass/issues/2521
It is something that needs to be addressed at the Sass or Libsass level.

**Comment by robvdl** [comment]
Ah yes you're right, this should be closed then. This is the exact issue I am having, so it is in libsass thanks.
