### ISSUE TITLE
node-sass@4.7.2 download link broken

### ISSUE THREAD

**Issue by phaldiya** [sass/node-sass#2607]
download link is broken for node-sass@4.7.2

it's trying to download from following link which give 404
https://github.com/sass/node-sass/releases/download/v4.7.2/linux_musl-x64-64_binding.node

**Comment by nschonni** [comment]
See https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s
You're not running a comparable Node and node-sass version
