### ISSUE TITLE
Nominate multiple environmental bindings to be installed at once

### ISSUE THREAD

**Issue by alex-holt** [sass/node-sass#2609]
Hi there,  

I'm working on the same app in multiple environments and would like to pull down bindings for all environments using the just one npm install command in any of these environments. 

Is it possible to nominate which environment bindings are installed? 

ie. darwin-x64-57 and linux-x64-57 ?

**Comment by nschonni** [comment]
No this can't be done directly from NPM. You can setup an offline cache through the binary configs, but i'm not sure how well that works with the multiple environment setup https://github.com/sass/node-sass#binary-configuration-parameters
