### ISSUE TITLE
Replace binary download with optional platform specific packages

### ISSUE THREAD

**Issue by Toxicable** [sass/node-sass#2611]
Replacing the postinstall script of this package with platform specific optional dependencies will alleviate most of the issues around the binary dependency.

An example can be seen here:
https://github.com/bazelbuild/rules_nodejs/tree/master/packages/bazel
https://github.com/bazelbuild/rules_nodejs/tree/master/packages/bazel-win32_x64
https://github.com/bazelbuild/rules_nodejs/tree/master/packages/bazel-linux_x64
https://github.com/bazelbuild/rules_nodejs/tree/master/packages/bazel-darwin_x64

The parent package has an optional dependency on all 3 of the platform specific packages, but then only one of them will be downloaded by npm. 
This allows for better caching and easier mirroring.

We internally had an issue where 5 in 20 downloads of the binary would randomly be very slow to download. If this module handled it's platform binaries in this way then this could have been very easily avoided.

**Comment by xzyfer** [comment]
We require over 50 binaries. This is not sustainable.
