### ISSUE TITLE
Error: Missing Binding on Linux 64-bit with Node.js 11.x (Using CentOS 6.10)

### ISSUE THREAD

**Issue by sortinousn** [sass/node-sass#2615]
- NPM version (`npm -v`):
 `6.70`
- Node version (`node -v`): 
`11.10.0`
- Node Process (`node -p process.versions`): 
 `{ node: '11.10.0',v8: '7.0.276.38-node.17', uv: '1.26.0',zlib: '1.2.11', brotli: '1.0.7',ares: '1.15.0', modules: 
 '67',nghttp2: '1.34.0',napi: '4',llhttp: '1.1.1',http_parser: '2.8.0',openssl: '1.1.1a',cldr: '34.0',icu: '63.1',tz: 
 '2018e', unicode: '11.0' }`
- Node Platform (`node -p process.platform`):
`linux`
- Node architecture (`node -p process.arch`):
`x64`
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):
`node-sass@4.11.0 `

I'm Trying to run webpack in my Laravel project. I get this error on my linux machine. The OS is currently on centos-release-6-10 (CentOS V 6.10)   

I tried running the suggested command `npm rebuild node-sass` and also removed and re-installed node_modules to no avail.

```
throw new Error(errors.missingBinary());
      ^
Error: Missing binding /home/k4t59vro/dev.safcopayments.com/node_modules/node-sass/vendor/linux-x64-67/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 11.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/k4t59vro/dev.safcopayments.com/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/k4t59vro/dev.safcopayments.com/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
```

**Comment by nschonni** [comment]
> Found bindings for the following environments:
>   - Linux 64-bit with Node.js 6.x

If you've rebuilt and you're seeing this, then you might have something that is changing your node version. Maybe you're using a node version manager like NVM, or you've apt-get'd mutliple versions of Node

**Comment by sortinousn** [comment]
You're absolutely right. I didn't even know this box had NVM. Switching the version to 6.16 fixed my issue.

Thanks!
