### ISSUE TITLE
Failed at the node-sass@4.7.3 install script

### ISSUE THREAD

**Issue by HelloHang** [sass/node-sass#2616]
Running  npm install node-sass throws the following error. The error message is as follows。

7435 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
47436 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
47437 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
47437 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
47437 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
47437 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
47438 warn optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 (node_modules\phantomjs-prebuilt):
47439 warn optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 install: `node install.js`
47439 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
47440 verbose optional SKIPPING OPTIONAL DEPENDENCY:
47440 verbose optional Failed at the phantomjs-prebuilt@2.1.16 install script.
47440 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
47441 verbose stack Error: node-sass@4.9.3 install: `node scripts/install.js`
47441 verbose stack Exit status 1
47441 verbose stack     at EventEmitter.<anonymous> (E:\projects\bs\hybris\bin\ext-content\npmancillary\resources\npm\node\node-v10.7.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
47441 verbose stack     at EventEmitter.emit (events.js:182:13)
47441 verbose stack     at ChildProcess.<anonymous> (E:\projects\bs\hybris\bin\ext-content\npmancillary\resources\npm\node\node-v10.7.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
47441 verbose stack     at ChildProcess.emit (events.js:182:13)
47441 verbose stack     at maybeClose (internal/child_process.js:961:16)
47441 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
47442 verbose pkgid node-sass@4.9.3
47443 verbose cwd E:\projects\bs\hybris\bin\ext-content\npmancillary\resources\npm
47444 verbose Windows_NT 6.1.7601
47445 verbose argv "E:\\projects\\bs\\hybris\\bin\\ext-content\\npmancillary\\resources\\npm\\node\\node-v10.7.0-win-x64\\node.exe" "E:\\projects\\bs\\hybris\\bin\\ext-content\\npmancillary\\resources\\npm\\node\\node-v10.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install"
47446 verbose node v10.7.0
47447 verbose npm  v6.1.0
47448 error code ELIFECYCLE
47449 error errno 1
47450 error node-sass@4.9.3 install: `node scripts/install.js`
47450 error Exit status 1
47451 error Failed at the node-sass@4.9.3 install script.
47451 error This is probably not a problem with npm. There is likely additional logging output above.
47452 verbose exit [ 1, true ]

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
