### ISSUE TITLE
Consider replacing `request` package

### ISSUE THREAD

**Issue by SimonSchick** [sass/node-sass#2622]
You might want to consider replacing request as it is entering maintenance mode.
request/request#3142
request/request#3143

After a first look it should be relatively easy to replace request with the built-in http/https library as you are only using a tiny subset of its features.

**Comment by nschonni** [comment]
Request is used by node-gyp as well so replacing it wouldn't really remove the subdependncy. We tried other packages in the past, but `request` still has the best support for Proxies, which is needed for many consumers
