### ISSUE TITLE
node-sass will watch "css" files in directory mode

### ISSUE THREAD

**Issue by imhangoo** [sass/node-sass#2624]
Say I have `test.css`, then in same directory, I run
`node-sass -w ./ -o ./` (Watch files in directory)
It will watch changes in test.css and this only happens in watch mode.

But non-watch mode `node-sass ./ -o ./`  will give `No input file was found.` , which is as expected.

That is to say, node-sass will also watch all generated css files from sass/scss files in directory mode.

Is this a bug or by design?

- NPM version (`npm -v`): 6.9.0
- Node version (`node -v`): v10.15.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.15.0',
  v8: '6.8.275.32-node.45',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`): Cannot find module 'node-sass'
- npm node-sass versions (`npm ls node-sass`): 4.11.0

**Comment by saper** [comment]
There is a need for a breaking change for that, you may follow #2111 for details

See sass/libsass#2611
See #2184
See #2006
See #1933
See #1925
See #1867
See #1845
