### ISSUE TITLE
Unable to hook url() function when the parameter is not quoted

### ISSUE THREAD

**Issue by infinnie** [sass/node-sass#2626]
- NPM version (`npm -v`): 6.2.0
- Node version (`node -v`): 10.8.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
     node: '10.8.0',
     v8: '6.7.288.49-node.19',
     uv: '1.22.0',
     zlib: '1.2.11',
     ares: '1.14.0',
     modules: '64',
     nghttp2: '1.32.0',
     napi: '3',
     openssl: '1.1.0h',
     icu: '62.1',
     unicode: '11.0',
     cldr: '33.1',
     tz: '2018e' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.11.0
- npm node-sass versions (`npm ls node-sass`): 4.11.0

When running
```js
var Sass = require("node-sass");
Sass.render({
    data: ".a{test:url(a)}",
    functions: {
        "url($a)": function (x) {
            console.log(x.getValue());
        }
    }
}, function () { });
```
nothing is logged. However, when I quote the parameter passed to `url()`, 
```js
var Sass = require("node-sass");
Sass.render({
    data: ".a{test:url('a')}",
    functions: {
        "url($a)": function (x) {
            console.log(x.getValue());
        }
    }
}, function () { });
```
the string "a" does get logged.

What could I do besides quoting all URLs passed to the `url()` function?

**Comment by xzyfer** [comment]
Technically it's a bug that you can override url in this way. It's a
somewhat special function. Relying on quoted values trigger the custom
function is unsafe and isn't guaranteed to work in the future.

If you need to change the url function is suggest doing do with some other
tool like posr-css before or after the Sass compilation

**Comment by infinnie** [comment]
@xyzfer post-css?

**Comment by infinnie** [comment]
Maybe there needs to be an API for specifically hooking the `url()` function.

**Comment by xzyfer** [comment]
This feature suggestion is tracked as https://github.com/sass/sass/issues/2535

**Comment by infinnie** [comment]
Perhaps a convention that quoted URLs be hooked would be good enough.

**Comment by xzyfer** [comment]
This isn't behaviour we can guarantee at this time. This is a quirky of Libsass that isn't consistent across the major Sass engines. This is why we need it specified in the sass/sass repo.

**Comment by infinnie** [comment]
Documentation might be needed that recommends against hooking `url()` in SASS functions or the `functions` property passed to `sass.render()`.

**Comment by infinnie** [comment]
Still it surprises me that `libsass/src/functions.hpp` doesn’t handle the `url()` function at all.
