### ISSUE TITLE
Incorrect output for @-ms-keyframes

### ISSUE THREAD

**Issue by infinnie** [sass/node-sass#2628]
- NPM version (`npm -v`): 6.2.0
- Node version (`node -v`): 10.8.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
     node: '10.8.0',
     v8: '6.7.288.49-node.19',
     uv: '1.22.0',
     zlib: '1.2.11',
     ares: '1.14.0',
     modules: '64',
     nghttp2: '1.32.0',
     napi: '3',
     openssl: '1.1.0h',
     icu: '62.1',
     unicode: '11.0',
     cldr: '33.1',
     tz: '2018e' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.11.0
- npm node-sass versions (`npm ls node-sass`): 4.11.0

Running
```js
Sass.render({
    data: ".a{@-ms-keyframes t{0%{color:#fff}}}"
}, function (_, result) {
    console.log(result.css.toString());
});
```
the output would be like
```css
@-ms-keyframes t {
  .a 0% {
    color: #fff; } }
```

which is invalid CSS.

The problem does not occur when using unprefixed `@keyframes`.

**Comment by nschonni** [comment]
I can't reproduce this either with your included JS snippet or using the content in a file.
What is the output you're seeing?

**Comment by nschonni** [comment]
OK, I think I see it now, the unprefixed one outputs
```css
@keyframes t {
  0% {
    color: #fff; } }
```
Please open an issue on LibSass, since that is were any fix would need to be.

**Comment by nschonni** [comment]
On sassmiester, this is the same behaviour as Ruby-Sass 3.3, but not any of the newer releases or Dart-Sass

**Comment by infinnie** [comment]
Changing a line in `ast.hpp` would make node-sass behave as expected:
![image](https://user-images.githubusercontent.com/8168391/56351403-9c661000-61ff-11e9-9404-fec8490b7bbe.png)

**Comment by xzyfer** [comment]
Would appreciate a pr in Libsass

**Comment by nschonni** [comment]
Looks like this might have never been a real vendor prefixed element, which might have been why it wasn't updated https://github.com/CSSLint/csslint/issues/295#issuecomment-7599588 (I think it was introduced as a beta, but got unprefixed by the time IE10 final was released).
Unrelated to the bug, but you're better off not manually writting vendor prefixes and using a library like https://github.com/postcss/autoprefixer to add them post-comiliation depending on your targetted browsers

**Comment by infinnie** [comment]
I know that it was not really used. It just does not look good.

**Comment by shockthetoast** [comment]
@nschonni In case it's still a question, the original MSDN documentation verifies that `@-ms-keyframes` never hit a release browser.

March 2012 - MSDN lists `@-ms-keyframes` as being new to IE10.
https://web.archive.org/web/20120318151807/http://msdn.microsoft.com/en-us/library/ie/hh772747(v=vs.85).aspx
(Caniuse verifies CSS animation wasn't available in IE9: https://caniuse.com/#feat=css-animation)

July 2012 - shortly _before_ IE10 released, MSDN marks `@-ms-keyframes` as deprecated and says to use `@keyframes`:
> The version of this rule using a vendor prefix, @-ms-keyframes, has been deprecated. To ensure compatibility in the future, applications using this rule with a vendor prefix should be updated accordingly.

https://web.archive.org/web/20120827002451/http://msdn.microsoft.com/en-us/library/ie/hh772747(v=vs.85).aspx

November 2012 - MSDN makes it even clearer that `@-ms-keyframes` should never be used:
> Do not use the Microsoft vendor prefix ("-ms-") before the Cascading Style Sheets (CSS) animations properties.  They are supported unprefixed in Internet Explorer 10 and later.

https://web.archive.org/web/20120827002451/http://msdn.microsoft.com:80/en-us/library/ie/hh772747(v=vs.85).aspx

**Comment by saper** [comment]
If the issue is still relevant the PR should be directed to libsass.
