### ISSUE TITLE
U+F00D appended to the output filename of CLI if the script invoking node-sass contains CRLF line endings

### ISSUE THREAD

**Issue by riddlemd** [sass/node-sass#2631]
- NPM version (`npm -v`): 6.9
- Node version (`node -v`): 11.14
- Node Process (`node -p process.versions`): 11.14
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.11
- npm node-sass versions (`npm ls node-sass`): 4.11

#### What I did:
Setup a shell script `build-dev.sh` which contains:
```
node-sass ./scss/input.scss ./css/output.css
rollup -c -f iife -i ./js/input.js -o ./js/output.js
``` 
and run it via `npm run build-dev`.

#### What I got
A file in ./css/ named output.css  -- notice the strange extra character? The character only appears if there more lines following the node-sass call, it's strange because no other command is having this issue.

#### [EDIT1]
Ok this is wild, so apparently it's related to \r\n newlines in the .sh file -- Not sure why it's outputting U+F00D some places, but doing ls in bash it's ^M and with a bit of googling that's common issue with script that don't handle \r\n correctly.

Is there something different you guys are doing to parse args vs other scripts? Because node-sass is the only npm module I've had this issue with. In the meantime anyone that runs into this issue, just change from using \r\n to \n eol. (If you're using VS Code it's down in the lower right corner where it says CRLF, VS code automatically uses CRLF over LF if it detects ANY CRLF in the file.)

**Comment by saper** [comment]
Doesn't not look like anything related to node-sass to me. I'd suggest fixing your editor to provide normal characters to the shell. There is nothing special in the node-sass processing.
