### ISSUE TITLE
404 Not Found x64-72

### ISSUE THREAD

**Issue by straxico** [sass/node-sass#2634]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-72_binding.node

Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-72_binding.node": 

HTTP error 404 Not Found

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/2632
