### ISSUE TITLE
[Security] new node-gyp version available to patch security vulnerability

### ISSUE THREAD

**Issue by benwiley4000** [sass/node-sass#2636]
Since the #2625 discussion got locked I had to open a new thread, but just wanted to note that a few hours ago node-gyp v4.0.0 was released which patches the security vulnerability with the tar package.

https://github.com/nodejs/node-gyp/pull/1718#issuecomment-486024548

The major version bump is because node-gyp v4 drops support for any Node.js version lower than 6. This sounds like a big change since node-sass currently supports Node.js 0.10 and higher.

## *However...*

I noticed that the currently used version of node-gyp (v3.8) only officially supports Node.js 4 and higher, so perhaps the Node version restriction is irrelevant for node-sass's use case, and it could be released as a minor or patch version bump.

**Comment by xzyfer** [comment]
Thank you. We're aware of the update and are considering our options.

**Comment by gpkoltermann** [comment]
They bumped tar and loosen up node constraints 2 days ago. I think now you can update :). Please take a look here: https://github.com/nodejs/node-gyp/issues/1714#issuecomment-489638042
