### ISSUE TITLE
npm i node-sass@latest fails on travis build server

### ISSUE THREAD

**Issue by shanplourde** [sass/node-sass#2642]
Hello, my project builds locally, but fails on travis when it attempts to build. I was hoping you might have some ideas about it. 

Travis build link: https://travis-ci.com/shanplourde/react-hooks-form-util/builds/109692828

From build log: 

$ node --version
v12.0.0
$ npm --version
6.9.0
$ nvm --version
0.34.0

I'm not sure sure what node process and platform versions are in use on Travis. 

I had node-sass@latest, then tried node-sass@4.10.0. When the build first broke on travis I hadn't changed anything related to node-sass, but I had added yup, and bumped up the patch version of react-hooks-testing-library.

Any suggestions or pointers are appreciated

**Comment by nschonni** [comment]
See pinned issue https://github.com/sass/node-sass/issues/2632
