### ISSUE TITLE
Missing binary 4.11.0

### ISSUE THREAD

**Issue by MalteOschlies** [sass/node-sass#2643]
Our pipeline fails with
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node": 

Yesterday it stil worked with x64-67, was there an update today?

**Comment by skjnldsv** [comment]
Same here

**Comment by nschonni** [comment]
Duplicate of #2632
