### ISSUE TITLE
Node sass fails to install on alpine

### ISSUE THREAD

**Issue by materemias** [sass/node-sass#2646]
Node in alpine container cannot install node-sass

```
node-sass@4.11.0 install /app/node_modules/node-sass
node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-72_binding.node": 
HTTP error 404 Not Found
```
the same build went well yesterday, seems like the referenced binary is missing

**Comment by materemias** [comment]
found out this was me using node:alpine image and node being updated to v12. node:11-alpine works.
when #2632 gots resolved this will be ok too.

**Comment by AshuSingh07** [comment]
I had the same issue and resolve by downgrading my node version to one of older version 8.0.0
