### ISSUE TITLE
latest 4.12.0 version doesn't support nodejs 6.9.1

### ISSUE THREAD

**Issue by kadinwu** [sass/node-sass#2651]
npm install which will install latest node-sasss 4.12.0 version, failed with below errors.
4.11.0 version is fine.

[ERROR] npm ERR! node v6.9.1
10:58:18  [ERROR] npm ERR! npm  v3.10.8
10:58:18  [ERROR] npm ERR! code ELIFECYCLE
10:58:18  [ERROR] 
10:58:18  [ERROR] npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
10:58:18  [ERROR] npm ERR! Exit status 1
10:58:18  [ERROR] npm ERR! 
10:58:18  [ERROR] npm ERR! Failed at the node-sass@4.12.0 postinstall script 'node scripts/build.js'.
10:58:18  [ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
10:58:18  [ERROR] npm ERR! If you do, this is most likely a problem with the node-sass package

**Comment by xzyfer** [comment]
Open a new issue following the issue template.
