### ISSUE TITLE
Dependency Vulnerability

### ISSUE THREAD

**Issue by ErenYatkin** [sass/node-sass#2654]
Hello, I added `node-sass` and npm audit throws and high severity vulnerability. Do you have any idea about how to fix this ?
![Ekran Resmi 2019-04-29 13 09 04](https://user-images.githubusercontent.com/8920659/56889865-60913d00-6a80-11e9-91f0-3f89ce54cc9f.png)

**Comment by ErenYatkin** [comment]
Running `npm audit fix` second time fixed the issue.

**Comment by nschonni** [comment]
Duplicate of #2625
