### ISSUE TITLE
Audit issues with the latest version

### ISSUE THREAD

**Issue by bsas** [sass/node-sass#2657]
Already tried everything including deleting the lock file and the entire node_modules folder.
This audit error doesn't make sense since I am using the latest version but it is an error on the old version.

- **Docker version**: node:10.15.3-jessie

- **NPM version** (`npm -v`): 6.4.1

- **Node version** (`node -v`): v10.15.3

- **Node Process** (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }

- **Node Platform** (`node -p process.platform`): linux

- **Node architecture** (`node -p process.arch`): x64

- **node-sass version** (`node -p "require('node-sass').info"`):
node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]

- **npm node-sass versions** (`npm ls node-sass`):
`-- node-sass@4.12.0

- **Audit error** (`npm audit`):
                                 Manual Review
             Some vulnerabilities require your attention to resolve
          Visit https://go.npm.me/audit-guide for additional guidance

  High            Arbitrary File Overwrite                       
  Package         tar                                                      
  Patched in      >=4.4.2                                            
  Dependency of   node-sass [dev]                           
  Path            node-sass > node-gyp > tar                
  More info       https://nodesecurity.io/advisories/803                        

found 1 high severity vulnerability in 31872 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by nschonni** [comment]
Duplicate of #2625
