### ISSUE TITLE
ARM64v8 not supported

### ISSUE THREAD

**Issue by eidram** [sass/node-sass#2667]

**Comment by xjw181221** [comment]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/linux-arm64-64_binding.node"   --same issue

**Comment by nschonni** [comment]
We're looking at ARM support in #2647, but we've never supported ARM for any version before

**Comment by maltebeckmann** [comment]
> We're looking at ARM support in #2647, but we've never supported ARM for any version before

Thanks for looking into support for ARM. I tried to pull off a super simple docker project on my RPi 4 but compiling in the docker image just seems a bit too much. Thanks for your efforts!

**Comment by midhunvnadh** [comment]
@nschonni Hi, can't we use arm64/armhf chroot on github CI to get arm64/armhf node-sass build?

Please we need arm64 support.
Thanks.

**Comment by saper** [comment]
You can build a binary yourself once and just distribute the binding.node to your projects. It does not have to be compiled every time.

**Comment by midhunvnadh** [comment]
Oh okay
