### ISSUE TITLE
Installing node-sass 4.11.0 with Node 11.14.0

### ISSUE THREAD

**Issue by vicabelotelova** [sass/node-sass#2668]
Please help!
node version 11.14.0
npm version 6.9.0
npm ERR! file C:\Program Files\Git\cmd
npm ERR! path C:\Program Files\Git\cmd
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Git\cmd
npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
npm ERR! spawn C:\Program Files\Git\cmd ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vica\AppData\Roaming\npm-cache\_logs\2019-05-13T17_29_27_029Z-debug.log
[2019-05-13T17_29_27_029Z-debug.log](https://github.com/sass/node-sass/files/3174086/2019-05-13T17_29_27_029Z-debug.log)

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
