### ISSUE TITLE
@at-root and @import 

### ISSUE THREAD

**Issue by javierartero** [sass/node-sass#2669]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v10.15.3
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): └── node-sass@4.12.0

------

I think, it could be a cool idea if we can modify the scope with `@import` and `@at-root`

```
@at-root {
  @import '~bootstrap/scss/functions';
  @import '~bootstrap/scss/variables';
  @import '~bootstrap/scss/mixins';

  $modal-header-padding: 3rem;
  $modal-inner-padding: 3.5rem;
  $modal-footer-border-width: 0;
  @import '~bootstrap/scss/modal';
}
```

But it shows me the following error:

```
      Import directives may not be used within control directives or mixins.
```

`@at-root` according to the [documentation](https://sass-lang.com/documentation/at-rules/at-root) is not a [mixin](https://sass-lang.com/documentation/at-rules/mixin) and is not a [control directive](https://sass-lang.com/documentation/at-rules/control).

**Comment by nschonni** [comment]
Sounds like you're looking for a change to the language. That should be opened over on https://github.com/sass/sass
I don't see what this would give you since `@import` isnt' scoped, and will be replaced with the module system in the next language version

**Comment by javierartero** [comment]
Sorry to be corrected but `@import` if it can be used with scope, the problem is that only from another selector or an `@at-rule` such as `@supports`, for this it is much better `@at-root` since it does not create any markup extra and allows you to specify the scope.

https://sass-lang.com/documentation/at-rules/import#nesting

### same scope:

```
$colors: (
  'blue': #0673a2,
  'dark-blue': #232045,
  'indigo': #6610f2,
  'purple': #b2abff,
  'pink': #f0589e,
  'red': #ed3c50
);

:root {
  @import '~bootstrap/scss/functions';
  @debug color('blue');
}
```

result:
```
DEBUG: #0673a2
```

### out of scope

```
$colors: (
  'blue': #0673a2,
  'dark-blue': #232045,
  'indigo': #6610f2,
  'purple': #b2abff,
  'pink': #f0589e,
  'red': #ed3c50
);

:root {
  @import '~bootstrap/scss/functions';
}

@debug color('blue');
```

result: 
```
DEBUG: color("blue")
```

In my opinion it is a node-sass problem that is confusing `@at-rule` with a mixin or a control directive.

The main advantage is to prevent those mixins or functions from being accessed from outside @at-root.
