### ISSUE TITLE
Installing node-sass 4.11.0 with Node 11.14.0 #2668

### ISSUE THREAD

**Issue by vicabelotelova** [sass/node-sass#2670]
- NPM version (6.5.0):
- Node version (11.14.0):
- Node Process 
{ node: '11.14.0',
  v8: '7.0.276.38-node.18',
  uv: '1.27.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '67',
  nghttp2: '1.37.0',
  napi: '4',
  llhttp: '1.1.1',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '34.0',
  icu: '63.1',
  tz: '2018e',
  unicode: '11.0' }
- Node Platform (win32):
- Node architecture (x64):
- node-sass version 
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:124:20)
    at Object.runInThisContext (vm.js:314:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at evalScript (internal/process/execution.js:60:25)
- npm node-sass versions
+-- @angular-devkit/build-angular@0.13.9
| `-- UNMET OPTIONAL DEPENDENCY node-sass@4.12.0
`-- UNMET DEPENDENCY node-sass@^4.11.0
npm ERR! missing: node-sass@^4.11.0, required by task@0.0.0
npm ERR! file C:\Program Files\Git\cmd
npm ERR! path C:\Program Files\Git\cmd
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Git\cmd
npm ERR! node-sass@4.12.0 install: node scripts/install.js
npm ERR! spawn C:\Program Files\Git\cmd ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Vica\AppData\Roaming\npm-cache_logs\2019-05-13T17_29_27_029Z-debug.log
[2019-05-13T17_29_27_029Z-debug.log](https://github.com/sass/node-sass/files/3178780/2019-05-13T17_29_27_029Z-debug.log)

i need to install "node-sass" or update my dependencies to 4.12.0 but i got an error anywhere
what i must do?

**Comment by nschonni** [comment]
Can you try installing node-sass into a separate folder to see if the issue is something with the cli/current node_modules?

**Comment by conrallendale** [comment]
The version 4.11 was simply removed from release page (https://github.com/sass/node-sass/releases), breaking all builds which use it as a dependency and rebuild the sass (npm rebuild node-sass). The rebuild is necessary to correct a bug when building a Vue project.

The removal was intentional?

**Comment by nschonni** [comment]
Nothing was removed https://github.com/sass/node-sass/releases/tag/v4.11.0

**Comment by conrallendale** [comment]
Sorry for the incomplete feedback. I'm posting the log of our build process. As I can see, only the "binding" files was removed:

`17:32:53 #10 39.14 > node-sass@4.11.0 install /app/node_modules/node-sass
17:32:53 #10 39.14 > node scripts/install.js
17:32:53 #10 39.14 
17:32:57 #10 43.10 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-72_binding.node
17:32:58 #10 44.17 Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux_musl-x64-72_binding.node": 
17:32:58 #10 44.17 
17:32:58 #10 44.17 HTTP error 404 Not Found`

**Comment by nschonni** [comment]
That is Node 12, and you need to upgrade to support that version https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimium-support
I'm hiding this discussion because it's not related to the original issue
