### ISSUE TITLE
Installing on plesk

### ISSUE THREAD

**Issue by mjmnagy** [sass/node-sass#2674]
Hi, 

Ive been looking online for a solution to installing node-sass on my plesk server. I read that this is kind of a no no as this should not be done on a production server(dont care - not a live site).
 
I have uploaded the documents via bitbucket and click the NPM install button. The result is the failure below:

	3822 verbose stack Error: node-sass@4.12.0 install: `node scripts/install.js`
	3822 verbose stack spawn ENOENT
	3822 verbose stack     at ChildProcess.<anonymous> (/opt/plesk/node/9/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
	3822 verbose stack     at ChildProcess.emit (events.js:180:13)
	3822 verbose stack     at maybeClose (internal/child_process.js:936:16)
	3822 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
	3823 verbose pkgid node-sass@4.12.0
	3824 verbose cwd /var/www/vhosts/mjmnagy.info/app
	3825 verbose Linux 3.10.0-862.9.1.el7.x86_64
	3826 verbose argv "/opt/plesk/node/9/bin/node" "/opt/plesk/node/9/bin/npm" "install"
	3827 verbose node v9.10.1
	3828 verbose npm  v5.6.0
	3829 error file sh
	3830 error code ELIFECYCLE
	3831 error errno ENOENT
	3832 error syscall spawn
	3833 error node-sass@4.12.0 install: `node scripts/install.js`
	3833 error spawn ENOENT
	3834 error Failed at the node-sass@4.12.0 install script.
	3834 error This is probably not a problem with npm. There is likely additional logging output above.
	3835 verbose exit [ 1, true ]

I attempted to login to the server using SSH but for the life of me couldn't figure out how to install it.

Using SSH,  i navigated to where node is install (`/opt/plesk/node/7/bin/`) trying 6/7/8 and then running npm. i always got unrecognized command.

I then realized that the version i have of node-sass was higher than the node version install on the server(`9.10.1`)

What do i need to do to be able to install the module?

**Comment by xzyfer** [comment]
Have you read through the troubleshooting guide?

**Comment by mjmnagy** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md ?

Yes. 
Im still unable to install the module. Plesk is becoming more of a hassle than its worth

**Comment by xzyfer** [comment]
All I can think of is adding the --unsafe-perms flag to npm install.
Otherwise I suggest skimming through the npm error log file for an obvious
error block.

**Comment by mjmnagy** [comment]
Hi, 

i was unsure of how i could run the command as plesk actually just has the button to install them. I added a script into my package.json `"install": "npm i --unsafe-perms"` and it installed
