### ISSUE TITLE
Node-sass 4.8.3 with Node 10.13

### ISSUE THREAD

**Issue by thany** [sass/node-sass#2677]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 10.13
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '10.13.0',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
```
node-sass       4.8.3   (Wrapper)       [JavaScript]
libsass         3.5.2   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): 
```
Landal_CRO@1.0.0 C:\workspaces\landal-cro
`-- (empty)
```

Installing node-sass 4.8.5 on Node 10.13 wants to compile from, I guess C++ sources. I cannot change these versions. It's a big project, and I can't just willy-nilly start upgrading (or downgrading) components. So, I'm stuck with this combination, at least for now.

What that out of the way, at first, I noticed installing node-sass requires Python 2.
Okay...? That's a kinda weird requirement for a component that's built in C++ and used with javascript? What does python have to do with anything?

Anyway. Installed. Works better now. Next error is about MSBuild. It really wants the C++ build tools and such, *and* the entire Windows SDK. Isn't that a bit... much? Shouldn't a compiler be enough?

So installed that too. 20 minutes and a reboot later, node-sass installs (and compiles, I guess) just fine.

So the bottomline is two things:
1) Why does installing node-sass require installing so much (literally gigabytes!) of extra bloat? It only needs to be installed once, but still.
2) Can't you just place a prebuilt binary somewhere that is downloaded during installation? I guess I could donate mine, now that it's been built successfully.

**Comment by xzyfer** [comment]
We supply pre-built for the compatible version combination as documented at
the top of the readme. We also make it easy for you support host your own
pre-built for unsupported combinations that may still work.

As for why you need python et al that's simply how the team supports
building native extensions. Raise you issue with them.

**Comment by thany** [comment]
Okay, so why is this particular combination unsupported? Is there something magical about the supported combinations?

**Comment by xzyfer** [comment]
Typically supported versions are which versions existed at time of the node
sass release. We can know what changes will land in future major versions
so there's no way we build the binding code such that it's forward
compatible.
