### ISSUE TITLE
Importing a js file with node-sass imported gives error: Uncaught TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by FlorisSchippers** [sass/node-sass#2678]
# Context
I am working on a webappliction with Vue and want to preprocess some user-made sass/scss to give the user css back.

# What I did
I installed the package with  
`npm install node-sass`  
Imported node-sass in my preprocessor.js file with  
`import sass from 'node-sass';`  
Imported preprocessor.js in my Vue project with  
`import preprocessor from '../../../helpers/preprocessor';`

# What I get
![errormessage](https://i.imgur.com/e7915Sn.png)

# Troubleshooting data
```zsh
 ~  mkdir ~/temp1
cd ~/temp1
 ~/temp1  npm -v
node -v
node -p process.versions
node -p process.platform
node -p process.arch
6.9.0
v11.13.0
{ node: '11.13.0',
  v8: '7.0.276.38-node.18',
  uv: '1.27.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '4',
  llhttp: '1.1.1',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '34.0',
  icu: '63.1',
  tz: '2018e',
  unicode: '11.0' }
darwin
x64
 ~/temp1  npm install node-sass@latest

> node-sass@4.12.0 install /Users/florisch/temp1/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/florisch/.npm/node-sass/4.12.0/darwin-x64-67_binding.node

> node-sass@4.12.0 postinstall /Users/florisch/temp1/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/florisch/temp1/node_modules/node-sass/vendor/darwin-x64-67/binding.node
Testing binary
Binary is fine
npm WARN saveError ENOENT: no such file or directory, open '/Users/florisch/temp1/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/florisch/temp1/package.json'
npm WARN temp1 No description
npm WARN temp1 No repository field.
npm WARN temp1 No README data
npm WARN temp1 No license field.

+ node-sass@4.12.0
added 174 packages from 138 contributors and audited 529 packages in 3.727s
found 0 vulnerabilities

 ~/temp1  npm ls node-sass

/Users/florisch/temp1
└── node-sass@4.12.0 

 ~/temp1  node -p "require('node-sass').info"
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
 ~/temp1  cd node_modules/node-sass/vendor
 ~/temp1/node_modules/node-sass/vendor  node -p "require('node-sass').info"

node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

Edit: Updated 'troubleshooting data' codeblock with zsh highlighting

**Comment by nschonni** [comment]
Are you trying to load node-sass on the client side through Vue?
I don't think this is something we'll be able to help with, and might get more responses on StackOverflow

**Comment by FlorisSchippers** [comment]
`node-sass` cannot run in the browser, I fixed this issue by making a API endpoint which runs in a node environment.

**Comment by ruthall87** [comment]
having the same issuse and none of these forums can figure it out TypeError: fs.existsSync is not a function
hasBinary
node_modules/node-sass/lib/extensions.js:405
  402 |  */
  403 | 
  404 | function hasBinary(binaryPath) {
> 405 |   return fs.existsSync(binaryPath);
  406 | }
  407 | 
  408 | /**
View compiled
push../node_modules/node-sass/lib/binding.js.module.exports
node_modules/node-sass/lib/binding.js:11
   8 |  * Require binding
   9 |  */
  10 | module.exports = function(ext) {
> 11 |   if (!ext.hasBinary(ext.getBinaryPath())) {
  12 |     if (!ext.isSupportedEnvironment()) {
  13 |       throw new Error(errors.unsupportedEnvironment());
  14 |     } else {
