### ISSUE TITLE
Installing node-sass fails on Ubuntu 18.04.02 LTS

### ISSUE THREAD

**Issue by MiroJ** [sass/node-sass#2679]
I have a simple Next.js project that requires node-sass. When running `npm install` on Ubuntu 18.04.02, node-sass fails and nothing gets installed.

I have followed the basic debugging instructions here (empty `Temp1` folder with `npm install node-sass@latest`) and the output in the CLI is in this [gist](https://gist.github.com/MiroJ/a9d0acbfe2773f92f6ff409020dc9ba9). 

I have tried `npm install node-sass --force ` as well with the same result.

The required system information is below:

- NPM version (`npm -v`): **6.4.1**
- Node version (`node -v`): **10.15.3**
- Node Process (`node -p process.versions`): 
{
  http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' 
}
- Node Platform (`node -p process.platform`): **linux**
- Node architecture (`node -p process.arch`): **x64**
- node-sass version (`node -p "require('node-sass').info"`): **^4.12.0**
- npm node-sass versions (`npm ls node-sass`): **empty**

**Comment by xzyfer** [comment]
Try npm install --unsafe-perms

**Comment by MiroJ** [comment]
That, with some experimenting with the `owner` and `group` credentials of the folder fixed it. Thank you!
