### ISSUE TITLE
Sourcemap wrong lines - webpack

### ISSUE THREAD

**Issue by betorobson** [sass/node-sass#2684]
It looks like that sass-loader is generating a sourcemap which point out wrong lines.

I am not sure if it is a bug or a bad rule configuration however, after a long few days looking for a answer I was not able to find and solution.

Here a example of what is wrong, it is possible to see on first screenshot my css on line 12 is point out by the source map at line 6.

![Screenshot from 2019-06-03 14-16-08](https://user-images.githubusercontent.com/13212208/58823784-e6208380-8610-11e9-9182-a4ff059eff0b.png)
![Screenshot from 2019-06-03 14-15-48](https://user-images.githubusercontent.com/13212208/58823790-e7ea4700-8610-11e9-9538-b26ba37270af.png)

Could you please guys help me out to get what could be wrong here?

* Operating System: Ubuntu 18.04
* Node Version: 10.15.3
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* sass-loader Version: 7.1.0

### Code - webpack - Sass rules
```js
	// Docs SASS files
	{
		test: /[\\/]dev-tools[\\/]docs[\\/].+\.scss$/,
		use: [
			MiniCssExtractPlugin.loader,
			{
				loader: 'css-loader',
				options: {
					sourceMap: true
				}
			},
			{
				loader: 'resolve-url-loader',
				options: {
					sourceMap: true
				}
			},
			{
				loader: 'sass-loader',
				options: {
					sourceMap: true
				}
			}
		]
	},
```

**Comment by nschonni** [comment]
This might be related to this project, but you've given version info for https://github.com/webpack-contrib/sass-loader/issues
sass-loader can also use dart-sass, so it might not be compiling with node-sass at all

**Comment by betorobson** [comment]
I found the solution and this can help others.
I just added the `outputStyle: 'compressed'  in sass-loader, so my config is like that:
```javascript
{
	loader: 'sass-loader',
	options: {
		outputStyle: 'compressed',
		sourceMap: true,
	}
}
```
I am sure that there are many other developers facing the same issue.

**Comment by betorobson** [comment]
@nschonni I have try to warning that `sass-loader` guys without any success. They just need to change a line in README. That is so sad when people are not make any effort to help others developers. Any way, tks for your help :-).

https://github.com/webpack-contrib/sass-loader/pull/690

**Comment by SweetsXob** [comment]
> I found the solution and this can help others.
> I just added the `outputStyle: 'compressed' in sass-loader, so my config is like that:
> 
> ```js
> {
> 	loader: 'sass-loader',
> 	options: {
> 		outputStyle: 'compressed',
> 		sourceMap: true,
> 	}
> }
> ```
> 
> I am sure that there are many other developers facing the same issue.

#### I also tried this configuration, but some selectors are normal, some selectors are not normal

**Comment by NickolasBoyer** [comment]
Some weird things can happen when using `css-loader` and `sass-loader` with sourcemaps. I'm not sure if this is going wrong in `node-sass` or `sass-loader` but this seems like the most relevant place to leave it:

When `outputStyle` is not set to `'compressed'` source contents and paths (under the sources property in the sourcemap) are included twice.

Furthermore, the second source path (generated by `sass-loader`) mistakenly adds the relative file directory (relative to the project root that is) for a second time. Example:

``` json
sources: [
  "/Users/admin/Desktop/devsync-test-setups/webpack-test/src/styles/index.scss"
  "/Users/admin/Desktop/devsync-test-setups/webpack-test/src/styles/src/styles/index.scss"
]
```
_When `outputStyle` is not set to `'compressed'` only the second path is included._
