### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [sass/node-sass#2686]
On [this](https://www.npmjs.com/package/node-sass) website there is the following section:

> Some users have reported issues installing on Ubuntu due to node being registered to another package. Follow the official NodeJS docs to install NodeJS so that #!/usr/bin/env node correctly resolves.

where the link (pointing to [here](https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager)) hasn't been working for a long while. You can see how it looked like when it last worked in 2016 over [here](https://web.archive.org/web/20160326221735/https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager).

I'm too much of a beginner to understand what text should be copied over or what should be done. So just letting you know.

**Comment by schwigri** [comment]
I created a pull request for this issue: [#2753](https://github.com/sass/node-sass/pull/2753).

**Comment by xzyfer** [comment]
Fixed in #2753
