### ISSUE TITLE
[Security vulnerabilities] Update node-gyp to 4.0.0

### ISSUE THREAD

**Issue by shinhwas** [sass/node-sass#2687]
There were security vulnerabilities (related to node-gyp -> tar)
https://www.npmjs.com/advisories/803

That are now supposedly fixed as of node-gyp@4.0.0.
Could you update node-gyp to 4?

**Comment by nschonni** [comment]
Asked and answered many times https://github.com/sass/node-sass/search?q=node-gyp+to+4.0.0&type=Issues
