### ISSUE TITLE
Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by powerlimit** [sass/node-sass#2691]
- NPM version : 6.9.0
- Node version: 12.4
- Node Process:
`
{
  node: '12.4.0',
  v8: '7.4.288.27-node.18',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
`
- Node Platform: linux mint 19.1
- Node architecture : x64
- node-sass version:
`
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
`
- npm node-sass versions: node-sass@4.12.0
![image](https://user-images.githubusercontent.com/27887514/59178818-ccc78c00-8b68-11e9-8e07-bf0b74c8578c.png)

can someone explain what the hell?

**Comment by nschonni** [comment]
I would guess this might have something to do with workspace mappings and docker. I do see the message is confusing. Can you see what the contents of the "vendor" folder are inside and outside the container?

**Comment by powerlimit** [comment]
nwm.... few hours ago i find solution. command `npm rebuild node-sass --force` works, but it must be executed in nodejs container. BUT firstly we must add python to container. 
``
FROM node:12-alpine
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*
... lot of code...
RUN npm rebuild node-sass --force

ARG APP_ENV=prod
RUN yarn install \
 && if [ "$APP_ENV" != "dev" ]; then \
        yarn run encore production \
    ;fi

COPY docker/nodejs/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
``
and problem solved)))

**Comment by xzyfer** [comment]
Never run rebuild --force. Just install the correct version of node-sass as
stated above.
