### ISSUE TITLE
cannot download linux-x64-72_binding.node

### ISSUE THREAD

**Issue by Nathanlee2010** [sass/node-sass#2694]
![image](https://user-images.githubusercontent.com/20190746/59490631-ca8e6600-8eb7-11e9-96f6-c850e4f2cfad.png)

**Comment by Nathanlee2010** [comment]
I have temporarily solved this problem.

I manually modify devDependencies.node-sass from "^4.9.2" to "^4.12.0"    it works。

I want to know why this problem arises?   

Why can't npm get the latest node-sass on node version 12?  i have used "^" mark

**Comment by nschonni** [comment]
node-sass is a native module, the supported versions are listed here https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimium-support
