### ISSUE TITLE
'node"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by version03** [sass/node-sass#2696]
This is an error occurred while I run the js code in the atom.  I'm struggling to solve this error from days anyone knows
![problem](https://user-images.githubusercontent.com/51793206/59556151-5b119700-8fdb-11e9-80fa-80f8846ccccd.png)

 how to overcome this error while running using the script package in the atom can help me thanks in advance.

**Comment by nschonni** [comment]
This doesn't look like it's related to node-sass. I suggest asking your question on stackoverflow
