### ISSUE TITLE
Proxy error after upgrading to Node 10.16.0

### ISSUE THREAD

**Issue by Jeoffreybauvin** [sass/node-sass#2697]
Hi there,

- NPM version (`npm -v`): 6.9.0
- Node version (`node -v`): v10.16.0
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '10.16.0',
  v8: '6.8.275.32-node.52',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '4',
  openssl: '1.1.1b',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019a' }

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64

We are behing a corporate proxy.

My npmrc :

```
$ cat ~/.npmrc 
proxy=http://10.2.223.24:3128/
https-proxy=http://10.2.223.24:3128/
```

I have no issue downloading packages. But after upgrading from 10.15.1 to  10.16.0, node-sass doesn't use proxy anymore : 

```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-64_binding.node": 

ETIMEDOUT

Timed out attemping to establish a remote connection

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

Rollbacking to 10.15.0 and everything is working again...

Looks like node-sass is not using my npmrc anymore. But if I'm setting manually the proxy, it's working  with node 10.16 : 

```
$ HTTP_PROXY=http://10.2.223.24:3128/  npm ci
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.9 install front/node_modules/fsevents
> node install

> husky@1.3.1 install front/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> node-sass@4.11.0 install front/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-64_binding.node
Download complete
Binary saved to front/node_modules/node-sass/vendor/linux-x64-64/binding.node

> node-sass@4.11.0 postinstall front/node_modules/node-sass
> node scripts/build.js

Binary found at front/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
added 1384 packages in 18.553s
```
Regards,

**Comment by xzyfer** [comment]
Sounds like a node or system issue. Nothing to do with node-sass.

**Comment by Jeoffreybauvin** [comment]
It happens only with node-sass...

**Comment by xzyfer** [comment]
I don't know what to say. This code hasn't changed in a long time. Could
any number of things from the request library, to network issues talking to
our binary host. Either way there is nothing we can do.

**Comment by mrSingh007** [comment]
facing same issue. I have tried node v12 but still having problem
