### ISSUE TITLE
"C:\Microsoft.Cpp.Default.props" was not found

### ISSUE THREAD

**Issue by mamoorkhan** [sass/node-sass#2699]
- NPM version (`npm -v`):
6.9..0
- Node version (`node -v`):
12.4.0
- Node Process (`node -p process.versions`):

```
{
  node: '12.4.0',
  v8: '7.4.288.27-node.18',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`):
win32
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):

```
Project \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.sln\" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration \"Release|x64\".
Project \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.sln\" (1) is building \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (2) on node 1 (default targets).
Project \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (2) is building \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\src\\libsass.vcxproj\" (3) on node 1 (default targets).
C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\src\\libsass.vcxproj(21,3): error MSB4019: The imported project \"C:\\Microsoft.Cpp.Default.props\" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\src\\libsass.vcxproj\" (default targets) -- FAILED.
Done Building Project \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (default targets) -- FAILED.
Done Building Project \"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.sln\" (default targets) -- FAILED.

Build FAILED.

\"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.sln\" (default target) (1) ->
\"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (default target) (2) ->
\"C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\src\\libsass.vcxproj\" (default target) (3) ->
  C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\src\\libsass.vcxproj(21,3): error MSB4019: The imported project \"C:\\Microsoft.Cpp.Default.props\" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.27
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\node-gyp\\lib\\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\repos\\\\delivany\\\\delivany.consumer.web\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd C:\\repos\\delivany\\delivany.consumer.web\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by nschonni** [comment]
> "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.

Looks like your Visual Studio copy might not have the correct workloads. This would be something to check to see if you meet the node-gyp requirements.
Given your os/node versions, you shouldn't need to be manually building the bindings. If you're connected to the internet, the pre-built bindings should just be downloaded for you on install.

**Comment by buffos** [comment]
It builds fine here if I just install node-sass. If there are other dependencies (for example angular that requires a previous version of node-sass) it breaks.

**Comment by hooray** [comment]
same problem

**Comment by buffos** [comment]
> same problem

A question. Did you try on a blank project? Just npm init and then install node-sass.

**Comment by hooray** [comment]
> > same problem
> 
> A question. Did you try on a blank project? Just npm init and then install node-sass.

yes, in the blank project the problem still exists.

**Comment by nschonni** [comment]
> check python checking for Python executable "python2" in the PATH

This isn't the same issue as the original poster. You don't have python2 which is a requirements to build node-gyp modules https://github.com/nodejs/node-gyp#on-windows

**Comment by hooray** [comment]
@nschonni thx, but I find other way to solve this problem.

**Comment by saper** [comment]
Can you check your log against a [good build on AppVeyor](https://ci.appveyor.com/project/sass/node-sass/builds/28163289/job/jk8yq7apk0d1xary?fullLog=true) and see what the differences are?

**Comment by mamoorkhan** [comment]
The problem was fixed when I installed the incredibuild, which is used to build node-sass on my machine, I am still not sure why it was building from sources on my machine, but that is how I solved the problem at my previous workplace. Where I don't work anymore.

**Comment by crisz** [comment]
> Given your os/node versions, you shouldn't need to be manually building the bindings. If you're connected to the internet, the pre-built bindings should just be downloaded for you on i

In more than 1 year that I use node-sass, I didn't know it was supposed to work without manual building. How can I understand why it's not downloading the prebuilt?
