### ISSUE TITLE
@import fails in node-sass 0.2.4

### ISSUE THREAD

**Issue by William-Owen** [sass/node-sass#27]
When attempting to use a simple @import I get the following error message: -

```
ERROR -- , line 1: error reading file "variables"
```

My app config: -

``` javascript

app.configure(function(){

    app.set('views', __dirname + '/buildkit/views');
    app.set('view engine', 'jade');
    app.set('view options', {pretty: true});
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.locals.pretty = true;
    app.use(sass.middleware({
        "src" : __dirname + '/buildkit/assets/sass',
        "dest" : __dirname + '/buildkit/assets/',
        "debug" : true
    }));
    app.use(express.static(__dirname + '/buildkit/assets'));

});

```

My SASS 'screen.scss' (in the same directory as '_variables.scss': -

``` css
@import "variables";

body {
    background:red;
}
```

I have also tried importing  '_variables.scss'

Any thoughts / help welcome.

**Comment by parag** [comment]
Was having the same issue. It got fixed by changing
@import 'mixin'
to
@import 'mixin.scss.css'

Should not have fixed like this though.

**Comment by xzyfer** [comment]
Are you sure you're using 0.2.4? That's an incredible old and unsupported
version.

Please update to 3.1.
