### ISSUE TITLE
Node-Sass causing failed build

### ISSUE THREAD

**Issue by daningamells** [sass/node-sass#2706]
Daniels-MBP:Optisights danielingamells$ git push heroku master
Enumerating objects: 1214, done.
Counting objects: 100% (1213/1213), done.
Delta compression using up to 4 threads
Compressing objects: 100% (612/612), done.
Writing objects: 100% (835/835), 2.13 MiB | 170.00 KiB/s, done.
Total 835 (delta 522), reused 493 (delta 186)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  10.8.0
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 10.8.0...
remote:        Downloading and installing node 10.8.0...
remote:        Using default npm version: 6.2.0
remote:        
remote: -----> Restoring cache
remote:        - node_modules is checked into source control and cannot be cached
remote:        
remote: -----> Installing dependencies
remote:        Prebuild detected (node_modules already exists)
remote:        Rebuilding any native modules
remote:        
remote:        > node-sass@4.12.0 install /tmp/build_0c60f2e9c710bf8705e1d26d67547491/node_modules/node-sass
remote:        > node scripts/install.js
remote:        
remote:        internal/modules/cjs/loader.js:583
remote:            throw err;
remote:            ^
remote:        
remote:        Error: Cannot find module './definition_schema'
remote:            at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:507:25)
remote:            at Module.require (internal/modules/cjs/loader.js:637:17)
remote:            at require (internal/modules/cjs/helpers.js:20:18)
remote:            at Object.<anonymous> (/tmp/build_0c60f2e9c710bf8705e1d26d67547491/node_modules/ajv/lib/keyword.js:5:24)
remote:            at Module._compile (internal/modules/cjs/loader.js:689:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
remote:            at Module.load (internal/modules/cjs/loader.js:599:32)
remote:            at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:530:3)
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the node-sass@4.12.0 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.cj0EU/_logs/2019-07-08T23_51_39_497Z-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - node_modules checked into source control
remote:          https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits
remote:        
remote:        - A module may be missing from 'dependencies' in package.json
remote:          https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to optisights-staging.
remote: 
To https://git.heroku.com/optisights-staging.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/optisights-staging.git'

Hey all any ideas?

**Comment by nschonni** [comment]
> remote: - node_modules checked into source control
> remote: https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits

Seems related, but we can't really troubleshoot a Heroku issue for you

**Comment by daningamells** [comment]
Dude you just answered my question, sorry for the stupid question. Much love x
