### ISSUE TITLE
node-sass using node-gyp v3.8.0 when v5.0.3 is out is there a reason?

### ISSUE THREAD

**Issue by jasonwilliams** [sass/node-sass#2716]
as title.

node-sass seems to be using an old version of node-gyp (which then pulls in old dependencies), but looks like node-gyp is now on v5.0.3.

Can node-sass bump to this version?

https://github.com/sass/node-sass/blob/master/package.json#L67

**Comment by xzyfer** [comment]
4.0.0 breaks support for old node.

**Comment by jeffrson** [comment]
Well, newer node-gyp can use Python3 - which is important when Python2 will be end-of-life at the end of 2019. So you definitely should move on.

**Comment by omarlara** [comment]
@xzyfer any plan to upgrade node-gyp 6.0.0?  Python2 will be losing support at the end of 2019.

**Comment by jkim7** [comment]
Yes I'd also like this upgraded, it introduces a file cb-never-called-1.0.1.tgz which throws a malware warning on my antiviruse

**Comment by mitchellmebane** [comment]
@xzyfer node-gyp@6.0.1 requires Node >= 6.0.0.  Node 4.x has been EOL since April 2018, and Node 5.x has been EOL since June 2018.  If you're concerned about strictly following semver, could you please consider cutting a 5.x release with just a node-gyp bump?  The Python 2 dependency is going to start being a very big pain point for many users in the coming months.

**Comment by LC43** [comment]
can this be reconsidered?

there's two vulnerabilities related to old version. Latest node-gyp@6.0.1 uses tar@4.4.12 which clears :
- https://www.npmjs.com/advisories/803
- https://www.npmjs.com/advisories/886

**Comment by qnighy** [comment]
What is blocking this from happening other than compatibility things, which can be addressed by what @mitchellmebane said?

**Comment by boggsey** [comment]
Python 2 is now EOL and the latest versions of node-gyp now support Python 3. Would love to see node-sass bump this up.

**Comment by kpcyrd** [comment]
Any news here? We're going to drop python2 from Arch Linux in the foreseeable future.

**Comment by LC43** [comment]
@xzyfer , should we open a new ticket to review this update?

**Comment by KingOfCramers** [comment]
I believe the old node-gyp version is breaking installs, for example I've run a clean docker install and this is causing failures, see [this](https://github.com/sass/node-sass/issues/2822) thread

**Comment by xzyfer** [comment]
5.0 has been released with latest node-gyp

**Comment by saper** [comment]
> I believe the old node-gyp version is breaking installs, for example I've run a clean docker install and this is causing failures, see [this](https://github.com/sass/node-sass/issues/2822) thread

What makes you think so?

**Comment by kpcyrd** [comment]
I didn't read the full log in the linked issue but there's:
```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
```
so it seems the base image that was used dropped the end-of-life python2 binary.
