### ISSUE TITLE
error node-sass@4.12.0 postinstall: `node scripts/build.js`

### ISSUE THREAD

**Issue by EdwardBatt** [sass/node-sass#2725]
I have tried reviewing similar issues that others have reported, however none of the proposed solutions are working. Although I am still learning, I have never had this much difficulty installing a module before, usually I am able to fix minor issues by reading all the forums, this time I could really use some help. 

debug log is attached, hoping some generous soul can assist. 

[2019-08-30T10_18_00_419Z-debug.log](https://github.com/sass/node-sass/files/3559504/2019-08-30T10_18_00_419Z-debug.log)

**Comment by EdwardBatt** [comment]
For anyone that sees this post, issue was resolved by changing ownership of root folder, and then reinstalling without using sudo.

**Comment by TechnoSayge** [comment]
@EdwardBatt that didn't explain what was done.  I didn't use sudo to begin and what do you mean by changing ownership of root folder? Thanks
