### ISSUE TITLE
Determine what Node Sass Binding to download?

### ISSUE THREAD

**Issue by kolomu** [sass/node-sass#2728]
Hello I am behind a corporate proxy and now need to manually download node-sass to install it.

How do I determine what binding I need?

My node-sass version is 4.11.0 and I use windows 10 64bit.

When I click on releases there are many to choose from but which is the correct one?

I know it have to start with win32-x64-??_binding.pdb

?? What number do I have to choose from here.

Best regards

**Comment by nschonni** [comment]
This table lists all the Module Versions https://nodejs.org/en/download/releases/
