### ISSUE TITLE
node-sass not supported on Mac 10.14.6 (after upgrade)

### ISSUE THREAD

**Issue by krishsur** [sass/node-sass#2731]
- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

I am getting node-sass not supported error after upgrading to Mac to new version today, the Mac version that I upgraded to 10.14.6. Here are the other details about my Mac system

- NPM version (`npm -v`): 6.11.3
- Node version (`node -v`): v12.10.0
- Node Process (`node -p process.versions`):
{
  node: '12.10.0',
  v8: '7.6.303.29-node.16',
  uv: '1.31.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '4',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1c',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): node-sass@4.12.0

**Comment by nschonni** [comment]
Delete your node_modules and re-install
