### ISSUE TITLE
Intermittent error installing node-saas on ppc64le 

### ISSUE THREAD

**Issue by rashmi-ibm** [sass/node-sass#2741]
Facing error installing node_modules on ppc64le.

System Info:
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# npm -v
6.10.3
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# node -v
v12.10.0
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# node -p process.versions
{
  node: '12.10.0',
  v8: '7.6.303.29-node.16',
  uv: '1.31.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '4',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1c',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# node -p process.platform
linux
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# node -p process.arch
ppc64
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# node -p "require('node-sass').info
>
> ^C
root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules# npm ls node-sass
trusted-connector-ui@0.1.0 /trusted-connector/ids-webconsole/src/main/resources/www
+-- @angular-devkit/build-angular@0.13.9
| `-- UNMET OPTIONAL DEPENDENCY node-sass@4.12.0
`-- spectacle-docs@1.0.7
  `-- node-sass@4.11.0

root@b5430f6b9bf2:/trusted-connector/ids-webconsole/src/main/resources/www/node_modules#

Error:-
> Task :ids-webconsole:yarnInstall
[4/4] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass
Output:
Building: /usr/local/bin/node /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.10.0 | linux | ppc64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c \"import sys; print \"2.7.13
gyp verb check python version .%s.%s\" % sys.version_info[:3];\"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.10.0
gyp verb command install [ '12.10.0' ]
gyp verb install input version string \"12.10.0\"
gyp verb install installing version: 12.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 12.10.0
gyp verb ensuring nodedir is created /root/.node-gyp/12.10.0
gyp http GET https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz

....
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`...
gyp verb checksum url https://nodejs.org/download/release/v12.10.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v12.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.10.0/SHASUMS256.txt
gyp verb checksum data {\"node-v12.10.0-aix-ppc64.tar.gz\":\"c5058a0fcbd0c9f8d49b64aa573ef151460f9de142a94479b2eda7d077d9de37\",\"node-v12.10.0-darwin-x64.tar.gz\":\"4c16d1f6454f5dc3977ad00cea123792b8d4e1d6d1bf42bbc82a4202039a5971\",\"node-v12.10.0-darwin-x64.tar.xz\":\"3edc050787453e20000047d892467065671f4a2ecf3acf6363bdd50f64009826\",\"node-v12.10.0-headers.tar.gz\":\"992bd91f5fadacb47a530b19b86c9dfd7fb0952e383595f971fc44047952d8e4\",\"node-v12.10.0-headers.tar.xz\":\"3a066f2341d7b6a80a0fbf46842765b51ba817ee26c3f3ba9d035c77afd12fd7\",\"node-v12.10.0-linux-arm64.tar.gz\":\"fd117a6ed22f493900fabdc7881fee50c7661c0eed88ae10c1139fa0d6c72535\",\"node-v12.10.0-linux-arm64.tar.xz\":\"fa1afb9e8cfd964867351b6dac6cd918784ff309291612251c4745aeb0b10e02\",\"node-v12.10.0-linux-armv7l.tar.gz\":\"79b2f3d4eeffdf67e175143e032a1e38d6757dce0f361c064a2034ba9bbd69af\",\"node-v12.10.0-linux-armv7l.tar.xz\":\"6bb777eaa0373c48059911272ea1b2d5cb567330e0474cedc8da42abc52fc346\",\"node-v12.10.0-linux-ppc64le.tar.gz\":\"5c4ca2b8b3150f6c56c6b2fc3cb7d316f1f0c3cb5650ff87922580f4c5230bd7\",\"node-v12.10.0-linux-ppc64le.tar.xz\":\"44892427765d8eb33cead16b81ebb13c75352868e2fa55f67324809e420882b1\",\"node-v12.10.0-linux-s390x.tar.gz\":\"dd0462f45231b0032c2cd6f26350e31cd1e26bba3a629d61cece6ff17c6ef32d\",\"node-v12.10.0-linux-s390x.tar.xz\":\"ecfb6fdd6ea8de7381261a2769bcb9539fb69a799d0fddccc0a0793b63d557e4\",\"node-v12.10.0-linux-x64.tar.gz\":\"3de23fd9f2145ff76d0583e7f57aa4ccead58b3fb991e215f862e779c9cdf151\",\"node-v12.10.0-linux-x64.tar.xz\":\"e8d2e6b62dd8183dc59a139a9ca3edc7c419a0d3d92e90fea9cb0ad52489843a\",\"node-v12.10.0-sunos-x64.tar.gz\":\"460db7890a8aa4171361d5e9e3fb57c4e8b2fb65cdb7c0c1d165fe06e228f4cb\",\"node-v12.10.0-sunos-x64.tar.xz\":\"3383dd4fc93d41b2294212904da4d9c6566de890e4f2513438bbf7cd575dfc10\",\"node-v12.10.0-win-x64.7z\":\"c1be70e47884fab24eb69fc0406f8206b135ae2f3e57f9acbb2f0b204c918f89\",\"node-v12.10.0-win-x64.zip\":\"de341476711c71f82d06fabcc9874c1ff9e865fd7274334d64a67b1e31a53fd0\",\"node-v12.10.0-win-x86.7z\":\"a60fc412a608894b264f2dadcd33ba6588287c04fc348f91a4223b59a6fbfa68\",\"node-v12.10.0-win-x86.zip\":\"16028bf616dfb49bcc42c1955f2d1eede0f0420df8289cbb34ee332f144f7a4b\",\"node-v12.10.0-x64.msi\":\"ac6b582ac63a6c761b7acf423817dd8d7d36060c04b7359a5e2361071ff970b5\",\"node-v12.10.0-x86.msi\":\"79463a43412e16cb0ef83f183705ac2f93bec84c11020b47f42d5391a2c1be51\",\"node-v12.10.0.pkg\":\"4fb0592a5e7987ae9443cdbc42398edc30db108f065e8152a9ab3079ba5c9cac\",\"node-v12.10.0.tar.gz\":\"371a3e39f1a14adbd7b37dee57641075ccfa240bd990630ff213298f16ad49b4\",\"node-v12.10.0.tar.xz\":\"2515b87c60921f22514a58830e86e54831daa2453d0e82f2ed7ab02134ee30cd\",\"win-x64/node.exe\":\"d2910dc57eb167a01714fd81ab039bad6cf99d39f7c84d16fdfa87af86b5de8d\",\"win-x64/node.lib\":\"f9aafbd5373fa9bab5291193afaa67facfb45d6c9ef3fd193b03130d3f3ee5eb\",\"win-x64/node_pdb.7z\":\"4c1281c598ed4426e2661fc881bf6778ac8938ac87ec66dc83f8f10e128c5a32\",\"win-x64/node_pdb.zip\":\"e43e5e73a401bd6b6547bab26f3b55ea03fee33c19204896bd5112697ddb3ebb\",\"win-x86/node.exe\":\"25ead049aa7b9ef0b4323dda6ef1994d52dfc2253c80247948f7dfc0299b5436\",\"win-x86/node.lib\":\"4dc68735e4262a426fd20535df6ca695f2928d4e92e5fe39468c7892dd44aeef\",\"win-x86/node_pdb.7z\":\"60e5664f8db09439054d54f8de419aeade5e7f5a1e7e9abb46e3ab663a40891c\",\"win-x86/node_pdb.zip\":\"7f77626abc1647d74769f7479d57d5d8816d688653d6c7aa241971a19fa1daad\"}
gyp verb download contents checksum {\"node-v12.10.0-headers.tar.gz\":\"992bd91f5fadacb47a530b19b86c9dfd7fb0952e383595f971fc44047952d8e4\"}
gyp verb validating download checksum for node-v12.10.0-headers.tar.gz (992bd91f5fadacb47a530b19b86c9dfd7fb0952e383595f971fc44047952d8e4 == 992bd91f5fadacb47a530b19b86c9dfd7fb0952e383595f971fc44047952d8e4)
gyp verb get node dir target node version installed: 12.10.0
gyp verb build dir attempting to create \"build\" dir: /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass/build
gyp verb build dir \"build\" dir needed to be created? /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing \"make\"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/12.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/12.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/12.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ppc64
gyp verb node dev dir /root/.node-gyp/12.10.0
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/which/which.js:80:29)
gyp ERR! stack     at /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/which/which.js:89:16
gyp ERR! stack     at /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:169:21)
gyp ERR! System Linux 4.15.0-58-generic
gyp ERR! command \"/usr/local/bin/node\" \"/trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd /trusted-connector/ids-webconsole/src/main/resources/www/node_modules/node-sass
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1"

**Comment by nschonni** [comment]
Sorry ppc64le isn't an architecture we test on, so we can't really help you.
