### ISSUE TITLE
My node-sass keeps reporting an earlier version when I try to run a script

### ISSUE THREAD

**Issue by DragonOsman** [sass/node-sass#2742]
- NPM version (`npm -v`): 6.11.3
- Node version (`node -v`): 12.10.0
- Node Process (`node -p process.versions`): 
```
{
  node: '12.10.0',
  v8: '7.6.303.29-node.16',
  uv: '1.31.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '4',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1c',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`): Win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
```
E:\programming\DragonOsman.github.io\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
    at module.exports (E:\programming\DragonOsman.github.io\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (E:\programming\DragonOsman.github.io\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)
```
But when I run `node-sass --version`, I see 
```
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.11.0.

I tried running the command to uninstall and reinstall node-sass, and I also updated and upgraded it.  I don't know why it's still version 4.11.0.  That's what I need help on.  Thanks.

**Comment by xzyfer** [comment]
You probably have multiple versions installed. Run npm la node-sass to
confirm.

**Comment by DragonOsman** [comment]
I only had one.  It's updated now, but there are issues with running the `npm audit fix` command when it says to do so.  
```
up to date in 7.891s
fixed 0 of 99 vulnerabilities in 23752 scanned packages
  99 vulnerabilities required manual review and could not be updated
```
How do I do this?

**Comment by nschonni** [comment]
Sorry, that's not an issue with node-sass, StackOverlow would be a better place to look for general NPM support

**Comment by DragonOsman** [comment]
I deleted the `node-modules` folder and both the `package.json` and `package-lock.json` files, and then installed `node-sass` again.  Now I have no vulnerabilities and the version is also the latest.  I couldn't find a better way to do this.
