### ISSUE TITLE
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

### ISSUE THREAD

**Issue by thaniyarasu** [sass/node-sass#2743]
OS: ubuntu 18.04
node: 12.10
npm: 6.11.3
ng: 6.2.4

Error: 
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Missing binding ./node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.

**Comment by nschonni** [comment]
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass` to download the binding for your current environment.

**Comment by jsousa1919** [comment]
Unless you can come up with a better answer than vomiting what's shown in the error message @nschonni that doesn't help anyone.  You can rebuild node-sass however much you want with the newest node versions but at the moment sass will only build if I use (with nvm) node@10.16.3

**Comment by dmt0** [comment]
I'm getting this error in CI, where packages are pulled and node-sass is rebuilt each time.

**Comment by kristian-mypos** [comment]
I got similar problem

Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 12.x

And I am running 12.14.0

**Comment by ThomasConnolly** [comment]
Sad to say, but the "disruptive content" comment above is what helped me after days of struggling. I changed to node 10x and finally could deploy to heroku. While the comment may have seemed somewhat negative, it is useful for some. This is a hard enough business without adding to the chaos, right? Thanks everyone! (Also this topic, in my opinion, should not be closed, as it is still a vexing issue.

**Comment by saper** [comment]
@ThomasConnolly can you suggest us some changed to the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) file to let people know? The binding file has to match the currently running node version. There is no way around that.

(You can edit the file directly on github then save proposed changes and submit a pull request).
