### ISSUE TITLE
The Error of Rebuilding binaries 

### ISSUE THREAD

**Issue by cuidaowang** [sass/node-sass#2744]
I am going to install node-sass on an ARM-based computer with a Linux operating system, but I can't find this version, so I followed the instructions to rebuild it. There was an error in the process. I have spent a day solving this problem, but it still has not been solved. I am grateful if I can get help. The rebuild steps and errors are as follows:
1)git clone --recursive https://github.com/sass/node-sass.git
2)cd node-sass
3)npm install
4)node scripts/build -f
![error](https://user-images.githubusercontent.com/55750041/65517552-7dd61480-df15-11e9-87dc-b76fcc07cd51.PNG)

**Comment by derdiggn** [comment]
Error: getaddressinfo means you have network or connectivity issues pls check your internet, network and/or proxy settings

**Comment by cuidaowang** [comment]
@derdiggn 
Thank you very much for your answer, yes, my computer does not have a network. I want to know if rebuilding node-sass requires a network. No network can't be finished?

**Comment by ip1981** [comment]
I think you need to point npm where your node.js headers are. Otherwise it will try to fetch them from the internets. Something like this:

```
npm run build --nodedir=/usr
```

**Comment by nschonni** [comment]
ARM isn't a supported architecture. You can see the patches that would be required in #2647, but as @ip1981 mentioned, https://github.com/nodejs/node-gyp will require the Node headers locally if they can't be downloaded as part of the build
