### ISSUE TITLE
How to use new sass features ex: @use ? 

### ISSUE THREAD

**Issue by samayo** [sass/node-sass#2750]
Sorry for the newbie question. but I have been learning about sass recently and found out about the new Built-in Modules system: https://sass-lang.com/documentation/modules 

From my understanding lib-sass is the main interpreter and node-sass, dart-sass, ruby-sass are wrappers around it? and ruby-sass is no longer maintained, while node-sass hasn't implemented the new features yet (as of 4.12.0) ..

So, is the only way to use the new features like: `@use` or `math:sass` to use dart-sass via npm?

**Comment by xzyfer** [comment]
This isnt supported in node-sass yet. You can use the sass module in the mean time.

**Comment by samayo** [comment]
@xzfer which sass module? dart-sass?

**Comment by xzyfer** [comment]
npm install sass
