### ISSUE TITLE
Node Module Tar is outdated

### ISSUE THREAD

**Issue by jkim7** [sass/node-sass#2751]
Hi, 

There is a version of Tar in this project that contains a file called cb-never-called-1.0.1.tgz which is throwing a malware warning in our virus scan.

Can anyone upgrade Tar to the latest version to resolve this?

thanks

**Comment by nschonni** [comment]
Answered a few times like https://github.com/sass/node-sass/issues/2734#issuecomment-531189301

**Comment by jkim7** [comment]
I looked into this further and it looks like node-gyp needs to be updated from 3.8 to at least 4.0
