### ISSUE TITLE
Problem compiling on nw-gyp 

### ISSUE THREAD

**Issue by mjschutz** [sass/node-sass#2759]
Hello.

When I try to compile on nw-gyp (version is on output bellow) with:

nw-gyp rebuild --target=0.41.3 --runtime=x64

I get a error with the /RELEASE parameter on the link command (not supported on lld-link of nw-gyp), if I manually link with /DEBUG and create the vendor/win32-x64-72 (script thinks that NW.js is Node 12) it works.

  lld-link : error : could not open /RELEASE: no such file or directory [F:\Projetos\ArtSis\node_modules\node-sass\bui
ld\binding.vcxproj]

    0 Aviso(s)
    1 Erro(s)

Tempo Decorrido 00:00:00.74
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mauro\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mauro\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--verbose"
gyp ERR! cwd F:\Projetos\ArtSis\node_modules\node-sass
gyp ERR! node -v v10.16.3
gyp ERR! nw-gyp -v v3.6.5
gyp ERR! not ok

**Comment by nschonni** [comment]
Sorry we don't support building on nw-gyp. If you resolve you issue feel free to comment here though, in case someone else runs into the same issue

**Comment by saper** [comment]
@mjschutz  I am pretty sure you have edited something incorrectly... First, what is an error you are getting with `/RELEASE` ? Obviously your "manual link" could not work at all. Please provide detailed error messages.

**Comment by saper** [comment]
Thank you @mjschutz - I think this is something that should be reported to the https://github.com/nwjs/nw-gyp

**Comment by gpetrov** [comment]
did you got any further @mjschutz ?

I would also like to compile node-sass for NWJS, but are getting this weird error.

It's a shame @nschonni that you are limiting the support to only known platforms, while with just a switch you can compile for NWJS as well

**Comment by gpetrov** [comment]
After further investigation it seems you need to change the setting **SetChecksum** to **false** at:

https://github.com/sass/node-sass/blob/master/binding.gyp#L27

and then run:
```
nw-gyp configure --target=0.44.5 --runtime=x64
```

from the **node_modules/node-sass** folder

It will all compile then just fine.

final step is to copy the release file:
```
copy .\build\Release\binding.node .\vendor\win32-x64-79\
```
so that is the whole NWJS compilation working just fine.

Maybe you should consider supporting it our of the box @nschonni - it is just a simple conditional switch! Or maybe the setting is not needed at all ... anyway this is just a windows thing

**Comment by saper** [comment]
I think gyp should now it is using lld and not Microsoft linker and than it all works. Feel free to see if the updated gyp works better.

**Comment by gpetrov** [comment]
@saper the compilation works all fine - but the new lld does not understand the Microsoft's SetChecksum flag - so that is why it should be removed from binding.gyp as stated above
