### ISSUE TITLE
node-sass watch does not find @include myMixin()

### ISSUE THREAD

**Issue by wende60** [sass/node-sass#2762]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): 10.15
- Node Process (`node -p process.versions`): { 
  http_parser: '2.8.0',
  node: '10.15.0',
  v8: '6.8.275.32-node.45',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' 
}
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
  node-sass	4.12.0	(Wrapper)	[JavaScript]
  libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): node-sass@4.12.0

main.scss contains:
```
  @import './scss/mixins.scss';
  @import './scss/home.scss';
```

mixins.scss contains:
```
  @mixin biggerMobile() {
      @media (min-width: 650px) {
          @content;
      }
  }
```

home.scss contains something like
```
    .contentSliderContainer {
        width: 100%;
        @include biggerMobile() { 
            width: 80%;
        }  
    }
```

package.json contains scripts like:
```
    "cssDev": "node-sass --output-style compact ./src/home/css/main.scss ./src/home/css/main.css",
    "cssWatch": "node-sass --output-style compact --line-numbers --watch ./src/home/css/main.scss -o ./src/home/css/",
```

running **cssWatch** results in an output like that (using yarn, but npm is doing the same):
```
    => changed: /...../src/home/css/scss/home.scss
    => changed: /...../src/home/css/main.scss
    {
    "status": 1,
    "file": "/...../src/home/css/scss/home.scss",
    "line": 7,
    "column": 14,
    "message": "no mixin named biggerMobile",
    "formatted": "Error: no mixin named biggerMobile\n        on line 7 of src/home/css/scss/contentSlider.scss\n>>     @include biggerMobile() { \n\n   -------------^\n"
    }
    Rendering Complete, saving .css file...
    Wrote CSS to /...../src/home/css/main.css
```

However, the file is properly written, containing the mixin's condition!
If i run **cssDev** the main.css is written without any issues.

Any explanation for that behaviour?

**Comment by saper** [comment]
This is https://github.com/sass/node-sass/issues/2560 again. Everything works properly if only `main.scss` is touched. 

Workaround: use `_home.scss` and `_mixins.scss` as module names.

**Comment by wende60** [comment]
Ahh. I had to remember this: underscore prefix turns an imported sass-file into a partial, which should be done anyways for performance optimization. Thanks!
