### ISSUE TITLE
node 13 support

### ISSUE THREAD

**Issue by saper** [sass/node-sass#2765]
Node 13.0.0 is out. 

node-sass does not support node 13 yet.

- [x] Travis-CI support for 13
- [x] AppVeyor support for 13
- [x] Update known MODULE_VERSIONS. EX: #2764

**Comment by saper** [comment]
Good news - just build node 13 from source and it looks like we have no issues compiling our binding:

```
  rm -rf "Release/binding.node" && cp -af "Release/obj.target/binding.node" "Release/binding.node"
gmake: Leaving directory '/home/saper/node_modules/node-sass/build'
gyp info ok 
Installed to /home/saper/node_modules/node-sass/vendor/freebsd-x64-79/binding.node
```

**Comment by TimothyKZhu** [comment]
+1 to this report. NodeJS 13 just recently released and does not play well with node-sass.

**Comment by saper** [comment]
It does play well. https://github.com/sass/node-sass/pull/2766 is probably ready to go.

**Comment by justmedanny** [comment]
I hope that it does play well and the issue I'm having is only local to me. I'm on node 13.0.1 and I'm getting the error:

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

**Comment by saper** [comment]
@justmedanny This is what this bug is about. node-sass does not currently ship ready to use binaries for node 13.

**Comment by saper** [comment]
Please upgrade to node-sass 4.13.0 when using node 13. Thank you!

**Comment by mrpapercut** [comment]
Thank you for your work. Sadly, the one release I need is missing: `linux_musl-x64-79_binding.node` for version 4.13.0, which is the version needed in `node:alpine` Docker containers

**Comment by nschonni** [comment]
Yeah, looks like the Alpine bindings are missing

**Comment by saper** [comment]
How do we build them? Docker something something?

**Comment by saper** [comment]
Thanks, I think [I got it working](https://github.com/saper/node-sass-build-alpine-binaries/tree/updates-2019) ... Trying to build now

**Comment by saper** [comment]
@mrpapercut @ramiel node-sass binary for Alpine Linux running node 13 has been uploaded, please check

**Comment by nschonni** [comment]
Thanks @saper ! I keep meaning to at least add the Alpine build into the release build matrix, but haven't gotten to it.
Closing since the bindings should all be there again

**Comment by saper** [comment]
Thank you!

**Comment by y0y0z** [comment]
@saper \ @nschonni: thank you! works for me.
