### ISSUE TITLE
Cannot download 4.12.0 binary

### ISSUE THREAD

**Issue by aasili-shoprunner** [sass/node-sass#2770]
My build steps are failing because 4.12.0 binaries returns a 404:
https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node

- NPM version (`npm -v`): 6.9.0
- Node version (`node -v`): v12.2.0
- Node Process (`node -p process.versions`):
```
{
  node: '12.2.0',
  v8: '7.4.288.21-node.17',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.12.0

**Comment by nschonni** [comment]
The "79" in the download URL means you're using Node 13. You need to upgrade you node-sass or downgrade your NodeJS version
