### ISSUE TITLE
Disappearing downloads

### ISSUE THREAD

**Issue by arkwis** [sass/node-sass#2771]
Every once in a while I get an error when pushing my project to heroku that states
`Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-79_binding.node"`

Checking on github, that file does not exist at all, so my question would be, why is it even being looked for? It happens during the install of `node-sass@4.12.0`, running `node v8.16.0`.

**Comment by nschonni** [comment]
The 79 in the download URL means it's running Node 13 https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support
