### ISSUE TITLE
Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by jianghai** [sass/node-sass#2774]
Error: Missing binding /Users/nonrep/projects/rb/builder-lst-app/node_modules/_node-sass@4.13.0@node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x  Found bindings for the following environments:   - OS X 64-bit with Node.js 10.x

---------------------
My node version v10.16.2
My node_mudules node-sass@4.13.0 is vendor/darwin-x64-64/binding.node

---------------------
rebuild node-sass not work

------

rebuild result
```
> node-sass@4.13.0 install /Users/nonrep/projects/rb/builder-lst-app/node_modules/_node-sass@4.13.0@node-sass
> node scripts/install.js

node-sass build Binary found at /Users/nonrep/projects/rb/builder-lst-app/node_modules/_node-sass@4.13.0@node-sass/vendor/darwin-x64-64/binding.node

> node-sass@4.13.0 postinstall /Users/nonrep/projects/rb/builder-lst-app/node_modules/_node-sass@4.13.0@node-sass
> node scripts/build.js

Binary found at /Users/nonrep/projects/rb/builder-lst-app/node_modules/_node-sass@4.13.0@node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
node-sass@4.13.0 /Users/nonrep/projects/rb/builder-lst-app/node_modules/_node-sass@4.13.0@node-sass
```

**Comment by xzyfer** [comment]
npm rebuild node-sass

**Comment by saper** [comment]
Yes, it did work.
