### ISSUE TITLE
Syntax Error: C:\Users\***\AppData\Roaming\npm-cache\node-sass\4.9.2:1

### ISSUE THREAD

**Issue by MrDuCongcong** [sass/node-sass#2778]
Syntax Error: C:\Users\***\AppData\Roaming\npm-cache\node-sass\4.9.2:1
(function (exports, require, module, __filename, __dirname) { MZ�
                                                                ^

SyntaxError: Invalid or unexpected token

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-e01550a8","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0&bustCache!./src/components/datepicker.vue 4:14-389 13:3-17:5 14:22-397
 @ ./src/components/datepicker.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/multipage/departleader/pages/main.vue
 @ ./src/multipage/departleader/pages/main.vue
 @ ./src/multipage/departleader/pages lazy ^\.\/.*\.vue$
 @ ./src/multipage/departleader/router/_import.js
 @ ./src/multipage/departleader/router/index.js
 @ ./src/multipage/departleader/index.js

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.
