### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node"

### ISSUE THREAD

**Issue by gix111** [sass/node-sass#2779]
Hey, 

we´re using Microsoft Azure Dev Ops build pipeline with a npm plugin for our SASS files.
At the moment the **https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node" is not reachable.**

So we are not able to compile our files.

We also get a 404 to this link:
**https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node**

**Comment by YannDanthu** [comment]
same with https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node

**Comment by Castria** [comment]
Same issue for me

**Comment by mklosterboer** [comment]
Same issue. Started today. First build that failed was at 8:48 AM CST.
Let me know if I can provide any info to help investigate.

**Comment by nschonni** [comment]
This is answered in the issue template you ignored https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s

**Comment by mklosterboer** [comment]
@nschonni Excuse my ignorance, but this is running in a pipeline on Azure DevOps that has been unchanged for several months.
This has started failing repeatedly today for the first time.
An unsupported Environment seems and unlikely resolution to this issue. Especially with 4 people reporting the issue within an hour. 

Is there any other guidance you could offer or avenues we could research to determine what has changed that would cause 4 unrelated projects to begin failing builds within hours of each other?

**Comment by mklosterboer** [comment]
For anyone who is still having this issue, Node recently moved 12.x to LTS, and it seems like Azure DevOps is now using Node 12.x instead of Node 10.x for builds when the node version isn't specified. 

To resolve the issue, I added a [Node.js Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) task build step to our build pipeline to specify which version of Node to use for Node commands.

**Comment by nschonni** [comment]
@mklosterboer thanks for sharing your solution 👍

**Comment by donruperto** [comment]
@mklosterboer thx for your solution, worked for me as well

**Comment by ohdihe** [comment]
@mklosterboer 
Thanks! your suggestion worked

**Comment by bcbuddy** [comment]
@mklosterboer 
THANK YOU.

**Comment by zuo305** [comment]
Yes. I update the node-sass to v.4.13, it is working fine on my local and Azure Dev-ops too. Only one thing is stranger, after build "node-sass\vendor\win32-x64-72\binding.node" success. It still shows "Cannot download "xxx/node-sass/v4.13.0/win32-x64-72_binding.node", it does not make sense.

**Comment by j6967chen** [comment]
@mklosterboer The solution works. Thanks
