### ISSUE TITLE
[Unsupported] Installing node-sass 3.13.1 with Node 8

### ISSUE THREAD

**Issue by sankaryg** [sass/node-sass#2784]
03:31:13 + node -v
03:31:13 v8.16.2
03:31:13 + npm -v
03:31:13 6.4.1
Always failing when i run ionic app in jenkins server
03:35:21 + npm i
03:35:38 npm WARN deprecated angular-cli@1.0.0-beta.22-1: angular-cli has been renamed to @angular/cli. Please update your dependencies.
03:35:39 npm WARN deprecated cordova-sqlcipher-adapter@0.3.0: Possible security and integrity issues resolved in version 0.4.0
03:35:43 npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
03:35:46 npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
03:35:46 npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
03:35:46 npm WARN deprecated exists-sync@0.0.4: Please replace with usage of fs.existsSync
03:35:47 npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
03:35:48 npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
03:35:48 npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
03:35:52 npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
03:36:01 npm WARN deprecated exists-sync@0.0.3: Please replace with usage of fs.existsSync
03:36:04 npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
03:36:10 npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
03:36:10 npm WARN deprecated   npm i nyc
03:36:10 npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
03:36:12 npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
03:36:12 npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
03:36:12 npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
03:36:12 npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
03:36:12 npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
03:36:13 npm WARN deprecated istanbul@0.4.3: This module is no longer maintained, try this instead:
03:36:13 npm WARN deprecated   npm i nyc
03:36:13 npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
03:36:13 npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
03:36:14 npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
03:36:29 
03:36:29 > node-sass@3.13.1 install /Users/iosapp_test1/jenkins/workspace/ProcurementAppFinalQABuild-IOS/node_modules/angular-cli/node_modules/node-sass
03:36:29 > node scripts/install.js
03:36:29 
03:36:31 npm WARN @ionic-native-mocks/file@2.0.12 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native-mocks/sqlite@2.0.12 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/core@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/camera@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/app-version@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/app-preferences@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/device@4.20.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/email-composer@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/file@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/file-chooser@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/file-opener@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/file-path@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/file-transfer@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/file-picker@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/fingerprint-aio@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/http@4.20.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/is-debug@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/keyboard@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/in-app-browser@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/native-page-transitions@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/network@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/secure-storage@4.20.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/splash-screen@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/sqlite@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/user-agent@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic-native/status-bar@4.19.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic/angular@4.8.0 requires a peer of @angular-devkit/core@7.2.1 - 8 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic/angular@4.8.0 requires a peer of @angular-devkit/schematics@7.2.1 - 8 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic/angular@4.8.0 requires a peer of @angular/router@7.2.1 - 8 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @ionic/angular@4.8.0 requires a peer of rxjs@>=6.2.0 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN fundamental-ngx@0.8.0 requires a peer of rxjs@^6.4.0 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN sass-loader@3.2.3 requires a peer of node-sass@^3.4.2 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN @angular/tsc-wrapped@0.5.2 requires a peer of typescript@^2.0.2 but none is installed. You must install peer dependencies yourself.
03:36:31 npm WARN tsickle@0.2.6 requires a peer of typescript@^2.0.0 but none is installed. You must install peer dependencies yourself.
03:36:31 
03:36:31 npm ERR! file sh
03:36:31 npm ERR! path sh
03:36:31 npm ERR! code ELIFECYCLE
03:36:31 npm ERR! errno ENOENT
03:36:31 npm ERR! syscall spawn sh
03:36:31 npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
03:36:31 npm ERR! spawn sh ENOENT
03:36:31 npm ERR! 
03:36:31 npm ERR! Failed at the node-sass@3.13.1 install script.

**Comment by nschonni** [comment]
Node-sass 3.13.1 is too old to run on Node 8, upgrade your node-sass or downgrade Node if you need to use that version
