### ISSUE TITLE
node-sass@4.11.0 404 darwin-x64-72_binding.node

### ISSUE THREAD

**Issue by esaruoho** [sass/node-sass#2788]
Hi, I'm trying to download the `releases/download/v4.11.0/darwin-x64-72_binding.node` and am getting a 404. 

Can this be reintroduced into the repository release folder?

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node": 

HTTP error 404 Not Found
```

**Comment by saper** [comment]
Please upgrade node sass (currently at 4.13.0). https://github.com/sass/node-sass/releases/tag/v4.11.0 supported versions of node up to 11 and you seem to be running 12.

**Comment by esaruoho** [comment]
Thanks, good to know that 4.11.0 is for Node v11 only and that for Node v12 support, 4.13.0 is required.
