### ISSUE TITLE
Static content for proxy repositories

### ISSUE THREAD

**Issue by ochstobi** [sass/node-sass#2790]
Hello,

I wanted to know if it is possible (and useful) for other users (in enterprise environment) to create a static website for the binding.node files.

**Use case:** It is forbidden to directly download content from github.com. So node-sass fails because the binding.node files can't be downloaded. 
**Workaround:** Download and host every file on a private server. Set the SASS_BINARY_SITE environment variable to that server.
**Problem:** With every update builds are failing because new binding.node files are not in the private repo.
**Solution:** So the idea is to proxy it with e.g. an Nexus Proxy repository like it is possible with https://nodejs.org/dist

Best regards

**Comment by saper** [comment]
I leave this open for others to comment; I don't think it would be very difficult to setup something that checks Github Releases say once a day for a new release and download the binaries to the mirror.

**Comment by tuxknight** [comment]
May be it is nessary to package all things including binary to npm package. When we use npm as a package management system, we may want npm to deal all denpendences, including sass binary.

**Comment by saper** [comment]
@tuxknight [a list of all binaries](https://github.com/sass/node-sass/releases/tag/v4.13.0) is available for every release. Those are relatively large files and we constantly keep adding more as more platforms and node versions are supported. I think this is to much to put into one binary package.

**Comment by xzyfer** [comment]
>May be it is nessary to package all things including binary to on single npm package

This is not feasible as the resulting package would be well over 100mbs.

If you need a mirror we suggest you copy the binaries to a perferred server as part of your node-sass upgrade process. This is how many enterprise users work. We offer some environment variables to configure where the binaries are downloaded from during `npm install`. You can find these environment variables towards to end of the README.
