### ISSUE TITLE
node-sass has HIGH vuln as long as it relies on libsass <3.6

### ISSUE THREAD

**Issue by DonkeyAfterDark** [sass/node-sass#2791]
You might wanna update your code as no enterprise security team will allow a build to go to production with node-sass as long as it relies on libsass 3.54.

**Comment by RaitNao** [comment]
Bump. Are there any updates on upgrading to 3.6? Since #2685 has been closed. Whitesource reports same vulnerabilities as that issue does 
![image](https://user-images.githubusercontent.com/17132358/69556728-47e3f980-0f73-11ea-9a33-751fc9efd172.png)

**Comment by nschonni** [comment]
Closing as duplicate of #2685 which isn't closed
