### ISSUE TITLE
4 new vulnerabilities detected by Snyk

### ISSUE THREAD

**Issue by andymsuk** [sass/node-sass#2795]
The following CVEs have been made public by Snyk:
https://snyk.io/vuln/SNYK-JS-NODESASS-535497
https://snyk.io/vuln/SNYK-JS-NODESASS-535498
https://snyk.io/vuln/SNYK-JS-NODESASS-535500
https://snyk.io/vuln/SNYK-JS-NODESASS-535502

**Comment by nschonni** [comment]
Follow #2685 for when libsass will be updated
