### ISSUE TITLE
@import from node_modules does not allow omitting file extension

### ISSUE THREAD

**Issue by teetotum** [sass/node-sass#2796]
- NPM version (`npm -v`): 6.9.0
- Node version (`node -v`): v10.15.3
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.13.0
- npm node-sass versions (`npm ls node-sass`):-- (empty)

# What I try to do
I generate a single CSS output file from various SCSS partials, including a well established third-party sanitize lib.

# what is my setup?
In my package.json I have "sanitize.css": "^8.0.0" in the devDependencies (because it is only needed during compile time, not during runtime)
As expected we will find the file in node_modules/sanitize.css/sanitize.css
According to the documentation (https://sass-lang.com/documentation/at-rules/import#importing-css) I should be able to import it from the css file (and have it inlined in the final output file) as if it were just any SCSS partial by omitting the file extension.
like so:
@import "~sanitize.css/sanitize";

But this results in an error:
{
  "status": 1,
  "file": "C:/workspace/<path_to_my_main_style.scss>",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: ~sanitize.css/sanitize.",
  "formatted": "Error: File to import not found or unreadable: ~sanitize.css/sanitize.\n        on line 1 of src/main/path_to_my_main_style.scss\n>> @import \"~sanitize.css/sanitize\"; \n\n   ^\n"
}

When I change the import to also include the file extension:
@import "~sanitize.css/sanitize.css";
...it is treated like a plain CSS @import
as described in the documentation (https://sass-lang.com/documentation/at-rules/import#plain-css-imports)

**Comment by xzyfer** [comment]
~ in import os a sass-loader feature. Please open an issue with that
package.

**Comment by teetotum** [comment]
I'm not using sass-loader, only node-sass directly from the command line interface.
So, node-sass must have some mechanism of its own to resolve imports with an ~

**Comment by xzyfer** [comment]
It does not. However ~ is often an aliases the hike directory. That may be why the file is not found.

**Comment by teetotum** [comment]
Sorry I have no idea what that is. I would be forever grateful if you could point me in the right direction.

**Comment by nschonni** [comment]
The option if you are just using node-sass and not though a separate build tool is the includePaths https://github.com/sass/node-sass#includepaths

**Comment by teetotum** [comment]
@nschonni Thanks. I got it working using the option you proposed.
Now an import from the node_modules like:
`@import "sanitize.css/sanitize";`
is inlined as expected into the output file.
I run node-sass like so:
`node-sass --include-path node_modules <input_directory> -o <output_directory>`
