### ISSUE TITLE
Removing Post-Install script

### ISSUE THREAD

**Issue by bosstweed11** [sass/node-sass#2798]
Please consider removing the post-install test runner and notify the user to run the tests as a warning in the console, with the main goal of allowing users to set `npm config set ignore-scripts true`

Check out https://youtu.be/24tQRwIRP_w?t=930, this is my reason for posting.

Thanks!

**Comment by xzyfer** [comment]
We will not. Feel free to ignore scripts and manually build the binary of you wish.
