### ISSUE TITLE
angular-devkit requires older version of node-sass

### ISSUE THREAD

**Issue by omaracrystal** [sass/node-sass#2799]
- NPM version (`npm -v`): 
`6.13.1`
- Node version (`node -v`): 
`13.3.0`
- Node Process (`node -p process.versions`): 
```
{
  node: '13.3.0',
  v8: '7.9.317.25-node.23',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '79',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.1',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`): 
`darwin`
- Node architecture (`node -p process.arch`): 
`x64`
- node-sass version (`node -p "require('node-sass').info"`): 
```
node-sass	4.13.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): 
```
enterprise@1.4.0 /Users/rush/enterprise
├─┬ @angular-devkit/build-angular@0.13.7
│ └── UNMET OPTIONAL DEPENDENCY node-sass@4.11.0
├─┬ @nrwl/builders@7.7.2
│ └─┬ @angular-devkit/build-angular@0.13.9
│   └── node-sass@4.12.0 
├─┬ ng-packagr@4.7.1
│ └── node-sass@4.13.0  deduped
└── node-sass@4.13.0 
```

Having an issue with node-sass after upgrading node v13.3.0. Read through similar issues and upgraded node-sass to v4.13.0 did not fix the issue for me. 

Saw in issue #2632 
That there could be an issue with line 17 in create_string.cpp
It shows  ` v8::String::Utf8Value string(value);`
After npm install I see in the node-modules folder that this same line is compiled to  `Nan::Utf8String string(value);`

The error within terminal:
```
/src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
```
I have tried completely detleting npm, nvm, node, and yarn, clearing cach and reinstalled them.  However, having the same issue. 

I am using macOS High Sierra version 10.13.6
I have Xcode V10.1 installed

**Comment by xzyfer** [comment]
You have two versions of node-sass installed. Only 4.13.0 will work with
node 13.

**Comment by saper** [comment]
This is the same as https://github.com/sass/node-sass/issues/2794

**Comment by em1208** [comment]
I had the same issue on a old angular project running node v12.22.12 and the solution was to upgrade to "@angular-devkit/build-angular": "0.13.10".
