### ISSUE TITLE
_sass_make_boolean symbol not found

### ISSUE THREAD

**Issue by dodgertodd** [sass/node-sass#2800]
- NPM version (`npm -v`): 6.12.0
- Node version (`node -v`): 10.13.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.8.0',
  node: '10.13.0',
  v8: '6.8.275.32-node.36',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): This is the problem -- that script won't run!
- npm node-sass versions (`npm ls node-sass`): node-sass@4.12.0

I can get node-sass to successfully install (I have it as a dependency of hexo-renderer-sass, but have also tried a direct install), and while I get a successful install, the build fails to run. I get the following error:

> dyld: lazy symbol binding failed: Symbol not found: _sass_make_boolean
>   Referenced from: /Users/twils18/dev/one-amex-docs/node_modules/node-sass/vendor/darwin-x64-64/binding.node
>   Expected in: flat namespace
> 
> dyld: Symbol not found: _sass_make_boolean
>   Referenced from: /Users/twils18/dev/one-amex-docs/node_modules/node-sass/vendor/darwin-x64-64/binding.node
>   Expected in: flat namespace
> 
> Abort trap: 6

What's frustrating is that on clean pulls of this app on others' machines, **they don't have any problems.** So there's obviously some kind of machine/environment configuration that is required that we can't deduce from instructions or error messages.

I downloaded the darwin-x64-64 build from https://github.com/sass/node-sass/releases/tag/v4.12.0 and then ran `node -p "require('node-sass').info"` again and I get this, which seems to contradict itself...:

```
/Users/myProject/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /Users/myProject/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 10.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/Users/myProject/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/myProject/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
```

Some other environment info:
Python version 3.7.5
Python 2.7.17 also installed (and referenced in the build output)
MacOS 10.14.6
Xcode 11.2.1, Build version 11B500
GNU Make 3.81
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0

**Comment by dodgertodd** [comment]
I know about https://github.com/sass/node-sass/issues/278, but that's an ancient issue and doesn't address the gap I have now, which is that my node and node-sass versions should be compatible but aren't, they work together on others' machines! So some other version / dependency / env config requirement is getting in the way and I'm looking for guidance on what that might be.

**Comment by nschonni** [comment]
Also old, but I'd try out some of this stuff https://stackoverflow.com/questions/15678546/git-dyld-lazy-symbol-binding-failed-symbol-not-found-iconv-open#23785476
I had problems with recent XCode updates as well that messed up general brew/build things till it was able to get past it

**Comment by saper** [comment]
@dodgertodd can you try one of the solutions from https://stackoverflow.com/questions/4506121/how-to-print-a-list-of-symbols-exported-from-a-dynamic-library (nm, objdump, otool) to list the dynamic symbols exported by the `binding.node` file?

**Comment by mrflip** [comment]
I hit this (OSX) and solved it without really knowing how. I first hit an error because I did not have libsass installed, so I did `brew install libsass`. I then re-did the npm install and hit this. I wiped out my existing `node_modules/node-sass`, and changed the package.json to specify `4.13.0`. Re-ran `npm install node-sass`, and all worked.

**Comment by saper** [comment]
@mrflip interesting: libsass shouldn't be necessary at all.

I'll close this unless someone comes out with some more information regarding Xcode differences or symbols provided in the `binding.node`. Feel free to reopen in this case.

**Comment by jokey2k** [comment]
Attaching requested output as I also just hit this issue...
[binding.node.nm-output.txt](https://github.com/sass/node-sass/files/4789118/binding.node.nm-output.txt)

**Comment by jokey2k** [comment]
Additional note: re-installing node-sass seems to fix the issue as it uses its own target path as part of linking. Hence when the lib is available in the target path, it works just fine.

I'm not an expert regarding build scripts in npm context, so I cannot provide a sane fix. But for autotools(configure) and others there are hints on the net regarding this issue and how to fix them

**Comment by saper** [comment]
I could not understand the following:

> Additional note: re-installing node-sass seems to fix the issue as it uses its own target path as part of linking. Hence when the lib is available in the target path, it works just fine.

Can you explain?

**Comment by Anthea-L** [comment]
Hello! I'm facing a similar problem, reinstalling could not solve this problem. Is there any conclusion to solve this problem? Such as using another version for one of the packages?
here is my result for running the codes:

```
sh-3.2# node -p process.platform
darwin
sh-3.2# node -p process.arch
x64
sh-3.2# node -p "require('node-sass').info"
node-sass	5.0.0	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
sh-3.2# npm ls node-sass
hexo-site@0.0.0 /Users/anthea/blog
├─┬ hexo-renderer-sass@0.4.0
│ └── node-sass@4.14.1
└── node-sass@5.0.0

sh-3.2# npm -v
7.0.3
sh-3.2# node -v
v15.0.1
sh-3.2# node -p process.versions
{
  node: '15.0.1',
  v8: '8.6.395.17-node.15',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}

```
I met this problem when trying to run `hexo clean` for my blog, or simply when rebuilding the node-sass module

```
sh-3.2# npm rebuild node-sass
npm ERR! path /Users/anthea/blog/node_modules/hexo-renderer-sass/node_modules/node-sass
npm ERR! command failed
npm ERR! signal SIGABRT
npm ERR! command sh -c node scripts/build.js
npm ERR! Binary found at /Users/anthea/blog/node_modules/hexo-renderer-sass/node_modules/node-sass/vendor/darwin-x64-88/binding.node
npm ERR! Testing binary
npm ERR! dyld: lazy symbol binding failed: Symbol not found: _sass_make_boolean
npm ERR!   Referenced from: /Users/anthea/blog/node_modules/hexo-renderer-sass/node_modules/node-sass/vendor/darwin-x64-88/binding.node
npm ERR!   Expected in: flat namespace
npm ERR! 
npm ERR! dyld: Symbol not found: _sass_make_boolean
npm ERR!   Referenced from: /Users/anthea/blog/node_modules/hexo-renderer-sass/node_modules/node-sass/vendor/darwin-x64-88/binding.node
npm ERR!   Expected in: flat namespace
```
or is it because the brew install of libsass put the libsass under a different path? `/usr/local/Cellar/libsass/3.6.4`
