### ISSUE TITLE
CSS file is not overwritten, instead changes are appended

### ISSUE THREAD

**Issue by paddelboot** [sass/node-sass#2804]
node `v12.13.1`
npm `6.12.1`
node-sass `4.13.0`
libsass `3.5.4`

node -p process.versions
    
`{
  node: '12.13.1',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}`

node -p process.platform

`linux`

node -p process.arch

`x64`

I am using `node-sass --watch file.scss > file.css` on the command line, but any changes are *appended* to the output file, instead of overwriting it:

    => changed: /media/xyz/file.scss

    [changes here..]

     => changed: /media/xyz/file.scss

    [changes here..]

Nor sure where to look for in the documentation. Any clues?

**Comment by paddelboot** [comment]
I tried it in a different way:

`node-sass -w -r scss/force-app/ -o ../dfind/force-app/`

Seems to work for now.

**Comment by nschonni** [comment]
If you're using the redirect operator https://quickleft.com/blog/command-line-tutorials-redirection-pipes/ and it's not working, that is a system level issue unrelated to node-sass
