### ISSUE TITLE
node-sass not found

### ISSUE THREAD

**Issue by iburrows** [sass/node-sass#2806]
Hi, 

I know this has been asked before but using linux here and on a bamboo agent. `npm install` works if I run it on a local ubuntu setup but trying to run it as part of a build I receive the following:

09-Dec-2019 17:52:02 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node
09-Dec-2019 17:52:03 Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node":
09-Dec-2019 17:52:03 HTTP error 404 Not Found

I have had a look at the github project and no binary linux-x64-72_binding.node exists for v4.9.4 Only for v4.13.0. On my local Ubuntu installation the binary https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-57_binding.node is downloaded and exists.

What determines which binary is being downloaded from a release?

Thanks for the assistance.

**Comment by nschonni** [comment]
Your server is running an older version of Node that is incompatible with Node 13 https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s
