### ISSUE TITLE
Crash installing on node 13.2

### ISSUE THREAD

**Issue by ghazal** [sass/node-sass#2807]
node --version
v13.2.0
 npm --version
6.13.1

macOS Catalina

Error message:
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/darwin-x64-79_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Applications/mampstack-7.3.10-0/apache2/htdocs/j4-CLI/joomla-cms/node_modules/node-sass/vendor/darwin-x64-79/binding.node
Caching binary to /Users/xxx/.npm/node-sass/4.13.0/darwin-x64-79_binding.node
node[1686]: ../src/signal_wrap.cc:159:void node::DecreaseSignalHandlerCount(int): Assertion `(new_handler_count) >= (0)' failed.
 1: 0x100b8ff9a node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000832c4 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10008307c node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/bin/node]
 4: 0x1000f7e52 node::HasSignalJSHandler(int) [/usr/local/bin/node]
 5: 0x1000f85ad node::(anonymous namespace)::SignalWrap::Close(v8::Local<v8::Value>) [/usr/local/bin/node]
 6: 0x10003eb76 node::Environment::CleanupHandles() [/usr/local/bin/node]
 7: 0x10003ed2f node::Environment::RunCleanup() [/usr/local/bin/node]
 8: 0x1000b4a3a node::NodeMainInstance::Run() [/usr/local/bin/node]
 9: 0x100060f13 node::Start(int, char**) [/usr/local/bin/node]
10: 0x7fff6e49c405 start [/usr/lib/system/libdyld.dylib]
11: 0x2
zsh: abort      npm ci
```
As you can see, I come from the joomla 4 world.
I modified package.lock.json to set it on par with version 4.13, as the original is behind (on 4.12), sha512 included.
Error message quite similar to #2805

**Comment by ghazal** [comment]
@xzyfer 
You say in #2805:

> It's possible the Darwin binaries built on Mojave aren't compatibile with Catalina

OK.
Then, I  guess it's useless to regress to former versions of node and node-sass ?
Can we expect that the binary will be updated for macOS Catalina ?

**Comment by xzyfer** [comment]
This is pure speculation. I don't have Catalina to test on.

**Comment by xzyfer** [comment]
Confirming whether you can successfully install an older version of node-sass would provide a useful data point.

**Comment by ghazal** [comment]
Well, reversing to node 12, and keeping the former settings of joomla package.lock.json, ie node-sass 4.12, success !
Node modules installed properly.
NB : darwin-x64-72_binding.node was used

**Comment by saper** [comment]
This is a node bug:

https://github.com/nodejs/node/issues/30581

Please upgrade to 13.3.0

**Comment by ghazal** [comment]
Tks for checking and modifying issue title accordingly.
