### ISSUE TITLE
Node-Gyp dependency requires python2 - please update your dependency to a newer version of node-gyp

### ISSUE THREAD

**Issue by c4collins** [sass/node-sass#2808]
- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by nschonni** [comment]
Duplicate of #2716 and a bunch of other issues

**Comment by c4collins** [comment]
How can this be a duplicate if the other issue is closed without remark?
