### ISSUE TITLE
Release v4.9.0/darwin-x64-67_binding.node missing

### ISSUE THREAD

**Issue by LucaPrete** [sass/node-sass#2809]
Hello everyone,

For different reasons, I still have to use the version 4.9.0 of node-sass, and I can't upgrade it.

Unfortunately, while running `npm install` I get `version of Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-67_binding.node"`

The same thing happens under Ubuntu (of course the release has a different name).

I've tried to go to the release page, and indeed this version is missing.

This causes npm to download the source and starting a full build, which takes a large amount of time. Would it be possible to please upload the v4.9.0 release? This would save lots of time waiting for endless builds!

Then, we'll update as soon as we can to newer versions.

Thank you

**Comment by xzyfer** [comment]
Check the compatibility chart on the first line of the read me

**Comment by LucaPrete** [comment]
@xzyfer thanks for replying.

I saw it, but I can't understand how that can help to solve the issue. What am I missing?

**Comment by xzyfer** [comment]
Check what version of node-sass you're using against the compatibility table.

```
npm list node-sass
```
```
node -v
```

**Comment by LucaPrete** [comment]
@xzyfer I don't see why this should be closed, and what version I'm using has anything to do with the issue of a release missing from the release page.

Node-sass, unfortunately, is not directly installed by me, but from another package through angular.
And I cannot even update the package now, because this would require an angular update as well.

**Comment by xzyfer** [comment]
Then version of node-sass you have does not support your version of node. That's why the binary is missing. You need to.down grade your node to a supported version or update your version of node-sass. There is nothing we can do so the issue is closed.

**Comment by LucaPrete** [comment]
That was it! Thanks so much for the help!
