### ISSUE TITLE
Denial of Service vulnerability

### ISSUE THREAD

**Issue by diogomiguel** [sass/node-sass#2818]
All versions of node-sass are vulnerable to Denial of Service (DoS). Crafted objects passed to the renderSync function may trigger C++ assertions in CustomImporterBridge::get_importer_entry and CustomImporterBridge::post_process_return_value that crash the Node process. 

All versions affected.

[More info](https://www.npmjs.com/advisories/961)

**Comment by zevioso** [comment]
See https://github.com/sass/node-sass/issues/2816

**Comment by nschonni** [comment]
Duplicate of #2816
