### ISSUE TITLE
Security issue when running npm audit

### ISSUE THREAD

**Issue by rodrigomata** [sass/node-sass#2820]
NPM version (npm -v): 6.11.3
Node version (node -v): v12.6.0
Node Process (node -p process.versions):
Node Platform (node -p process.platform): darwin
Node architecture (node -p process.arch): x64
node-sass version (node -p "require('node-sass').info"):

**Issue**:
Running `npm audit` shows the following security information:
![Screen Shot 2020-01-14 at 11 38 15](https://user-images.githubusercontent.com/15259836/72368702-317d3300-36c4-11ea-90b2-8efdb31e8c94.png)

(Issue also happens with node-sass v.4.13.0)

**Comment by pzelnip** [comment]
https://www.npmjs.com/advisories/961 reports that it's *all* versions of node-sass that are vulnerable.

Is there an ETA on a fix?

**Comment by nschonni** [comment]
Duplicate of #2816
