### ISSUE TITLE
4.13.1 vulnerabilities

### ISSUE THREAD

**Issue by clement-fleury-assoconnect** [sass/node-sass#2826]
There are 16 active vulnerabilities referenced in Snyk : https://snyk.io/test/npm/node-sass/4.13.1
And there are 0 referenced in GitHub : https://github.com/sass/node-sass/security/advisories

These should be fixed ASAP, or contact Snyk to close them if they are false positives.

**Comment by adamsbloom** [comment]
Is there anyone looking at upgrading the version of the libsass binary in node-sass to >=3.6.9? I believe that might resolve the Snyk vulnerabilities.

**Comment by nschonni** [comment]
Libsass Upgrade is being tracked in https://github.com/sass/node-sass/issues/2685

**Comment by Janaka-Steph** [comment]
Are those vulnerabilities can affect a production web app already compiled?

**Comment by xzyfer** [comment]
@Janaka-Steph these only affect people compiling Sass as a web service. It does not affect compiling Sass code as a CLI and build pipeline.

**Comment by Janaka-Steph** [comment]
Alright thank you!
