### ISSUE TITLE
Error in Node - Linux

### ISSUE THREAD

**Issue by Mikeez** [sass/node-sass#2829]
- NPM version (`npm -v`): 6.13.4

 Node version (`node -v`): 10.18.1

- Node Process (`node -p process.versions`): 
`{ http_parser: '2.8.0',
  node: '10.18.1',
  v8: '6.8.275.32-node.55',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.39.2',
  napi: '5',
  openssl: '1.1.1d',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019c' }
`
- Node Platform (`node -p process.platform`): Linux

- Node architecture (`node -p process.arch`): x64

- node-sass version (`node -p "require('node-sass').info"`): 
`node-sass	4.13.1	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
`
- npm node-sass versions (`npm ls node-sass`): 4.13.1

**On Windows I can run my app that has node-sass, but on my linux ubuntu 18.04 x64
I get an error:** 
```Creating an optimized production build...
Failed to compile.

./src/assets/scss/style.scss
SassError: File to import not found or unreadable: partials/other/Switches.
        on line 58 of /home/mikeez/Documents/datacentral/frontend/src/assets/scss/style.scss
>> @import "partials/other/Switches";

   ^
```

**I tried deleting node modules, reinstalling node-sass, rebuilt and using unsafe command.
Nothing worked.
My files are named correctly as it works in windows.... _whatever..**

**Comment by Mikeez** [comment]
There was an issue opened for people like that before, so it seems it is a users end? Any fix though?

**Comment by nschonni** [comment]
Do you have the project published somewhere to reproduce this?
Guess would be a casing issues since Windows is case-insensitive, but unix isn't.

**Comment by Mikeez** [comment]
@nschonni I can provide the files? Will that help? I do not have all files somewhere, its a private repo.

```/**======================================================================
=========================================================================
File: style.css
=========================================================================
=========================================================================
  == Table of Contents==
	- Generic classes
		-	Margin, Padding, Font class, text align, position, floating, overflow, background class, text color, display class, boarder class
	- Theme Elements
		-	Accordion, Button, tabs, typography, buttons, box shadow, Lable & Badges, Alert, Pagination, Breadcumb, Cards, Collapse,
        -   Carousel, Grid, Progress, Model, tooltip, popover, Datepicker, Gridstack, lightbox, notification, Nestable, pnotify, rating,
        -   Rangeslider, Slider, Syntax Highlighter, Tour, Treeview, Toolbar, Session Timeout, Session idle Timeout, offline, Animation
    - Forms
        -   Forms Elements, Advance Form Control, Validation, Masking, Wizard, Picker, Select
	- Pages
		-   Chat, authentication, Maintenance, Maps, Landingpage messages, task, Todo, Notes, Charts, Icons, Gallery, Editors,
        -   Invoice, Full Calender, File Upload,
=================================================================================
=================================================================================== */
@import "~bootstrap/dist/css/bootstrap";
// General theme contents
@import "partials/variables";
@import "partials/general";
@import "partials/generic";
@import "partials/mixins/function";

// important Element
@import "partials/menu/menu-lite";
@import "partials/widget/widget";

// Theme Element
@import "partials/theme-elements/form";
@import "partials/theme-elements/radiobox-checkbox";
@import "partials/theme-elements/labels-badges";
@import "partials/theme-elements/data-tables";
@import "partials/theme-elements/authentication";
@import "partials/theme-elements/button";
@import "partials/theme-elements/alert";
@import "partials/theme-elements/breadcrumb-pagination";
@import "partials/theme-elements/progress";
@import "partials/theme-elements/tooltip";
@import "partials/theme-elements/popover";
@import "partials/theme-elements/nav";
@import "partials/theme-elements/modal";
@import "partials/theme-elements/notes";
@import "partials/theme-elements/gallery-masonry";
@import "partials/theme-elements/gallery-advance";

@import "~fullcalendar-reactwrapper/dist/css/fullcalendar.min.css";

// Other
@import "partials/other/chat";
@import "partials/other/prism";
@import "partials/other/toolbar";
@import "partials/other/Switches";
@import "partials/other/wizard";
@import "partials/other/chart";
@import "partials/other/icon-lauouts";
@import "partials/other/calendar";
@import "partials/other/file-upload";

@import "partials/layouts/dark";
@import "partials/layouts/rtl";

@import "partials/third-party/third-party";```

File name: _switches.scss

```
/**  =====================
      Switches css start
==========================  **/

.switch {
    input[type=checkbox] {
        opacity: 0;
        position: absolute;

        + .form-check-label,
        + .cr {
            position: relative;
            display: inline-block;
            transition: 0.4s ease;
            height: 20px;
            width: 35px;
            border: 1px solid #e9eaec;
            border-radius: 60px;
            cursor: pointer;
            z-index: 0;
            top: 12px;

            &:after,
            &:before {
                content: "";
                position: absolute;
                display: block;
                top: 0;
                left: 0;
            }

            &:before {
                transition: 0.2s cubic-bezier(0.24, 0, 0.5, 1);
                height: 20px;
                width: 35px;
                border-radius: 30px;
            }

            &:after {
                box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1), 0 4px 0 0 rgba(0, 0, 0, 0.04), 0 4px 9px rgba(0, 0, 0, 0.13), 0 3px 3px rgba(0, 0, 0, 0.05);
                transition: 0.35s cubic-bezier(0.54, 1.6, 0.5, 1);
                background: #f7f7f7;
                height: 19px;
                width: 19px;
                border-radius: 60px;
            }
        }

        &:checked + .form-check-label,
        &:checked + .cr {
            &:before {
                background: $theme-color;
                transition: width 0.2s cubic-bezier(0, 0, 0, 0.1);
            }

            &:after {
                left: 16px;
            }
        }

        &:disabled + label {
            opacity: 0.5;
            filter: grayscale(0.4);
            cursor: not-allowed;
        }
    }
    @each $value in $color-bt-name {
        $i: index($color-bt-name, $value);

        &.switch-#{$value} input[type=checkbox]:checked + .form-check-label:before,
        &.switch-#{$value} input[type=checkbox]:checked + .cr:before {
            background: nth($color-bt-color,$i);
        }
    }

    &.switch-alternative input[type=checkbox]:checked + .form-check-label:before,
    &.switch-alternative input[type=checkbox]:checked + .cr:before {
        background: $theme-color2;
    }
}
/**====== Switches css end ======**/
.switch{
    .invalid-feedback{
        position: absolute;
        width: max-content;
        top: calc(100% + 15px);
    }
    .form-check{
        input[type=checkbox] + .form-check-label{
            top: 4px;
        }
    }
}
```

**Comment by Mikeez** [comment]
> Do you have the project published somewhere to reproduce this?
> Guess would be a casing issues since Windows is case-insensitive, but unix isn't.

You are right.

Unix is case sensitive and there was a capital letter... Thank you

**Comment by raj360** [comment]
I am having the same exact error, the project is working fine locally but the error arose when I deploy it to production, any suggestions ??

**Comment by CarlosAlberto1x9** [comment]
> Do you have the project published somewhere to reproduce this?
> Guess would be a casing issues since Windows is case-insensitive, but unix isn't.

thanks!! works
