### ISSUE TITLE
@import (@use) with absolute paths (create-react-app)

### ISSUE THREAD

**Issue by ehahn9** [sass/node-sass#2834]
Hi. I'm trying to get absolute paths to work without much luck (oversimplified folder structure, real one is deeper):
```
(project-root)/
  src/
    folderA/ 
      styles.scss
    folderB/
       other.scss
```

In `other`, I'd like to write something like:

```
@import "src/folderA/styles";   /* or @use, etc. */
```
I've tried a lot of combinations of `{}/src/folderA/styles` (and also `~`) but alas no luck.

Is there an syntax for the import path I should use? Is there a config I should set up (note: this is a non-ejected create-react-app environment, so I'm a bit limited).

Thanks!

**Comment by xzyfer** [comment]
You need to add your root directory in includePaths

https://github.com/sass/node-sass/blob/master/README.md#includepaths

**Comment by ehahn9** [comment]
Thanks, but is there any documentation on where sass looks for the config? I've tried (project)/sass.config.js but I know it's reading that (I'm probably not understanding the sass config flow)... Is c-r-a forcing the sass config to come from elsewhere? Apologies for newbie Q's here - but I suspect c-r-a folks might run into the same thing if they attempt abs imports..

**Comment by xzyfer** [comment]
We don't know anything about CRA. You'll have to ask them as they're in control of how the config I'd loaded.

From our perspective we highly recommend you use relative paths. That's how we intend import to be used.
