### ISSUE TITLE
meta: Clear out old Travis CI Service Setting on Repo

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#2836]
@xzyfer came across this when I was trying to troubleshoot a random GitHub bug/feature and come across this setting https://github.com/sass/node-sass/settings/hooks/575718
Looks like it was setup by Andrew a long time ago, but I didn't want to just silently remove it in case it broke something unintentionally. Don't think that's really a risk, just wanted to check with you first.

**Comment by xzyfer** [comment]
I don't have any recollection of this. Feel free to remove it and we'll
deal with any issues if the come up

**Comment by nschonni** [comment]
OK, it's been deleted now
