### ISSUE TITLE
FreeBSD assets missing for v4.13.1

### ISSUE THREAD

**Issue by spagu** [sass/node-sass#2837]
A quick one that for some reason v4.13.1 has no FreeBSD assets.  Any reason FreeBSD was dropped?

**Comment by nschonni** [comment]
We don't have a CI that produces FreeBSD pending https://github.com/sass/node-sass/pull/2592
@saper builds and attaches them when he can, but they aren't something we block a release waiting for

**Comment by saper** [comment]
I have uploaded the assets, sorry for the delay.
