### ISSUE TITLE
my project can't run at my fedora desktop with some Error! 

### ISSUE THREAD

**Issue by qiphon** [sass/node-sass#2845]
Syntax Error: /home/qiphon/.npm/node-sass:1
ELF
^

SyntaxError: Invalid or unexpected token
imgupload.vue?vue&type=style&index=0&id=07465d7a&lang=scss&scoped=true& 1:0-555 1:571-574 1:576-1128 1:576-1128

**Comment by saper** [comment]
Can you please follow the TROUBLESHOOTING.md and update the issue to list all the information in the issue template?
