### ISSUE TITLE
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (75)

### ISSUE THREAD

**Issue by somebeaver** [sass/node-sass#2848]
npm: `6.13.6`
    node: `13.8.0`

    Node Process:
    {
      node: '13.8.0',
      v8: '7.9.317.25-node.28',
      uv: '1.34.1',
      zlib: '1.2.11',
      brotli: '1.0.7',
      ares: '1.15.0',
      modules: '79',
      nghttp2: '1.40.0',
      napi: '5',
      llhttp: '2.0.4',
      openssl: '1.1.1d',
      cldr: '36.0',
      icu: '65.1',
      tz: '2019c',
      unicode: '12.1'
    }
    Node Platform: `darwin`
    Node Architecture: `x64`

    node-sass version:
    node-sass	4.13.1	(Wrapper)	[JavaScript]
    libsass  	3.5.4	(Sass Compiler)	[C/C++]

    npm node-sass versions:
    project@0.0.1 /Users/name/Projects/project/electronapp
    └── node-sass@4.13.1

I have installed node-sass by running `npm install node-sass` in my project directory. This is my app's main.js file:

    const sass = require('node-sass')

When I run the Visual Studio Code debugger, this is what I see:

    Users/name/Projects/project/electronapp/node_modules/.bin/electron --inspect-brk=13989 . 
    Debugger listening on ws://127.0.0.1:13989/86ea89cf-84a2-40b9-b47a-3d7422c8a98a
    For help, see: https://nodejs.org/en/docs/inspector
    Debugger attached.
    App threw an error during load
    Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported     runtime (75)
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v4.13.1
        at module.exports (/Users/name/Projects/project/electronapp/node_modules/node-    sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/name/Projects/project/electronapp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)

The only dependency my project has is Electron (7.1.12).

I have tried reinstalling node-sass (globally and not), I have tried `npm rebuild node-sass` and I even tried reinstalling macOS from the recovery disk because I can't find anyone else with this error. Any help is appreciated, thanks.

**Comment by xzyfer** [comment]
The visual studio debugger is running a different version of node than your system version. You need to configure visual studio to use your system node install.

We don't know how to do this, but a Google search should help.
