### ISSUE TITLE
Node Sass does not yet support your current environment: OS X 64-bit

### ISSUE THREAD

**Issue by zhilianbi520** [sass/node-sass#2849]
- NPM version (`6.13.4`):
- Node version (`v12.16.0`):
- Node Process (`node -p process.versions`):
- Node Platform (`{
  node: '12.16.0',
  v8: '7.8.279.23-node.31',
  uv: '1.34.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}`):
- Node architecture (`x64`):
- node-sass version (`node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]`):
- npm node-sass versions (`node-sass@4.12.0`):

mac :macOS Catalina   OS version 10.15.3

**Comment by zhilianbi520** [comment]
![20200214150547](https://user-images.githubusercontent.com/16549630/74509091-a8178580-4f3b-11ea-92be-9f8dc81bb44f.jpg)
@xzyfer

**Comment by zhilianbi520** [comment]
![20200214150547](https://user-images.githubusercontent.com/16549630/74509215-e4e37c80-4f3b-11ea-8f1a-805279512c61.jpg)
@xzyfer

**Comment by nschonni** [comment]
From you screenshot (please don't use screenshots in the future), you're also trying to install node-sass 4.94. That version isn't supported on Node 12. Find what package that has it as a dependency and upgrade it

**Comment by zhilianbi520** [comment]
![20200214153258](https://user-images.githubusercontent.com/16549630/74510759-67217000-4f3f-11ea-8126-03c2b512a9d7.jpg)
@nschonni
