### ISSUE TITLE
URL is not accessible - Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node":   HTTP error 404 Not Found 

### ISSUE THREAD

**Issue by kevin-patel** [sass/node-sass#2852]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node
  Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node":
  HTTP error 404 Not Found

- NPM version (`6.13.7`):
- Node version (`13.9.0`):
- Node Process (`{
  node: '13.9.0',
  v8: '7.9.317.25-node.28',
  uv: '1.34.2',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '79',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  openssl: '1.1.1d',
  cldr: '36.0',
  icu: '65.1',
  tz: '2019c',
  unicode: '12.1'
}`):
- Node Platform (`win32`):
- Node architecture (`x64`):
- node-sass version (`node-sass       4.13.1  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]`):
- npm node-sass versions (`nfq-angular@1.1.2 D:\Projects\NFQ\Source\NFQ.Web\ClientApp
`-- node-sass@4.13.1`):

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s
