### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '...../node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by MattOndo** [sass/node-sass#2853]
I've tried every "solution" on the internet and no matter what I can't get this to work. What am I missing?

node -v: v12.16.1
npm -v: 6.13.4

package.json:
```
{
  "name": "collaboratemd.com",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "gulp sass"
  },
  "devDependencies": {
    "gulp": "^4",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.6.0"
  }
}
```

I've tried rebuilding node-sass, I've tried sudo npm install, I've tried file permissions, I've tried various versions of NPM, Node, and Gulp, nothing. Please help this is killing me!!!

**Comment by saper** [comment]
I think you might need to ask gulp-sass first. Also, please follow our TROUBLESHOOTING.md guide...

**Comment by jakubka** [comment]
I had the same.

Tried reinstalling the package (`npm install node-sass`) and now it works. ¯\_(ツ)_/¯

**Comment by saper** [comment]
Sorry, we have not enough information to troubleshoot this!

**Comment by eueid** [comment]
I just typed `npm install` and restarted my pc and worked
