### ISSUE TITLE
node sass 4.7.2 can't be installed in my mac

### ISSUE THREAD

**Issue by Arnav2416** [sass/node-sass#2854]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-79_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 postinstall /Users/arnav/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/arnav/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/arnav/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.8.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/arnav/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/arnav/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/arnav/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/arnav/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/arnav/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/arnav/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/arnav/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/arnav/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/arnav/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/arnav/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/arnav/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/arnav/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (/Users/arnav/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/Users/arnav/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/Users/arnav/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /Users/arnav/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /Users/arnav/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /Users/arnav/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /anaconda3/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:441:11)
gyp ERR! stack     at Socket.emit (events.js:321:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:668:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/arnav/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/arnav/node_modules/node-sass
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open '/Users/arnav/package.json'
npm WARN arnav No description
npm WARN arnav No repository field.
npm WARN arnav No README data
npm WARN arnav No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arnav/.npm/_logs/2020-03-05T07_54_11_343Z-debug.log
arnavs-Air:~ arnav$ 

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by xzyfer** [comment]
You're trying to install 4.7.2 on node 13. Please the VERY FIRST LINE of the readme.
