### ISSUE TITLE
Can't install node-sass

### ISSUE THREAD

**Issue by evandentremont** [sass/node-sass#2855]
I'm unable to install node-sass. 

It appears to be related to this error: 

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-72_binding.node": 
HTTP error 404 Not Found
```

It doesn't appear to be able to find `https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-72_binding.node` which is unsurprising, because the most recent version is actually `https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-72_binding.node`

`npm install node-sass@4.13.1` has the same error.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s

**Comment by evandentremont** [comment]
Well that was helpful. 


```
evan@Omen:~/Repos/test$ node -v
v12.16.1
```

It would appear this version of node is supported and there is no other information listed.

Is this simply not an issue then?

**Comment by evandentremont** [comment]
So as someone who's never had an issue with this project, it's not clear what that issue template is or where to find it. I found another one that wasn't summarily closed, am I able to include that information in this issue? Should I open a new one?

**Comment by saper** [comment]
The issue template is there when you open an issue; it can be also found in [the repository](https://github.com/sass/node-sass/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

However I think you should go through our https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md document. I think some part of your project has a typo in their dependencies, as [v3.13.1](https://github.com/sass/node-sass/releases/v3.13.1) is pretty old (will run with node 6 which is end of life). Did you mean `v4.13.1`?

**Comment by evandentremont** [comment]
I tried to install 4.13.1 and whatever abstraction is going on is trying to download 3.13.1. I assumed it was a bug, but didn't say the magic words apparently. 

Fuck it. I don't care enough to help.
