### ISSUE TITLE
"Incompatible units" with "min(32rem, 100%)"

### ISSUE THREAD

**Issue by distantnative** [sass/node-sass#2856]
- NPM version (`npm -v`): 6.13.7
- Node version (`node -v`): v10.16.3
- Node Process (`node -p process.versions`):
{ http_parser: '2.8.0',
  node: '10.16.3',
  v8: '6.8.275.32-node.54',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.39.2',
  napi: '4',
  openssl: '1.1.1c',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019a' }

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.13.1  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):
node-sass@4.13.1 

Error message

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Incompatible units: '%' and 'rem'.

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Layout/Cards.vue?vue&type=style&index=0&lang=scss& 4:14-451 14:3-18:5 15:22-459
```

### Code

```css
grid-template-columns: repeat(auto-fill, minmax(min(32rem, 100%), 1fr));
```

However, mixing `rem` and `%` is according to specification: https://developer.mozilla.org/en-US/docs/Web/CSS/min

**Comment by nschonni** [comment]
If you're trying to use the native CSS `min` function you need to quote it, as it overlaps with an older Sass function that is what is throwing the error. EX: https://github.com/sass/node-sass/issues/2815#issuecomment-574038619

**Comment by distantnative** [comment]
Awesome, thank you so much for the quick reply!
