### ISSUE TITLE
[Unsupported] Installing node-sass 4.13.1 on Electron

### ISSUE THREAD

**Issue by VariableVasasMT** [sass/node-sass#2857]
Ubuntu system process.versions.modules returns 75 on ubuntu 18.04

Breaks the code in cypress@^4.1.0 and node-sass@^4.13.1
https://github.com/sass/node-sass/blob/e84c6a9f8d62b27174d650c38d18b327c97753ba/lib/extensions.js#L62
should this even be a switch case?

**Comment by nschonni** [comment]
It sounds like you're likely running through Electron or another non-NodeJS v8 environment

**Comment by VariableVasasMT** [comment]
Yeah, I am running using electron

**Comment by nschonni** [comment]
Sorry, Electron isn't a supported environment, this is why it is currently a switch case
