### ISSUE TITLE
mkdirp < v1 deprecated

### ISSUE THREAD

**Issue by SampsonCrowley** [sass/node-sass#2865]
```bash
node-sass > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

mkdirp less than version 1 has been deprecated. I will try to submit a pull request later today

**Comment by YellowPanda11** [comment]
this will help me a ton.
https://app.zenhub.com/workspaces/issues-5966701b37fdf9775617e322/issues/adobe-community/issues/41658

**Comment by YellowPanda11** [comment]
https://github.com/sass/node-sass/issues/2876

**Comment by PolyPik** [comment]
We can close this now.
