### ISSUE TITLE
Azure Linux Kernel support

### ISSUE THREAD

**Issue by LucasFormiga** [sass/node-sass#2867]
- NPM version: 6.13.4
- Node version: 12.16.1
- Node Process:
- Node Platform: Linux
- Node architecture: x64
- node-sass version: (the server not even install the package, but is trying to install node-sass 4.9.3)
- npm node-sass versions: 4.9.3

Hello, I am trying to `npm install` my Laravel project (which uses node-sass) on my new staging environment at Azure. When the NPM tries to install the node-sass, It gives the following message: 

> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-72_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-72_binding.node": 404 not found

I went on the node-sass releases page and I saw that version 4.9.3 doesn't have linux-x64-72 binary, it means that this version does not support my Linux Kernel?

Linux Distro: Ubuntu **18.04** (tried on Ubuntu **16.04** too)
Kernel: **Linux machine-name 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**
(also, tried with Kernel: **Linux other-machine-name 4.15.0-1071-azure #76-Ubuntu SMP Wed Feb 12 03:02:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**)

**Comment by nschonni** [comment]
Node-sass 4.9.3 doesn't support Node 12 https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support
