### ISSUE TITLE
Recent linux-ia32 builds are missing in release downloads

### ISSUE THREAD

**Issue by flberger** [sass/node-sass#2870]
There for example is no `linux-ia32-72_binding.node` in https://github.com/sass/node-sass/releases/tag/v4.13.1

This effectively breaks a current installation of node-sass on my system, and subsequently the software that depends on it.

node v12.13.0 , npm 6.12.0

**Comment by xzyfer** [comment]
This is explained in the release notes table. The node project has dropped
Linux ia32 support in recent major versions.

**Comment by flberger** [comment]
Is there any chance of building a `linux-ia32-72_binding.node` myself?

Seems the more straightforward way than convertign a running server from 32 to 64 bit.

**Comment by xzyfer** [comment]
In you're able to run node as 32bit then maybe. But we cannot offer support.

**Comment by flberger** [comment]
But compile instructions? I did not find any on how to build my own `linux-ia32-72_binding.node` in the repository.

**Comment by xzyfer** [comment]
You can try npm rebuild node-sass --force

**Comment by flberger** [comment]
Thanks!
