### ISSUE TITLE
Update libsass to 3.6.0

### ISSUE THREAD

**Issue by DanielNohra** [sass/node-sass#2871]
@xzyfer please update node-sass to use lib-sass to 3.6.0  since whitesource tool always throws the below vulnerability:
"An issue was discovered in LibSass through 3.5.4. An out-of-bounds read of a memory region was found in the function Sass::Prelexer::skip_over_scopes which could be leveraged by an attacker to disclose information or manipulated to read from unmapped memory causing a denial of service."

**Comment by nschonni** [comment]
Duplicate of #2685
