### ISSUE TITLE
node-sass won't compile on Python 3 systems (e.g. EL8) due to node-gyp dependency lock

### ISSUE THREAD

**Issue by ehelms** [sass/node-sass#2877]
The current version of node-sass is locked to the 3.8.0 stream of node-gyp. This version of node-gyp does not support Python 3 only environments such as Enterprise Linux 8.

This support was added to node-gyp starting at version 5.0.0. See:

https://github.com/nodejs/node-gyp/pull/1582

Example compilation output:

```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/lib/node_modules/node-gyp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/lib/node_modules/node-gyp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
```

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by PolyPik** [comment]
It is available in the v5 branch.

**Comment by himdel** [comment]
Indeed, fixed in https://github.com/sass/node-sass/commit/15886f081b585fd784c9ab6a5b9ad36aba7105a4, now we just need a release :)

**Comment by gtmills** [comment]
We hit this on [OpenBMC ](https://en.wikipedia.org/wiki/OpenBMC) when trying to [move up our meta-oe layer](https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/31299/2/meta-openembedded/meta-oe/recipes-devtools/nodejs/nodejs_12.14.1.bb#7), which drops support for Python 2 and is Python 3 only. Any update of when a release with this fix will happen? I see this fix is in the v5 branch, would you consider pulling this fix into a version 4 release? 

Thank you!
Gunnar

**Comment by Zekfad** [comment]
There's a workaround using _yarn_ until v5 is released:
```json
	"resolutions": {
		"**/node-gyp": "^7.0.0"
	}
```

**Comment by himdel** [comment]
There were only 5 commits to the v5 branch this year.

I would suggest that node-sass is truly dead, and [Dart sass](https://sass-lang.com/dart-sass) ([npm:sass](https://www.npmjs.com/package/sass)) is the new official sass implementation (which does not depend on node-gyp or python2).

**Comment by ext** [comment]
Run into this as well as part of python2.7 being dropped from our systems. Does the master-branch not build with later versions or why can it not be bumped there as well?

This effectively kills node-sass package until either v5 is released or node-gyp is bumped.

**Comment by dospunk** [comment]
also having this issue. It's really frustrating to have to install a deprecated language to use this when the version could just be bumped.
