### ISSUE TITLE
Setting up on Ununtu 18.04 doesn't work

### ISSUE THREAD

**Issue by youradds** [sass/node-sass#2878]
My setup: 

- NPM version : 6.14.4
- Node version : v13.12.0
- Node Process:
```
node -p process.versions
{
  node: '13.12.0',
  v8: '7.9.317.25-node.30',
  uv: '1.35.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '79',
  nghttp2: '1.40.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1e',
  cldr: '36.1',
  icu: '66.1',
  tz: '2019c',
  unicode: '13.0'
}
```
- Node Platform: linux (Ubuntu 18.04)
- Node architecture: x64
- node-sass version:
> 
> node -p "require('node-sass').info"
> node-sass       4.13.1  (Wrapper)       [JavaScript]
> libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):

```
npm ls node-sass
/usr/bin
└── node-sass@4.13.1
```

How am I supposed to access the CLI stuff? With the old Ruby setup (depreciated, thus trying the new one), I used to do:

sass --watch /home/ultranerds/web/x.ultranerds.co.uk/public_html/2018/css/sass:/home/ultranerds/web/x.ultranerds.co.uk/public_html/2018/css --style expanded

It seems "node-sass" and "sass" don't work (only `sassc`, which I have also installed while trying to get this going)

Its doing my head in :( I'm not sure if its a bug - or a mis-configuration somewhere

TIA

Andy

**Comment by saper** [comment]
> npm ls node-sass
> /usr/bin
> └── node-sass@4.13.1

Are you doing this in `/usr/bin` directory? Please, no...

> It seems "node-sass" (...) don't work

Can you show me the log files what you are trying to do? `node-sass` program will be installed in `node_modules/.bin` after it is installed. Some people add that to their `$PATH`.

**Comment by youradds** [comment]
All I did was install with -g 

Anyway, I gave up with this version. Was much easier just to install `sassc` , and then I've written my own Perl script to watch a directory, and re-compile the .scss files when a change is made. So far its worked really well, and gives me more flexability

**Comment by saper** [comment]
ok, can we close this then?

**Comment by youradds** [comment]
Yes please do

Thanks
