### ISSUE TITLE
Errors even after `npm rebuild` +  current environment matches the found binding's environment

### ISSUE THREAD

**Issue by brightpixels** [sass/node-sass#2882]
- NPM version (`npm -v`): 5.6.0
- Node version (`node -v`): 10.0.0
- Node Process (`node -p process.versions`): 
````
{
    http_parser: '2.8.0',
    node: '10.0.0',
    v8: '6.6.346.24-node.5',
    uv: '1.20.2',
    zlib: '1.2.11',
    ares: '1.14.0',
    modules: '64',
    nghttp2: '1.29.0',
    napi: '3',
    openssl: '1.1.0h',
    icu: '61.1',
    unicode: '10.0',
    cldr: '33.0',
    tz: '2018c'
}
````
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Error: ENOENT: no such file, or directory, scandir 'C:\Users......\node-modues\node-sass\vendor'
- npm node-sass versions (`npm ls node-sass`): node-sass@4.11.0

I have successfully installed node-sass with env variable pointing to a local version binary: `SASS_BINARY_PATH=/c/......../win32-x64-64_biniding.node npm install node-sass`.

When I try to run `npm start'` in a create-react-app which has .sccs file, I get this error: Error: ENOENT: no such file, or directory, scandir 'C:\Users......\node-modues\node-sass\vendor'

I have tried npm rebuild node-sass with `SASS_BINARY_PATH=/c/......../win32-x64-64_biniding.node npm rebuild node-sass` it seems to go through successfully BUT `npm start` gives me this error:

````
Error: Missing binding C:\Users\............\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
- Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`. Run `npm rebuild node-sass` to download the binding for your current environment
````

The last error message is little confusing because the current environment it's displaying and the bindings it's found are exactly the same.

**Comment by saper** [comment]
> `SASS_BINARY_PATH=/c/......../win32-x64-64_biniding.node npm install node-sass`

This is unlikely to cause any effect. Can you put your full logs somewhere (on gist.github.com for example?) Please try not to redact paths manually. What filesystem are you running on?

**Comment by brightpixels** [comment]
Where do i find the logs?

**Comment by saper** [comment]
Can you run this

    node -p "require('node-sass').info"

with your `SASS_BINARY_PATH` set and give us a full output?

**Comment by saper** [comment]
Also, when you run your app, do you have `SASS_BINARY_PATH` set as well? It isn't obvious from what you say here.

**Comment by brightpixels** [comment]
Your last point was my solution! my `npm start` command didn't include setting the path as well. I didn't think I needed it there as well! Thank you.
