### ISSUE TITLE
Jenkins not able to download binding

### ISSUE THREAD

**Issue by BTARPAR** [sass/node-sass#2883]
- NPM version (`6.13.4`):
- Node version (`12.14.1`):
- node-sass version (`4.11.0`):

![Screen Shot 2020-04-01 at 12 46 39 PM](https://user-images.githubusercontent.com/18237494/78180518-bc461200-7417-11ea-8e0c-c076bca41cfd.png)

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s

**Comment by BTARPAR** [comment]
> https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s

thank you
