### ISSUE TITLE
Missing binding for latest node:alpine

### ISSUE THREAD

**Issue by tlaukkan** [sass/node-sass#2898]
Latest working node:alpine docker image:
sha256:69aa28f8a555cbc5b01d30e43a7fb4ab0485fa16a3b4a6d220564a8ecf68c8e0

Failing node:alpine docker image:
sha256:10fd9c0eef5de69e5d7f3e91e8592d97cbcf1431b0de15b84a1a7c25f85fb539

Build is unable to load binary:
https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node

**Comment by lehuuhienn** [comment]
Me too, Someone please fix it :((

**Comment by xzyfer** [comment]
![Screenshot_20200422-184452](https://user-images.githubusercontent.com/579928/79960973-68d05c80-84c9-11ea-803c-a732bf42fc3f.png)
