### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by ReutovDanila** [sass/node-sass#2899]
"node-sass": "^4.13.1",

I see it on gitlab pipeline
![image](https://user-images.githubusercontent.com/58364276/79973276-f303cb00-849f-11ea-9652-c6e1378b4285.png)

**Comment by goto-bus-stop** [comment]
you can use Node.js 13 for now until the node-sass 4.14.0 release is on npm.

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/2895

**Comment by adwhit** [comment]
@xzyfer Not sure this is a duplicate? This is related to `4.13.1` failing to download. I have the same problem on CI.

**Comment by xzyfer** [comment]
It's 4.13.1 trying to download the node 14 binary.

**Comment by jpettit** [comment]
Seeing the same thing.  If you're suddenly hitting this it is most likely because you're using `node:alpine` as your docker image.  It was just updated to Node 14 / alpine3.11 yesterday.

https://github.com/nodejs/docker-node/blob/2d82f7b12b855d3ce857f09efcf2c5508f0fe26b/14/alpine3.11/Dockerfile

**Comment by Sanyaorg** [comment]
Fixed with downgrading Node to v13 (image: node:13-alpine3.10) and "node-sass": "4.13.0"

**Comment by sbelausteguiCG** [comment]
Hi, we have the same problem here with BitBucket pipelines.
We've tried @Sanyaorg approach but with same results. All of our pipelines are failing. Does anyone have fixed this with bitbucket?
Thanks!

**Comment by sbelausteguiCG** [comment]
> Hi, we have the same problem here with BitBucket pipelines.
> We've tried @Sanyaorg approach but with same results. All of our pipelines are failing. Does anyone have fixed this with bitbucket?
> Thanks!

We had fixed it on bitbucket with image: node:13-alpine3.11 and "node-sass": "4.13.0".
