### ISSUE TITLE
node-sass v4.13.1 issue

### ISSUE THREAD

**Issue by Sanyaorg** [sass/node-sass#2900]
Hi,

After latest update we have issue with deployment:

> Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node"

It seems that this file is missing for some reason on version 4.13.1 but present on version 4.14.0.
The problem with this npm doesn't have v4.14.0 yet which is a bit inconvenient.

Could you please check/update file/npm?

Thank you!

**Comment by nschonni** [comment]
Duplicate #2899
