### ISSUE TITLE
Setup Issue Hunt for repository

### ISSUE THREAD

**Issue by steelbrain** [sass/node-sass#2908]
Could you please setup Issue Hunt or something similar so users can fund individual issues?

**Comment by xzyfer** [comment]
No. These platforms come and go. We prioritise work based on impact and our available time.

**Comment by steelbrain** [comment]
I appreciate that you prioritise work based on impact and your available free time but with services like issue hunt, outside contributors may be interested to fix bugs that maintainers don't have time for.

I request that you reevaluate the decision

**Comment by xzyfer** [comment]
Contributor PRs are always welcome. Open issues represent potential contributions. We have tried similar platforms in past years, until the platform closed down. In practice.l for a project of this size it had zero impact on contributions.

In our opinion they'll only add more overhead for us, taking away the time we have available to contribute ourselves.
