### ISSUE TITLE
Unable run node-sass globally on fresh installed Ubuntu 20.04

### ISSUE THREAD

**Issue by Moongazer** [sass/node-sass#2909]
Hey everyone,

I'm experiences issues were I can't figure out myself anymore what's wrong here. From a fresh installed Ubuntu 20.04 I try to setup the whole dev-toolchain again, starting with node-sass first:

```
$ sudo npm install -g node-sass
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@4.14.0 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js
```
The global installation of node-sass seems to be successful, no error like in #2216.
But if I try to use it, **both** of these commands throwing the following exception:
```
$ node-sass version (`node -p "require('node-sass').info"`)
$ node-sass theme.scss -o theme.css
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:790:3)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/usr/local/lib/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/lib/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```
If I check the scandir path, there is indeed no `vendor` directory in `/usr/local/lib/node_modules/node-sass`

**Environment infos:**
System: Ubuntu Linux 20.04 x64
node-sass: 4.14.0 (extracted from package.json as --version is not working)
npm: 6.14.4
process-versions:
```
{
  http_parser: '2.9.3',
  node: '10.19.0',
  v8: '6.8.275.32-node.55',
  uv: '1.34.2',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.40.0',
  napi: '5',
  openssl: '1.1.1d',
  icu: '66.1',
  unicode: '13.0',
  cldr: '36.1',
  tz: '2019c'
}
```
Does any of you having a similar issue or an idea how to solve this?

**Edit:** 
Just for test purposes I reinstalled with the `--unsafe-perm` option as it seems there are many issues related with global installations. There was no permission error thrown without this option in the first place, but it seems now the installation run longer and also created the missing `vendor` dir. So its working now.
```
$ sudo npm install -g --unsafe-perm node-sass
$ node-sass -v
node-sass	4.14.0	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
```
I'll not delete this issue as it was not clear to see, that the first installation was not successful (no error thrown). So it might help someone else.

**Comment by xxKeefer** [comment]
life saver, thank you so much

**Comment by lfom** [comment]
> If I check the scandir path, there is indeed no `vendor` directory in `/usr/local/lib/node_modules/node-sass`

Same error here (Pop!_OS 20.04), vendor dir cannot be created and installation fails before the package is downloaded. Thanks to @Moongazer for the workaround, but I think this should be re-opened?

**Comment by nschonni** [comment]
@lfom this is part of our troubleshooting guide that is part of our issue template https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root
