### ISSUE TITLE
Vulnerability in node-sass > sass-graph > yargs > yargs-parser

### ISSUE THREAD

**Issue by stefano-pietroiusti** [sass/node-sass#2912]
After npm install --save-dev node-sass sass-loader
-     "node-sass": "^4.14.0",
-     "sass-loader": "^8.0.2"

Get this report: 
Low             Prototype Pollution                                           

  Package         yargs-parser                                                  

  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2              

  Dependency of   node-sass [dev]                                               

  Path            node-sass > sass-graph > yargs > yargs-parser                 

  More info       https://npmjs.com/advisories/1500

**Comment by andrewphillipo** [comment]
This is affecting me too...

**Comment by rafaeljosem** [comment]
I'm having the same issue too...

**Comment by wdews-slalom** [comment]
Also affected by this.

**Comment by xzyfer** [comment]
Fixed in v4.14.1
