### ISSUE TITLE
FreeBSD is missing in node-sass V4.14.0

### ISSUE THREAD

**Issue by Jack-eliteSoho** [sass/node-sass#2914]
in node-sass 4.14.0, the FreeBSD package is missing

https://github.com/sass/node-sass/releases/tag/v4.14.0

although in node-sass 4.13.1, FreeBSD package is available.

https://github.com/sass/node-sass/releases/tag/v4.13.1

can someone upload the FreeBSD package for node-sass 4.14.0?

**Comment by saper** [comment]
Done, we are dropping node 8 since it got removed from the FreeBSD ports tree and packages

https://svnweb.freebsd.org/ports/head/www/npm/Makefile?r1=528195&r2=528194&pathrev=528195
