### ISSUE TITLE
node-sass: Command failed: node -e "try{require('./postinstall')}catch(e){}"

### ISSUE THREAD

**Issue by anon987654321** [sass/node-sass#2916]
Anybody know what to do? I'm stuck:

```
% node -v
v12.16.1
% npm -v
6.13.4
% yarn -v
1.22.4
% uname -sr
OpenBSD 6.7
% env
CC=/usr/bin/clang
CXX=/usr/bin/clang++

% yarn add webpack
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "openbsd" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠐ core-js
[2/3] ⠐ node-sass
error /home/tim/timsdisco/node_modules/core-js: Command failed.
Exit code: 127
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments:
Directory: /home/tim/timsdisco/node_modules/core-js
Output:
/tmp/yarn--1588719970972-0.4719067568869322/node[3]: /tmp/yarn--1588719970972-0.4719067568
```

Thanks.

**Comment by xzyfer** [comment]
The issue is with core-js

**Comment by anon987654321** [comment]
@xzyfer seems to be trying to download a non-existing node-sass file though? Any idea what to do?

**Comment by xzyfer** [comment]
Take a look at the very first line of the readme

**Comment by anon987654321** [comment]
@xzyfer what do you mean by that? That it's due to v4.14.1 being released? Or that OpenBSD is not in the list of supported OSes?

**Comment by anon987654321** [comment]
A bit odd, by the way, that you support FreeBSD and not OpenBSD. These days FreeBSD is on life support.

> Choose [OpenBSD](https://openbsd.org/) for your Unix needs. OpenBSD -- the world's simplest and most secure Unix-like OS. Creator of the world's simplest and most secure webserver [httpd](https://man.openbsd.org/httpd.conf)/TLS & crypto stack [LibreSSL](https://libressl.org/)/SSH implementation [OpenSSH](https://openssh.org/)/firewall [pf](https://www.openbsd.org/faq/pf/)/mail server [OpenSMTPD](https://opensmtpd.org/) and much, much more. OpenBSD -- the cleanest kernel, the cleanest userland and the cleanest configuration syntax.

**Comment by xzyfer** [comment]
Correct. Openbsd is not supported. The download will fail as expected but npm will try to compile the binary locally if you have the tool chain

**Comment by anon987654321** [comment]
@xzyfer any chance you could give some more pointers? It doesn't seem to be making it as far as to the local compile part.

The usual "but it used to work just fine a couple of months ago" also hold true in this case :)

**Comment by xzyfer** [comment]
I see no reason from the information provided why this would have ever worked, or why it would have recently stopped working.

**Comment by anon987654321** [comment]
Thanks, guess I'm in for the deep dive. I'll report back on my findings.

**Comment by anon987654321** [comment]
Managed to fix it by commenting out these two lines and installing locally:

https://github.com/zloirock/core-js/blob/master/packages/core-js/package.json#L55
https://github.com/sass/node-sass/blob/master/scripts/install.js#L157

I hope somebody else has to go through the same trouble.

**Comment by 465788227** [comment]
> Managed to fix it by commenting out these two lines and installing locally:
> 
> https://github.com/zloirock/core-js/blob/master/packages/core-js/package.json#L55
> https://github.com/sass/node-sass/blob/master/scripts/install.js#L157
> 
> I hope nobody else has to go through the same trouble.

Can you show how you install it locally?

**Comment by anon987654321** [comment]
The fix is here: https://marc.info/?l=openbsd-ports&m=160657052927238

`ln -s /usr/local/bin/node /tmp/node`

Shoutout to Solene for her help.

**Comment by anon987654321** [comment]
The fix is here: https://marc.info/?l=openbsd-ports&m=160657052927238

`ln -s /usr/local/bin/node /tmp/node`

Don't forget to replace `gcc` with `clang`:

```sh
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```

Shoutout to Solene for the help.
