### ISSUE TITLE
Failed at the node-sass@4.12.0 postinstall script. `GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by mdsadique2** [sass/node-sass#2926]
**Version detials:**
node v12.16.3
npm  v6.14.4
node-sass 4.12.0

Error starts with logged message:

_Binary has a problem: Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by xyzPath/node_modules/node-sass/vendor/linux-x64-72/binding.node)_

_npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script._

**Comment by saper** [comment]
What operating system are you running node-sass on, please specify the exact version

**Comment by trondhuso** [comment]
This also happens for me on Ubuntu 18.04 using node 12.19.0 and npm 6.14.8

**Comment by FulljsDeveloper** [comment]
It worked well with node version: 10.23.0  👍  :)

**Comment by BondJamesBond700** [comment]
i am facing same issue
Version detials:
node v15.5.1
npm 6.14.8
node-sass 4.12.0

Although , npm official says https://www.npmjs.com/package/node-sass

node 15+ works with node-sass 5.0+
