### ISSUE TITLE
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)

### ISSUE THREAD

**Issue by bsmile4all** [sass/node-sass#2928]
Loading "sass.js" tasks...ERROR
>> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v4.5.3

**Comment by nschonni** [comment]
See https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#404s
You're not running a comparable Node and node-sass version
