### ISSUE TITLE
SPFX + Office Fabric UI

### ISSUE THREAD

**Issue by dbobrovsky** [sass/node-sass#2929]
We adopt our old AngularJS APP to use SPFX. Great problem is Office Fabric UI. This library is added to the page and I cannot change it. 
![Capture](https://user-images.githubusercontent.com/1652915/83389517-038d5680-a3f9-11ea-9556-7b2ee9d25202.PNG)

We use Office 2.1 and other icons and in addition, we develop for on-prem version SP and cannot use CDN because our clients work without the Internet. I tried to use SPComponentLoader to load my version of Office Fabric

  },
  "dependencies": {
    "@angular/router": "^9.1.9",
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-loader": "^1.10.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@types/angular": "1.6.6",
    "@types/jquery": "^1.10.31",
    "@types/react": "^16.9.35",
    "@types/react-dom": "^16.9.8",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "tslint": "^6.1.2",
    "typescript": "^2.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "gulp": "^3.9.1"
  }
my package.json

How I can use my own version of Office Fabric?  I don't see any settings for it

**Comment by nschonni** [comment]
This doesn't appear to be related to the node-sass project
