### ISSUE TITLE
FreeBSD issue with tag 4.14.1 and missing bindings

### ISSUE THREAD

**Issue by SebastianStroniewskiWojtczak** [sass/node-sass#2932]
Release v4.14.1 does not contain **freebsd-x64-83_binding.node**, it stopped at freebsd-x64-79_binding.node which is obsolete and does not work with node v14.0.0

You can check your repo:
https://github.com/sass/node-sass/releases/tag/v4.14.1

**Comment by SebastianStroniewskiWojtczak** [comment]
NodeJS | Minimum node-sass version | Node Module
-- | -- | --
**Node 14 | 4.14+ | 83**

**Comment by Dracozny** [comment]
[freebsd-x64-83_binding.tar.gz](https://github.com/sass/node-sass/files/5442195/freebsd-x64-83_binding.tar.gz)
I just so happened to need this. Hope it helps.

**Comment by saper** [comment]
Would that be ok if we fix it only for 5.0.0 (#3060)?

**Comment by SebastianStroniewskiWojtczak** [comment]
Because it is not important issue and any other version can be used, I've decided to close this one.

**Comment by saper** [comment]
I have uploaded the 5.0.0 binaries so it should work out of the box.
