### ISSUE TITLE
will npm download the newest subversion by default?(support needed)

### ISSUE THREAD

**Issue by appleyuchi** [sass/node-sass#2934]
apologise that copy **node-sass's  official hints**  into following table

version name | command |  my version
-|-|-
NPM version  |npm -v | 6.11.3|
Node version | node -v | v12.11.1|
Node Process|node -p process.versions|node: '12.11.1',<br>v8: '7.7.299.11-node.12',<br>uv: '1.32.0',<br>zlib: '1.2.11',<br>brotli: '1.0.7',<br>ares: '1.15.0',<br>modules: '72',<br>nghttp2: '1.39.2',<br>napi: '5',<br>llhttp: '1.1.4',<br>http_parser: '2.8.0',<br>openssl: '1.1.1c',<br>cldr: '35.1',<br>icu: '64.2',<br>tz: '2019a',<br>unicode: '12.1'|
Node Platform |node -p process.platform|linux
Node architecture| node -p process.arch|x64
node-sass version |node -p "require('node-sass').info"|node-sass	4.14.1	(Wrapper)[JavaScript]<br>libsass  	3.5.5	(Sass Compiler)	[C/C++]
npm node-sass versions| npm ls node-sass|appleyuchi@1.0.0 /home/appleyuchi<br>└── node-sass@4.14.1

package.json is:
https://paste.ubuntu.com/p/7QNx7qPjrr/

My question is :
why did `npm ci`choose  linux-x64-72_binding.node which has been deleted in the following link?
https://github.com/sass/node-sass/issues/2648

I mean,why the `72`above is selected?
just newest by default or set by somewhere?

aplogise that if github is not the right place to ask question,
point this to me please and I'll ask it on quora/stackoverflow,etc...

**Comment by xzyfer** [comment]
72 is V8 module version for node 12. See the table at the top of the readme.
