### ISSUE TITLE
404 on download https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node

### ISSUE THREAD

**Issue by mitgath** [sass/node-sass#2958]
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node": 

HTTP error 404 Not Found

npm 6.14.6
node v12.18.3
kernel 5.7.8-200.fc32.x86_64 on fedora32

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
