### ISSUE TITLE
fix security vulnerabilities found by snyk

### ISSUE THREAD

**Issue by bboydflo** [sass/node-sass#2960]
Thanks for an awesome helpful package.

Here is a link of security vulnerabilities found by snyk: [https://snyk.io/test/npm/node-sass/4.14.1](https://snyk.io/test/npm/node-sass/4.14.1) not sure anything is actually insecure but it would be nice to get rid of these.

<img width="533" alt="Screenshot 2020-08-26 at 15 28 29" src="https://user-images.githubusercontent.com/2241459/91309989-9dbf2980-e7b1-11ea-9b86-bee4f5878e5a.png">

**Comment by nschonni** [comment]
Duplicate of a bunch of issues
