### ISSUE TITLE
node-sass does not compile when used with webpack NPM script

### ISSUE THREAD

**Issue by da-kicks-87** [sass/node-sass#2966]
I am trying to compile sass and javascript in one NPM script command.  I want to use node-sass and webkit

In npm's package.json file i have this script defined:

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "scss": "node-sass --watch src/scss/master.scss dist/css/master-compiled-min.css --output-style compressed",
    "start": "webpack --config webpack.config.js && node-sass --watch src/scss/master.scss dist/css/master-compiled-min.css --output-style compressed"
  }, 

```
From command line I am able to run the **start** script. I don't get error message. It compiles the js with webpack but it doesn't compile / watch for changes in sass.  

Anyone know why this happens?

- NPM version (`npm -v`): 6.14.8

- Node version (`node -v`): v12.10.0

- Node Process (`node -p process.versions`): {
  node: '12.10.0',
  v8: '7.6.303.29-node.16',
  uv: '1.31.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '4',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1c',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}

- Node Platform (`node -p process.platform`): win32

- Node architecture (`node -p process.arch`): x64

- node-sass version (`node -p "require('node-sass').info"`): 
node-sass       4.14.1  (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):
node-sass@4.14.1

**Comment by nschonni** [comment]
Hey, I think this is a better question for StakeOverflow
