### ISSUE TITLE
Issue in coming TFS, using this sass

### ISSUE THREAD

**Issue by RehmanaliMomin** [sass/node-sass#2968]
ERROR in ./src/styles.scss
  Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
  ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
EXEC : error : Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72) [I:\Agent-Win-I\_work\916\s\src\Web\SAT.Web.csproj]
  For more information on which environments are supported please see:
  https://github.com/sass/node-sass/releases/tag/v4.9.4

**Comment by nschonni** [comment]
Please follow the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
