### ISSUE TITLE
404 upon npm install, v4.14.1/linux-arm64-83_binding.node

### ISSUE THREAD

**Issue by riccardolardi** [sass/node-sass#2969]
Getting `Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-83_binding.node": HTTP error 404 Not Found` - upon `npm i node-sass` on a Raspberry Pi 4 running Ubuntu Server 20 latest (openbox). Is this pointing to a non existing release?

**Comment by xzyfer** [comment]
ARM is not supported by node-sass. You can try not install node-sass --force to compile the binary locally but you'll need the C++ build chain. I suggest try dart sass.

**Comment by riccardolardi** [comment]
Weird thing is the other day I installed it on Raspian OS which worked fine? It now failed on Ubuntu Server though. How come?
