### ISSUE TITLE
Can't find bindings for "Linux 64-bit with Node.js 14.x"

### ISSUE THREAD

**Issue by vegerot** [sass/node-sass#2992]
- NPM version (`npm -v`): 6.14.8
- Node version (`node -v`): v14.13.0 (https://hub.docker.com/_/node node:latest)
- Node Process (`node -p process.versions`): 

```json

{
  node: '14.13.0',
  v8: '8.4.371.19-node.16',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.2',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}

```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): unknown.  Assuming
```
node-sass       4.14.1  (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): `└── node-sass@4.14.1`

I am building my code using a [GitLab Runner](https://docs.gitlab.com/runner/), with the Docker executer using `node:latest`.  I don't have the ability to run the commands listed ^ on the GitLab Runner, so I just ran the commands with `docker run -t -i node:latest bash`.

Every so often, when building `node-sass` I get the following errors: 
```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /builds/wingops/a/b/node_modules/node-sass/vendor/linux-x64-83/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x
Found bindings for the following environments:
  - Linux/musl 64-bit with Node.js 14.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
```
.  I have seen similar issues while researching, but all the solutions involve running `npm rebuild node-sass`, which cannot be done.

Is there a way to get `node-sass` to compile with `node:latest`?  If not, is there a fork of `node:latest` with the `musl` bindings I need?

**Comment by nschonni** [comment]
No, you can't build one platform (Debian for the `latest` tag) then pass the `node_modules` to an Alpine container to execute. You'd need to build on `node:alpine` (or a more specific tag) if you're passing the results one to an alpine image after

**Comment by vegerot** [comment]
Thanks!  I don't think I'm doing that.  The GitLab Runner is running on an Ubuntu Server machine, and the runners are based off ubuntu/debian too.

**Comment by nschonni** [comment]
> Linux/musl 64-bit with Node.js 14.x

Sorry, I have that reversed. Somewhere you are sharing the node_modules from an Alpine image and trying to run it on your Debian machine

**Comment by vegerot** [comment]
Interesting.  And how did you come to that conclusion?  Are the musl headers only in Alpine by default?  How could this be if I'm running `node:latest` inside GitLab Runner inside Ubuntu server?

**Comment by nschonni** [comment]
My guess is based on the error message saying it found an Alpine binary when it went to install. We can't really help you troubleshoot your individual CI setup though
