### ISSUE TITLE
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (88)

### ISSUE THREAD

**Issue by jledgett** [sass/node-sass#3010]
- NPM version (`npm -v`): 6.14.8
- Node version (`node -v`): v15.0.1
- Node Process (`node -p process.versions`): {
  node: '15.0.1',
  v8: '8.6.395.17-node.15',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): N/A (since it won't install)
- npm node-sass versions (`npm ls node-sass`): N/A (since it won't install)

What are the release plans for support of Node.js 15+. ?

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/2965
