### ISSUE TITLE
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.

### ISSUE THREAD

**Issue by krishnaTORQUE** [sass/node-sass#3016]
- NPM version (`npm -v`): 6.14.8
- Node version (`node -v`): 14.15.0
- Node Process (`node -p process.versions`): 
```
{
  node: '14.15.0',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	5.0.0	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): `-- node-sass@5.0.0 

**ERROR:**
`Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.`

Using `create-react-app`with bootstrap `v4.5.3` after update to `node-sass v5` I got this error.

**Comment by nschonni** [comment]
Yes, that's how semantic versioning works https://docs.npmjs.com/about-semantic-versioning
The v5 version won't match anything that depends on `^4`
You shouldn't need to manually updated `node-sass` unless you're looking to support Node 15. That is really the only change introduced https://github.com/sass/node-sass/releases/tag/v5.0.0

**Comment by krishnaTORQUE** [comment]
> Yes, that's how semantic versioning works https://docs.npmjs.com/about-semantic-versioning
> The v5 version won't match anything that depends on `^4`
> You shouldn't need to manually updated `node-sass` unless you're looking to support Node 15. That is really the only change introduced https://github.com/sass/node-sass/releases/tag/v5.0.0

alright I got it but now what I am suppose to do? downgrade `node-sass` or is there any thing else ?

**Comment by xzyfer** [comment]
npm install node-sass@4

**Comment by infabo** [comment]
How to find out which package depends on node-sass ^4? Nothing to find in package-lock.json

**Comment by JackHowa** [comment]
https://github.com/facebook/create-react-app/milestone/79
