### ISSUE TITLE
Missing 4.9.3 linux-x64-72 binary

### ISSUE THREAD

**Issue by EloyID** [sass/node-sass#3018]
- NPM version (`npm -v`): 6.9.0
- Node version (`node -v`): 10.16.3
- Node Process (`node -p process.versions`): 
{ http_parser: '2.8.0',
  node: '10.16.3',
  v8: '6.8.275.32-node.54',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.39.2',
  napi: '4',
  openssl: '1.1.1c',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019a' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): throw new Error(errors.missingBinary());
- npm node-sass versions (`npm ls node-sass`):
LFG@2.0.1 /home/apollinaire/PlatformCode
└── node-sass@4.10.0 

Hello,
I'm trying to install meteor 1.10.2 who installs package fourseven:scss@4.10.0 who installs node-sass v4.9.3. I get the message

```While loading package fourseven:scss@4.10.0:
error: Command failed: /home/apollinaire/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild
--update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g. 

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via
```
**If I go to https://github.com/sass/node-sass/releases?after=v4.12.0 in the 4.9.3 section, there is no 4.9.3 linux-x64-72**
Do you know why, and how can this be solved ?

Thank you in advance !

**Comment by nschonni** [comment]
Node 12 isn't supported by node-sass 4.9 https://github.com/sass/node-sass#node-version-support-policy

**Comment by EloyID** [comment]
Sorry, I'm not very familiar with node etc, but the node version I have is 
Node version (node -v): 10.16.3
Why have you tagged it ad node 12? Maybe it's me who haven't understood well :) 
Thanks for you help

**Comment by nschonni** [comment]
The "72" means it's running in a Node 12 environment. This is likely to do we meteor, but not something we can debug for you
