### ISSUE TITLE
Docs seem to show wrong way to use built-in modules

### ISSUE THREAD

**Issue by jeremygottfried** [sass/node-sass#3020]
In the sass docs, it seems to show the wrong way to use built-in modules.

One example is the docs demonstrate the `alpha` method like this:
https://sass-lang.com/documentation/modules/color#alpha
```scss
@debug color.alpha(#e1d7d2); // 1
```

That causes the following error 
```sh
SassError: Invalid CSS after "color": expected expression (e.g. 1px, bold), was ".alpha(#e1d7d2)"
```
When I remove the color keyword and just use the method name it works:
```scss
@debug alpha(#e1d7d2); // 1

```

It seems like the docs should be updated to remove module name prefix when demonstrating how to use built-in modules. 

If there is something I am missing, maybe docs should be updated to explain when it's appropriate to use the module name?

node-sass version: "^4.14.1"

**Comment by nschonni** [comment]
As per the top of that page, those are only supported in dart-sass
![image](https://user-images.githubusercontent.com/1297909/97944658-2ed2f380-1d53-11eb-93e4-c902b08e1749.png)

**Comment by jeremygottfried** [comment]
@nschonni That is very confusing, because the methods themselves are not only supported in dart-sass. If you are looking for documentation on how to use these methods outside of dart-sass, then the docs could easily lead you astray.

**Comment by jeremygottfried** [comment]
@nschonni could you update so that this line is automatically present and not revealed by a dropdown?

"Only Dart Sass currently supports loading built-in modules with @use. Users of other implementations must call functions using their global names instead."

**Comment by nschonni** [comment]
You'd need to raise that over on the website repo https://github.com/sass/sass-site/
