### ISSUE TITLE
Missing binary when installing v5 on Windows 10: win32-ia32-79_binding.node 

### ISSUE THREAD

**Issue by NoelAbrahams** [sass/node-sass#3030]
- NPM version (`npm -v`): 6.13.7
- Node version (`node -v`): 13.11.0
- OS: Windows 10 x64
- Node-Sass (trying to install) v.5.0.0

**Description of the problem**

Running `C:\foo>npm install node-sass -g`  produced the following error:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\bar\AppData\Roaming\npm\node-sass -> C:\Users\bar\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass

> node-sass@5.0.0 install C:\Users\bar\AppData\Roaming\npm\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/win32-ia32-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/win32-ia32-79_binding.node":

HTTP error 404 Not Found
```

I've checked the release page and the binary `win32-ia32-79_binding.node` is not on the list. Any chance of adding support for this?

We really don't want to ask everyone to install Python.

Thanks.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
