### ISSUE TITLE
能否支持一下arm架构呢？

### ISSUE THREAD

**Issue by ghost** [sass/node-sass#3036]
我的arm架构服务器在npm的时候无法下载到sass，能否在后面版本考虑一下arm架构的机子

**Comment by Dream-456** [comment]
Error message as folllow:
"Cannot download linux-arm64-64_binding.node from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-arm64-64_binding.node"
Can you please provide an ARM version? or when it is available?thinks

**Comment by nschonni** [comment]
ARM is not currently supported, there are a bunch of previous threads on this
