### ISSUE TITLE
Issue with npm install node-sass@4.13.1

### ISSUE THREAD

**Issue by michaeljin89757** [sass/node-sass#3037]
When running command npm install node-sass@4.13.1 on VS Code, the installation was trying to get build **v4.13.1/win32-x64-83_binding.node** which does not exist.  Fact is only build **win32-x64-79** is there. 
![image](https://user-images.githubusercontent.com/54333536/101131639-9a54fd00-3640-11eb-9dc3-9bede68df7f7.png)

**Comment by derdeka** [comment]
+1 same here

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
