### ISSUE TITLE
Release for FreeBSD with node > 13

### ISSUE THREAD

**Issue by fschulze** [sass/node-sass#3045]
What is needed to get releases for node 15 and or 14? Support for node 12 will be dropped by the end of the year and 13 isn't available via ``pkg``. Is it *just* an updated CI file, or is there something bigger blocking this?

Alternatively, is there a way to install without binary releases from source?

**Comment by fschulze** [comment]
Using ``npm-force-resolutions`` and a force updated ``node-gyp`` I'm able to compile everything, but it takes quite a while. The force update might only be necessary for me because of other packages which declare a pin for ``node-gyp``.

**Comment by saper** [comment]
I have uploaded binaries for node-sass 5.0.0 (node 10,12,14 and 15).
