### ISSUE TITLE
requests library uses the SHA1 hashing algorithm by default

### ISSUE THREAD

**Issue by iadibar** [sass/node-sass#3050]
- NPM version (`npm -v`):6.11.3
- Node version (`node -v`):10.17.0
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

Im using `node-sass` that dependent on `request version ^2.88.0`(inside package-lock.json).
when I scan my app (with Veracode sca) I getting Insecure Cipher from `request`,
They said : `requests uses an insecure cipher. The library uses the SHA1 hashing algorithm by default which was shown to be compromised with the SHA1 shatter attack. The library also does not offer any alternate hashing algorithm.`

What do you suggest to solve this problem?

**screen shout from Veracode sca security scan:**

![Image 22-12-2020 at 9 04](https://user-images.githubusercontent.com/36728277/102859519-b1635f80-4434-11eb-84c2-7db6dd512c83.jpg)

**Comment by saper** [comment]
We use the library to download the binding file. If you provide the binding file by some other, more secure means, you are not affected by this.
