### ISSUE TITLE
linux-arm64-64_binding.node is unavailable

### ISSUE THREAD

**Issue by Dream-456** [sass/node-sass#3052]
Error message as follow:
"Cannot download linux-arm64-64_binding.node from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-arm64-64_binding.node"
Can you please provide an ARM version? or when it is available?thinks

**Comment by saper** [comment]
It is not available, but one can try to build one for itself.

**Comment by Dream-456** [comment]
I have buid it,but when i use "npm run buid",it also to download from github

**Comment by Dream-456** [comment]
I have build it on ARM platform,and  also passed the test
