### ISSUE TITLE
node-sass ignores engines config in package.json?

### ISSUE THREAD

**Issue by yosiasz** [sass/node-sass#3054]
Greetings,

we have both angularJs and angular applications. We need to go between different versions of nodejs depending on app.
angularjs apps we use node 12.15.0 and for angular applications we use LTS nodejs 14.15.3.

we leverage nvm to do that but it get tiring so we use the engines setting in package.json.

```
  "engines": {
    "node": "12.15.0",
    "npm": "6.13.4"
  }
```
node-sass seems to be the only module that has issues when we go between nodejs versions with this engines config. It forces us to use 

```
nvm use 12.15.0

or

nvm use 14.15.3
```

it is as if node-sass ignores the engines setting?

- NPM version (`npm -v`): 6.13.4
- Node version (`node -v`):v12.15.0
- Node Process (`node -p process.versions`):
```
{
  node: '12.15.0',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.13.1  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`):

`-- node-sass@4.13.1

**Comment by nschonni** [comment]
Engines is to declare what Node version **your** package is compatible with https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines
This has nothing to do with how native addons are installed with NPM
