### ISSUE TITLE
Node Sass Unsupported Runtime (80)

### ISSUE THREAD

**Issue by PixelDev0** [sass/node-sass#3059]
- NPM version (`npm -v`):
`7.4.0`
- Node version (`node -v`):
`v15.6.0`
- Node Process (`node -p process.versions`):
`{
  node: '15.6.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.0',
  icu: '68.1',
  tz: '2020b',
  unicode: '13.0'
}`
- Node Platform (`node -p process.platform`):
`win32`
- Node architecture (`node -p process.arch`):
`x64`
- node-sass version (`node -p "require('node-sass').info"`):
`node-sass       5.0.0   (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]`
- npm node-sass versions (`npm ls node-sass`):

When trying to start my program, I am getting the following error:
`
Uncaught exception:
Error: Node Sass does not yet support your current environment: Windows 32-bit with Unsupported runtime (80)
`

**Comment by nschonni** [comment]
"80" isn't a Node module version https://github.com/sass/node-sass#node-version-support-policy
It's possible it's an Electron version (running through VS Code or another Electron based app), but we don't support those runtimes

**Comment by PixelDev0** [comment]
How would I be able to fix the issue then?
