### ISSUE TITLE
 FreeBSD issue with tag 5.0.0 and missing bindings

### ISSUE THREAD

**Issue by Martinfx** [sass/node-sass#3060]
Release v5.0.0 does not contain freebsd-x64-88_binding.node again with node 15.  :-( !

You can check your repo:
https://github.com/sass/node-sass/releases/tag/v5.0.0

@saper @nschonni

**Comment by moracca** [comment]
Wondering this as well.  Is the FreeBSD release strategy different than the other supported platforms?

**Comment by moracca** [comment]
[freebsd-x64-88_binding.tar.gz](https://github.com/sass/node-sass/files/6120509/freebsd-x64-88_binding.tar.gz)

Here's the result of building on freebsd w/ node 15.  Hope it helps someone

**Comment by Martinfx** [comment]
@moracca thx

**Comment by saper** [comment]
I have added the missing binaries for 5.0.0.
