### ISSUE TITLE
make: *** No rule to make target `Release/obj.target/libsass/src/libsass/src/ast.o', needed by `Release/obj.target/src/sass.a'.  Stop.

### ISSUE THREAD

**Issue by jimjiyn** [sass/node-sass#3061]
Forgive my pool Engilish
when I built node-sass-v4.2.0 on arm64，it notes
`gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/node-sass/node-sass-4.2.0/build'
make: *** No rule to make target `Release/obj.target/libsass/src/libsass/src/ast.o', needed by `Release/obj.target/src/sass.a'.  Stop.
make: Leaving directory `/home/node-sass/node-sass-4.2.0/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/node-sass/node-sass-4.2.0/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.14.0-115.el7a.0.1.aarch64
gyp ERR! command "/usr/bin/node" "/home/node-sass/node-sass-4.2.0/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/node-sass/node-sass-4.2.0
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1`
Does version 4.2.0 not support arm64，or some other problem?
And I found verison 4.3.0  does not occur this problem

**Comment by nschonni** [comment]
No, ARM isn't currently supported

**Comment by ECJ222** [comment]
is there any workaround for this?
