### ISSUE TITLE
Node-sass build error MSB8013

### ISSUE THREAD

**Issue by Torokhov** [sass/node-sass#3074]
there was a problem assembling the nodier sass. error MSB8013: This project does not contain a combination of Release | Win32 configuration and framework.

Reinstalling node-sass, node-gyp, msbuild, clearing the npm cache did not help.

NPM version: npm@6.14.11
Node version:  node@v14.16.0
Node-sass version: node-sass@4.13.1
Node-gyp version: node-gyp@7.1.2
Node process: 
```
{                              
  node: '14.16.0',
  v8: '8.4.371.19-node.18',    
  uv: '1.40.0',                
  zlib: '1.2.11',              
  brotli: '1.0.9',             
  ares: '1.16.1',              
  modules: '83',               
  nghttp2: '1.41.0',           
  napi: '7',                   
  llhttp: '2.1.3',             
  openssl: '1.1.1j',           
  cldr: '37.0',                
  icu: '67.1',                 
  tz: '2020a',                 
  unicode: '13.0'              
}

```
Node Platform: win32
Node architecture: x64
msbuild 2017

>  node-sass@4.13.1 postinstall C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js
> 
> Building: C:\Program Files\nodejs\node.exe C:\Users\olegtorokhov\Projects\billy\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [
> gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library='
> gyp verb cli ]
> gyp info using node-gyp@3.8.0
> gyp info using node@14.16.0 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "C:\Users\olegtorokhov\.windows-build-tools\python27\python.exe" in the PATH
> gyp verb `which` succeeded C:\Users\olegtorokhov\.windows-build-tools\python27\python.exe C:\Users\olegtorokhov\.windows-build-tools\python27\python.exe
> gyp verb check python version `C:\Users\olegtorokhov\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.15
> gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
> gyp verb get node dir no --target version specified, falling back to host node version: 14.16.0
> gyp verb command install [ '14.16.0' ]
> gyp verb install input version string "14.16.0"
> gyp verb install installing version: 14.16.0
> gyp verb install --ensure was passed, so won't reinstall if already installed
> gyp verb install version is already installed, need to check "installVersion"
> gyp verb got "installVersion" 9
> gyp verb needs "installVersion" 9
> gyp verb install version is good
> gyp verb get node dir target node version installed: 14.16.0
> gyp verb build dir attempting to create "build" dir: C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build
> gyp verb build dir "build" dir needed to be created? C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build
> gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
> gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
> gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
> gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
> gyp verb find vs2017   - Using this installation with Windows 10 SDK
> gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
> gyp verb build/config.gypi creating config file
> gyp verb build/config.gypi writing out config file: C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\config.gypi
> gyp verb config.gypi checking for gypi file: C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\config.gypi
> gyp verb common.gypi checking for gypi file: C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\common.gypi
> gyp verb gyp gyp format was not specified; forcing "msvs"
> gyp info spawn C:\Users\olegtorokhov\.windows-build-tools\python27\python.exe
> gyp info spawn args [
> gyp info spawn args   'C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'msvs',
> gyp info spawn args   '-G',
> gyp info spawn args   'msvs_version=2015',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\gulp-sass\\node_modules\\node-sass\\build\\config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\node-gyp\\addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\olegtorokhov\\.node-gyp\\14.16.0\\include\\node\\common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=C:\\Users\\olegtorokhov\\.node-gyp\\14.16.0',
> gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\node-gyp',
> gyp info spawn args   '-Dnode_lib_file=C:\\Users\\olegtorokhov\\.node-gyp\\14.16.0\\<(target_arch)\\node.lib',
> gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\gulp-sass\\node_modules\\node-sass',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'C:\\Users\\olegtorokhov\\Projects\\billy\\node_modules\\gulp-sass\\node_modules\\node-sass\\build',
> gyp info spawn args   '-Goutput_dir=.'
> gyp info spawn args ]
> gyp verb command build []
> gyp verb build type Release
> gyp verb architecture x64
> gyp verb node dev dir C:\Users\olegtorokhov\.node-gyp\14.16.0
> gyp verb found first Solution file build/binding.sln
> gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
> gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
> gyp info spawn args [
> gyp info spawn args   'build/binding.sln',
> gyp info spawn args   '/nologo',
> gyp info spawn args   '/p:Configuration=Release;Platform=x64'
> gyp info spawn args ]
> Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "/m".
> Сборка начата 25.03.2021 10:15:25.
> Проект "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" в узле 1 (целевые объекты по умолчанию)
> .
> ValidateSolutionConfiguration:
>   Создание конфигурации решения "Release|x64".
> Проект "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" (1) выполняет сборку "C:\Users\olegtoro
> khov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) в узле 1 (целевые объекты по умолчанию).
> Проект "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) выполняет сборку "C:\U
> sers\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj" (3) в узле 1 (целевые объекты по умолчанию)
> .
> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(358,5): error MSB8013: этот проект
>  не содержит сочетание конфигурации и платформы Release|Win32. [C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\bu
> ild\src\libsass.vcxproj]
> Сборка проекта "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj" завершена (целевые объе
> кты по умолчанию) с ошибкой.
> 
> Сборка проекта "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" завершена (целевые
>  объекты по умолчанию) с ошибкой.
> 
> Сборка проекта "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" завершена (целевые объекты по у
> молчанию) с ошибкой.
> 
> 
> Ошибка сборки.
> 
> "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln" (целевой объект по умолчанию) (1) ->
> "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (целевой объект по умолчанию) (2)
>  ->
> "C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj" (целевой объект по умолчанию) (3) ->
> (PrepareForBuild конечный объект) ->
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(358,5): error MSB8013: этот прое
> кт не содержит сочетание конфигурации и платформы Release|Win32. [C:\Users\olegtorokhov\Projects\billy\node_modules\gulp-sass\node_modules\node-sass\
> build\src\libsass.vcxproj]
> 
>     Предупреждений: 0
>     Ошибок: 1

**Comment by saper** [comment]
v4.13.1 is too old for node 14. Can you tell your project to use v5.0.0?

**Comment by Torokhov** [comment]
Я могу. Но при установке последней версии тщву-ыфыы я все равно получаю эту ошибку. Я пробовал менять версии ноды, версии ноде-сасс - это не помогает

**Comment by Torokhov** [comment]
I can. But when I install the latest version, I still get this error. I tried changing node versions, node-sass versions - it doesn't help

**Comment by saper** [comment]
Can you post your log when this happens with 5.0.0 please?

**Comment by Torokhov** [comment]
The log is no different from the one above. The error is the same. The problem was solved by installing Microsoft Build Tools 2019. Before that, there was a 2017 version. Apparently the problem was this
