### ISSUE TITLE
Failed to compile material design scss file

### ISSUE THREAD

**Issue by nomi4** [sass/node-sass#3080]
Facing the following error while using the button component in the app.scss:

```
Failed to compile.

./src/app.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/app.scss)
SassError: Invalid CSS after "@include button": expected 1 selector or at-rule, was ".core-styles;"
        on line 3 of src/app.scss
>> @include button.core-styles;

```
- NPM version (`npm -v`): 6.14.11 but tried with 7.8.0
- Node version (`node -v`): 12.18.2
- Node Process (`node -p process.versions`):{
  node: '12.18.2',
  v8: '7.8.279.23-node.39',
  uv: '1.38.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '72',
  nghttp2: '1.41.0',       
  napi: '6',
  llhttp: '2.0.4',
  http_parser: '2.9.3',    
  openssl: '1.1.1g',       
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- npm node-sass versions (`npm ls node-sass`): node-sass@5.0.0

**Comment by saper** [comment]
Can you post the `src/app.scss` file?

**Comment by nomi4** [comment]
Sure here it is:

`@use '@material/button/mdc-button';
@use '@material/button';

.foo-button {
  @include button.container-fill-color(darksalmon);
}`

**Comment by saper** [comment]
libsass 3.5.5 we are using does not support "new module system" and **`@use`** - see https://github.com/sass/libsass/issues/3051 

You need to use dart-sass for that.
