### ISSUE TITLE
Fresh install broken on linux x64: Document and/or Fix

### ISSUE THREAD

**Issue by byteit101** [sass/node-sass#3084]
- NPM version (`npm -v`): 7.6.3
- Node version (`node -v`): v12.13.1
- Node Process (`node -p process.versions`):{
  node: '12.13.1',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 
node-sass	5.0.0	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): node-sass@5.0.0

Upon a fresh install:
```
$ node_modules/node-sass/bin/node-sass
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '$MY_PROJECT/node_modules/node-sass/vendor'
(snippped)
```
I saw that I might need to rebuild things, but that didn't do anything:

```
$ npm rebuild node-sass     
rebuilt dependencies successfully
$ node_modules/node-sass/bin/node-sass
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '$MY_PROJECT/node_modules/node-sass/vendor'
(snippped)
```

After much searching around issues closed because of yarn/gulp/etc that I wasn't using, I found no documentation on what to do until I looked at the release page and attempted to manually download it:

```
$ mkdir -p  node_modules/node-sass/vendor/linux-x64-72
$ cd $_
$ wget https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-72_binding.node -O binding.node
$ cd -
$ node_modules/node-sass/bin/node-sass
Provide a Sass file to render
```

Hurray!

However, the new user experience is terrible, and there is no documentation on what to do when it goes wrong, as it always did on my machine (multiple versions and fresh folders).

# To manually fix this error

 1. Look up your node module version on the table on https://github.com/sass/node-sass
 2. Then go to the github downloads page for the version of node-css bindings for your OS/architecture/module
 3. Place this in `node_modules/node-sass/vendor/$OS-$ARCH-$MODULE/binding.node`

**Comment by saper** [comment]
Something went wrong with your "fresh install" stage. Could share a log file of that?

**Comment by byteit101** [comment]
Which log file? I don't see any in the node_modules folder

Or do you mean this output?
```
$ npm install node-sass         
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 195 packages, and audited 196 packages in 11s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

As for platform,  Debian 10 x64. Any further details  you would like?

**Comment by Poyoman39** [comment]
Same problem here after npm ci. For some reason `node_modules/node-sass/vendor` is not created. 
`npm rebuild node-sass` fix the issue ... but anyway npm ci should work at the first time

**Comment by saper** [comment]
> As for platform, Debian 10 x64. Any further details you would like?

Compiler version?

**Comment by byteit101** [comment]
Assuming GCC:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
```

**Comment by saper** [comment]
Do you have `node_modules` somewhere below the directory you are currently in?

**Comment by byteit101** [comment]
```

**Comment by saper** [comment]
Can you increase verbosity of npm install?

**Comment by saper** [comment]
You say 

    node -p "require('node-sass').info

is working. Where the module is coming from? Installed globally, maybe?

**Comment by byteit101** [comment]
> Where the module is coming from?

I fixed it before running it. :smiley:  Not fixing it gives the original error.

However, I've found the cause of this: [disabled](https://snyk.io/blog/ten-npm-security-best-practices/) [scripts](https://www.nerdycode.com/prevent-npm-executing-scripts-security/) [for](https://blog.usejournal.com/12-strange-things-that-can-happen-after-installing-an-npm-package-45de7fbf39f0?gi=9f875c69bc54) [security](https://www.zdnet.com/article/malicious-npm-packages-caught-installing-remote-access-trojans/) [reasons](https://blog.bitsrc.io/malicious-npm-development-kit-a02401e6537e?gi=6cbb19ef30be) in npmrc. Should be documented on that being a possibility and direct people to the manual install instructions. Enabling scripts allows both rebuilding and the initial install to work.

**Comment by nschonni** [comment]
Thanks, that is in our TROUBLESHOOTING.md guide https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root but feel free to suggest some updated text

**Comment by byteit101** [comment]
>  some updated text
How about on the error message pointing people to that guide? that guide was ungoogleable from the error messages
