### ISSUE TITLE
Cannot Find module 'mkdirp'

### ISSUE THREAD

**Issue by karneaud** [sass/node-sass#3085]
My issue is based on my [stackoverflow](https://stackoverflow.com/questions/66994590/node-sass-error-cannot-find-module-mkdirp) post

My environment has been updated to as follows:-

**- Node: v14.0.0
- Yarn: 1.22.10
- OS: Linux homestead 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-** 

I cannot seem to isolate the issue and trying to install one by one seems to encounter other issues to resolve. Is this a Node version thing?

**Comment by ryuran** [comment]
It seems the install script try to be executed before the complete node_modules install.
Some required modules are not yet installed when install.js run.

**Comment by nschonni** [comment]
It's possible Yarn isn't waiting for all the dependencies to be installed before executing the install script. Unfortunately, it's not something we can address (if this wasn't something machine/time specific)
