### ISSUE TITLE
Ubuntu 20.04 Installation Failure

### ISSUE THREAD

**Issue by tomleo** [sass/node-sass#3098]
- NPM version (`npm -v`): 7.11.1
- Node version (`node -v`): v16.0.0
- Node Process (`node -p process.versions`):
```
{
  node: '16.0.0',
  v8: '9.0.257.17-node.10',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.0',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): (can't install, so this throws a `MODULE_NOT_FOUND` error)
- npm node-sass versions (`npm ls node-sass`): same as above

----

Installing node-sass on Ubuntu 20.04.2 LTS results in the following error in npm:

```
npm ERR! make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/tom/my-project/webpack/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.8.0-50-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/home/tom/my-project/webpack/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/tom/my-project/webpack/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.0.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

I know `python` isn't bound to anything in Ubuntu 20.04, so I did the following: `npm config set python /usr/bin/python2.7` but got the same result.

Things I've tried so far for `python2.7` & `node-sass 4.11` (using `npm config set python /usr/bin/python2.7`)
1. `npm install node-sass@4.11.0`
2. `npm install --unsafe-perm node-sass@4.11.0` 
3. `sudo npm install node-sass@4.11.0`
4. `sudo npm install --unsafe-perm node-sass@4.11.0`

This I've tried so far for `python3.8` & `node-sass 5.0.0` (using `npm config set python /usr/bin/python3.8`)
1. `npm install node-sass@5.0.0` 
2. `npm install --unsafe-perm node-sass@5.0.0`
3. `sudo npm install node-sass@5.0.0` 
4. `sudo npm --unsafe-perm install node-sass@5.0.0`

I'm really grasping at straws here, I have no idea why this isn't working, any help would be appreciated.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/3077
