### ISSUE TITLE
Node 16 support with 5.x

### ISSUE THREAD

**Issue by maxburke** [sass/node-sass#3106]
Hi,

I noticed that Node 16 was released as version 6.0. Unfortunately a new major version seems to break all the other dependencies we have that require node-sass 4.x or 5.x. 

Is it possible to have this backported to be a patch on top of 5.x? Or released also as 5.1?

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy

**Comment by maxburke** [comment]
@nschonni I see that but unfortunately that doesn't help address the knock-on ecosystem breakage brought on by a new major version! 

The original node-sass + Node 16 issue mentions a 5.1 version as well: https://github.com/sass/node-sass/issues/3077

**Comment by maxburke** [comment]
For what it's worth the reason I am asking because node 15 isn't available through normal channels anymore with the release of node-16.1, and node 14 doesn't work on M1 Macbooks so downgrading to that version isn't possible.

cc @xzyfer who closed a similar issue.

**Comment by xzyfer** [comment]
Odd numbered node versions are short live releases. You'll have better luck
with node 14 which is an LTS release.

**Comment by maxburke** [comment]
@xzyfer But node 14 doesn't work with apple's m1 processor; node 15 was the first version to support it.

**Comment by xzyfer** [comment]
That's an interesting call out. Looks like there are some ways to get node < 15 working via Rosetta bit there are quirks. I can take a look at what our options are here. 

Out of curiosity are you able to confrim that node-sass did previously work on Apple M1 with Node 15? It was our impression that node-sass wouldn't work on Apple M1.

**Comment by maxburke** [comment]
@xzyfer Yup, it worked fine until I did a `brew upgrade` yesterday and had my node-15 replaced with node-16.

**Comment by xzyfer** [comment]
Out of curiosity, are there any community packages that are being particularly problematic? I know gulp-sass doesn't support node-sass 6 yet for example.

**Comment by maxburke** [comment]
@xzyfer The issue is that sass-loader 10 requires node-sass 4 or 5, and react-scripts/create-react-app right now depends on sass-loader 10. There's an issue open for react-scripts to support sass-loader but it's open (https://github.com/facebook/create-react-app/issues/10944) 

So the resolution I'm looking at in order to get our react app working for local development is either to eject the react webpack config and tweak versions myself, or build node-15 locally from source.

**Comment by xzyfer** [comment]
Thanks. This isn't likely to happen for a couple days due to my schedule.
We'll keep an eye on the linked issue to see if this is still needed over
the weekend.

**Comment by maxburke** [comment]
Thank you for looking into this!

**Comment by maxburke** [comment]
Any further updates? Is it possible to have a 5.x release issued with Node 16 support?

**Comment by maxburke** [comment]
Four weeks later; is it possible to get a release of node-sass 5.x with node 16 support?

**Comment by maxburke** [comment]
@nschonni / @xzyfer ?

**Comment by maxburke** [comment]
@nschonni / @xzyfer can you please update this ticket?

**Comment by phavor** [comment]
Seems like the support for v16 hasn't come through yet?

**Comment by xzyfer** [comment]
Seeing if this possible in https://github.com/sass/node-sass/pull/3136. 

I'm concerned given the recent security updates we've applied to the main line branch that this will get unmaintainable very quickly.

**Comment by TheBrenny** [comment]
I'm curious to learn more about what broke with the changes? Having a look at the files changed, it really only looks like environment stuff has changed, but I can't see anything which points out as an "uh oh" to me...

Just curious! 😅

**Comment by AjiTae** [comment]
Just hard-patch dependencies to node-sass v6 via yarn resolutions or the like. There is no major change interface-wise anyway.)

**Comment by alshdavid** [comment]
Installing node-sass `^5.0.0` on Node 16 fails. With node 16 being in LTS now this is causing a bit of grief in our teams trying to update.

Any tips on how to get it working?

**Comment by richardeschloss** [comment]
I had to install node-sass v6 with node 14.

**Comment by xzyfer** [comment]
Unfortunately this has proven to difficult to achieve in a sustainable way due to some of our dependencies dropping support for older Node versions whilst patching security issues.
