### ISSUE TITLE
yarn build shows deprication warnings

### ISSUE THREAD

**Issue by adamcooper1386** [sass/node-sass#3107]
- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

Did a fresh install of node-sass using yarn and it seems like there are unhandled deprication warnings.

<img width="909" alt="Screen Shot 2021-05-12 at 6 28 39 PM" src="https://user-images.githubusercontent.com/38062975/118064576-238b0100-b350-11eb-9328-c760beb67c64.png">

**Comment by nschonni** [comment]
Tracked in https://github.com/sass/node-sass/issues/2851
