### ISSUE TITLE
node-sass deprecation results in broken compilation on latest sass features coming with angular material design

### ISSUE THREAD

**Issue by MagicPoulp** [sass/node-sass#3110]
- NPM version (`npm -v`):
6.14.13
- Node version (`node -v`):
14.17.0
- Node Process (`node -p process.versions`):
{
  node: '14.17.0',
  v8: '8.4.371.23-node.63',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}

- Node Platform (`node -p process.platform`):
linux
- Node architecture (`node -p process.arch`):
 x64
- node-sass version (`node -p "require('node-sass').info"`):
node -p "require('node-sass').info"
node-sass	6.0.0	(Wrapper)	[JavaScript]
- npm node-sass versions (`npm ls node-sass`):
/home/thierry/sass
└── node-sass@6.0.0 

BUG

  "dependencies": {
    "@angular/cdk": "^12.0.0",
    "@angular/core": "^12.0.0",
    "@angular/material": "^12.0.0",
    "node-sass": "^6.0.0",
    "node-sass-tilde-importer": "^1.0.2"
  }

node-sass style.scss --importer=node_modules/node-sass-tilde-importer -o dist

It will be error of syntax on the core() below copied form the material design doc.
style.scss:
@use '~@angular/material' as mat;
@import '~@angular/material/theming';
@include mat.core();

I know why
the libsass delivered via npm in node-sass has a too old version.
And even if it was updated, it is officially deprecated by the sass team.
https://sass-lang.com/blog/libsass-is-deprecated

Maybe document in the README that it is deprecated?

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-sass

**Comment by MagicPoulp** [comment]
thanks :)
