### ISSUE TITLE
Not Working on Arch Linux, it was working on Ubuntu 20.04 

### ISSUE THREAD

**Issue by Burnsedia** [sass/node-sass#3112]
- NPM version (`npm -v`): 4
- Node version (`node -v`): 16
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`): Linux 64 bit
- Node architecture (`node -p process.arch`): x86-64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`): 4.4.4

**Comment by patrickjaja** [comment]
@Burnsedia this might be related to latest kernel update released two days ago https://archlinux.org/packages/core/x86_64/linux-lts/

because i have same issue

my kernel
```
$ uname -r
5.10.38-1-lts
```
Error on `yarn install`
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                                                                                               friendly-errors 15:17:07
/home/patrickjaja/development/vsf-theme/node_modules/node-sass/lib/binding.js:1
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/patrickjaja/development/vsf-theme/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/patrickjaja/development/vsf-theme/node_modules/node-sass/lib/index.js:14:35)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
```

**Comment by nschonni** [comment]
>     * npm node-sass versions (`npm ls node-sass`): 4.4.4

This is a very old version that doesn't support Node 16



> Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
> For more information on which environments are supported please see:

4.14.1 also does not support Node 16

https://github.com/sass/node-sass#node-version-support-policy

**Comment by Burnsedia** [comment]
Thanks, I am fixxing it know.
