### ISSUE TITLE
Did a release get deleted? / Do releases get deleted for this repo?

### ISSUE THREAD

**Issue by MichaelDimmitt** [sass/node-sass#3116]
```
npm install; npm start

> node-sass@4.11.0 install /Users/michaeldimmitt/new_c/10_react/components-library/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

version of npm and node that I used:
node: v12.22.1
npm: 6.14.12

I see the directions for creating a pr state: 
- If you're running Node 13, you must be running node-sass 4.13.

It is concerning if releases are getting deleted, because a package-lock.json is supposed to make a project stable. and package.json in someone elses project had the library hardcoded to 4.11.0

I did eventually upgrade the package to ^4.13.0

My environment is a Mac computer 
Os, Big Sur

Let me know if there is any more information needed.
Thanks for taking the time to read this.

I could be mistaken but thought this was worth documenting in case someone else had a similar issue.

**Comment by nschonni** [comment]
No https://github.com/sass/node-sass#node-version-support-policy

**Comment by MichaelDimmitt** [comment]
https://github.com/sass/node-sass/releases

But why it show on the releases section of github? 
also the tags section of github?
https://github.com/sass/node-sass/releases
