### ISSUE TITLE
npm ERR! Build failed with error code: 7

### ISSUE THREAD

**Issue by LoesterFranco** [sass/node-sass#3117]
$ npm -v && node -v && nodejs -v
7.14.0
v16.2.0
v16.2.0

$ sudo npm install
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/loester/dev/sistema/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /home/loester/dev/sistema/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/loester/dev/sistema/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.2.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.2.0
npm ERR! gyp verb command install [ '16.2.0' ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION 
npm ERR! gyp ERR! stack Error: Cannot find module 'block-stream'
npm ERR! gyp ERR! stack Require stack:
npm ERR! gyp ERR! stack - /home/loester/dev/sistema/node_modules/node-sass/node_modules/tar/lib/entry-writer.js
npm ERR! gyp ERR! stack - /home/loester/dev/sistema/node_modules/node-sass/node_modules/tar/lib/pack.js
npm ERR! gyp ERR! stack - /home/loester/dev/sistema/node_modules/node-sass/node_modules/tar/tar.js
npm ERR! gyp ERR! stack - /home/loester/dev/sistema/node_modules/node-sass/node_modules/node-gyp/lib/install.js
npm ERR! gyp ERR! stack - /home/loester/dev/sistema/node_modules/node-sass/node_modules/node-gyp/lib/node-gyp.js
npm ERR! gyp ERR! stack - /home/loester/dev/sistema/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js
npm ERR! gyp ERR! stack     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
npm ERR! gyp ERR! stack     at Function.Module._load (node:internal/modules/cjs/loader:774:27)
npm ERR! gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1013:19)
npm ERR! gyp ERR! stack     at require (node:internal/modules/cjs/helpers:93:18)
npm ERR! gyp ERR! stack     at Object.<anonymous> (/home/loester/dev/sistema/node_modules/node-sass/node_modules/tar/lib/entry-writer.js:7:19)
npm ERR! gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1109:14)
npm ERR! gyp ERR! stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
npm ERR! gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:989:32)
npm ERR! gyp ERR! stack     at Function.Module._load (node:internal/modules/cjs/loader:829:14)
npm ERR! gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1013:19)
npm ERR! gyp ERR! System Linux 5.4.0-73-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/home/loester/dev/sistema/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/loester/dev/sistema/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-24T18_34_29_660Z-debug.log

[log_2021-05-24T18_34_29_660Z-debug.log](https://github.com/sass/node-sass/files/6534366/log_2021-05-24T18_34_29_660Z-debug.log)

/usr/lib
├── node-gyp@8.0.0
├── node-sass@6.0.0
└── npm@7.13.0

$ sudo apt-get install node-gyp
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
node-gyp is already the newest version (6.1.0-3).
node-gyp configurado para instalar manualmente.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 3 não atualizados.

**Comment by nschonni** [comment]
node-sass 6 is using node-gyp 7 https://github.com/sass/node-sass/blob/886319b0c66af74145816fcc601ac0e7edbea1e9/package.json#L66, so you must have a dependency trying to install an older version, which won't be supported on Node 16

**Comment by LoesterFranco** [comment]
first of all thank you very much.
I did as you said and it works correctly. 

-------------------------------------------------------------------------------------------------

curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt-get install -y nodejs

#node-sass 6 is using node-gyp 7 
sudo npm install -g node-gyp@7.1.0
sudo npm install -g node-sass@6.0.0

**Comment by webblufter** [comment]
> node-sass 6 is using node-gyp 7
> 
> https://github.com/sass/node-sass/blob/886319b0c66af74145816fcc601ac0e7edbea1e9/package.json#L66
> 
> , so you must have a dependency trying to install an older version, which won't be supported on Node 16

**I spend 2 days and tries many solutions but this one worked for me - thanks alot**
