### ISSUE TITLE
[unsupported] Installing node-sass 4.13.1 on Node 14

### ISSUE THREAD

**Issue by Yaminipodugu** [sass/node-sass#3119]
./src/components/home/app.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/components/home/app.scss)
Error: Node Sass does not yet support your current environment: Windows 32-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
C:\Users\Yamini\IdeaProjects\2021_citizens_engage\UI\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat 'C:\Users\Yamini\My Documents'] {
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\Yamini\\My Documents'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-login-signup-ui-template@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-login-signup-ui-template@0.1.0 start script.
Starting the development server...

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\Users\Yamini\IdeaProjects\2021_citizens_engage\UI\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\Yamini\IdeaProjects\2021_citizens_engage\UI\node_modules\express\lib\Failed to compile.

./src/components/home/app.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/components/home/app.scss)
Error: Node Sass does not yet support your current environment: Windows 32-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
C:\Users\Yamini\IdeaProjects\2021_citizens_engage\UI\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat 'C:\Users\Yamini\My Documents'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
Starting the development server...

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\Users\Yamini\IdeaProjects\2021_citizens_engage\UI\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\Yamini\IdeaProjects\2021_citizens_engage\UI\node_modules\express\lib\

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
