### ISSUE TITLE
npm execution error "'CALL "X:\node.js\\node.exe" "X:\node.js\\node_modules\npm\bin\npm-cli.js" prefix -g'

### ISSUE THREAD

**Issue by RobertMcMorran** [sass/node-sass#3124]
- NPM version (`6.14.13`):
- Node version (`v14.17.0`):
- Node Process (`{
  node: '14.17.0',
  v8: '8.4.371.23-node.63',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}`):
- Node Platform (`win32`):
- Node architecture (`x64`):
- Node-sass version (node -p "require('node-sass').info"):
`Error: Cannot find module 'node-sass'
Require stack:
C:\Users\Programming\[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:133:18)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Programming\\[eval]' ]`
- npm node sass version: (`C:\Users\Programming
-- (empty)``):

- [info.txt](https://github.com/sass/node-sass/files/6610634/info.txt)

Regarding the
`"'CALL "X:\node.js\\node.exe" "X:\node.js\\node_modules\npm\bin\npm-cli.js" prefix -g' it is not recognized as an internal or external command, operable program or batch file."`
error message that you receive after running npm. npm still works but its annoying. **I worked on this for 3 days and its not a permissions issue or an issue with the path.** There is something wrong with your npm.cmd file in the section

    `FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_CLI_JS%" prefix -g') DO (
         SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
    )
     IF EXIST "%NPM_PREFIX_NPM_CLI_JS%" (
      SET "NPM_CLI_JS=%NPM_PREFIX_NPM_CLI_JS%"
    )`

 I can run this command from a command prompt, but it won't work in npm.cmd. I believe it is parsing the command looking for the -g global flag and is trying to prefix the .npm-global folder name to each module name that has a -g flag, but I am not sure. None the less, it doesn't work. I simply commented out that section, because I am going to using the .npm-global method or pre-user method. I also noticed that there are double-backslashes `\\` between the node path `X:\node.js` and command `node.exe`; as well as double-backslashes `\\` between the CALL'ed program `"X:\node.js\\node.exe"` and the parameter `"X:\node.js\\node_modules\npm\bin\npm-cli.js"`. I thought this might help new users (like me) to install node.js and npm.

**Comment by xzyfer** [comment]
This is an issue with npm. There is no `npm.cmd` in node-sass.
