### ISSUE TITLE
Security vulnerability issue with trim-newline  >=3.0.1 <4.0.0 || >=4.0.1  

### ISSUE THREAD

**Issue by ahermant** [sass/node-sass#3127]
- NPM version (`npm -v`):
6.14.11
- Node version (`node -v`):
12.21.0
- Node Process (`node -p process.versions`):
```
{
  node: '12.21.0',
  v8: '7.8.279.23-node.45',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  http_parser: '2.9.4',
  openssl: '1.1.1j',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`):
darwin
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
`node-sass       4.14.0  (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]`
- npm node-sass versions (`npm ls node-sass`):
`network-cloud@0.3.0 /Users/aymerichermant/Projects/Bell/networkcloud_front-end
└── node-sass@4.14.0 
`

# Description

`yarn audit ` identifies an issue with trim-newline >=3.0.1 <4.0.0 || >=4.0.1 which is a dependency of meow<10.0.0.
The same issue should occur with node-sass 6.0.0 which still uses meow 3.7

![image](https://user-images.githubusercontent.com/16947818/121221533-aae66a00-c853-11eb-9d91-8c29ec9aec1d.png)

**Comment by nschonni** [comment]
Duplicate of #3123
Feel free to add the extra details there though
