### ISSUE TITLE
Cannot find module 'webpack/lib/node/NodeOutputFileSystem' error when try to build to build the project

### ISSUE THREAD

**Issue by FelipeDania** [sass/node-sass#3132]
Guys,

I'm on ubuntu 20.04 trying to build my project but received a Cannot find module 'webpack/lib/node/NodeOutputFileSystem' error ouput. I tried several things I found on the internet but they all went wrong.

node version in 16.3.0
angular cli version in 7.3.10
angular version in 7.2.15

`@angular-devkit/architect       0.13.10
@angular-devkit/build-angular   0.13.10
@angular-devkit/core            7.3.10
@angular-devkit/schematics      7.3.10
@angular/cdk                    7.3.7
@angular/cli                    7.3.10
@angular/fire                   5.2.3
@angular/material               7.3.7
@schematics/angular             7.3.10
@schematics/update              0.13.10
rxjs                            6.5.3
typescript                      3.2.4
webpack                         5.39.0`

Bellow the the error trace

`Your global Angular CLI version (12.0.4) is greater than your local version (7.3.10). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Cannot find module 'webpack/lib/node/NodeOutputFileSystem'
Require stack:
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/lib/fs.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/lib/Server.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/architect/src/architect-legacy.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/architect/src/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/models/architect-command.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/commands/build-impl.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/schematics/tools/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/utilities/json-schema.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/models/command-runner.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
Error: Cannot find module 'webpack/lib/node/NodeOutputFileSystem'
Require stack:
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/lib/fs.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/lib/Server.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/architect/src/architect-legacy.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/architect/src/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/models/architect-command.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/commands/build-impl.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular-devkit/schematics/tools/index.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/utilities/json-schema.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/models/command-runner.js
- /mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/lib/fs.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/index.js:7:27)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/mnt/c/N3/Application/FRONT/Mozaik_Portal_Mozaik_Frontend/node_modules/webpack-dev-server/lib/Server.js:38:30)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)`

Bellow the package.json and I have not the package-lock.json, I deleted the file

`{
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/fire": "^5.2.3",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/router": "^7.2.15",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-free": "^5.11.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.2",
    "@types/crypto-js": "^4.0.1",
    "angular-gauge-chart": "^0.7.2",
    "angular5-data-table": "^1.0.3",
    "animate.css": "^3.7.2",
    "apexcharts": "^3.15.3",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "chartjs-plugin-datalabels": "^0.7.0",
    "chartjs-plugin-labels": "^1.1.0",
    "core-js": "^2.6.9",
    "crypto-js": "^4.0.0",
    "datatables.net": "^1.10.19",
    "datatables.net-dt": "^1.10.19",
    "easytimer.js": "^4.1.1",
    "firebase": "^7.24.0",
    "getstats": "^1.2.0",
    "jquery": "^3.3.1",
    "jwt-decode": "^2.2.0",
    "ng-apexcharts": "^1.2.0",
    "ng-click-outside": "^6.0.0",
    "ng-connection-service": "^1.0.4",
    "ng-editable-table": "^0.3.15",
    "ng-lottie": "^0.3.2",
    "ng-recaptcha": "6.0.0",
    "ng2-charts": "2.2.3",
    "ng2-currency-mask": "^5.3.1",
    "ng2-money-mask": "^2.1.0",
    "ng2-select2": "^1.0.0-beta.16",
    "ng5-slider": "^1.2.4",
    "ngx-audio-player": "8.0.2",
    "ngx-device-detector": "1.3.11",
    "ngx-facebook": "^2.4.0",
    "ngx-image-cropper": "^1.5.1",
    "ngx-mask": "^8.0.7",
    "ngx-mask-2": "^6.5.23",
    "ngx-order-pipe": "^2.0.4",
    "ngx-pagination": "^3.3.1",
    "ngx-summernote": "^0.6.0",
    "ngx-toastr": "^10.2.0",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.3",
    "select2": "^4.0.10",
    "summernote": "^0.8.16",
    "tslib": "^1.10.0",
    "zone.js": "~0.8.26",
    "@azure/msal-angular": "^1.1.2",
    "msal": "^1.4.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^7.3.10",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@babel/core": "^7.7.2",
    "@types/google.analytics": "0.0.40",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "babel-loader": "^8.0.6",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.14.1",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~3.2.4"
  }`

Some tip to do?

**Comment by nschonni** [comment]
The messages all seem related to Angular, with this project as just a dependency. StackOverflow is probably a better place for a general question like this
