### ISSUE TITLE
6.0.1 Includes binaries for Node 10 for some platforms, despite only Node 12 being supported.

### ISSUE THREAD

**Issue by Ivaylo-Lafchiev** [sass/node-sass#3137]
- NPM version (`npm -v`): not relevant
- Node version (`node -v`): not relevant
- Node Process (`node -p process.versions`): not relevant
- Node Platform (`node -p process.platform`): not relevant
- Node architecture (`node -p process.arch`): not relevant
- node-sass version (`node -p "require('node-sass').info"`): not relevant
- npm node-sass versions (`npm ls node-sass`): not relevant

Looks like in the latest release, only the win32-x64 Node 10 binary was removed from the assets, but not all the other platform binaries for Node 10. I believe these were included in error and should be removed as well to avoid confusion.

**Comment by xzyfer** [comment]
Nice catch! This has been addressed for 6.0.1 but not 6.0.0 just in case someone out there is being cheeky with the node 10 binaries.
