### ISSUE TITLE
grayscale()

### ISSUE THREAD

**Issue by gamb** [sass/node-sass#314]
I have an issue compiling with `node-sass@0.8.6`.

`$ node_modules/.bin/node-sass app/sass/app.scss -o app/style/app.css`

Yields: `error: argument `$color` of `grayscale($color)` must be a color`. Where the offending (and obviously valid) line is:

```
.myClass {
    -webkit-filter: grayscale(1);
}
```

`app.scss` compiles fine with Ruby Sass. If I comment out the above line, Node Sass can compile the rest of the file(s).

**Comment by proov** [comment]
@sandropaganotti Thanks, class and effective (y)

**Comment by rambo-panda** [comment]
@sandropaganotti Thanks, class and effective (y)
