### ISSUE TITLE
Issue when running sassc command

### ISSUE THREAD

**Issue by webmasterpf** [sass/node-sass#3146]
Hello,

I get an issue when I want ti run this command into a project for 
 $ sassc  $(sassIncludePaths --sassc --node_modules) [...]
-bash: sassIncludePaths: command not found
Internal Error: File to read not found or unreadable: [...]

After search, it could be related with node-sass. Could it be ? If yes, what can I do to fix it ?

Thanks

- NPM version (`npm -v`):  6.14.12
- Node version (`node -v`): v10.24.1
- Node Process (`node -p process.versions`): 
{ http_parser: '2.9.4',
  node: '10.24.1',
  v8: '6.8.275.32-node.59',
  uv: '1.34.2',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.41.0',
  napi: '7',
  openssl: '1.1.1k',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019c' }
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
  node-sass       4.14.1  (Wrapper)       [JavaScript]
  libsass         3.5.5   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):
├─┬ gulp-sass@4.1.0
│ └── node-sass@4.14.1  deduped
└── node-sass@4.14.1

**Comment by xzyfer** [comment]
This is not a node-sass issue. The error is because you don't any executable call `sassIncludePaths` on your system.

**Comment by webmasterpf** [comment]
but the module is installed, I don't understand what could miss
└── sass-include-paths@4.10.0
