### ISSUE TITLE
[unsupported] Installing node-sass 6.0.1 on Node 10

### ISSUE THREAD

**Issue by martinvaillancourt** [sass/node-sass#3151]
- NPM version (`npm -v`): 6.9.0
- Node version (`node -v`): v10.16.0
- Node Process (`node -p process.versions`):{ http_parser: '2.8.0',
  node: '10.16.0',
  v8: '6.8.275.32-node.52',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '4',
  openssl: '1.1.1b',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019a' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

Hello,
I'm traying to run this command "npm install node-sass" to install the latest version (6.0.1) but I got this error while installing.

_Cannot download "https://github.com/sass/node-sass/releases/download/v6.0.1/linux_musl-x64-64_binding.node"_

Looks like the image is missing.

I installed the previous version (6.0.0) and it works fine "npm install node-sass@6.0.0"

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
