### ISSUE TITLE
Node 12 support with 6.x  Regular Expression Denial of Service

### ISSUE THREAD

**Issue by GajapatiBag** [sass/node-sass#3152]
Hi,

Noticed that Node 16 was released as version 6.0. 
Unfortunately a new major version seems to break all the other dependencies we have.

Is it possible to have this back-ported to be a patch on top of node 12 with node-sass 6.

# Run  npm install --save-dev node-sass@6.0.1  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ trim-newlines                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-sass [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-sass > meow > trim-newlines                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1753                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by nschonni** [comment]
Node 12 is supported with 6.0.1 https://github.com/sass/node-sass#node-version-support-policy
