### ISSUE TITLE
Apple Silicon build

### ISSUE THREAD

**Issue by Peredery** [sass/node-sass#3157]
Hi! @nschonni  Please look at this https://github.com/actions/virtual-environments/issues/2486#issuecomment-885458538

original issue: https://github.com/sass/node-sass/issues/3033

**Comment by nschonni** [comment]
Thanks for pointing this out! I've added a note to the other thread, so I'm going to close this one

**Comment by Peredery** [comment]
@nschonni hi!  need to fill out the form for get access 😄 

https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md
 
https://github.com/actions/virtual-environments/issues/2486#issuecomment-892637763

form url: https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR_fA7dPeYFZNhXEED2yRSuVUQk01REoxS05JTUhZRDFMTkYzRjVURklWMy4u

**Comment by brysonreece** [comment]
As per [actions/virtual-environments#2486)](https://github.com/actions/virtual-environments/issues/2486) it looks like the general availability release has been delayed. In the meantime @nschonni, you can sign up using the above form to be granted access to the image early, which should help unblock a fix for broken ARM environments.

**Comment by xzyfer** [comment]
Thanks all, I've submitted the form 🤞

**Comment by nschonni** [comment]
So the Big Sur build has now hit GA https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/
Unfortunately, it isn't an M1 based build. That's being tracked on https://github.com/actions/virtual-environments/issues/2187
