### ISSUE TITLE
Sourcemaps not being created when using middleware

### ISSUE THREAD

**Issue by ilanbiala** [sass/node-sass#316]
With Node-sass's middleware, it seems like sourcemaps cannot be created.

```
app.use(sass.middleware({
    src: __dirname + '/public',
    dest: __dirname + '/public',
    sourceMap: '/sourcemaps',
    outputStyle: 'compressed',
    debug: true
}));
```

Is this a bug, or am I forgetting something? The middleware section of the documentation is a bit short, so I'm entirely sure what's possible and what isn't when using the middleware. Also, is there any way to ignore files? I'm using Foundation, which provides the files already compiled and as .scss, but I just want to serve the compiled ones. Is there something like an `ignore` property for files that can just be requested normally?

**Comment by xraymutation** [comment]
This worked for me: 
`sourceMap: __dirname + '/public/sourcemaps',`

**Comment by xraymutation** [comment]
Just to clarify, my entire setup looked this way:

```
app.use(sassMiddleware({
    src: __dirname + '/sass/',
    dest: __dirname + '/public/css',
    sourceMap: __dirname + '/public/sourcemaps',
    prefix: '/css',
    debug: !PROD,
    outputStyle: 'nested',
    sourceComments: 'normal',
    force: !PROD
}));
```
