### ISSUE TITLE
node sass in manjaro

### ISSUE THREAD

**Issue by DarkDeveloper-Plant** [sass/node-sass#3160]
I got this error on Linux manjaro 20 

`Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)`

- NPM version : `7.20.2`
- Node version : `16.5.0`
- Node Process :
 ```
{
  node: '16.5.0',
  v8: '9.1.269.38-node.20',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```
- Node Platform : `linux`
- Node architecture : `x64`

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
