### ISSUE TITLE
No support for macOS 12 (montery)?

### ISSUE THREAD

**Issue by alexgurr** [sass/node-sass#3162]
- NPM version (`npm -v`): 7.20.3
- Node version (`node -v`): 16.6.1
- Node Process (`node -p process.versions`):
```
{
  node: '16.6.1',
  v8: '9.2.230.21-node.19',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
```

Can't seem to install node-sass with the latest Node + node-sass@next. Any ideas or workarounds?

**Comment by nschonni** [comment]
That is a supported combination with 6+ https://github.com/sass/node-sass#node-version-support-policy
There is no `next` is a very old tag that points to v4

**Comment by alexgurr** [comment]
That was just an example. I get the same error with latest `yarn add node-sass`.

**Comment by nschonni** [comment]
check your dependency tree for something that is forcing it to install a version below 6. That message is only thrown for older versions
