### ISSUE TITLE
Snyk vulnerabilities detected in node-saas 6

### ISSUE THREAD

**Issue by sjcotto** [sass/node-sass#3166]
Hi, we are seeing reported issues by snyk.

![image](https://user-images.githubusercontent.com/3880470/128899195-878048d6-3189-482f-be6d-6a89512a777d.png)

**Comment by nschonni** [comment]
These all appear related to libsass

**Comment by sjcotto** [comment]
are you saying this should be in another repo? going from libsass i ended here
