### ISSUE TITLE
Complex math operation can't be compiled when running with react

### ISSUE THREAD

**Issue by Zkang0729** [sass/node-sass#3169]
I was converting an app from Angular to React. I can confirm that the following line of codes compiled correctly when using with Angular with the exact same version information.
```sass
@function cubic-bezier-clip-path($start-x, $end-x, $start-y, $end-y) {
  $points: 0% 0%, 0% 100%, 50% 100%;
  $middle-point-y: ($start-y + $end-y) / 2;

  $i: 1;
  @while ($i >= 0) {
    $points: append(
      $points,
      $end-x * pow(1 - $i, 3) + 3 * $end-x * $i * pow(1 - $i, 2) + 3 * $start-x * pow($i, 2) * (1 - $i) + $start-x * pow($i, 3)
      $end-y * pow(1 - $i, 3) + 3 * $middle-point-y * $i * pow(1 - $i, 2) + 3 * $middle-point-y * pow($i, 2) * (1 - $i) + ($start-y) * pow($i, 3),
      "comma"
    );

    $i: $i - 0.001;
  }

  @return polygon($points, 100% 0%);
}
```
However, when running with node-sass and react, it's giving me this error: **SassError: Undefined operation: "100% times pow(0, 3)".** I have seen similar bugs being reported but they are all from 2017-2019 with a lot older version of node-sass. Any help will be appreciated! Thanks

- NPM version (`npm -v`): 6.14.8
- Node version (`node -v`): 14.13.1
- Node Process (`node -p process.versions`):
```json
{
  node: '14.13.1',
  v8: '8.4.371.19-node.16',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```console
    node-sass       6.0.1   (Wrapper)       [JavaScript]
    libsass         3.5.5   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@6.0.1

**Comment by xzyfer** [comment]
Using angular or react doesn't affect node-sass. I suggest double checking you haven't accidentally changed the version of node-sass or altered your build setup. As long as you're using the same version of node-sass the behaviour will always be the same.
