### ISSUE TITLE
Sass watch option to force compile at startup

### ISSUE THREAD

**Issue by mangelozzi** [sass/node-sass#3170]
Hi, I am trying to find out the conclusion of:

https://github.com/sass/node-sass/issues/1742 or
https://github.com/sass/node-sass/issues/1660

Both issues are closed without any explanation?

**Comment by nschonni** [comment]
The explanation is in the threads, that it isn't supported, and a new option to support it won't be added

**Comment by mangelozzi** [comment]
@nschonni Actually the last post is asking if there is any update on this issue. It seems to me as if the SASS developers do not empathise nor give time to external peoples suggestions. The impression I get from read issues is that actually don't care.
