### ISSUE TITLE
Cant npm install

### ISSUE THREAD

**Issue by Tofugrass** [sass/node-sass#3183]
Output from cmd (on windows, ran as admin)
npm install node-sass
npm ERR! code 1
npm ERR! path E:\MicahD\vs2019_repos\cms\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.1.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\MicahD\\vs2019_repos\\cms\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd E:\MicahD\vs2019_repos\cms\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.1.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MicahD\AppData\Local\npm-cache\_logs\2021-09-21T20_28_03_698Z-debug.log

**Comment by nschonni** [comment]
You skipped the issue template, but from the `node-gyp@3.8.0` you're not trying to install node-sass 6, which is the only version that supports Node 16 https://github.com/sass/node-sass#node-version-support-policy

**Comment by stoplion** [comment]
Same issue, everytime I use node-sass it's always failing to install
