### ISSUE TITLE
Dynamic js variables

### ISSUE THREAD

**Issue by MuratovBektur** [sass/node-sass#3187]
Hi

my English is not very good. But I will try to explain the essence of the problem. I would like to add js variables to css code for example:

.myClass {
color: $ {myJSVariables}
}

in order to dynamically add variables to css in most browsers I use CSSStyleSheet.insertRule in css, but this is not very convenient and readable

**Comment by xzyfer** [comment]
This is not possible with node-sass. We are just an implementation of the Sass language. See the Sass documentation for what is possible: https://sass-lang.com/
