### ISSUE TITLE
Support for Node 17

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#3194]
This new major version is  supposed to be released on October 19th. Opening this as a placeholder for when we start to get "node-sass won't install" issues.
- [x] Add 17 to CI
- [x] Add the Module version to extensions.js
- [x] Update support table in README.md
- [x] Pick if this should be 6.1 or 7.0, and land any related PRs if we're cutting a major
- [x] Land https://github.com/sass/node-sass/pull/3122
- [x] Land https://github.com/sass/node-sass/pull/3149

/cc @saper @xzyfer

**Comment by nschonni** [comment]
@xzyfer not sure if we want to try and add https://github.com/sass/node-sass/pull/3193 or just the setUnauthorized one

**Comment by CharlesStover** [comment]
I know this says Node 17 released October 19th, but it wasn't until sometime between Nov 4-10 that GitHub Actions upgraded their Node version for `lts/*` to 17.x, causing all `node-sass` dependencies to fail to install.

I'm not sure if this change by GitHub Actions impacts the timelines or priorities of this ticket at all.

**Comment by nschonni** [comment]
> Node version for `lts/*` to 17.x,

No, 17 is not LTS, that is was bumped from 14 to 16 around that date. 17 will never be a LTS release. If that is happening that would be a bug with nvm/GitHub Actions

The work for 17 was mostly done in the other PR, but binaries still need to be cut and an NPM release made.

**Comment by xzyfer** [comment]
Apologies for the delay I've been job hunting and moving house. 

Thanks for this @nschonni. I've merged #3149 and will try to cut a release in the next couple hours.

**Comment by xzyfer** [comment]
I ran into some issues with the build scripts. Managed to get the windows, osx, linux, and alpine Node 17 binaries uploaded to the v7.0.0 prerelease before going to bed. Will need to copy over the remaining binaries from the v6.0.1 release tomorrow.

**Comment by RochelleLong** [comment]
Goodnight, I have been getting the same error for the past 3 weeks trying to run command **npm i node-sass -save**

I have been reading the comments and I am not sure I understand the proper way to go about this. I have tried using older versions of Node and NPM to try to run and keep getting the same error. Please help

npm WARN deprecated har-validator@5.1.5: this library is no longer supported    
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older v   ersions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\roche\Desktop\starter\node_modules\node-sass
npm ERR! command failed                                                         5Z-
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js     
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\roche\Desktop\starter\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\roche\\Desktop\\starter\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@17.1.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHONnpm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path      
npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error   
npm ERR! gyp verb find Python checking if "python" can be used
npm ERR! gyp verb find Python - executing "python" to get executable path       
npm ERR! gyp verb find Python - "python" is not in PATH or produced an error    
npm ERR! gyp verb find Python checking if "python2" can be used
npm ERR! gyp verb find Python - executing "python2" to get executable path      
npm ERR! gyp verb find Python - "python2" is not in PATH or produced an error   
npm ERR! gyp verb find Python checking if Python is C:\Python37\python.exe      
npm ERR! gyp verb find Python - executing "C:\Python37\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Python37\python.exe" could not be run       
npm ERR! gyp verb find Python checking if Python is C:\Python27\python.exe      
npm ERR! gyp verb find Python - executing "C:\Python27\python.exe" to get version
npm ERR! gyp verb find Python - "C:\Python27\python.exe" could not be run       
npm ERR! gyp verb find Python checking if the py launcher can be used to find Python
npm ERR! gyp verb find Python - executing "py.exe" to get Python executable pathnpm ERR! gyp verb find Python - "py.exe" is not in PATH or produced an error    
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHONnpm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error   
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error    
npm ERR! gyp ERR! find Python checking if "python2" can be used
npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error   
npm ERR! gyp ERR! find Python checking if Python is C:\Python37\python.exe      
npm ERR! gyp ERR! find Python - "C:\Python37\python.exe" could not be run       
npm ERR! gyp ERR! find Python checking if Python is C:\Python27\python.exe      
npm ERR! gyp ERR! find Python - "C:\Python27\python.exe" could not be run       
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error    
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python. 
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:      
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"   
npm ERR! gyp ERR! find Python For more information consult the documentation at:npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation   
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use    
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Users\roche\Desktop\starter\node_modules\node-gyp\lib\find-python.js:302:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Users\roche\Desktop\starter\node_modules\node-gyp\lib\find-python.js:136:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\roche\Desktop\starter\node_modules\node-gyp\lib\find-python.js:200:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\roche\Desktop\starter\node_modules\node-gyp\lib\find-python.js:266:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:416:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:475:16)   
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\roche\\Desktop\\starter\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\roche\Desktop\starter\node_modules\node-sass     
npm ERR! gyp ERR! node -v v17.1.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\roche\AppData\Local\npm-cache\_logs\2021-12-04T02_24_09_048Z-debug-0.log

**Comment by xzyfer** [comment]
I ran into some issues with my release script but it's resolved now. V7 has been released with Node 17 support.

**Comment by xzyfer** [comment]
Version 7.0
