### ISSUE TITLE
Upgrade to Node-GPY 8.x

### ISSUE THREAD

**Issue by robd003** [sass/node-sass#3200]
Right now when installing node-sass you'll get an annoying message about requests being used by an out of date node-gyp dependency.

Could we please require node-gyp in the ^8.x version so this message disappears?

requests has something like 42 useless dependencies and has been fully deprecated.

**Comment by pzrq** [comment]
Looks like Dependabot is already on the case: https://github.com/sass/node-sass/pull/3199

**Comment by xzyfer** [comment]
Fixed in 7.0.1.
