### ISSUE TITLE
Dependency meow security vulnerability

### ISSUE THREAD

**Issue by kkmavr** [sass/node-sass#3201]
There is a vulnerability in the trim-newlines library used.
node-sass>meow 9.0.0 >trim-newlines 3.0.0

[GHSA-7p7h-4mm5-852v](https://github.com/advisories/GHSA-7p7h-4mm5-852v)

Is there a change to update meow to v10.0.1 or a later one, so that it ends up using trim-newlines v4.0.1 which is the patched version?

**Comment by nschonni** [comment]
Duplicate of https://github.com/sass/node-sass/issues/3188
