### ISSUE TITLE
yarn install issue

### ISSUE THREAD

**Issue by emanuallan** [sass/node-sass#3203]
Having an issue with yarn though it seems to work fine when I do `npm install`. Any insights? Thanks in advance.
![Screen Shot 2021-11-12 at 5 37 31 PM](https://user-images.githubusercontent.com/22531461/141562456-e92566b6-6d02-47b3-9cc8-f13956c48a13.png)

- NPM version (`npm -v`): 8.1.0
- Yarn version (`yarn -v`): 1.22.17
- Node version (`node -v`): 16.13.0
- Node Process (`node -p process.versions`): yarn install 
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): arm64
- node-sass version (`node -p "require('node-sass').info"`): 6.0.0
- npm node-sass versions (`npm ls node-sass`):
├─┬ gulp-sass@4.1.0
│ └── node-sass@4.14.1
├── node-sass@6.0.0
└─┬ react-scripts@4.0.3
  └─┬ sass-loader@10.2.0
    └── node-sass@6.0.0 deduped

**Comment by nschonni** [comment]
`node-sass@4.14.1` doesn't support Node 16  https://github.com/sass/node-sass#node-version-support-policy

**Comment by emanuallan** [comment]
Okay, but could you help me understand how to upgrade it? Because in my package.json node-sass appears as 6.0.0. Also why would it work for npm but not yarn?

**Comment by emanuallan** [comment]
Found a fix. Add this to package.json:

```
"resolutions": {
    "node-sass": "6.0.0"
  },
```

still would like a better understanding as to why it would have worked for npm and not for yarn prior to my fix.

**Comment by emanuallan** [comment]
Found another solution. Updated `gulp-sass` to 5.0.0
