### ISSUE TITLE
Security vulnerability 

### ISSUE THREAD

**Issue by coderealm** [sass/node-sass#3207]
lodash version 4.17.15 has security vulnerability issues seen from Lighthouse report in developer tools in Google Chrome.
Can you please upgrade to lodash version 4.17.21 which does not have this security vulnerability.

Screenshot below

<img width="591" alt="Lodash_vulnerability" src="https://user-images.githubusercontent.com/6623831/143722559-a39297a9-7b3c-4d20-b0c2-700690cab6fd.png">

**Comment by nschonni** [comment]
node-sass doesn't support running in the browser, so you're likely getting it from somewhere else.
