### ISSUE TITLE
linux-x64-93_binding.node disappeared from 4.14.1 repo

### ISSUE THREAD

**Issue by jf250315** [sass/node-sass#3213]
- NPM version (`npm -v`): 6.14.15
- Node version (`node -v`): 14.18.1
- Node Process (`node -p process.versions`):

```
{
  node: '14.18.1',
  v8: '8.4.371.23-node.84',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.4',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 4.14.1
- npm node-sass versions (`npm ls node-sass`): 

```
jf250315$ npm ls node-sass
root@ /Users/jf250315/projects/<project folder>
└── (empty)
```

Our project is in a monorepo with a somewhat old version of react-scripts, which makes it very difficult to upgrade our node-sass version. Everything was working fine with this until today, when our builds started failing with the following error:

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-93_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234
```

None of our projects actually use node-sass, but nevertheless this build failure is preventing deployments. Can this file be readded to the repo by any chance? Or is there any known workaround?

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy

**Comment by jf250315** [comment]
it says it's a supported version, how do i convince it to use the -83 module?

**Comment by nschonni** [comment]
If it's requesting 93, you're running Node 16. Maybe you are using a version manager, but we can't help you debug your local setup
