### ISSUE TITLE
linux-x64-64_binding.node available in 6.0.0 but not 6.0.1

### ISSUE THREAD

**Issue by ethanwinters** [sass/node-sass#3216]
https://github.com/sass/node-sass/releases/download/v6.0.0/linux-x64-64_binding.node exists, https://github.com/sass/node-sass/releases/download/v6.0.1/linux-x64-64_binding.node does not.

<img width="1088" alt="Screen Shot 2021-12-06 at 12 55 55 PM" src="https://user-images.githubusercontent.com/22176794/144897176-c81a1dcf-91da-46bf-8ba1-04cfbfb2aa6d.png">

**Comment by nschonni** [comment]
It looks like 64 releases were accidentally added to 6.0, but that isn't a supported version for that release
