### ISSUE TITLE
Getting 503 Egress is over the account limit when downloading binary artifacts

### ISSUE THREAD

**Issue by orgads** [sass/node-sass#3218]
- NPM version (`npm -v`): 6.14.5
- Node version (`node -v`): v12.18.2
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.14.1  (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): node-sass@4.14.1

When running npm install, I oftel get the following error (started today):
```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-72_binding.node": 

HTTP error 503 Egress is over the account limit.
```

**Comment by xzyfer** [comment]
Looks like an issue with GitHub. They're working on a fix https://github.com/github/feedback/discussions/8535

**Comment by xzyfer** [comment]
https://github.com/github/feedback/discussions/8535#discussioncomment-1799627
