### ISSUE TITLE
Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime

### ISSUE THREAD

**Issue by mohamedmalki** [sass/node-sass#3221]
- NPM version (`npm -v`): 8.1.2
- Node version (`node -v`): v16.13.0
- Node Process (`node -p process.versions`): {
  node: '16.13.0',
  v8: '9.4.146.19-node.13',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime
- npm node-sass versions (`npm ls node-sass`):
- ├─┬ @angular/cli@1.7.4
│ ├── node-sass@4.14.1 deduped
│ └─┬ sass-loader@6.0.7
│   └── node-sass@4.14.1 deduped
└── node-sass@4.14.1

../node_modules/@angular/cli/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

and in build it gives:
ERROR in ./src/assets/styles/app.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

I want to upgrade node-sass to 6.0.1 version, but it gives error, I think it's because of linux x64 not support with node 16.13.0 version.

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy, you may have a sub-dependency that is still trying to pull in an older version, but if you're running Node 16, only node-sass 6 is supported
