### ISSUE TITLE
-bash: sass: command not found\

### ISSUE THREAD

**Issue by voglish** [sass/node-sass#3229]
- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v10.15.0
- Node Process (`node -p process.versions`):
\{ http_parser: \cf4 '2.8.0'\cf2 ,\
  node: \cf4 '10.15.0'\cf2 ,\
  v8: \cf4 '6.8.275.32-node.45'\cf2 ,\
  uv: \cf4 '1.23.2'\cf2 ,\
  zlib: \cf4 '1.2.11'\cf2 ,\
  ares: \cf4 '1.15.0'\cf2 ,\
  modules: \cf4 '64'\cf2 ,\
  nghttp2: \cf4 '1.34.0'\cf2 ,\
  napi: \cf4 '3'\cf2 ,\
  openssl: \cf4 '1.1.0j'\cf2 ,\
  icu: \cf4 '62.1'\cf2 ,\
  unicode: \cf4 '11.0'\cf2 ,\
  cldr: \cf4 '33.1'\cf2 ,\
  tz: \cf4 '2018e'\cf2  \}\
- Node Platform (`node -p process.platform`): Darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): 7.0.1
- npm node-sass versions (`npm ls node-sass`):
/Users/tingching/temp1\
\uc0\u9492 \u9472 \u9472  \cf11 \cb10 node-sass@7.0.1\cf2 \cb3  \

**We cannot install sass and continuously encounter "-bash: sass: command not found\" . We also follow the troubleshoot guide, please see attachment. 

For it is quite long in processing "$ npm install node-sass@latest", I will not post below but paste the part of the code after installing. If there is any information I missed, please just let me know. Thank you so much.**

[~/temp1] $ npm ls node-sass
/Users/tingching/temp1
└── node-sass@7.0.1 

   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New major version of npm available! 6.4.1 → 8.3.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v8.3.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

[~/temp1] $ y@1.0.0 /tmp
-bash: y@1.0.0: command not found
[~/temp1] $ y@1.0.0 /tmp
-bash: y@1.0.0: command not found
[~/temp1] $ node -p "require('node-sass').info"
node-sass	7.0.1	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
[~/temp1] $ which sass
[~/temp1] $ sass --version
-bash: sass: command not found
[~/temp1] $ sass --version
-bash: sass: command not found
[~/temp1] $ cd ..
[~] $ which sass
[~] $ sass --version
-bash: sass: command not found
[~] $ 
[終端機sass安裝狀況畫面.docx](https://github.com/sass/node-sass/files/7806866/sass.docx)
![E4FC983D-DF47-4A98-88BE-062CA5B42C8A](https://user-images.githubusercontent.com/97092848/148044126-4a2bf3f0-711b-4e7d-abf8-d002ae2853f8.jpeg)

**Comment by nschonni** [comment]
the binary name is `node-sass` not `sass`. `sass` is the binary for https://github.com/sass/dart-sass
