### ISSUE TITLE
[unsupported] Installing node-sass 5 on Node 16

### ISSUE THREAD

**Issue by mhmdalii** [sass/node-sass#3230]
error in node sass does not yet support your current environment: os x 64-bit with unsupported runtime (93)
- i face this error and cannot run my project --> on React JS
- node -v : v16.13.1
- OS : macos Catalina 10.15.7

![image](https://user-images.githubusercontent.com/33903920/148644012-e7de0312-411d-46b0-82d8-c7d3ae2fda1c.png)

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
