### ISSUE TITLE
Failed to install node-sass in Azure DevOps container with Ubuntu 20.04

### ISSUE THREAD

**Issue by zhebinliu** [sass/node-sass#3231]
- NPM version (`npm -v`):8.1.2
- Node version (`node -v`):16.13.2
- Node Process (`node -p process.versions`):
- {
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

- Node Platform (`node -p process.platform`):linux
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

Error shows as below:
[4/4] Building fresh packages...
error /home/vsts/work/1/s/node_modules/gulp-sass/node_modules/node-sass: Command failed.
Exit code: 1

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vsts/work/1/s/node_modules/gulp-sass/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.11.0-1025-azure
gyp ERR! command "/usr/local/bin/node" "/home/vsts/work/1/s/node_modules/gulp-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/vsts/work/1/s/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
That old node-gyp means you must be running an older version that we don't support running on Node 16

**Comment by sandrinjoy** [comment]
> https://github.com/sass/node-sass#node-version-support-policy That old node-gyp means you must be running an older version that we don't support running on Node 16

so how can we relsove this issue, there are some internal packages in the project which is using older versions of gyp.
