### ISSUE TITLE
Unable to remove incompatible node-sass

### ISSUE THREAD

**Issue by DenyVeyten** [sass/node-sass#3233]
**Steps to reproduce:**
1. Install some old node-sass version successfully (e.g. node-sass@4.12 with node 12)
2. Switch to node that doesn't support installed node-sass version (e.g. node 16)
3. Try to remove node-sass (`npm uninstall node-sass`)

**Actual result:** node-gyp tries to compile modules and fails, node-sass is not removed from package.json/package-lock.json

**Expected result:** node-sass removes successfully

**Comment by nschonni** [comment]
Sounds like there is still a dependency on node-sass in your tree, so you removing the direct one, still falls back to installing an incompatible version when NPM tries to satisfy it

**Comment by DenyVeyten** [comment]
When I remove manually node-sass from package.json and package-lock.json, `npm install` works well.
Does this a good indicator that I have no node-sass deps deeply in packages?

**Comment by DenyVeyten** [comment]
@nschonni well, you're right, I had sass-webpack-plugin as well, so checked on an empty project, node-sass uninstalls without issues.
Sorry for the false alert

**Comment by zedverse** [comment]
I have the same issue. I don't have node-sass mentioned in package.json. However, when doing `npm install` it tries to install node-sass and fails with node-gyp . I tried degrading the versions of node to the ones mentioned in node-sass support but still same. I believe, node-sass is a dependency in other package, here is package.json. Can you guide me how to proceed. I am not even able to spot the node-sass dependent dependency in package.json: ```
"dependencies": {
    "@quasar/extras": "^1.0.0",
    "axios": "^0.18.1",
    "jsqr": "^1.3.1",
    "pdfvuer": "^1.6.1",
    "quasar": "^1.9.5",
    "vue-class-component": "^7.2.2",
    "vue-croppa": "^1.3.8",
    "vue-property-decorator": "^8.3.0"
  },
  "devDependencies": {
    "@quasar/app": "^1.6.2",
    "@types/node": "^10.17.15",
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.17.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.1.2",
    "webpack-cli": "^3.3.11"
  },
  "engines": {
    "node": ">= 10.18.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ],
  "resolutions": {
    "@babel/parser": "7.7.5"
  }
```
