### ISSUE TITLE
Support for riscv64

### ISSUE THREAD

**Issue by kirana1996** [sass/node-sass#3234]
Hi, 

     Able to install node-sass on riscv target, but while executing facing binding issue.

npm ERR! Testing binary
npm ERR! node: symbol lookup error: /home/root/ki/vault/ui/node_modules/node-sass/vendor/linux-riscv64-93/binding.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE

Help us to resolve issue..

Thanks,

**Comment by nschonni** [comment]
I'll leave this open for anyone else coming across it, but to be clear we don't support the architecture and similar to https://github.com/sass/node-sass/issues/3167 we won't support any architecture we can't have a CI run on to test and produce builds reliably

**Comment by saper** [comment]
you didn't say which node version this was, closing.
