### ISSUE TITLE
Cannot run build for node v16.1.0, is it supported?

### ISSUE THREAD

**Issue by blaasvaer** [sass/node-sass#3247]
Cannot build node-sass for node v16.1.0, is it supported at all? I can't seem to find any information on what is supported other than this: https://github.com/sass/node-sass/releases/tag/v4.5.0

Which seem to only mention Node up until v7 ... but it runs just fine on v14.17.0 … so, what's true and what is not?

According to the README node versions after 7 does not seem to be supported … or has managing updates in the docs and readme's become to overwhelming?

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
