### ISSUE TITLE
install: for version incompatibility issues, log clear prompts

### ISSUE THREAD

**Issue by hufei365** [sass/node-sass#3248]
When executing “npm install”, because the third-party package relies on a lower version of "node-sass", which is incompatible with the current node version, then installation fails. The installation log does not prompt version compatibility information.

**Comment by engjames256** [comment]
Try npm i node-sass --save

**Comment by nschonni** [comment]
A message has been printed https://github.com/sass/node-sass/blob/master/lib/errors.js#L32 and hasn't changed in some time, so there should be something unless the dependency is trying to install a v3 version
