### ISSUE TITLE
Check we're handling .sass files correctly

### ISSUE THREAD

**Issue by andrew** [sass/node-sass#326]
Once https://github.com/andrew/node-sass/issues/324 has shipped we'll have pretty much automatic support for .sass files thanks to https://github.com/hcatlin/libsass/pull/181/files by @mgreter.

We'll need to check that this is working correctly and add some tests for .sass files.

The only place I can see that needs to be updated is in https://github.com/andrew/node-sass/blob/master/lib/middleware.js#L82-L89, as well as updating documentation everywhere to show we support both kinds of syntax.

**Comment by pongstr** [comment]
Hi there,

I was wondering whether `.sass` syntax is supported via `data`? like the example below:

```javascript
var result = sass.renderSync({
  data: '$font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif\r\n$font-size:   13px\r\n\r\n$brand-primary: darken(#428bca, 6.5%)\r\n$brand-success: #5cb85c\r\n\r\n\r\nbody\r\n  min-height: 100%\r\n  font-family: $font-family\r\n  font-size: $font-size\r\n  ',
  success: function (result) {
    console.log(result.css)
  }
});
```

**Comment by am11** [comment]
@pongstr, certainly with `indentedSyntax` set to `true` like so:

```javascript
var result = sass.renderSync({
  data: '$font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif\r\n$font-size:   13px\r\n\r\n$brand-primary: darken(#428bca, 6.5%)\r\n$brand-success: #5cb85c\r\n\r\n\r\nbody\r\n  min-height: 100%\r\n  font-family: $font-family\r\n  font-size: $font-size\r\n  ',
  indentedSyntax: true,
  success: function (result) {
    console.log(result.css)
  }
});
```

produces:

```javascript
// on probing 'result'
{ stats:
   { entry: 'data',
     start: 1421917498878,
     includedFiles: [],
     end: 1421917498886,
     duration: 8 },
  css: 'body {\n  min-height: 100%;\n  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;\n  font-size: 13px;
}\n',
  sourceMap: '{}' }
```

**Comment by pongstr** [comment]
Thanks @am11

**Comment by am11** [comment]
@andrew, should this be closed as resolved? Also, we have couple of tests for indented syntax to signify: all is well. :sunglasses:
