### ISSUE TITLE
Reported Vulnerability for package trim-newlines/1.0.0 with node-sass/4.14.1 version

### ISSUE THREAD

**Issue by amit199309** [sass/node-sass#3269]
Hi Node-Sass Team,

I am using node-sass/4.14.1, and this package using internally trim-newlines/1.0.0 addon with path
( **node-sass/4.14.1/meow/3.7.0/trim-newlines/1.0.0** ) ,
During  scan check this addon reported vulnerable and expecting latest version of this. So could you please work on this by update the package.json for node-sass/4.14.1 to get the latest of trim-newlines.

Please do needful.

Thank you

**Comment by nschonni** [comment]
We don't support old versions of the packge, just the latest release
