### ISSUE TITLE
build(deps): bump node-gyp from 7.1.2 to 8.4.1 - node-sass 6.0+

### ISSUE THREAD

**Issue by wedneyyuri** [sass/node-sass#3272]
It would be possible to backport #3209 to node-sass 6.0+? 

**Motivation:**
- Nodejs v16 is still under LTS
- The [supported node-sass version](https://github.com/sass/node-sass#node-version-support-policy) for node v16 is node-sass 6.x
- Node-sass v6 depends on node-gyp v7.1: https://github.com/sass/node-sass/blob/v6.0.1/package.json#L65
- Before node-gyp v8, node-gyp depends on python2 for some use cases: https://github.com/nodejs/node-gyp/commit/0da2e0140dbf4296d5ba7ea498fac05e74bb4bbb

It would avoid the following error:

> env: python: No such file or directory

**Workaround:** Use [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) strategy in package.json:

```json
"resolutions": {
  "node-sass/node-gyp": "8"
},
```

- NPM version (`npm -v`): 8.1.2
- Node version (`node -v`): v16.13.2
- Node Process (`node -p process.versions`):
```js
{
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): arm64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	6.0.1	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):

```
nextjsproject@0.0.2 /Users/yurilima/Projects/nextjsproject
├─┬ next@12.0.7
│ └── node-sass@6.0.1 deduped
└── node-sass@6.0.1

```

**Comment by nschonni** [comment]
It's been requested before like https://github.com/sass/node-sass/issues/3106#issuecomment-1001921136 to backport changes, but we don't support more than one active release
