### ISSUE TITLE
Cannot download v6.0.1/linux-x64-64_binding.node

### ISSUE THREAD

**Issue by grekpg** [sass/node-sass#3277]
npm i 
......

Downloading binary from https://github.com/sass/node-sass/releases/download/v6.0.1/linux-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v6.0.1/linux-x64-64_binding.node": 

and this is true : 

https://github.com/sass/node-sass/releases/download/v6.0.1/linux-x64-64_binding.node 

not found ?

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
