### ISSUE TITLE
position: sticky -> position: -webkit-sticky

### ISSUE THREAD

**Issue by math-GH** [sass/node-sass#3281]
Hi,

I use node-sass via the Visual Studio Code extension https://github.com/yutent/scss-to-css

When I have `position: sticky;` in `.scss` than it compiles to:
```
position: -webkit-sticky;
position: sticky;
```

As I see `position: -webkit-sticky;` is not needed anymore.
See: https://caniuse.com/?search=position%3A%20sticky (the prefix `-webkit` is needed for Safari 7.1-12.1. Last release of Safari 12.1 was in 2019 (see: https://en.wikipedia.org/wiki/Safari_version_history#Safari_12)

I would say, that `-webkit-sticky` is not used anymore.

(CC: @yutent)

**Comment by yutent** [comment]
This is not a mistake.
What you need is to place a file `.scssrc`.

**Comment by nschonni** [comment]
That plugin is probably using something like PostCSS to add the prefixes, that isn't anything to do with this library
