### ISSUE TITLE
Error installing node-sass module on Linux - trying to download incorrect file - 404 Not Found

### ISSUE THREAD

**Issue by gasgithub** [sass/node-sass#3291]
I have this dependency in package-lock:
```
   "node-sass": {
      "version": "4.12.0",
```

when running `npm install` on project or directly `npm install --save-dev node-sass@4.12.0` I see the following error:

```
npm install --save-dev node-sass@4.12.0
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> node-sass@4.12.0 install /tmp/dtcc/cplane-frontend/src/main/cp1-web-frontend/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-83_binding.node":

HTTP error 404 Not Found
```

The 404 is correct as there is no such link, as the latest build for 4.12 is `-72 ` https://github.com/sass/node-sass/releases/tag/v4.12.0
so why the installer is trying to download -83???

- NPM version (`npm -v`): # 6.14.17
- Node version (`node -v`): v14.20.0
- Node Process (`node -p process.versions`):
{
  node: '14.20.0',
  v8: '8.4.371.23-node.87',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.5',
  openssl: '1.1.1q',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}

- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
