### ISSUE TITLE
node-sass library dependency started breaking this morning

### ISSUE THREAD

**Issue by taivoe** [sass/node-sass#3301]
This is a dependency of another installed library, I can see it in package-lock.json, but this binary seems to be missing?

> node-sass@4.13.0 install C:\git\react-applications\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

**Comment by joniramovincit** [comment]
I am encountering the same issue installing node-sass with Node 14 (installing with npm, lockfile version 1).

> 39.97 Downloading binary from https://github.com/sass/node-sass/releases/download/v6.0.1/linux-arm64-83_binding.node
40.48 Cannot download "https://github.com/sass/node-sass/releases/download/v6.0.1/linux-arm64-83_binding.node": 

> 40.78 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-83_binding.node
41.32 Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-83_binding.node": 
41.32 

Both URLs return 404. Any resolution to this issue?
