### ISSUE TITLE
Build broken styles width max() min()

### ISSUE THREAD

**Issue by zdimaz** [sass/node-sass#3308]
left: max(0%, 100% - 150px);
and try 
left: max(0%, calc(100% - 150px));

Build:
left:max(0,100% - 150px)

=====================
left:max(0,100% - 150px)

left:max(0 this mast be % , this mast be indent 100% - 150px)

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/2815#issuecomment-574038619

**Comment by zdimaz** [comment]
Its doesnt work (=
