### ISSUE TITLE
darwin-arm64-83_binding.node  notfound

### ISSUE THREAD

**Issue by zyj429030759** [sass/node-sass#3316]
- NPM version (6.14.17):
- Node version (14.20.1):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/3033
