### ISSUE TITLE
macos 13  npm rebuild node-sass  darwin-arm64-83_binding.node no Found

### ISSUE THREAD

**Issue by 514315959** [sass/node-sass#3323]
- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

> node-sass@4.14.1 install /Users/zhaodong/xcx/ysh-rebang/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://npm.taobao.org/mirrors/node-sass/v4.14.1/darwin-arm64-83_binding.node
Cannot download "https://npm.taobao.org/mirrors/node-sass/v4.14.1/darwin-arm64-83_binding.node": 

HTTP error 404 Not Found

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/3033
