### ISSUE TITLE
Node 20 Support (module 115)

### ISSUE THREAD

**Issue by ZachHandley** [sass/node-sass#3353]
I removed most of the content of the issue template as this is not something that is super important, but Node-Sass doesn't support Node 20 (which is fair it came out yesterday), but seeing as how Node 20 will be the next LTS I think it's relatively important it's supported

**Comment by gustawdaniel** [comment]
![7mbzw0](https://github.com/sass/node-sass/assets/16663028/00180b5c-a15c-4c0e-870c-3e1e6c90dc93)

## Don't use node-sass anymore

node-sass is now deprecated. You can easily fix it by the following.

```
npm uninstall node-sass
npm install sass
```

It works fully the same with better stability.

source: https://stackoverflow.com/a/74791465/6398044

**Comment by xzyfer** [comment]
Node 20 support has landed in v9.0.0
