### ISSUE TITLE
[Unsupported] Installing node-sass 4.12 on Node 16

### ISSUE THREAD

**Issue by SeniorGuru** [sass/node-sass#3360]
I got this issue when npm install or yarn install.
Please help me fix this issue quickly. I can't deploy my react app on any hosting sites because of this issue.

npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/BAUSERVICE/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.15.0-1033-aws
npm ERR! gyp ERR! command "/home/ubuntu/.nvm/versions/node/v16.13.1/bin/node" "/home/ubuntu/BAUSERVICE/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/ubuntu/BAUSERVICE/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-05-12T09_39_29_776Z-debug.log

- NPM version (`8.1.2`):
- Node version (`16.13.1`):
- npm node-sass versions (`4.12.0`):

**Comment by nschonni** [comment]
https://github.com/sass/node-sass#node-version-support-policy
