### ISSUE TITLE
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js)

### ISSUE THREAD

**Issue by Suresh-shanmugam-msc** [sass/node-sass#3362]
Hi,

When I try to run the self hosted developer portal with few updation getting the below warnings using npm start command

WARNING in ./src/themes/website/styles/styles.design.scss (./src/themes/website/styles/styles.design.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/themes/website/styles/styles.design.scss)

Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(4090:3) autoprefixer: end value has mixed support, consider using flex-end instead

WARNING in ./src/themes/website/styles/styles.design.scss (./src/themes/website/styles/styles.design.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/themes/website/styles/styles.design.scss)

Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(4518:3) autoprefixer: end value has mixed support, consider using flex-end instead

**Comment by nschonni** [comment]
None of that error messages relate to node-sass. Try StackOverflow for general web dev questions
