### ISSUE TITLE
Cannot install node-sass 9.0.0 on node 20

### ISSUE THREAD

**Issue by LaurensRietveld** [sass/node-sass#3365]
### Version details

- NPM version (`npm -v`): 9.6.6
- Node version (`node -v`): v20.2.0
- Node Process (`node -p process.versions`):
<details>

```
{
  node: '20.2.0',
  acorn: '8.8.2',
  ada: '2.4.0',
  ares: '1.19.0',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '8.1.0',
  modules: '115',
  napi: '8',
  nghttp2: '1.52.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.8+quic',
  simdutf: '3.2.9',
  tz: '2023c',
  undici: '5.22.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.16',
  v8: '11.3.244.8-node.9',
  zlib: '1.2.13'
}
```

</details>

- Node Platform (`node -p process.platform`): `linux`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`): `9.0.0`
- npm node-sass versions (`npm ls node-sass`): ``-- node-sass@9.0.0`

### Problem

It is not possible to install node-sass `9.0.0` on node 20 without python

```
> docker run -it --rm node:20-bullseye-slim bash
# inside the container:
>  mkdir test && cd test && yarn init -y
> yarn add node-sass
```

Note that if I use the `node:18-bullseye-slim` image and install `node-sass@8.0.0`, then the installation works fine

**Comment by nschonni** [comment]
Bindings are attached to the [release](https://github.com/sass/node-sass/releases/tag/v9.0.0) and downloaded during install, they're not bundled with the NPM package

**Comment by nschonni** [comment]
You haven't provided any error message, you just keep saying it's missing something. You may have a dependency with a dependency on a version older than v9, which won't work on Node 20

**Comment by LaurensRietveld** [comment]
Ah, good point, see here (this is the output of the sequence of commands I posted in the OP)

**Comment by nschonni** [comment]
@xzyfer I wonder if the `GLIBC` error is related to the newer bindings?

**Comment by LaurensRietveld** [comment]
> Bindings are attached to the [release](https://github.com/sass/node-sass/releases/tag/v9.0.0) and downloaded during install, they're not bundled with the NPM package

Just a followup on this one, as I'm still confused. Should we expect differences between 8.0.0 and 9.0.0 wrt the bundled files? As npmjs shows, 8.0.0 contains a `vendor` subdirectory (see [here](https://www.npmjs.com/package/node-sass/v/8.0.0?activeTab=code)) where 9.0.0 does not (see [here](https://www.npmjs.com/package/node-sass/v/9.0.0?activeTab=code))

**Comment by xzyfer** [comment]
@LaurensRietveld directory is created as part of the install process. Can you confirm whether you're able to install V8 on Node 20?

@nschonni it could be related

**Comment by LaurensRietveld** [comment]
> @LaurensRietveld directory is created as part of the install process. Can you confirm whether you're able to install V8 on Node 20?

If that directory is created as part of the install process, then I wouldn't expect that folder to show up in the published npm package. The links above indicates that the directory is created as part of the publication 

With respect to v8: do you mean the v8-dev package? I can install that on node20:

```
docker run -it --rm node:20-bullseye-slim bash -c "apt update && apt install -y libv8-dev"
```

**Comment by xzyfer** [comment]
The vendor directory is sometimes published because I publish the release from my local install, which already have a vendor directory that I forgot to delete.

Sorry, I mean can you try installing node-sass 9 on node 18. I'm trying to determine if the issue is specific to the combination of node-sass v9 on Linux with mode 20.

**Comment by LaurensRietveld** [comment]
It seems to be specific to node 20 indeed. The following sequence of commands install node-sass@9.0.0 fine:

```
> docker run -it --rm node:18-bullseye-slim bash
# inside the container:

mkdir test
cd test/
yarn init -y
yarn add node-sass
```

**Comment by xzyfer** [comment]
Thanks. This suggests I'll need to rebuild the binary tomorrow. I'll update this issue when the new binary has been uploaded

**Comment by LaurensRietveld** [comment]
Excellent, this seems to have fixed it. Many thanks!
