### ISSUE TITLE
 I'm using Node-Sass V8 with Node 18

### ISSUE THREAD

**Issue by KunalOjha** [sass/node-sass#3384]
Attempting to start my local application and receive this error: `OS X Unsupported architecture (arm64) with Node.js 18.x `

Upon checking, i have Node-Sass version 8 package in my package.json, which should be compatible with Node 18 that i'm running against. I'm not sure how to resolve this since this appears to be correct? Tried deleting node_modules, rebuilding node_sass, same error each time.

Node version: v18.17.0
Node-Sass: v8.0.0
M1 Macbook
macOS: Sonoma 14

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/3033
