### ISSUE TITLE
How do I download node-sass@6.0.1

### ISSUE THREAD

**Issue by xahy123** [sass/node-sass#3388]
<img width="260" alt="image" src="https://github.com/sass/node-sass/assets/43662455/84ff27e3-db99-4192-a626-f1f7d24c55ae">
All of these failed

The documentation says to use V16
<img width="701" alt="image" src="https://github.com/sass/node-sass/assets/43662455/f0ff9e61-b524-4780-b90d-8b0bbc3b98cd">

**Comment by saper** [comment]
Please try `npm install node-sass@9.0.0`.
