### ISSUE TITLE
node-sass@8.0.0 install "Binary has a problem"

### ISSUE THREAD

**Issue by hridoyworkac** [sass/node-sass#3406]
C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Binary found at C:\..\..\node_modules\node-sass\vendor\win32-x64-115\binding.node
npm ERR! Testing binary
npm ERR! Binary has a problem: Error: \\?\C:\..\..\node_modules\node-sass\vendor\win32-x64-115\binding.node is not a valid Win32 application.
npm ERR! \\?\C:\..\..\node_modules\node-sass\vendor\win32-x64-115\binding.node
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at module.exports (C:\..\..\node_modules\node-sass\lib\binding.js:19:10)
npm ERR!     at Object.<anonymous> (C:\..\..\node_modules\node-sass\lib\index.js:13:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }

- NPM version (`npm -v`): 10.4.0
- Node version (`node -v`):v20.11.1
- Node Process (`node -p process.versions`):{
  node: '20.11.1',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.13+quic',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.3',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.17',
  zlib: '1.2.13.1-motley-5daffc7'
}
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'true-case-path'
Require stack:
- C:\..\..\node_modules\node-sass\lib\extensions.js
- C:\..\..\node_modules\node-sass\lib\index.js
- C:\..\..\[eval]
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\..\..\\node_modules\node-sass\lib\extensions.js:8:22)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\..\\..\\node_modules\\node-sass\\lib\\extensions.js',
    'C:\\..\\..\\node_modules\\node-sass\\lib\\index.js',
    'C:\\..\\..\\..\\[eval]'
  ]
}

Node.js v20.11.1

- npm node-sass versions (`npm ls node-sass`):
├── node-sass@8.0.0
└─┬ react-scripts@5.0.1
  └─┬ sass-loader@12.6.0
    └── node-sass@8.0.0 deduped invalid: "^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from node_modules/sass-loader

**Comment by airowe** [comment]
@saper Seeing this issue as well all of a sudden. Did you find a resolution?

**Comment by nevez** [comment]
I am also seeing this, cant find a way to solve it apart from building under linux.

**Comment by saTaniguchi** [comment]
same here.
Has someone resolved this error?

**Comment by Bizarrus** [comment]
Same problem here.

I hate some depencies with native install depencies.

**Comment by ecofi** [comment]
Same problem here, very critical as rebuild install fails. Moving now to a different module.

**Comment by saper** [comment]
> Moving now to a different module.

Please do!

**Comment by saper** [comment]
https://github.com/sass/node-sass/releases/tag/v8.0.0 clearly says that node 20 is not supported. Use 9.0.0

**Comment by ecofi** [comment]
> https://github.com/sass/node-sass/releases/tag/v8.0.0 clearly says that node 20 is not supported. Use 9.0.0

I'm running node version 22.0

npm ERR! Binary found at /XXXX/node_modules/node-sass/vendor/linux-x64-127/binding.node
npm ERR! Testing binary
npm ERR! Binary has a problem: Error: /XXXX/node_modules/node-sass/vendor/linux-x64-127/binding.node: file too short
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1572:18)

**Comment by nevez** [comment]
In my case I couldn't downgrade node, but I could substitute "node-sass"
for "sass", and it worked.

Stephen

**Comment by saper** [comment]
> I'm running node version 22.0

PLEASE check the list of the node versions supported. Since we are using binary components, we only support versions listed in the release.
