### ISSUE TITLE
Unable to install node-sass v7.0.0

### ISSUE THREAD

**Issue by buttoski44** [sass/node-sass#3407]
- NPM version (`8.1.0`):
- Node version (`17.0.0`):
- Node Process (`{
  node: '17.0.0',
  v8: '9.5.172.21-node.12',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '102',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.0+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}`):
- Node Platform (`darwin`):
- Node architecture (`arm64`):
- npm node-sass versions (`node-sass@7.0.0 extraneous`):

i was trying to install node-sass `v7.0.0`, but url npm is trying to install package from is not correct

![image](https://github.com/sass/node-sass/assets/87636014/28a9b694-a970-460f-b08b-ecf10688a1f7)

url that node is trying to download packge from is following
https://github.com/sass/node-sass/releases/download/v7.0.0/darwin-arm64-83_binding.node

you can see that in image i have attached, its hitting url that does not exist hence 404 code.
but url for `v7.0.0 (drwin-arm64-83)` has been changed to following location
https://github.com/sass/node-sass/releases/download/v7.0.0/darwin-x64-83_binding.node
[Reference](https://github.com/sass/node-sass/releases/tag/v7.0.0)

**Comment by nschonni** [comment]
https://github.com/sass/node-sass/issues/3033
