### ISSUE TITLE
Error in compiling the scss file with @use and @forward tag

### ISSUE THREAD

**Issue by amitkumarsingh41** [sass/node-sass#3421]
I encountered an error while trying to compile my scss to css. Here are the details:

```
[common]# sass abc.scss xyz.css
Error: Can't find stylesheet to import.
   ╷
12 │ @use "src/styles/common/tokens" as *;
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  abc.scss 12:1  root stylesheet
```

Additional Information:
Node.js version: v22.2.0
npm version: 10.7.0
ubi9 container 

Please let me know if there are any additional details or steps I can provide to help resolve this issue. Thank you!

**Comment by nex3** [comment]
You're using [Dart Sass](https://github.com/sass/dart-sass), not Node Sass. If you're still experiencing this issue, please file a request on that repository.
