### ISSUE TITLE
npm warn deprecated

### ISSUE THREAD

**Issue by MyNameTony1000** [sass/node-sass#3422]
`npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.`

`npm warn deprecated gauge@4.0.4: This package is no longer supported.`

`npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported`
`npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported`

`npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported`

npm ls core-js outputs:

```
-- node-sass@9.0.0
  -- node-gyp@8.4.1
    -- npmlog@6.0.2
      -- gauge@4.0.4

-- node-sass@9.0.0
  -- gaze@1.1.3
    -- globule@1.3.4
      -- glob@7.1.7
        -- inflight@1.0.6 deduped
  -- make-fetch-happen@10.2.1
    -- cacache@16.1.3
      -- glob@8.1.0
        -- inflight@1.0.6 deduped

-- node-sass@9.0.0
  -- gaze@1.1.3
    -- globule@1.3.4
      -- glob@7.1.7
  -- glob@7.2.3 deduped
  -- make-fetch-happen@10.2.1
    -- cacache@16.1.3
      -- glob@8.1.0
  -- node-gyp@8.4.1
    -- glob@7.2.3 deduped
    -- make-fetch-happen@9.1.0
      -- cacache@15.3.0
        -- glob@7.2.3 deduped
  -- sass-graph@4.0.1
    -- glob@7.2.3 deduped

-- node-sass@9.0.0
  -- make-fetch-happen@10.2.1
    -- cacache@16.1.3
      -- @npmcli/move-file@2.0.1
        -- rimraf@3.0.2 deduped
      -- rimraf@3.0.2 deduped
  -- node-gyp@8.4.1
    -- make-fetch-happen@9.1.0
      -- cacache@15.3.0
        -- @npmcli/move-file@1.1.2
          -- rimraf@3.0.2 deduped
        -- rimraf@3.0.2 deduped
    -- rimraf@3.0.2 deduped
```

How can I fix this moment?

**Comment by nex3** [comment]
Node Sass is deprecated. Please use the [`sass`](https://www.npmjs.com/package/sass) package instead.
