### ISSUE TITLE
Problem with node-sass on openshift

### ISSUE THREAD

**Issue by koxa** [sass/node-sass#373]
Hi guys, im trying to run my Harp webserver for nodejs on openshift.
It fails on node-sass building. 
Here is the problem i'm getting:

> node-sass@0.8.4 install /var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node build.js

linux-x64-v8-3.14 exists; testing
Traceback (most recent call last):
  File "/opt/rh/v8314/root/usr/bin/gyp", line 15, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/configure.js:338:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-431.20.3.el6.x86_64
gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo/node_modules/harp/node_modules/terraform/node_modules/node-sass
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
Build failed
npm ERR! Error: ENOENT, lstat '/var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/tree/mixin.js'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Linux 2.6.32-431.20.3.el6.x86_64
npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "update"
npm ERR! cwd /var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path /var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/tree/mixin.js
npm ERR! fstream_path /var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo/node_modules/harp/node_modules/terraform/node_modules/less/lib/less/tree/mixin.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /opt/rh/nodejs010/root/usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! node-sass@0.8.4 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.8.4 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.20.3.el6.x86_64
npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "update"
npm ERR! cwd /var/lib/openshift/53d032eb5973ca04900000db/app-root/runtime/repo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE

**Comment by jrgleason** [comment]
Is there a specific thread I can follow I am also getting this when I run...

    node rebuild node-sass 

On my Windows/Cygwin env

**Comment by xzyfer** [comment]
@jrgleason please create a new issue after following the [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md). Make sure to capture **all** output into a github gist. Do not post the output into a GH issue.
