### ISSUE TITLE
Shadow DOM styling errors

### ISSUE THREAD

**Issue by trevordmiller** [sass/node-sass#376]
When trying to use the `/deep/` Shadow DOM selectors for Web Components, the Sass task (in Gulp/Grunt) throws the following error:

``` bash
Warning: /Users/trevordmiller/Sites/github/frontendtv.github.io/app/styles/main.scss:41: error: invalid top-level expression
```

http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/

**Comment by agalazis** [comment]
any update on this ? I use the latest version which is supposed to be compatible with  3.3+ that supports it still same issue...
