### ISSUE TITLE
segmentation fault when parsing invalid sass

### ISSUE THREAD

**Issue by chrisspiegl** [sass/node-sass#378]
This problem was already discussed in issue #7. But as far as I tested it, it is still a problem.
I am using node-sass via gulp-sass. gulp-sass use the current version of node-sass (^0.9).

If I try to compile a scss file with an missing `;` it writes `segmentation fault` to the console and crashes.

**Comment by JustineWin** [comment]
Experienced a lot of segfault errors just a while ago. Tried doing npm rebuild and reinstalling my node modules but to no luck. Finally went back to my code and noticed one line exceeded one tab. Deleted the extra tab and now it finally works! This error occured while I was testing the responsiveness of the site and made a quick change in sass and gulp watch it right ahead.

**Comment by xzyfer** [comment]
> noticed one line exceeded one tab
I'm not sure what you mean by this. Can you please show an example so I can see the segfaults myself?

**Comment by JustineWin** [comment]
@xzyfer take this as an example:

sass is tab-sensitive, I failed to see one line exceeded by a tab. Something similar like this:

`#scroll-1
	background: url('../img/scroll-1.png')
	     background-position: center
	background-size: cover`

**Comment by xzyfer** [comment]
Thanks @JustineWin this should throw an error, not segfault

```
Inconsistent indentation: "\t     " was used for indentation, but the rest of the document was indented using 1 tab.
```

This is likely a bug in sass2scss /cc @mgreter

**Comment by JustineWin** [comment]
@xzyfer I see, mine was because of a tab. That's why I was wondering why I'm having a segmentation fault.

**Comment by xzyfer** [comment]
@JustineWin your segmentation fault is due to an unhandled error. So yes, the extra tab is the problem, but a bug is causes libsass to segfault instead of returning an error,
