### ISSUE TITLE
Expose config param to allow specific libsass commit for build

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#389]
Although we ship prebuilt binaries, it may be beneficial to allow users to rebuild their own bindings to a specific version of libsass. The use case I'm seeing with this is for those that want the latest libsass, but not require us to re-release and prep for a non-tagged libsass release.

Maybe something like this in the package.config
```json
{
...
  "libsass": "commitHash"
}
```
I lean towards a config value rather than a `.node-sass.yml`, although that would be a valid approach too.

@andrew thoughts?

**Comment by am11** [comment]
At present, if end-user wants to get the binary out of the desired libsass and given they have compiler GCC 4.6+ (or VC 2013+) and python v2.7 installed, they can:

>
1 - first install node-sass:
>
```bash
cd /tmp
npm install node-sass
cd node_modules/node-sass
>
# the following is to overcome the bug in v2.0.1, as pangyp (temporary fork of node-gyp
# supporting io.js) was mistakenly added as devDependency. This has been mitigated:
npm install pangyp
```
>
2 - then update upstream submodule:
>
```bash
cd src/libsass
git remote add libsass https://github.com/sass/libsass
git fetch libsass
git checkout <my-favourite-hash>
cd ../..
```
>
3 - rebuild binary:
>
```bash
node scripts/build --force
# force flag tells the script to ignore the presence of existing binary
```

Are we aiming to provision automating step 2 here; replacing `<my-favourite-hash>` with `require('package').libsassHash` (since `libsass` in now reserved for libsass version in our package.json)?

So user can do:

```bash
# pwd: node-sass root directory
nano package.json
# updated the value of libsassHash with desired hash, save and close editor, then
node scripts/build --force --update
# where --update would be the new flag which would tell the build script to: git checkout <hash>
```

**Comment by xzyfer** [comment]
I believe this use case has been addressed by the `LIBSASS_EXT ` flag introduced in https://github.com/sass/node-sass/pull/763.

You can now supply the on disk location of the Libsass you wish to use with

```
LIBSASS_EXT=/path/to/libsass npm install node-sass
```

**Comment by saper** [comment]
There are two ways you can specify the external library:

    LIBSASS_EXT=auto

to detect library using `pkg-config`

or

    LIBSASS_EXT=yes
    LIBSASS_CFLAGS=-I<path to sass.h header>
    LIBSASS_LDFLAGS=-L<path to libsass.so or libsass.a library>
    LIBSASS_LIBRARY=-lsass

For example:

    LIBSASS_EXT=yes
    LIBSASS_CFLAGS=-I/usr/local/include
    LIBSASS_LDFLAGS=-L/usr/local/lib
    LIBSASS_LIBRARY=-lsass
