### ISSUE TITLE
Wrong path used for sourceMap

### ISSUE THREAD

**Issue by halfdan** [sass/node-sass#425]
This commit seems to break the path used in sourceMap generation: https://github.com/sass/node-sass/commit/fd6a201dff36a75e6b0658ba4051e44edd3c38d6

We're using `node-sass` and `grunt-sass` for Ghost with the following setup:

```
// ### grunt-sass
// compile sass to css
sass: {
    compress: {
        options: {
            style: 'compressed',
            sourceMap: true
        },
        files: [
            { dest: 'core/client/assets/css/<%= pkg.name %>.min.css', src: 'core/client/assets/sass/screen.scss' },
            { dest: 'core/client/docs/dist/css/<%= pkg.name %>.min.css', src: 'core/client/assets/sass/screen.scss' }
        ]
    }
},
```

This however leads to the following error:

```
Running "sass:compress" (sass) task
Warning: ENOENT, open '/home/vagrant/code/Ghost/core/client/assets/css/core/client/assets/css/ghost.min.css.map' Use --force to continue.
```

---

The two lines used in `sass.js` generate that path:

```
dir = path.dirname(options.outFile); // Contains the full path to the outfile
sourceMapFile = path.resolve(dir, options.sourceMap); // sourceMap also contains the full path
```

**Comment by STRML** [comment]
Is there a reason why this was closed? This appears to cause incorrect source file locations in grunt-sass.

**Comment by spelufo** [comment]
Option parsing is still badly broken. You have examples for a thousand frameworks on the readme but your cli doesn't work.

```bash
$ ls static/
main.sass
$ node_modules/.bin/node-sass -r static/
{
  "status": 4,
  "message": "File to read not found or unreadable: static/",
  "code": 4
}
$ node_modules/.bin/node-sass -w static/main.sass -o static/main.css
Provide a Sass file to render

  Example
    node-sass --output-style compressed foobar.scss foobar.css
    cat foobar.scss | node-sass --output-style compressed > foobar.css
```

**Comment by am11** [comment]
@spelufo it is because you are not reading the docs carefully. `-o` option is for output directory.

> You have examples for a thousand frameworks on the readme but your cli doesn't work.

Possibly.. This is an open source project and the philosophy that follow is: DIY

**Comment by glassdimly** [comment]
```
cat sass/test.scss | node-sass > test.css
{
  "message": "file to import not found or unreadable: base\nCurrent dir: ",
  "column": 9,
  "line": 1,
  "file": "stdin",
  "status": 1
}
```
I can cat this file at the path normally... but node-sass is not reading from the pipe properly.

**Comment by saper** [comment]
@glassimly Where are your imports? in "sass"? If so, node-sass has no way to figure out it should look there - it just receives some bytes on standard input coming out of nowhere...

**Comment by glassdimly** [comment]
@saper Thank you for your response. Isn't using cat with a pipe supposed to send text from standard input into node-sass for compilation? If I cat in the directory that the file is located it works. Are you saying that node-sass is not reading from standard input?
To clarify, this works:
```
cat ./test.scss | node-sass
```
It just spits compiled css into the terminal. Isn't this how it's supposed to work?
```
node-sass --help
  Example
    cat foobar.scss | node-sass --output-style compressed > foobar.css
```
Thanks for helping me to clear up any misunderstanding I might have.

**Comment by saper** [comment]
can you post your files (to gist.github.com or somewhere else convenient)? it is hard to guess what is going on...

**Comment by glassdimly** [comment]
Alright, I made a simple test to reproduce and thereby clarified things.

The actual bug/functionality here is that node-sass attempts to process @import relative to the current directory rather than from the directory of the file.

https://github.com/glassdimly/sass-bug-test

```
$ cat sasstest/test.scss | node-sass
{
  "message": "file to import not found or unreadable: test_import\nCurrent dir: ",
  "column": 9,
  "line": 6,
  "file": "stdin",
  "status": 1
}
$ cd sasstest/
$ cat test.scss | node-sass
.test .test-indent {
  font-weight: bold; }

.test_import {
  display: none; }

$ 
```

**Comment by saper** [comment]
node-sass has no idea where `test_import` is.

If you really want, you can do this


    cat sass/test.scss | ~/node_modules/node-sass/bin/node-sass --include-path sass

**Comment by glassdimly** [comment]
@saper Thank you, that's really helpful, and fixes my problem.
