### ISSUE TITLE
node-sass@1.0.1: [Windows Error ] %1 is not a valid win32 application

### ISSUE THREAD

**Issue by Subash** [sass/node-sass#468]
![windows_8__running_](https://cloud.githubusercontent.com/assets/3478693/4680995/750711b8-560f-11e4-8b0e-0816e236ddde.png)

**Comment by smohadjer** [comment]
I still see this error on windows 7 64-bit when using latest grunt-sass npm package. Here is what I see in Node console:

Loading "sass.js" tasks...ERROR
>> Error: %1 is not a valid Win32 application.
>> c:\test\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-11\binding.node

**Comment by xzyfer** [comment]
Please follow the steps in our troubleshooting guide and paste the output
into a gist.

**Comment by harole** [comment]
I have the same problem, which is fixed by reinstalling the node-sass.

**Comment by saper** [comment]
@subash you are installing ancient version of node-sass, the current version is node-sass@3.3.3

**Comment by mariorandrade** [comment]
I'm having the same issue and I'm using node 5.6.0 and node-sass 3.8.7 on Windows 7 64 Bit.  

Here's the current output:

`> cmd.exe /c gulp -b "E:\WORK\Dashboard\Website\Dashboard.Web" --color --gulpfile "E:\WORK\Dashboard\Website\Dashboard.Web\Gulpfile.js" build
[13:29:07] Using gulpfile E:\WORK\Dashboard\Website\Dashboard.Web\Gulpfile.js
[13:29:07] Starting 'clean'...
[13:29:08] Finished 'clean' after 131 ms
[13:29:08] Starting 'build'...
[13:29:08] Starting 'styles'...
[13:29:08] 'styles' errored after 253 ms
[13:29:08] Error: %1 is not a valid Win32 application.
E:\WORK\Dashboard\Website\Dashboard.Web\node_modules\node-sass\vendor\win32-ia32-11\binding.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (E:\WORK\Dashboard\Website\Dashboard.Web\node_modules\node-sass\lib\index.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (E:\WORK\Dashboard\Website\Dashboard.Web\node_modules\gulp-sass\index.js:183:21)
[13:29:08] Finished 'build' after 256 ms
Process terminated with code 1.
[13:29:08] gulp-inject 21 files into app.scss.`

What is causing this error?

**Comment by majianxiong** [comment]
What is the reason for the error

**Comment by mariorandrade** [comment]
This issue stopped happening after after installing **es6-promise**.

I've added this line on **gulpfile.js**

`var promise = require('es6-promise').polyfill();`

right after

`var gulp = require('gulp');`

**Comment by daisyHawen** [comment]
I have met this problem before.
And I refreshed my **node.js**.
then 
`npm install node-sass`
It's done.

Or you can try 
`npm rm node-sass`
`npm install node-sass`

**Comment by yihou** [comment]
@daisyHawen yay, you are right, I had the same issue and I reinstall local `node-sass` and its working now. Thanks

**Comment by ErisoHV** [comment]
@daisyHawen Thanks, it works

**Comment by ErisoHV** [comment]
@daisyHawen Thanks, it works
`npm rm node-sass
npm install node-sass`

**Comment by iwantmadaxe** [comment]
after replace the python 3.6.0 to 2.7.0 it's ok

**Comment by zhouhuan0910** [comment]
@Subash   it is Ok

**Comment by wangaimin** [comment]
thanks.it is OK

**Comment by stephenykk** [comment]
win7 64 node7.9
try reinstall node-sass, but not work; the lastest version is 4.5.x; 
try the old version `npm i node-sass@3.11.0`, so cool, it just  works!!
but i don't understand what happen inside..

**Comment by Y2KPRABU** [comment]
Issue is here there is a file named %ur proj path%\node_modules\node-sass\vendor\win32-x64-48\binding
this binding file is supposed to be an exe.
but sometimes its blocked by proxies or nw errors. so I downloads a file not found html file instead.
so the solution is to delete this file and remove node-sass and re install it
