### ISSUE TITLE
Windows: Cannot open include file: 'stdbool.h'

### ISSUE THREAD

**Issue by jmcbee** [sass/node-sass#469]
> g:\www\luto\node_modules\gulp-sass\node_modules\node-sass\libsass\sass.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory (..\libsass\util.cpp) [g:\www\ luto\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]

**Comment by tatanano** [comment]
I added <mysql.h> in my code. 
After that I can see this message . 
" Cannot open include file: 'stdbool.h': No such file or directory "
Please help me .
