### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by streamich** [sass/node-sass#542]
Throws an `Segmentation fault (core dumped)` error when processing an empty file.

**Comment by aaronBeryUcl** [comment]
I received this error from creating an infinite loop of includes

I included a patterns listings scss file

within I accidently included patterns.scss instead of anotherfile.scss

**Comment by xzyfer** [comment]
This is a different issue. Please create a simple GitHub repo that shows this issue. Create a new node-sass issue with a link to that repo so we can this locally and debug.
