### ISSUE TITLE
Compiling should create output directory

### ISSUE THREAD

**Issue by SebastianOsuna** [sass/node-sass#574]
Hello guys,

I was using the library to build compile a scss file. I noticed the library doesn't use something like `mkdir` or `mkdirp` to create the output directory in case it doesn't exists.

Here is the command I used:
 `node-sass --output-style compressed src/css/my_project.scss lib/css/my_project.min.css`

Thanks

**Comment by am11** [comment]
`npm install node-sass@2.0.0` is released!
Checkout the release notes: https://github.com/sass/node-sass/releases/tag/v2.0.0

**Comment by nozpheratu** [comment]
Does this only apply to the CLI? Doesn't appear to work when I call the render function from JavaScript.

**Comment by xzyfer** [comment]
@nozpheratu as is made clear in the documentation, the `render` functions return the result of the compilation as a `Buffer`. It's you're responsibility to write it to disk if that's what you want.
