### ISSUE TITLE
Windows 8.1 - Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by iMoses** [sass/node-sass#580]
Installation was successful and when I run node-sass on a single file it works like a charm.
But when I try to use it as part of my script it always throws the same error.

```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
```

my code is simple:

```
var file = sass.renderSync({file: file_path});
```

It works great when I run it on Ubuntu 14, only on my Windows 8.1 I have this problem.

I'm using:
Node v0.10.34
Node-sass v2.0.0-beta
Npm v1.4.28

**Comment by alejandro85** [comment]
Help me! Please.

Error: `libsass` bindings not found. Try reinstalling `node-sass`?

C:\wamp\www\laravel\test>node -v
v0.10.28
C:\wamp\www\laravel\test>npm -v
1.4.9
C:\wamp\www\laravel\test>node -p process.arch
x64
C:\wamp\www\laravel\test>node
require('node-sass')
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
-------------------------------------------------------------------------------------------

node_modules/node-sass/lib/index.js

not found files.
not exist files in the locate

c:\wamp\www\test\laravel\node_modules\node-sass/build/Debug/binding.node, 
c:\wamp\www\test\laravel\node_modules\node-sass/build/Release/binding.node
c:\wamp\www\test\laravel\node_modules\node-sass/vendor/win32-x64-node-0.10/binding.node

function getBinding() {
  var candidates = [
    path.join(__dirname, '..', 'build', 'Debug', 'binding.node'),
    path.join(__dirname, '..', 'build', 'Release', 'binding.node'),
    path.join(__dirname, '..', 'vendor', process.sassBinaryName, 'binding.node')
  ];

  var candidate = candidates.filter(fs.existsSync).shift();

  if (!candidate) {
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
  }

  return candidate;
}


Thanks.

**Comment by bORm** [comment]
+1

**Comment by naveenraina** [comment]
+1

**Comment by xzyfer** [comment]
`+1`ing a closed issue serves no purpose. Please open a new issue **after** following the [TROUBLESHOOTING guide](TROUBLESHOOTING.md).
