### ISSUE TITLE
outFile not working anymore

### ISSUE THREAD

**Issue by philippkuehn** [sass/node-sass#582]
Before version 2.0 this worked fine:

``` javascript
sass.renderFile({
  file: 'assets/scss/style.scss',
  outFile: 'assets/css/style.css',
  outputStyle: 'compressed'
});
```

And with version 2.0 the outFile will be not generated with this code:

``` javascript
sass.render({
  file: 'assets/scss/style.scss',
  outFile: 'assets/css/style.css',
  outputStyle: 'compressed'
});
```

**Comment by myxibrium** [comment]
I don't see a single reference to the success callback on the Github page: https://github.com/sass/node-sass

**Comment by am11** [comment]
Four yrs. back it was introduced in v2: https://github.com/sass/node-sass/blob/v2.0.0-beta/README.md#usage. The API was changed again in v3.

**Comment by repnox** [comment]
It would be nice to have an example on the readme of compiling scss and writing it to the filesystem as this is the most common use case, especially if a lot of backwards incompatible changes get made. I assumed that outFile means it gets written automatically. I think most people will assume this.

**Comment by SinGlEBW** [comment]
I also thought that outFile should work automatically, but in fact I didn't understand what it does at all. I use my own approach

`let writeableStream = fs.createWriteStream("style.css");
render({file: 'src/css/scss/style.scss'}, (err, result) => {
  if(err)
    console.error(err);
  else
    writeableStream.write(result.css)
 
});`
