### ISSUE TITLE
[FR] output file dependencies for incremental compilation support

### ISSUE THREAD

**Issue by amitport** [sass/node-sass#590]
if given a sass file, node-sass could output the files that it depends on (imports - optionally recursive) then it would be relatively easy to implement incremental compilation via tools like [gulp](https://github.com/gulpjs/gulp)+[gulp-changed](https://github.com/sindresorhus/gulp-changed)

Any chance that node-sass will support such an function?

**Comment by am11** [comment]
Hi @amitport, take a look at https://github.com/xzyfer/sass-graph! It does what you are looking for. :)

**Comment by amitport** [comment]
@am11 Thanks! I think your previous suggestion was already good enough for this purpose, but I'm not sure. Generally, having the result after only a full node-sass compilation is OK, since I'm doing an incremental compilation not just analysis. In any case, I haven't got around to making this experiment yet, hopefully, I'll have a chance next weekend.

**Comment by xzyfer** [comment]
You can use sass-graph in your gulp watcher or gulp changed. It'll give you
an array of sass files that your changed file in imported by. Then you can
just pass those files into your normal gulp compilation task.

**Comment by amitport** [comment]
@xzyfer, but don't already know which files I need to watch from `stats.includedFiles`? remember I run an initial compilation. Can't I just keep a mapping (processed.stats.includesFiles)->sourceFile?

**Comment by xzyfer** [comment]
I think it might be a little more difficult that it seems. FWIW here is my current gulp setup for incremental sass compilation https://gist.github.com/xzyfer/1225f52c370b511c1fed
