### ISSUE TITLE
style.css compiles inside /sass folder no matter which path is set

### ISSUE THREAD

**Issue by vedranjaic** [sass/node-sass#595]
Hello, sorry if this was asked before, but I'm not finding anything about it.
No matter what path I set in my gulpfile, style.css gets compiled inside sass folder.
Problem persists using either gulp-sass or gulp-ruby-sass

Ex,
`.pipe(gulp.dest('.'))`
compiles in `project/sass/style.css` instead of `project/style.css`

`.pipe(gulp.dest('/css'))`
compiles in `project/css/sass/style.css` instead of `project/css/style.css`

etc...
Does anyone know how to fix this?

**Comment by kevva** [comment]
Wrong place to report this. `gulp-ruby-sass` doesn't even use this module.
