### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by Larivact** [sass/node-sass#596]
It would be cool if you add something like the following note to the installation paragraph. Without knowing this I got a bunch of errors and I would like to prevent that anyone in future will experience the same stupid problems.

If you have multiple VS versions, use npm install with the --msvs_version=2013 flag also use this flag when rebuilding the module with [node-gyp](https://github.com/TooTallNate/node-gyp) or [nw-gyp](https://github.com/rogerwang/nw-gyp).

**Comment by am11** [comment]
This is indeed a good idea.
Would you like to send a pull request? Here is [a good example](https://github.com/sass/node-sass/pull/594).
