### ISSUE TITLE
A way to get notified on new releases?

### ISSUE THREAD

**Issue by Larivact** [sass/node-sass#597]
My new project heavily depends on node-sass. I just wondered why my success callback got a string instead of an object as the parameter. Your documentation clearly stated that the success callback is passed an object. Thankfully I noticed the inconspicuous comment in the example below that this is new in v2. Until that point I wasn't even aware of the new release.

Now I would like to get notified on every release of node-sass.
I know that git-hub has a watch feature, but with that I get notified on all conversations. And frankly I don't care about people opening issues on your project. I guess I am blaming git-hub. It isn't your fault. It is embarrassing that such an important feature is missing.
Is it possible to open an issue for git-hub itself ? :]

Maybe it would be possible to setup something like an email notification system ?

**Comment by kevva** [comment]
https://github.com/yeoman/update-notifier

**Comment by am11** [comment]
You can subscribe to Atom feed:  https://github.com/sass/node-sass/releases.atom.
You can use [Sibbell](http://sibbell.com/), which uses GitHub API and send you notifications.
Also, @andrew tweet about new releases, so you can follow `@nodesass` on twitter.

Besides, you can always [contact](https://github.com/contact) GitHub team and share your thoughts.

PS: just like its Sass not SASS and its CSS not Css, its GitHub not git-hub :)

**Comment by Larivact** [comment]
Thanks for Sibbell! It looks promising.

**Comment by bocharsky-bw** [comment]
Thank you @am11 ! Your suggestion to use Atom is cool!

**Comment by TomasVotruba** [comment]
There is also a way how to get notified by email: http://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases

I prefer that to RSS, since I don't use it.

**Comment by andrew** [comment]
Also can use https://libraries.io/npm/node-sass

**Comment by TomasVotruba** [comment]
@andrew Wow, thanks! Looks great. How are you satisfied with it?

I saw similar service, but it was paid after 2 weeks.

**Comment by andrew** [comment]
@TomasVotruba I've been building http://libraries.io myself for a couple years now, it's all open source and new version notifications will always be free!

**Comment by TomasVotruba** [comment]
@andrew I could not imagine more awesome answer :) wow.

Do you have a Facebook page or Tweet I could share?
And place I could support you?

**Comment by andrew** [comment]
Twitter: https://twitter.com/librariesio working on getting an opencollective page setup for donations at the moment

**Comment by xzyfer** [comment]
Official channels for node-sass and LibSass are

- Twitter - https://twitter.com/nodesass
- Slack - https://libsass-slack.herokuapp.com/

Generic methods for getting release updates of node modules

- "Watch" their GitHub repo
- http://libraries.io
- Subscribe to GitHub atom feeds - https://github.com/<org>/<repo>/releases.atom

**Comment by TomasVotruba** [comment]
@xzyfer I meant my whole message to @andrew . Sorry it looks confusing.

**Comment by xzyfer** [comment]
@TomasVotruba yep I got that. Just wanted to leave an offical word for anyone else who comes across this.

**Comment by TomasVotruba** [comment]
@xzyfer Oh, I see.

**Comment by insign** [comment]
https://sibbell.com

**Comment by RishabhTayal** [comment]
Hi, I am working on an iOS which let's you get notified when there is a new release available on any Github repository. Testers and contributors are welcome.

https://github.com/RishabhTayal
