### ISSUE TITLE
npm ERR! 404 404 Not Found: gulp-saas

### ISSUE THREAD

**Issue by anandchavan** [sass/node-sass#600]
Hi,

I am getting below error on windows multipoint server 2012, please check. 

Thanks in advance!

Here is error log from console - 

npm WARN package.json @ No repository field.
npm ERR! 404 404 Not Found: gulp-saas
npm ERR! 404
npm ERR! 404 'gulp-saas' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-saas"
npm ERR! cwd D:\test\tester
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\test\tester\npm-debug.log
npm ERR! not ok code 0

Here is error log from npm-debug.log -

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp-saas' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 warn package.json @ No repository field.
6 verbose readDependencies using package.json deps
7 verbose cache add [ 'gulp-saas', null ]
8 verbose cache add name=undefined spec="gulp-saas" args=["gulp-saas",null]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'gulp-saas',
9 verbose parsed url   path: 'gulp-saas',
9 verbose parsed url   href: 'gulp-saas' }
10 silly lockFile 84cf557d-gulp-saas gulp-saas
11 verbose lock gulp-saas C:\Users\Administrator\AppData\Roaming\npm-cache\84cf557d-gulp-saas.lock
12 silly lockFile 84cf557d-gulp-saas gulp-saas
13 silly lockFile 84cf557d-gulp-saas gulp-saas
14 verbose addNamed [ 'gulp-saas', '' ]
15 verbose addNamed [ null, '*' ]
16 silly lockFile 1c147f9e-gulp-saas gulp-saas@
17 verbose lock gulp-saas@ C:\Users\Administrator\AppData\Roaming\npm-cache\1c147f9e-gulp-saas.lock
18 silly addNameRange { name: 'gulp-saas', range: '*', hasData: false }
19 verbose request where is /gulp-saas
20 verbose request registry https://registry.npmjs.org/
21 verbose request id 64879363de02c008
22 verbose url raw /gulp-saas
23 verbose url resolving [ 'https://registry.npmjs.org/', './gulp-saas' ]
24 verbose url resolved https://registry.npmjs.org/gulp-saas
25 verbose request where is https://registry.npmjs.org/gulp-saas
26 info trying registry request attempt 1 at 03:31:04
27 http GET https://registry.npmjs.org/gulp-saas
28 http 404 https://registry.npmjs.org/gulp-saas
29 verbose headers { date: 'Sat, 03 Jan 2015 21:59:44 GMT',
29 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
29 verbose headers   'content-type': 'application/json',
29 verbose headers   'cache-control': 'max-age=0',
29 verbose headers   'content-length': '52',
29 verbose headers   'accept-ranges': 'bytes',
29 verbose headers   via: '1.1 varnish',
29 verbose headers   age: '0',
29 verbose headers   'x-served-by': 'cache-sn86-SIN',
29 verbose headers   'x-cache': 'MISS',
29 verbose headers   'x-cache-hits': '0',
29 verbose headers   'x-timer': 'S1420322384.076978,VS0,VE801',
29 verbose headers   'keep-alive': 'timeout=10, max=50',
29 verbose headers   connection: 'Keep-Alive' }
30 silly registry.get cb [ 404,
30 silly registry.get   { date: 'Sat, 03 Jan 2015 21:59:44 GMT',
30 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
30 silly registry.get     'content-type': 'application/json',
30 silly registry.get     'cache-control': 'max-age=0',
30 silly registry.get     'content-length': '52',
30 silly registry.get     'accept-ranges': 'bytes',
30 silly registry.get     via: '1.1 varnish',
30 silly registry.get     age: '0',
30 silly registry.get     'x-served-by': 'cache-sn86-SIN',
30 silly registry.get     'x-cache': 'MISS',
30 silly registry.get     'x-cache-hits': '0',
30 silly registry.get     'x-timer': 'S1420322384.076978,VS0,VE801',
30 silly registry.get     'keep-alive': 'timeout=10, max=50',
30 silly registry.get     connection: 'Keep-Alive' } ]
31 silly lockFile 1c147f9e-gulp-saas gulp-saas@
32 silly lockFile 1c147f9e-gulp-saas gulp-saas@
33 error 404 404 Not Found: gulp-saas
33 error 404
33 error 404 'gulp-saas' is not in the npm registry.
33 error 404 You should bug the author to publish it
33 error 404
33 error 404 Note that you can also install from a
33 error 404 tarball, folder, or http url, or git url.
34 error System Windows_NT 6.2.9200
35 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-saas"
36 error cwd D:\test\test1
37 error node -v v0.10.35
38 error npm -v 1.4.28
39 error code E404
40 verbose exit [ 1, true ]

**Comment by am11** [comment]
This belongs to gulp-sass https://github.com/dlmanning/gulp-sass.
Also, you are mistyping the name in command: its gulp-sass not gulp-saas. :)
