### ISSUE TITLE
Source map not generated through API

### ISSUE THREAD

**Issue by jenius** [sass/node-sass#605]
I feel like this one is either something dumb I'm missing or something quick you guys can fix. I see that you have a test for source map generation through the CLI, but not through the API. And when I try to generate one through the API, it's coming up blank.

Reproduce:

```js
sass.render({
  sourceMap: true,
  data: "stylesheet blah blah",
  success: function(res){ console.log(res.map) }
});
```

This logs out `{}`, unfortunately.

**Comment by am11** [comment]
Possible duplicate https://github.com/sass/node-sass/issues/591.

You need to set outFile and file option to make the maps generated (with v2.0.0, you will only require to set outFile option in case of data).

**Comment by jenius** [comment]
Just got this and came back here to comment. I feel like it should be made clear under the `sourceMap` option documentation that this option requires 2 other options to be set or it will do nothing. It seems like the guy who files 591 said he would PR clarity in the docs, did he never do this? I can do it now if not, only takes a minute.

**Comment by am11** [comment]
In case of `data`, we need to set `outFile` option as well so to make `sourceMap` option take effect.
This is how it will be with forthcoming v2.0.0 (for which I am building binary right now). 
Sure thing, PRs are always welcome! :)

Sorry for the haste, I thought the solution addresses this issue.
