### ISSUE TITLE
min & max functions removes first item from list

### ISSUE THREAD

**Issue by sup3rman** [sass/node-sass#608]
Since node-sass > 1.1.X the min and max functions have begun to remove the first item when passed a list variable.

To reproduce:
```
$range: 1px, 2px, 3px, 4px;
@debug $range;//1px, 2px, 3px, 4px
$test: min($range...);
@debug $test;//1px
@debug $range;//2px, 3px, 4px
$test: max($range...);
@debug $test;//4px
@debug $range;//3px, 4px
$test: max($range...);
@debug $test;//4px
@debug $range;//4px
```

**Comment by browniefed** [comment]
Sounds like a libsass issue

**Comment by am11** [comment]
Agree with @browniefed. This belongs to libsass.

Here are the reproduction steps with output generated by SassMeister:

(perhaps there is a little error in your example, `$range` would remain the same you are dropping a number at every step)

ruby-sass (v3.4.9): http://sassmeister.com/gist/85a836dd52663840509a
libsass (v3.1.0-beta): http://sassmeister.com/gist/f51caa25837f6d4684fb (exact same result with v3.1.0 final version, I have just tested locally)

Next step? See https://github.com/sass/node-sass/issues/585#issuecomment-68176226.

//cc @xzyfer, @mgreter

**Comment by sup3rman** [comment]
No, there is not a mistake in my example. That IS the error... that min and max removes the first item from the list.

**Comment by am11** [comment]
Oh well I missed that part.
But I showed the output of the latest version, which yields different kind of invalid result. :)

**Comment by am11** [comment]
BTW, the bleeding edge version of node-sass is v2.0.0-beta. You may want to update node-sass.

**Comment by sup3rman** [comment]
This bug exists in ALL node-sass after version 1.0.3.

**Comment by am11** [comment]
I know, I was just giving you a heads-up because your output is not matching that of node-sass latest version..

**Comment by sup3rman** [comment]
Oh, then in that case: thanks for the heads up! Unfortunately I use min() and max() heavily so upgrading version is not an option right now.
