### ISSUE TITLE
--include-path doesn't work in 2.0.0-beta

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#610]
In the process of moving a project over to Libsass I've notice `@import`s are not using the `--include-path`s in `node-sass@2.0.0-beta`

This was a late bug in Libsass 3.1.0 that was fixed just before going stable.

Libsass commit: https://github.com/sass/libsass/commit/fa222821fccab6a9d9cd09a1cd8e320f958a4497
SassC commit: https://github.com/mgreter/sassc/commit/25d2bb355b21e8221472928ee7f9468369c54894

**Comment by am11** [comment]
The include files option is set in both the render and renderSync cases: [binding.cpp#L160](https://github.com/sass/node-sass/blob/a11fafdc744332f5b3bc9de2900bf0a20aa64361/src/binding.cpp#L160).
The input path is set differently. In case of renderFile (sync or async), we set it to ctor: [RenderFile](https://github.com/sass/node-sass/blob/a11fafdc744332f5b3bc9de2900bf0a20aa64361/src/binding.cpp#L304) and [RenderFileSync](https://github.com/sass/node-sass/blob/a11fafdc744332f5b3bc9de2900bf0a20aa64361/src/binding.cpp#L321), while in case of async variants, we set it as option: [binding.cpp#L148](https://github.com/sass/node-sass/blob/a11fafdc744332f5b3bc9de2900bf0a20aa64361/src/binding.cpp#L148).

With CLI, we call `render()` (the async function) in JS, which corresponds to `Render()` or `RenderFile()` in cpp (which depends on [this condition](https://github.com/sass/node-sass/blob/a11fafdc744332f5b3bc9de2900bf0a20aa64361/lib/index.js#L223)).

Is there a broken functionality which we need to be fixed? Currently all tests are passing on Linux and Windows (pointing to libsass v3.1.0 stable).

**Comment by xzyfer** [comment]
I ran into this issue on node-sass 2.0.0-beta and with libsass master.
Maybe node-sass master has patched this issue. Include paths were broken in
Libsass until the stable release. Include path isn't covered by sass-spec.

**Comment by am11** [comment]
Actually we have bunch of include-files tests in both [cli.js](https://github.com/sass/node-sass/blob/520dd86a1461ac28b2e6e8fb365eb7ffeaeb4b0c/test/cli.js) and [api.js](https://github.com/sass/node-sass/blob/520dd86a1461ac28b2e6e8fb365eb7ffeaeb4b0c/test/api.js). The good news is TravisCI is passing. So I think we are golden! :)

The weird thing is, it was passing the TravisCI build just before v2.0.0-beta was released (I commented out free() and tested it [just before the release](https://github.com/sass/node-sass/pull/577#issuecomment-67904885)). Perhaps we are not testing the critical aspect of the feature? :worried:

**Comment by xzyfer** [comment]
Interesting. I'll put together a minimal test case in the morning.

**Comment by xzyfer** [comment]
I can't reproduce this anymore. Must've been [PEBCAK](http://en.wiktionary.org/wiki/PEBCAK).

**Comment by bezoerb** [comment]
There's also an issue with includePaths in version 2.0.1. See #812
