### ISSUE TITLE
Source maps don't work when outputStyle set to "compressed"

### ISSUE THREAD

**Issue by joelworsham** [sass/node-sass#612]
They simply don't work. Inspector just shows the compressed stylesheet. Works fine in same configuration when set to "nested".

**Comment by am11** [comment]
Please post minimal steps of reproduction with expected and actual output. Also, which version of node-sass are you using?

**Comment by joelworsham** [comment]
Gruntfile task:
```
sass: {
    options: {
        sourceMap: true,
        outputStyle: 'compressed'
    },
    front: {
        files: {
            'style.css': 'assets/sass/main.scss'
        }
    },
    admin: {
        files: {
            'admin.css': 'assets/sass/admin/admin.scss'
        }
    }
},
```

Expected: Source maps to work.
Actual: They did not work.

node-sass version:  0.17.0

**Comment by am11** [comment]
That is quite an old version.
The edge version is v2.0.0-beta, what uses libsass 3.1.0-beta which has improved significantly in terms of source-maps. The v2.0.0 stable is on its way, which improves more.

OAN, the grunt task doesn't count as the most applicable steps of reproduction here in node-sass issue tracker. We expect something more concrete, like sass code and how you would run it with mere node-sas API to produce the issue. 

Note that node-sass does not compile code or produce source-maps, it is eventually libsass which does all the heavy-lifting job. So the shorter the dependency chain is, the easier is to spot the bug.

**Comment by joelworsham** [comment]
Sorry, that was actually the version of "grunt-sass", which uses node-sass.

The version of node-sass itself is 1.2.3

**Comment by christianseel** [comment]
I'm experiencing the same issue with node-sass version 2.0.1!
This is my render function:
```
    nodesass.render({
		    file: file,
		    outFile: path.resolve(outFile),
		    
		    includePaths: [ 'assets/tpl/sources/scss/', 'assets/tpl/sources/', 'assets/tpl/sources/bower_components/' ],
		    
		    sourceMap: true,
		    outputStyle: 'nested', // 'compressed';
		    
		    success: function(result) {
	            
	            fs.writeFile(outFile+'.map', result.map);
	            fs.writeFile(outFile, result.css);
			},
			
		    error: function(error) {
		        console.log(color.red('ERROR found in ') + color.red.bold(path.basename(file)) + color.red(': '+error.message));
		    }
	    });
```
Sourcemaps work if outputStyle is set to `nested`. If I use `compressed` it seems like the `@import`s are not found, because chrome always shows the main file as source, not the imported scss file.

**Comment by christianseel** [comment]
@am11 May I ask you to check this issue again? I'm still having this problem with node-sass 2.0.1.

**Comment by am11** [comment]
@chriseppstein, if you getting the incorrect mappings with `outputStyle: compressed` and correct mappings with `outputStyle: nested` but all the paths are correct, then this is a libsass issue (since the source-map are emitted by libsass).
