### ISSUE TITLE
Add support for --line-numbers

### ISSUE THREAD

**Issue by wdamien** [sass/node-sass#614]
sassc / libsass have support for --line-numbers, it would be great if node-sass also supported this feature.

Works (css file includes line numbers)
```sassc --line-numbers file.scss > file.css```

Doesn't work (css file outputs fine, but with no line numbers)
```node-sass --line-numbers --output-style compressed file.scss file.css```

**Comment by am11** [comment]
> The option which produces comment for each rule block in output, with corresponding line-number to source file.

We definitely have this option with another name `--source-map`. :smile:  :tada: 

But note that it will not work with the conflicting option `--output-style compressed` (we essentially refer `sourceComment` as a debug info, checkout [command line help](https://github.com/sass/node-sass/#command-line-interface) list). 

To wit:

```bash
node-sass --source-comments --stdout /path/to/your/favourite/filename.scss

# will print the following on stdout (console)

/* line 1, /path/to/your/favourite/filename.scss */
test {
  one: 1;
  two: 2; }
```
