### ISSUE TITLE
Sourcemaps broken?

### ISSUE THREAD

**Issue by polarathene** [sass/node-sass#619]
I'm new to all this, I've been following a gulp workflow but noticed something is wrong with my sourcemap. Have put gulp aside and just compiled my scss file with node-sass and a sourcemap. I've tried each of the options(embedded, external, sourceContent included, etc). The mapping according to a visual tool shows the scss file is mapped correctly, but the output css doesn't appear to be, everything is mapped from 0. I've used the tool with the sourcemap produced for the input/output css files from autoprefixer and they map correctly. So this issue must be related to node-sass or libsass?

All my packages are straight up `npm install package`. You can see the visualizer tool with my test scss/css [here](http://sokra.github.io/source-map-visualization/#base64,LnRoaW5nIHsKICBmaWx0ZXI6IHNlcGlhKDEpOwogIGNvbG9yOiAjM2JiZmNlOyB9CgouYm9vdHMgewogIGZpbHRlcjogc2VwaWEoMSk7CiAgY29sb3I6ICNhMjI7IH0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtiYXNlNjQsZXdvSkluWmxjbk5wYjI0aU9pQXpMQW9KSW1acGJHVWlPaUFpZUcxaGFXNHVZM056SWl3S0NTSnpiM1Z5WTJWeklqb2dXd29KQ1NKdFlXbHVMbk5qYzNNaUNnbGRMQW9KSW5OdmRYSmpaWE5EYjI1MFpXNTBJam9nV3dvSkNTSWtZbXgxWlRvZ0l6TmlZbVpqWlR0Y2NseHVKSEpsWkRvZ0kyRXlNanRjY2x4dVhISmNibHh5WEc0dWRHaHBibWQ3SUdacGJIUmxjam9nYzJWd2FXRW9NU2s3SURzZ1kyOXNiM0k2SkdKc2RXVTdmVnh5WEc1Y2NseHVMbUp2YjNSemUxeHlYRzRnSUdacGJIUmxjam9nYzJWd2FXRW9NU2s3WEhKY2JpQWdZMjlzYjNJNklDUnlaV1E3WEhKY2JuMGlDZ2xkTEFvSkltMWhjSEJwYm1keklqb2dJa0ZCU1VFc1FVRkJVU3hCUVVGUkxFRkJRVmtzUVVGS2NrSXNRVUZOVUN4QlFVTkZMRUZCUVZFc1FVRkRVaXhCUVZCSklpd0tDU0p1WVcxbGN5STZJRnRkQ24wPSAqLw==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoieG1haW4uY3NzIiwic291cmNlcyI6WyJtYWluLnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiJGJsdWU6ICMzYmJmY2U7XHJcbiRyZWQ6ICNhMjI7XHJcblxyXG5cclxuLnRoaW5neyBmaWx0ZXI6IHNlcGlhKDEpOyA7IGNvbG9yOiRibHVlO31cclxuXHJcbi5ib290c3tcclxuICBmaWx0ZXI6IHNlcGlhKDEpO1xyXG4gIGNvbG9yOiAkcmVkO1xyXG59Il0sIm1hcHBpbmdzIjoiQUFJQSxBQUFRLEFBQVEsQUFBWSxBQUpyQixBQU1QLEFBQ0UsQUFBUSxBQUNSLEFBUEkiLCJuYW1lcyI6W119,JGJsdWU6ICMzYmJmY2U7DQokcmVkOiAjYTIyOw0KDQoNCi50aGluZ3sgZmlsdGVyOiBzZXBpYSgxKTsgOyBjb2xvcjokYmx1ZTt9DQoNCi5ib290c3sNCiAgZmlsdGVyOiBzZXBpYSgxKTsNCiAgY29sb3I6ICRyZWQ7DQp9) .

**Comment by polarathene** [comment]
I've read up on how the VLQ values are used to map code between files and with the help of that tool I linked previously and the working autoprefixer sourcemap, manually figured out the mapping values for my example.
[The broken libsass/node-sass output](http://sokra.github.io/source-map-visualization/#base64,LnRoaW5nIHsKICBmaWx0ZXI6IHNlcGlhKDEpOwogIGNvbG9yOiAjM2JiZmNlOyB9CgouYm9vdHMgewogIGZpbHRlcjogc2VwaWEoMSk7CiAgY29sb3I6ICNhMjI7IH0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPXhtYWluLmNzcy5tYXAgKi8=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoieG1haW4uY3NzIiwic291cmNlcyI6WyJtYWluLnNjc3MiXSwibWFwcGluZ3MiOiJBQUlBLEFBQVEsQUFBUSxBQUFVLEFBSm5CLEFBTVAsQUFDRSxBQUFRLEFBQ1IsQUFQSSIsIm5hbWVzIjpbXSwic291cmNlUm9vdCI6Ii4uLy4uL3Njc3MvIn0=,JGJsdWU6ICMzYmJmY2U7DQokcmVkOiAjYTIyOw0KDQoNCi50aGluZ3sgZmlsdGVyOiBzZXBpYSgxKTsgY29sb3I6JGJsdWU7fQ0KDQouYm9vdHN7DQogIGZpbHRlcjogc2VwaWEoMSk7DQogIGNvbG9yOiAkcmVkOw0KfQ==)
[Manual mappings edit on main.css.map file](http://sokra.github.io/source-map-visualization/#base64,LnRoaW5nIHsKICBmaWx0ZXI6IHNlcGlhKDEpOwogIGNvbG9yOiAjM2JiZmNlOyB9CgouYm9vdHMgewogIGZpbHRlcjogc2VwaWEoMSk7CiAgY29sb3I6ICNhMjI7IH0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPXhtYWluLmNzcy5tYXAgKi8=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoieG1haW4uY3NzIiwic291cmNlcyI6WyJtYWluLnNjc3MiXSwibWFwcGluZ3MiOiJBQUlBO0VBQVEsUUFBUTtFQUFVLE9BSm5COztBQU1QO0VBQ0UsUUFBUTtFQUNSLE9BUEkiLCJuYW1lcyI6W10sInNvdXJjZVJvb3QiOiIuLi8uLi9zY3NzLyJ9,JGJsdWU6ICMzYmJmY2U7DQokcmVkOiAjYTIyOw0KDQoNCi50aGluZ3sgZmlsdGVyOiBzZXBpYSgxKTsgY29sb3I6JGJsdWU7fQ0KDQouYm9vdHN7DQogIGZpbHRlcjogc2VwaWEoMSk7DQogIGNvbG9yOiAkcmVkOw0KfQ==)

As you can't see the actual sourcemap via the links,
Original:
```
{
    "version":3,
    "file":"xmain.css",
    "sources":["main.scss"],
    "mappings":"AAIA,AAAQ,AAAQ,AAAU,AAJnB,AAMP,AACE,AAAQ,AACR,AAPI",
    "names":[],
    "sourceRoot":"../../scss/"
}
```
Manual Edit:
```
{
    "version":3,
    "file":"xmain.css",
    "sources":["main.scss"],
    "mappings":"AAIA;EAAQ,QAAQ;EAAU,OAJnB;;AAMP;EACE,QAAQ;EACR,OAPI",
    "names":[],
    "sourceRoot":"../../scss/"
}
```

What libsass/node-sass is missing to do is provide proper mapping data for the output css. Column values(1st letter per block), instead it is always using `A` which has a value of `0`. In addition it is not  using `;` between blocks to signify new lines on the output css, so everything is mapped to `line 1` only. This is fine if you output compressed I guess, just the lack of column data that is preventing the source map output to be useful.

**Comment by xzyfer** [comment]
Libsass has some known issues with sourcesmap at the moment. We believe most of these have been address in a recent patch that will land in Libsass 3.2.

**Comment by polarathene** [comment]
That's good to know :) I've read plenty of confusion over github/stackoverflow/blogs with libsass and sourcemaps. node-sass doesn't point out that there are any issues with sourcemaps, and likewise I came across the cited communities whom were under the impression the sourcemap output was fine and blaming issues on other projects like autoprefixer. Tripped me up for a while trying to understand what I was doing wrong :P

I saw your 3.2 release on libsass issues, seems we will have to wait until around mid Feb before this fix is easily available? Am I able to build libsass from source and get node-sass to use it, or will I run into issues? In the meantime I guess for sourcemaps I can compile with ruby-sass.

**Comment by xzyfer** [comment]
For local testing you can checkout node-sass into your node_modules then
point the node-sass .gitmodules at your Libsass master.

Use the instructions on node-sass readme on how to compile node-sass
manually.

**Comment by polarathene** [comment]
I've tried to follow the instructions as well as any other solutions I came across. I have some success with the build then it errors out with `error LNK2001: unresolved external symbol` errors. Something to do with msbuild. It seems to be problematic to use node-gyp with Win7_x64 +  node_x64, it's quite evident in another issue for node-sass. 

I could try using a linux vm to build it, though would that mean I wouldn't be able to transfer it back to windows to use?

**Comment by xzyfer** [comment]
Sorry I'm not familiar with the windows build /cc @am11 

If you build it on linux you will not be able to transfer the build files to Windows. The compilation in platform specific.

**Comment by am11** [comment]
@polarathene, this is not an issue with node-sass per se. 

Libsass added some source files after v3.1.0, which are not referenced in node-sass yet.
You can add those into binding.gyp. So assuming have VS2013 Update 4+ (professional, community, express-desktop or even VS2015 preview) installed, follow these steps:

* before [line 16](https://github.com/sass/node-sass/blob/af72ccc49681e3db011184ecf4e19365c349315f/binding.gyp#L16), add `'src/libsass/cssize.cpp',` 
* before [line 28](https://github.com/sass/node-sass/blob/af72ccc49681e3db011184ecf4e19365c349315f/binding.gyp#L28) add `'src/libsass/position.cpp'`, hit Ctrl+Shift+B in Visual Studio
* in node-sass repo's root, run `node scripts/build -f`.

Later if you want to build with VS, open the solution file located at `<node-sass-repo-root>/build/binding.sln` and rebuild. Then you can attach to any running `node` process and debug with VS.

Note, node-gyp builds VS solution file on Windows, Makefile on Linux and Xcode files on Mac/Darwin targets.

Also, to explicitly make a debug release, run `node-gyp rebuild -d`. With VS you can toggle between Release and Debug configurations as well.

Hope this *relaxes* the situation. :)

**Comment by polarathene** [comment]
Thanks @xzyfer  and @am11 , that got it working. Had to append `--msvs_version=2013` to `node scripts/build -f` in my case. In future is there any easy way for me to figure out what new sources to add and where(as line order seems important?). Or will it be easier when the appveyor automation is done?

The sourcemap updates are great. Few minor issues and one important one that I'll go bring up with libsass, cheers for the help :)

**Comment by polarathene** [comment]
Issue is up on libsass. node-sass might be responsible for handling the optional `sourceRoot` property? It's not a big issue as gulp-sass with gulp-sourcemaps allows me to insert that. When using only node-sass though seems I have to manually add that property or prepend a relative filepath from sourcemap to source files in `sources`, it doesn't appear to be a listed option on node-sass. The rest of the bugs are probably related to libsass.

**Comment by josephdburdick** [comment]
Yeah, this is the end of the rabbit hole for me. I have to stay with ruby-sass until this is fixed.

**Comment by am11** [comment]
Closing in favor of https://github.com/sass/libsass/issues/837.
