### ISSUE TITLE
The `outFile` options does not work with `render()` or `renderSync()` in node-sass#2.0.0-beta

### ISSUE THREAD

**Issue by Herriau** [sass/node-sass#622]
Everything is pretty much in the title. It seems like the following code does not generate a css file like it used to in 1.x:

```
require('node-sass').render({
    data: '.hello { background: #fff; }',
    outFile: 'result.css'
})
```

**Comment by am11** [comment]
That is correct and this behavior is by design.

Going by the [release notes of v2.0.0-beta](https://github.com/sass/node-sass/releases/tag/v2.0.0-beta), under `Breaking Changes` it says:

> node-sass does not write output to disk from code usage. It will deliver the output which user can store in file/data-base or generate in-memory HTTP responses.

Note, the exception here is CLI usages (the third entry point). :)

**Comment by Herriau** [comment]
Thank you for the clarification. 
Please note that the README in 2.0.0-beta still advertizes `outFile` as a valid option though.

**Comment by am11** [comment]
Actually `outFile` is a valid option and the README states:

> 
 `outFile` specifies where the CSS will be saved. This option does not actually output a file, but is used as input for generating a source map.

**Comment by Herriau** [comment]
I am not sure I understand why the knowledge of where the CSS will eventually be saved is a necessity for generating the source map. From `lib/index.js` I understand it's used to generate the path of the `.map` file, but since the lib will not write the sourcemap file to disk either why is that required at all?

**Comment by am11** [comment]
Hi, please see this: https://github.com/sass/node-sass/issues/591 for some reasoning.

Bottom line:
In principle, source-map is used in source-to-source transpilation scenarios (in this case Scss <=> CSS). If one side of the equation is missing, it adversely affect the context and question the reason of having source-map in first place. Hence, the source-map will not be generated.

Note that all these decisions are transpiring in libsass.

However, v2.0.0-beta added two new options: [`sourcemapembed`](https://github.com/sass/node-sass#sourceMapEmbed) and [`sourcemapContents`](https://github.com/sass/node-sass#sourceMapcontents). Now if `sourceMapEmbed` is set to `true` along with `sourceMap` and you are using data-input, it should work without setting the `outFile` (which it doesn't and hence its an issue that needs to be reported to libsass).

**Comment by xzyfer** [comment]
Should `sourceMapEmbedded` not just enable sourcemaps? Having to enable a
secondary flag to get a feature to work is fraught with confusion IMHO.`

**Comment by am11** [comment]
I agree.

IMO, it would be best if this behavior is in libsass instead. Same goes for `sourceMapContents`.

@mgreter, here is the gist:


- `source_map_embed == true` and `source_map_conents == true` should emit source-map without needing the presence of `source_map`.
- `source_map_embed == true` should emit source-map without needing the presence of `output_path` and `source_map`, when `data` is available (regardless of `input_path` as well).

**Comment by xzyfer** [comment]
I'll look into this for 3.2.

**Comment by am11** [comment]
Since the reported issue is referring to the confusion caused by breaking change, this needs to be closed.

@xzyfer, I have opened the other issue in LibSass issue tracker.

**Comment by gpapin** [comment]
I just updated to the latest version and wanted to make you aware that the current readme is a bit misleading regarding this outputFile option 
>Specify the intended location of the output file. Strongly recommended when outputting source maps so that they can properly refer back to their intended files.

When I saw **Specify the intended location of the output file** I never suspected that now the file is not written on disk anymore. I had to find this issue to finally find out what was going on.

My point is, it's worth mentioning explicitly in this description that the file is not written

**Comment by saper** [comment]
@gpapin do you think you have an idea what the better wording would be? A pull request would be very handy!

**Comment by gpapin** [comment]
@saper I wrote what would have help me in this pull request: https://github.com/sass/node-sass/pull/1084

**Comment by saper** [comment]
Think you very much!
