### ISSUE TITLE
What should an importer function do if the requested file cannot be found?

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#632]
Say my custom importer function is called, asking for something called `'foo'`, and I determine that the file does not exist (i.e. the `@import 'foo'` is an error)...

I should be able to call `done` in some special way to explicitly indicate that the requested file does not exist, causing libsass to call my `error` callback with an appropriate error object (including the line number of the bad `@import`).

Something like `done(false)` or `done({file: false})` would be good.

**Comment by browniefed** [comment]
`done({contents: ''})` ?

**Comment by callumlocke** [comment]
That would appear to libsass as if the file does exist and it's just empty.
That's not the same thing.

**Comment by browniefed** [comment]
`done({contents: ' '})` toss a space in there?

**Comment by browniefed** [comment]
@callumlocke sorry thought you were asking to make it not error out.

**Comment by am11** [comment]
Sorry I am lost, what exactly is the requirement here?

Currently libsass produces the error if you only return the file from custom importer, which doesn't exist:

Synchronous:

```javascript
require('./').renderSync({
  data: '@import "foo.scss"',
  importer: function(u,p){
    return {file:"devNull"};
  }
});

// returns stderr

{
  "status": 1,
  "file": "stdin",
  "line": 1,
  "column": 9,
  "message": "file to import not found or unreadable: devNull\nCurrent dir: "
}
````

Asynchronous:

```javascript
require('./').render({
  data: '@import "foo.scss"',
  importer: function(u, p, done) {
    done({file:"devNull"})    // you can also return from asynchronous ignoring done
  },
  error: function(e){ console.error(e) }
});

// returns:

{ file: 'devNull' }   // <<-- this output on console is a workaround for v8/libuv, just ignore.
{ status: 1,
  file: 'stdin',
  line: 1,
  column: 9,
  message: 'file to import not found or unreadable: devNull\nCurrent dir: ',
  code: 1 }
```

**Comment by joshbroton** [comment]
I don't know if this belongs here (I'll also create another issue and post the # here), but when I try to compile using @import url(http://some.external/file) and I don't have internet access, I get this error:

Broken @import declaration of "https://fonts.googleapis.com/css?family=Mr+Dafoe" - timeout

**Comment by am11** [comment]
@joshbroton, there are two kinds of imports: CSS3 and Sass. 
If you have a CSS3 import, the URL will be emitted to the output CSS as is and the browser will take care of the URL. 
But in case of Sass import directive, with URL, LibSass does not download any resource from remote computer (see the discussion here: https://github.com/sass/libsass/pull/691). You will need to add custom importer, read the remote resource and pass it along to libsass as `data`.

@callumlocke, should we close this issue?

**Comment by callumlocke** [comment]
I still have a problem, but I think it actually stems from the way libsass has implemented custom importers, and I've started an issue there instead (sass/libsass#862)... if that one ever gets fixed then I might open a clearer issue here :)
