### ISSUE TITLE
Feature request: Output compilation errors to css.

### ISSUE THREAD

**Issue by strille** [sass/node-sass#633]
[Sass](https://github.com/sass/sass) has a clever feature where compilation errors are printed to the output css in a body:before selector, which causes them to show up in the browser. This is very useful when you have set up a build system which automatically compiles Sass to css on file changes.

Any chance seeing this in node-sass?

**Comment by am11** [comment]
(regardless of what we think about ruby-sass behavior)

With v2.0.0-beta, we have made some changes to API (or code) usage. For instance, we do not save anything on the disk but return the result back to user. So if the user didn't want to save the result but output it directly to some stream (httpResponse for instance), they don't get unnecessary IO operation. Similarly the errors are returned to a separate callback.

```javascript
require('node-sass').render({
  file: 'manifest.scss',  // a good idea, see https://twitter.com/Una/status/557195604137222144
  success: function(result) {
    // Here `result.css` (among other things) is a string, we will not
    // save it to filesystem, as saving to fs is not the only use case.
    // Therefore, we leave this decision to the consumer whatever
    // they want to do with the result.
  },
  error: function(error) {
    // Here `error.message`  (among other things) is a string.
    // you can write it to the stream or save it to logs or your
    // CSS file.
  },
});
```

The only time we write to disk is with CLI usage. With CLI, the error is printed to stderr.

The third usage is `renderSync`, where we let C++ throw the error directly to standard-error (stderr) stream (the error message in that case is a stringified JSON, in the previous two cases, the error is parsed as JS object literal). See readme and release notes for more details.

I think this approach is giving more control to the downstream consumer.

**Comment by strille** [comment]
Thanks, I didn't realise node-sass gave you that kind of control, I should have looked at the API before asking :-)
