### ISSUE TITLE
Hanging at `win32-ia32` exists; testing

### ISSUE THREAD

**Issue by davetgreen** [sass/node-sass#637]
Hello!

I use node-sass in a boilerplate I maintain for my team, and we're having a rather annoying issue with the installation hanging at this stage:

    'win32-ia32' exists; testing

If left alone, it completes this 'testing' after around an hour. In a lot of cases I've been able to get around the delay by cancelling the install and then immediately running it again.

I've read a few posts on other issues that suggest that this may be more of an issue with Node/NPM than node-sass but I'm yet to see a definitive answer or find a solution that works every time.

I'd be grateful if you could shed some light of this.

We're using Windows 7 (32bit, SP1), Node 0.10.33, NPM 2.1.11 and the version of node-sass we're trying to install is 1.2.3 (though the node-sass version seems to be irrelevant based on my testing).

Cheers,
Dave

**Comment by am11** [comment]
@davetgreen, please reopen your existing issue https://github.com/sass/node-sass/issues/524 and try answering the question.
