### ISSUE TITLE
Build failing on Travis Docker image

### ISSUE THREAD

**Issue by austinpray** [sass/node-sass#638]
Hello!

I know there are known issues with linux but I did not see this specific error when searching. We get this occasionally over on our Travis: https://travis-ci.org/roots/roots/jobs/48079124

```bash
> node-sass@2.0.0-beta install /home/travis/build/roots/roots/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
Binary downloaded and installed at /home/travis/build/roots/roots/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node
> node-sass@2.0.0-beta postinstall /home/travis/build/roots/roots/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js
npm ERR! cb() never called!
npm ERR! not ok code 0
```

Full log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/48079124/log.txt

**Comment by am11** [comment]
It does not seems to be a problem with node-sass, but npm cache issue. See http://stackoverflow.com/a/15483897/863980.

Apparently, the recent builds are not exhibiting the issue: https://travis-ci.org/roots/roots/builds.

**Comment by austinpray** [comment]
Ah okay. It was a super infrequent issue anyway. Just wanted to make sure you guys had as much info as possible to debug your linux issues. Thank you!
