### ISSUE TITLE
Not installing on Win7 64 - "node scripts/install.js"

### ISSUE THREAD

**Issue by Errvald** [sass/node-sass#640]
Getting the following error, not sure what's going on, but on Ubuntu/OS X installs with no problem.

```
npm ERR! Failed at the node-sass@2.0.0-beta install script.
npm ERR! node-sass@2.0.0-beta install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@2.0.0-beta install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! cwd E:\test
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0
```

**Comment by pamrichmond** [comment]
I am having the same problem.  Below shows ```node-sass@2.0.0-beta```, but the same error occurs when trying to install ```node-sass@1.2.3``` using the Zurb Foundation 5 CLI to create a Libsass project.
```
PS C:\temp> node -v
v0.10.36
PS C:\temp> npm -v
1.4.28
PS C:\temp> node -p process.arch
x64
PS C:\temp> cd /temp
PS C:\temp> npm install node-sass; node
|
> node-sass@2.0.0-beta install C:\temp\node_modules\node-sass
> node scripts/install.js


npm ERR! node-sass@2.0.0-beta install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@2.0.0-beta install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "node-sass"
npm ERR! cwd C:\temp
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0
```

**Comment by Errvald** [comment]
Any idea?

**Comment by pamrichmond** [comment]
I wasn't able to install those versions (2.0.0beta and 1.2.3). I used ```"node-sass": "~0.7.0"``` in my package.json based on another project that was working.

**Comment by am11** [comment]
I am not sure about it. I built the Windows x64 binaries on Win 8.1. 
I was under the impression than Windows binaries built with VS2013 do not require a separate configuration (like XP target) for seven?

Meanwhile you can test it by manually downloading the binary in `vendor/<os-specific-folder>/binding.node` from https://github.com/sass/node-sass-binaries/tree/v2.0.0-beta based on `node -p process.arch`. If it says `ia32` then create a directory called `win32-ia32` inside `node-sass/vendor` directory otherwise `win32-x64` then test with `node -p console.log(require('node-sass').info())`.

If the above solution works, that would mean this issue is fixed, because we have already fixed the download binary machinery which was broken in beta. If not then it is a broken binary issue which needs digging for seven-target (which I really hope is not the case here)..

**Comment by pamrichmond** [comment]
@am11, where is the ```node-sass/vendor``` directory?

**Comment by am11** [comment]
@pamrichmond, when we run `npm install node-sass`, our install script creates a directory called `vendor` at node-sass root. This directory doesn't exist in the repo (which I think it should with a .gitkeep).

**Comment by pamrichmond** [comment]
@am11 , I am new to node, npm, and node-sass, so I'm not sure where the folders should be placed. I tried creating these folders in several places unsuccessfully, but I'm guessing here. I'm willing to try again if you can be specific about the locations of the folders/files. Here is what I tried:
```
c:\temp\myprojectname\node_modules\node-sass\vendor\win32-x64\bindings.node
c:\temp\myprojectname\node_modules\node-sass\bin\win32-x64\bindings.node 
   (because an older working version used bin instead of vendor)
c:\Program Files\nodejs\node_modules\npm\node_modules\node-sass\vendor\win32-x64\bindings.node
c:\Program Files\nodejs\node_modules\npm\node_modules\node-sass\bin\win32-x64\bindings.node
```
Here is the output:
```
c:\temp\myprojectname>node -p console.log(require('node-sass').info())

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:13
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
```

**Comment by am11** [comment]
@pamrichmond, the first one is correct.

First, please execute these commands line by line: https://gist.github.com/am11/e5de3c49c219f0811e1d.

If it fails, please create a similar [GH gist](http://gist.github.com/) with the produced output of that script and share the link.

**Comment by pamrichmond** [comment]
@am11, I ran the commands you gave. The results are at: https://gist.github.com/pamrichmond/5c7680d40ded1d1d2e0e

Note that I was installing in ```c:\temp\temp1```, but the install error says ```> node-sass@2.0.0-beta install c:\temp\node_modules\node-sass```, which seems like it might be trying to install into the wrong folder.  Regardless, the install failed.  The install didn't create the ```node_modules``` folder, so I manually created it and the appropriate subfolders, as well as the binary.  The ```node``` command still generated an error.

**Comment by am11** [comment]
@pamrichmond, this is strange that it didn't created the node_modules directory, but great that you created it manually. :)

```cmd
c:\temp\temp1\node_modules\node-sass\vendor>node -p console.log(require('node-sass').info())
```

Can you try:

```cmd
c:\temp\temp1\node_modules\node-sass\vendor>cd ..\..\..\

c:\temp\temp1> node -p console.log(require('node-sass').info())
```

Also:

```powershell
c:\temp\temp1> node

# this is node.js shell
require('node-sass')
```

**Comment by pamrichmond** [comment]
@am11 I tried the additional commands:
```
c:\temp\temp1>node -p console.log(require('node-sass').info())

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:13
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3

c:\temp\temp1>node
> require('node-sass')
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
>
```

**Comment by am11** [comment]
Actually `require()` automagically resolves the relevance from current directory to `<current-directory>\node_modules\<module-name>` and then it looks for global installation of the module (`npm -g ..`).

**Comment by am11** [comment]
@pamrichmond, does this help: http://stackoverflow.com/a/25877185/863980?

**Comment by Errvald** [comment]
@am11 That fixed it for me, thanks!
I had to add ```c:\Windows\System32``` to System variables.

**Comment by pamrichmond** [comment]
@am11, that fixed it for me. I added 'C:\Windows\System32' to my PATH, and `npm install node-sass` now works. Thank you.

**Comment by am11** [comment]
Great! Glad to hear that. :)

@davetgreen this may also fix the issue you are having as well.
