### ISSUE TITLE
fresh git pull -> npm install -> npm test results in error

### ISSUE THREAD

**Issue by olsonpm** [sass/node-sass#645]
Steps to reproduce:
1) git clone --recursive \<git repo\> && cd node-sass
2) npm install
3) npm test

Test output found here:
https://gist.github.com/olsonpm/e61f0233b518bacd9d37

I'm running
 - ubuntu 14.10
 - npm 1.4.28
 - node-sass 2.0.0 beta

I just wrote some functionality allowing render to return a promise (via pRender).  I found this error when writing my tests for that.

If there's any more info I can give please let me know.  I won't have time to look into the issue myself any further - and am fine keeping a personal copy of my pRender version of node-sass.

**Comment by am11** [comment]
You missed two steps after `npm install`:

* `npm install node-gyp`
* `node_modules/.bin/node-gyp rebuild`

**Comment by olsonpm** [comment]
Ah - thanks much

**Comment by olsonpm** [comment]
Just tested now, worked great.  Go ahead and close this
