### ISSUE TITLE
Installs failing due to EEXIST error

### ISSUE THREAD

**Issue by austinpray** [sass/node-sass#648]
I'm having several users reporting errors like this:

```
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/home/forge/.nvm/v0.10.36/bin/node" "/home/forge/.nvm/v0.10.36/bin/npm" "install"
npm ERR! cwd /home/forge/xxxxx.com/web/app/themes/xxxxx
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /home/forge/.npm/e55268eb-pm-source-map-0-1-43-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

In addition:
http://discourse.roots.io/t/npm-issues-with-gulp-branch/2848

I get this error occasionally on travis as well. Perhaps there is some sort of race condition here?

**Comment by austinpray** [comment]
Shoot. Looks like this might be related: https://github.com/npm/npm/issues/6309

**Comment by bevacqua** [comment]
Do `npm update -g npm`.

**Comment by austinpray** [comment]
Yeah race conditions with npm 1.2.28. Too bad we won't get npm 2.0.0 until 0.11. Till then just recommending users `npm install -g npm@latest`
