### ISSUE TITLE
Loads of console.logs when using custom importers

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#671]
Seems to be [this line](https://github.com/sass/node-sass/blob/9416836972e47e4eb9af5943c3348a1667c3b64f/lib/index.js#L205):

```js
        console.log(data); // ugly hack
```

what is it a hack for?

**Comment by am11** [comment]
It is to keep the libuv loop alive: https://github.com/sass/node-sass/pull/615.
Also see the discussion: https://github.com/sass/node-sass/pull/644#discussion_r23903134. This will be removed, once we have custom function implemented.
