### ISSUE TITLE
Change default value of `precision` from 5 to 10

### ISSUE THREAD

**Issue by sindresorhus** [sass/node-sass#673]
The default is currently 5, but Bootstrap requires 8 (and probably many other grid like frameworks), which means most users will have to change this. Make it easy for users and come with a better default.

[`grunt-sass`](https://github.com/sindresorhus/grunt-sass) currently defaults to 10 instead of 5 for this exact reason.

**Comment by am11** [comment]
Actually LibSass has the precision set to 5: [libsass/inspect.cpp#L374](https://github.com/sass/libsass/blob/84d9b0c1517b9bea804204d14c747ebfd0bc952b/inspect.cpp#L374) and we tend to use libsass defaults. Moving ahead, we are trying to avoid setting defaults (for instance; [index.js#L138](https://github.com/sass/node-sass/blob/dfc026bae39bd4e3e5aae9b3d10dbe25d9ae36bd/lib/index.js#L138)) in node-sass and let it fallback to libsass defaults.

**Comment by am11** [comment]
@sindresorhus, please open this issue with LibSass issue tracker and node-sass will inherit their defaults.

**Comment by sindresorhus** [comment]
In https://github.com/sass/libsass/issues/675 they say they don't want diverge from `sass` regarding default precision. See https://github.com/sass/sass/issues/1122 for a bikeshedding `sass` discussion about upping the precision default, that seemingly went nowhere.

I'm going to keep the default precision for grunt-sass at 10 as that's the best for users.

**Comment by am11** [comment]
Well, as much as I personally prefer siding the majority's opinion, node-sass needs to be synced with LibSass. And I really feel the need to change after going through all the comments on ruby-sass.

@xzyfer, is it possible that LibSass take a stand here and provide what majority of users want?

**Comment by xzyfer** [comment]
I don't see this changing in Libsass any time soon. I do however agree that the bikeshed has been unnecessary and that increasing the default precision should be a no brainer. Unfortunately just as node-sass is a thin wrapper over Libsass, Libsass needs to be transparently swappable with Ruby sass.
