### ISSUE TITLE
Return calculated Source Map output path in stats object

### ISSUE THREAD

**Issue by sindresorhus** [sass/node-sass#674]
Currently I have to manually calculate the output path of the source map file based on the `sourceMap` option value. Would be handy if node-sass returned this so every consumer didn't have to duplicate that logic.

https://github.com/sindresorhus/grunt-sass/blob/bb1136d18cdca2be8529ed92a2620b391c2b20c6/tasks/sass.js#L30

**Comment by am11** [comment]
Agree. :+1:

**Comment by am11** [comment]
This was addressed by 2aebbd1c8b6fd2c792d87e4f3405a84d6915d62b via https://github.com/sass/node-sass/pull/686. 

You would be able to access `this.options.sourceMap` in (both method-like or node-like) callbacks.
