### ISSUE TITLE
`libsass` bindings not found (broccoli-sass)

### ISSUE THREAD

**Issue by deepflame** [sass/node-sass#678]
Hi guys,

not sure if this is libsass related but upgrading it in broccoli-sass it gave me the following error:

```
16:47:46 ember.1 | `libsass` bindings not found. Try reinstalling `node-sass`?
16:47:46 ember.1 | Error: `libsass` bindings not found. Try reinstalling `node-sass`?
16:47:46 ember.1 |     at getBinding (/Users/aboehrnsen/.../frontend/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:22:11)
16:47:46 ember.1 |     at Object.<anonymous> (/Users/aboehrnsen/.../frontend/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:188:23)
16:47:46 ember.1 |     at Module._compile (module.js:460:26)
16:47:46 ember.1 |     at Object.Module._extensions..js (module.js:478:10)
16:47:46 ember.1 |     at Module.load (module.js:355:32)
16:47:46 ember.1 |     at Function.Module._load (module.js:310:12)
16:47:46 ember.1 |     at Module.require (module.js:365:17)
16:47:46 ember.1 |     at require (module.js:384:17)
16:47:46 ember.1 |     at Object.<anonymous> (/Users/aboehrnsen.../frontend/node_modules/broccoli-sass/index.js:5:12)
16:47:46 ember.1 |     at Module._compile (module.js:460:26)
```

I am running Node 0.12 and NPM 2.5.0 on OSX Yosemite. Any idea what I should do? Reinstalling as suggested did not help btw.

**Comment by am11** [comment]
Hi, the latest version of node-sass v2.0.1 is supported with node.js v0.12.
Please check you get the same issue with `npm install node-sass@2.0.1`.

**Comment by Ghostavio** [comment]
I'm having the same problem. broccoli-sass is using version 1.2.3 of node-sass. Releasing a new version of node-sass shouldn't break the older ones though :/

**Comment by am11** [comment]
> Releasing a new version of node-sass shouldn't break ...
You mean node.js? Whenever node.js minor version is updated, all npm packages using C++ addons need are required to use newer version. 

This bug belongs to broccoli-sass. The solution is to update node-sass to latest version.

**Comment by xzyfer** [comment]
More specifically, node-sass before 2.0.0 only supports 0.12. Alternative
you could down grade node for an immediate fix.

**Comment by davidweisss** [comment]
In my case downgrading node breaks something else. I'm trying am11 solution but I don't get where I should run: require('node-sass').renderSync({data: '.test { padding: 0; } '})

Thanks.

**Comment by am11** [comment]
@davidweisss, in command line interface (Linux/Mac: Terminal, Windows: cmd/powershell):

```powershell
# type
node  # and hit enter

# you have entered node.js interactive console. yay!
# here you paste all the javascript code you want and
# just hit enter to execute

> require('node-sass').renderSync({data: '.test { padding: 0; } '})

# paste the above line without '>' and hit enter

# if succeeded, it will output:

{ stats:
   { entry: 'data',
     start: 1425132450747,
     includedFiles: [],
     end: 1425132450749,
     duration: 2 },
  css: '.test {\n  padding: 0; }\n',
  map: '{}' }
```

**Comment by davidweisss** [comment]
Thanks, but.

I got the proper response but it still broken.

I cloned the version from a colleague: 
node 0.10.33
node-sass: @1.2.3
See
└─┬ broccoli-sass@0.3.3
  └── node-sass@1.2.3 

I also had this when I installed node-sass with npm:

├─┬ broccoli-sass@0.3.3
│ └── node-sass@1.2.3 
└── node-sass@2.0.1  extraneous

npm ERR! extraneous: node-sass@2.0.1 /Users/davidweiss/github/emberApp/node_modules/node-sass

**Comment by cfator** [comment]
Can someone recommend a catch all to solve this short of reinstalling the host operating system?

**Comment by xzyfer** [comment]
```
npm rebuild node-sass
```

**Comment by cfator** [comment]
Appreciate that.  After running it I get a long list of compile errors.  Is
there some way I can get rid of all things related to node-sass and try
again?

**Comment by xzyfer** [comment]
Please open an issue with the related compile errors.

To remove an npm package
```
npm uninstall <package>
```

**Comment by cfator** [comment]
I've tried to rebuild it, got a long list of compile errors.  Then I removed all node_modules globally and started from scratch and I'm still hitting this.  Tried rebuilding again, same compile errors.  I know the set of node modules my app calls for (Ember-cli) work together but I can not get node-sass working.

Is there a large reset button somewhere?

**Comment by xzyfer** [comment]
You can use `npm ls node-sass` to determine if you've somehow got multiple node-sass' installed.

The **only** fix is
```
npm rebuild node-sass
```

If you're getting compilation errors there is an compatibility with your system. Please open a new issue with the compilation errors your seeing.

**Comment by mudassir0909** [comment]
@xzyfer when I do `npm ls node-sass`

I see

```
├─┬ broccoli-sass-source-maps@1.3.0
│ └── node-sass@3.4.2
├─┬ ember-cli-font-awesome@1.3.0
│ └─┬ ember-cli-sass@5.3.1
│   └─┬ broccoli-sass-source-maps@1.6.0
│     └── node-sass@3.4.2
├─┬ ember-cli-sass@3.3.1
│ └─┬ broccoli-sass-source-maps@0.7.0
│   └── node-sass@2.1.1
├─┬ gulp-sass@2.2.0
│ └── node-sass@3.4.2
└── node-sass@3.3.3
```

Yes, there are multiple versions, now how do I fix this?

**Comment by xzyfer** [comment]
Try updating all your package.json dependencies the latest versions
