### ISSUE TITLE
Changing binary

### ISSUE THREAD

**Issue by nwhite89** [sass/node-sass#689]
I'm currently hitting a problem that I need to force the binary in which is installed and used. 

*My Scenario*
Before deploying we package our entire system up rather than running things like ``npm install`` on the deployed server. The problem that arises is that the server is a linux box however, it's being pushed (packaged up) by a Mac originally.

Is there anything currently that I could work with, in order to set this that you can think of?

Thanks in advanced

**Comment by am11** [comment]
This will be a nice addition if we could provide a switch to `npm install` to let user download multiple binaries from the catalogue: https://github.com/sass/node-sass-binaries/. But unfortunately, we cannot provide custom arguments to npm install. 

The workaround is the good old manual download technique from https://github.com/sass/node-sass-binaries/tree/v2.0.1. Download the zip, extract it in `vendor/` and remove the ones you don't want to keep before pushing it to the deployment server.

HTH.

**Comment by nwhite89** [comment]
I see, do you think it would be possible to run as a separate command passing the arg to ``build`` ? something post install like:
``node scripts/build.js --binary=linux`` ?

**Comment by am11** [comment]
Unfortunately no; on Mac, we cannot build binary for Linux (well not without doing some virtual machine magic involving scp and whatnot).

So the straightforward options are:

* download the pre-build binaries from node-sass-binaries in `vendor/linux-<arch>-<target-runtime>-version/binding.node` directory and deploy.
* build the binary on Linux and push it to deployment server separately.
* build the binary on Linux VM, copy it to vendor directory on mac and then deploy.

**Comment by nwhite89** [comment]
Ah I see of course thank you @am11

**Comment by am11** [comment]
:+1:
