### ISSUE TITLE
Problem with Node wrapper and "sassBinaryName"

### ISSUE THREAD

**Issue by Bumxu** [sass/node-sass#691]
When **node-sass** is installed with ```npm install node-sass``` or as dependency by another npm installation, binary binding is enclosed in a "OS-ARCH-**node**-VERSION" folder.

![image](https://cloud.githubusercontent.com/assets/1742635/6310051/5164a3b8-b953-11e4-90a5-3056db668e3d.png)

Now, if app is launched with a node wrapper which ```process.execPath``` is not the node path, for example **LiveScript** (*execPath = C:\Users\UserName\AppData\Roaming\npm\node_modules\LiveScript\bin\lsc*) ```import``` fails with *Error: `libsass` bindings not found* because it search for "OS-ARCH-**lsc**-VERSION" folder.

Should the binding name be dependent on the *execPath* mandatory?

Thanks :)

**Comment by am11** [comment]
Thanks for brining this to attention. I considered many angles to avoid version sniffing but missed this one.

The real solution will come with the approach which will be finalised by: https://github.com/TooTallNate/node-gyp/pull/564 (and used by https://github.com/TooTallNate/node-gyp/pull/564).

So the standard "hacky" (version sniffing) approach is to add the following at [node-sass (v2.0.1)/lib/extensions.js#L11](https://github.com/sass/node-sass/blob/v2.0.1/lib/extensions.js#L11):

```javascript
return runtimeVersion.major < 1 ? 'node' : 'iojs';
```

**Comment by am11** [comment]
This issue is addressed by https://github.com/sass/node-sass/pull/695.
