### ISSUE TITLE
Remove console.log from importer function

### ISSUE THREAD

**Issue by ubenzer** [sass/node-sass#698]
In [lib/index.js line 205](https://github.com/sass/node-sass/blob/master/lib/index.js#L205) there is a line like this:

`console.log(data); // ugly hack`

This generates huge uncontrolled output in console making it impossible to use importer function in a production-ready application and should be removed if possible.

**Comment by am11** [comment]
See this for reasoning at: https://github.com/sass/node-sass/pull/615.
It was a silly console log output vs. the broken import functionality: so we chose the former one.

**Comment by davidgtonge** [comment]
This issue should be re-opened - it makes this project unusable

**Comment by jareware** [comment]
:+1: for reopen, importers are a really neat feature, but the `console.log`s are quite troublesome.

**Comment by Snugug** [comment]
:no_entry_sign: This was resolved in a massive refactor and is no longer an issue

**Comment by jareware** [comment]
Ah, excellent, sorry of unearthing it, looking forward to a stable release!
