### ISSUE TITLE
Can not download file ".../v2.0.1/linux-x64-iojs-1.3/binding.node"

### ISSUE THREAD

**Issue by jrasanen** [sass/node-sass#699]
Hi,

Node-sass fails to install on iojs 1.3.0.

	npm install node-sass
	> node-sass@2.0.1 install /tmp/node_modules/node-sass
	> node scripts/install.js
	 
	Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.3/binding.node
	 

Debug data gist: https://gist.github.com/jrasanen/28ff1461ae9f17317538

**Comment by xzyfer** [comment]
Io.js 1.3 is not currently supported. Downgrade or the use nvm to manage multiple versions for now.

See https://github.com/sass/node-sass/issues/694 for more information.

**Comment by jgacuca567** [comment]
@xzyfer Still getting the Cannot download file, from 

What is the solution for that?

**Comment by saper** [comment]
@jguacuaca567: which node version are you using? Are you using the newest version of node-sass (3.4.1 at the moment)?

**Comment by jgacuca567** [comment]
@saper Version of Node SASS - It Says Node-SASS@2.01

<img width="164" alt="screen shot 2015-10-31 at 6 03 01 pm" src="https://cloud.githubusercontent.com/assets/4000076/10866156/aa0642ac-7ff9-11e5-95e2-fafefb41fdfc.png">

**Comment by xzyfer** [comment]
This version us very old and only supports node 0.10 and 0.12.

**Comment by jgacuca567** [comment]
@xzyfer  Actually I just downloaded it today from (https://www.npmjs.com/package/node-sass)

**Comment by xzyfer** [comment]
The current version is 3.4.1

**Comment by jgacuca567** [comment]
@xzyfer  How do I change it to show that version

**Comment by xzyfer** [comment]
```
npm install node-sass
```

**Comment by jgacuca567** [comment]
Hi @xzyfer I tried installing and this is what I got see screenshots below. 

<img width="1159" alt="screen shot 2015-11-01 at 9 09 00 am" src="https://cloud.githubusercontent.com/assets/4000076/10869283/5d57d31a-8078-11e5-9964-babde7e3f077.png">
<img width="1183" alt="screen shot 2015-11-01 at 9 09 22 am" src="https://cloud.githubusercontent.com/assets/4000076/10869281/5d553cae-8078-11e5-9b7a-5e5630394699.png">
<img width="593" alt="screen shot 2015-11-01 at 9 09 32 am" src="https://cloud.githubusercontent.com/assets/4000076/10869282/5d56669c-8078-11e5-9938-baeb1eb15939.png">

**Comment by xzyfer** [comment]
Try upgrading to grunt-sass@^1

**Comment by jgacuca567** [comment]
I did, see screenshot below, let me know if I did the correct way @xzyfer 

Also when the node_modules are yellow, is that a good thing or? 

<img width="1040" alt="screen shot 2015-11-01 at 10 13 13 am" src="https://cloud.githubusercontent.com/assets/4000076/10869572/5b56db5c-8081-11e5-93bd-b9f5308b7c1d.png">

**Comment by xzyfer** [comment]
That final screen looks like the installation succeeded. Problem solved.

**Comment by jgacuca567** [comment]
Thanks @xzyfer. But would you know what the yellow means, or is that just color variables?

**Comment by xzyfer** [comment]
I don't know. That's an npm issue.
