### ISSUE TITLE
Watch for changes in imported files as well

### ISSUE THREAD

**Issue by twistedR** [sass/node-sass#700]
Currently if I watch a file that has `@import` statements it will not watch for changes in the imported files. It would be great to have that feature even if it's an additional command line flag.

**Comment by xzyfer** [comment]
This should be fixed in 2.0.1

**Comment by am11** [comment]
> This should be fixed in 2.0.1

That is what I was thinking and confused about.  :)
@twistedR, see https://github.com/sass/node-sass/pull/629 and the related issue. Are you using node-sass v2.01?

**Comment by twistedR** [comment]
Yes I am on 2.0.1. I was using the incorrect command. My bad. 
Using `node-sass -w -r --output dist src` the proper import path is traversed. I was compiling a single file earlier. So my command `node-sass -w sass/app.scss public/css/app.css` was only looking for changes on that single file which has all my imports.

My bad, I should have looked through the existing issues better. 

My use case is easily solved by using the recursive flag, I leave it up to you if you consider going through the import tree when compiling a single file is supposed to happen or not.

**Comment by am11** [comment]
@twistedR, lets continue the recursive-related discussion at this open issue: https://github.com/sass/node-sass/issues/601.
