### ISSUE TITLE
API: Retire image_path option

### ISSUE THREAD

**Issue by am11** [sass/node-sass#702]
Based on sass/libsass#834 and sass/libsass#489.

Related: https://github.com/sass/node-sass/pull/224.

**Comment by xzyfer** [comment]
:tada: :rocket:

**Comment by xzyfer** [comment]
Off topic, but if we're introducing breaking changes can we changed the milestone to 3.0. Packages that don't follow semver are the bane of npm.

**Comment by am11** [comment]
I agree. With all the new features in LibSass and the custom functions feature coming to node-sass the vNext is going to be a HUGE one! :mega:

**Comment by am11** [comment]
Revoked by 5cf107b via #704.

**Comment by justin808** [comment]
What is the replacement for imagePath? Are there any upgrade guidelines?

**Comment by xzyfer** [comment]
No. It was removes because it's not in Ruby Sass. You can use a custom
function or sass-eyeglass which has this.
