### ISSUE TITLE
Can't install. Windows 8.1

### ISSUE THREAD

**Issue by ttocskcaj** [sass/node-sass#709]
Error is below:
![Error](http://i.imgur.com/iyyN7tD.png)

Versions:
![Versions](http://i.imgur.com/m0AbSVs.png)

Here's npm-debug.log
https://gist.githubusercontent.com/ttocskcaj/b42952835ba31ade22ca/raw/node-sass%20log

**Comment by am11** [comment]
Hello, thanks for reporting this issue.

Can you please try this:

```cmd
:: this is cmd
npm install node-sass
:: it fails with the aforementioned error
node
:: you have entered node interactive console (REPL)
var spawnSync = require('child_process').spawnSync;
spawnSync('C:\\Program Files\\Internet Explorer\\iexplore.exe');
:: does it open IE?
```

**Comment by ttocskcaj** [comment]
`var spawnSync = require('child_process').spawnSync`
returns undefined

`spawnSync('C:\\Program Files\\Internet Explorer\\iexplore.exe')`
Does open IE

**Comment by am11** [comment]
I asked that because it seemed like a path issue with spawn (where path has a space).

To further investigate, please download the zip file from https://github.com/sass/node-sass/releases/tag/v2.0.1, extract and then in `scripts\install.js`, throw in some console.log statements, save and then:

```cmd
:: this is cmd
cd into\extracted\node-sass\v2.0.1\src\directory
node scripts/install
```

It will not install like that anyway, but we just need to figure out which line is causing this issue:

> /c/program files no such file or directory

**Comment by am11** [comment]
Also, please show the output of:

```
cd \temp1
node -p process.execPath
``

**Comment by ttocskcaj** [comment]
Running `node scripts/install` is coming up with this error:
https://gist.github.com/ttocskcaj/576f17c97b9a220e3941

And `node -p process.execPath` returns this:
`C:\Program Files (x86)\nodejs\node.exe`

(I've tried the 64bit and 32bit versions)

**Comment by am11** [comment]
Sorry, please try with:

```cmd
:: this is cmd
cd into\extracted\node-sass-v2.0.1
npm install
```

Also, add some `console.log('test 1')` (test 2, test 3 ...) in `scripts\install.js`, so it appear in output and try to detect at which line it throws.

**Comment by ttocskcaj** [comment]
OK none of the console.logs are showing on the screen.
Including one on the first line of scripts/install.js

Maybe it's not reaching this file?

**Comment by am11** [comment]
Once `npm install` succeeds, please try explicitly running `node scripts/install` (again).

**Comment by ttocskcaj** [comment]
I've got it to install, though I think the problem was with my "ComSpec" environmental variable rather than node-sass. Cheers for the help.
