### ISSUE TITLE
Grunt error: >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by jdsteinbach** [sass/node-sass#719]
I've run npm install, made sure node-sass is in `package.json ... devDependencies` & is installed globally. Can't get past the error `>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?`

Reinstalling hasn't helped (else I wouldn't be here!) and I'm puzzled at this. 

I'm on OS X (10.10.2), npm 2.3.0, node-sass 2.0.1, grunt 0.4.5.

**Comment by am11** [comment]
Which version of node.js or io.js you are testing with?

**Comment by jdsteinbach** [comment]
0.12.0

I blew away everything in node_modules & re-ran `npm install` - that fixed it.

**Comment by am11** [comment]
Awesome! Congrats. :smiley: :+1:
