### ISSUE TITLE
Download sass binary from environment variable url

### ISSUE THREAD

**Issue by johnrc** [sass/node-sass#720]
What do you think about doing something similar to what [phantomjs](https://github.com/Medium/phantomjs/blob/master/install.js#L23) does with `PHANTOMJS_CDNURL` and fetch the sass binary from a url set as an environment variable? This would provide options for downloading the binaries instead of only building from source or downloading from GitHub.

**Comment by am11** [comment]
Hi, thanks for the suggestion!

Any ideas what kind of (free cloud / free CDN ?) hosting they are using for binaries?

**Comment by johnrc** [comment]
According to their [docs](https://www.npmjs.com/package/phantomjs#custom-binaries-url), they use https://bitbucket.org/ariya/phantomjs/downloads and give the example of using http://cnpmjs.org/ or any other internal or external url.

**Comment by am11** [comment]
@johnobe, thanks for your feedback. We have introduced the feature and much more in binary names/paths/urls customizations; see https://github.com/sass/node-sass/issues/712 and the [related PR](https://github.com/sass/node-sass/pull/743).

Also v3.0.0-pre is out. Let us know what you think. :sunglasses:
