### ISSUE TITLE
install error if inside /root

### ISSUE THREAD

**Issue by minutuslausus** [sass/node-sass#736]
Hi 

I had a strange error. If I wanted to install in /root/teset folder then I got the following error:
https://gist.github.com/minutuslausus/97043119dade7dffe058

I could solve it, but it was annoying to debug

**Comment by am11** [comment]
Hi, do you get the same error if you install in other location, say `/tmp`?

**Comment by minutuslausus** [comment]
No. It works both in my home dir both in /tmp

**Comment by am11** [comment]
Perhaps it is the directory permission that npm is unable to create a `scripts` directory in /admin on install? 
Does it create node-sass directory at all after it fails the installation?

**Comment by minutuslausus** [comment]
hm, strange
https://gist.github.com/minutuslausus/6f0d8bd2daa99f9335a3
it creates node_modules with my base user as owner (puffy) and then bin owned by root

I thought the process should inherit the rights of the user

**Comment by am11** [comment]
Unfortunately, that part of installation process we don't control. This is not undoable, but this is a very rare use-case which I think should be addressed by npm folks: https://github.com/npm/npm.

Alternatively, I would suggest you to install [nvm](https://github.com/creationix/nvm) or update node to use latest version of node.js v0.12.0, which packs with npm v2.5.1 and retry. Perhaps they have already fixed it.

**Comment by minutuslausus** [comment]
this can be true, but seems unlikely to me
I have this package.json: https://gist.github.com/minutuslausus/f11ff2867793147870bd 
and all of them works without any problem 

on the other hand I am far from an expert, so you could be right :)

right now, my problem is solved (I moved the folder)

**Comment by am11** [comment]
Great! We I try to reproduce this issue once we are done with other build related stuff. :)

**Comment by am11** [comment]
The pre-release `v3.0.0-pre` is out. See the breaking changes in README.

```
npm install node-sass@3.0.0-pre
```

To see the runtime coverage matrix, see node-sass-binaries readme: https://github.com/sass/node-sass-binaries/#node-sass-binaries.
