### ISSUE TITLE
Error installing `3.0.0-preview` on iojs 

### ISSUE THREAD

**Issue by micahlmartin** [sass/node-sass#748]
I'm trying to upgrade to iojs 1.5.1 from 1.2.0 and I'm having trouble intalling. I tried using the `2.0.1` package but that has issues with the binary download path which is solved in #695. So was hoping to use the latest preview as a way to fix the issue but now I'm getting this:

```
> node-sass@3.0.0-preview install /Users/micah/trackr/app/node_modules/node-sass
> node scripts/install.js


> node-sass@3.0.0-preview postinstall /Users/micah/trackr/app/node_modules/node-sass
> node scripts/build.js

Building: /Users/micah/.nvm/versions/io.js/v1.5.1/bin/iojs node_modules/pangyp/bin/node-gyp rebuild
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:4:10: fatal error: 'libsass/sass_context.h' file not found
#include "libsass/sass_context.h"
```

**Comment by am11** [comment]
Umm I haven't even published it to npm yet. :)

I will upload the Linux and Windows binaries and then publish later today.

Meanwhile you can clone the repo and build.

```bash
cd somewhere-wild
git clone https://github.com/sass/node-sass --recursive
cd node-sass
git submodule update --recursive --init 
npm install
node scritps/build -f
```

You need to have Python 2.7.x and GCC 4.7+ installed.

Or you can wait till we arrange all the binaries and publish.

**Comment by am11** [comment]
Mac and Windows binaries are published: https://github.com/sass/node-sass/releases/tag/v3.0.0-pre.
Linux binaries will arrive later today.

Note that we have unpublished `-preview` release in favour of `-pre` (and there was a bug in install script).

**Comment by am11** [comment]
Linux binaries are uploaded.

**Comment by micahlmartin** [comment]
@am11 Thanks for doing this so quickly. I installed 3.0.0-pre and it's working great! :+1:

**Comment by am11** [comment]
@micahlmartin, i have just added the release notes. https://github.com/sass/node-sass/releases/tag/v3.0.0-pre. :notes:
