### ISSUE TITLE
[ @extend ] Comma separated selectors > failed

### ISSUE THREAD

**Issue by aritmico** [sass/node-sass#750]
I'm not able to compile something like:

.selector1{ ... }
.selector2{ ... }

.selector3{ @extend .selector1, .selector2; }

According to sass-lang ref-doc:

Multiple extends can also be written using a comma-separated list of selectors. For example, @extend .error, .attention is the same as @extend .error; @extend .attention.

**Comment by am11** [comment]
The syntax related issues need to be reported in libsass issue tracker: https://github.com/sass/libsass/issues.

When you are reporting an issue at libsass, please search for the issues already reported. I think there are some improvements made around `@extend` recently.
