### ISSUE TITLE
build.js fails when installed through npm

### ISSUE THREAD

**Issue by joliss** [sass/node-sass#752]
Node-sass v2.0.1 fails to download the binary on my platform; this seems to fixed with v3.0.0-pre, and it's not what this issue is about.

However, I encountered the following curiosity, which I think might be a bug:

When I run `npm install` on the node-sass v2.0.1 source repo, it falls back to compiling from source and succeeds:

```
(tags/v2.0.1) src/node-sass ♥ rm -rf vendor node_modules; npm install
|
> node-sass@2.0.1 install /home/ubuntu/src/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.5/binding.node

> node-sass@2.0.1 postinstall /home/ubuntu/src/node-sass
> node scripts/build.js

make: Entering directory `/home/ubuntu/src/node-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  CXX(target) Release/obj.target/binding/src/sass_context_wrapper.o
  CXX(target) Release/obj.target/binding/src/libsass/ast.o
...
[compiles successfully, and npm finishes installing dependencies]
```

This is great!

However, it doesn't seem to work when node-sass is installed as a dependency by npm. For instance, running `npm install` for broccoli-sass, which depends on node-sass v2.0.1:

```
(tags/v0.5.0) src/broccoli-sass ♥ rm -rf node_modules; npm install
-
> node-sass@2.0.1 install /home/ubuntu/src/broccoli-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-iojs-1.5/binding.node

> node-sass@2.0.1 postinstall /home/ubuntu/src/broccoli-sass/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/home/ubuntu/src/broccoli-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:865:3
Build failed
mkdirp@0.3.5 node_modules/mkdirp

broccoli-caching-writer@0.5.5 node_modules/broccoli-caching-writer
├── core-object@0.0.3
├── promise-map-series@0.2.1
├── symlink-or-copy@1.0.1 (copy-dereference@1.0.0)
...
[npm continues installing stuff, but leaves the package unusable]
```

There are two issues here:

1. The "compile from source" fallback doesn't seem to be working when node-sass is installed through npm.
2. The compilation failure isn't caught - maybe a non-zero exit code is swallowed somewhere. Instead, npm merrily continues installing stuff, leaving the package in an unusable state. `require('node-sass')` fails with "Error: `libsass` bindings not found. Try reinstalling `node-sass`?"

I'm not sure if these are intentional and/or fixable, but I figured I'd report it just in case!

I'm using iojs 1.5.1 on Ubuntu.

**Comment by am11** [comment]
v2.0.1 had this bug, I mistaken added pangyp (a variant of node-gyp which supports io.js) under `devDependencies`.
You can try out the latest v3.0.0-pre. In addition to this bug fix, we have added prebuild binaries for io.js v1.0 to v1.5, node 0.10 and node 0.12. :)

**Comment by joliss** [comment]
Oh cool. Sounds like we can close this then?

**Comment by am11** [comment]
:+1:
