### ISSUE TITLE
FreeBSD port and binaries

### ISSUE THREAD

**Issue by saper** [sass/node-sass#756]
I've been working recently on providing official FreeBSD port of node-sass, focusing on automated building of binaries that shall be included in the http://github.com/sass/node-sass-binaries repository

This bug is about status of this work in progress, hopefully to finish on 3.0.0

- [x] Prepare automated build environment for the following versions:

Environment name | System release | Architecture | GCC/Clang | Node fork | Proposed binary name
---- | ----| ----  | ---- | ---- | ----
iojs_10_1_amd64  |  10.1-RELEASE-p6  |  amd64 | clang | iojs 1.4.3 | `freebsd10-x64-m43`
nodejs010_10_1_amd64  |  10.1-RELEASE-p6  |  amd64 | clang | node 0.10.36 | `frebsd10-x64-m11`
nodejs_10_1_amd64  |  10.1-RELEASE-p6  |  amd64 | clang | node 0.12.0 | `freebsd10-x64-m13`
iojs_10_1_i386  |  10.1-RELEASE-p6  |  i386 | clang | iojs 1.4.3 | `freebsd10-ia32-m43`
nodejs010_10_1_i386  |  10.1-RELEASE-p6  | i386 | clang | node 0.10.36 | `freebsd10-ia32-m11`
nodejs_10_1_i386  |  10.1-RELEASE-p6  |  i386 | clang |  node 0.12.0 | `freebsd10-ia32-m14`
iojs_8_4_amd64  |  8.4-RELEASE-p24  |  amd64 | gcc | iojs 1.4.3 | `freebsd8-x64-m43`
nodejs010_8_4_amd64  |  8.4-RELEASE-p24  |  amd64 | gcc | node 0.10.36 | `freebsd8-x64-m11`
nodejs_8_4_amd64  |  8.4-RELEASE-p24  |  amd64 | gcc | node 0.12.0 | `freebsd8-x64-m14`
iojs_8_4_i386  |  8.4-RELEASE-p24  |  i386 | gcc | iojs 1.4.3 | `freebsd8-ia32-m43`
nodejs010_8_4_i386  |  8.4-RELEASE-p24  |  i386 | gcc | node 0.10.36 | `freebsd8-ia32-m11`
nodejs_8_4_i386  |  8.4-RELEASE-p24  |  i386 | gcc |  node 0.12.0 | `freebsd8-ia32-m14`
iojs_9_3_amd64  |  9.3-RELEASE-p10  |  amd64 | gcc | iojs 1.4.3 | (can use `freebsd8` binary)
nodejs010_9_3_amd64  |  9.3-RELEASE-p10  |  amd64 | gcc | node 0.10.36 | (can use `freebsd8` binary)
nodejs_9_3_amd64  |  9.3-RELEASE-p10  |  amd64| gcc | node 0.12.0 | (can use `freebsd8` binary)
iojs_9_3_i386  |  9.3-RELEASE-p10  |  i386 | gcc | iojs 1.4.3 | (can use `freebsd8` binary)
nodejs010_9_3_i386  |  9.3-RELEASE-p10  |  i386 | gcc |node 0.10.36 | (can use `freebsd8` binary)
nodejs_9_3_i386  |  9.3-RELEASE-p10  |  i386 | gcc | node 0.12. 0  | (can use `freebsd8` binary)

- [x] Improved dependency selection for `npm` to have `node-0.10` available next to `node-0.12` and `iojs - [Bug 198220 (comment 3)](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198220#c3)
- [x] Fixed problem of `iojs` not building on GCC-based FreeBSD `8.4-RELEASE` - [Bug 198349](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198349)
- [x] Fix or workaround kernel 32 bit compatibility problem preventing automatic build of `npm` on i386   - [Bug 178881 - getifaddrs(3) does not report IPv6 addresses properly in 32-bit compatibility mode](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=178881) - WORKAROUND in the build cluster
- [x] Upgrade existing FreeBSD `libsass` port to 3.1.0 - [Bug 198498](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198489) - SUBMITTED
- [x] Fully automatic build of `libsass` 3.1.0
- [ ] Teach [lib/extensions.js](https://github.com/sass/node-sass/blob/master/lib/extensions.js) to generate FreeBSD binary name, fixing also #517 for FreeBSD (by using `freebsd8` and `freebsd10`) EASY
- [x] Extend `binding.gyp` to use existing, already compiled `libsass.a` or maybe a shared `libsass.so` if needed, discussed in #744, #389 ("Expose config param to allow specific libsass commit for build") - pull request #763

**Comment by am11** [comment]
@saper thanks for the proposal. But I am afraid we are not going to release compiler falvoured binaries just for FreeBSD, simply because it is not possible to manage.

Please stick with the current format as already discussed in our previous conversations. Even if this means only support v10+ for FreeBSD.

**Comment by saper** [comment]
It is possible to manage, let me send a simple pull request :)

**Comment by am11** [comment]
@saper, no its not. We are not going to change the format.

**Comment by saper** [comment]
One more question: how can we arrange the binary release process, so that I can prepare binaries for the release *before* it goes out? Should I just prepare a pull request to http://github.com/sass/node-sass-binaries for v3.0.0-pre ?

**Comment by am11** [comment]
Can you test the binary submitted here: https://github.com/sass/node-sass-binaries/pull/49? This is for node v0.12.0 x64.

Yes you need to send a PR to node-sass-binaries like that. You only would have to rename the binding.node to `<version-slug>_binding.node` ([link](https://github.com/sass/node-sass-binaries/pull/49#issuecomment-78502524)) and commit only that binding file.

**Comment by pgib** [comment]
@saper Thank you in advance for this work!

![thanks](https://dl.dropboxusercontent.com/u/31250/gifs/thanks.gif)
