### ISSUE TITLE
Move pangyp to dependencies in 2.0.x version

### ISSUE THREAD

**Issue by rubennorte** [sass/node-sass#757]
I'm getting an error in Jenkins (CentOS x86_64, Node 0.10.31 and npm 2.6.1) trying to build the package because pangyp is a devDependency instead of a dependency:

```
[exec] > npm install
[exec] > node-sass@2.0.1 install /var/lib/jenkins/jobs/PROJECT_NAME/workspace/node_modules/grunt-sass/node_modules/node-sass
[exec] > node scripts/install.js
[exec] 
[exec] Skipping downloading binaries on CI builds
[exec] 
[exec] > node-sass@2.0.1 postinstall /var/lib/jenkins/jobs/PROJECT_NAME/workspace/node_modules/grunt-sass/node_modules/node-sass
[exec] > node scripts/build.js
[exec] 
[exec] 
[exec] module.js:340
[exec]     throw err;
[exec]           ^
[exec] Error: Cannot find module '/var/lib/jenkins/jobs/PROJECT_NAME/workspace/node_modules/grunt-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
[exec]     at Function.Module._resolveFilename (module.js:338:15)
[exec]     at Function.Module._load (module.js:280:25)
[exec]     at Function.Module.runMain (module.js:497:10)
[exec]     at startup (node.js:119:16)
[exec]     at node.js:906:3
[exec] Build failed
```

I'd be great if you could fix this in a 2.0.x version so it can be automatically fixed in grunt-sass, instead of having to wait for a version update.

**Comment by am11** [comment]
Sorry, but we are not back-porting changes for to v2 tag (we don't even use separate branches).
However, you can fork the repo and point your dependency to the *commit-ish* (v2 tag) to your fork like this: http://stackoverflow.com/a/14188105/863980.

**Comment by rubennorte** [comment]
OK, no problem. I'll publish it to my private npm proxy then. Thanks.

**Comment by am11** [comment]
:+1:
