### ISSUE TITLE
Command line compile throwing ": No such file or directory" - v3.0.0-pre

### ISSUE THREAD

**Issue by lennym** [sass/node-sass#758]
Using the command line tool as part of an npm script fails with an error of `: No such file or directory` for even the simplest scss files.

Using Ubuntu 14.04, node v.0.10.29

The same command with v2.0.1 works fine.

Test case: https://github.com/lennym/node-sass-testcase

**Comment by callumacrae** [comment]
I'm getting a similar error, but I'm getting `env: node\r: No such file or directory`

**Comment by am11** [comment]
Is your `test.scss` in the current directory?

I tested as follow:

```cmd
C:\temp>notepad test.scss

C:\temp>type test.scss
div {
    color: red;
}

C:\temp>node_modules\.bin\node-sass -v
node-sass       3.0.0-pre       (Wrapper)       [JavaScript]
libsass         3.1.0           (Sass Compiler) [C/C++]

C:\temp>node -v
v0.10.36

C:\temp>node_modules\.bin\node-sass test.scss test.css
Rendering Complete, saving .css file...
Wrote CSS to C:\temp\test.css

C:\temp>type test.css
div {
  color: red; }

C:\temp>
```

**Comment by callumacrae** [comment]
Ah, I thought you might be using Windows.

Have you got access to a non-Windows system to test this one? I'm using OS X, and @lennym is using Ubuntu 14.04. I suspect it's something to do with the \r in my error.

**Comment by lennym** [comment]
@am11 Yes, the code in lennym/node-sass-testcase is exactly what I'm running.

I've pushed it to travis to test on a couple of other environments too, and it's failing in the same way: https://travis-ci.org/lennym/node-sass-testcase/builds/54256968

**Comment by am11** [comment]
Ok on Ubuntu 12.4. :)

```bash
vagrant@precise64:/tmp$ uname -a
Linux precise64 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:39:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

vagrant@precise64:/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:        12.04
Codename:       precise

vagrant@precise64:/tmp$ nvm install v0.10.29
######################################################################## 100.0%
Now using node v0.10.29

vagrant@precise64:/tmp$ nano test.scss

vagrant@precise64:/tmp$ cat test.scss
div {
    color: red;
}

vagrant@precise64:/tmp$ npm install node-sass

> node-sass@3.0.0-pre install /tmp/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /tmp/node_modules/node-sass/vendor/linux-x64-11/binding.node

> node-sass@3.0.0-pre postinstall /tmp/node_modules/node-sass
> node scripts/build.js

` /tmp/node_modules/node-sass/vendor/linux-x64-11/binding.node ` exists.
 testing binary.
Binary is fine; exiting.

# eradicated for brevity

vagrant@precise64:/tmp$ node node_modules/.bin/node-sass -v
node-sass       3.0.0-pre       (Wrapper)       [JavaScript]
libsass         3.1.0   (Sass Compiler) [C/C++]

vagrant@precise64:/tmp$ node node_modules/node-sass/bin/node-sass test.scss test.css
Rendering Complete, saving .css file...
Wrote CSS to /tmp/test.css

# yay!

vagrant@precise64:/tmp$ cat test.css
div {
  color: red; }

# yay!
```

(note on Windows, `node_modules/.bin/node-sass`  ===  `node node_modules/node-sass/bin/node-sass`, on Linux, it needs to be prefixed with node-sass, as its just a symlink to js file `node-sass`)

**Comment by callumacrae** [comment]
What happens if you clone https://github.com/lennym/node-sass-testcase and run `npm i && npm test`?

**Comment by lennym** [comment]
Interesting `node node_modules/.bin/node-sass test.scss` works ok, but `node_modules/.bin/node-sass test.scss` fails.

Will have a look at the code and see what the issue is.

**Comment by am11** [comment]
It fails because node-sass is not globally installed. If you change this line: https://github.com/lennym/node-sass-testcase/blob/master/package.json#L7 to `"test": "node node_modules/.bin/node-sass test.scss test.css"`, it works.

**Comment by callumacrae** [comment]
Are you now requiring that node-sass is globally installed?

This is going to break everyone's npm scripts.

**Comment by lennym** [comment]
It *shouldn't* be necessary to globally install to run as part of an npm script - it certainly isn't the case for mocha, browserify etc.

**Comment by am11** [comment]
> Are you now requiring that node-sass is globally installed?

No, I am not requiring it. This is how it works.

> It shouldn't be necessary to globally install to run as part of an npm script

True and to make it work without globally installed, see https://github.com/sass/node-sass/issues/758#issuecomment-79048409.

**Comment by lennym** [comment]
I understand that that is a solution, it's just a nasty one, which isn't necessary for other modules, which can just have their binaries called directly as part of npm scripts.

I'm trying to look into why, if I find the reason I'll PR.

**Comment by callumacrae** [comment]
> True and to make it work without globally installed, see #758 (comment).

That's a bug. npm adds `node_modules/.bin` to the PATH variable, and that's a feature. For some reason, it doesn't work with node-sass. It works with everything else.

node-sass@3 can't be intuitively used with npm run as a build tool, and the old version did.

http://substack.net/task_automation_with_npm_run
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

edit: lenny won. ah well.

**Comment by am11** [comment]
> That's a bug. npm adds  node_modules/.bin 

We definitely don't control why your path is not being set by npm installation!

Try:

```
export PATH=$PATH:node_modules/.bin
```

> I understand that that is a solution, it's just a nasty one, which isn't necessary for other modules, which can just have their binaries called directly as part of npm scripts - e.g. mocha, browserify, node-sass@2.0.1.

And if you start over and give it a clean shot in for instance `/tmp` directory,  you will notice that node-sass behaves same as other packages. Make sure you don't have mocha globally installed.

**Comment by lennym** [comment]
Have done some digging, and I'm seeing more oddness...

If I open the binary file in sublime, copy the contents, then delete and save the empty file, then paste the contents back then running it works fine.

However, the file size is now reported as 6,084 bytes, compared with 6,346 for the original file.

If I look at the binary file in the clone'd repo, then this runs fine, and reports a file size of 6,084 bytes as per my modified version.

Conclusion - there is "something" in the binary file which is breaking things, and I don't know what it is.

**Comment by callumacrae** [comment]
Are the line endings fucked up? That would explain the \r in my error, and the windows / unix difference.

**Comment by lennym** [comment]
262 bytes difference, 262 lines in the file... I think you might be onto it.

**Comment by callumacrae** [comment]
Called it! https://twitter.com/callumacrae/status/576395063338618880

**Comment by lennym** [comment]
Which leaves the next question as "What is happening between https://github.com/sass/node-sass/blob/master/bin/node-sass and my node_modules to mess them up?"

**Comment by callumacrae** [comment]
Possibly the change to that file in 2220ba96b9a20920ccfaaadc12978f40e069caf9? It seems suspiciously close to the hashbang, which is where the error is being thrown from on my machine.

I thought github warns you when the line endings are wrong, though?

**Comment by am11** [comment]
@lennym, is the original issue "No such file or directory" fixed? You should open a separate issue for line endings.

**Comment by callumacrae** [comment]
the line endings are causing the issue

**Comment by lennym** [comment]
@am11 The original issue *is* the line endings as far as I can tell - with *good* line endings then all works happily.

**Comment by callumacrae** [comment]
https://github.com/sass/node-sass/blob/master/bin/node-sass#L1

> #!/usr/bin/env node\r

`env: node\r: No such file or directory`

**Comment by lennym** [comment]
@callumacrae - I found that the file in the git repo seems to have correct line-endings though, and the file size reported by github seems to confirm this. The issue seems to be appearing somewhere between the code here, and npm.

Possibly by virtue of being npm publish-ed from a Windows machine?

**Comment by callumacrae** [comment]
I feel that would have been noticed and fixed a very long time ago: wouldn't that affect every single binary on npm pushed from windows?

Also, why is 2.0.1 working?

**Comment by lennym** [comment]
¯\_(ツ)_/¯

**Comment by am11** [comment]
Ok. I admit. I screwed up!
I published it with Windows ([again](https://github.com/sass/node-sass/issues/496)!) and npm (unlike git) does not change the line-endings.

2.0.1 was working because I published with Linux. I will republish it with Ubuntu.

Thanks.

**Comment by callumacrae** [comment]
No worries—that definitely sounds like a bug in npm, and not something you should have to remember to do! Are they aware of this?

**Comment by am11** [comment]
I think they are since 2012! https://github.com/npm/npm/issues/2097. :-1:

**Comment by keithamus** [comment]
I'm not sure `npm publish` is unlikely to effect this. It's more likely that an editor you're using is automatically converting all line endings. We could add a test to ensure this doesn't happen in future.

**Comment by keithamus** [comment]
Well, I'll eat my words. That is messed up.

**Comment by lennym** [comment]
Prepublish hook to throw if OS is Windows?

:trollface:

**Comment by lennym** [comment]
Thanks for your help @am11

**Comment by keithamus** [comment]
BTW this might be a good reason to get Travis to do deploys from now on. We already do it with [node-sass-middleware](https://github.com/sass/node-sass-middleware/blob/master/.travis.yml). Doing it would mean builds always built on Linux, in a "reproducable" environment.

**Comment by callumacrae** [comment]
+1, also makes it really difficult to accidentally push failing builds

**Comment by am11** [comment]
@keithamus, my editor is set to LF. But git first converts all files on Windows to CRLF (the expected line-ending on Windows) and then apply in-memory LF on push. Twice..

So either I compromise git auto linefeed cure settings or publish npm package from Linux (Travis or VM). I think the latter one is the better option. :sunglasses:

**Comment by mgreter** [comment]
@am11 you may be able to fix this by adding correct [`.gitattributes`] [1] to the repo.

[1]: https://github.com/sass/perl-libsass/blob/develop/.gitattributes

**Comment by am11** [comment]
Thanks for the suggestion @mgreter. I have added .gitattributes to the repo.

**Comment by kudos** [comment]
Can you guys cut a release with this fix? I can't use either 3.0.0-pre or 2.0.1 in automated build tools right now with io.js without patching for either this bug or the lack of a binary in 2.0.1 (and the lack of pangyp in dependencies in 2.0.1, which would have let npm compile a binary instead).

**Comment by am11** [comment]
From semver POV, what should be the tag for vNext? `3.0.0-pre.2`, is it @xzyfer?

**Comment by am11** [comment]
@xzyfer, going by https://docs.npmjs.com/misc/semver#prerelease-tags, it should be `-alpha.0`, `-alpha.1`, `-beta.0` and since so forth. So lets make a `3.0.0-alpha.0` then.

**Comment by xzyfer** [comment]
node-semver will infer the prerelease identifier as whatever comes after the `-` so `pre`, `alpha`, `beta` are all valid. It's more a matter of eco-system consistency for which `pre` is kinda weird.

The caveat of moving from `pre` to `alpha` is anyone who now has `^3.0.0-pre` in their package.json will not get the auto update. I say stick with `3.0.0-pre.x` until we hit beta this time around.

**Comment by am11** [comment]
Lol I just released.

**Comment by xzyfer** [comment]
I just saw. Oh well lets see how it goes then.

**Comment by kudos** [comment]
When I just used `npm install --save-dev node-sass` and got 3.0.0-pre, without opting into a prerelease in any explicit way.

**Comment by am11** [comment]
Working like a charm here on Ubuntu!
Sometimes it takes time to sync the changes on npm server (aka lag): https://twitter.com/othiym23/status/522847862304956419. You can explicitly try `npm install node-sass@3.0.0-alpha.0`.
