### ISSUE TITLE
includePaths in custom importer

### ISSUE THREAD

**Issue by Snugug** [sass/node-sass#762]
I'd like to support `includePaths` in a custom importer, but I don't see a way to get the array of included paths from just a custom importer. Are the options passed in to `node-sass` available for importers to inspect so I can get it?

**Comment by Snugug** [comment]
For added background, I'm testing using `gulp-sass` 1.3.3 on Node v0.12.0 and `this` is undefined in my external importer.

**Comment by am11** [comment]
If you are talking about `result.stats.includePaths`, then no. Those paths are resolved during the compilation and returned, once the compilation is completed all by `LibSass`.

If you trying to access the `options.includePaths` array that you passed in options (or some custom array) in importer, you can get it via `this.options`. A new feature in node-sass v3.

For example:

```javascript
var sass = require('node-sass'); // using node-sass v3.0.0-pre
var options = {
  file: 'demo/test.scss',
  includePaths: ['/local/bin/libraries/javascript','/projects/'],
  blah: ['orange','apple','msft'],
  importer:function(file, prev) {
    var arr = this.options.includePaths
             .split(path.delimiter); // because this array was flattened to a string for libsass
    console.log('probe `includePaths`:', arr);  
    console.log('probe `blah`:', this.options.blah);
    return {
      file: myInterimPathProcessor(file, prev),
      contents: myInterimContentProcessor(file, prev)
    };
  }
};

sass.render(options, function(err, result) {
  // do stuff.. console.log(err, result);
  // or now you have result.stats.includePaths to play with
  // better late than never!
});

// Output:
//> probe `includePaths`: ['/local/bin/libraries/javascript', '/projects/']
//> probe `blah`: [ 'orange', 'apple', 'msft' ]
```

**Comment by Snugug** [comment]
I was referring to the later. I made the assumption that because `this` is documented the current README under the title **>=2.0.0** that it was available in that version or greater. I'll update to 3.0.0 and take a look.

**Comment by am11** [comment]
Yeah the docs needs an overhaul. You can refer to changelog to know which feature arrived in what version. https://github.com/sass/node-sass/releases/tag/v3.0.0-pre.

**Comment by Snugug** [comment]
Cool, yah this is all working for me now. Thank you again!
