### ISSUE TITLE
bug : node-sass api will automatically become a command-line app and block other console.log

### ISSUE THREAD

**Issue by benpptung** [sass/node-sass#769]
to reproduce it.

test.js file:

    var sass = require('node-sass');
    console.log('done');

Then, in command line, try the following command.

$ node test.js
done
$ node test.js --help
Wrapper around libsass

This is because in extension.js, node-sass will use meow module to parse the process arguments. 
Then, use them as flags. 

I don't understand why design it in this way, but it seems this will make node-sass as a pure command-line tool, and not an API for other module to require.

**Comment by am11** [comment]
Thanks for reporting this bug. It is fixed by 0f88e9a via #770.
