### ISSUE TITLE
Only Git tag prerelease builds rather than publish to NPM

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#772]
NPM lets people install by Git tag like `npm install node-sass@v3.0.0-alpha.0`, but it has no awareness of a prerelease package. Right now the alpha version will be installed by anyone just running `npm install node-sass`.

EX: NPM itself only has the latest stable 2.7.1 published https://www.npmjs.com/package/npm but they have tagged prereleases up to 2.7.3 https://github.com/npm/npm/releases/tag/v2.7.3

**Comment by am11** [comment]
I missed that one. I thought `npm` would just figure it out from semver. :)

Thanks for pointing it out. Moving forward, I will only publish the stable release to npm.

**Comment by am11** [comment]
I have created a new release [`v3.0.0-alpha.1`](https://github.com/sass/node-sass/releases/tag/v3.0.0-alpha.1). But I am unable to install it as: `npm install node-sass@v3.0.0-alpha.1`. However, explicitly specifying the org worked: `npm install sass/node-sass#v3.0.0-alpha.1`. 

Perhaps without specifying organization in slug is something special for npm itself?
Nonetheless we can live with it. :)

**Comment by nschonni** [comment]
I found a few things last night that I'll try to post here when I'm back home. The main one I came across is that I think you now need to use `npm dist-tag` https://docs.npmjs.com/cli/dist-tag to manage the tags you want to be able to `@tag` install.

**Comment by joliss** [comment]
> Moving forward, I will only publish the stable release to npm.

People using broccoli-sass are asking for the alpha updates; it'd be nice for them to have the alpha releases on npm too (maybe behind the npm tag thing? - I haven't used it) so that broccoli-sass can update the `package.json` dependency.

If not, we can just wait it out till 3.0.0 stable of course :)

**Comment by am11** [comment]
I have updated the release notes in package.json usage:  https://github.com/sass/node-sass/releases/tag/v3.0.0-alpha.1

Sent from my Windows Phone
________________________________

**Comment by joliss** [comment]
Cool. I've bumped the broccoli-sass dependency to `git+https://github.com/sass/node-sass#v3.0.0-alpha.1` (apparently HTTPS URLs tend to be more reliable, because firewalls). I worry that some people will still have trouble getting npm to download it from GitHub, but we'll see.

**Comment by mzgol** [comment]
You can publish alpha packages to npm, just tag them so that they're not tagged as latest:
```
npm publish --tag alpha
```

**Comment by kudos** [comment]
The horse has already bolted, not much point closing the stable doors now. 

Since the default package npm installs right now is 3.0.0-alpha.0, you may as well keep pushing onwards and learn from this mistake.

It might be useful to mark all of these pre-release packages as [deprecated](https://docs.npmjs.com/cli/deprecate) on the registry too so people will have some idea what they're getting into.

**Comment by kudos** [comment]
Actually, I take it back. I think something like this could work:

```
npm dist-tag rm node-sass@3.0.0-apha.0 latest
npm dist-tag add node-sass@3.0.0-apha.0 alpha
npm dist-tag add node-sass@3.0.0-pre alpha
npm dist-tag add node-sass@2.0.1 latest
```

**Comment by am11** [comment]
@kudos, thanks! 2.0.1 is set to latest: https://www.npmjs.com/package/node-sass.

**Comment by mzgol** [comment]
@kudos I wouldn't remove the latest tag; also, there's no point in adding the tag alpha twice (and order matters!). Tags point at one version exactly, tagging another version with the same tag moves the tag. Your suggestions sets 3.0.0-pre to alpha whereas 3.0.0-alpha.0 should get it.

**Comment by am11** [comment]
@mzgol, I added v2.0.1 to `latest` and v3.0.0-alpha.1 to `alpha`.

**Comment by kudos** [comment]
@mzgol didn't realise tags were unique, thanks for the heads up :)

@am11 glad it's sorted!
