### ISSUE TITLE
All latest non-alpha releases broken

### ISSUE THREAD

**Issue by haf** [sass/node-sass#773]
Please, publish a version that's not a pre-release version and that compiles, to npm.

The solution can not be 'use this alpha'.

Here are releases available:

```
  '1.2.3', <- old, broken?
  '2.0.0-beta', broken
  '2.0.0', broken
  '2.0.1', broken
  '3.0.0-alpha.0', works
  '3.0.0-pre' ] works
```

**Comment by haf** [comment]
Related https://github.com/sass/node-sass/issues/753

**Comment by am11** [comment]
Unfortunately there are no plans to visit v2 branch at this point.

**Comment by haf** [comment]
https://stackoverflow.com/questions/28409100/how-should-i-solve-error-libsass-bindings-not-found-try-reinstalling-node-sa/28974608#28974608

**Comment by haf** [comment]
https://gitter.im/webpack/webpack?at=550a3b7318b0c31d20df4b1a

**Comment by haf** [comment]
Why are there no plans when you're breaking your users? Don't you care about supporting them and following semver?

**Comment by xzyfer** [comment]
@am11 sounds like you should just in publish the pre release. It's causing
more problems than it solves.

**Comment by am11** [comment]
@xzyfer, Nick and I are already discussing this matter in an open issue. At this point I just don't have time to republish v2 tag, because simply I don't see many people complaining to death on this matter, as there is more than one workarounds to handle it. All the major down-streams at the moment have version lock on v2.0.1.

**Comment by gigablah** [comment]
"At this point I just don't have time to republish v2 tag"

Isn't it just moving one package from devDependencies to dependencies? Why force your users to work around this problem? And where are the workarounds documented?
