### ISSUE TITLE
`npm install node-sass` doesn't install latest pre-release

### ISSUE THREAD

**Issue by haf** [sass/node-sass#774]
```
$ npm install --save-dev node-sass
> node-sass@3.0.0-alpha.0 install /Users/abc/front/node_modules/node-sass
> node scripts/install.js
# etc
```

**Comment by am11** [comment]
It seems like it *does* install latest pre-release that is v3.0.0-alpha.0.

**Comment by kevva** [comment]
`npm install node-sass@next`

**Comment by haf** [comment]
Ok, so, to be clear, alpha.0 is after `pre`?

**Comment by am11** [comment]
Yes. 

You can see the list of releases here: https://github.com/sass/node-sass/releases.

The current release is `v3.0.0-alpha.1`.

You can also subscribe to atom feed (RSS'ish): https://github.com/sass/node-sass/releases.atom and also get email notification via [sibbell](http://sibbell.com/) (see the [philosophy](http://www.davegaeddert.com/2014/10/11/sibbell-emails-for-new-releases-on-github/) behind Sibbell project).

**Comment by haf** [comment]
Doesn't P sort after A?

Anyway, thanks for answering. That explains it.

**Comment by am11** [comment]
Preview and Alpha are interchangeable, we decided later to use alpha instead of pre. 
And last time I checked, it has nothing to do with sorting order..

**Comment by haf** [comment]
Ok, so it's the exact same code? They're not interchangeable from a semver perspective.

<blockquote>Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order.</blockquote>

From http://semver.org/ also see https://github.com/haf/semver/blob/master/spec/semver_spec.rb#L174-L186 for real-life tests for it.

**Comment by haf** [comment]
Btw, you should unpublish the pre-release if npm supports that.

**Comment by am11** [comment]
Not the exact code, see the release changelog.
They are interchangeable as in you can use either pre or alpha, they *imply* the same meaning.
As I mentioned earlier, it was later we decided to go with alpha instead of pre, and sticking with alpha in future. 
I understand this is against the principles of semver, but the damage has done.

**Comment by haf** [comment]
Just use this command https://docs.npmjs.com/cli/unpublish

**Comment by haf** [comment]
Or choose another greek character, like zeta.
