### ISSUE TITLE
When installing 3.0.0-alpha.0 cannot d/l binary

### ISSUE THREAD

**Issue by haf** [sass/node-sass#777]
I'm getting this output which causes the package to recompiled on every `npm install`:

```
> node-sass@3.0.0-pre install /app/node_modules/sass-loader/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download//v3.0.0-pre/linux-x64-14_binding.node
```

Is this the intended functionality?

**Comment by am11** [comment]
> Is this the intended functionality?

No.

Solution:

```
npm install sass/node-sass@v3.0.0-alpha.1
```

Aside, in title you are referring to alpha.0, but you are downloading 3.0.0-pre.

**Comment by haf** [comment]
Why are you closing the issues? They are not resolved.

I know they are different.

I don't *obviously* do a npm install explicitly, I try to freeze the dependencies in packages.config -- is this not the right method?

This is what the package.json looks like:

```
  "dependencies": {
    "async": "^0.9.0",
    "body-parser": "^1.9.3",
    "css-loader": "^0.9.0",
    "express": "^4.7.2",
    "extract-text-webpack-plugin": "^0.3.5",
    "file-loader": "^0.8.1",
    "html-loader": "^0.2.2",
    "items-store": "^0.4.2",
    "jsx-loader": "^0.12.0",
    "less": "^2.1.2",
    "less-loader": "^2.0.0",
    "markdown-loader": "^0.1.2",
    "node-sass": "^3.0.0-alpha.0",
    "null-loader": "^0.1.0",
    "react": "^0.12.1",
    "react-hot-loader": "^1.0.0",
    "react-proxy-loader": "^0.3.1",
    "react-router": "^0.12.0",
    "sass-loader": "^0.5.0",
    "style-loader": "^0.8.2",
    "superagent": "^0.21.0",
    "url-loader": "^0.5.5",
    "uuid": "^2.0.1",
    "webpack": "^1.3.2-beta9",
    "webpack-dev-server": "^1.4.7"
  }
```

The -pre gets installed by sass-loader. Is this not the intended behaviour?

**Comment by am11** [comment]
`"node-sass": "3.0.0-alpha.1",`

**Comment by haf** [comment]
If you spend 1 second reading what I wrote above you'll see that what is says.

**Comment by am11** [comment]
I have spend more than a second dude!

Your version:

 "node-sass": "^3.0.0-alpha.0",

My solution:

 "node-sass": "3.0.0-alpha.1", 

See the difference?

**Comment by haf** [comment]
Ah, ok, thank you, let me try that.

**Comment by am11** [comment]
Also put back binaries for -pre, so if anyone dearly want that, it is there.

**Comment by haf** [comment]
```
npm ERR! version not found: node-sass@3.0.0-alpha.1
```

**Comment by haf** [comment]
```
npm WARN deprecated node-sass@3.0.0-pre: This version is superseded in favour of 3.0.0-alpha.1
```

when switching back to alpha.0 which has been published.

**Comment by am11** [comment]
> when switching back to alpha.0 which has been published.

You probably need to clear your cache

```
npm cache clear
```

then

```
"node-sass": "3.0.0-alpha.0", 
```

Because alpha.1 is not published to npm and is hosted via GitHub, you will need to prefix the org name:

```
"node-sass": "sass/node-sass#v3.0.0-alpha.1", 
```

And it was # not @ (my bad). For more "tricks and tips", see this guide to find out how many ways one can install an npm package: https://docs.npmjs.com/cli/install.
