### ISSUE TITLE
When installing 3.0.0-alpha.0 cannot d/l binary

### ISSUE THREAD

**Issue by haf** [sass/node-sass#778]
Repro of #777 which is still an issue, and isn't ready to be closed.

I'm getting this output which causes the package to recompiled on every `npm install`:

```
> node-sass@3.0.0-pre install /app/node_modules/sass-loader/node_modules/node-sass
> node scripts/install.js

Can not download file from:,https://github.com/sass/node-sass/releases/download//v3.0.0-pre/linux-x64-14_binding.node
```

Is this the intended functionality?

**Comment by am11** [comment]
@haf, please stop opening further issue. I have answered your question there.

**Comment by haf** [comment]
No you haven't. While your library keep breaking these invariants and costing everyone time, I'm going to continue opening issues:

 - follow semver ordering, or unpublish `pre` or alternatively release something that sorts after `pre`
 - broken download like above, which you still haven't addressed
 - no non-broken non-prerelease release

Because all of the above are open and bleeding issues that is wasting everybody's time. You have can fix them if you stop closing the issue before you understand the implications.
