### ISSUE TITLE
npm package for 3.0.0-alpha.1

### ISSUE THREAD

**Issue by fourseven** [sass/node-sass#779]
I can't seem to find the 3.0.0-alpha.1 on npm, is it going to be published there?

**Comment by am11** [comment]
According to #772, we shouldn't publish any alphas / betas to npm: npm install sass/node-sass#v3.0.0-alpha.1.

We encourage to use github tag for nightly builds: `npm install sass/node-sass#v3.0.0-alpha.1` or in package.json `"node-sass": "sass/node-sass#v3.0.0-alpha.1"`.

**Comment by fourseven** [comment]
Ah, interesting. I'm trying to wrap through Meteor, which makes things more complex. They only support strict semver for their package versions anyway (3.0.0_1 for example) so I'm probably going to delay until node-sass 3.0.0 is final. 

Thanks for the quick response :+1:
