### ISSUE TITLE
gyp: libsass.gyp not found when building from git

### ISSUE THREAD

**Issue by haf** [sass/node-sass#788]
In package.json

```
  "devDependencies": {
    "css-loader": "*",
    "file-loader": "*",
    "jsx-loader": "*",
    "node-sass": "git://github.com:sass/node-sass.git#HEAD",
    "react-hot-loader": "^1.2.3",
    "sass": "*",
    "sass-loader": "*",
    "style-loader": "*",
    "url-loader": "*",
    "webpack": "*",
    "webpack-dev-server": "*"
  },
```

```
> node-sass@3.0.0-alpha.1 postinstall /node_modules/node-sass
> node scripts/build.js

` /node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/Cellar/node/0.12.0/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp: libsass.gyp not found (cwd: /node_modules/node-sass) while loading dependencies of binding.gyp while trying to load binding.gyp
```

Time to get your act together!

**Comment by saper** [comment]
can you publish your `git branch -vv` ? which commit are you on?

**Comment by enjoym** [comment]
Sorry, it seems that you have blocked @haf from the repository. You'll have to unblock him if you want answers to this.

In general, we're very sad to see the way that you handle your users.

**Comment by nschonni** [comment]
Sorry that was unintentional from me. I just didn't want to be getting more emails as he appeared to be opening multiple issues for release requests.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: enjoymSent: Monday, March 23, 2015 8:52 AMTo: sass/node-sassReply To: sass/node-sassSubject: Re: [node-sass] gyp: libsass.gyp not found when building from git (#788)Sorry, it seems that you have blocked @haf from the repository. You'll have to unblock him if you want answers to this.

In general, we're very sad to see the way that you handle your users.

—Reply to this email directly or view it on GitHub.
