### ISSUE TITLE
sourceComments path question

### ISSUE THREAD

**Issue by ivayloc** [sass/node-sass#789]
I am using node-sass with `sourceComments: true` , my questions is why the generated comments contains the full path to the source file:

`/* line 3, C:/Users/icherkezov/_lab/node-sass-2/MyPolicy/Content/sass/styles.scss */`

instead of:

`/* line 3, MyPolicy/Content/sass/styles.scss */`

**Comment by am11** [comment]
With `sourceComments` option, libsass emits diagnostics information for each selector it encounters.
It is supposed to be a raw debug info, hence the paths  are not resolved.

On a more serious note, this info emerges from core abstract syntax tree, where resolving canonical file paths will slow down the performance of the overall compilation.

For the browser dev tools aid, please use `sourceMap` option instead, as source-map carries relative paths.

**Comment by ivayloc** [comment]
Thanks for the replay
