### ISSUE TITLE
renderSync() doesn't exit the node process if an importer() function is provided.

### ISSUE THREAD

**Issue by aputinski** [sass/node-sass#794]
In both `2.0.1` and `3.0.0-alpha.0`, calling `renderSync()` with a custom `importer()` function works as expected, but causes the node process to never exit. This happens on node `0.10.36` as well as `0.12.0`. No errors are thrown and the correct result is returned. 

This works fine:

```js
var sass = require('node-sass');
var result = sass.renderSync({
  data: '.foo{background:red;}'
});
console.log(result.css);
```

This gives the same result, but never exits the node process (even though the importer isn't being used):

```js
var sass = require('node-sass');
var result = sass.renderSync({
  data: '.foo{background:red;}',
  importer: function(url, prev) {
    return {
      contents: '.bar{background:blue;}'
    };
  }
});
console.log(result.css);
```

**Comment by am11** [comment]
Are you using Windows?

**Comment by aputinski** [comment]
@am11 I'm on OSX 10.10.2

**Comment by am11** [comment]
Alright. This entire feature is rewritten and will be released with the upcoming beta. If it is still an issue, I will dive deeper.
Thanks for reporting it!

**Comment by saper** [comment]
Works for me using FreeBSD with `node 0.12`, `libsass 3.2.0-beta.2`, `node-sass 3.0.0-beta.4`

**Comment by xzyfer** [comment]
@aputinski can you please confirm whether this is still an issue with node-sass@3.0.0-beta.7?

**Comment by aputinski** [comment]
@xzyfer Just tried the above code with `3.0.0-beta.7` and everything seems to be working as expected. Thanks!

**Comment by xzyfer** [comment]
Thanks @aputinski!
