### ISSUE TITLE
release v2.0.2 w/ an iojs fix

### ISSUE THREAD

**Issue by jonathanong** [sass/node-sass#795]
see: https://github.com/sass/node-sass/pull/791#issuecomment-85425643

pretty please :heart_eyes_cat:

**Comment by adamck** [comment]
:+1:

**Comment by l4u** [comment]
:+1:

**Comment by dworzanski** [comment]
![image](https://cloud.githubusercontent.com/assets/1278707/6871695/6c39d142-d472-11e4-8df5-fdd20bb95825.png)

**Comment by am11** [comment]
:+1: 

Release v2.1.1. :tada:

**Comment by kevva** [comment]
:+1:
