### ISSUE TITLE
alpha.2?

### ISSUE THREAD

**Issue by chriseppstein** [sass/node-sass#796]
Could really use a new alpha release with the custom functions patch merged in :pray:

**Comment by am11** [comment]
v3.0.0-beta.1 is released. Waiting for binaries, which will take some time because I am going to try that [docker thingy](https://github.com/sass/libsass/issues/382#issuecomment-83519065) for the first time (C++11 lang features on CentOS 5x).

//cc @xzyfer

**Comment by am11** [comment]
FTR, to install v3.0.0-beta.1, it would be a matter of `npm install node-sass@beta`.

**Comment by am11** [comment]
`node-sass@beta` is released. Linux and Windows binaries published. Awaiting Mac binaries.
