### ISSUE TITLE
Build automation: Multiple issues with docker

### ISSUE THREAD

**Issue by am11** [sass/node-sass#800]
@QuLogic, @Vektah,

As per the previous conversation: https://github.com/sass/libsass/issues/382#issuecomment-83519065, I am building binaries for v3.0.0-beta.1 using docker container (so we don't have to manually build apply code patch to libsass).

So far I have this Dockerfile, https://gist.github.com/am11/1529b2458b1a1f4bdba8. I am able to configure nvm (which happen to not support x86-32 runtimes, hence these [ugly workarounds](https://gist.github.com/am11/1529b2458b1a1f4bdba8#file-node-sass_docker-sh-L56-L84)). 

The end objective is to get total of eight binaries for four versions of runtimes for both, 64 and 32 bit architectures.

I am able to build the x64 binaries, removing [lines 44-84](https://gist.github.com/am11/1529b2458b1a1f4bdba8#file-node-sass_docker-sh-L44-L84), but i386 build throw the following on linking:

>
SOLINK_MODULE(target) Release/obj.target/binding.node
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.0/ld: skipping incompatible /opt/centos/devtools
et-1.0/root/usr/lib/gcc/x86_64-CentOS-linux/4.7.0/libstdc++_nonshared.a when searching for -lstdc++_nonshared
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.0/ld: cannot find -lstdc++_nonshared
collect2: error: ld returned 1 exit status

I tried many solution ranging from setting `-m32` for CXX, CL, LD flags, but could not satisfy/shut-up linker..

Also tried a separate CentOS 5x i386 containers, such as this one: https://registry.hub.docker.com/u/gpmidi/centos-5/, but they all end up with varied issues: some are actually x86_64 (uname -a), some are versioned <= 5.10, so yum throws mirror not found server error. If this works out, we will also save us from the nvm hacks for i386.

---

Secondly, the last step is to add `vendor/` to a gzip image. After that I want to obtain that image in host so I can untar and upload to GitHub release. We already have upload-directly-to-GitHub-release script ready: [scripts/upload.js](https://github.com/sass/node-sass/blob/3d8ad45c304bbc23850066650d869fcfc217d190/scripts/upload.js), but for some crazy reason the uploaded binaries are corrupted (probably due to ill-serialization? or we should use zip content-type instead of application/octet-stream?). 

Once the process exits, the container goes in stale state, hence the following doesn't work:

```
docker cp <containerId>:/node-sass/binaries.tar.gz ./mystore
```

(from http://stackoverflow.com/a/22050116/863980)

where container id can be fetched from

```
docker ps -a
```

Do we need to upload it somewhere? or send as Email attachment? 

Also copying @xzyfer, @mgreter; feel free to chime in. :)

**Comment by am11** [comment]
@xzyfer, @nschonni I think we should add this Dockerfile to node-sass-binaries, so in future contributors can also build Linux binaries till we fully automate the binary publishing with node-pre-gyp (https://github.com/sass/node-sass/issues/56).

**Comment by saper** [comment]
Can you add `V=1` (for example `env V=1 node scripts/build -f`) and dump the full compilation log?

**Comment by saper** [comment]
You need a properly re-targeted compiler with i386 libgcc, and also i386 binutils

**Comment by am11** [comment]
@saper, I think I captured the most significant piece from the noise above. If you are looking for something else, can you give it a try and if succeeded let us know which step needed what modification?

**Comment by QuLogic** [comment]
> /opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.0/ld: skipping incompatible /opt/centos/devtoolset-1.0/root/usr/lib/gcc/x86_64-CentOS-linux/4.7.0/libstdc++_nonshared.a when searching for -lstdc++_nonshared

Yea, you need 32-bit libraries; it can only find 64-bit. Did you install `libstdc++.i686` (or i386, i586, etc.)?

**Comment by am11** [comment]
As per [line 48](https://gist.github.com/am11/1529b2458b1a1f4bdba8#file-node-sass_docker-sh-L48), I installed `libstdc++-devel.i386`. Is libstdc++.i386 different?

**Comment by Vektah** [comment]
You probably want devtools.i386 the centipedes packages are ancient

**Comment by saper** [comment]
No, @am11, I need to see compiler and linker flags your build is getting. But as it is mentioned here already, just -m32  is not enough if some platform-specific libraries are missing. Not only libstdc++ but also libgcc or crt* files.

**Comment by Vektah** [comment]
`libstdc++`/ is going to be gcc *4.1*, its the core centos version of libstdc++.

Devtoolkit is a more modern gcc, but they don't seem to provide 32bit binaries, only 64bit.

I guess the solution would be to build gcc...

**Comment by am11** [comment]
That's right. As it turned out, they have i386 tools for devtoolkit v1.1 and 2 but not 1.0: 
http://people.centos.org/tru/devtools-2/5/
http://people.centos.org/tru/devtools-1.1/5/
http://people.centos.org/tru/devtools/5/

With 1.1 and 2.0, I am getting other errors like missing g++ and since so forth.

I think the best course of action for time being would be to ship the x64 binaries for now (since those are building just fine) and then ship 32 bit binaries later at some point (it may be that not many people are using 32-bit OS, but some servers have 32 bit node installed, so we cannot dodge the 32 bit support forever).. Thoughts?

On this note, the second part of this issue, is there a way to obtain the compiled binaries in host OS? If not, I will create a rails app on my hosting with simple upload support and push the gzip image within docker. Long method, but the promising one that I have figured out so far.. A simple solution is most welcome!

**Comment by Vektah** [comment]
Ahh neat!

A few thoughts: 
 - Watch `yum`. It does a retarded thing with exit codes - if `anything` succeeds to install it returns success. This means that if you are doing a `yum -y install a b c devtools` and devtools failed to install it will not fail the build. 
 - later version of devtools will be in a different path, make sure the PATH in the dockerfile is updated to match the new location.

**Comment by am11** [comment]
Thank you. I will have a look after my working hours. :)

**Comment by Vektah** [comment]
I had some success with devtools-2

```
[root@51cbbdf15328 node-sass]# file /node-sass/vendor/linux-x64-11/binding.node
/node-sass/vendor/linux-x64-11/binding.node: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), not stripped
```

I've split the base centos + gcc 4.8 into its own Docker layer - https://github.com/vektah/centos5-gcc
Set to build automatically on docker hub as `vektah/centos5-gcc`

I got a bit lost in all of the nvm stuff, but a minimal Dockerfile for the 32bit binary is:
```
FROM vektah/centos5-gcc

RUN curl -SL https://rpm.nodesource.com/setup | sh
RUN yum install -y nodejs
RUN git clone https://github.com/sass/node-sass --recursive

WORKDIR /node-sass
RUN mv /usr/bin/python /usr/bin/python_ && mv /usr/bin/python26 /usr/bin/python
RUN npm install
RUN CFLAGS="-m32" CXXFLAGS="-m32" LDFLAGS="-m32" node scripts/build.js
```

build with: 
`docker build --tag node-sass-binary .`

As far as extracting the binary (or tarball) goes there are two ways:
 - cat it out: `docker run tag_name cat /node-sass/vendor/linux-x64-11/binding.node > local_file`
 - mount it and build it again. This is probably way better in CI: 
```
$ git checkout node-sass $HOME/projects/node-sass --recursive 
$ docker run -it -v $HOME/projects/node-sass:/node-sass -e CFLAGS="-m32" -e CXXFLAGS="-m32" -e LDFLAGS="-m32" ed4fb76b8542 node scripts/build.js
```
The -v is the magic, it mounts the hosts checkout into the container, so the binary is written straight out on the host.

**Comment by am11** [comment]
#### SUCCESS!

#### Thanks @Vektah! (-8

I would have used `vektah/centos-5-gcc` base container as is, but turned out there was a node.js system installation step in base. So I took the glorious parts from your Dockerfile and inlined `.repo` files (everything in a single `Dockerfile`).

Here is updated gist https://gist.github.com/am11/1529b2458b1a1f4bdba8
And see the comment below for usage: https://gist.github.com/am11/1529b2458b1a1f4bdba8#comment-1420215 (I used `cat` :smile_cat:)

Verified binaries by testing on another CentOS 5.11 and Ubuntu 12.0.4.
