### ISSUE TITLE
Support for polling interval with --watch

### ISSUE THREAD

**Issue by jareware** [sass/node-sass#801]
If using `node-sass --watch` in an environment where Gaze falls back to polling (e.g. networked file system) the polling can cause unnecessary CPU-load.

Would you consider some method for passing [the `interval` option](https://www.npmjs.com/package/gaze#properties) to Gaze?

**Comment by jareware** [comment]
Related: #636

**Comment by am11** [comment]
Thanks for your feedback. 

The `watch` feature of node-sass certainly needs a major overhauling, even besides the underlying dependency. There is an on-going PR, which will probably improve the situation: https://github.com/sass/node-sass/pull/782.

Currently, we are focusing on implementing the remaining features of libsass API and streamlining the build process. We will probably be able to visit it after v3.0.0.

Nonetheless, the PRs are always welcome; we still have time to include breaking changes in v3. Feel free to chip in. :)

**Comment by xzyfer** [comment]
I wonder what a good way to handle this via the CLI is. I don't want to duplicate all of Gaze's CLI options in our CLI.

Handling the API side of this is easy because we can simple pass through a `watch` object to Gaze.

**Comment by saper** [comment]
@jareware I've had some experience troubleshooting performance of NFS and I'd like to know more about your case before we take a stab at fixing it. What kind of environment is this? What is the performance issue you are experiencing? Are you running something like `rpc.statd` (if it's NFS indeed?)

**Comment by xzyfer** [comment]
I suspect this is not a performance issue. I suspect the 500ms polling interval just makes things feel sluggish relative the speed of the rest of the asset compilation tool chain. It's a feeling I can relate to, but I'm not convinced it's something we need to support. I opened a PR purely because it was very little overhead.

**Comment by xzyfer** [comment]
NVM I miss that this was a CPU issue. I doubt debugging this over GH issues will productive. Our slack channel is  better medium https://libsass-slack.herokuapp.com/. @jareware feel free to join us here if the issue persists.

Closing this in the interim as is appear to be an isolated case.

**Comment by jareware** [comment]
@saper, @xzyfer, sorry I was away from civilization for a few weeks. :)

The issue was (as I recall it) that the polling interval was too high, essentially busy-looping when looking for changes, whereas I would have been completely happy with e.g. looking every 250ms. But there was no option for it in node-sass.

Not an issue for me anymore (environment changed), so no need to reopen for me.
