### ISSUE TITLE
Where is image-url() ?

### ISSUE THREAD

**Issue by OnkelTem** [sass/node-sass#803]
I'm using none-sass of 2.0.1 version which was installed via dependencies from gulp-sass.
In my README.rm there is mention of ```imagePath``` setting which is used by ```image-url()```, but in the current version I don't see it.
Please, explain how to use image-url() then?

**Comment by mgreter** [comment]
From https://github.com/sass/node-sass/releases/tag/v3.0.0-pre
> Retired image path options. (driven by the change in libsass #702)

Or https://github.com/sass/libsass/releases/tag/3.2.0-beta.1
> Hard deprecated image-url and compact functions (throw errors until removed) (#834, #835)

**Comment by nschonni** [comment]
See the linked issues in #702 for the history on why it was removed.

**Comment by koenpunt** [comment]
I've created a module for node-sass which implements some of the `image-*` and `font-*` functions to use in conjunction with node-sass >= v3: https://github.com/fetch/node-sass-asset-functions
