### ISSUE TITLE
FreeBSD install of 2.0.1 fails with node 0.12

### ISSUE THREAD

**Issue by WillGreen** [sass/node-sass#804]
I'm trying to install node-sass on a FreeBSD 10.1 x64 system, but it fails to download the binding.node then cannot find module node-gyp. I have cleared my npm cache and tried reinstalling all modules to no avail. This system has a fresh install of the current FreeBSD packages for node and npm. 

Any advice appreciated.

FreeBSD Packages:
* node-0.12.0_1                  V8 JavaScript for client and server
* npm-2.7.0                      Node package manager
* gcc-4.8.4                      GNU Compiler Collection 4.8
* gmake-4.1_1                    GNU version of 'make' utility

```
# node -v
v0.12.0
# npm -v 
2.7.0

# npm install -g node-sass
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@2.0.1 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/freebsd-x64-node-0.12/binding.node

> node-sass@2.0.1 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed
```

**Comment by am11** [comment]
FreeBSD support will be made available from v3. See the v3 milestone's description: https://github.com/sass/node-sass/milestones.

**Comment by WillGreen** [comment]
Thanks for the quick reply. I mistakenly thought it was supported having read https://github.com/sass/node-sass-binaries/

I look forward to v3 release.

**Comment by saper** [comment]
There is no binary for the 2.0.1 version. I am working now on the official FreeBSD port.

How to work around the problem:

```env CC=clang CXX=clang++ LINK=clang++ SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1 V=1 npm -g install
```

I hope it works for you

**Comment by saper** [comment]
There is no binary for the 2.0.1 version. I am working now on the official FreeBSD port.

How to work around the problem:

```env CC=clang CXX=clang++ LINK=clang++ SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1 V=1 npm -g install
```

I hope it works for you

**Comment by WillGreen** [comment]
Thanks for the suggestion and I'm happy someone is working on a port.

However, I'm afraid it still fails even with the SKIP:

```
# env CC=clang CXX=clang++ LINK=clang++ SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1 V=1 npm -g install node-sass
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@2.0.1 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js

Skipping downloading binaries on CI builds

> node-sass@2.0.1 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed
```

**Comment by am11** [comment]
@WillGreen, we have two steps to build the binary:

* Lookup the prebuild binary.
* If prebuild binary is not found, or is broken, fallback to manual build

On Linux, Mac and Windows, the first step works most of the time as we invest lot of time building and verifying those binaries. However, the fallback step in node-sass is broken in v2.0.1, when we moved from node-gyp to pangyp (a shippable variant of node-gyp C++ module build tool, which supports io.js) and added it to `devDependencies` instead of `dependencies` in package.json.

For the time being, you can try out alpha version: https://github.com/sass/node-sass/releases/tag/v3.0.0-alpha.1, in which we have both prebuild binaries as well fix for gyp.

**Comment by WillGreen** [comment]
That install worked. Thank you. Fingers crossed it works for the application too. :-)

```
# npm install -g sass/node-sass#v3.0.0-alpha.1
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@3.0.0-alpha.1 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/local/lib/node_modules/node-sass/vendor/freebsd-x64-14/binding.node

> node-sass@3.0.0-alpha.1 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js

` /usr/local/lib/node_modules/node-sass/vendor/freebsd-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.0.0-alpha.1 /usr/local/lib/node_modules/node-sass
├── get-stdin@4.0.1
├── nan@1.7.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── meow@3.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8, semver@4.3.1)
├── gaze@0.5.1 (globule@0.1.0)
├── sass-graph@1.2.0 (commander@2.7.1, glob@4.5.3, lodash@2.4.1)
├── request@2.54.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.12.1, har-validator@1.4.0, hawk@2.3.1)
└── pangyp@2.1.0 (which@1.0.9, osenv@0.1.0, rimraf@2.2.8, graceful-fs@3.0.6, nopt@3.0.1, glob@4.3.5, semver@4.2.2, fstream@1.0.4, minimatch@2.0.4, tar@1.0.3, request@2.51.0, npmlog@1.0.0)
```

**Comment by am11** [comment]
:+1:

**Comment by krzysztofantczak** [comment]
Saper's hint with env also helps when You hit https://gist.github.com/krzysztofantczak/429042d17368de8f33b5 - also freebsd related stuff.

**Comment by saper** [comment]
It should help for all node-gyp or pangyp applications :)
