### ISSUE TITLE
Windows 7 Grunt/node-sass/libsass

### ISSUE THREAD

**Issue by eip56** [sass/node-sass#806]
Hello everyone,

I am attempting to run grunt on a folder and when I do I receive the following error:

Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

I have tried reloading both libsass and node-sass and getting the same results. 

When I check the node-sass dir this is what I am seeing:
C:\wamp\www\genericname>npm ls node-sass
foundation-libsass-template@0.0.1 C:\wamp\www\genericname
├─┬ grunt-libsass@0.2.0 extraneous
│ └── node-sass@0.8.6
└── node-sass@2.0.1  invalid
npm ERR! extraneous: grunt-libsass@0.2.0 C:\wamp\www\genericname\node_modules\gru
nt-libsass
npm ERR! invalid: node-sass@2.0.1 C:\wamp\www\genericname\node_modules\node-sass
npm ERR! not ok code 0

Any help in getting this resolved is greatly appreciated!

-Eric

**Comment by am11** [comment]
Hello,

Apparently, you are using grunt-libsass package, which uses a very old version of node-sass (v0.8.6).
https://github.com/project-collins/grunt-libsass/blob/master/package.json

I would suggest you to use grunt-sass package instead, which is most up-to-date: https://github.com/sindresorhus/grunt-sass.
