### ISSUE TITLE
includePaths not working on 2.0.1

### ISSUE THREAD

**Issue by bezoerb** [sass/node-sass#812]
Travis as well as an ubuntu 12.04.5 LTS vm with node 0.10.0 fails when using `grunt-sass` with the `includePaths` option set. 
```shell
Running "sass:all" (sass) task
OptionParser::InvalidOption: invalid option: --include-paths=bower_components
  Use --trace for backtrace.
```

See: https://github.com/bezoerb/generator-grunt-symfony/issues/10 for some more details.
My local copy using node 0.12.0 however is working fine as well as the cli version.

**Comment by am11** [comment]
When reporting issue on node-sass, please include the reproducible steps with node-sass API code.
More at bug reporting guidelines: https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md#bug-reports.

**Comment by bezoerb** [comment]
Thanks for the hint ;)
Looks like this is no node-sass issue. At least i can't reproduce the the error when using the node-sass API or the CLI directly. Sorry for the interrupt. I'll try to dig some deeper.
