### ISSUE TITLE
Doesn't install under n

### ISSUE THREAD

**Issue by secrettriangle** [sass/node-sass#816]
```sh
    npm install -g n
    n io stable # gets latest stable iojs
    n 0.12 # gets 0.12 node; `node` now refers to `iojs` but is still node
    npm install node-sass # fails

    readlink -f /usr/local/bin/node # should refer to iojs
    mv /usr/local/bin/node /usr/local/bin/node.bak
    mv /usr/local/bin/iojs /usr/local/bin/node
    npm install node-sass # now works
```

**Comment by am11** [comment]
Hello,

In v2, we were using runtime name in binary path, hence this issue. We have change the behavior in v3.

I don't know the theory behind `n`, but io.js started with v1x. 0.12 refers to node. But anyhow, if you are not happy with renaming io.js (v0.12?) to node, you can rename it as you did, once it is installed, rename node-sass/vendor/node-blah to node-sass/vendor/iojs-blah, then rename back the exec name to iojs, it will work.

Rest assured, we are not using this hard naming tying approach with v3 any more.
