### ISSUE TITLE
Version 3.0.0-pre is no longer available in npm

### ISSUE THREAD

**Issue by maspwr** [sass/node-sass#820]
Installing version 3.0.0-pre no longer works.

```
npm ERR! notarget No compatible version found: node-sass@'>=3.0.0-pre <4.0.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.9.4-rc1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.7.0-alpha","0.7.0","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4-rc1","0.9.4","0.9.5-rc1","0.9.5","0.9.6","1.0.0","1.0.1","1.0.2-alpha","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.2.0","1.2.1","1.2.2","1.2.3","2.0.0-beta","2.0.0","2.0.1","3.0.0-alpha.0","3.0.0-beta.2","3.0.0-beta.3","3.0.0-beta.4","2.1.0","2.1.1"]
```

**Comment by am11** [comment]
`npm install node-sass@beta` superseded it.

**Comment by maspwr** [comment]
Some libraries we were depending on (v0.5.0 of https://github.com/jtangelder/sass-loader) relied on it. I can see if they can release a newer version.

**Comment by maspwr** [comment]
It seems some Sass libraries are having trouble compiling under later releases of 3.0.0-X. If it's not too much trouble, could `3.0.0-pre` be republished for the time being to give some time to try and figure out why some libraries don't compile under `3.0.0-beta.4`?

**Comment by am11** [comment]
AFAICR, `node-sass@alpha` === `node-sass@pre`, so if you don't want to break compatibility just switch to alpha.

Nonetheless, please pin point where exactly are you having trouble with, we may able to fix it. Because the coming beta and RC will have tons of other breaking changes and these interim builds are meant to change. Moral of the story: don't rely on them too much for serious work unless v3 is solidify.

Would be happy to help.

**Comment by maspwr** [comment]
OK, thanks for the help. My preference would be to upgrade to sass-loader 1.0.0 and use 3.0.0-beta.4. But when compiling Foundation I get this error:

```
Module build failed:
      dialog, .#{$reveal-modal-class} {
             ^
      You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .reveal-modal" on line 203 of bower_components/foundation/scss/foundation/components/_reveal.scss
```

Line 203 looks like:

```
    dialog {
      @extend .#{$reveal-modal-class};  // Line 203
      display: none;

      &::backdrop, & + .backdrop {
        @include reveal-bg(false);
      }

      &[open]{
        display: block;
      }
    }
```

**Comment by blimmer** [comment]
@maspwr I am running into the same thing when I was forced to upgrade this morning, too. I [opened an issue](https://github.com/sass/node-sass/issues/823), since it's not directly related to this issue.

**Comment by am11** [comment]
@maspwr, do you get the same error with `node-sass@alpha`?

**Comment by maspwr** [comment]
Interestingly, yes. But I didn't get it with `-pre`.

**Comment by am11** [comment]
> Interestingly, yes

Indeed interesting. AFAICT, we didn't upgraded to libsass v3.2.0-beta.x until node-sass v3.0.0.beta.

On this note, can you make an [SSCCE](http://sscce.org/) for this issue?

**Comment by am11** [comment]
BTW, this error string was first introduce in libsass v3.2-beta, https://github.com/sass/libsass/pull/927.

Are you sure you are trying with node-sass@alpha? Because at that time we were using libsass v3.1.0. To wit: see https://github.com/sass/node-sass/blob/v3.0.0-alpha.1/package.json#L4 and https://github.com/sass/node-sass/tree/v3.0.0-alpha.1/src (libsassh hash `31521ef3ece636892f395a80392448ceae449b90` corresponds to v3.1.0)

You may need to clean your npm cache.

**Comment by maspwr** [comment]
I think you are right about the caching issue. Removing `node_modules`, doing `npm install` again, and compiling seems to work with `3.0.0-alpha.0`. The only issue I'm now seeing is that occasionally the compilation seems to hang. I'll have to keep investigating that one.

**Comment by am11** [comment]
Note that Foundation has removed that mixin. You will get exact same error with ruby-sass if you try something like:

```
h2 {
  color:transparent;
}
  
@media print{
  h1 {
    @extend h2;
  }
}
```

**Comment by maspwr** [comment]
@am11 We actually just ripped out Foundation, so that issue is no longer a problem. I also haven't seen the compilation hang anymore. We are now running `3.0.0-beta.4` without any noticeable issues. Thanks for your help!

**Comment by am11** [comment]
:+1:
