### ISSUE TITLE
Feature: Implement Custom Headers Support

### ISSUE THREAD

**Issue by am11** [sass/node-sass#822]
Corresponds to https://github.com/sass/libsass/pull/1000.

//cc @jhnns

**Comment by am11** [comment]
@xzyfer, just saw the rest of the conversation at sass/libsass#1000, I have changed the milestone. Based on whether or not libsass is going to continue with this feature (via RFC), we will hold off the implementation and continue supporting importer. Would you please open an RFC in libsass tracker so everyone can share thoughts on these features? It is really interesting feature, but violation of the core precepts of language design (as mentioned by @chriseppstein), I agree that it should not be continued.

(I think it would still possible to provision such functionality via custom plugin, but that can probably co-exit)

**Comment by xzyfer** [comment]
Apologies for being vague.

I'm waiting for @mgreter to chime in. I agree that multiple importers is a
great feature.

I think having both features lumped into a single PR has unintentionally
conflated to two features. For that reason I think the RFC is important for
these features to be fully understood.

**Comment by xzyfer** [comment]
Close this as custom headers is not ready for general use and isn't a LibSass priority until after 4.0.
