### ISSUE TITLE
Saving '&' as a variable

### ISSUE THREAD

**Issue by hobi** [sass/node-sass#829]
Hi, in my code I save `&` into variable `$parent` and after that I use it as a selector. 

(I use the gulp-sass which using node-sass)

Example of my code is below - which uses my super idea how to make the `.switch--people__radio:checked + .switch--people__label` selector.
```sass
  &--people {
    $parent: &;

    &__radio {
      display: none;
      margin: 0;
      padding: 0;

      &:checked + #{$parent}__label {
        font-weight: $g-weight-semi-bold;
        color: $g-color-primary;
      }
    }
```

But it throws an error.

```console
[14:29:17] Starting 'sass'...

stream.js:94
      throw er; // Unhandled stream error i
n pipe.
            ^
Error: error reading values after :
```

Is there any way how to fix it?

I want to use node-sass, because it is much faster than the ruby version (in my case 328ms vs ~2,5s - which is a really big difference).

**Comment by Snugug** [comment]
The problem lives in `Libsass`, specifically sass/libsass#548

That being said, that says it's closed there, I can't get this to work with `node-sass 3.0.0-beta.4`

**Comment by hobi** [comment]
@Snugug thank you for the info. I will wait a few more days until the next release. :)

**Comment by am11** [comment]
Lets track the progress at #827.
