### ISSUE TITLE
Implement random() function

### ISSUE THREAD

**Issue by gandazgul** [sass/node-sass#831]
Hi there,

libsass has added random() could you guys add it too?

https://github.com/sass/libsass/issues/657
http://sass-lang.com/documentation/Sass/Script/Functions.html#random-instance_method

Thank you

**Comment by am11** [comment]
Hi,
When libsass incorporates any language spec, it gets automagically supported by node-sass. Going by the history, this test https://github.com/sass/sass-spec/pull/151/files is passing since v2.0.1. The latest stable version is 2.1.1 and the beta is at v3. Which version are you testing against?

**Comment by gandazgul** [comment]
Ah, we have al old version, 0.9.6, I will look into upgrading. Sorry for the bad issue report.
