### ISSUE TITLE
Source maps doesn't work correctly (node-sass from CLI)

### ISSUE THREAD

**Issue by cachaito** [sass/node-sass#834]
Hi!
Tested environment: `Win7 64bit`, `Node 0.12.2`, `node-sass 2.1.1`

Code from Npm scripts CLI:
```
 "scripts": {
    "pretask-libsass": "node-sass --source-map true --output-style expanded scss/custom.scss .tmp/css/custom.css",
    "task-libsass": "node-sass --watch sass -o .tmp/css --source-map .tmp/css/custom.css.map --output-style expanded scss .tmp/css/custom.css"
    "start": "npm run task-libsass"
  }
```
I've noticed that when I DevTools inspect styles from imported *.scss files, it always pointing to the main custom.scss instead of _headers.scss or _typography.scss

**Comment by am11** [comment]
This issue belongs to LibSass. node-sass does not alter source-maps generate by LibSass.
LibSass recently fixed some source-map related issues, you can retest your usecase using [v3 beta](https://github.com/sass/node-sass/releases/tag/v3.0.0-beta.5).

**Comment by cachaito** [comment]
Thank You for answer @am11. I've tested `node-sass@3.0.0-beta.5` and amazingly simple: `node-sass --watch --source-map true scss/custom.scss -o .tmp/css` works correctly. Amazingly even the flag `--watch` works fine! (except every second *.scss save node-sass yields:
```
{
  "message": "File to read not found or unreadable: D:\\somePath\\scss\\custom.scss",
  "status": 4
}
```

**Comment by am11** [comment]
> except every second ...

This looks like resource acquisition issue with simultaneous I/O operations.
Seems like #801 is related, so lets tackle this issue there.
