### ISSUE TITLE
Stack Trace line numbers from errors in custom functions

### ISSUE THREAD

**Issue by chriseppstein** [sass/node-sass#843]
The line numbers reported in stack traces appear when there is an error from a custom function appear to have changed to be 0-index based instead 1-index based from the initial implementation of custom functions.

**Comment by chriseppstein** [comment]
I have the following Sass contents:

```js
"@import '<eyeglass>/assets'; div { background-image: asset-url('fake.png'); }"
```

The file imported by "<eyeglass>/assets" is:

```scss
@function asset-url($relative-path) {
  @return url(eyeglass-asset-uri($relative-path));
}
```

and I get the following error:

```
error in C function eyeglass-asset-uri: Asset not found: fake.png
Backtrace:
	<eyeglass>/assets:1, in function `eyeglass-asset-uri`
	<eyeglass>/assets:1, in function `asset-url`
	stdin:0
```

**Comment by saper** [comment]
Care to share a bit of `eyeglass-asset-uri`? Looks like a little bug in libsass

**Comment by chriseppstein** [comment]
@saper that function is defined in javascript.

**Comment by saper** [comment]
I know, I needed it to reproduce your error.

**Comment by chriseppstein** [comment]
@saper Any custom function that returns an error should suffice. my specific function would not run in isolation.

**Comment by saper** [comment]
Yep, I know, it looks like it's a simple `libsass` bug.
Can you try if https://github.com/saper/libsass/commit/2c5f97a14eaf50519b7e1176ffbf0eedb27ec735 fixes it for you? It needs to be applied to the libsass source you are using.

**Comment by chriseppstein** [comment]
@saper I don't have time to test this at the moment, but It looks good to me.

**Comment by am11** [comment]
This belongs to libsass. Lets follow the progress at https://github.com/sass/libsass/pull/1078.
