### ISSUE TITLE
Should result.css return a SlowBuffer?

### ISSUE THREAD

**Issue by chriseppstein** [sass/node-sass#845]
I've noticed that in some cases, `result.css` is a SlowBuffer instead of a plain string. Is this expected behavior? I can't find anything in the docs about it.

I'm able to reproduce this in the following script:

```js
var sass = require("node-sass");

var options = {
  data: ".test { version: version(); }",
  functions: {
    "version()": function(done) {
      done(sass.types.String('"' + "1.0.1" + '"'));
    }
  }
}
sass.render(options, function(err, result) {
  console.log(result.css);
});
```

It's a simple matter of calling `result.css.toString()`, but it just wasn't something I knew I needed to do.

**Comment by am11** [comment]
In the docs we have: https://github.com/sass/node-sass/#result-object

The behavior was changed after this discussion: https://github.com/sass/node-sass/issues/711.

**Comment by chriseppstein** [comment]
:+1: Thanks
