### ISSUE TITLE
Support for sass files on watch mode

### ISSUE THREAD

**Issue by vegetableman** [sass/node-sass#851]
Watch mode is not working for sass files on the current version. Simply changing the glob pattern on ```sass-graph.js``` from below code

```js
_(glob.sync(dir+"/**/*.scss", {})).forEach(function(file) {
     graph.addFile(path.resolve(file));
  });
```
to

```js
_(glob.sync(dir+"/**/*.s[ca]ss", {})).forEach(function(file) {
     graph.addFile(path.resolve(file));
  });
```

seems to do the trick. Would be great to see this supported.

**Comment by am11** [comment]
This is fixed in current master:

https://github.com/sass/node-sass/blob/3d44ce88d5fcefbf70abb9e8b69eb98d06ffcc16/bin/node-sass#L122

The sass-graph issue should be reported at https://github.com/xzyfer/sass-graph.

**Comment by vegetableman** [comment]
It doesn't seems so. I am using the master version, the above line does get the files (if dir)/file (if single) for both sass and scss, but sass-graph again does a glob search which eventually decides the files to be added to the watch list for gaze. I will open an issue on that repo. Thanks for pointing me to the right dir.

**Comment by am11** [comment]
:+1: 

@vegetableman, you would probably want to send a PR there, since you already have the solution. ;)

/cc @mgreter

**Comment by vegetableman** [comment]
Sure. but only if the fix is approved by
