### ISSUE TITLE
Install seems spit out an exit code of 1 before completing.

### ISSUE THREAD

**Issue by howardroark** [sass/node-sass#861]
To see the system I am testing this on you can use this [gist](https://gist.github.com/howardroark/25550e799297fafb3b94) (requires Vagrant and Virtualbox).  This box uses the latest 14.04 build from Ubuntu.

It appears that just before the install completes it spits out an exit code of `1`. Right around here...

```
npm info install node-sass@2.1.1

> node-sass@2.1.1 install /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/node-sass
> node scripts/install.js

npm info postinstall node-sass@2.1.1

> node-sass@2.1.1 postinstall /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/node-sass
> node scripts/build.js

`linux-x64-node-0.12` exists; testing
Binary is fine; exiting
node-sass@2.1.1 /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/node-sass
├── get-stdin@4.0.1
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── nan@1.7.0
├── cross-spawn@0.2.9 (lru-cache@2.5.2)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
```

This is problematic for me because I am attempting to build a system with provisioning tools that give up at first sight of an exit code with a value of `1`. 

Is there anything that could be done to avoid this?

Thanks very much!

**Comment by saper** [comment]
Right now with node-sass `master` (sass/node-sass@c481f30):

````
m> node scripts/install.js
m> echo $?
0
m> node scripts/build.js
` /home/saper/node_modules/node-sass/vendor/freebsd-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
m> echo $?
0
````

So both scripts return `0` (OK) when the requested binary is fine. Can you try this on your system?

**Comment by xzyfer** [comment]
@howardroark can you confirm whether this is still an issue on node-sass@beta. The 2.x branch is coming close to it's EOL.

**Comment by howardroark** [comment]
I think this may actually be more of an NPM issue than anything else. I'm getting 0 exit codes over and over when I run your scripts for 2.x and 3.x. I'm gonna close this up for now.

Thanks for the help though!
