### ISSUE TITLE
adjust-color() does not change anything

### ISSUE THREAD

**Issue by binarykitchen** [sass/node-sass#862]
```sass
linear-gradient(top, $header-button-background-color, adjust-color($header-button-background-color, $hue: -6deg, $lightness: -16, $saturation: -7));
```

Assuming $header-button-background-color is set to `#ffffff`, then I expect the above `adjust-color()` call to return `#d6d6d6` but it doesn't. It still returns the same, `#ffffff`. A bug? Or am I doing something wrong?

**Comment by xzyfer** [comment]
Thanks @binarykitchen. Node-sass is a simply wrapper over Libsass. 
Please open any Sass related issue at https://github.com/sass/libsass/issues with a copy pastable snipped showing issue, and the result of `./node_modules/.bin/node-sass -v`

**Comment by binarykitchen** [comment]
Fair enough, moved to https://github.com/sass/libsass/issues/1100

**Comment by xzyfer** [comment]
Thank you
