### ISSUE TITLE
Recursive output

### ISSUE THREAD

**Issue by talwoolf** [sass/node-sass#867]
There doesnt seem to be a way to recursively output files. All my attempts simply extract one file. my setup in package.json : ```cat ./app/styles/**/*.scss | node-sass | autoprefixer -b 'last 2 versions' | cleancss -o public/css/main.css```

is this even possible?

Thanks

**Comment by saper** [comment]
Do you mean UNIX `cat` does not support `**` syntax? Use `find app/styles -type f -name '*.scss' -print` to get a list of files to concatenate. You could even try

     find app/styles --type f -name '*.scss' -exec cat {} \; | node-sass

to feed them all to `node-sass`. It's a UNIX shell question, not a node-sass issue, is it?

**Comment by talwoolf** [comment]
Sorry, I think I explained it wrong and that this might be discussion on another thread. 

I am trying to find a way to output the compiled files individually, rather than into one compiled css file. So that when I run the command my sass input structure will be mirrored in my output folder.

Not sure if this is possible using node-sass.

Thanks

**Comment by saper** [comment]
That's unrelated to node-sass

a script similar to the one below would do the job:

```
find nt -name '*.scss' -exec $HOME/node_modules/node-sass/bin/node-sass {} `dirname {}`/`basename {} .scss`.css \;
```

**Comment by paulcpederson** [comment]
@talwoolf do you mean you want to compile multiple files in a sass directory and output them to a css directory? If so that was [added to the cli recently](https://github.com/sass/node-sass/pull/838) and should be part of the next beta version.

**Comment by talwoolf** [comment]
Amazing, thats exactly what I wanted. great work. Thanks.
