### ISSUE TITLE
node-sass returning logs instead of content

### ISSUE THREAD

**Issue by talwoolf** [sass/node-sass#868]
I am trying to use node sass with cli commands. I am using node child_process.spwan but when i get the stdout results, its just the console logs instead of the actual file.

Is this even possible? is it an issue or am i doing something wrong?

this is my code:

```var child = spawn( 'node-sass', [ filePath, '--output-style', 'compact', '--output', './public/css' ] );

	child.stdout.on('data', function (data) {
	  console.log('stdout: ' + data);
	});

	child.stderr.on('data', function (data) {
	  console.log('stderr: ' + data);
	});

	child.on('close', function (code) {
	  console.log('child process exited with code ' + code);
	});```

**Comment by saper** [comment]
Related: #855

**Comment by paulcpederson** [comment]
@talwoolf the node-sass cli pipes all messaging and errors to `stderr`. 
What is `filePath` in your above example? Also, is there a reason you can't  just use the node-sass api directly instead of spawning a child_process?

**Comment by talwoolf** [comment]
I was just trying to extract individual files rather than concatenate them into a single css output. I have sorted it now though.

Thanks

**Comment by paulcpederson** [comment]
Glad you got it figured out :+1:
