### ISSUE TITLE
Release 3.0.0-beta.6

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#873]
This is tracking the tasks required to release 3.0.0-beta.6

- [x] bump libSass and sass-spec to 3.2.0-beta.6 (https://github.com/sass/node-sass/pull/872)
- [x] build OSX binaries (https://github.com/sass/node-sass-binaries/pull/58)
- [x] build linux binaries
- [x] build windows binaries
- [x] mention known issue with Windows and iojs (#870)
- [x] update readme to clarify that custom importers and functions are highly experimental (#878)

### Optional

- [ ] build SmartOS binaries /cc @geekrohit @Candid
- [ ] build FreeBSD binaries /cc @saper 

@am11 @saper @geekrohit @Candid could you please assist in creating the relevant binaries and PR'ing node-sass-binaries?

You can use https://github.com/sass/node-sass-binaries/pull/58 as a template for said PR. We require binaries for node 0.10.latest, node 0.12.latest, iojs 1.0.0, iojs 1.7.1 on both 32 and 64 bit OSes. I recommend using [nvm](https://github.com/creationix/nvm) to manage the multiple node/iojs versions.

When this issue is closed 3.0.0-beta.6 will be released.

**Comment by xzyfer** [comment]
x-referencing https://github.com/sass/node-sass/issues/858 https://github.com/sass/node-sass/issues/713 https://github.com/sindresorhus/grunt-sass/issues/203

**Comment by djensen47** [comment]
Out of curiosity, why are SmartOS and FreeBSD optional?

**Comment by Jakobud** [comment]
Just curios, why doesn't node-sass version numbers stay consistent with the libsass version that is used? For example if libsass is at 3.2 and node-sass using that version, shouldn't node-sass say it's also version 3.2? Just for consistency sake? I came to this issue because when I was looking at my version of node-sass I had installed I saw 3.0.0 and my first thought was "it's using libsass 3.0?".

**Comment by xzyfer** [comment]
> Out of curiosity, why are SmartOS and FreeBSD optional? Or is it just optional for Beta 6?

@djensen47 for this beta, and potentially the initial stable release. I don't believe it makes sense (or fair?) to hold up a release waiting on FreeBSD or SmartOS binaries for a couple reasons.

- support for them is either very new or non-existent in current releases
- as a results using is on those OSes is small in comparison
- we don't currently have anyone owning the responsibility to build those binaries

Until we can automate the building of FreeBSD and SmartOS binaries, or someone volunteers to be responsible for doing so, it's hard to justify holding everyone else behind.

**To be clear we can trivially add these binaries as soon as they become available.**

If this is something you want to help with we're more than happy to make this a priority :)

**Comment by xzyfer** [comment]
> why doesn't node-sass version numbers stay consistent with the libsass version that is used

@Jakobud these are two distinct projects. Node-sass adheres strictly to semver. We desire the freedom to make improvements or breaking changes to our user face API independent of libSass releases.

Our relationship to libSass is analogous to grunt-sass' or gulp-sass' relationship to node-sass.

**Comment by mgreter** [comment]
I fully agree with @xzyfer, as it would tightly couple the release cycles of both projects, and that is not what you want, neither as a developer nor as a consumer! I agree, try to keep it somewhat close if possible, but semver goes first!

**Comment by xzyfer** [comment]
We're currently waiting on @am11 to either building our linux binaries, or instruct me on his process. There is some complication around our linux binaries as we need to support relatively old distributions.

**Comment by xzyfer** [comment]
x-referencing https://github.com/sass/node-sass/issues/850

**Comment by geekrohit** [comment]
On it. Will see if I can setup a jenkins task to do this and push. What say @xzyfer ?

**Comment by xzyfer** [comment]
Push to what exactly?

Ideally we need SmartOS binaries for node 0.10.38, 0.12.0, iojs 1.0.0, 1.7.1 on both 64 and 32 bit. Binaries should be submitted as PR to https://github.com/sass/node-sass-binaries.

Here is a good template to follow https://github.com/sass/node-sass-binaries/pull/58

**Comment by xzyfer** [comment]
I will be spending considerable time on automating this process for the next minor release. 
For now I'm keen to get this release out asap.

**Comment by geekrohit** [comment]
Yeah, will make a repo like that and submit for PR. Thats what I meant by using jenkins for doing that.

**Comment by xzyfer** [comment]
Oh ok, great. I currently use docker for as much as possible. I use a minor variation of this for building linux binaries - https://gist.github.com/am11/1529b2458b1a1f4bdba8

**Comment by saper** [comment]
Which commit should I base the FreeBSD ports on? Currently using 8b7ad43 for testing

**Comment by xzyfer** [comment]
I'll be creating the 3.0.0-beta.6 tag in minutes.

**Comment by frvge** [comment]
Very interested in the FreeBSD binaries here.

**Comment by chriseppstein** [comment]
:+1:


....


OMG I'm that guy.

**Comment by xzyfer** [comment]
This has been released as [v3.0.0-beta.7](https://github.com/sass/node-sass/releases/tag/v3.0.0-beta.7).

There was an npm hiccup on publishing v3.0.0-beta.6 so I have unpublished. My fault.
