### ISSUE TITLE
Pass the stdout on render

### ISSUE THREAD

**Issue by talwoolf** [sass/node-sass#877]
Is there a way I can sill get the stdout from writefile in the render method in order to still pipe the result through to other modules.

```So node-sass app/styles -o $npm_package_config_dest | chosenModuleToPipeTo```

I am using the beta version in order to export a directory rather than a single output.

**Comment by xzyfer** [comment]
We render to stdout by default. Using the `-o` flag redirects the output to
the designated location.

Outputting to stdout and a file at the same time doesn't make sense, and
violates the principal of least surprise.

**Comment by talwoolf** [comment]
Yeah thats fine, I am just going about it a differe
