### ISSUE TITLE
autoprefix before output using CLI in beta-6

### ISSUE THREAD

**Issue by talwoolf** [sass/node-sass#883]
Just a quick question with node-sass beta-6.. 

Whats the best approach to compile a directory and autoprefix each file before its output? is this even possible using CLI?

Thanks

**Comment by xzyfer** [comment]
>Whats the best approach to compile a directory

The current beta release allows you compile an entire directory via the cli - https://github.com/sass/node-sass#usage-1

>autoprefix each file before its output

This is not possible with node-sass cli. You can however use Gulp to achieve this.

This feature will never be in node-sass.
