### ISSUE TITLE
node build.js fails on my system

### ISSUE THREAD

**Issue by KarinLau** [sass/node-sass#884]
I tried to follow the instructions on http://wet-boew.github.io/wet-boew/docs/start-en.html#implement
under  “I want to customize WET and design a new WET theme“.
Point 5 “Run yo wet-boew-theme from the command prompt,..”  didn’t work out.
 
As I didn’t know how I had to answer the question
[?] What license do you want to use? (MIT)
I first tried with “MIT” the second time I left it empty. (The other tries I took M, I and T).
All tries ended with failure:
 
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
 
I appended the logs for the first 2 tries in the mail to 'andrewnez@gmail.com'; 'deanmao@gmail.com'; 'laurent.goderre@gmail.com'; 'npm@keithcirkel.co.uk'; 'adeelbm@outlook.com'; 'xzyfer@gmail.com'

**Comment by xzyfer** [comment]
Please attach the logs here.

**Comment by KarinLau** [comment]
Only PNG, GIF or JPG are allowed as attachment. 
Is there a better way than pasting the whole content in a post?

**Comment by xzyfer** [comment]
https://gist.github.com

**Comment by KarinLau** [comment]
Thanks, and here we go: 
https://gist.github.com/KarinLau/8444e64046005c503289#file-npm-debug_1sttry-log

**Comment by xzyfer** [comment]
I'm not familiar with wet-boew but they're using node-sass v 0.9.x which is very old. We're up to v3.x.

This appears to be an issue with their project, please an issue with them.
