### ISSUE TITLE
Getting the file context within a custom function

### ISSUE THREAD

**Issue by jameslnewell** [sass/node-sass#886]
Within a custom function I'd like to use the path of the invoking file containing the call to the custom function.

For example:
```js
    {
        'relative-url($url)': function(url) {
            var abs = path.resolve(path.dirname(this.callingFile), url.getValue());
            var rel = path.relative(path.dirname(this.rootFile), (abs));
            return sass.types.String('url("'+rel+'")');
        }
    }
```
Is that possible? If not where should I start looking?

Thanks.

**Comment by jameslnewell** [comment]
FYI I managed hack this up by using an importer method to prepend a $__dirname variable to each imported file, as well as a SASS function which proxies to a JS function to do the path manipulation. Code is [here](https://github.com/digitaledgeit/sass-composer/blob/master/lib/plugins/asset-url.js).

**Comment by xzyfer** [comment]
Thanks for the request @jameslnewell!

Closing this in favour of #895 as per https://github.com/sass/node-sass/issues/895#issuecomment-96849806.
