### ISSUE TITLE
clean install of 2.1.1 can't find nan

### ISSUE THREAD

**Issue by drewfish** [sass/node-sass#887]
When I try to install 2.1.1 w/out downloading binaries I get the following error

```
> node-sass@2.1.1 install /Users/folta/tmp/zz/node_modules/node-sass
> node scripts/install.js

Skipping downloading binaries on CI builds

> node-sass@2.1.1 postinstall /Users/folta/tmp/zz/node_modules/node-sass
> node scripts/build.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
```

I'm doing `SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true SASS_FORCE_BUILD=true npm i node-sass@2.1.1`.

I need to build the underlying sass lib from source since this is a corporate environment and downloading arbitrary binaries isn't considered safe.

**Comment by drewfish** [comment]
OK, nan@1.8.1 appears to be borked. The package.json lists `"main": "include_dirs.js"` yet the package tgz doesn't have that file.

**Comment by drewfish** [comment]
https://github.com/iojs/nan/issues/320

**Comment by drewfish** [comment]
OK, I was able to pin to nan@1.8.0 and then `SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true SASS_FORCE_BUILD=true npm run-script postinstall` which worked.

This is not your bug :)

**Comment by xzyfer** [comment]
Bumped to `nan@^1.8.4` to prevent this happening to other people https://github.com/sass/node-sass/pull/902
