### ISSUE TITLE
README.md is out of date

### ISSUE THREAD

**Issue by windwhinny** [sass/node-sass#890]
The example in README.md is out of date, should be update.

```javascript
// discard
var sass = require('node-sass');
sass.render({
    file: scss_filename,
    [, options..]
}, function(err, result) { /*...*/ });
```

```javascript
// new
var sass = require('node-sass');
sass.render({
    file: scss_filename,
    success: function(result) { /*...*/ },
    error: function(err) {/*...*/}
    [, options..]
});
```

**Comment by xzyfer** [comment]
Thanks for the report @windwhinny. I believe the readme currently reflects the 3.0.0-betas. The update you're suggesting is for the 2.1.1 release.

W'll make this more clear in the future. Since the 3.0.0-beta is about to be stable we will leave this as is.
