### ISSUE TITLE
Not installing on Win8 (64 bit)

### ISSUE THREAD

**Issue by andrey-luzin** [sass/node-sass#893]
Getting this error when installed node-sass. Ubuntu installs with no problem.
<pre>
<code>
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFra meworkVersion or PlatformToolset may be set to an invalid version number. [c:\projects\devvela-front\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(146,5): error MSB6006: "CL.exe" завершилась с кодом -1073741515. [c:\projects\d evvela-front\node_modules\node-sass\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\projects\devvela-front\node_modules\node-sass\node_modules\pangyp\lib\build.js:271:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\projects\\devvela-front\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd c:\projects\devvela-front\node_modules\node-sass
gyp ERR! node -v v1.8.1
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
</code>
</pre>

**Comment by xzyfer** [comment]
Hi @andrey-luzin can you please follow the instructions in this gist and paste the full output here - https://gist.github.com/am11/e5de3c49c219f0811e1d

**Comment by saper** [comment]
@andrey-luzin which version of Windows SDK do you have installed?

**Comment by saper** [comment]
The error message you are getting is C0000135 which is "Unable to locate component". You compiler cannot find Windows SDK or another important component.

**Comment by xzyfer** [comment]
Given that we supply Windows binaries I would have expected there wouldn't be any need for SDKs. Am I mistaken @saper ?

Frankly it's possible I didn't compile the binaries correctly. @am11 has always done that and I couldn't find any documentation on the topic.

**Comment by saper** [comment]
@xzyfer Obviously the log is from pangyp so somehow the build process got started. Maybe our supplied binary could not get loaded, we don't know. Maybe @andrey-luzin could provide a full log.

**Comment by andrey-luzin** [comment]
Problem solved. I installed <code>nodejs</code> and <code>iojs</code> via <a href="https://github.com/hakobera/nvmw">nvmw</a>, selected the current version and then install.

**Comment by saper** [comment]
:+1 good!

**Comment by xzyfer** [comment]
Great, I'll add this to the upcoming troubleshooting guide.

**Comment by xzyfer** [comment]
Thanks for all your help @saper
