### ISSUE TITLE
The last `.contents` property returned by an importer is always used

### ISSUE THREAD

**Issue by jameslnewell** [sass/node-sass#894]
When an importer function returns the `.contents` string, node-sass always uses the last returned value is used.

The following example imports a file called `foobar` twice with a different `.contents` returned each time. Node-sass always uses the last `.contents` for both imports resulting in `.barfoo` being repeated twice.

    var sass = require('node-sass');
    
    var i = 0;
    
    sass.render(
      {
        data: '@import "foobar"; @import "foobar";',
        importer: function(file, prev, cb) {
          console.log(file, prev);
    
          if (i++ === 0) {
            cb({contents: '.foobar {color: red;}'});
          } else {
            cb({contents: '.barfoo {color: blue;}'});
          }
    
        }
      },
      function(err, result) {
        if (err) {
          console.log(err);
        } else {
          console.log(result.css.toString());
        }
      }
    );

Note: Using a `.file` result for one import and a `.contents` result for the other import does not result in the same issue.

I'm using node-sass `3.0.0-beta.7`, libsass `3.2.0-beta.6` and running on OS X 10.10.3.

**Comment by xzyfer** [comment]
I haven't had a chance to look into this yet.

Could this be a race condition? Can you confirm both callbacks are being
called.

**Comment by saper** [comment]
confirmed here.

**Comment by xzyfer** [comment]
Thank @jameslnewell and @saper. I'm scheduling this for v3.next.

**Comment by saper** [comment]
Early research indicates this is a bug in `libsass`. Will follow up.

**Comment by xzyfer** [comment]
After some digging I've confirmed this actually not the case. Custom importers are working as expected.

The test cases provided illustrates a feature of LibSass which is caching of import resolution. Custom importers must be idempotent, meaning that given the same input they **must** return the same output. Given this restriction the result of the importer is cached within LibSass.

**Comment by saper** [comment]
@xzyfer I have a question:

 https://github.com/sass/libsass/wiki/API-Sass-Importer says

> Imports have to be relative from the parent import context. Therefore we need to pass this information to the importer callback. This is currently done by passing the complete import string/path of the previous import context.

If the imports are idempotent, why do we have `prev` parameter then?

**Comment by xzyfer** [comment]
I expect only @mgreter knows the answer to that question.

**Comment by saper** [comment]
Ruby has two methods (http://sass-lang.com/documentation/Sass/Importers/Base.html):

````
(Sass::Engine?) find(uri, options) 
(Sass::Engine?) find_relative(uri, base, options) 
````

so there is some notion of the importer being relative to some abstract `base` (maybe a directory, maybe not), so different meanings of `uri` can be provided, per "parent" context. 

`prev` is I think just a simple workaround in libsass to provide something similar.

Plus Sass importers may use http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options to generate their output, but that does not necessary preclude idempotency (as long as the options stay constant per run). But this is another story (I think there is an issue for that somewhere).

**Comment by mgreter** [comment]
`prev` is given in case the import is relative. It's the job of the importer to do the proper resolving and to return an "absolute" and canonical path back to libsass plus (optionaly) the fetched content. That "absolute" path is the idempotent part @xzyfer mentions. This "absolute" path is then used as argument for `prev` for all sub-imports found in the content.
