### ISSUE TITLE
implement --check

### ISSUE THREAD

**Issue by serkanyersen** [sass/node-sass#896]
Ruby sass has a feature where you can send flag `--check` which instead of compiling the file checks for syntax errors and displays found problems in a human readable way.

I got node-sass to do the same thing but I have to force it to print out to stdout and suppress the output, and if there is an error, error is in json format.

`node-sass --stdout path/to/file.sass >/dev/null`

I was using this feature of ruby sass in the `pre-commit` hook and would print sass error before committing in a readable way. Now that I switch to node-sass completely I want to also move pre-commit hook to node-sass as well.

Right now it works with the above command by just printing the json string but it would be nice to have human readable version as well.

Ruby sass output
```
$: sass --check path/to/file.sass
Error: Invalid CSS after "some style ": expected selector, was "{"
        on line 2 of path/to/file.sass
  Use --trace for backtrace.
```

node-sass output
```
$: node-sass --stdout path/to/file.sass >/dev/null
{
  "status": 1,
  "file": "path/to/file.sass",
  "line": 2,
  "column": 12,
  "message": "invalid property name",
  "code": 1
}
```

**Comment by xzyfer** [comment]
Thanks for the suggestion @serkanyersen !

I agree this sounds like a useful feature. I'm scheduling it for the vNext.

**Comment by am11** [comment]
This seems like dup of https://github.com/sass/node-sass/issues/680.

**Comment by xzyfer** [comment]
Welcome back @am11 

I think this is very different to #680, but does address a form of linting. In this case we simply want to know if the file is a valid sass file.

**Comment by xzyfer** [comment]
@serkanyersen is the expectation that is stops after the first error?

**Comment by radum** [comment]
@xzyfer Ideally it should show all errors and stop after the last one. Stoping after the first one will be counterproductive as you will have to run the commit over and over again to see all of them.

**Comment by xzyfer** [comment]
I don't believe what you're asking for is technically possible. Most (if
not all) Sass errors are unrecoverable. I believe the Ruby Sass engine stop
after the first error.

**Comment by radum** [comment]
Hmm good point, you are correct, sorry. I was mixing what a linter does with this one.

**Comment by xzyfer** [comment]
Node sass made stdout the default in v3 so you no longer need to pipe to `/dev/null`. As is stands this feature is no long required as it's the default behaviour.
