### ISSUE TITLE
Update libsass to 3.2.2

### ISSUE THREAD

**Issue by lucasmotta** [sass/node-sass#897]
They just released the 3.2.0 version:
https://github.com/sass/libsass/releases/tag/3.2.0

There is ton of nice things on this release, so it would be great to see `node-sass` updated too.

**Comment by saper** [comment]
We are following libsass very closely, so please expect node-sass to be upgraded soon. If you would like to try libsass 3.2.0 yourself, you can compile the library yourself and just tell node_sass to use it by setting `LIBSASS_EXT` environment variable. For more details please see https://github.com/sass/node-sass/pull/763#issuecomment-81253363.

**Comment by OnkelTem** [comment]
Can't wait!

**Comment by xzyfer** [comment]
This will land in node-sass@3.0.0. You can track the progress in the [milstone]( https://github.com/sass/node-sass/milestones/3.0).

Ideally we'll have this out within the week.

**Comment by xzyfer** [comment]
Fixed in 3.0.0.
