### ISSUE TITLE
Missing source maps support for multi-file compilation

### ISSUE THREAD

**Issue by kkopachev** [sass/node-sass#903]
Currently it is impossible to compile directory with source maps output.

`node-sass --source-map=true -r -o ./css ./scss` outputs all maps into one file `./css/scss.css.map` which contains sourcemap content for last compiled file.
If I specify directory for source maps `node-sass --source-map=css -r -o ./css ./scss` then it throws an error 
```
Rendering Complete, saving .css file...
ErrorError: EISDIR, open '/home/kkopachev/dev/css'
```

version info
```
$ node-sass -v
node-sass	3.0.0-beta.7	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.6	(Sass Compiler)	[C/C++]
```

multi-file compilation was added in https://github.com/sass/node-sass/pull/838

**Comment by am11** [comment]
Fixed by 1c65c53 va #964.
