### ISSUE TITLE
`libsass` binding not found

### ISSUE THREAD

**Issue by caseymorrisus** [sass/node-sass#906]
I've seen several threads elsewhere with this same issue, must have tried 20 solutions, none worked for me so far.

     "Uncaught Error: `libsass` bindings not found. Try rei nstalling `node-sass`?", source:     C:\Users\Casey\Electron\resources\app\node_modules\node-sass\lib\index.js (22)

**Comment by saper** [comment]
What does `npm install node-sass@beta` say?

**Comment by caseymorrisus** [comment]
Still getting the same error unfortunately. Also tried(with the same results):

`npm uninstall node-sass`
`npm cache clean`
`npm install node-sass@beta`

Error:

     "Uncaught Error: `libsass` bindings not found. Try reinstalling `node-sass`?", source: C:\Users\Casey\Electron\resources\app\node_modules\node-sass\lib\extensions.js (146)

**Comment by saper** [comment]
Can you please post a full output of `node install node-sass@beta` to gist.github.com?

**Comment by caseymorrisus** [comment]
Ahhh sorry for the misunderstanding. I assume you mean `npm install node-sass@beta` correct?

https://gist.github.com/caseymorrisus/27ea6ebe0ccc3493c2c4

**Comment by saper** [comment]
Thanks. The above link indicates that node-sass is installing correctly in `C:\Users\Casey\Electron\resources\app\node_modules\node-sass`

**Comment by caseymorrisus** [comment]
Any idea what could be causing the bindings not found error? Been working on fixing this for a few days.

**Comment by saper** [comment]
I am sorry, you give too little information.

**Comment by caseymorrisus** [comment]
Sorry about that, I'm not sure what you need to know. I'm currently trying to implement node-sass into my Electron (Atom Shell) project. Just trying to `require('node-sass')` produces the error I provided upon launching my application.

**Comment by saper** [comment]
I don't think we provide binaries from the atom shell and the original binary file for Windows might not work.

**Comment by caseymorrisus** [comment]
I am also running Windows 7 if that helps. I will test this out on OSX in ~1-2 hours to see if the problem exists there as well.

**Comment by saper** [comment]
See some discussion about atom shell compatibility: https://github.com/atom/electron/issues/533 https://github.com/atom/electron/pull/1002 https://github.com/iojs/nan/issues/226 

If you run normal `npm install node-sass@beta` you are probably using normal `node` and `npm` and not their atom counterparts, that's why it works.

**Comment by xzyfer** [comment]
@caseymorrisus please produce the full output from the following commands https://gist.github.com/am11/e5de3c49c219f0811e1d

Make sure substitute `npm install node-sass` with `npm install node-sass@beta`

**Comment by saper** [comment]
This PowerShell script might work just fine, as it uses normal `node` and `npm`. https://gist.githubusercontent.com/caseymorrisus/27ea6ebe0ccc3493c2c4/raw/f174f5f63a11b6ae556042e3f4a507354e64ae27/gistfile1.txt shows it installs just fine. We need to run it under atom shell, probably with `apm` or something. I don't know which engine atom shell uses, what is their module version number  etc. I  tried to compile atom shell but failed and gave up.


Somebody should step up and compile atom shell binaries and we should add them to the supported matrix. In the meantime  @caseymorrisus might try to compile the binding from the source (Visual Studio and Windows SDKs are required). I guess that the binary path will be the same as for other engines, just linking to some atomized iojs library.

For now, the answer is, "we need help to run node-sass under atom shell".

**Comment by caseymorrisus** [comment]
@xzyfer Headed out to work, will try this out on my windows machine when I get home. 

@saper I could give it a go, but I'll admit I don't know much about compiling. I might try to ask around my network of friends to see if anyone is willing to give it a go.

**Comment by SerenadeX** [comment]
+1 on OS X.  I gave it a shot running 3.0.0 and it won't launch because of that same error.

**Comment by xzyfer** [comment]
@SerenadeX please follow the steps in the troubleshooting guide exactly, and paste the output in a https://gist.gihtub.com.

https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx

**Comment by benmirkhah** [comment]
I ended up with this bug after updating my node to the latest version,
I fond this thread and followed all the steps above to no result, 
turns out the problem was gulp-sass, updating it to the newest version resolved it.

**Comment by Riuujin** [comment]
I had the same problem when using visual studio task explorer, it appears visual studio comes with its own node version (always x86). Luckily in vs2015 you can set it to use the version from the PATH, see http://blogs.msdn.com/b/webdev/archive/2015/03/19/customize-external-web-tools-in-visual-studio-2015.aspx for more info)

**Comment by r3db** [comment]
@Riuujin
:+1: Fixed my problem!

**Comment by r3db** [comment]
I don't know if it helps but in one of my machines none of the suggestions on this thread helped.
Until I ran.

`npm install node-sass`
`npm rebuild node-sass`

**Comment by xzyfer** [comment]
This appears to be resolved.

**Comment by Deminetix** [comment]
`npm rebuild node-sass` magically worked. No idea why

**Comment by xzyfer** [comment]
For context this error is almost always because `npm install` ran with a
different version of node than the version you're current running.

Since node-sass is a native module we build the c++ code on installation.
That code is tied to the version of node that ran the installation. If you
change your node version the extension needs to be rebuilt, that's what
`npm rebuild` does.

It's our fault for not producing a more useful error message. This will be
fixed.

**Comment by xzyfer** [comment]
A better error message will now be shown when this happens. https://github.com/sass/node-sass/pull/1148

>Error: The `libsass` binding was found in /Users/michael/Projects/Sass/node-sass/vendor/darwin-x64-45/binding.node
>This usually happens because your node version has changed.
>Run `npm rebuild node-sass` to build the binding for your current node version.

**Comment by AshConnolly** [comment]
@r3db
Thanks! :D
