### ISSUE TITLE
Create a troubleshooting guide

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#916]
We need a trouble shooting guide addresses some common issues. This will hopefully cut down on duplicate issues.

### Useful resources

**node-sass installation debug script (Windows)**
https://gist.github.com/am11/e5de3c49c219f0811e1d

**node-sass installation debug script (Linux/Mac)**
https://gist.github.com/am11/9f429c211822a9b15aee

### Common issues

- "Module did not self-register"on Windows w/ iojs
- `Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 209` with node-sass < 3.0.0
- can't install as root https://github.com/sass/node-sass/issues/919#issuecomment-98413667

**Comment by saper** [comment]
Maybe we could write it on a wiki here?

**Comment by xzyfer** [comment]
I reaaalllyy dislike wikis for just about anything. I'd rather a TROUBLESHOOTING.md. Documents in repos are better for a bunch of reasons

- it's available offline when you checkout the repo
- it can be version controlled
- it can be part of PRs

@sindresorhus has written on the topic and I completely agree - https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4

**Comment by saper** [comment]
On Sat, 2 May 2015, Michael Mifsud wrote:

> I reaaalllyy dislike wikis for just about anything. 

Ah, didn't know that

> I'd rather a TROUBLESHOOTING.md. Documents in repos are better for a bunch of reasons
> 
> - it's available offline when you checkout the repo
> - it can be version controlled

True for wikis as well

> - it can be part of PRs
> 
> @sindresorhus has written on the topic and I completely agree - https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4

I fully agree that the guide should be in the TROUBLESHOOTING.md
or something like that (I can even write a manpage).

The point is just to get started and collect issues - unfortunately
the issue we are commenting now is not editable. Writing comments
to this PR is much worse than wiki. 

Wiki stuff copy-edited should go into the repo, no question.

**Comment by xzyfer** [comment]
>True for wikis as well 

True but it requires as separate checkout and most people aren't away wikis are also repos. You still can't PR them though, so it's hard to get community involvement.

>unfortunately the issue we are commenting now is not editable

Completely agree. This issue a place holder, and a single point of reference for when the document is being written.

I didn't want to have to crawl through the issue tracker.
