### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sridwan** [sass/node-sass#919]
ubuntu 14.04
node v0.12.2 (compile from source)
npm v2.7.4

when installing node-sass locally `npm install node-sass`, got this error:

    -
    > node-sass@2.1.1 install /root/sandbox/node_modules/node-sass
    > node scripts/install.js

    module.js:338
        throw err;
              ^
    Error: Cannot find module '/root/sandbox/node_modules/node-sass/scripts/install.js'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    npm ERR! Linux 3.13.0-49-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sass"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@2.1.1 install: `node scripts/install.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@2.1.1 install script 'node scripts/install.js'.

Tried `node-sass@2.0.0-beta`, same error.

But when install globally `npm install -g node-sass` install successful.

It will be helpful if can install locally per project.
Any help / hints would be very appreciated.

**Comment by saper** [comment]
Is `npm install node-sass@beta` any better? (without 2.0.0)

**Comment by sridwan** [comment]
`npm install node-sass@beta`

Yes the error is exactly the same

    npm ERR! node-sass@3.0.0-beta.7 install: `node scripts/install.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@3.0.0-beta.7 install script 'node scripts/install.js'.

**Comment by saper** [comment]
Can you post a whole log including your command to gist.github.org? use `script` if you can
L

**Comment by sridwan** [comment]
https://gist.github.com/sridwan/076b57741481d219b94b

I've upload `npm-debug.log` for both `npm install node-sass` and  `npm install node-sass@beta`

**Comment by saper** [comment]
Can you try: `npm install --unsafe-perm node-sass@beta`

or try as usual but not as root?

**Comment by sridwan** [comment]
Yes, it installs succesfully.

**Comment by saper** [comment]
So I think you have a normal behaviour of npm - it refuses to run scripts as `root` unless you tell it `--unsafe-perm` or configure it in `.npmrc`. `-g` works because it's difficult to do this on a typical system without being root.

I think we can close this because it is not specific to node-sass at all.
