### ISSUE TITLE
sass.render() never calls back

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#923]
For me, using node-sass v2.1.1 on io.js v1.8.1, the callback is never called.

```js
var options = {
  data: 'body { p { color: blue; } }'
};

sass.render(options, function (err, result) {
  // this is never called.
});
```

But if I change to use the sync version, it works:

```js

var result = sass.renderSync(options);
// result.css is correct here
```

Any idea what could be causing this?

**Comment by xzyfer** [comment]
`render` in node-sass 2.x took the callback as an option, not a second parameter.

```js
sass.render({
  file: '/path/to/file.scss',
  success: function (data) { },
  error: function (err) { }
})
```

The readme is currently for the 3.x release, but you can see the 2.x docs here https://github.com/sass/node-sass/tree/226861c6a186291f9e957697f1115e1ddb4a4202
