### ISSUE TITLE
Calling render without file or data produces a cryptic error message

### ISSUE THREAD

**Issue by callumlocke** [sass/node-sass#924]
On master, and doing `sass.render({contents: input}, callback)`.

When `input` is an empty string, I get the error `File context created without an input path`.

**Comment by xzyfer** [comment]
Hi @callumlocke, node-sass@3.x (master) doesn't support `contents` as an option. You will need to use either `file` or `data` for file paths for file data respectively.

We should provide a more informative error message.

**Comment by callumlocke** [comment]
But contents works fine for me. (Just not with an empty string.)

**Comment by xzyfer** [comment]
Interesting... can you please supply an example of how you're using node-sass with `contents`?

**Comment by callumlocke** [comment]
No wait, maybe I am using data not contents. Not at a computer right now. I probably just entered the issue wrong. Sorry for confusion.

The point is, whatever property name I'm using, it works fine - except for when the value is an empty string, in which case I get the obscure error message.

**Comment by xzyfer** [comment]
Thanks for the clarification, I do think we need a better error message in this case.

**Comment by saper** [comment]
Empty braces cause this as well:

````
var sass = require('node-sass');

sass.render({
}, function(err, result) {
   if (err) {
        console.error(err);
   } else {
        console.log('successfully rendered');
   }
});
````

https://github.com/sass/node-sass/pull/915#issuecomment-99056525

**Comment by callumlocke** [comment]
So there's two separate problems:

1. Cryptic error message if you fail to provide either `file` or `data` (i.e. if both are undefined).

2. If `data` is an empty string, node-sass behaves as if it's undefined, and errors out. An empty string is valid Sass so it should not error. Should I open this as a separate issue?

**Comment by saper** [comment]
No, no need to, thanks.

**Comment by saper** [comment]
Should be fixed by #956. Now I think that the behaviour with `render({})` is acceptable - we can complain either about data or file context; we don't know which one was really meant.

**Comment by callumlocke** [comment]
It still errors out for me if I try to render/import a file that happens to be empty.

**Comment by jmartsch** [comment]
I have the same problem when running my gulp-sass task. When one ore more files of my template are empty, the error ```undefined:undefined  File context created without an input path``` occurs.

**Comment by xzyfer** [comment]
@callumlocke the patch has not yet been merged. It'll be in the next release of node-sass.

**Comment by saper** [comment]
Would `No input specified: provide options.data or options.file` be a better error message?

I also wonder what we should return in case of async functions: show we call a callback and emulate a `libsass` error JSON object?

**Comment by saper** [comment]
#956 should be ready for testing.

**Comment by xzyfer** [comment]
>Would `No input specified: provide options.data or options.file` be a better error message?

Yes. It's exponentially better.

>I also wonder what we should do in case of async functions

You suggestion sounds legit.
