### ISSUE TITLE
README on npmjs.com shows incorrect documentation

### ISSUE THREAD

**Issue by lennym** [sass/node-sass#925]
I'm fairly sure this is an issue with npm itself, but @keithamus asked that I raise an issue here.

The README file that is displayed at https://www.npmjs.com/package/node-sass is showing the usage information for the latest (3.*) version rather than the currently active 2.1.1 version.

In particular it shows `render` as taking a callback argument, which is not the case in 2.1.1.

**Comment by lennym** [comment]
Note that the README that is included in the 2.1.1 package is the correct version, which is what led me to conclude it is an issue with npm itself loading the incorrect README file and/or overwriting it with that from a pre-release version.

**Comment by lennym** [comment]
Confirmed issue with npm - https://github.com/npm/npm/issues/5259

**Comment by xzyfer** [comment]
Thanks for bringing this up. We'll be pushing 3.0.0 out soon negating this issue for the time being.

**Comment by xzyfer** [comment]
With 3.0.0 out now the readme is accurate once again :)

**Comment by lennym** [comment]
:+1: Thanks.
