### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Soularix** [sass/node-sass#933]
When I try to instal node-sass it shows up :
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'trim' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Souhaib\npm-debug.log

**Comment by xzyfer** [comment]
Hi @Soularix, please follow the steps in out troubleshooting guide and produce the output.

https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#windows-1

**Comment by Soularix** [comment]
I followed the steps but I still get the same error :
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'trim' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
-
npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp1\npm-debug.log

C:\temp1>cd node_modules\node-sass\vendor
The system cannot find the path specified.

**Comment by xzyfer** [comment]
That's fine. However we need to output from those commands before we can offer any help.

**Comment by Soularix** [comment]
what commands ?

**Comment by xzyfer** [comment]
The commands shown on our troubleshooting guide https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#windows-1

Please follow **every** single step and paste the output here.

**Comment by xzyfer** [comment]
This is an error in npm. It's cause by `git` not being installed. This related to https://github.com/sass/node-sass/pull/931. 

@am11 @saper it would seem having a git backed dep is show stopper for Windows. We need a solution here ASAP. #931 is failing CI hard. I suggest we revert the pangyp changes until it's fixed upstream.

**Comment by Soularix** [comment]
I followed the steps :
C:\temp1>npm -v
2.7.4

C:\temp1>node -v
v0.12.0

C:\temp1>node -p process.versions
{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }

C:\temp1>node -p process.platform
win32

C:\temp1>node -p process.arch
x64

C:\temp1>npm install node-sass
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/am11/pangyp) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/am11/pangyp) undefined
npm ERR! git clone https://github.com/am11/pangyp undefined
npm ERR! git clone https://github.com/am11/pangyp undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.4
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp1\npm-debug.log

C:\temp1>cd node_modules\node-sass\vendor
The system cannot find the path specified.

**Comment by xzyfer** [comment]
Hi @Soularix, apologies this is a know issue with Windows and will fixed in 3.0.1.

**Comment by Soularix** [comment]
Thank you very much

**Comment by DatasBoobieTrap** [comment]
Can someone answer if there is a workaround that allows this to work currently? Such as installing a previous version of gulp-sass? We are in a situation of needing to get this module functional on a Windows machine ASAP... Any help would be greatly appreciated.

**Comment by am11** [comment]
If you use shell which has git installed (lets say powerhsell prompt from GitHub, that comes with GitHub for Windows: https://windows.github.com/), it will install node-sass v3 on Windows. 

Later this week (=> soon), we will release v3.0.1.

**Comment by Soularix** [comment]
@DatasBoobieTrap I removed the old gulp-sass folder installed the previous version by : "npm install gulp-sass@1.3.3" it worked

**Comment by am11** [comment]
@Soularix, @DatasBoobieTrap, v3.1.0 is released.
