### ISSUE TITLE
Investigate CMake.js for build

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#935]
Came across this the other day as a alternate for the node-gyp/pan-gyp problems.
https://www.npmjs.com/package/cmake-js

I had looked at this for libsass awhile ago in https://github.com/sass/libsass/issues/616 but I've been pretty absent from development for the last while.

**Comment by unbornchikken** [comment]
Hi there,

I'm the author of the mentioned package. Let me know if you need help with this.

**Comment by am11** [comment]
> Let me know if you need help with this.

A PR would be much appreciated! :sunny:  :sunglasses:

**Comment by unbornchikken** [comment]
What's the actual issue are you having at node-sass side? If I PR a CMakeLists.txt, that's gonna be based on what I am seeing in binding.gyp file, not the libsass' makefile. So if you're having issues because gyp is ain't capable to does something that makefile does, then my PR migt not solve this. I simply don't have time to analize and deconstruct libsass source and its makefile, sorry. Converting the gyp file is achievable.

**Comment by saper** [comment]
Well, libsass can be compiled in a `Makefile`-only (poor man's mode) configuration as well as with a full-blown `autoconf`

**Comment by unbornchikken** [comment]
Yeah. I think io.js guys had to be stick with node.exe only. There is no good solution for this, that delay load hack that *.gyp uses is not works with every situation. Unfortuanatelly CMake.js can't help with that. Io.js modules of course builds flawlessly, but they are stick with iojs.exe, not node.js exe, so things like mocha.cmd or npm test will break, like with pangyp.

I hope for node and io.js reunion.

However, makefile to CMakeList.txt is doable. So there can be node-sass that compiles on every os and node compatible platforms, without using anything that have to be precompiled. Does this make you happier than you're today with gyp or doesn't?

**Comment by xzyfer** [comment]
I'm curious as to what the benefit you see here is @nschonni?

Is this just change for the sake of change, or is there a real world gain to be had?

**Comment by unbornchikken** [comment]
Yeah, I'm too. I still don't get what's the actual issue that CMake or CMake.js could solve there.
