### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by klquast** [sass/node-sass#937]
I'm getting the following errors when I try to install (on Windows).

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.
js:1087:5)
npm WARN addRemoteGit  git://github.com/am11/pangyp.git resetting remote C:\User
s\quastk\AppData\Roaming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-7
eb24aaa because of error: { [Error: Command failed: git -c core.longpaths=true c
onfig --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\quastk\AppData\Roaming\npm-cache\_git-rem
otes\_templates --mirror git://github.com/am11/pangyp.git C:\Users\quastk\AppDat
a\Roaming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-7eb24aaa: Clonin
g into bare repository 'C:\Users\quastk\AppData\Roaming\npm-cache\_git-remotes\g
it-github-com-am11-pangyp-git-7eb24aaa'...
npm ERR! git clone --template=C:\Users\quastk\AppData\Roaming\npm-cache\_git-rem
otes\_templates --mirror git://github.com/am11/pangyp.git C:\Users\quastk\AppDat
a\Roaming\npm-cache\_git-remotes\git-github-com-am11-pangyp-git-7eb24aaa: fatal:
 read error: Invalid argument
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\qu
astk\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com
/am11/pangyp.git C:\Users\quastk\AppData\Roaming\npm-cache\_git-remotes\git-gith
ub-com-am11-pangyp-git-7eb24aaa
npm ERR! Cloning into bare repository 'C:\Users\quastk\AppData\Roaming\npm-cache
\_git-remotes\git-github-com-am11-pangyp-git-7eb24aaa'...
npm ERR! fatal: read error: Invalid argument
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\quastk\temp1\npm-debug.log

--------

And here is the npm-debug.log: https://gist.github.com/klquast/ce1c507d96d74c97b7dc

**Comment by saper** [comment]
Can you try applying this patch https://github.com/sass/node-sass/pull/931 ?

**Comment by klquast** [comment]
That worked, thanks!
