### ISSUE TITLE
Custom importer outputting stuff!

### ISSUE THREAD

**Issue by callumacrae** [sass/node-sass#938]
I added a custom importer which currently doesn't do anything:

```javascript
function importer(url, prev, done) {
  return done({ file: url });
}
```

I get an object output for every import:

```
{ file: './styles' }
{ file: 'lmn.tarantula/sass/vender/normalize' }
{ file: './themes/default/styles' }
{ file: 'lmn-monkey/src/scss/styles' }
{ file: '../components/arrow/styles' }
{ file: '../components/button/styles' }
{ file: '../components/collapsible/styles' }
{ file: '../components/divider/styles' }
{ file: '../components/footer/styles' }
{ file: '../components/form-counter/styles' }
{ file: 'lmn.tarantula/sass/vender/normalize' }
{ file: '../components/form-label-bubble/styles' }
{ file: './themes/default/styles' }
```

Any ideas what could be causing this? Is it a bug?

**Comment by saper** [comment]
well, it returns the url... it is not "nothing". Does the above output come from the console? Which version are you using, how did you install it?

**Comment by am11** [comment]
@callumacrae, that was a side effect of the hack we were using in v2.x, to make importer not hang. It no longer exists in v3x.

**Comment by callumacrae** [comment]
Yep, it's fixed in 3.x! Cheers, and sorry for the useless issue—I didn't know I was running an out of date version!

@saper It is a passthrough function, so in theory it doesn't change anything and so doesn't do anything. If it didn't call the `done` callback, it would break my code and would therefore do something.
