### ISSUE TITLE
Source map has broken in 3.x?

### ISSUE THREAD

**Issue by callumacrae** [sass/node-sass#947]
I've just updated gulp-sass to 2.x (which updates node-sass to 3.x), and my source map has completely changed:

```diff
-{"version":3,"sources":["test.scss"],"names":[],"mappings":"AAGK,UAHG,MAAA","file":"test.css","sourcesContent":["$color: blue;\n\nbody {\n  .div {\n    color: $color;\n  }\n}\n"],"sourceRoot":"/source/"}
+{"version":3,"sources":["test.css"],"names":[],"mappings":"AAAA,UACE,MAAA","file":"test.css","sourcesContent":["body .div {\\n  color: blue; }\\n"],"sourceRoot":"/source/"}
```

I don't think this is an issue with gulp-sass, but I'll cc @Snugug who updated gulp-sass anyway.

Any ideas?

**Comment by mgreter** [comment]
You're content has changed too, as we can see by looking at `sourcesContent`!?!?

**Comment by callumacrae** [comment]
Yep. That's the output!

Literally the only change I made was updating gulp-sass, input and environment are the same.

**Comment by mgreter** [comment]
Yep, and of course the output position is part of the source-map, therefore the change!
You may want to inspect the result further here: http://murzwin.com/base64vlq.html

**Comment by xzyfer** [comment]
@mgreter I think what @callumacrae is getting at is that he has not changed the source content. Instead now the source content is showing the compiled css not the source Sass. This sounds like a bug.

**Comment by xzyfer** [comment]
@callumacrae can you test whether this bug happens when using node-sass directly so we can determine if it's a Libsass, node-sass or gulp-sass issue.

**Comment by callumacrae** [comment]
```js
var sass = require('gulp-sass/node_modules/node-sass');

sass.render({
  file: 'test/fixtures/sass/test.scss',
  outFile: 'test.css',
  sourceMap: true
}, function (err, res) {
  if (err) {
    throw err;
  }

  console.log(res.css.toString());
  console.log(res.map.toString());
});
```

output:

```
body .div {
  color: blue; }

/*# sourceMappingURL=test.css.map */
{
	"version": 3,
	"file": "test.css",
	"sources": [
		"test/fixtures/sass/test.scss"
	],
	"sourcesContent": [],
	"mappings": "AAGE,IAAI,CAAC,IAAI,CAAJ;EACH,KAAK,EAJD,IAAI,GAGJ",
	"names": []
}
```

Seems to be a bug in gulp-sass, then. I'll open an issue over there.

**Comment by xzyfer** [comment]
@callumacrae I'm confused. The mappings appear to be different again. I don't expect gulp-sass is altering the `mappings`. It would appear that you are proving output from multiple versions of node-sass.

Also I don't believe `sourceContent` should be empty.

**Comment by callumacrae** [comment]
When it was ran through gulp, it was ran through other stuff like autoprefixer and a minifier. gulp-sass is the only thing that changed between the two maps in the first post, so it couldn't have been anything else that broke it.

**Comment by callumacrae** [comment]
As in the issue on gulp-sass, it's an issue over there; I'll close this one.

https://github.com/dlmanning/gulp-sass/issues/269
