### ISSUE TITLE
npm aware `includePaths`

### ISSUE THREAD

**Issue by lennym** [sass/node-sass#949]
Is there a simple way to set `includePaths` to be the npm paths from `module.paths` from the command line?

At the moment I want to import files from a dependency, so have to write a script to call node-sass with the `includePaths` option set to `module.paths`, but ideally I would want to do this in a one line CLI call.

Possibly I could add a boolean flag of `--include-node-modules` or similar to automatically do this if it's not already possible?

**Comment by xzyfer** [comment]
@lennym is there a use case that `-I node_modules` doesn't cut it for?

**Comment by lennym** [comment]
In our case we have a shared module which depends on https://github.com/alphagov/govuk_frontend_toolkit and imports some sass file from there. 

We were doing `-I node_modules` for a while, but then it broke unexpectedly because an upstream project had added this as a dependency so govuk_frontend_toolkit was no longer being installed into ./node_modules.

If this is an extreme corner case then fine, but it feels like for a node-specific implementation of sass, it might be good to have some option to have `includePaths` work in a similar way to `require`.

**Comment by xzyfer** [comment]
>it broke unexpectedly because an upstream project had added this as a dependency

I'm not entirely sure what happened if. Since installing global modules is an anti-pattern I don't understand how `modules.paths` is solving a problem `-I node_modules` doesn't.

>it might be good to have some option to have `includePaths` work in a similar way to `require`.

I'm not sure there is benefit in this. I'm happy to be proven wrong. My main concern is that this is a big break away from the `sass` cli. Doing so would need to prove to be a large benefit to the community.

This issue will also be negated by the changes coming in npm@3 which will have much better support for web modules like bower.

**Comment by lennym** [comment]
It's not a question of global module installs, just that npm doesn't install a module in `./node_modules` if a compatible version exists higher in the dependency tree.

If I have an tree that looks like:

```
├─┬ module-a
│  └─ module-b
└─ module-b
```

then module-b will not be installed in `module-a/node_modules`, so any attempt to use `-I node_modules` will fail because module-b is actually installed at `module-a/../../node_modules`

If I want compilation within module-a to work reliably then I need to not be sensitive to the install location of my dependencies, because there is no guarantee at all that they will exist in the local node_modules directory.

**Comment by xzyfer** [comment]
[Eyeglass](eyeglass.rocks) is now the recommended solution for this.

**Comment by lennym** [comment]
Thanks, I ended up writing [npm-sass](https://www.npmjs.com/package/npm-sass) and others (@mikemaccana) have also written [their own similar modules](https://www.npmjs.com/package/sass-npm), but I'll take a look at eyeglass too.

FYI @xzyfer - the link in your comment above is broken

**Comment by xzyfer** [comment]
Link fixed. Thanks.
