### ISSUE TITLE
Segmentation fault on bootstrap

### ISSUE THREAD

**Issue by rockerzz** [sass/node-sass#950]
This block occurs segmentation fault on Ubuntu 15.04. If I comment on it - all is OK.

https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_utilities.scss#L36

nodejs v0.12.2
gulp-sass@2.0.0
node-sass@3.0.0

gdb out:

#32718 0x00007ffff60af849 in Sass::Eval::interpolation(Sass::Expression*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32719 0x00007ffff60af849 in Sass::Eval::interpolation(Sass::Expression*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32720 0x00007ffff60af849 in Sass::Eval::interpolation(Sass::Expression*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32721 0x00007ffff60afd49 in Sass::Eval::operator()(Sass::String_Schema*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32722 0x00007ffff60a5fe5 in Sass::Eval::operator()(Sass::List*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32723 0x00007ffff60b48e2 in Sass::Expand::operator()(Sass::Declaration*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32724 0x00007ffff60b34e4 in Sass::Expand::append_block(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32725 0x00007ffff60ba154 in Sass::Expand::operator()(Sass::Mixin_Call*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32726 0x00007ffff60b34e4 in Sass::Expand::append_block(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32727 0x00007ffff60ba154 in Sass::Expand::operator()(Sass::Mixin_Call*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32728 0x00007ffff60b34e4 in Sass::Expand::append_block(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32729 0x00007ffff60b4fcb in Sass::Expand::operator()(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32730 0x00007ffff60bc6cb in Sass::Expand::operator()(Sass::Ruleset*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32731 0x00007ffff60b34e4 in Sass::Expand::append_block(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32732 0x00007ffff60b754a in Sass::Expand::operator()(Sass::Import_Stub*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32733 0x00007ffff60b34e4 in Sass::Expand::append_block(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32734 0x00007ffff60b754a in Sass::Expand::operator()(Sass::Import_Stub*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32735 0x00007ffff60b34e4 in Sass::Expand::append_block(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32736 0x00007ffff60b4fcb in Sass::Expand::operator()(Sass::Block*) () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32737 0x00007ffff6089962 in Sass::Context::parse_file() () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32738 0x00007ffff6089dfb in Sass::Context::parse_string() () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32739 0x00007ffff607328d in sass_compiler_parse () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32740 0x00007ffff60782e6 in sass_compile_data_context () from <skipped>/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
#32741 0x0000000000e0f0d9 in worker (arg=<optimized out>) at ../deps/uv/src/threadpool.c:91
#32742 0x0000000000e1c991 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:49
#32743 0x00007ffff6f896aa in start_thread (arg=0x7ffff57d8700) at pthread_create.c:333
#32744 0x00007ffff6cbeeed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by xzyfer** [comment]
This is a known issue, fixed in Libsass 3.2.3, and will be in node-sass@3.0.1 later this week.

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/node-sass/issues/946

**Comment by xzyfer** [comment]
Fixed in 3.1.0.
