### ISSUE TITLE
Cannot download binaries (proxy settings)

### ISSUE THREAD

**Issue by fed135** [sass/node-sass#955]
Hello,

I'm trying to install node-sass via npm and it crashes during the install : 

    Cannot download "https://github.com/sass/node-sass/releases/download/v3.1.0/linux-x64-43_binding.node": connect ECONNREFUSED 192.30.252.129:443

I have the following ENV variables set:

    http_proxy
    https_proxy
    HTTP_PROXY
    HTTPS_PROXY

I have the following git configs:

    git config --global http.proxy http://my.proxy.com
    git config --global http.sslverify false
    git config --global url.https://.insteadOf git://

(These are sort of necessary since our company's network config blocks requests on port 22)

These seem to be ignored and cause the error seen above.

As mentionned in bug #775 , there is supposed to be an ENV variable to override the location that the install looks for to get the binaries from. I tried both ways:

    export SASS_BINARY_PATH=/var/www/html/binaries/v3.1.0

and

    export SASS_BINARY_SITE=http://localhost/binaries

but still I get the exact same message during my npm install :

    Cannot download "https://github.com/sass/node-sass/releases/download/v3.1.0/linux-x64-43_binding.node": connect ECONNREFUSED 192.30.252.129:443

1- Shouldn't the request to download the binaries take in account the ENV settings ?
2- The ENV variables to specify binary fetch settings seem broken

I'm on ubuntu 15, iojs v1.6.3, npm v2.7.6

Thank you

**Comment by saper** [comment]
Can you post a full log including your `npm install` command line? Something obviously cleans up your environment a bit....

**Comment by fed135** [comment]
My command is 

    sudo npm install node-sass

We are using a private npm repo (Sinopia) so that we don't have to worry about the setting a proxy for npm. 

If I understand correctly, npm gets the node-sass package through our private repo. Once it is downloaded on my machine, the install script starts, using my machine's ENV settings. So it should be fine.

Here's the log file: http://paste.ubuntu.com/11119587/

**Comment by luqin** [comment]
I get the same error when I install node-sass3.0. The error is ETIMEOUT.

**Comment by saper** [comment]
@fed135 Can you please follow our [troubleshooting guide]? https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md Your log indicates you have an `--unsafe-perm` npm problem.

**Comment by fed135** [comment]
Tried with --unsafe-perm. Same error. 
And nothing in troubleshooting about not being able to download binaries or network issues.

**Comment by saper** [comment]
Can you post you full log again when running with `unsafe-perm` enabled?

**Comment by fed135** [comment]
http://paste.ubuntu.com/11134885/

**Comment by saper** [comment]
Some how I don't see the real error message (you have given above) in the output - did you capture both standard output and standard error to the file?

Another question: can you post output of the `env` command after you do `npm install` somewhere?

**Comment by fed135** [comment]
Weird indeed that the error is not logged in the NPM debug file. Here's my console output:

http://paste.ubuntu.com/11135541/

As for my env: 

http://paste.ubuntu.com/11135632/

**Comment by saper** [comment]
On Thu, 14 May 2015, Frederic Charette wrote:

> Weird indeed that the error is not logged in the NPM debug file. Here's my console output:
> 
> http://paste.ubuntu.com/11135541/
> 
> As for my env: 
> 
> http://paste.ubuntu.com/11135632/

Thanks.

I just setup a tinyproxy on port 9999 and a little HTTP server on port 9998
and tried:

>  env HTTPS_PROXY=http://localhost:9999 SASS_BINARY_SITE=http://myserver:9998/local/node-sass-bin npm install node-sass@3.1.0

All transfers go via proxy to myserver, and when there is an error (file not found
for example) I get the http://myserver:9998/... URL in the error message.

You have mentioned earlier you are using "sudo npm install". I think your
local exported variables do not get transferred to the root shell behind
sudo. 

Can you post the output of:

> sudo env

you can try the following options:

1) Run "npm install" as the normal user *without* sudo and see if it works better.

2) Start root shell (sudo su -), set SASS_BINARY_SITE and/or proxies again *in that shell*
and try "npm install" (without sudo) there.

**Comment by fed135** [comment]
You found it! My http_proxy variables were not present in my sudo environment.
Thanks for the support!

**Comment by giovannyc28** [comment]
I've got the same problem and  I was  solve download from https://github.com/sass/node-sass/releases the linux-x64-57_binding.node and copy file to /home/user/.npm/node-sass/4.5.0 directory
