### ISSUE TITLE
SourceMap still doesn't work when outputStyle is compressed

### ISSUE THREAD

**Issue by dawidk92** [sass/node-sass#957]

**Comment by xzyfer** [comment]
Define doesn't work

**Comment by dawidk92** [comment]
It refers to wrong files and lines. Im using grunt-sass (1.0.0) and it generates sourceMap
```
sass: {
	options: {
		includePaths: [
			'bower_components/foundation/scss'
		],
		outputStyle: 'compact',
		sourceMap: true
	},
	dist: {
		files: { '<%= dir.css %>/main.css': '<%= dir.sass %>/app.scss' }
	}
}
```
Im also including Foundation (5.5.2) but it doesnt causes that bug (I checked it)

**Comment by xzyfer** [comment]
Have you tried using sassc or node-sass directly. We don't know anything about grunt.

**Comment by dawidk92** [comment]
Nope, but i was writing to them and they said that node-sass causes that problem. Grunt-sass is just workaround

**Comment by xzyfer** [comment]
This is very unhelpful. Try using node-sass directly and see if the problem persists. Otherwise this a grunt-sass issue.

Please never open a blank issue like this. It is very unhelpful, and wastes both our time.

**Comment by danielknell** [comment]
I have been experiencing similar issues with node-sass  and --output-style compressed i initially thought it was a bug in autoprefixer and filed https://github.com/postcss/autoprefixer/issues/453 which has more context including links to gists containing example source maps.

**Comment by DJDavid98** [comment]
I can verify that this is an issue with `node-sass`as the source map files it generates are sometimes broken when using the compressed style. Here's a gist with the SASS, the compiled CSS (`*.min`) and the map (`*.min.map`) files that reproduce the issue: https://gist.github.com/DJDavid98/eb52b3080e14ed06a02a

Visualized here: [working][1] vs [broken][2]

 [1]: http://sokra.github.io/source-map-visualization/#base64,I3NpZGViYXIgI3F1b3Rle3RleHQtYWxpZ246cmlnaHR9DQovKiMgc291cmNlTWFwcGluZ1VSTD10aGVtZS5taW4uY3NzLm1hcCAqLw0K,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQ0MsZUFBTyxDQUNOLFVBQVUsQ0FBRSxLQUFLIiwic291cmNlcyI6WyJ0aGVtZS5zY3NzIl0sIm5hbWVzIjpbXSwiZmlsZSI6InRoZW1lLm1pbi5jc3MifQ==,I3NpZGViYXIgew0KCSNxdW90ZSB7DQoJCXRleHQtYWxpZ246IHJpZ2h0Ow0KDQoJCS8vJjpiZWZvcmUgeyBjb250ZW50OiAnXDIwMUMnIH0NCgl9DQp9
 [2]: http://sokra.github.io/source-map-visualization/#base64,I3NpZGViYXIgI3F1b3Rle3RleHQtYWxpZ246cmlnaHR9I3NpZGViYXIgI3F1b3RlOmJlZm9yZXtjb250ZW50OiLigJwifQ0KLyojIHNvdXJjZU1hcHBpbmdVUkw9dGhlbWUubWluLmNzcy5tYXAgKi8NCg==,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkNBQ0MsY0FBTyxFQUNOLFNBQVUsRUFBRSxJQUFLLEVBRWpCLHFCQUFTLEVBQUUsTUFBTyxFQUFFLEVBQU8iLCJzb3VyY2VzIjpbInRoZW1lLnNjc3MiXSwibmFtZXMiOltdLCJmaWxlIjoidGhlbWUubWluLmNzcyJ9,I3NpZGViYXIgew0KCSNxdW90ZSB7DQoJCXRleHQtYWxpZ246IHJpZ2h0Ow0KDQoJCSY6YmVmb3JlIHsgY29udGVudDogJ1wyMDFDJyB9DQoJfQ0KfQ==

**Comment by DJDavid98** [comment]
I can verify that this is an issue with `node-sass`as the source map files it generates are sometimes broken when using the compressed style, more specifically, when nesting 2 `#id` selectors anywhere in a SASS file. Here's the smallest amount of SASS code, the compiled CSS, and the source map that reproduces the issue: ([visualization here][1])

	#sidebar {
		#quote {
			display: block;
		}
	}



    #sidebar #quote{display:block}
    /*# sourceMappingURL=theme.min.css.map */



	{
		"version": 3,
		"file": "theme.min.css",
		"sources": [
			"theme.scss"
		],
		"mappings": "AACC,QAAQ,CAAC,MAAM,AAAR,CACN,OAAO,CAAE,KAAM,CADR",
		"names": []
	}

 [1]: http://sokra.github.io/source-map-visualization/#base64,I3NpZGViYXIgI3F1b3Rle2Rpc3BsYXk6YmxvY2t9CgovKiMgc291cmNlTWFwcGluZ1VSTD10aGVtZS5taW4uY3NzLm1hcCAqLw==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGhlbWUubWluLmNzcyIsInNvdXJjZXMiOlsidGhlbWUuc2NzcyJdLCJtYXBwaW5ncyI6IkFBQ0MsUUFBUSxDQUFDLE1BQU0sQUFBUixDQUNOLE9BQU8sQ0FBRSxLQUFNLENBRFIiLCJuYW1lcyI6W119,I3NpZGViYXIgew0KCSNxdW90ZSB7DQoJCWRpc3BsYXk6IGJsb2NrOw0KCX0NCn0NCg==

**Comment by xzyfer** [comment]
Thanks @DJDavid98 this is perfect for helping us dig into these issues

**Comment by glen-84** [comment]
@xzyfer Is this a problem with libsass? If so, is there an issue that I can follow?

**Comment by saper** [comment]
With node-sass@3.4.0.beta we produce:

````
        "mappings": "AAAA,QAAQ,CACJ,MAAM,AAAC,CACH,OAAO,CAAE,KAAM,CAClB",
````

**Comment by glen-84** [comment]
Still doesn't work with `node-sass@3.4.0-beta1` via `gulp-sass@2.1.0-beta`.

**Comment by saper** [comment]
@glen-84 can you be more specific? Can you post your input and output like @DJDavid98 did?

**Comment by glen-84** [comment]
Unfortunately, I'm including the whole of Bootstrap 4 (v4.0.0-alpha), like this:

```scss
$brand-primary: #ed383d;

@import "../../../node_modules/bootstrap/scss/bootstrap.scss";
```

... so it's not really narrowed down. :disappointed:

**Comment by DJDavid98** [comment]
The way I came to the conclusion in my comment was that I started removing parts of a large CSS file until it started working properly, then progressively added back blocks until the issue came back again.

**Comment by jontro** [comment]
I can confirm this is broken when using foundationpress

**Comment by rvock** [comment]
As it looks for me, the source maps are wrong when using content-property without `@charset "utf-8"` within the same file:
```scss
html {
	content: ' – ';
}

body {
	z-index: 1;
}
```
This scss resulted in an incorrect Sourcemap. When inspecting body in chrome, it was pointing to line 2 of the file (instead of line 4).

If I add `@charset`, the sourcemap is correct:
```scss
@charset "utf-8";

html {
	content: ' – ';
}

body {
	z-index: 1;
}
```

But this does not solve the problem, when the content-property is within an included file:
```scss
// main.scss
@charset "utf-8";
@import "sub";

// _sub.scss
@charset "utf-8";

html {
	content: ' – ';
}

body {
	z-index: 1;
}
```

**Comment by marcofugaro** [comment]
Yup, still broken also for me.

**Comment by pablo-pacheco** [comment]
Same problem here

**Comment by mindplay-dk** [comment]
Doesn't work for me either.

Compact output works:

```
$ ./node_modules/.bin/node-sass --output-style compact --output ./layout ./layout-sass/style.scss
Rendering Complete, saving .css file...
Wrote CSS to C:\workspace\chill\site\layout\style.css
```

Combined with source-maps, it fails:

```
$ ./node_modules/.bin/node-sass --output-style compact --source-map --output ./layout ./layout-sass/style.scss
C:\workspace\chill\site\node_modules\node-sass\bin\node-sass:208
    var sourceMapIsDirectory = options.sourceMapOriginal.indexOf('.map', options.sourceMapOriginal.length - 4) === -1 && isDirectory(options.sourceMapOriginal);
                                                         ^

TypeError: options.sourceMapOriginal.indexOf is not a function
    at getOptions (C:\workspace\chill\site\node_modules\node-sass\bin\node-sass:208:58)
    at Object.<anonymous> (C:\workspace\chill\site\node_modules\node-sass\bin\node-sass:384:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by Ariel-Rodriguez** [comment]
I had a similar issue as @rvock and @SeinopSys have described already. Fortunately i found a solution for my case.

I have next classes:

```scss
$arrowchunky: "\1f52e";
// ... more icons
.icon {
	&.icon-arrowchunky:before {
		content: $arrowchunky;
	}
        //.... a hundred more icons
}
```
Then somehow the sourcemap refers to wrong files and lines.

I solve this by unquoting the content. (i don't specify UTF-8 at anywhere)

Here this works for me, the sourcemap is healthy:
```scss
$arrowchunky: \1f52e; // <-- Unquote the content.
// ... more icons
.icon {
	&.icon-arrowchunky:before {
		content: $arrowchunky;
	}
        //.... a hundred more icons
}
```

**Comment by sant123** [comment]
https://github.com/sass/node-sass/issues/1026

**Comment by am11** [comment]
☑️  `--source-map true` works
☑️ `--source-map path/to/my.map` works
☑️ `--source-map path/to/some/directory` works
❎  `--source-map` without any arg is invalid since v3 (breaking change was noted in v3 release notes)

Although readme was also updated when this breaking change was introduced; `--help` should state it as well.

**Comment by sant123** [comment]
Thank you @am11! It worked perfectly.

**Comment by mindplay-dk** [comment]
Indeed `--source-map` fails, but `--source-map true` works.

So, if this is not in fact just a bug in `node-sass`, it could work around this issue by making `--source-map` default to `true` internally.

Or not?

**Comment by mindplay-dk** [comment]
This is still broken.

Any chance we could have it default to `true` as mentioned above?

Every person I know gets tripped up by this - I have to google it myself and find this issue every time ;-)

**Comment by heaversm** [comment]
Doesn't work for me either:

```
"dev:sass": "node-sass ./path/static/css/main.scss ./path/static/css/main.css --output-style expanded –-source-map true",
```

from a call to:

```
"dev": "parallelshell 'yarn run dev:watch-css' 'yarn run dev:watch-js'",
   "dev:css": "yarn lint-sass && yarn dev:sass",
```

**Comment by sod** [comment]
I guess we soon move to the sass rewrite in dart

https://github.com/sass/dart-sass

Don't expect to happen much maintenance on this C fork in the future.

**Comment by saper** [comment]
I can't reproduce this issue anymore with 4.12.0, please reopen with the source and output files that demonstrate what is still wrong with the source map.
