### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v3.1.0/linux-x64-43_binding.node": connect ETIMEOUT

### ISSUE THREAD

**Issue by luqin** [sass/node-sass#958]
Error on linux and windows.

**Comment by xzyfer** [comment]
Sorry @luqin there is nothing we can do about this. I can confirm that file exists. This must be a networking issue on your end.

**Comment by luqin** [comment]
But I install packages from my local private npm registry, I hope install node-sass withoue use network. Can you put bindings in another npm package ?

**Comment by saper** [comment]
@Luqin you can always download binary packages yourself and create local mirror using `SASS_BINARY_SITE` environment variables.
