### ISSUE TITLE
@keyframes failing with `invalid selector after  `

### ISSUE THREAD

**Issue by davidlanger** [sass/node-sass#960]
Running the following scss with node-sass@3.0.0 returns the css as expected.

```sass
@mixin keyframes($animation-name) {
  @keyframes $animation-name {
    @content;
  }
}

@include keyframes(bounce) {
  0%, 20%, 50%, 80%, 100% {transform: translateY(0);}
  40% {transform: translateY(-30px);}
  60% {transform: translateY(-15px);}
}
```
 
When switching to node-sass@3.1.1 it fails with the following message, complaining about `@keyframes $animation-name`:
 
```sass
{
  "message": "invalid selector after  ",
  "column": 13,
  "line": 2,
  "file": "/Users/davidlanger/repos/temp-libsass/test.scss",
  "status": 1
}
```

**Comment by saper** [comment]
Checked with `sassc`, seems to be a libsass issue

**Comment by davidlanger** [comment]
Ok, I'll post the issue there. (And install `sassc` so I'll post in the right repo next time)

**Comment by saper** [comment]
According to my tests, sass/libsass@974ae42b87a3714fff5ed38132272486747f524c broke this. This was introduced in https://github.com/sass/libsass/pull/1177

**Comment by xzyfer** [comment]
@davidlanger I have fix in Libsass. Created a new issue there to track this https://github.com/sass/libsass/issues/1214.
