### ISSUE TITLE
How can I tell which version of Sass is running with node-sass?

### ISSUE THREAD

**Issue by markweston** [sass/node-sass#961]
Hi,

This might sound like an odd question but I'm using gulp-sass, a wrapper for node-sass which in turn uses libsass.

I'm confused as to how I know which version of Sass I'm running. Does it simply correspond to the version of node-sass? I found this more self explanatory when using Ruby gems for sass. 

Thanks.

**Comment by am11** [comment]
Hi,

node-sass is a wrapper around libsass which is an alternate / substitute implementation of Sass language compiler written in C/C++, as opposed to the primary implementation in Ruby language. 

Going by https://github.com/sass/libsass/issues/629, we can say LibSass' latest version (v3.2.4) fully conforms with Sass language v3.3 and majority of v3.4 features. In other words, the lines are blur from that perspective. Besides, (IMO) the language version is an implementation detail. However, from node-sass' consumer perspective, the more imperative and distinguishing detail is the LibSass version itself, which node sass emits as follow.

From CLI:

```bash
node-sass -v
# or, depending on cwd and env PATH status, you may need:
#
# node_modules/.bin/node-sass -v

# OR even

node -e "console.log(require('node-sass').info)"

# OR -p (processes && evaluates)

node -p "console.log(require('node-sass').info)"
```

From code usage:

```javascript
var sass = require('node-sass');
console.log(sass.info);
```

With latest node-sass, the output is:

```powershell
node-sass       3.1.1   (Wrapper)       [JavaScript]
libsass         3.2.4   (Sass Compiler) [C/C++]
```

Let us know if and how we can further improve this experience.

**Comment by xzyfer** [comment]
@markweston also see my response https://github.com/sass/node-sass/issues/962#issuecomment-102568127

**Comment by ggamir** [comment]
Another way to check the version of an indirect-dependency (node-sass) used in your direct dependency (gulp-sass) is to go into the `node_modules` folder and find the `node-sass` folder and check the `package.json` to see what version of libsass it depends on.

```
cd node_modules/gulp-sass/node_modules/node-sass
cat package.json | grep sass
```

**Comment by MusawwerRasheed** [comment]
npm code-sass -v

**Comment by fazil-imraan** [comment]
> npm node-sass -v works well

It only shows the npm version not the node-sass version i checked

**Comment by nerdess** [comment]
I found this command: 

`node -e 'console.log(require("node-sass").info)'`
