### ISSUE TITLE
Any ETA on newer features?

### ISSUE THREAD

**Issue by drone1** [sass/node-sass#962]
Sorry if this is a noob question here. I'd like to use a feature which came out with SASS 3.1.6 (http://sass-lang.com/documentation/file.SASS_CHANGELOG.html) -- the 'trace_selectors' option would be incredibly useful for my current project.

It looks like the current version is of node-sass is 3.1.1. Is there a newer (less stable) version I can get my hands on, or do I just need to wait? Any ETA on getting things up to date?

**Comment by xzyfer** [comment]
There is no relation between the Node Sass version numbers and Ruby Sass version numbers. Node Sass uses Libsass, whose version numbers are also unrelated.

If you wish to check if a feature is implemented you test against the "Libsass" option in http://sassmeister.com.

If want to request a command line or API option be added, please open an issue here and we'll discuss it.

**Comment by drone1** [comment]
That was what I figured initially but then second guessed myself.

So I'm just trying to use the trace_selectors option. I don't see a way to
set that option on sassmeister.com. I checked in the control panel and
didn't see a way to pass that along, or UI around that specific option.
