### ISSUE TITLE
Is there a way to resolve a dependency from a config file e.g. bower.json

### ISSUE THREAD

**Issue by rbhalla** [sass/node-sass#966]
My title might be slightly confusing so I will give an example. Right now I am installing bourbon using bower. I have set `bower_components` to be in my included paths, so then I can do `@import 'bourbon'`. The problem is the main file for bourbon is nested quite deeply (`/app/assets/stylesheets/bourbon`). This means when I import I have quite a long import string each time.

I frequently use webpack too, and they have quite a clean approach to this in the form of a resolver plugin. I'm not sure how well this translates over to the node-sass paradigm so I thought I'd ask. With webpack I can say `new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])` and this automatically reads the bower.json file of an imported folder and resolves my import statement to the correct file.

Is there an equivalent in node-sass?

**Comment by xzyfer** [comment]
Sounds like you want `loadPaths`

**Comment by rbhalla** [comment]
I can't seem to find anything about that option in the documentation. Do you mind pointing me to the right place? Or just explaining how it works from your knowledge?

**Comment by xzyfer** [comment]
Apologies it's `includePaths` in node-sass, which maps to `loadPaths` in Ruby Sass - https://github.com/sass/node-sass#includepaths

**Comment by rbhalla** [comment]
Hi @xzyfer 

As I mentioned in the first post, I already have setup my include paths correctly. The problem is that the necessary files aren't necessarily in the root of the folder. The actual location is stored in files such as bower.json and package.json, but there is no way to read that information and have it interpreted correctly.

**Comment by jameslnewell** [comment]
I've done something similar but for npm modules. You could try writing a plugin for [sass-composer](https://www.npmjs.com/package/sass-composer) or adapting the src to suit your use-case.

**Comment by xzyfer** [comment]
You will need to write a custom importer.
