### ISSUE TITLE
Node-sass expecting libsass binding at wrong location (linux-x64-11 vs linux-x64-14)

### ISSUE THREAD

**Issue by nicoburns** [sass/node-sass#969]
When trying to run node-sass I get the following error:

```
[path redacted]/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in [path redacted]/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath ([path redacted]/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> ([path redacted]/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] ([path redacted]/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:133:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([path redacted]/node_modules/node-sass-middleware/middleware.js:3:12)
```

However, by rerunning `npm install`, I get the following output:

```
> node-sass@3.1.1 install [path redacted]/node_modules/node-sass
> node scripts/install.js


> node-sass@3.1.1 postinstall [path redacted]/node_modules/node-sass
> node scripts/build.js

` [path redacted]/node_modules/node-sass/vendor/linux-x64-11/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
```

Note that the 4th line from the error, and 3rd last line from NPM contain almost exactly the same path, except for the former contains `linux-x64-14`, while the latter contains `linux-x64-11`. I'm guessing these refer to different C++ versions, but for some reason my system seems to be installing the '11' version even though `node-sass` is expecting the '14' version.

System is CentOS 6 if that helps. The exact same code works fine on my mac.

**Comment by nicoburns** [comment]
Upon further investigation, this issue is consistently reproducible on my system with node v0.12.0, but does not occur with node v0.10.8. Modules installed with NPM v2.5.1. Although I'm not sure how relevant that will be seeing as the same installed module works under node 0.10.

**Comment by nicoburns** [comment]
Ah, it turns out this was caused by inadvertently running `npm install` using node 0.10, followed by trying to run the app using node 0.12. Fixed by ensuring that npm runs using 0.12.

**Comment by saper** [comment]
you can run "npm install" (or "your-version-of-node -f script/install.js") as many times as you wish and put multiple binary files under `vendor` to cover different node (or io.js) engine versions.

`node-sass` will not automatically download anything when invoked, only during installation.

**Comment by cjbrowne** [comment]
Note for users of the npm package 'n': I got this problem when I started using 'n' on ubuntu 14.04 because the 'n' version of node was installed in /usr/local/bin/node and was preferred by bash, but npm picked up /usr/bin/node which was the ubuntu-installed version of node.  Simply removing the offending binary (you may wish to rename it in case you want to restore it later) fixed the issue for me.

I'm also reminding myself if I come here via google again since I've had this issue three times now in three separate environments and every time causes about an hour of head-scratching.
