### ISSUE TITLE
Can't install the application

### ISSUE THREAD

**Issue by chenxiaochun** [sass/node-sass#972]
![image](https://cloud.githubusercontent.com/assets/1744713/7740215/8594fea6-ffa0-11e4-90cd-6a12c79779bf.png)

My nodejs version is v0.12.3

**Comment by xzyfer** [comment]
```
Error: read ECONNREST
```

Looks like you've got some networking issue. This may happen if you're using a proxy. That version of node-sass is ancient and isn't actively supported. Many of these issues are resolved in 3.1.0.

**Comment by saper** [comment]
The real problem you will see few lines above (off the screen in the screenshot), when npm calls `script/install.js`
