### ISSUE TITLE
Failing in Debian Jessie

### ISSUE THREAD

**Issue by caiquecastro** [sass/node-sass#973]
Hello, I was trying to install the node-sass via npm as a dependency.

I got the following error:

npm ERR! Failed at the node-sass@3.1.2 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by saper** [comment]
@caiquecastro can you follow our https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md guide and report the results?

**Comment by caiquecastro** [comment]
Sorry for the delay! I solved it by updating my npm version.. I was using the default one from debian.. Now I am using nvm!

**Comment by ChristianRich** [comment]
I solved this by installing a later version of Node (8.x).
```
 url -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && \
            sudo apt-get install -y nodejs && \
            sudo npm i -g npm
```
