### ISSUE TITLE
Archeology: How to get source maps in 0.x?

### ISSUE THREAD

**Issue by Munter** [sass/node-sass#974]
I've been reading the docs of node-sass 0.9.6 and below and have tried to follow the README's instructions on how to get source maps.

This is my config

```javascript
var stats = {};

sass.renderSync({
  file: 'foo.scss',
  sourceComments: 'map',
  sourceMap: 'foo.map',
  stats: stats
});
```

When running the above config I get `stats.sourceMap` as undefined.

What am I missing?

**Comment by am11** [comment]
It seems like `outFile: [path: String]` in options is missing, which is mandatory to generate source-maps in trans-compilation.
For some other reason, libsass does not infer the output path from input path (by merely replacing extensions), even when source-map is requested. Also, the philosophy of node-sass is to remain slim wrapper and bring about transparency between libsass and consumer (without injecting/setting options on behalf of consumer).

**Comment by Munter** [comment]
Right, I did miss that option. Only in my example in this issue though. That should teach me to copy/paste my examples instead of retyping :)

Anyway, what I am trying to do is create a node-sass version agnostic compatibility layer for tool integrators. It's supposed to allow them to use the latest node-sass API, but let the consumer decide what version of node-sass they are running, and everything should still "just work".

The only thing I'm missing at the moment are sourcemaps from 0.x in these cases:

 - `sass.[render | renderSync]({ data: '...' })`: No matter what sourcemaps settings I provide there will never be a sourcemap from `render` via data.
 - `sass.renderSync({ file: '...' })`: renderSync seems to not create sourcemaps either.

These are my test cases: https://github.com/Munter/node-sass-evergreen/blob/master/test/test-sourceMap.js

I've added overrides for [`render` with `data`](https://github.com/Munter/node-sass-evergreen/blob/master/test/test-sourceMap.js#L9-L23) and [`renderSync` with `file`](https://github.com/Munter/node-sass-evergreen/blob/master/test/test-sourceMap.js#L564-L576) in order to make my tests pass for now.

Any insights in possibly wrong or missing configuration? Or were these cases simply not covered by sourcemaps in version 0.x?

**Comment by am11** [comment]
The following is producing source-map on Windows with node-sass@0.9:

```javascript
require('node-sass').render({
  file: 'blah.scss',
  outFile: 'blah.css',
  sourceMap: true,
  success: function(css, map){console.log(css, map)}})
// .render() returns the generated code and does not write to file-system


require('node-sass').renderFile({
  file: 'blah.scss',
  outFile: 'blah.css',
  sourceMap: true,
  success: function(cssFilePath, mapFilePath){console.log(cssFilePath, mapFilePath)}})
// .renderFile() writes to file-system and returns path
```
