### ISSUE TITLE
How to pass file encoding through to sass?

### ISSUE THREAD

**Issue by jonsamwell** [sass/node-sass#975]
I'm having encoding issue with the latest release. I've tracked this down to an encoding (http://blog.pixelastic.com/2014/09/06/compass-utf-8-encoding-on-windows/) issue and need to pass the correct encoding through to sass (-E utf-8). Is there anyway I can do this?

**Comment by am11** [comment]
#### intro:
Sass is a language, whereas ruby-sass (written in Ruby) and libsass (written in C++) are two implementations of Sass preprocessor.
node-sass is a JavaScript wrapper for node.js around the latter one: libSass.

#### which means..

The (ruby-sass) article you are referring to is not applicable here.

#### to recapitulate:

node-sass does not write the generated CSS code to file-system. It returns back the `Buffer`, as shown in the [README example](https://github.com/sass/node-sass#examples): `result.css` is of type `Buffer`, which can be converted as
`result.css.toString('utf8')` or if your ultimate goal is to write to file-system, then:

```javascript
fs.writeFile('path/to/file.css', {
  'encoding': 'utf8'
}, result.css);

// or less rhetorically:

fs.writeFile('path/to/file.css', 'utf8', result.css);
```

HTH
