### ISSUE TITLE
feature request: Improve install

### ISSUE THREAD

**Issue by AliMD** [sass/node-sass#976]
Sorry for report my problem here
We have many repo with many developers and want to upgrade to node-sass 3 (from 2)
Install usually take 50+ min and sometime failed on download process (firewall issue and we cant solve it)
Is there anyway to faster install and download?
Catching or global install ?
Thank you in advance

**Comment by AliMD** [comment]
We use `gulp-sass` and it use `node-sass v3.0.0`!

**Comment by erykpiast** [comment]
I have issues with installation too. Log dump:

```
> node-sass@3.1.2 install /home/ubuntu/workspace/cyclejs-examples/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/ubuntu/workspace/cyclejs-examples/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node

> node-sass@3.1.2 postinstall /home/ubuntu/workspace/cyclejs-examples/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /home/ubuntu/workspace/cyclejs-examples/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists. 
 testing binary.
node: symbol lookup error: /home/ubuntu/workspace/cyclejs-examples/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_
npm ERR! node-sass@3.1.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the node-sass@3.1.2 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

**Comment by xzyfer** [comment]
Please follow the troubleshooting guide in the repo and paste the output in
a gist.

**Comment by erykpiast** [comment]
Of course, sorry for that!

**Comment by AliMD** [comment]
I reported the problem
We have download speed issue open github https
And you download package every time per package
Is there anyway to faster install and download?
Catching or global install ?

**Comment by xzyfer** [comment]
@erykpiast in the future try not to edit issues because we don't get notified.

**Comment by xzyfer** [comment]
@erykpiast please follow _all_ of the steps and produce their output - https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx

**Comment by xzyfer** [comment]
@AliMD you have two options.

1) opt out of the download and compile locally. This will probably be slower.
2) cache the downloads in a local proxy and use the `SASS_BINARY_SITE` env to download your local copy.

**Comment by AliMD** [comment]
Could you please more describe about option two
Thank you

**Comment by xzyfer** [comment]
You can set an environment variable that node-sass will use has the url prefix to the binary downloads. This allows you to mirror the binaries in our releases locally.

The default value for this variable is `https://github.com/sass/node-sass/releases/download`

You can override it in two ways.

```
SASS_BINARY_SITE='http://example.com/path/to/releases' npm install
```

Or by setting the following in your `package.json`

```json
  "nodeSassConfig": {
    "binarySite": "https://github.com/sass/node-sass/releases/download"
  },
```
