### ISSUE TITLE
'libsass bindings not found.' When both 32 bit and 64 bit node are installed.

### ISSUE THREAD

**Issue by wjzhou** [sass/node-sass#978]
This is just a note.

The visual studio 2015 RC uses an internal 32-bit node program, while my system node is a 64-bit one.

I install the package though the system 64 bit one. (I prefer the command line)
Then the visual studio node can not find the libsass package because only the 64 bit binding is installed.

The solution:
install the package inside visual studio for this scenario.

I don't know whether this is the correct place to post this. If not please delete.
I waste 2 hours on this. Hope it may help someone.

**Comment by xzyfer** [comment]
The solution is to just npm install in each node context i.e. 32 vs 64bit. We don't clobber the previously installed binary so you can use both environments at once.

**Comment by xzyfer** [comment]
Thanks for the note, I expect this will help someone that searches for this in the future.

**Comment by eddiegroves** [comment]
For folks wondering, the version of Node that Visual Studio includes is located at `VisualStudio\Common7\IDE\Extensions\Microsoft\Web Tools\External\node`

I had this problem too and fixed it by replacing their version of node with my own installed exe. I wonder what their plans will be for updating the embedded version of node in the future.

**Comment by steviebob** [comment]
For anyone else having this issue, I found this post helpful:
http://blog.boro2g.co.uk/grunt-and-gulp-tasks-in-visual-studio-2015-libsass-error/

It tells you to make the PATH variable have a higher priority than the visual studio ones.
