### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by erykpiast** [sass/node-sass#980]
`node-sass@3.1.2` installation fails with `symbol lookup` error. After process exits there is no `node-sass` directory in `node_modules`, so I can't provide more information. Only branch 2 works for me, installation of any `3.x.x` version fails.

[NPM log](https://gist.github.com/erykpiast/53790acede46aad5d02a#file-npm-log)
[diagnostic info](https://gist.github.com/erykpiast/53790acede46aad5d02a#file-node-diag)

**Comment by xzyfer** [comment]
node-sass does not support node 0.11. This is a defunct unstable branch. Please update to stable 0.10 or 0.12 releases. You may also need to update you're npm to 2.4+
