### ISSUE TITLE
"Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js"

### ISSUE THREAD

**Issue by abyss-outpost** [sass/node-sass#982]
npm -v
2.7.5
node -v
v0.12.3
Maeolls-MacBook-Pro:node-sass maeoll$ node -p process.versions
{ http_parser: '2.3',
  node: '0.12.3',
  v8: '3.28.71.19',
  uv: '1.5.0',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.2a' }
Maeolls-MacBook-Pro:node-sass maeoll$ node -p process.platform
darwin
Maeolls-MacBook-Pro:node-sass maeoll$ node -p process.arch
x64
node-sass	3.1.2	(Wrapper)	[JavaScript]
libsass  	3.2.4	(Sass Compiler)	[C/C++]

Installation failed at postinstall script 'node scripts/build.js' with the following:
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/maeoll/Dropbox/repositories/fa-boilerplate/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js

**Comment by xzyfer** [comment]
I'm confused, are you installing node-sass 1.2.3 or 3.1.2?

**Comment by abyss-outpost** [comment]
It turns out there was a typo in a package.json file that set the node-sass version to 1.2.3 even though 3.1.2 was desired. Fixed the issue, thanks!
