### ISSUE TITLE
write to stdout when no output flag is set

### ISSUE THREAD

**Issue by NHQ** [sass/node-sass#984]
The Way and The Truth for CLI apps is to write to stdout when no output is set, so that the Unix Superstar may pipe said output to another program, such as a CSS prefixer.

**Comment by saper** [comment]
Doesn't it already?

````
> echo '/* Begin */ .a { .b { overflow: true; } } /* end */' | ~/node_modules/node-sass/bin/node-sass
/* Begin */
.a .b {
  overflow: true; }

/* end */

````

**Comment by xzyfer** [comment]
This was added in 3.0.0. Update node-sass for The Way maximum Superstar Truth in your Unix.

**Comment by saper** [comment]
:like:

**Comment by NHQ** [comment]
I must protest

```js
emitter.emit('error', 'Specify an output directory when using multi-file compilation');
```

https://github.com/sass/node-sass/blob/master/bin/node-sass#L273

**Comment by xzyfer** [comment]
This is because you're asking node-sass to compile an entire directory. This will produce multiple output files. This is not appropriate for piping.

**Comment by xzyfer** [comment]
If you compile a single file we will default to stdout.

**Comment by NHQ** [comment]
@xzyfer why is it not appropriate to spit multiple files?  seems pretty common for text files.  that's why we have concats.

**Comment by xzyfer** [comment]
It's not node-sass job to concat. Node turns a sass file to css file, no more. If you ask it to do that it will produce the output of a css file to stdout. Stdout is not a multipart format.

**Comment by NHQ** [comment]
But node-sass doesn't create multiple files from a directory.  It renders a
single CSS file from a folder of multiple sass files.  I don't see why that
couldn't be spit out.  What does the number of input files have to do with
it?

And you are correct, it is not node-sass's job to concatenate.  We should
do that ourselves, for instance by piping to cat, or some other parser.  It
is easy to work with streams of text from multiple files.

**Comment by chriseppstein** [comment]
If you want to concat, create a single sass file that @imports all the others.

**Comment by xzyfer** [comment]
>But node-sass doesn't create multiple files from a directory

Multifile mode will take all sass files not starting with an `_`, compile them to css, and output them into a directory. This is explained in the documentation

>Pass a directory as the input to compile multiple files. For example: `node-sass sass/ -o css/`. The `--output` flag is required and must be a directory when using multi-file compilation.

****

If this is not what you're seeing then it's a bug in the directory compilation logic that needs to be address.
