### ISSUE TITLE
Rename reference of multi-file to directory

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#985]
The `multi-file` terminology is unintuitive and could be seen as suggesting we support multiple input files. This is how our documentation describes the multi-file mode.

>Pass a directory as the input to compile multiple files. For example: `node-sass sass/ -o css/`. The `--output` flag is required and must be a directory when using multi-file compilation.

IMHO we should stop conflating these two terms and standardise on `directory`. I think this is much clearer.

Thoughts @am11

**Comment by am11** [comment]
This is indeed the directory compile.
The multi-file compile would be where user will provide paths from varied roots (using glob perhaps? brace syntax ..), but we don't support glob for input (yet?) :)

**Comment by xzyfer** [comment]
Cool. Upgrade to feature request.
