### ISSUE TITLE
Supporting 'directory/*' imports

### ISSUE THREAD

**Issue by Rush** [sass/node-sass#986]
I think it's pretty easy to support imports like this, but the only way I see to do this is concatenating the files together, which would break debugging and source maps. Can I say in the importer that I actually imported more than one file?

**Comment by xzyfer** [comment]
This is out of the scope for node-sass. This functionality belongs in a plugin using our custom importer API. There are a couple versions of this available. I suggest you look at https://github.com/sass-eyeglass/eyeglass

**Comment by Rush** [comment]
I wasn't reporting lack of globbing but I was asking on how to implement it. I didn't find any API calls that could accomodate it.

**Comment by xzyfer** [comment]
>Can I say in the importer that I actually imported more than one file

Technically no. You can however return a string containing a list of `@imports` representing the files matching the glob. This has many advantages of just globbing as you can map and filter the results of the glob.

**Comment by Rush** [comment]
That's what I thought but when there is a problem in one of those files wouldn't the error be cryptic? How could the error trace show the right file? Also how would the source map work in this case?

**Comment by xzyfer** [comment]
>when there is a problem in one of those files wouldn't the error be cryptic
>How could the error trace show the right file

I wouldn't think so. The string you return from the custom importer will then get parsed and it's imports resolved. These imported files should be no different from normal imports.

They is to return actual `@import` directives, and not concat the wanted files into a single file.

>Also how would the source map work in this case?

I'm honestly not sure.

**Comment by Rush** [comment]
Thanks @xzyfer. This allowed to write node-sass based sass builder, fully async with glob support in about an hours. I love node. :)
