### ISSUE TITLE
Injecting custom functions

### ISSUE THREAD

**Issue by sabeurthabti** [sass/node-sass#987]
I want to map my images to AWS images for each environment, in ruby sass we can do:

module Sass::Script::Functions
  def pathFor(path)
    isProd = ENV["ENV"] == "production"
    if (isProd)
 
[...]
      Sass::Script::Value::String.new(versionedFile ? remotePath : path.value)
[...]
  end
end

how can I do this in node?

**Comment by Snugug** [comment]
How about the [functions](https://github.com/sass/node-sass#functions--v300---experimental) stuff released in 3.0.0?

[Eyeglass](https://github.com/sass-eyeglass/eyeglass) also makes creating/sharing/etc… custom functions easier, I'd look in to that too.

**Comment by sabeurthabti** [comment]
It's as clear how to use them:

``` js
    var compile = sass.renderSync({
        file: options.file,
        sourceMap: options.sourceMap,
        outFile: options.outFile,
        includePaths: require('node-neat').includePaths,
        outputStyle: options.outputStyle,

        functions: {
            "hello($name: 'World')": function(name, done) {
                done(sass.types.String("Hello, " + name.getValue()));
            }
        }
    });

```
``

I have a custom function `hello`;

in my scss for example i have:
``` css
body::after {

  content: hello('sabeur')

}
```

compiles to : 

``` css

body::after {
  content: hello('sabeur'); }
```

@Snugug any tips?

**Comment by Snugug** [comment]
I highly recommend you try doing this with Eyeglass. There's a great example of how to create an Eyeglass module with custom functions in [Eyeglass Math](https://github.com/sass-eyeglass/eyeglass-math/blob/master/eyeglass-exports.js). Check that out.

Also, make sure you're actually using Node 3.x.

**Comment by sabeurthabti** [comment]
@Snugug thanks, i just don't want another module in my project. thanks for your suggestion.

**Comment by xzyfer** [comment]
I've talked in depth on how you can do this in Sass here
https://github.com/sass/node-sass/issues/965#issuecomment-103384773

**Comment by xzyfer** [comment]
There nothing actionable here for node-sass. Closing.
