### ISSUE TITLE
node-sass on AIX

### ISSUE THREAD

**Issue by lemms007** [sass/node-sass#988]
Is there a way to support node-sass on AIX Platform? I'm trying to install node-sass but it cannot find the binding.node for aix.

Thanks

**Comment by xzyfer** [comment]
I will admit ignorances in never heard of AIX. However the install process
will attempt to build a compatible binary if the target system has GCC.

**Comment by saper** [comment]
You can try to vomited the binding yourself, gcc should work - would be interesting to see if node-gyp can set xlC options as well.

Try to use the same compiler for node and binary node modules and you might need to point node-gyp to the compiled node code.

**Comment by xzyfer** [comment]
Unless there a community advocate for AIX willing to generate binaries for release, or provide an automated solution we cannot not actively support it.

**Comment by xzyfer** [comment]
Closing due to lack of interest.

**Comment by phpdave** [comment]
FYI this appears to be the main ticket for this issue https://github.com/sass/node-sass/issues/1802
