### ISSUE TITLE
TypeError: Object #<Object> has no method 'tmpDir'

### ISSUE THREAD

**Issue by nuthinking** [sass/node-sass#989]
Trying to install the module on the server at Webfaction (node -v 12.0) and I get this error:

$ ./bin/npm install node-sass
npm WARN package.json website@1.0.0 No description
npm WARN package.json website@1.0.0 No repository field.
npm WARN package.json website@1.0.0 No README data
\
> node-sass@3.1.2 install [APP PATH]/node_modules/node-sass
> node scripts/install.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'tmpDir'
    at [APP PATH]/node_modules/node-sass/node_modules/npmconf/node_modules/osenv/osenv.js:49:13
    at Object.tmpdir ([APP PATH]/node_modules/node-sass/node_modules/npmconf/node_modules/osenv/osenv.js:14:15)
    at Object.<anonymous> ([APP PATH]/node_modules/node-sass/node_modules/npmconf/config-defs.js:97:18)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> ([APP PATH]/node_modules/node-sass/node_modules/npmconf/npmconf.js:4:18)
npm ERR! Linux 2.6.18-402.el5PAE
npm ERR! argv "[APP PATH]/bin/node" "[APP PATH]/bin/npm" "install" "node-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.1.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.1.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [APP PATH]/npm-debug.log

Hosting support says it's a problem with the module.

**Comment by xzyfer** [comment]
I am not familiar with your hosting company. Please run though the
troubleshooting guide in the repo and paste the output in a gist.

**Comment by nuthinking** [comment]
the module simply can't be installed:

    $ ./bin/npm -v
    2.5.1
    $ ./bin/node -v
    v0.12.0
    $ ./bin/node -p process.versions
    { http_parser: '2.3',
      node: '0.12.0',
      v8: '3.28.73',
      uv: '1.0.2',
      zlib: '1.2.8',
      modules: '14',
      openssl: '1.0.1l' }
    $ ./bin/node -p process.platform
    linux
    $ ./bin/node -p process.arch
    ia32

The current server runs CentOS 5, I could ask to upgrade it to CentoOS 6 64bit. Any thoughts?

**Comment by saper** [comment]
@nuthinking can you run a simple test?

Fire up `node` and say:

````
> var os=require('os')
> os.tmpDir()
````

What does it say? If it fails - this is the problem with your `node` binary.

**Comment by nuthinking** [comment]
it doesn't fail, it outputs '/tmp'.

**Comment by saper** [comment]
But the same thing fails in your output above. Are there some other `node` engines installed?

**Comment by nuthinking** [comment]
@saper yes, basically how Webfaction works, is that there is a global node bin but that is very old. Web apps have their own node binary in their folder. That's why in my bash above I was using ./bin/node.

**Comment by saper** [comment]
Maybe your old node gets picked up somehow. Not sure I can help any further.

**Comment by nuthinking** [comment]
Yeah, the global node which I might have installed years ago, it's very old. Will try to migrate to a new server.

**Comment by saper** [comment]
Normally the engine shouldn't change in between. Maybe try to output process.version to a file somewhere in the osenv.js to check what is really going on.

**Comment by kevva** [comment]
`os.tmpDir` is deprecated since 0.10 and is now `os.tmpdir`.

**Comment by sindresorhus** [comment]
You could use https://github.com/sindresorhus/os-tmpdir to get consistent tmpfolder path on all Node versions.

**Comment by kevva** [comment]
@sindresorhus, it happens because `npmconf` is using ´osenv` which still uses the deprecated method. That's why I bumped it :P.

**Comment by saper** [comment]
Well but deprecated does not mean removed... `os.tmpDir` is still there

**Comment by xzyfer** [comment]
Tracking this more succinctly in #1018.

**Comment by xzyfer** [comment]
This bug was in [osenv](https://github.com/npm/osenv) and has been patched in `v0.1.2`.
