### ISSUE TITLE
node-sass package.json says libsass version of 3.2.4, node-sass -v reports 3.2.2?

### ISSUE THREAD

**Issue by LukeNZ** [sass/node-sass#991]
I'm using node-sass 3.1.2 (actually as a dependency of gulp-sass, but whatever), and I need version 3.2.4 of libsass for one of my SASS frameworks to compile ([see this bug](https://github.com/olivierbossel/gridle/issues/57)). However, no matter what I do with either gulp-sass or node-sass, uninstall, reinstall, globally or locally, libsass always reports a version of 3.2.2 and does not work.

How can I upgrade my version of libass? Why is this even occuring if the package.json file for node-sass specifies a libsass requirement of 3.2.4?

I've opened a question at SO with more details: http://stackoverflow.com/questions/30681658/how-can-i-upgrade-libsass-with-npm

**Comment by xzyfer** [comment]
Sounds you've either
- inadvertently installed node-sass and gulp-sass with two different versions (this happens alot)
- or you have a dirty cache

gulp-sass will install the latest node-sass (https://github.com/dlmanning/gulp-sass/blob/master/package.json#L25).

Try cleaning your npm cache

```
npm cache clean
rm -rf node_modules
npm install gulp-sass
```
