### ISSUE TITLE
Use latest npm in AppVeyor

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#996]
For 3.2.0 we had to lock to npm@2.7.5 (https://github.com/sass/node-sass/pull/995) to work around an npm regression with Windows (https://github.com/npm/npm/issues/8517).

Once this is resolved we should revert #995.

**Comment by saper** [comment]
[We have a suggestion](http://help.appveyor.com/discussions/problems/2347-npm-275prefer-global-warning-causes-failure-command-executed-with-exception#comment_37223989) from @FeodorFitsner not to use PowerShell to invoke npm. Any thought on that @am11 (we did to fix AppVeyor in c64d596bd2139b1e1692795dcf127430910c222a) ?

**Comment by am11** [comment]
@saper, you are right. I think we need to change:

```yaml
- ps: npm install --msvs_version=2013
```
to:
```yaml
- npm install --msvs_version=2013
```

https://github.com/sass/node-sass/pull/844#discussion_r29990660

**Comment by saper** [comment]
Thanks @am11, looks like #1024 fixes that problem indeed.

**Comment by saper** [comment]
A hopefully proper fix for npm: https://github.com/npm/npm/pull/8841

**Comment by xzyfer** [comment]
@saper if you feel this is fixed by #1024 feel free to close this issue.

**Comment by xzyfer** [comment]
Fixed by 1024

**Comment by saper** [comment]
Will be fixed in npm soon, hopefully :)

**Comment by xzyfer** [comment]
This has been fixed upstream in npm :tada:
