### ISSUE TITLE
malformed URL Error

### ISSUE THREAD

**Issue by codeuniquely** [sass/node-sass#999]
I have a very simple fonts.scss included in my project that references a font from Google

    @import url(//fonts.googleapis.com/css?family=Roboto:400,500,700,400italic);
    html {
      font-family: roboto, arial, helvetica, sans-serif;
    }

but this generates the following error

    [06:35:20] { [Error: src\client\scss\fonts.scss
      1:9  malformed URL]
      message: 'src\\client\\scss\\fonts.scss\n  1:9  malformed URL',
      column: 9,
      line: 1,
      file: 'F:/Projects/Upload/src/client/scss/common/fonts.scss',
      status: 1,
      messageFormatted: '\u001b[4msrc\\client\\scss\\fonts.scss\u001b[24m\n\u001b[90m  1:9\u001b[39m  malformed URL',
      name: 'Error',
      stack: 'Error: src\\client\\scss\\fonts.scss\n  1:9  malformed URL\n    at options.error (F:\\Projects\\Upload\\node_modules\\node-sass\\lib\\index.js:276:32)',
      showStack: false,
      showProperties: true,
      plugin: 'gulp-sass' }

If I remove the reference to googleapi and just do this

    html {
      font-family: arial, helvetica, sans-serif;
    }

Then everything generates without error - but I obviously don't get the font I want.

**Comment by saper** [comment]
which version of node-sass and libsass are you running? Check out https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md for help.

**Comment by codeuniquely** [comment]
node -v
    v0.12.4

npm -v
    2.11.1

node-sass
  "name": "node-sass",
  "version": "3.1.2",
  "libsass": "3.2.4",

**Comment by saper** [comment]
Thanks, I can reproduce it here, looks like a libsass regression

**Comment by xzyfer** [comment]
Tracking this in Libsass https://github.com/sass/libsass/issues/1298. For now you can work around this by quoting the URL.
